### ISSUE TITLE
Add file and add folder dialog can be opened at the same time

### ISSUE THREAD

**Issue by Marton6** [processing/p5.js-web-editor#1003]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: On Chrome
- Operating System: Linux and Windows
- Steps to reproduce this bug:
    1. Click add folder option in the file navigator
    2. Click add file option in the file navigator

Being logged in makes this stand out even more since the add file dialog will be larger and partially visible under the add folder dialog.

It might be a good idea to disallow interaction with the rest of the page when a dialog is open or to dismiss the dialog when the user clicks outside of it. Similarly to the settings dialog.

**Comment by catarak** [comment]
thanks for reporting! i agree that the interaction with the add file/add folder dialogs is weird.

**Comment by siddhant1** [comment]
I agree on this as well , dialog boxes and modals should close on leaving focus

**Comment by shakeabi** [comment]
I think this can be implemented by adding a layer between the modal and the ide or by setting a state key and disabling the interactions with the interface. I believe that there exists a key already to denote whether a modal is open or not. Which method is better? @catarak

**Comment by catarak** [comment]
i think, also, these could be combined into one modal.

**Comment by ashu8912** [comment]
Yes @catarak modals are related to the ui state and all ui related state should live in the component itself and not in redux store.

**Comment by ashu8912** [comment]
Will send a pr if you want to make these changes

**Comment by neelesh7singh** [comment]
@catarak what is understand is the new folder/file model should close whenever we click anywhere else, pluse the new file and new folder model should not be opened at the same time. 
Is this correct??

**Comment by catarak** [comment]
@neelesh7singh that is correct!
