### ISSUE TITLE
Gray Text on White Background is not WCAG compliant

### ISSUE THREAD

**Issue by prcoy** [processing/p5.js-web-editor#1004]
#### New feature details:

Screenshot of WAVE extension, which has 51 contrast errors.
![editor P5js](https://user-images.githubusercontent.com/7294437/55185692-46a3c800-516b-11e9-9142-83713039710a.png)

[Contrast Reference](webaim.org/resources/contrastchecker)

Colors could be updated to be AA compliant (and the high contrast theme can be AAA compliant).

**Comment by catarak** [comment]
thanks for pointing out these design issues. i would request in the future that you refer to the [p5.js community statement](https://p5js.org/community/) in submitting issues. this project is worked on by humans who are trying their best, who are dedicated to keeping this project free and open source, who deserve respect. 

you are welcome to make a pull request to suggest changes you think are important.

**Comment by prcoy** [comment]
The title was simply a reference to a popular internet meme. I'm sorry you took offence. My apologies to all involved.

--
 Securely sent with Tutanota. 



Mar 28, 2019, 3:30 PM by notifications@github.com:

**Comment by catarak** [comment]
thanks for the apology, and i hear you that it was not your intention to be disrespectful.

**Comment by siddhant1** [comment]
@catarak is this high priority , if yes, I can have a look

**Comment by catarak** [comment]
@siddhant1 this is an issue that needs design input, so i would wait on it.

**Comment by ashu8912** [comment]
@catarak still waiting for designs?

**Comment by catarak** [comment]
fixed by #1406!
