### ISSUE TITLE
Fix Colors in "Add Folder" dialog box

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1005]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

On hover, Color of the button should change and error message colour should be displayed according to the theme set.

![Capture](https://user-images.githubusercontent.com/28510494/55193296-8fd83400-51cc-11e9-9a17-13f063f782ed.PNG)

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

I am working on this.

**Comment by catarak** [comment]
thanks for reporting!

**Comment by catarak** [comment]
hmmm, i don't know if the error should be the logo color! i think for this ticket, a new color should be defined that's like, "error color" that's a red color that has a good contrast with the black background.

**Comment by plxity** [comment]
@catarak Yeah, showing red color would be a nice idea. I will make the changes. :)
