### ISSUE TITLE
Feature : Change setting's page UI as per the selected theme.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1006]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### Feature enhancement details:
The current theme is : 

![Capture](https://user-images.githubusercontent.com/28510494/55193469-13922080-51cd-11e9-916a-8a7c85095c2e.PNG)

The present UI of the settings page looks like:
So I think if we change the settings page UI according to the theme set it will look better

![Capture](https://user-images.githubusercontent.com/28510494/55193562-53590800-51cd-11e9-9008-07f568e68fa4.PNG)

#### New feature details:

**Comment by plxity** [comment]
@catarak What do you think about this? :)

**Comment by catarak** [comment]
i'm hoping to move a few pages to being overlays, rather than full screen views, including this one. i would hold off for the moment 😸

**Comment by plxity** [comment]
@catarak  oh okay, so should I close this one?

**Comment by catarak** [comment]
yeah, i think this will probably get fixed when that fix happens.
