### ISSUE TITLE
Error while "npm run start"

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1007]
![Capture](https://user-images.githubusercontent.com/28510494/55252028-dfc00500-5277-11e9-8cf2-e9c4cb803a6d.PNG)

I updated my codebase to work on an issue and getting this error while the app is starting.

**Comment by plxity** [comment]
Can anyone help?

**Comment by meiamsome** [comment]
Did you re-run `npm install`?

**Comment by plxity** [comment]
@meiamsome Thank you so much :)
