### ISSUE TITLE
Drag file text missing when theme is changed.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1009]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
In the light theme text is present.

![image](https://user-images.githubusercontent.com/28510494/55256837-23207080-5284-11e9-8749-87caf4f3c3f0.png)

But in dark theme it is not visible.

![Capture](https://user-images.githubusercontent.com/28510494/55256948-798daf00-5284-11e9-90b3-bee24d9d241f.PNG)

- Web browser and version: Chrome
- Operating System: Windows 10
- Steps to reproduce this bug:

#### New feature details:

**Comment by plxity** [comment]
It is present but the font color is not appropriate that's why it is invisible.

**Comment by siddhant1** [comment]
#946 resolves this

**Comment by plxity** [comment]
@siddhant1 Cool.
