### ISSUE TITLE
Sketch Naming

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#101]
A source of confusion for students was naming sketches (when to name them, many sketches with the same name, etc).   Again, this may need to wait until after the design review, but here are some thoughts that came up in class.
1.  Sketch names for a user account have to be unique.  This would also help with #68 so that each sketch can have a url like `/username/sketch-name/`.
2. When you "duplicate" or "save as" you are prompted to name the sketch (with the previous name filled in already.)
3. When you make a "new" sketch, you are prompted to name the sketch or it is named with something automatic perhaps date and time related?
4. Whenever you name a sketch, a save action is performed?  I'm not sure about this, but this was the expectation of some users.   Maybe irrelevant if we force naming and save on the creation of a new sketch anyway.

**Comment by REAS** [comment]
For reference for #3, the Processing format is "sketch_YYMMDDa." This could be one of many options to consider. I do prefer a default sketch name instead of forcing someone to make the decision when "new" is selected.
