### ISSUE TITLE
Option to add files and folders without going to the nav bar

### ISSUE THREAD

**Issue by abhinavsagar** [processing/p5.js-web-editor#1010]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
There should be a way to add files and folders by just right clicking in the files and folders already present. This feature is commonly used in IDE's and I think users would prefer this rather than going back to nav bar every time.

**Comment by plxity** [comment]
@abhinavsagar I think this would be a great feature to implement.

**Comment by anku255** [comment]
I am a little confused about "option to add new files/folders by right clicking on the existing file/folders".

Right clicking on a folder in the sidebar already presents an option to create a file/folder within that folder.

![image](https://user-images.githubusercontent.com/22813027/55383067-e33be080-5544-11e9-9894-f957ea3d25c9.png)

Can you please clarify your suggestion?
