### ISSUE TITLE
When clicked anywhere inside the model the automatically closes.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1014]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
![Capture](https://user-images.githubusercontent.com/28510494/55490073-bf65c100-5650-11e9-977c-43d3069193f7.PNG)

Whenever clicked anywhere in the modal, lt automatically closes.
- Web browser and version: Chrome
- Operating System: Windows 10.
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment]
i'm not able to reproduce!

**Comment by anku255** [comment]
I am not able to reproduce this bug on Windows 10/Chrome as well.

**Comment by plxity** [comment]
@catarak Go to Edit->File Next and then a modal opens and click anywhere on it.

**Comment by anku255** [comment]
@plxity Okay. Seems like the bug is present in *Find Next Modal* and not in *Find Modal*.  If you are not working on this then I would like to fix this.

**Comment by catarak** [comment]
i can reproduce!

**Comment by plxity** [comment]
@anku255 I am working on it.

**Comment by plxity** [comment]
@catarak I have a suggestion. Apparently, we don't need 'find next' and 'find previous'. We already provide an option to users to find next/previous matched word in the 'find' modal.  have never seen options like these in the navbar. What do you think?
Just for reference: This is the edit menu of visual studio code editor.
![Capture](https://user-images.githubusercontent.com/28510494/55585917-688de380-5745-11e9-94c0-ef550e665552.PNG)

**Comment by catarak** [comment]
on other applications, it does appear though (e.g. Chrome):
<img width="456" alt="Screen Shot 2019-04-05 at 11 39 47 AM" src="https://user-images.githubusercontent.com/6063380/55639533-98fe6d80-5797-11e9-9fe4-9630f8d728ca.png">

**Comment by ashu8912** [comment]
Hey @catarak i think @plxity  is right here we can remove the find prev and find next thing for now and can show the find modal button for all button shortcuts,
Its because this is a problem with codemirror itself and we can't override that behaviour

**Comment by ashu8912** [comment]
If you want i can send in a pr that removes those options or would love to make any other change that you recommend
