### ISSUE TITLE
Line 0 error

### ISSUE THREAD

**Issue by todonnell7** [processing/p5.js-web-editor#1016]
#### Nature of issue?

- Found a bug
Maybe its not so much a bug as some other glitch but code that was running fine a few days ago is now often not running - am seeing the following error:

Script error. (: line 0)

Was also trying to edit some old examples to share with a new class today and at one point just could not edit it any more due to freeze ups- 

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by anku255** [comment]
@todonnell7 Hi! Would it be possible for you to share the code for us to take a look?

**Comment by todonnell7** [comment]
Thanks, I figured it out - for some reason all the accounts have tripped the

Accessible text-based canvas

switches ... odd but we were able to get our work done today.

Thank you for responding so fast.


Tom O'Donnell

Computer Science Teacher

IS 220, John J. Pershing

4812 9th Ave

Brooklyn, NY 11220

(718) 633-8200


“The end of a melody is not its goal: but nonetheless, had the melody not reached its end it would not have reached its goal either. A parable.”

― Nietzche





________________________________

**Comment by catarak** [comment]
thanks for reporting @todonnell7! i've noticed that folks have accidentally been turning on these features and i've been trying to pin down why. i removed a misleading interaction yesterday—keep me updated if it keeps coming up!

**Comment by catarak** [comment]
@todonnell7 fyi i just removed your personal information from this issue—if you reply to a Github issue via email, your email signature gets included!
