### ISSUE TITLE
Instance Mode no longer supported/broken

### ISSUE THREAD

**Issue by SacuL** [processing/p5.js-web-editor#1017]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: On Chrome Version 73.0.3683.86 (Official Build) (64-bit)
- Operating System: Windows 7
- Steps to reproduce this bug:
Open online editor. File > Examples. Choose "Instance Mode : Instantiating". Hit Play.
Error on console:  "Script error. (: line 0)"

#### Description:

Up until yesterday I used to write all my sketches using Instance Mode but now they are no longer working. I was looking for a problem on my code but even the examples are no longer working for me.

**Comment by catarak** [comment]
thanks for reporting! can you go into your settings (the cog icon) and then accessibility, and see if any of the accessible outputs are on?

**Comment by SacuL** [comment]
"Lint warning sound" is off and Sound is checked for "Accessible text-based canvas"

**Comment by SacuL** [comment]
Turning Sound off makes everything works again =D

**Comment by catarak** [comment]
i'm glad that fixed it! do you remember turning that setting on, or did you turn it on accidentally?

**Comment by SacuL** [comment]
I certainly didn't turn it on. Is there a keybind I might have accidentally pressed?

**Comment by catarak** [comment]
i'm thinking that's the case. issues similar to this one have popped up with some regularity, and i'm trying to pinpoint how users are accidentally turning it on.

**Comment by SacuL** [comment]
Well yesterday I was running my sketch on this very low end notebook and at some point the thing simply froze. I remember pressing a few keybinds, like ctrl+w, trying to close the window without success. I had to reboot using the power button. I can't remember if the problem happened right after turning the notebook on again or some time after. 

Anyway thank you for the quick reply and let me know if you need more info/help to figure this out.

**Comment by catarak** [comment]
thank you, that's helpful!

**Comment by catarak** [comment]
since this has been popping up so much, and because of a bug that turned on these features by default, i decided to run a DB command to turn this off for all users. they can obviously be turned on again, but hopefully this will fix the instances in which users accidentally have turned it out, and i can start fresh and get a better sense of how users are turning this on.
