### ISSUE TITLE
"Uncaught TypeError object.function is not a function" when copy/pasting to new editor

### ISSUE THREAD

**Issue by mattertater** [processing/p5.js-web-editor#1018]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 
   - Google Chrome | 73.0.3683.86 (Official Build) (64-bit) (cohort: Stable)
   - Revision | f9b0bec6063ea50ce2b71f5b9abbae7beee319a6-refs/branch-heads/3683@{858}
- Operating System: 
  - Windows 10
- Steps to reproduce this bug
  - Write code with object containing a function, run to see it working, then copy/paste to new editor and see that it no longer sees that function. 

I came across this while teaching a lesson, then giving the students the code to paste into their editor. I got numerous responses saying it doesn't work, then made this simple code to only include the bug we came across- 
```
var a;

function setup() {
  a = new Thing();
}

function draw() {
  a.show();
}

function Thing() {
  this.show = function() {
    ellipse(50, 50, 20, 20);
  }
}
```

When typing this out in one editor, things work fine. When copy/pasting this code to another editor, "Uncaught TypeError: a.show is not a function (sketch: line 8)" comes up. It seems to still display the ellipse, meaning it ran the function

**Comment by catarak** [comment]
thanks for reporting! do you have any of the accessibility features enabled? you can check this by clicking on the "Preferences" icon (the cog), and then clicking on the "Accessibility" tab.

**Comment by mattertater** [comment]
Lint warning sound is off, and all of the "Accessible text-based canvas" options are checked. 

If it means anything, I've also just found out that the error only pops up when I am NOT logged into my account.

**Comment by catarak** [comment]
i would try turning off all of the accessible options, and see if that fixes it!

**Comment by catarak** [comment]
i just noticed that all of the accessible options are being turned on by default—will investigate!

**Comment by mattertater** [comment]
Turning them all off worked for the test code in this issue, and the longer code I had the problem with originally. Thank you!

**Comment by catarak** [comment]
fixed and merged—will be deployed in ~10 min
