### ISSUE TITLE
Script error. (: line 0)

### ISSUE THREAD

**Issue by Shreevathsa99** [processing/p5.js-web-editor#1020]
![Screenshot from 2019-04-07 17-16-51](https://user-images.githubusercontent.com/45475433/55683074-2fc65800-5959-11e9-924c-3500f972b616.png)

#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by dhruvdutt** [comment]
@Shreevathsa99 It's bad to hear about such issues. Can you please send a reproducible snippet for the issue so we can debug and resolve it?

**Comment by catarak** [comment]
@Shreevathsa99 thanks for reporting! could you try turning off the accessibility features and see if this still comes up? there was a bug that was turning them on by default. you can turn them off by going to preferences (the cog icon) -> accessibility -> unchecking everything.

**Comment by catarak** [comment]
@Shreevathsa99  i actually ran a database command to reset this, so it shouldn't be an issue anymore!
