### ISSUE TITLE
Feature request: A mini-tutorial tour of the editor

### ISSUE THREAD

**Issue by shakeabi** [processing/p5.js-web-editor#1022]
#### Nature of issue?

- New feature request

#### New feature details:

It would be really helpful to beginners if there was a mini guided tutorial when a user first uses the editor, explaining all the options and their functions. Something like this ([link](https://react-joyride.com/)).

@catarak What are your thoughts on this?

**Comment by shakeabi** [comment]
P.S. I would like to work on it. :)

**Comment by catarak** [comment]
@shakeabi this is a great idea! i think this is captured as #806.
