### ISSUE TITLE
 Getting "TypeError: Interceptor.getColorName(...) is undefined," only when editing for saving

### ISSUE THREAD

**Issue by greggelong** [processing/p5.js-web-editor#1024]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Starting 4/19/2019 10am Beijing time,
I started getting a, 
 TypeError: Interceptor.getColorName(...) is undefined,
when passing a color to a class.  

The error started on code that previously ran without a problem.
I found however if I use the share option and view it in another tab it runs error free.
(It also runs locally on my browser if I download the files)
It only give the error if the code is open for editing and saving while the preview window open.

I am using Firefox browser
Microsoft Windows 7 Ultimate

Here is a link to the code:
https://editor.p5js.org/greggelong/sketches/A5vX2s8eL
You will need to duplicate it and open it for editing and saving in your account to reproduce the error.

Showing the error when open for editing and saving
![Firefox_Screenshot_2019-04-09T20-26-33 143Z](https://user-images.githubusercontent.com/37335796/55775231-4057fa80-5a4d-11e9-8e83-5cf0c952bcf0.png)

but running when shared
![Firefox_Screenshot_2019-04-09T20-27-50 352Z](https://user-images.githubusercontent.com/37335796/55775230-3fbf6400-5a4d-11e9-96e2-de4fdf10ec8e.png)

**Comment by catarak** [comment]
@greggelong thanks for reporting! can you try turning off the accessibility features? you can do this by going to preferences (the cog icon) -> accessibility -> uncheck everything. there was a bug a few days ago in which these features were being turned on by default, which i fixed.

**Comment by catarak** [comment]
@greggelong  i actually ran a database command to reset this, so it shouldn't be an issue anymore!

**Comment by greggelong** [comment]
@catarak Thanks! Working great now!
