### ISSUE TITLE
default name generator produces upsetting results (content warning for language in thread)

### ISSUE THREAD

**Issue by aparrish** [processing/p5.js-web-editor#1026]
The default name generator introduced in #184 often produces upsetting results. For example, just now when creating a new sketch I looked up to find it was named `abusive dad`. A quick glance at the list of [adjectives](https://github.com/aceakash/project-name-generator/blob/master/src/adjectives.js) and [nouns](https://github.com/aceakash/project-name-generator/blob/master/src/nouns.js) in `project-name-generator` (the dependency used to generate the name) turns up a number of words that could create uncomfortable and/or harmful juxtapositions. Without even reading through the entire list, I can see terms that are often (or exclusively) used in ableist and sexist language.

When teaching classes with the editor, I have sometimes needed to quickly change the randomly-generated name—usually it's cute and amusing, but sometimes it's awful.

Jenn Schiffer of Glitch has put a lot of work into curating a list of friendly words specifically to mitigate this issue in default project naming: https://github.com/FogCreek/friendly-words I wonder if this list could be integrated into the p5js web editor as well?

**Comment by catarak** [comment]
thanks for reporting! wow, yes, there are some not so great words in there. i think it's a great idea, and would be super simple to move to the Glitch friendly words.

**Comment by catarak** [comment]
just pushed a fix, to be deployed in ~10 min when the CD finishes running

**Comment by aparrish** [comment]
wonderful, thank you <3
