### ISSUE TITLE
Mismatching of colors.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1029]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System: Windows 10
- Steps to reproduce this bug:
1) Change the theme of the editor
2) Go to Login route
3) Click on Login with GitHub
 As a user clicks on the button, the onClick event sets the color to pink. Even if the theme is High Contrast. 

#### New feature details:

**Comment by catarak** [comment]
thanks for reporting! in general, i think the theming isn't right for the login/signup views with the web editor.

**Comment by plxity** [comment]
@catarak I would like to take up this issue.

**Comment by catarak** [comment]
@plxity i would hold off. i would like to move the login/signup screens from full-screen views to within a modal overlay, which i think will fix this issue.

**Comment by plxity** [comment]
@catarak Okay sure, no issues :)

**Comment by catarak** [comment]
fixed by #1340.
