### ISSUE TITLE
Misaligned dialog box

### ISSUE THREAD

**Issue by abhieshekumar** [processing/p5.js-web-editor#1030]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
- Steps to reproduce this bug
   - Goto Edit > Find on the menu bar.
   - Goto Sketch >  Add Folder on the menu bar.
   - The respective dialog boxes will pop-up. The 'Find' dialog box is aligned to the centre of the web page but the 'Add Folder' dialog box is not aligned to the centre of the web page. The same behaviour is shown by the 'Add File' dialog box.

![webEditor-Issue](https://user-images.githubusercontent.com/24494390/56056349-87116180-5d79-11e9-84ca-7eab8bbe8f22.png)

**Comment by abhieshekumar** [comment]
I would like to work on this issue.

**Comment by catarak** [comment]
thanks for reporting! yes, these dialogs should be centered on the page.

**Comment by abhieshekumar** [comment]
now, working on this one

**Comment by dylsteck** [comment]
Is this issue fixed or is this something I can help try to fix?

**Comment by catarak** [comment]
@dylsteck there's an open PR so I suggest working on something else!
