### ISSUE TITLE
Focus on choosing option in find menu

### ISSUE THREAD

**Issue by nimishagarwal76** [processing/p5.js-web-editor#1034]
#### Nature of issue?

- Found a bug
#### Details about the bug: 
Clicking on search specifiers causes the editor lose focus from the search box. 

Most of the editors retain focus in the search box on clicking these specifiers (eg. VS Code). We can have that too. @catarak  what are your views on it.

![Screenshot (5)](https://user-images.githubusercontent.com/37630020/56083802-8e06a580-5e47-11e9-8480-8125f6d48efd.png)

**Comment by catarak** [comment]
thanks for reporting! i think we have to be careful here with respect to mouse vs. keyboard users. i noticed that on VSC, when you tab into those options, it does change focus. so yes, the focus should stay on the input box, but only if you click on one of the options using your mouse.
