### ISSUE TITLE
Display model instead of alert.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1035]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: WIndows 10
- Steps to reproduce this bug:

#### Feature enhancement details:

![Capture](https://user-images.githubusercontent.com/28510494/56084084-6dd8e580-5e4b-11e9-86e3-208d837b7746.PNG)

When a user tries to delete the project, the model should be displayed instead of alert. It looks more professional to introduce a model and when the project is finally deleted, display a toast saying "Project Deleted" as a confirmation.

#### New feature details:

**Comment by siddhant1** [comment]
Yeah! I think this can be improved

**Comment by plxity** [comment]
I am working on this. once @catarak approves this.

**Comment by catarak** [comment]
from what i have seen, this is common practice, to use an `alert` window in this case.
