### ISSUE TITLE
Responsiveness for settings overlay

### ISSUE THREAD

**Issue by Shubhanshu88** [processing/p5.js-web-editor#1036]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

The settings overlay is not responsive for both landscape and portrait view, 
 - The solution for portrait view might be to increase width of the overlay for mobile devices or to keep the general settings and accessibility tab as column display for small screens
- The solution for landscape view would be to set a minimum or fixed height
![overlay_1](https://user-images.githubusercontent.com/42772987/56151846-d18c1b80-5fcf-11e9-8cdf-93e106438ec2.png)
![overlay_2](https://user-images.githubusercontent.com/42772987/56151847-d2bd4880-5fcf-11e9-9219-7636166245f5.png)

**Comment by Shubhanshu88** [comment]
@catarak could you give some suggestions?

**Comment by siddhant1** [comment]
I don't think the entire editor is responsive now, I think we can make few prs to make it responsive

**Comment by shakeabi** [comment]
Yeah, currently very few elements of the page are responsive. Thus, as @siddhant1 said, this task must be broken down into various prs. For this particular settings component, I think the component filling up the whole screen will look better in small screens.

**Comment by abhieshekumar** [comment]
Designs for responsive design [Link](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3)

**Comment by catarak** [comment]
i agree with @shakeabi, that the component should fill the whole page on mobile.
