### ISSUE TITLE
In-editor p5 references (exposed Doc Comments)

### ISSUE THREAD

**Issue by bit-wise** [processing/p5.js-web-editor#1038]
#### Nature of issue?

- New feature request

#### New feature details:
Integration of the p5 reference material into the p5 editor. A common IDE feature is to have a reference lookup of the currently focused function -- providing a short description along with available parameters (usually provided by some sort of Doc Comments).

**Comment by catarak** [comment]
thanks for the suggestion, and yes, i think this is a great idea! i think there's an open issue about this but i can't find it at the moment.

**Comment by qualitymanifest** [comment]
Looks like this is the related issue https://github.com/processing/p5.js-web-editor/issues/99

**Comment by catarak** [comment]
@qualitymanifest yes thank you!

**Comment by catarak** [comment]
i'm gonna mark this as a duplicate and fold it into #99.
