### ISSUE TITLE
Move location of notification bar

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1040]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

in my opinion, i don't like the location of the notification bar. i miss seeing it all of the time, and the location to me feels kind of random. i think it should be at the top, in the center.

**Comment by plxity** [comment]
@catarak Can you explain in brief? Which notification bar are you referring?

**Comment by catarak** [comment]
the one that comes up when a user saves a sketch!
