### ISSUE TITLE
Displaying a play symbol

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1041]
#### Nature of issue?

- New feature request

#### Feature enhancement details:
![11](https://user-images.githubusercontent.com/28510494/56319583-b829d180-617f-11e9-9a76-910c469897a5.PNG)

I think adding a play symbol before ' preview sound ' will make it look better.
@catarak What do you think about this? 

#### New feature details:

**Comment by AnkurIngale** [comment]
I'll suggest just put a play icon and give hint as preview sound.

**Comment by plxity** [comment]
@AnkurIngale Yeah, you are right. Just waiting for @catarak views on this.

**Comment by catarak** [comment]
honestly, this feels pretty low priority, and in my opinion, i don't think it's necessary.
