### ISSUE TITLE
cross origin problem

### ISSUE THREAD

**Issue by tomlecoz** [processing/p5.js-web-editor#1048]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  on every browser
- Operating System: on every OS
- Steps to reproduce this bug:

go here https://editor.p5js.org 
And try to load an image located somewhere on internet

#### Feature enhancement details:

Please just add the property "crossOrigin" and set it to "anonymous" for every file you want to load 

for example 
var img = document.createElement("img");
img.crossOrigin = "anonymous";
img.src = "https://pbs.twimg.com/profile_images/502135348663578624/-oslcYof.png" 

the same for the sound, the video, the font, the file 

This is the only thing you have to do to get it work, please do it, it can be done in 15 minutes , just look for ".src=" in the whole project and add a the crossOrigin-code just before.

Thank you

#### New feature details:

**Comment by shakeabi** [comment]
@tomlecoz I believe this is related to #912 . There's a temporary solution in the comments that you can try.
However, @catarak is the solution suggested by @tomlecoz feasible?

**Comment by shakeabi** [comment]
If so, I'll fix it.

**Comment by shakeabi** [comment]
My bad. This seems like an in-project fix.

**Comment by catarak** [comment]
@tomlecoz thanks for reporting! i'm slightly confused about the context for this issue—is there something specific you were trying to do that you that this solves? also, I recommend using the [p5 DOM library](https://p5js.org/reference/#/libraries/p5.dom) rather than using `document.createElement`, when using the DOM with p5.js.
