### ISSUE TITLE
Duplicated sketches no longer save after an image upload

### ISSUE THREAD

**Issue by aiboyles** [processing/p5.js-web-editor#1052]
#### Nature of issue

- Found a bug

#### Details about the bug: 

- Steps to reproduce this bug:
1) Take an existing sketch and duplicate it.
2) Upload a file, such as an image. (Either from the left hand side menu, or the Sketch > Add File option from the menu). 
3) Try to save the sketch (File > Save).

The sketch will not save. An pop up message box often appears that says:
"Error: The project you have attempted to save has been saved from another window. Please refresh the page to see the latest version."

I noticed this issue starting to occur a couple of weeks ago, perhaps around April 8th.
![Screen Shot 2019-04-24 at 9 11 32 AM](https://user-images.githubusercontent.com/8883830/56675790-cf7e2880-6671-11e9-8e46-d41090ba6bab.png)

**Comment by catarak** [comment]
Thanks for reporting! This is a bug caused by a recent pull request, https://github.com/processing/p5.js-web-editor/pull/1039.
