### ISSUE TITLE
Cross button on notifications.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#1054]
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 
I do not understand the need for the cross button on notifications. I mean, they disappear before you can click on it. Although it's a low priority one, we should give it a thought. 
- Web browser and version: On Chrome
- Operating System: MacOSX

**Comment by plxity** [comment]
@AnkurIngale No, It's not like this. It is basically a toast component. we can't keep it for longer on a screen and it stays on screen for around 2 Seconds. It gives enough time to the user to press the close button.
I think this behaviour is fine.
