### ISSUE TITLE
Add script to generate syntax highlighting files

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1056]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

#978 was recently fixed, which fixed certain p5.js keywords not being highlighted. I would like to automate this process by pulling from https://p5js.org/reference/data.json.

This issue involves writing a script that generates the [p5-javascript.js](https://github.com/processing/p5.js-web-editor/blob/master/client/utils/p5-javascript.js) file from https://p5js.org/reference/data.json.

**Comment by siddhant1** [comment]
Cool ! I will have a look at this later .
In the meantime if anyone wants to pick this up , go ahead .

**Comment by singhvisha** [comment]
Hi, I want to work on this issue.
Is it open?

**Comment by singhvisha** [comment]
hi,if it is still an issue,Please allow me to fix.

**Comment by siddhant1** [comment]
Go for it!

**Comment by singhvisha** [comment]
Hi,Could you please help me how to approch?

**Comment by siddhant1** [comment]
@catark has provided the link above , I think you can look at 
https://github.com/processing/p5.js-web-editor/blob/master/client/utils/p5-javascript.js

**Comment by catarak** [comment]
@singhvisha go ahead and work on this! you'll need to parse the `data.json` file, pull out the p5.js keywords, and then dump them into the `p5-javascript.js` file by making a template file to insert them into. let me know if you need more help!

**Comment by SGeetansh** [comment]
Hi, is anyone already working on this issue? I'd like to give it a shot, if not.

**Comment by catarak** [comment]
@SGeetansh go ahead and work on this!

**Comment by simranaggarwal1999** [comment]
Hey! I s this issue still open? Can I work upon this issue? @catarak

**Comment by simranaggarwal1999** [comment]
@catarak Kindly assign me an issue. Thanks!

**Comment by SGeetansh** [comment]
@simranaggarwal1999 I started working on somethng else meanwhile. You go ahead if you want to. Best of luck!

**Comment by ashu8912** [comment]
@catarak can you guide a little please on how to start working on this issue

**Comment by adrijshikhar** [comment]
@catarak i would like to work on this issue, can you please assign it to me?

**Comment by devashish1099** [comment]
@catarak where should i add the request for json file

**Comment by thegitone23** [comment]
I would like to work on this issue, if it's still not done.

**Comment by thegitone23** [comment]
Can someone have a look at [this gist](https://gist.github.com/thegitone23/1939f65ffe544ddafb3b6363e7a108fd)

**Comment by catarak** [comment]
Go ahead! No one else is working on it at the moment.

**Comment by thegitone23** [comment]
@catarak  I have written a simple script, [here is the gist](https://gist.github.com/thegitone23/1939f65ffe544ddafb3b6363e7a108fd), I have tested that it captures all the function names and keywords already existing in the code base and also many new ones defined in data.json file. It would be great if you can have a look.

**Comment by catarak** [comment]
Amazing work @thegitone23, thank you! I think this is a great start. What I would recommend you do next is:
1. Rather than using a local data.json, have it pull from the p5.js website url. [request](https://www.npmjs.com/package/request) is already a dependency in the web editor so you could use that library. 
2. Create a template version of [p5-javascript.js](https://github.com/processing/p5.js-web-editor/blob/master/client/utils/p5-javascript.js) that will allow you to inject those keywords.
3. Write code that reads `p5-javascript.template.js`, inserts the keywords into the right place, and then writes the resulting string to the file `p5-javascript.js`.

**Comment by thegitone23** [comment]
Thank You @catarak  .. I will start working on the next part accordingly ..
