### ISSUE TITLE
Sketch won't open

### ISSUE THREAD

**Issue by TFLGamer** [processing/p5.js-web-editor#1061]
I have encountered an issue where one of my sketches won't open. 

Whenever I try to open one of my sketches it loads up a blank web page with the URL still being correct, however the name of the sketch appears to change to something random every time I retry opening it. This only occurs with one of my sketches, the rest work normally. I've been using a Chromebook.

Link to Sketch: 
https://editor.p5js.org/16343tg@hvhs.school.nz/sketches/8AXhnkAss

Is there any way to recover my sketch data if it has been lost?

**Comment by catarak** [comment]
@TFLGamer thanks for reporting! i will investigate.

**Comment by catarak** [comment]
just pushed a fix that will be deployed in ~10 min!
