### ISSUE TITLE
Images are opened as regular editable files.

### ISSUE THREAD

**Issue by abhieshekumar** [processing/p5.js-web-editor#1062]
#### Nature of issue?

- Found a bug - Maybe not necessarily a bug but definitely not the behaviour commonly expected by most users. 

#### Details about the bug: 

- Web browser and version: Google Chrome v74.0
- Operating System: Linux (Mint)
- Steps to reproduce this bug :
  - Click on Sketch > Add File
  - Import any image file. The image is imported and added to file-navigation.
  - Click on the image file.
  - The image is opened in the code editor as an editable text file. However, there is no problem in using the image file in index.html page or elsewhere.
  - This behaviour is not something what most programmers expect while others may claim that it can be used for documentation.

- A [sketch](https://editor.p5js.org/abhieshekumar@gmail.com/sketches/VxEA5vFs0) illustrating the issue.
  - The images used are `kitty.jpg` and `cat.png`.

**Comment by catarak** [comment]
thanks for reporting! this is currently captured as #57. i think this should be bumped up in priority!

**Comment by catarak** [comment]
i'm going to close this as a duplicate.
