### ISSUE TITLE
Uncaught ReferenceError: Ene is not defined (sketch: line 8)

### ISSUE THREAD

**Issue by JoAraujo** [processing/p5.js-web-editor#1064]
Hi, i'm trying to do a space invaders in p5js web, and i'm started to programming recently, and i'm having a problem, the title is the problem, i already created a new file " ene.js" but i can't see where is the error, please help
(if my english do not sounds good, i'm Brazilian.)
Here's the code: 
`
var nav; 
var enes = [];

function setup() {
  createCanvas(700, 500);
  nav = new nav();
  for (var i = 0; i < 5; i++) {
   enes[i] = new Ene(random(width), 20);
  }
}

function draw() {
  background(51);
  nav.show();
  for (var i = 0; i <5; i++) {
  enes[i].show();
  }
  
}
function keyPressed() {
  if (keyCode === RIGHT_ARROW) {
    nav.move(1);
  } else if (keyCode ===LEFT_ARROW) {
    nav.move(-1);
  }
}
`
And the code i used to ene:
`
function Ene(x, y) {
  this.x = x;
  this.y = y;
  
  this.show = function() {
    fill(255, 0, 200);
    ellipse(this.x, this.y, 60, 60);
  }
  
}
`
Thanks for the attention.

**Comment by JoAraujo** [comment]
Sorry i don't know how to compress the code

**Comment by piecesofuk** [comment]
Have you added a script tag in **index.html** that references ene.js? ie:
...
```
  <body>
    <script src="ene.js"></script>
    <script src="sketch.js"></script>
  </body>
```

...

**Comment by JoAraujo** [comment]
Yeah, i have added, i think so. Look: 
`<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.sound.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />

  </head>
  <body>
    <script src="nav.js"></script>
    <script scr="ene.js"></script>
    <script src="sketch.js"></script>
  </body>
</html>
`

**Comment by JoAraujo** [comment]
LOL, i have noticed that my script is wrong, "scr" and not "src", but thanks for the help. Newbie mistake

**Comment by catarak** [comment]
i'm glad you figured out the issue!

**Comment by JoAraujo** [comment]
Thanks!! Is that a lot to learning about programming haha, nothing that does not solve with pratice
