### ISSUE TITLE
Unable to view "full" mode sketches

### ISSUE THREAD

**Issue by piecesofuk** [processing/p5.js-web-editor#1065]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
When using the "share" option and selecting "full" mode, the sketch does not render. The P5 banner briefly appears at the top of the screen then disappears. The title of the page is two random words. For example, see https://editor.p5js.org/piecesofuk/full/_c9XIyc0V
Could be the same problem as closed issue #1057 ?
It works fine in "present" mode.

I can reproduce the problem in Chrome on a Chromebook and Firefox on Windows 10.

There are no console errors or network errors, and the sketch does seem to get downloaded if I look at the Chrome Dev Tools network events.

**Comment by SableRaf** [comment]
Same issue on Mac (Chrome, Safari, Firefox) and iOS (Safari & Chrome). The issue seems to be platform and browser independent. The page generates a new <Title> each time you reload.

**Comment by shiffman** [comment]
I can confirm this is happening too! Referencing #1057 where this was originally reported and maybe fixed for a period of time?

**Comment by catarak** [comment]
sorry about that! looking into it.

**Comment by catarak** [comment]
okay, i figured out the issue—it's redeploying now!
