### ISSUE TITLE
Add ability to highlight blocks of code and tab to increase indentataion – shift+tab to decrease indentation

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js-web-editor#1067]
#### Feature enhancement details:

In other editors, I find it incredibly helpful to be able to highlight selections of code and hit tab to increase the indentation or hit shift+tab to decrease the indentation.  Currently the editor replaces the code with a tab character. I believe that before we removed the indentation spacing from the users settings this behavior existed. Is there a way to bring this back with out that setting?

currently it's Ctrl-] (PC), Cmd-] (Mac)
I propose we map this to the tab key.

so on a new line, it will tab the line by one indentation unit
and on a selection, it will tab the whole selection by one indentation unit.

This is definitely a quality of life / personal preference thing, but it's a pretty typical default in text editors.

**Comment by catarak** [comment]
Shift + tab is currently mapped to code tidy (which I believed I pulled from CodePen), which also uses Cmd + [/Ctrl + [. Sublime Text and Glitch also use these shortcuts. Just to give you some background on where I pulled these keyboard shortcuts from. To me, this the de facto choices, but I am open to input and discussion about this.

**Comment by bmoren** [comment]
oh! I suppose that you're right. I didn't look wide enough! 

Atom's preference are that the Cmd + [ and tab both have the indent functionality. 

But, if this is the general trend then lets keep with where it's at.
_If_ we wanted to change anything in this case I'd say to map `tab` to indent on a highlight of selection and leave it at that?

**Comment by catarak** [comment]
i support mapping `tab` to indent a highlighted section! i just tried it in VSC and it worked, so it seems fairly standard.

**Comment by catarak** [comment]
I just made a [PR to add this feature](https://github.com/processing/p5.js-web-editor/pull/1174), however, <kbd>Shift</kbd> + <kbd>Tab</kbd> is mapped to "Code Tidy". There seems to be no consistency across editors what the keyboard shortcut for this is, and therefore I could change it, but I also feel like I can't change it at this stage in the game. Maybe I could add some analytics to see if folks actually use this keyboard shortcut? Maybe that's too complicated for a relatively small feature?

Anyway, all of this is to ask, does adding **just** <kbd>Tab</kbd> to indent feel like enough, or does it feel useless without <kbd>Shift</kbd> + <kbd>Tab</kbd> to unindent as well?

**Comment by bmoren** [comment]
per the conversation above <kbd>Command</kbd> + <kbd>]</kbd> can be used to decrease or opposite to increase, so the tab functionality on a highlighted section seems like a convenience mapping, and good enough in my book!

It seems like adding a tab for an additional loop or conditional statement is far more common than needing to remove indentation which might be a better candidate for tidying anyway!

**Comment by catarak** [comment]
okay, that makes sense! i'll merge in the PR then and leave it at that. thanks for your input!
