### ISSUE TITLE
Add collections across user accounts

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1068]
#### Nature of issue?

- New feature request

#### New feature details:

There's an open issue about collections within a user's account (#43), but I'd also like for there to be collections that can contain sketches from multiple accounts. Maybe they should have a different name, maybe not. I do think, however, that one user should be an "owner", and that they should be able to add sketches that they want, and other users could submit a sketch to a collection (and this could function like a "homework" submission too).

**Comment by andrewn** [comment]
Closing this as #1115 now has more detail about users being able to add any user's sketch to their own collections. #1117 has detail about user's being able to submit their sketches to someone else's collection.
