### ISSUE TITLE
Fix the "Text Size" input field.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1069]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

![Capture](https://user-images.githubusercontent.com/28510494/57351694-7c7f9780-7180-11e9-969e-d3f01d80f1df.PNG)

When a user accesses the input field, it doesn't allow the user to enter the value and when a user presses backspace it switches between values "8" and "16".

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

**Comment by plxity** [comment]
I will fix this up.

**Comment by catarak** [comment]
this is currently captured as #924.

**Comment by plxity** [comment]
@catarak  Okay no issues.
