### ISSUE TITLE
Mouse does not track correctly with WEBGL renderer

### ISSUE THREAD

**Issue by ajavamind** [processing/p5.js-web-editor#1074]
Bug: Mouse tracking with the WEBGL renderer display works differently than P2D.
This code should give same result when using WEBGL or default in createCanvas.

function setup() {
	createCanvas(800, 600,WEBGL);  // not ok
	//createCanvas(800,600);  // ok
	background(100);
}

function draw() {
	ellipse(mouseX, mouseY, 20, 20);
}

Browser Chrome on windows 10 pro
Google Chrome is up to date
Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by catarak** [comment]
thanks for reporting! i tried this code outside of the context of the web editor and i'm getting the same behavior, so i think this is related to the p5.js library itself. i'm going to move this issue over to that repository!
