### ISSUE TITLE
Implementing Redis in backend.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1078]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### Feature enhancement details:
As of now, Redis is not implemented in the backend. Implementing it would make the fetching of data fast.

#### New feature details:
@catarak What do you think?

**Comment by catarak** [comment]
you are suggesting using redis as a cache on top of mongo? i'm not sure how high priority this is—i have a feeling this will come up as the API features get built out, to make queries faster, but i think for now this is low priority.

**Comment by plxity** [comment]
@catarak Okay, but we can keep this as a feature which can be implemented.
