### ISSUE TITLE
sketch name in <title>

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#108]
I noticed in class that students often have many tabs open with several sketches.  It's hard to quickly see which is which.  Having the sketch name in `<title>` along with or instead "p5.js web editor" could be helpful?

**Comment by catarak** [comment]
Not sure why I can't assign this ticket, but @zhuoxi is working on it.

**Comment by catarak** [comment]
This shouldn't be too hard to do, with the use of [react-helmet](https://github.com/nfl/react-helmet).
