### ISSUE TITLE
Loading data from non-HTTPS sources

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#109]
I think this is related to https://github.com/vanevery/p5.serialport/issues/33.

I was helping a student with a homework using data from a "moon phase" API: http://api.usno.navy.mil/moon/phase?date=9/23/2016&nump=1

The following code:

```javascript
var data;
function preload() {
  data = loadJSON('http://api.usno.navy.mil/moon/phase?date=9/23/2016&nump=1');
}
function setup() {
}
```

results in this error:

<img width="579" alt="screen shot 2016-09-23 at 2 06 27 pm" src="https://cloud.githubusercontent.com/assets/191758/18796523/b44ea9de-8197-11e6-906d-3af83b70be28.png">

Is there anything we can do about this or is this something we have to live with for non HTTPS APIs?

**Comment by catarak** [comment]
I tried this example on codepen, and I noticed that to solve this issue, Codepen serves their site in both http and https, except for login/signup. As a quick fix, I can serve the site in both http and https, and turn off redirecting http to https, and then figure out the login stuff later.

**Comment by shiffman** [comment]
This can be closed now that amazing @catarak has enabled http and https. . . Just tested and the code works now! 🎉 🎉
