### ISSUE TITLE
There's no step-by-step installation guide for self-hosted local implementations

### ISSUE THREAD

**Issue by q2dg** [processing/p5.js-web-editor#1091]
I want to install this project to serve a private classroom seminar but I don't know where to start.
Thanks!

**Comment by catarak** [comment]
It's not super in depth, but I recommend looking at the [Deployment](https://github.com/processing/p5.js-web-editor/blob/master/developer_docs/deployment.md) documentation. I think it'll get you most of the way there.

**Comment by q2dg** [comment]
Oh, yes, that's what I mean (mostly). Thanks!!
I'll close the issue, then, although you could reopen it if you consider it deserves.
