### ISSUE TITLE
SyntaxError: missing = in destructuring declaration (sketch: line 14)

### ISSUE THREAD

**Issue by HAGZI** [processing/p5.js-web-editor#1093]
![Screenshot (148)](https://user-images.githubusercontent.com/51364444/58871278-54337c00-86df-11e9-8371-e1c22f5ebd1d.png)

`
function setup() {
  createCanvas(100);
}

function draw() {
  background(220);
  rect(x,y,20,30);
}

var {
x=100,
y=50
}

I KNOW ITZ A BASIC BUT IS SHOWS"SyntaxError: missing = in destructuring declaration (sketch: line 14)
![Screenshot (77)](https://user-images.githubusercontent.com/51364444/58871090-03bc1e80-86df-11e9-9c3e-04f3dff5c723.png)
"`

**Comment by andrewn** [comment]
Try declaring the `x` and `y` variables like this:

```js
var x = 100;
var y = 50;
```

Also, make sure [`createCanvas()`](https://p5js.org/reference/#/p5/createCanvas) has two arguments, for the width and height of the canvas e.g. `createCanvas(400, 400)`.

This code works for me:

```js
var x = 100;
var y = 50;


function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(220);
  rect(x, y, 20, 30);
}
```

**Comment by andrewn** [comment]
I'll close this for now, please reopen if it doesn't work for you.
