### ISSUE TITLE
HELP link does not work in full screen mode

### ISSUE THREAD

**Issue by nanatejapai** [processing/p5.js-web-editor#1098]
I'm new to p5js and using to p5.speech with videos. Video supposes to be autoplay when loading the web, which works perfectly fine in web editor's small screen preview. However, sometimes it does not work in full screen mode and present mode.

<img width="1280" alt="Screen Shot 2019-05-22 at 2 03 47 PM" src="https://user-images.githubusercontent.com/25845385/58197779-f775a180-7c9a-11e9-835e-68ae5303c718.png">

https://editor.p5js.org/nanatejapai/sketches/O45T33V2b

**Comment by catarak** [comment]
@nanatejapai thanks for reporting! when i run your sketch in edit mode, i'm getting errors. do you have a version of this sketch without errors, or a simplified version of this one? thank you!
