### ISSUE TITLE
Email Confirmation

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#11]
Things that need to be added, eventually:
- Error validation
- Email confirmation
- Password reset
- Login with Github

**Comment by shiffman** [comment]
Adding a reminder for "logout" option too!

**Comment by catarak** [comment]
Just pushed logout to master. Still need to add all of the other stuff.

**Comment by catarak** [comment]
Added the error validation!

**Comment by catarak** [comment]
I've started to add email confirmation and password reset, though I think it may have to wait until I enable https.

**Comment by shiffman** [comment]
Many students this week created multiple accounts b/c they lost / forgot their password.  So this is perhaps a higher priority then we might have thought.

**Comment by bensk** [comment]
Teaching this in HS and several student have already forgotten their passwords and are unable to login. They're creating individual projects and sending me the code. Could this be alieved by adding GitHub or Google Apps login?

✨ Thank you! ✨

**Comment by catarak** [comment]
Yes! I will prioritize fixing the Github login, and shortly afterwards password reset.

**Comment by bensk** [comment]
🙇 Thank you! How ridiculously hard would it be to save sketches as repos after logging with GitHub?

**Comment by catarak** [comment]
That would be a great feature! I'm not sure how soon I'd get around to implement something like that, either saving the projects as a gist or a Github repo though, as there are a lot of other features that are higher priority.

Right now, the workflow for getting a project onto Github is

1. Download the project as a zip
2. Unzip the project
3. Initialize git in that repository, make commit to master (all can be done with the Github GUI application)
4. Create remote repository on Github, set remote repo of project to that new remote
5. Push local repository to Github

which is a little time consuming but also not the worst thing in the entire world.

**Comment by Akarshit** [comment]
@catarak I am working on email-verification, will try to do a PR today.

**Comment by catarak** [comment]
Awesome! I don't know if this is mentioned explicitly anywhere but this project used Mailgun. Also I think the big reason to add email verification is so we don't get a bunch of spammers uploading lots of files to S3, so part of it will be adding some authorization that doesn't allow users to upload files unless their email is verified.

**Comment by Akarshit** [comment]
@catarak Yes I understand that, I have written the functions over mailgun, now the only thing left is to use them for verification and to use the verification field
Also while we are on this topic, I think it would make sense to remove the token system from reset-password. Instead send encrypted email and expiry field, when the link is clicked decrypt those fields and change the password. This saves space in the DB(no expiry and token field), and also would be less pain while debugging as the email could be extracted directly from the link.
If the above idea suits you, I will open a issue for it.

**Comment by catarak** [comment]
@Akarshit that would be awesome! If it's not too much work go ahead and do that 😄
