### ISSUE TITLE
Update Toolbar to match new designs

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1105]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

There's a new design for the toolbar that hasn't yet been implemented:
<img width="710" alt="Screen Shot 2019-06-14 at 5 54 28 PM" src="https://user-images.githubusercontent.com/6063380/59541001-8a39e280-8ecd-11e9-8515-ff6309a564e6.png">

For now, I'd ignore the icons on the right—that design/functionality should be covered in #208.

**Comment by adrijshikhar** [comment]
@catarak is this issue still available to work on?
