### ISSUE TITLE
Script error. (: line 0) with PoseNet

### ISSUE THREAD

**Issue by sguzmanolmos** [processing/p5.js-web-editor#1112]
#### Nature of issue?

- Script error. (: line 0)

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: MacOS Mojave
- Steps to reproduce this bug:

<img width="1440" alt="Screen Shot 2019-07-02 at 03 11 53" src="https://user-images.githubusercontent.com/49649437/60475439-a08ac100-9c77-11e9-8890-835a49429c92.png">

**Comment by andrewn** [comment]
From the console output, it looks as though the `manifest.json` URL is not being found (the 404 error).

Do you have a link to the sketch that I could look at?
