### ISSUE TITLE
Dividing by a zero shouldn't give Infinity

### ISSUE THREAD

**Issue by dark3bod** [processing/p5.js-web-editor#1114]
Should be NaN
![image](https://user-images.githubusercontent.com/39875072/60782717-755d1180-a150-11e9-847b-265e8fb4087c.png)

**Comment by andrewn** [comment]
Hi, thanks for reporting this.

The MDN web documentation says that [dividing by 0 should return `Infinity`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Division_()).

I've also checked `1/0` in Firefox 67.0.4 and Chrome 75.0.3770.100 which both return `Infinity`. So it appears the p5.js Editor console is displaying the result returned by the browser.

I'm going to close this, please re-open if there's something I've missed.

Thanks!
