### ISSUE TITLE
Add sketches to a collection

### ISSUE THREAD

**Issue by andrewn** [processing/p5.js-web-editor#1115]
#### Nature of issue?

- New feature request

#### New feature details:

This issue merges #43, #1068 as I think that an initial implementation of Collections should allow a user to add anyone's sketches into their Collections.

##### Collection

Collections have the following properties:
- id (a shortid, like projects)
- name
- description
- slug (for easily shareable URLs)
- owner
- items (a list of collected sketches)

##### Features

1. A user can create a new collection
2. A user can edit their collections' name, description and slug
3. A user can delete their own collections'
4. A user can see their own collections
5. A user can see another user's collection (by their username)
6. A user can add and remove any sketch to their own collections
7. Collections can be sorted by: 
    - name
    - date sketch was added
    - date sketch was created
    - date sketch was last updated
    - sketch owner's username
8. Deleting a sketch that is in a collection removes it from all collections
9. Changing a slug changes the URL the collection is available at, and the old slug URL will not longer work

##### Out of scope

- Submitting a sketch to another user's collection
- Displaying sketches as a thumbnail in a grid view

**Comment by andrewn** [comment]
@catarak If you're ok with this, I'll close #43 and #1068 in favour of this issue.

**Comment by catarak** [comment]
thanks for making this issue! i do think that users being able to submit/add sketches to a collection that is not theirs is important, the use case being a classroom/assignment setting. there's obviously a totally new design here, but maybe that's something i can work on.

**Comment by andrewn** [comment]
Totally agree with you @catarak. I've opened #1117 to capture this.

**Comment by catarak** [comment]
fixed by #1340.
