### ISSUE TITLE
How to add .bin files in web editor

### ISSUE THREAD

**Issue by MaanasNegi** [processing/p5.js-web-editor#1118]
#### Nature of issue?

- Feature enhancement

#### Details about the bug: 

- Web browser and version :On Chrome

**Comment by catarak** [comment]
thanks for reporting! i haven't come across a use case yet for folks who want to use `.bin` files on the web editor, so this is new to me! if i understand correctly, `.bin` files are generated by an ML algorithm, so users wouldn't ever need to edit them on the web editor, right? how large are these files typically? right now, there's an upload limit of 5MB on the web editor.

**Comment by MaanasNegi** [comment]
Hi, I am trying to use the .bin for a simple doodle classifier as shown in: [https://www.youtube.com/watch?v=wMe6qcpD8jI&list=PLRqwX-V7Uu6Zs14zKVuTuit6jApJgoYZQ&index=3](url) and I saw that you had to add the directory of the files but in the web editor you have to add files. The files were supposed to be 784 kb but the download says 766 kb.

**Comment by catarak** [comment]
okay cool! that's super helpful. it seems relatively easy and straightforward to support .bin files so that's definitely something we can do.

**Comment by MaanasNegi** [comment]
Thanks for helping!!

**Comment by singhvisha** [comment]
@catarak , is it open?

**Comment by singhvisha** [comment]
hi, is this issue open?
I would like to fix it.

**Comment by catarak** [comment]
@singhvisha go ahead and work on this!

**Comment by singhvisha** [comment]
@catarak 
hi, I am not able to get the file.

**Comment by catarak** [comment]
you need to edit the accepted mime types in the uploader in `server/utils/fileUtils.js`

**Comment by EkaanshArora** [comment]
Hey @singhvisha are you still working on this? I'll take it up if you're stuck somewhere.

**Comment by singhvisha** [comment]
@EkaanshArora 
hi, I will be soon submitting PR.
