### ISSUE TITLE
No check present for valid email address

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1119]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
In the reset password route, there is no check if a valid email address is entered or not.
![Capture](https://user-images.githubusercontent.com/28510494/61435586-7105d500-a956-11e9-8c56-3fe11c6681a7.PNG)

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:
 1) Visit reset password route
 2) Enter anything and check.

I would like to work on this.

**Comment by catarak** [comment]
thanks for reporting! yes, there should be an email validator here. feel free to work on it!

**Comment by plxity** [comment]
@catarak Thank you, I will send a PR soon.
