### ISSUE TITLE
update default p5.js version to 0.9.0

### ISSUE THREAD

**Issue by brianpeiris** [processing/p5.js-web-editor#1121]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Latest Firefox and Chrome
- Operating System: Windows 10
- Steps to reproduce this bug: 

Run this code in the editor:
```javascript
function draw() {
  background(200);
  text(deltaTime, 50, 50);
}
```
deltaTime is not defined

**Comment by catarak** [comment]
thanks for reporting! this is because the current default version of p5.js on the web editor is 0.8.0 and needs to be updated to 0.9.0.
