### ISSUE TITLE
Only Integers should be allowed to enter

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1129]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
![Capture](https://user-images.githubusercontent.com/28510494/62839936-f196c780-bcaf-11e9-9a19-ec4a44717bfa.PNG)

Only Integers should be allowed to enter in text size field
- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:
1) Open settings tab

#### New feature details:

**Comment by catarak** [comment]
thanks for reporting! this is, indeed, a bug.

**Comment by plxity** [comment]
@catarak I would like to work on this!
