### ISSUE TITLE
Everyone in class has access to one students' account

### ISSUE THREAD

**Issue by bensk** [processing/p5.js-web-editor#113]
Hey it's me again, your favorite High School CS teacher. 

Everyone in my AP CS class now has access to the account `Mikey316` and their own work has disappeared. That's weird, right?

**Comment by catarak** [comment]
That is very strange! Can you give me a little more detail so I can figure out what's happening? 
- What account are they logged in as?
- Is the issue that they have access to the user's sketches by looking at http://alpha.editor.p5js.org/Mikey316/sketches? It may not be clear but that is a feature, not a bug.
- Are they able to save/edit these sketches, not by making a copy of one?

**Comment by bensk** [comment]
Uh oh...this is happening again. I'm currently logged in as a student in a different class, even when I log out and back in, and I have lost access to all of my saved sketches.

**Comment by catarak** [comment]
Can you tell me the student's username?

**Comment by bensk** [comment]
And of course now it’s working fine…

zmedina is the username.

We have two classes of ~30 students each working in computer labs at the same time. Is it possible that the reuse of IP addresses is messing anything up?

¯\_(ツ)_/¯

**Comment by catarak** [comment]
I'm thinking that maybe the app got into a weird state, under one of the following possible circumstances:
1. Two users logged in under the same account open in different sessions
2. Having multiple browser windows open, logged into different accounts
3. Something else.

**Comment by bensk** [comment]
Anything I can do to help test?

**Comment by catarak** [comment]
I think the steps to reproduce this are
1. Open one window to the editor and login
2. Open another window to the editor
3. Logout on one of the windows
4. The other window still appears to be logged in. Click on "Open" in the navigation and there are no sketches.
Does this seem plausible?

I also noticed that the app gets into a similarly weird state if you
1. Open one window to the editor and login
2. Open another window to the editor
3. Logout on one of the windows and then log into another account

I think there needs to be some event listener on the cookies to solve this.

**Comment by bensk** [comment]
It's happening again, right now 😢

**Comment by catarak** [comment]
i've been thinking about how to fix this, and I think there are a couple things to do:
- [ ] better error checking, server side--check the user before saving
- [ ] make an api request at an interval that updates the session from the server. 
sorry this has taken so long to fix! it's hard to balance writing code enhancements and user account enhancements, and the former has taken precedent up to now.

**Comment by bensk** [comment]
🙏 Do you think it might be an issue that we're on a school network which might have some shared IP addresses? Happy to test anything we can help with.

**Comment by catarak** [comment]
All of the session handling is done with cookies, so I _think_ shared IP addresses wouldn't affect it. I think the most likely culprit is the editor open in a minimized/hidden window with a stale session cookie. I'll update this ticket when I've finished the updated session handling.
