### ISSUE TITLE
Add limit in file name

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1131]
#### Nature of issue?

- New feature request

#### Details about the bug: 
![Capture](https://user-images.githubusercontent.com/28510494/62890925-21060c80-bd62-11e9-9903-2516980a837d.PNG)

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
Add limit in the file name

#### New feature details:

**Comment by catarak** [comment]
there is a file name length limit currently, of 256 characters, which maybe is too long. there's been some discussion around this, see #568.

**Comment by plxity** [comment]
@catarak Yeah, I went through the discussion. So should I fix this up? 😃

**Comment by catarak** [comment]
how are you suggesting to fix this? do you think the name should be shorter? do you think it should be truncated in a different way on the front end?

**Comment by plxity** [comment]
Yes, I think the file name should be shorter. Add a limit in the input field and as it exceeds display an error message.

**Comment by catarak** [comment]
what is the length limit you suggest?

**Comment by plxity** [comment]
I think not more than 60 characters. What do you suggest?

**Comment by plxity** [comment]
@catarak Okay will fix that up :)

**Comment by shakti97** [comment]
is this issue still open? if no, i would like to contribute to it.

**Comment by catarak** [comment]
go for it!
