### ISSUE TITLE
Update p5.js Web Editor Mission Statement

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1135]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

@Luxapodular and I have been working on updating the overview/mission statement that currently lives in this repository's [README](https://github.com/processing/p5.js-web-editor/blob/master/README.md). Our process for writing this so far is captured in a [process wiki page](https://github.com/processing/p5.js-web-editor/wiki/p5.js-Web-Editor-Mission-Statement-Process). Here's the current draft, and we would love feedback:

The p5.js Editor is a platform for creative coding, with a focus on making coding accessible for artists, designers, educators and beginners. Simply by opening the website you can get started writing p5 sketches without downloading or configuring anything. The editor is designed with simplicity in mind by limiting features and frills. We strive to listen to the community to drive the editor’s development, and to be intentional with every change. The editor is free and open-source because we believe software, and the tools to learn it, should be accessible to everyone. 

You can even host your own version of the editor!

cc @shiffman @lmccart @saberkhaniscool

**Comment by saberkhaniscool** [comment]
Love it. Do you want to say anything about being able to download their work and put it up elsewhere so they have full control and ownership over their creative output.

**Comment by sinabahram** [comment]
Awesome stuff! Thanks for your work on this. The word "accessibility" is used twice, but possibly with different meaning. Do you think we could enhance the statement a bit with exactly what the statement means when it says accessible?

**Comment by lmccart** [comment]
This is great! I'd offer the suggestion to update "artists, designers, educators and beginners" to "artists, designers, educators, beginners, and anyone else that wants to learn" This might be a little redundant, but I think makes it feel a little more open, like it's not just for artists or designers.

**Comment by catarak** [comment]
thanks for the feedback, y'all! i'm gonna take this in and write an updated version.

**Comment by catarak** [comment]
i took another stab at it, and this is what i have. most notably, i expanded the second paragraph and i removed the second instance of "accessibility": 

The p5.js Editor is a platform for creative coding, with a focus on making coding accessible for artists, designers, educators, beginners, and anyone else that wants to learn. Simply by opening the website you can get started writing p5.js sketches without downloading or configuring anything. The editor is designed with simplicity in mind by limiting features and frills. We strive to listen to the community to drive the editor’s development, and to be intentional with every change. The editor is free and open-source.

We also strive to give the community as much ownership and control as possible. You can download your sketches so that you can edit them locally or host them elsewhere. You can also host your own version of the editor, giving you control over its data.

**Comment by sinabahram** [comment]
Thanks for the additional work on this, all.

 

My major comment right now is that it doesn’t mention accessibility at all in the sense that “the editor strives to be accessible for as many people as possible” or something like that.

 

In other words, can we have a firm commitment to digital accessibility in here?

**Comment by catarak** [comment]
@sinabahram i absolutely want to include that in the mission statement! i like how you have phrased it and i want to include basically that sentence somewhere in here.

**Comment by catarak** [comment]
alright, I tried switching around the first sentence to make the accessibility goal more explicit (the rest is the same, but i've put it all in here just because): 

The p5.js Editor is a platform for creative coding, with a focus on making coding accessible for as many people as possible, including artists, designers, educators, beginners, and anyone who wants to learn. Simply by opening the website you can get started writing p5.js sketches without downloading or configuring anything. The editor is designed with simplicity in mind by limiting features and frills. We strive to listen to the community to drive the editor’s development, and to be intentional with every change. The editor is free and open-source.

We also strive to give the community as much ownership and control as possible. You can download your sketches so that you can edit them locally or host them elsewhere. You can also host your own version of the editor, giving you control over its data.

**Comment by sinabahram** [comment]
I think it’s really good. It is ambiguous, to me, about which definition of accessibility is being used, but I also think in a way, this is a good thing. I think we can make much stronger claims once additional work is done, just like how it does around being able to download your sketches, etc., but we first need to do that work and then can elaborate on it.

 

Those are my thoughts.

**Comment by catarak** [comment]
i agree. "access" is an important part of the mission and we can define it more clearly as we figure out what it looks like!

**Comment by catarak** [comment]
fixed as part of #1152!
