### ISSUE TITLE
add ability to toggle line numbers to accessibility settings

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1138]
#### Nature of issue?

- New feature request

#### New feature details:

Suggested by @sinabahram, this feature would add a setting under "Accessibility Settings" to toggle line numbers within the code editor. When using a screen reader, sometimes the line numbers can be distracting and don't indicate position in the same way as they do for sighted users.

**Comment by singhvisha** [comment]
@catarak, Can I work on this issue?

**Comment by catarak** [comment]
@singhvisha go ahead!

**Comment by singhvisha** [comment]
Hi @catarak , I tried many time to built the webeditor locally.But it always end up with following message and i am not  able to find the link which led me to  my locally built editor.

> p5.js-web-editor@0.0.1 start /home/vishal/p5.js-web-editor
> cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js

[nodemon] 1.18.10
[nodemon] reading config ./nodemon.json
[nodemon] to restart at any time, enter `rs`
[nodemon] or send SIGHUP to 10605 to restart
[nodemon] ignoring: ./.git/**/* node_modules/**/node_modules
[nodemon] watching: /home/vishal/p5.js-web-editor/server/**/*
[nodemon] watching extensions: js,json
[nodemon] starting `node index.js`
[nodemon] forking
[nodemon] child pid: 10618
[nodemon] watching 41 files
p5js web editor is running on port: 8000!
webpack built a561bcd8f1891904e77f in 42037ms
webpack built 24d095784217e6a206e1 in 35499ms
⚠ ｢wdm｣: Hash: a561bcd8f1891904e77f24d095784217e6a206e1
Version: webpack 3.12.0
Child
    Hash: a561bcd8f1891904e77f
    Time: 42037ms
                                   Asset       Size  Chunks                    Chunk Names
    237d2039aa962a5ee45659fb827e7af3.svg  668 bytes          [emitted]         
    012da1d36804510edb76a75abeb939d4.svg  826 bytes          [emitted]         
    2daf3e371983de31b186092a66cd95ec.svg    1.02 kB          [emitted]         
    c89fbd9b15d5b81ab095f66e6e2af8fb.mp3    21.9 kB          [emitted]         
    b765603e096aa2a2efa1dcac698ce9ca.svg  924 bytes          [emitted]         
    7f8cec1ea5ad20cc1d7dac95382ed8a8.svg     2.5 kB          [emitted]         
    00eb4548e1fb30871670f90e50e0528e.svg  909 bytes          [emitted]         
    dabd027c78f988c2c08e5f64c720412a.svg    1.18 kB          [emitted]         
    541811a2fcb281689101ba8299458467.svg    1.03 kB          [emitted]         
    a6f98f83cf5a5b052980ed6cb6fe3143.svg       1 kB          [emitted]         
    0b2d2f6a38574a14150ef24557fae362.svg  167 bytes          [emitted]         
    40f2ffec4a9b4d01d29016a829781c4e.svg  925 bytes          [emitted]         
    0230b9407b59b773818b8b92530cf9fc.svg  698 bytes          [emitted]         
    12f3d8ca46ebff2bc67d892bf2f819ce.svg  698 bytes          [emitted]         
    76d2c68b246caec362782d46b7db1119.svg    1.22 kB          [emitted]         
    39216ce6b16a0117586b813500d7800f.svg    1.02 kB          [emitted]         
    65269fc755f9442b46a9abb9cba42add.svg    1.17 kB          [emitted]         
    4dbb2df6558eecde70917025c43604c1.svg    1.07 kB          [emitted]         
    1d420d3020185830e26e714d5dc347f0.svg    2.77 kB          [emitted]         
    2fba8dbd3f1f9049c93fb803116ee537.svg     1.1 kB          [emitted]         
    efc190473219531fece35442df174ef8.svg    8.51 kB          [emitted]         
    d7396366ba9295f987f7432907373dd7.svg  662 bytes          [emitted]         
    93e8b283b25d21d3082cb63d7b3acbee.svg  828 bytes          [emitted]         
    1e9dd30dd2874c211a95f9efa61ff8a1.svg  633 bytes          [emitted]         
    a09ea20f42b98188ef1e9367c7e75d2f.svg    1.55 kB          [emitted]         
    04512ad01b8b8ffbc8c31abde661a130.svg    1.54 kB          [emitted]         
    540ab804438f313771eb13d621a6ed4b.svg     1.7 kB          [emitted]         
    1cfd677411ff4323b18b337c0b320314.svg     1.7 kB          [emitted]         
    8be18038bc7e125d71d8b5b6ed9d41ed.svg    1.93 kB          [emitted]         
    f19e115f21b5e9555f6c704551b09f2d.svg    1.93 kB          [emitted]         
    60105991f8484713bdfb8a1069e598af.svg     1.6 kB          [emitted]         
    ae872d4dfc6e5cb1cceb303dc271b2a7.svg     1.6 kB          [emitted]         
    14770500e6b1dec4584af173eb90f588.svg  609 bytes          [emitted]         
    45d21a1a7e6084d013638398f30c080c.svg     2.9 kB          [emitted]         
    28bbb99e6331f41cf5f67dfb3f754910.svg  330 bytes          [emitted]         
    36b9abec9bb0e4d046b6a0d7bfacecf6.svg  513 bytes          [emitted]         
    08fbcf1c34903b0381de90362553af90.svg    1.57 kB          [emitted]         
             images/p5js-square-logo.png    13.7 kB          [emitted]         
                                  app.js    15.2 MB       0  [emitted]  [big]  app
                               vendor.js    2.32 MB       1  [emitted]  [big]  vendor
       [1] ./node_modules/react/index.js 190 bytes {1} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
       [9] ./node_modules/react-router/es/index.js 1.46 kB {0} [built]
      [14] ./node_modules/react-redux/es/index.js 229 bytes {0} [built]
      [70] ./node_modules/react-dom/index.js 1.36 kB {1} [built]
     [341] multi webpack-hot-middleware/client react-hot-loader/patch ./client/index.jsx 52 bytes {0} [built]
     [342] (webpack)-hot-middleware/client.js 7.77 kB {0} [built]
     [350] (webpack)-hot-middleware/process-update.js 4.37 kB {0} [built]
     [351] ./node_modules/react-hot-loader/patch.js 228 bytes {0} [built]
     [352] ./node_modules/react/cjs/react.development.js 63.5 kB {1} [built]
     [353] ./node_modules/react-dom/cjs/react-dom.development.js 778 kB {1} [built]
     [364] ./client/index.jsx 2.26 kB {0} [built]
     [420] ./client/store.js 2.39 kB {0} [built]
     [977] ./client/images/p5js-square-logo.png 73 bytes {0} [built]
     [978] multi react react-dom 40 bytes {1} [built]
        + 964 hidden modules
    
    WARNING in ./client/modules/IDE/components/ErrorModal.jsx
    
    /home/vishal/p5.js-web-editor/client/modules/IDE/components/ErrorModal.jsx
      29:1  warning  Line 29 exceeds the maximum line length of 120  max-len
    
    ✖ 1 problem (0 errors, 1 warning)
    
     @ ./client/modules/IDE/pages/IDEView.jsx 65:18-53
     @ ./client/routes.jsx
     @ ./client/index.jsx
     @ multi webpack-hot-middleware/client react-hot-loader/patch ./client/index.jsx
    
    WARNING in ./client/modules/IDE/components/SketchList.jsx
    
    /home/vishal/p5.js-web-editor/client/modules/IDE/components/SketchList.jsx
      39:1  warning  Line 39 exceeds the maximum line length of 120  max-len
    
    ✖ 1 problem (0 errors, 1 warning)
    
     @ ./client/modules/IDE/pages/IDEView.jsx 123:18-53
     @ ./client/routes.jsx
     @ ./client/index.jsx
     @ multi webpack-hot-middleware/client react-hot-loader/patch ./client/index.jsx
Child
    Hash: 24d095784217e6a206e1
    Time: 35499ms
                Asset    Size  Chunks                    Chunk Names
    previewScripts.js  589 kB       0  [emitted]  [big]  main
       [0] ./node_modules/react/index.js 190 bytes {0} [built]
      [55] ./node_modules/console-feed/lib/Transform/index.js 1.42 kB {0} [built]
      [92] ./client/utils/previewEntry.js 630 bytes {0} [built]
      [93] ./node_modules/loop-protect/lib/loop-protect.js 17.5 kB {0} [built]
      [94] ./node_modules/console-feed/lib/index.js 841 bytes {0} [built]
      [95] ./node_modules/console-feed/lib/Component/index.js 5.34 kB {0} [built]
     [103] ./node_modules/console-feed/lib/Component/theme/default.js 5.41 kB {0} [built]
     [182] ./node_modules/console-feed/lib/Component/Message.js 6.13 kB {0} [built]
     [200] ./node_modules/console-feed/lib/Hook/index.js 3.22 kB {0} [built]
     [201] ./node_modules/console-feed/lib/definitions/Methods.js 660 bytes {0} [built]
     [202] ./node_modules/console-feed/lib/Hook/parse/index.js 4.83 kB {0} [built]
     [210] ./node_modules/console-feed/lib/Transform/HTML.js 3.2 kB {0} [built]
     [211] ./node_modules/console-feed/lib/Transform/Map.js 2.49 kB {0} [built]
     [212] ./node_modules/console-feed/lib/Transform/replicator/index.js 34.7 kB {0} [built]
     [213] ./node_modules/console-feed/lib/Unhook/index.js 1.22 kB {0} [built]
        + 199 hidden modules
ℹ ｢wdm｣: Compiled with warnings.

**Comment by singhvisha** [comment]
hi,sorry.it worked..

**Comment by RickBr0wn** [comment]
Hi, how is this going? If its stalled I'd like to help. I have a pull request ready, but do not want to take an issue that someone else is working on.

Would be happy to discuss with @singhvisha

**Comment by singhvisha** [comment]
hi @RickBr0wn ,Please go head.
when your pull request is ready, no worth of trying it.

**Comment by RickBr0wn** [comment]
Thank you @singhvisha.

@catarak PR submitted #1146.
