### ISSUE TITLE
multiple copies of same project

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#114]
I am working on reproducing the steps to make this happen and hope to provide more context.  I recently noticed that sometimes when I make a new project/sketch, two versions of the project (showing identical creation timestamps) appear in my list of sketches.

<img width="881" alt="screen shot 2016-09-29 at 3 42 43 pm" src="https://cloud.githubusercontent.com/assets/191758/18969504/7a435d2a-865b-11e6-95df-64a279097a89.png">
<img width="881" alt="screen shot 2016-09-29 at 3 42 57 pm" src="https://cloud.githubusercontent.com/assets/191758/18969508/7d1cd6d4-865b-11e6-990b-de3afff910a8.png">

Anyone else have this happen?

**Comment by catarak** [comment]
I'm going to close this one, but definitely reopen this one if this happens again.
