### ISSUE TITLE
Notification should appear when new sketch is opened

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1140]
#### Nature of issue?

- New feature request

#### Details about the bug: 
![Capture](https://user-images.githubusercontent.com/28510494/63464926-d7ae6f00-c47d-11e9-8988-b709bf1b6448.PNG)

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
When a user clicks on 'New' option, the toast should appear stating the new file is created.
As of now if a user clicks on 'New', only the file name changes else there is no notification regarding new file opened. 

#### New feature details:

**Comment by catarak** [comment]
thanks for creating this issue! i agree that the toast notification should appear when you create a new sketch.

**Comment by plxity** [comment]
@catarak Okay No issues, Can I work on this? 😄

**Comment by RickBr0wn** [comment]
Hi @plxity, how is this going? If it has stalled in any way, I'd like to help.
