### ISSUE TITLE
Move sketches and assets to their own page

### ISSUE THREAD

**Issue by andrewn** [processing/p5.js-web-editor#1142]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Having sketches and assets appear in a modal is app-like, but the table can be cramped and doesn't make full use of the browser window. From a technical point of view, it makes state management a bit harder than it needs to be and makes the IDE component care about more than it should.

The modals are currently designed to be opened, display some info and then closed again. This makes them an unsuitable UI for multi-step experiences such as listing collections and their contents. It would make sense to find a UI pattern that works well for sketches, assets and collections in a unified way.

Behold that pattern! The tabbed page allows sketches and assets to be easily displayed, and provides flexibility for introducing profiles and collections too.

![Sketches@2x](https://user-images.githubusercontent.com/1762/63636976-3d198000-c677-11e9-8245-2239e1505bce.png)

**Comment by catarak** [comment]
I think it makes sense to close this since this is merged into the `feature/public-api` branch!
