### ISSUE TITLE
text wrapping

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#115]
I thought this might  be my personal bias, but I polled several teachers / students today and all suggested no text wrapping in the code editor.  Obviously there's no great solution when there are long lines of code and it could ultimately be a preference, but @catarak how do you feel about defaulting to no wrapping and just horizontal scolling?

**Comment by catarak** [comment]
Just pushed this to master, to be deployed. Let me know what you think though, as I also made it so the line numbers scroll off of the editor, which is not ideal, but for some reason the fixed line numbers are buggy on CodeMirror.
