### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js-web-editor#1153]
Sometimes unable to login. After inputting credentials and trying to click Login, there is a red error cursor (circle with slash) and no event upon clicking. Refresh and/ or new tab does not fix it. 

Then other times there is no issue. So not real sure how to reproduce.

Several of my students and myself have experienced this over the past day or two.

**Comment by catarak** [comment]
thanks for reporting! i too have noticed this occasionally. i'll look into this shortly.

**Comment by catarak** [comment]
just pushed a change for this which will take a few minutes to deploy! try it out and let me know if it's fixed.

**Comment by slowizzm** [comment]
so far so good ... ty!

**Comment by catarak** [comment]
okay great. i'm going to close this for now, please reopen if you notice other issues!

**Comment by ashley-towey** [comment]
I've noticed this issue presenting itself again, and am unable to login.

**Comment by JalokimDev** [comment]
Bump, have the same issue right now. Wrong credentials on the first try, couldn't log in anymore, disabling cache/incognito mode didn't help.

**Comment by kjhollen** [comment]
I'm having trouble logging in, too, with an unlinked account (not through google or github). I'm also noticing that some links I have for specific sketches are not loading, after a long wait/loading screen it just goes to a new default sketch. FYI @catarak

**Comment by Tntosion** [comment]
same problem! It's been like this for about 30 minutes. Is it because maintenance is going to happen soon next week? I need to log in to submit an assignment! Please fix this ASAP lmao

**Comment by catarak** [comment]
Hey all,

I'm doing my best to assess the issue but quite honestly I've never encountered this specific issue before and I'm not sure what's happening. I'm doing my best to isolate the issue but I can't really give a timeline on when it will be fixed. I appreciate some grace, I'm a one person team trying to fix this as fast as possible.

**Comment by catarak** [comment]
I've isolated the issue to an error with the database. I'm not sure what caused it and I've filed a ticket with the database service support. Hopefully I will hear back soon.

**Comment by Tntosion** [comment]
Mine is working now! It automatically logged me in. Haven't tested out the login page as i'm too afraid to log out haha. Thanks for looking into this issues!

**Comment by catarak** [comment]
Yes I think it is fixed! I'm going to work with the database support engineer to figure out what happened, but essentially it seems like the database service got messed up. I think that the planned outage scheduled for this weekend will actually address this.

**Comment by raclim** [comment]
Hi everyone! This issue seems to be resolved, so I'm going to close it. Please feel free to reopen it or report a new one in the future if it comes up again, thanks! 🙂

**Comment by epicurean-nomad** [comment]
This issue has showed up again. Details are as follows:

1. Was unable to save my sketch cause it said the sketch had been saved in another tab

2. When I refreshed the page, it was unable to reload with a "Bad Gateway Error"

3. Now I'm also unable to login with a red slash mark.

**Comment by SpineyPete** [comment]
Same issue today.
