### ISSUE TITLE
Embed in click funnels members area NOT WORKING

### ISSUE THREAD

**Issue by jtrimble2593** [processing/p5.js-web-editor#1159]
I am having an issue with the embed codes, When I embed the code into a clickfunnels membership area it will now show up 

Well, it pops up for a split second then it disappears. I am not sure why it does that.

But when I embed it into a public clickfunnels page it embeds just fine. the only difference is between the public page and the members area

**Comment by catarak** [comment]
hi! i think you have the wrong repository? i have no idea what clickfunnels is.
