### ISSUE TITLE
delete p5.js account! please help

### ISSUE THREAD

**Issue by jokercoding** [processing/p5.js-web-editor#1160]
#### delete p5js account

- Found a bug

#### Details about the bug: 
please help me delete my p5 js account.

- signed in with google account to p5 js
- MacOSX

**Comment by catarak** [comment]
i can definitely help you with this! can you tell me your username so i can delete the account?

**Comment by leonardof131** [comment]
Taking the oportunity to ask a question.
@catarak , if I wanted to manually create/delete user in my stance of the web editor, the only way to do so is creating/deleting an entry in the mLab mongodb of my deploy ?

**Comment by catarak** [comment]
@leonardof131 that is true for deleting! if you want to create a new user, you can also just go through the sign up process on your instance.

**Comment by leonardof131** [comment]
We're creating some standardized users so we can quickly assess wich class/shift the student is just by looking at the login information. 
I was wondering if there was another option other than manually registering in the instance

**Comment by jokercoding** [comment]
Hey! thank you very much for the fast reply.
my username was florin.raske@gmail.com
thank you for your help!

**Comment by jokercoding** [comment]
> i can definitely help you with this! can you tell me your username so i can delete the account?

**Comment by Drnagrom** [comment]
I'm looking to delete my p5.js account too?

**Comment by catarak** [comment]
@Drnagrom okay! please email cassie@processing.org with your account info.
