### ISSUE TITLE
web editor audio bug is plaguing me 

### ISSUE THREAD

**Issue by socalledsound** [processing/p5.js-web-editor#1161]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 
78.0.3904.12 (Official Build) dev (64-bit)

- Operating System: 

This happens on any computers I use, chromebook, macbook, imac, hackintosh, mac mini, you name it.

- Steps to reproduce this bug:
I'm having a pretty strange problem.  Many of my sketches are having audio glitches, whether they have audio in them or not.  If I ever sign in to my web editor in any given browser, I get these glitches, which are strange oscillators pulsing on and off at fairly random pitches.  There is nothing in my code that has audio at the moment and it's still happening.  I've reset chrome and deleted all cached files.  
Also, I am getting a persistent error in the console that says

p5 had problems creating the global function "createElement", possibly because your code is already using that name as a variable. You may want to rename your variable to something else. 

I get this error even in a completely empty sketch.

Right now I'm trying to teach a class focused on using the p5 web editor so this is all a bit of a pain.  Any help would be appreciated!  Thanks!

video clip of the problem in action:

https://youtu.be/3ZDERAzOtyA

the code in the clip:

let myBubble, myBubble2;
let bubbles = [];
function setup() {
  createCanvas(400, 400);
  

  
  
  for(let i = 0; i < 100; i++){
  
    bubbles[i] = new Bubble(random(width), random(height), random(200), [random(255), random(255), random(255)], random(5));
  }
  
  
  
}

function draw() {
  background(220);
  
for(let i =0; i < bubbles.length; i++){
  bubbles[i].move();
  bubbles[i].display();
}
}

function Bubble(x, y, size, color, speed){
  this.x = x;
  this.y = y;
  this.size = size;
  this.color = color;
  this.speed = speed

  this.display = function(){
    fill(this.color);
    ellipse(this.x, this.y, this.size);
  
  }
  
  this.move = function(){
    if(this.x > width || this.x < 0) {
      this.speed = this.speed * -1;
    }
    this.x = this.x + this.speed;
  
    }

}

**Comment by catarak** [comment]
hi! can you look in your settings and see if you have the accessibility features turned on? if so, you can turn them off to get rid of these sounds. you can access this by clicking on the cog icon in the upper right, then clicking on the "accessibility" tab.

**Comment by socalledsound** [comment]
Hi I think that may have fixed it!  thank you!
