### ISSUE TITLE
Allow creation of shader files from within the editor

### ISSUE THREAD

**Issue by lsh** [processing/p5.js-web-editor#1162]
- Existing feature enhancement

#### Feature enhancement details:
Shaders are allowed through drag and drop files, but the filetypes `.frag`, `.vert`, and `.glsl` are not working when created through the sketch>add file menu or through renaming files.

**Comment by catarak** [comment]
thanks for creating this issue! yes, i agree it should be possible. maybe this issue could be handled with #1118 since it involves editing the same files.
