### ISSUE TITLE
Online editor crashes through nested loop

### ISSUE THREAD

**Issue by sebmorales** [processing/p5.js-web-editor#117]
(this issue was first reported on the p5.js issues page and then moved here (p5.js-web-editor) as instructed)

Hi,
Fist time here. I am trying to make radial color gradients by mathematically assigning values to every pixel within a circle. I am basically using a big nested loop and it takes a little to run but it only needs to run once.

When I was writing this code on the online editor I got an error saying that my loop was taking too long to run and that it might be an infinite loop.

It works fine on the desktop version.

Here an example of the nested Loop:
https://alpha.editor.p5js.org/projects/Hk3Npc36

Here the gradient code:
https://alpha.editor.p5js.org/projects/HJNqd936

**Comment by catarak** [comment]
I just pushed some updates to the infinite loop handling code, is this still not working for you?

**Comment by sebmorales** [comment]
It seems to be running ok now. 
Thanks!

ps. I did get the error once but then it went away.
![image](https://cloud.githubusercontent.com/assets/12665779/19172665/fce2b024-8bf0-11e6-944f-73d42884e880.png)

**Comment by catarak** [comment]
Okay, that's good to know. The infinite loop detecting code has a time limit on how much time it takes for code to run before it thinks the code is possibly an infinite loop, so I guess this code is hitting that limit.
