### ISSUE TITLE
Increase Auto-refresh reload time

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1177]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

I rarely use the autorefresh feature because I find it annoying that it refreshes so often, and I'm honestly surprised that no one else has opened this issue. It currently will update if the user has stopped typing for 400ms. I'm going to try increasing it to 1 second (1000ms) and see how it feels!

**Comment by ashu8912** [comment]
Yes The One Second Reload Looks good this issue is fixed and can be closed now.
@catarak
