### ISSUE TITLE
Unable to add new file from top navigation

### ISSUE THREAD

**Issue by frankwinter** [processing/p5.js-web-editor#1180]
- Found a bug

It's not possible to **Add File** for a sketch. The console logs:
`app.75f9d4564e8bb797e7c7.js:14 Uncaught TypeError: Cannot read property 'children' of undefined`

Tested on MacOS Chrome & Safari

**Comment by catarak** [comment]
thanks for reporting! i'm currently not able to reproduce. can you be more specific about your steps to produce this bug? are you adding a text file or uploading a file? are you adding a file to the root directory of the sketch or to a subfolder?

**Comment by frankwinter** [comment]
I just start the web editor and use the top menu to select SKETCH / ADD FILE - enter a name and hit ADD FILE. This leads to the error.
Using the sidebar to add a file works fine.

**Comment by socalledsound** [comment]
My class and I are also unable to load add any files to our sketches.  It was working in the middle of last week but starting perhaps sunday? we can't add external files of any type.  Have tried text and sound files.  The editor responds as always but fails to load anything.  Older sketches with image or sound assets are all still working fine.

**Comment by socalledsound** [comment]
and ps, how do you add a file using the sidebar?

**Comment by frankwinter** [comment]
When you expand the sidebar to see all files you can click on the small triangle after "Sketch Files".

**Comment by socalledsound** [comment]
I'm not sure which small triangle you mean, is it pictured here?
![arrow](https://user-images.githubusercontent.com/4337279/66343774-34b49600-e901-11e9-828a-4237b67a048e.png)

**Comment by frankwinter** [comment]
Over here it looks like this:

<img width="287" alt="Bildschirmfoto 2019-10-07 um 22 11 01" src="https://user-images.githubusercontent.com/13355366/66345096-9d2a6400-e94f-11e9-8373-24550c51505f.png">

(Up to date Chrome, Safari and Firefox on MacOs)

**Comment by catarak** [comment]
@socalledsound that's a different error, but thanks for reporting! i think a PR i made caused that regression, i'll unmerge it and fix that issue.

**Comment by catarak** [comment]
just pushed a fix that should fix both of these issues!
