### ISSUE TITLE
Change the account page theme as per the selected theme.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1182]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Linux
- Steps to reproduce this bug:

#### Feature enhancement details:
In the account page, the theme should change as per the theme selected by user.

#### New feature details:

**Comment by plxity** [comment]
@catarak What do you think about this feature? If you approve can I work on this?

**Comment by catarak** [comment]
this is currently fixed on the `feature/public-api` branch, which hasn't yet been merged.
