### ISSUE TITLE
Add password minimum to Account Settings

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1188]
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Linux
- Steps to reproduce this bug:

#### Feature enhancement details:
While setting up the new password add a limit of at least 6 characters similar to sign up form.

#### New feature details:

**Comment by plxity** [comment]
@catarak Can I work on this?

**Comment by catarak** [comment]
the password minimum is already six characters.

**Comment by plxity** [comment]
@catarak Please check this.
![Screenshot from 2019-10-09 02-55-43](https://user-images.githubusercontent.com/28510494/66434580-79931680-ea40-11e9-95bb-49e367014d7b.png)

**Comment by plxity** [comment]
In this after typing only 1 character the button becomes active. It should be activated only when at least six characters are entered.

**Comment by catarak** [comment]
ahh, you mean on the account settings page! got it. yes, that is a bug.

**Comment by plxity** [comment]
@catarak Can I work on this?

**Comment by ashu8912** [comment]
@catarak is this fixed?

**Comment by plxity** [comment]
@ashu8912 Yes, This is fixed.
