### ISSUE TITLE
File upload error / Add File will not upload: TypeError

### ISSUE THREAD

**Issue by sssshuang** [processing/p5.js-web-editor#1189]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

When trying to upload an image or file, the browser reports: 
Uncaught TypeError: Cannot read property 'children' of undefined
and the image is not uploaded

- Web browser and version: Chrome: 77.0.3865.90
- Operating System: MacOSX: 10.14.5
- Steps to reproduce this bug:

<img width="636" alt="Screen Shot 2019-10-08 at 4 25 00 PM" src="https://user-images.githubusercontent.com/47423233/66434446-33aa6400-e9e8-11e9-81e5-acd06eb92fdb.png">

#### New feature details:

**Comment by catarak** [comment]
thanks for reporting! i attempted to fix this issue in #1183 but it seems like it didn't get deployed. will investigate...
