### ISSUE TITLE
disable console messages when minimized

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#119]
Related to #80 @lmccart and I discussed on Friday that we could disable the console from printing messages when it's minimized to alleviate resources.   This may all be moot if we eventually replace the console with a different engine as discussed in #7, but could be good for now especially as we approach ICM's "synthesis" workshop.

**Comment by lmccart** [comment]
this is addressed in this pr: https://github.com/processing/p5.js-web-editor/pull/118
