### ISSUE TITLE
classes static properties false syntax error

### ISSUE THREAD

**Issue by ScriptHosT12** [processing/p5.js-web-editor#1193]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 77.0.3865.75 64bit
- Operating System: ubuntu Linux 19.04
- Steps to reproduce this bug:

write:
`class t
{
  static w = 2;
}`

![image](https://user-images.githubusercontent.com/30875598/66701358-7b383500-ecf3-11e9-8663-5b886758139a.png)

however it works perfectly

**Comment by catarak** [comment]
thanks for reporting! i assume this is related to the jshint parsing not being 100% up to date with the newest javascript features.

**Comment by catarak** [comment]
it seems like this is actually still an ES7 stage 3 proposal, so it hasn't been added to JSHint yet? see https://github.com/jshint/jshint/issues/3139. the way around this is to use a getter:

```javascript
class t {
  static get w() {
    return 2; 
  }
}
```

**Comment by adrijshikhar** [comment]
@catarak does this issue still persist?

**Comment by catarak** [comment]
Going to roll this into #1540.
