### ISSUE TITLE
PUT error 409 when trying to save a sketch after a previously added sketch file is deleted

### ISSUE THREAD

**Issue by piecesofuk** [processing/p5.js-web-editor#1198]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
After deleting a previously added sketch file a 409 error is logged on the PUT request when trying to save the sketch

- Web browser and version: 
Chrome
- Operating System: 
Chrome OS
- Steps to reproduce this bug:
Create a new sketch
Save it
Click the sidebar
Select Sketch Files/Add File
In the popup type in the file name and click the Add File button
Close the Add File popup
Save the sketch
Delete the file that was just added
Save the sketch -> here I get PUT 409 error

If I re-add the deleted file then saving works again.

**Comment by catarak** [comment]
thanks for reporting! i am able to reproduce. it seems like the error is at https://github.com/processing/p5.js-web-editor/blob/master/server/controllers/project.controller.js#L23, the code that is supposed to prevent users from saving an older version of a sketch over a newer one.

**Comment by catarak** [comment]
Just went through the steps to reproduce and this appears to be fixed now.
