### ISSUE TITLE
In mobile display can't identify if button is disabled or not.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1199]
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: LInux
- Steps to reproduce this bug:

#### Feature enhancement details:
![Screenshot from 2019-10-21 08-37-55](https://user-images.githubusercontent.com/28510494/67174031-3476c900-f3de-11e9-98b1-460cbb3279d5.png)
In desktop when we hover on the button we can see an icon which shows it is disabled until all the details are not entered correctly.

Whereas in the case of mobile, It is really difficult for a user to figure out if the button is disabled or not. 
![Screenshot from 2019-10-21 08-37-19](https://user-images.githubusercontent.com/28510494/67174106-86b7ea00-f3de-11e9-80f0-94c46e4356d7.png)

#### New feature details:
Change the CSS properties of button when the screen size is reduced to 500px or so.

**Comment by catarak** [comment]
thanks for reporting! i agree that these two button states could be better differentiated.

**Comment by plxity** [comment]
@catarak i am working on this. Can you assign this to me?

**Comment by plxity** [comment]
@catarak What colour should I keep when it is in a disabled state? (in mobile screen)

**Comment by ani4aniket** [comment]
![Screen Recording 2019-12-01 at 8 38 03 AM](https://user-images.githubusercontent.com/31184591/69908827-f2966500-1416-11ea-932c-e9e8cfea1b5b.gif)
@catarak and @plxity This is issue is not resolved for a quite long, so I tried to resolve this.
Please review this @catarak and thanks @plxity for point this.

**Comment by catarak** [comment]
just looked at your PR, @ani4aniket! styles should be added in `client/styles/*.scss`, rather than directly in the react components.

**Comment by tanhengyeow** [comment]
@ani4aniket Are you still working on this? If not I'm interested to take this up 😄
