### ISSUE TITLE
infinite loop check freezes up editor even w/o auto-refresh

### ISSUE THREAD

**Issue by mimiyin** [processing/p5.js-web-editor#120]
repro steps:

1. Create new sketch
2. auto-refresh is unchecked
3. sketch is in stopped mode
4. write an infinite loop
```javascript
for(var x = 0; x < width; x+=0) {
}
```

Infinite loop warning pops up and slows down/freezes up editor depending on how much other stuff there is in the sketch.

**Comment by shiffman** [comment]
I just did some testing and can confirm there is a still an issue.   Without the infinite loop problem auto-refresh seems to be working properly.  So my suspicion is that the infinite loop detection is eating up all the resources somehow?  Any ideas @yining1023?

I'm able to get the sketch back, but there is a big slowdown and if I don't fix the infinite loop in time it will eventually freeze.

**Comment by catarak** [comment]
I may disable the infinite loop checking for now and see if @yining1023 and I can figure out a better solution.

**Comment by yining1023** [comment]
Um...What infinite loop detection does is that whenever the sketch changes,
after 1 second, it runs the code in one iframe, and if there is one
infinite loop it will stop the sketch. But if there is no changes in the
editor, it won't run the sketch. I'm guessing maybe the loop protection
runs the code too frequently, or it runs too late so it fails to catch the
loop before it crashes the editor. I need to get the timing right. Or will
the editor freeze even though user doesn't change anything in the editor?

**Comment by shiffman** [comment]
@catarak yes sounds like a good plan.  Do you think we should disable auto-run by default too (for the time being or. . .)?   @lmccart

**Comment by shiffman** [comment]
Just adding that I've now seen this with two students in office hours (both downloaded the desktop editor b/c they were too stuck) so yes let's disable the infinite loop checker for now if we can.   

(Also while looking at the problem with a student it came up that the infinite loop checker doesn't need to run if "auto-refresh" is disable and only when the user presses play).

Thanks everyone!

**Comment by lmccart** [comment]
sounds good, I agree let's disable autorun completely and tweak and test in a different branch until we've got it solid, then reintroduce it.

**Comment by shiffman** [comment]
@yining1023 and I just met and some more context!  The infinite loop checking only breaks if the infinite loop is in `draw()`.  And I was able to break the original code at jsbin.com with:

```javascript
while (true) {
  for (var i = 0; i < 10; i+=0) {
  }
}
```

So it may not be our bug even . . but perhaps we can sort it out and contribute it back.

**Comment by catarak** [comment]
I temporarily removed autorun and the loop protect, and deployed to production. 

@shiffman does the same code break on CodePen? If not, maybe we should email our contact there and see what they do.

**Comment by shiffman** [comment]
I quickly tested and codepen locks up briefly but then resolves and gives you the error.  It looks like CodePen's behavior is to let the infinite loop run for a short bit (1-2 seconds?) and then detect and stop the code.

**Comment by yining1023** [comment]
I think if we only call loop protection when user tries to run the sketch, it will be fine. Before, loop protection will run the code every time something changes in the editor, so it's eating up the resource. Like CodePen, it would work if we give time(1-2 second, or a little longer) to it, and let it finish detecting the current code first.

**Comment by catarak** [comment]
An update to this has been pushed, let me know if there are problems and I will reopen this.
