### ISSUE TITLE
I cant LogIn

### ISSUE THREAD

**Issue by UselessSaint** [processing/p5.js-web-editor#1202]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Win
- Steps to reproduce this bug: 
   Im not really sure if this is a bug (maybe im just stupid), but i had an accout (UselessSaint) and i cant logIn or reset (mail is not even in spam). So i tryed to Register one more (UselessSaintv2) and i cant Verify it and also cant logIn (im sure the pass is ok)

![image](https://user-images.githubusercontent.com/32227002/67529705-93ca2700-f6c5-11e9-9e31-0cddec4e1eaf.png)

**Comment by catarak** [comment]
what happens when you try to reset your password?
