### ISSUE TITLE
Coment Collapse bug 

### ISSUE THREAD

**Issue by Jkutkut** [processing/p5.js-web-editor#1204]
- Found a bug

If i try to collapse this whole part of code:
/*for(let i = 0; i < setS.length; i++){//get pairs
    //pair
    let pairsWithMe = 0;
    let sector1 = 0;
      /*if(true){
        console.log("(" + setS[i].x + ", " + setS[i].y + ") and (" + setS[j].x + ", " + setS[j].y + ") -> l:" + pairs.length);
        console.log(setS[i].posVal + " ---- " + setS[j].posVal);
        //setS[i].show(color(20,20,20))
      }* /
    }
    /*
    sfjlkhsdkjfkhds* /
  }*/

i does not able us to do so.
I believe that it has something to do with the "/*" because it works with:

/*for(let i = 0; i < setS.length; i++){//get pairs
    //pair
    let pairsWithMe = 0;
    let sector1 = 0;
      / *if(true){
        console.log("(" + setS[i].x + ", " + setS[i].y + ") and (" + setS[j].x + ", " + setS[j].y + ") -> l:" + pairs.length);
        console.log(setS[i].posVal + " ---- " + setS[j].posVal);
        //setS[i].show(color(20,20,20))
      }* /
    }
    / *
    sfjlkhsdkjfkhds* /
  }*/ 

- Web browser and version: Chrome | 77.0.3865.120
- Operating System: ubuntu 19.04
- Steps to reproduce this bug:

The process is the same as showed above, there are no errors on the screen.

Thank you creating this editor, it is really useful.

**Comment by catarak** [comment]
hey @jkutkut, i think you have a syntax error in your code. it seems like you're trying to comment code by writing
```js
/ if (true) {

}
*/
```
which doesn't work! you need to write
```js
/* if (true) {

}
*/
```

**Comment by Jkutkut** [comment]
It was just an example, my code has that /* and the problem remains

**Comment by catarak** [comment]
okay, got it! i was just going off of the code that you posted. so, the error is that code like 
```js
/*
 * some stuff here...
 *
 */
```
isn't collapsing correctly? i will try to reproduce.
