### ISSUE TITLE
Can't load assets with URL that contains the file name

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1205]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Mac OSX
- Steps to reproduce this bug:

I noticed that example [P_1_2_2_01](https://editor.p5js.org/generative-design/sketches/P_1_2_2_01) doesn't work in the web editor. It's not able to load the images, and makes a request to the following url: https://cdn.jsdelivr.net/gh/generative-design/Code-Package-p5.js@master/01_P/P_1_2_2_01/https://cdn.jsdelivr.net/gh/generative-design/Code-Package-p5.js@master/01_P/P_1_2_2_01/data/pic1.jpg. The example works if you change the names of the images, [check out my forked version that works](https://editor.p5js.org/cassie/sketches/z27m8WNb3).

The reason for this strange issue is that the file URL contains within it the file name as specified in the web editor. When the HTML is being created, the file name is replaced with its url, which happens twice to account for all edge cases.

**Comment by ashu8912** [comment]
Working on it

**Comment by ashu8912** [comment]
@catarak couldn't figure out how this URL generation is occurring can you guide me a little here.

**Comment by ashu8912** [comment]
@catarak any updates on this
