### ISSUE TITLE
had problems creating the global function "createElement" -- BUG

### ISSUE THREAD

**Issue by pringools** [processing/p5.js-web-editor#1208]
#### Details about the bug: 

- Web browser and version: **Opera v63.0.3368.107**
- Operating System: **Windows 7**
- Steps to reproduce this bug: **I don't know them.**

This bug is REALLY weird. I don't know what i've done wrong, but whenever I run a sketch, this error shows up: 

*"p5 had problems creating the global function "createElement", possibly because your code is already using that name as a variable. You may want to rename your variable to something else."* 

And it shows up all the time, even when I create a brand new sketch and run it, the error still shows up.

Also, in some sketches, where something moves (changes coordinates), the editor plays like a piano sounds. I know, it sounds ridiculously dumb, but it's true! I tried to open the same sketches and run them in the incognito mode and it all disappeared. It also gone away when i logged out of my account. I really don't understand the nature of this bug... And because of this glitch I can't properly use my account in the web-editor without getting error in the console and sounds playing!

**Comment by catarak** [comment]
thanks for reporting! do you have the accessibility features turned on? you can check this by going to settings (the cog icon) -> accessibility settings, and make sure you uncheck all of the boxes.

**Comment by pringools** [comment]
Oh, yes, thank you! That fixed everything :)

**Comment by anirban0104** [comment]
THAT FIXED EVERYTHING, SORRY BTW I MESSED UP WITH THE SETTINGS
