### ISSUE TITLE
The end of empty element is broken

### ISSUE THREAD

**Issue by kazuhikoarase** [processing/p5.js-web-editor#1211]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

At server/views/index.js line 15, the end of empty element is broken.

```html
  <link rel='shortcut icon' ... type='image/x-icon'/ >
```
should be
```html
  <link rel='shortcut icon' ... type='image/x-icon' />
```

- Web browser and version: Microsoft Edge (I see the error message at the developer console.)
- Operating System: Windows
- Steps to reproduce this bug: run the editor

**Comment by catarak** [comment]
thanks for reporting!

**Comment by zoyron** [comment]
If the issue is still open and it is assigned to no one, I'd like to work on this.
Thank you.

**Comment by ani4aniket** [comment]
@zoyron I have already created a PR fixing this.

**Comment by ashu8912** [comment]
Hey @ani4aniket please mention your pr here so that others can get that there is already a pr regarding this.
