### ISSUE TITLE
409 Conflict PUT

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js-web-editor#1213]
409 Conflict PUT - sketch not saving

- [x] Found a bug

#### Which platform were you using when you encountered this?
- [x ] Desktop/Laptop

#### Details about the bug: 

- p5.js version: 0.9.0
Chrome 78 on Windows 10

Myself and students have been experiencing this quit a bit lately. Sketches will not save resulting in lost work. Looking in the console I see a 409 conflict error ... 

![Capture](https://user-images.githubusercontent.com/14972059/69499996-fbd67d80-0ebc-11ea-921c-93e35ad43e10.PNG)

**Comment by slowizzm** [comment]
Sorry, I thought I was in the web editor repo when I created this issue but now that it has been transferred I see this issue has already been created at #1198

**Comment by catarak** [comment]
thanks for reporting! i'm sorry it's causing your students to lose their work. can you think of more specific steps to reproduce? for example, if one of your students had the sketch open in multiple tabs, and was editing both of them, that would cause this issue.

**Comment by slowizzm** [comment]
@catarak Yes, this seems to be the cause of the error, thank you. Sorry I did not provide steps to reproduce, I never would have thought there was a safety net to prevent overwriting older version of sketch and I could not see a viable path to reproduce. 

I do wonder if there is a way this could be toggled on/off in the settings or if there could be an option to open multiple windows to view html, css, and js side by side (similar to codepen)? I know the goal of the web editor is simplicity but a lot of the times I have found students need to see the files open next to each other and edit simultaneously in order to correlate the concepts.

**Comment by catarak** [comment]
that makes sense! maybe this could be solved by allowing users to open multiple files in the web editor.

**Comment by slowizzm** [comment]
@catarak 

That would be wonderful. I was going to suggest this, something similar to code pen, but held off because I didn’t know if that countered the idea of keeping the web editor as simple as possible. 

I find it easier for students to understand the concepts by having multiple windows open so they can see how different parts of the code relate to each other (without cluttering one file), especially when it comes to html/css. 

I like codepens dynamic multi-tab layout, but I feel codepen is too overwhelming for most of my students as they are new to code.

**Comment by catarak** [comment]
I agree that CodePen's default with all of the panes is kind of overwhelming, but maybe having the ability to have **two** files open side by side is useful enough, especially in a classroom setting. It's been on my list to add a view that's _just_ code full-width, so maybe this idea could be incorporated into that design!

**Comment by slowizzm** [comment]
@catarak 

Sorry I wasn’t clear, I think the panes are great and that is what I would like incorporated into the p5 editor. Especially the ability to resize/fold/unfold them when needed.

It is all the extra bells and whistles beyond the editor view that I find can be too overwhelming for my students.

**Comment by catarak** [comment]
got it! well, fell free to post designs/images/videos/etc of stuff you like or your own ideas,

**Comment by slowizzm** [comment]
@catarak 

Sounds good. Is there an issue already open for this? 

Thanks

**Comment by catarak** [comment]
there is not! #208 is related to having different views but not the same thing.

**Comment by catarak** [comment]
Closing this into #1759 which I think will alleviate some of the error 409 issues.
