### ISSUE TITLE
Component styles

### ISSUE THREAD

**Issue by andrewn** [processing/p5.js-web-editor#1215]
#### Nature of issue?

- New feature request

#### New feature details:

Currently, CSS is written using SASS and stored together in [/client/styles/](https://github.com/processing/p5.js-web-editor/tree/master/client/styles).

This means re-use happens by re-using classes, which makes it hard to see exactly which component is using the styles and making changes error-prone. Styles are global and so may interact with each other in strange ways.

I propose that we move styles to be local to a component. e.g. a `<Button />` component would contain all the styles it uses nearby. Styles would not apply globally, so reuse would happen by using the Button component, or by splitting components into smaller ones to be used elsewhere.

#### Potential choices

- [styled-components](https://www.styled-components.com/)
- [CSS Modules](https://github.com/css-modules/css-modules)
- [CSS Modules](https://github.com/css-modules/css-modules) with [PostCSS](https://postcss.org/) plugins
- [SASS Modules](https://css-tricks.com/introducing-sass-modules/)
- [emotion](https://emotion.sh/docs/introduction)

#### Considerations:

- maintainability
- easy of use
- theming
- learning curve for new users
- support for server rendering
- output approach (single CSS files, inline etc)

**Comment by catarak** [comment]
I have used styled-components with Cycling '74 work and I do like it. I'm not sure the learning curve is any bigger than BEM + SCSS. For me the choice styled vs. emotion!

**Comment by andrewn** [comment]
# Comparing Styled Components and emotion

They both have a similar API sub-set so there's not much difference between the two...

- maintaibility: both projects seem to be well-maintained and actively developed;
- ease of use: I think both have a very similar API and make it easy to attach locally-scoped styles to components;
- learning curve for new users: once set-up in the project, I think picking up the "styled component" way of writing styles is easy as it's just CSS. I think ensuring people pick good names for things will be important when checking PRs;

- output approach: it's actually really difficult to find any info about how this is done...!

## Styled Components

### Pros

- [Supports theming](https://www.styled-components.com/docs/advanced#theming)
- Server rendering: [works with streaming HTML](https://www.styled-components.com/docs/advanced#server-side-rendering)

### Cons

- [Don't think it's ready for concurrent mode](https://github.com/styled-components/styled-components/issues/2122)

## emotion

### Pros

- [Supports theming](https://emotion.sh/docs/theming)
- Ready for [React's concurrent mode](https://reactjs.org/docs/concurrent-mode-intro.html). But this is still experimental, and would need to whole app to opt-into using it.

### Cons

- Server rendering: [has trade-offs](https://emotion.sh/docs/ssr): a "basic mode" that doesn't support nth-child selectors, and an "advanced mode" that does, but doesn't work with [React's server streaming](https://reactjs.org/docs/react-dom-server.html#rendertonodestream)

**Comment by andrewn** [comment]
Building on top of either emotion/styled-components, [Styled System](https://styled-system.com/) is an interesting approach for creating themable components. It might have too much of a learning curve for this project though as we want to make getting into the codebase as simple as possible.

**Comment by catarak** [comment]
Since `styled-components` has already been added to the web editor, I'm going to close this issue into #1760.
