### ISSUE TITLE
Text assets's content-type is always text/html

### ISSUE THREAD

**Issue by kazuhikoarase** [processing/p5.js-web-editor#1218]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

I found getFileContent function at /p5.js-web-editor/server/controllers/file.controller.js
But there are nothing considered about content-type and rely on default behavior.

Express official document says
> When the parameter is a Buffer object, the method sets the Content-Type response header field to “application/octet-stream”

> When the parameter is a String, the method sets the Content-Type to “text/html”

https://expressjs.com/en/api.html#res.send

I think that it should be text/javascript(or application/javascript) for .js, application/json for .json and so on.

Thank you.

**Comment by catarak** [comment]
Thanks for reporting! This is definitely a bug, related to #496 but fixing this in a different place.

**Comment by ashu8912** [comment]
Hey @catarak can you guide me where to start to fix this one.

**Comment by catarak** [comment]
You'll need to edit the function [getFileContent](https://github.com/processing/p5.js-web-editor/blob/master/server/controllers/file.controller.js#L111) to change the MIME type based on the file extension.

**Comment by ashu8912** [comment]
ok sending in a pr soon

**Comment by sorcerix** [comment]
Is anyone working on this?
