### ISSUE TITLE
Keep cursor position when tidying code

### ISSUE THREAD

**Issue by jpgualdarrama** [processing/p5.js-web-editor#1223]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
The tidying code feature resets the cursor back to the beginning of the file that was tidied. For long files, this can be irksome, because you then have to scroll back to your position. It would be helpful to keep the cursor position from before the tidying.

**Comment by catarak** [comment]
thanks for the suggestion! i think this feature is a little hard to add because the number of characters/lines might change, and therefore putting the cursor in the "same" position might actually be a different position. i was trying to find example code for why implemented this with `beautify-js` in the first place, and i couldn't find anything, so maybe code tidy in general could use a revisit?

**Comment by ashu8912** [comment]
@catarak I can Work On This Feature if its not already taken.

**Comment by ashu8912** [comment]
#1240 raised a pr that fixes this

**Comment by catarak** [comment]
I notice that with #1240 the cursor jumps forward in the line when running tidy code. I believe the fix for this would be removing the part that adds `INDENTATION_AMOUNT`.

**Comment by satyasaibhushan** [comment]
Hey @catarak,
You are true about `INDENTATION_AMOUNT` causing the cursor jump, 
But, we are not able to sustain the cursor position as required.
For example, In the video provided, the firstly the horizontal position is not retained and next the vertical position is not.
I think this might require opening a new different issue, Please give your thoughts.

https://user-images.githubusercontent.com/40578313/108746157-f6556080-7561-11eb-9f06-6029914b23f8.mov

**Comment by catarak** [comment]
Thanks for posting the video! The library that this project is currently using, [`beautify-js`](https://github.com/beautify-web/js-beautify), does not support code formatting with a cursor position. We can add some code that would get the cursor position pretty close, by preserving its line/column, but this is imperfect when the code formatting changes the number of lines of code. I believe this project would have to switch to using Prettier to fix this, which I just added as a dependency anyway.

**Comment by satyasaibhushan** [comment]
Hey @catarak ,
After hours of searching, I've figured out using prettier. There is still a bit of work to do.
Do you want me to open a new issue by closing this one or should we work on this one itself?

**Comment by satyasaibhushan** [comment]
Never mind,
I've figured it out and am attaching a PR
