### ISSUE TITLE
Flashing / Epilepsy Warning Feature

### ISSUE THREAD

**Issue by violetcraze** [processing/p5.js-web-editor#1224]
#### Nature of issue?

- New feature request

#### New feature details:

Been looking into making the coding train website more accessible and I'd like to add a flashing content warning to community contributions. The majority of links contributed are through the web editor. I think it would be significantly easier to add some automated testing to the web editor.

Here's what I'm thinking the feature would be, it would provide a pop up asking the person to verify that flashing is okay when they first run a sketch for those that have been flagged as violating the [WCAG 2.0](https://www.w3.org/TR/2008/REC-WCAG20-20081211/) rules on flashing content. People who are signed into the editor could save their approval. The tests likely wouldn't be able to account for all human input so people could manually flag their sketches as well.

Upon saving a sketch in the background the website would inject a few lines of code into the sketch and run it in a hidden canvas for a set number of frames or with a time limit. Possibly simulating random mouse and/or keyboard input. The injected code would look for flashing with consistency of more than 3 times a second in general and in the red channel. While looking at the size of the flashing area. If it's detected then it would be flagged.

Additional resources:
https://www.w3.org/WAI/WCAG21/Understanding/three-flashes-or-below-threshold
https://trace.umd.edu/peat

Not sure how realistic this idea is but thought I'd put it out there. Would be happy to work on it though I'm not super familiar with the code base so I'd probably require some guidance.

Love to hear your thoughts @catarak

**Comment by hellonearthis** [comment]
That would take a lot of processing power,  just look at how long codepen takes to generate a screenshot.  
The programmers need to be made more aware of the problem and have an alert.
A general warning on the site helps because generative art often involves flashing screens.

**Comment by violetcraze** [comment]
@hellonearthis Thanks for the input! I think a universal warning maybe good but my concern in doing that is it discourages an entire group of people from using the site. It would definitely be the easiest solution, however I think it's worth investing time in developing ways that those who have trouble with flashing content could participate safely.

I understand the concern around processing power. It maybe possible to work around this with a web worker that uses an [offscreen canvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) that way it wouldn't bog down the user experience. Also adding a per frame time out would be good so if the person is running it on a lower power system then it doesn't effect their ability to use the editor. I'll look into if it would be possible to use p5 in an offscreen canvas with a web worker.

**Comment by catarak** [comment]
Thanks for the suggestion, @violetcraze! This is a great idea. I think a great place to start is how to actually detect sketches that need this on the canvas/iframe? That could be tested separately from the web editor, and could be an awesome library that exists outside of the context of p5.js or the p5.js web editor. Then, we could figure out how to work that code into the web editor.

**Comment by violetcraze** [comment]
@catarak Thanks for the advice. Have started experimenting and it looks like it maybe possible but won't be easy so I'll look into it more over my holiday break. For now I'll close this issue as I think you're right it would be better tackled as a separate project and then possibly added to the web editor.
