### ISSUE TITLE
text editor + canvas sometimes don't load on Safari

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js-web-editor#123]
A student emailed me about an issue where the editor failed to load in Safari. We worked around it by having her use Chrome instead. She was able to see the navigation and title bar for the sketch (play/stop, sketch name, settings), but no text editor or canvas. 

I looked at it with her in class today and the dev tools show the entire editor-preview-container div is missing. Oddly, everything is okay with Safari on my Mac. Let me know if there's any more info I can provide... or if there's a certain browser we should encourage the students to use.

**Comment by catarak** [comment]
I'm going through and closing old issues. Going to close since I haven't heard this happening in a while, feel free to open a new issue!

**Comment by Macintosh-Fan** [comment]
Still a bug
