### ISSUE TITLE
P5 Console is cleared on pause

### ISSUE THREAD

**Issue by amitch6097** [processing/p5.js-web-editor#1231]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Steps to reproduce this bug:

1. Open Editor
2. Add console.log(this) to the draw function
3. Hit play and let the console spew out window objects
4. Hit pause and the console will be cleared

The output in the p5 console should persist until play button is pressed again so that a user can inspect what was printed during the last run.

**Comment by catarak** [comment]
thanks for reporting! i have noticed this and yes, this is annoying and should be fixed.
