### ISSUE TITLE
"Add New Folder Modal Or Any Other Modal" Should have a X Button At Top Right

### ISSUE THREAD

**Issue by ashu8912** [processing/p5.js-web-editor#1235]
- Found a bug
- New feature request

#### Details about the bug: 

- Web browser and version: Google Chrome | 79.0.3945.88 (Official Build) (64-bit)

- Operating System: MacOS Mojave(Version 10.14.6)
- Steps to reproduce this bug:
1.Select Sketch Files On The SideBar 
2.Click Add Folder 
3.The Opened Modal is Uncancellable and forces to create a new folder
A Simple Close Button (X) At The Top That Closes The Modal Would Make It Fine 
<img width="1439" alt="Screenshot 2020-01-13 at 10 08 21 PM" src="https://user-images.githubusercontent.com/30126128/72274885-fd1d5e80-3652-11ea-8226-6b28002d666c.png">

#### Feature enhancement details:
Add A Close Button On The Top Right Corner Of Each Modal

**Comment by ashu8912** [comment]
Ok So Its not visible on local will have to look on this

**Comment by catarak** [comment]
i'm not sure why the icon isn't appearing for you—maybe there's a different error that's causing the icon not to appear?

**Comment by ashu8912** [comment]
Ok So After removing node_modules and reinstalling them makes it work.
Closing this issue as it was my local development setup issue
