### ISSUE TITLE
PropType Validation Fails On Local Development Mode

### ISSUE THREAD

**Issue by ashu8912** [processing/p5.js-web-editor#1236]
- Found a bug

- Web browser and version:79.0.3945.88 (Official Build) (64-bit)
- Operating System: MacOS mojave version 10.14.6
- Steps to reproduce this bug:
On running npm start to start the dev server it fails because of props validation error
Here is the props validation error
<img width="1114" alt="Screenshot 2020-01-14 at 12 31 22 AM" src="https://user-images.githubusercontent.com/30126128/72284770-cbfb5900-3667-11ea-87d1-149adaf29811.png">

The sketch object is missing type for createdAt and updatedAt
<img width="596" alt="Screenshot 2020-01-14 at 12 37 24 AM" src="https://user-images.githubusercontent.com/30126128/72284922-167cd580-3668-11ea-98ca-f6a546d92a7f.png">

**Comment by catarak** [comment]
thanks for reporting! I think this will be fixed when #1164 is merged.

**Comment by simranaggarwal1999** [comment]
Hey! The error is still appearing and the webpage is not opening in the local server mode. When would the error get rectified?

**Comment by ashu8912** [comment]
You can try using docker till then @simranaggarwal1999
