### ISSUE TITLE
Add lint-staged, husky, and pre-commit hooks

### ISSUE THREAD

**Issue by ashu8912** [processing/p5.js-web-editor#1241]
#### Nature of issue?

- New feature request

#### Feature enhancement details:
Add husky and lint-staged to run linting before each commit is made

**Comment by simranaggarwal1999** [comment]
Hey! @ashu8912 Can I work upon this issue?

**Comment by shakti2379** [comment]
Please check similar issues before filing a new one:) 
i think someone already raised this issues #854 here and @catarak also replied to it.

**Comment by ashu8912** [comment]
@shakti2379 thanks for your concern but that issue was closed a year back (closed by author of the issue himself and not by the maintainers). I wanted to discuss this with @catarak as when I first started contributing to processing I went through this problem of making a pr that had linting errors if linting error could be checked on each commit itself that would save a lot of time of the contributor.

**Comment by catarak** [comment]
It would be great to add husky and lint-staged!

**Comment by ashu8912** [comment]
Ok Catrak I am working on this

**Comment by shakti97** [comment]
Are you still working on this issue @ashu8912 , if not I would like to work on this

**Comment by ashu8912** [comment]
Hey @shakti97 i have these changes on my local will push them by tomorrow
