### ISSUE TITLE
Remove "Find Next" and "Find Previous" from Nav dropdown

### ISSUE THREAD

**Issue by simranaggarwal1999** [processing/p5.js-web-editor#1243]
Nature of issue?
- 👍 Found a bug 
- 👍 Existing feature enhancement
- New feature request

Details about the bug: 
- Web browser and version: FireFox
- Operating System:  Windows

- Steps to reproduce this bug:
1. Click Edit in navbar
2. Click Find Next.
3. Click anywhere on the dialog box that pops up other than the text box.
4. The dialog box closes.

Feature enhancement details:
I feel the dialog box should not close this way. Also there should be a find button that would start finding in the document according to the letters typed by the user.

**Comment by ashu8912** [comment]
@simranaggarwal1999 Yes The Find-Next Modal  Should Close Only when The close button is clicked.will have to ask @catarak whether she wants this change,if yes will send a pr that fixes this.

**Comment by catarak** [comment]
Find next should maybe just open the find dialog? The overall find UX is a little off and should be adjusted to work like other text editors (i.e. VSCode).

Related to #942.

**Comment by simranaggarwal1999** [comment]
@catarak I feel Find Next dialog box should find and select the next occurrence of the text specified in the Find dialog box and Find Previous dialog box should find and select the previous occurrence of the text specified in the Find dialog box. Kindly guide me to solve this issue.

**Comment by ashu8912** [comment]
This is a issue with codemirror the find Next and find Prev both doesn't show the desired behaviour or a behaviour that is not similar to what we expect with editors like vscode when we press these combinations.
I have raised a issue regarding this on the codeMirror repo lets see if they add this feature.
https://github.com/codemirror/CodeMirror/issues/6130

**Comment by ashu8912** [comment]
So The CodeMirror editor  doesn't currently supports the behaviour we are thinking of achieving here.

**Comment by ashu8912** [comment]
@catarak what should we do now with the design should we let it the same for now.

**Comment by catarak** [comment]
I think that `Find Next` and `Find Previous` should just be removed from the dropdown because it's confusing. The keyboard shortcut overlay lists those shortcuts anyway.

**Comment by satyasaibhushan** [comment]
Hey @catarak !
I'd like to work on this issue if you simply need to remove the options from the dropdown

**Comment by satyasaibhushan** [comment]
But, there clearly seems to be a focus issue with the `find next` and `find previous` features as sometimes they just go off when clicked on the left part (on the play button or the editor) and they freeze and don't close when clicked on the right part of the screen(on the preview section), which leaves us no option but to refresh the page.
Please look into this!!

**Comment by catarak** [comment]
@satyasaibhushan you can go ahead and work on this one!

also, would you mind putting the other issue you're reporting in a separate issue, with steps to reproduce?

**Comment by satyasaibhushan** [comment]
Hey @catarak, 
I hope this closes the issue. Please check if I did anything wrong.
And I will open another issue as you mentioned :)
