### ISSUE TITLE
Add Auto Complete Feature to sketch code

### ISSUE THREAD

**Issue by ashu8912** [processing/p5.js-web-editor#1248]
- New feature request

#### Feature enhancement details:
Adding Auto Complete Feature To The Sketch Code Will Be Very Nice And Will also help newbies as well as professionals to write fast code.

**Comment by ashu8912** [comment]
I have produced a sample codesandbox that simulates the above behaviour with custom hints
the stylings are a little of in that but i have focused more on how part will fix styling and all if this feature is required
Here is the codesandbox
https://codesandbox.io/s/reverent-minsky-kih4r

**Comment by catarak** [comment]
Merging this issue into #99.
