### ISSUE TITLE
Open/Close Sidebar Button is too small/not noticeable

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1255]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

The button to open/close the Sidebar is really tiny:

<img width="166" alt="Screen Shot 2020-02-12 at 3 52 52 PM" src="https://user-images.githubusercontent.com/6063380/74376678-92298980-4db0-11ea-8934-46f487b091c7.png">

I think it could be a different color, the cursor could be changed to a "->", and it could be the whole left side that is a button that opens (like on the Glitch editor).

**Comment by ashu8912** [comment]
Working On This also what should be the color of the arrow

**Comment by keshav234156** [comment]
@catarak I would like to work on this issue!!

**Comment by keshav234156** [comment]
![Screenshot from 2020-02-21 13-19-12](https://user-images.githubusercontent.com/45951376/75014870-5461ea80-54ad-11ea-8226-706c31afd74a.png)
@catarak  How does it look now?.Should I make the PR or any other changes that you would like to suggest?

**Comment by keshav234156** [comment]
![Screenshot from 2020-02-21 19-44-36](https://user-images.githubusercontent.com/45951376/75041843-63fc2600-54e3-11ea-86aa-d840e34804fb.png)
This looks much better? @catarak ?

**Comment by keshav234156** [comment]
![Untitled_ Feb 21, 2020 8_14 PM (1)](https://user-images.githubusercontent.com/45951376/75044130-1f728980-54e7-11ea-8d35-f5ef3cd6a33b.gif)
