### ISSUE TITLE
[Enhancement] Enable Saving + Opening Projects from LocalStorage

### ISSUE THREAD

**Issue by hydrosquall** [processing/p5.js-web-editor#1258]
#### Nature of issue?

- Presently, if someone attempts the editor without an internet connection, they'll be unable to save their work. 
- This feature would move the application in the direction of a progressive webapp so that the editor can be used by those with intermittent/unreliable internet connections.

#### New feature details:

- In addition to the existing "save to cloud" feature, we could grant someone the ability to save their project to LocalStorage.
- This FR is based on the finding this behavior useful in a different web-based file editor that I've used, which supports in-browser saving of projects consisting of multiple files: https://stoplight.io/studio/

**Comment by catarak** [comment]
Merging this into #103. I really would like to prioritize this issue!
