### ISSUE TITLE
[dev] Cannot resolve module 'react-prefixer'

### ISSUE THREAD

**Issue by zhuoxi** [processing/p5.js-web-editor#126]
After a fresh checkout and ``npm install``, ``npm start`` will encounter:

```
ERROR in ./~/react-split-pane/lib/SplitPane.js
Module not found: Error: Cannot resolve module 'react-prefixer' in ~/p5.js-web-editor/node_modules/react-split-pane/lib
 @ ./~/react-split-pane/lib/SplitPane.js 19:21-46

ERROR in ./~/react-split-pane/lib/Pane.js
Module not found: Error: Cannot resolve module 'react-prefixer' in ~/p5.js-web-editor/node_modules/react-split-pane/lib
 @ ./~/react-split-pane/lib/Pane.js 15:21-46

ERROR in ./~/react-split-pane/lib/Resizer.js
Module not found: Error: Cannot resolve module 'react-prefixer' in ~/p5.js-web-editor/node_modules/react-split-pane/lib
 @ ./~/react-split-pane/lib/Resizer.js 13:21-46
```

Running ``npm install react-prefixer`` will solve this problem.

Is it because ``package.json`` is not requiring ``react-prefixer``?

We could add the following in ``package.json``, after line 95

`"react-prefixer": "^1.1.4",`

**Comment by catarak** [comment]
This is strange since it's a dependency of `react-split-pane`, which should automatically be installed, and therefore shouldn't need to be added to `package.json`. Did you try
```bash
rm -rf node_modules
npm cache clear
npm install
```
