### ISSUE TITLE
Project menu tooltip

### ISSUE THREAD

**Issue by shakti2379** [processing/p5.js-web-editor#1266]
#### Nature of issue?
- Feature Enhancement

#### Details about the bug: 

- Web browser and version: <!-- On Chrome 80
- Operating System: Linux

#### Feature enhancement details:
click on the project menu, hover on any item it will show project menu as tooltip, which is redundant, i think it should either show some more details about the item in tooltip or no need of tooltip there

**Comment by shakti2379** [comment]
if it looks fine, would like to work on it:)

**Comment by ashu8912** [comment]
@shakti2379 I have already made a pr regarding this that pr will fix every svg tooltip realated problem.

**Comment by ashu8912** [comment]
#1259

**Comment by catarak** [comment]
thanks for reporting! you are right that this `title` should be removed. See https://developer.paciellogroup.com/blog/2012/01/html5-accessibility-chops-title-attribute-use-and-abuse/!

**Comment by davidbmx** [comment]
Hi @catarak i create a pr for this issue ref #1382
