### ISSUE TITLE
Inconsistent style while hovering on auto-refresh label

### ISSUE THREAD

**Issue by shakti97** [processing/p5.js-web-editor#1275]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 80

- Operating System: Ubuntu 18.04

- Steps to reproduce this bug:
1. Open the p5.js editor
2. Hover over the `auto-refresh` label in the toolbar

if you check Setting's Accessibility checkboxes label they are working as desired.

**Comment by shakti97** [comment]
hey @catarak , I would like to work on this

**Comment by KKVANONYMOUS** [comment]
@catarak If this is a legit issue, I would like to work on it

**Comment by catarak** [comment]
Given UX conventions for checkboxes, I think all that needs to change is that the checkbox itself needs `cursor: pointer`. You can go ahead and open a PR that does that!
