### ISSUE TITLE
Sidebar Toggle Shortcut

### ISSUE THREAD

**Issue by shakti97** [processing/p5.js-web-editor#1282]
#### Nature of issue?
- New feature request

#### New feature details:
Vscode has shortcut for toggling sidebar, I think it would be better if we have the same feature here also.

**Comment by shakti97** [comment]
@catarak if possible, I would like to work on it:)

**Comment by catarak** [comment]
I'm into this idea! What is a good value for the shortcut? Here's some options:
- Glitch.com uses <kbd>Command</kbd> + <kbd>I</kbd>
- VSC uses <kbd>Command</kbd> + <kbd>B</kbd>
- Sublime Text uses  <kbd>Command</kbd> + <kbd>K</kbd>, <kbd>Command</kbd> + <kbd>B</kbd>
- Atom uses <kbd>Command</kbd> + <kbd>\</kbd>

seems like there's no consensus....

**Comment by catarak** [comment]
in XCode and Sublime Text, <kbd>Command</kbd> + <kbd>B</kbd> is mapped to "Build".

**Comment by shakti97** [comment]
I picked up that command which is being used by popular editor like vscode, codesandbox. I will research on it and get back to you.
