### ISSUE TITLE
MySketches Modal Loader not aligned

### ISSUE THREAD

**Issue by nik72619c** [processing/p5.js-web-editor#1284]
### Nature of issue?

- Found a bug

#### Details about the bug: 

The loader which is displayed in My Sketches modal is not aligned vertically in the centre. Other Loaders inside Modals like my assets is aligned vertically. Therefore, the position of all modals must follow consistency.
![processing-output](https://user-images.githubusercontent.com/30630904/75168745-68c41280-574d-11ea-8559-439dde408b02.png)

- Web browser and version: Google Chrome (version 74.0.3729.157 (Official Build) (64-bit))
- Operating System: Ubuntu v18
#### Steps to reproduce this bug:

- Open the editor and login with your account
- Inside the `My Account` option on the navbar, click on `My Sketches`
- Notice the vertical alignment of the Loader

**Comment by nik72619c** [comment]
I have proposed a fix for this here :- #1285 
@catarak Please let me know if it helps :)

**Comment by catarak** [comment]
thanks for reporting! i agree that it makes sense to center this loader.
