### ISSUE TITLE
ml5 Library doesn't load for new projects

### ISSUE THREAD

**Issue by annabateman** [processing/p5.js-web-editor#1289]
#### Nature of issue?
The ml5 library won't load for new sketches. I used my sketches defined in my account (https://editor.p5js.org/geekmommy/sketches/exk4mkes) and they load and run fine. However, when creating a new sketch with a literal copy/paste of the same code, I get a message that "Uncaught ReferenceError: ml5 is not defined (sketch: line 16)" (see example here https://editor.p5js.org/geekmommy/sketches/eNdOc1oU).

- Found a bug

#### Details about the bug: 

- Web browser and version: Tried on Chrome, IE, Firefox, and Edge
- Operating System: Windows 10
- Steps to reproduce this bug:
Create a new project and try to access the ml5 library

![image](https://user-images.githubusercontent.com/28957684/75205159-0a913280-5741-11ea-9c03-d022d50b43ed.png)

**Comment by DivyamAhuja** [comment]
Actually what you are missing is linking ml5 script in index.html
![Screenshot_20200303-020803](https://user-images.githubusercontent.com/39771050/75715780-fd051b00-5cf3-11ea-8453-0da178ba648c.png)
![Screenshot_20200303-020727](https://user-images.githubusercontent.com/39771050/75715784-fecede80-5cf3-11ea-97d6-a487c81db952.png)
