### ISSUE TITLE
Redundant Search Button

### ISSUE THREAD

**Issue by shakti97** [processing/p5.js-web-editor#1290]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
- Web browser and version: Chrome 80
- Operating System: Ubuntu 18.04
- Steps to reproduce this bug:
1. Open Sketches
2. Start typing, it will show result on change

if the result is showing on Change then there is no need to button for search.

**Comment by shakti97** [comment]
@andrewn if possible, I would love to work on it :)

**Comment by andrewn** [comment]
I see what you mean @shakti97, the submit button to perform a search does seem redundant as the search is performed when text is entered _and_ when the Enter key is pressed.

It's worth checking with @catarak if there's an accessibility reason for the search button?

**Comment by shakti97** [comment]
okay, @catarak can you please share your opinion here

**Comment by catarak** [comment]
I can't really think figure out a reason why we left it in. I think it had been there before the filter onChange was working and then it didn't make sense to take it out? I'm trying to figure out what the right thing to do with respect to web accessibility is but I'm not having much luck...
