### ISSUE TITLE
Shortcut for Example Modal

### ISSUE THREAD

**Issue by shakti97** [processing/p5.js-web-editor#1300]
#### Nature of issue?
- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome 80
- Operating System: Ubuntu 18.04 

#### Feature enhancement details:
Need Shortcut to open Examples directly to ease user experience.

**Comment by shakti97** [comment]
@catarak if possible I would love to take this up:)

**Comment by catarak** [comment]
I don't think it makes sense to add a keyboard shortcut for this!
