### ISSUE TITLE
How to reach Out for GSOC

### ISSUE THREAD

**Issue by ashu8912** [processing/p5.js-web-editor#1304]
Hello,Organisation how can we share our ideas and views or review a pr or get discussion over a raised issue.
I contacted the mentors one month back but no reply yet, which as a contributor feels disheartning  i would love if the slack channel link on the gsoc page should be made an invite link through which students can reach out to the org and share there views.
I know that github issues are not a place to discuss something like this but i couldn't reach out to the org from any other platform.
Please Help.

**Comment by shakti97** [comment]
Yes, I am also facing this issues, there is no way to communicate and discuss our ideas with the mentor. So it will be great if this problem resolves asap.
@andrewn @catarak can you please look at this issue

**Comment by catarak** [comment]
This year I didn't have the bandwidth to respond directly to proposal ideas. I hope y'all found help on the Processing forum!
