### ISSUE TITLE
the while loop makes the browser freeze

### ISSUE THREAD

**Issue by barick56** [processing/p5.js-web-editor#1306]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by barick56** [comment]
hi , i'm writing to report a bug, for a while now , i noticed that the while loop makes any of my browsers freeze, i'm on mac osX

**Comment by ankiiitraj** [comment]
Hi @barick56 , can you share your Code snippet of your code which makes your browser freeze.

**Comment by catarak** [comment]
closing for lack of steps to reproduce. duplicate of #698.
