### ISSUE TITLE
Making files sidebar expansion more intuitive or displaying it expanded by default

### ISSUE THREAD

**Issue by DivyamAhuja** [processing/p5.js-web-editor#1307]
- Existing feature enhancement

The Files sidebar is collapsed by default and it's difficult for new users to find if it even exists or how to open it (That was case for me at least) . So I think it will be better if it was like "Open/Show Files " like something or maybe expanded by default on load
@catarak

**Comment by shakti97** [comment]
yes, catarak already found this issue and open a similar issue #1255 and someone worked on that issue and filed a pr. So please check for similar issue before opening a new. You can discuss your idea on the accessbility of the sidebar toggler there.

**Comment by DivyamAhuja** [comment]
@shakti97 Thanks for marking the issue.... earlier I saw some issues where people had same problem that they didn't notice the arrow button so that's why I raised the issue .
I will close the issue now.
