### ISSUE TITLE
Toolbar too large on projectors 

### ISSUE THREAD

**Issue by demc** [processing/p5.js-web-editor#1310]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

When using a projector to present or teaching using the p5.js editor, the header takes an enormous amount of space. The header is so disproportionally large that this tool is not easy to use in a classroom and a better tool has to be used instead. This should be an easy CSS fix.

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

1. Open p5.js editor in Chrome.
2. Plug into a projector with VGA.
3. Notice that the header is absurdly large and makes the code difficult to read.
4. Use Zoom In and Zoom Out to see how the header is still absurdly large.

**Comment by demc** [comment]
![Screen Shot 2020-03-04 at 11 12 58 AM](https://user-images.githubusercontent.com/3744617/75914566-cd483700-5e09-11ea-9af6-f26930d20ef8.png)

**Comment by catarak** [comment]
Thanks for reporting! I'm sorry you're having issues with the sizing on projectors. But first, I want to reiterate that this is a non-profit open source project supported by volunteer work and grants, and we are doing our best to make it work. It is pretty rude to say "a better tool has to be used instead" and "this should be an easy CSS fix", and I would like to point you to the [p5.js Community Statement](https://p5js.org/community/).

By the header do you mean the toolbar with the play/pause buttons? Do you have a photo of the projection on a screen/wall to demonstrate what you mean?
