### ISSUE TITLE
esc key should hide modal box.

### ISSUE THREAD

**Issue by ankiiitraj** [processing/p5.js-web-editor#1312]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
The box that appears on clicking the add folder/file option onn the editor should close on clicking "esc" key which currently doesn't happens.

**Comment by ankiiitraj** [comment]
If this is ok I would like to work on this feature.

**Comment by ankiiitraj** [comment]
Hello @catarak, Can I work on this? Thanks

**Comment by catarak** [comment]
@ankiiitraj yes!

**Comment by shakti97** [comment]
@ankiiitraj are you still working on this issue , let me know if you need any help:)
