### ISSUE TITLE
Display message of file created

### ISSUE THREAD

**Issue by ankiiitraj** [processing/p5.js-web-editor#1313]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
On adding a new file by typing the file name and hitting "enter", file gets created.
I think on hitting "enter",  text should appears like "file.js was created" and should disappear after few seconds on the modal box.
![Screenshot from 2020-03-06 12-24-34](https://user-images.githubusercontent.com/48787278/76059930-17feb600-5fa6-11ea-91e2-c8ad48e30198.jpg)

**Comment by ankiiitraj** [comment]
If this enhancement is fine to community members I would like to work on this issue.

**Comment by shakti97** [comment]
yes I also think that empty the input box and hide the created message is good, but I was thinking isn't it better to toggle the modal , an open the newly created file on the editor. @catarak  what's your opinion on this?

**Comment by ankiiitraj** [comment]
@shakti97 But this will make creating several files a bit uneasy task.

**Comment by catarak** [comment]
I think this is a good idea! The component [Toast.jsx](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Toast.jsx) should appear and disappear.

**Comment by shakti97** [comment]
Would like to work on this issue , if @ankiiitraj has no issue in letting me work on this.

**Comment by ankiiitraj** [comment]
Hi @shakti97, let me try on this and if I can't do this, you can help me. Thanks

**Comment by shakti97** [comment]
Okay no issue, go ahead @ankiiitraj

**Comment by saijatin28** [comment]
Hello @ankiiitraj @catarak ! Can I take this issue up?

**Comment by ankiiitraj** [comment]
Hi @saijatin28 if @shakti97 is not working on this feel free to take on.

**Comment by catarak** [comment]
@saijatin28 i think you can safely start working on this since there haven't been any updates in a month!

**Comment by saijatin28** [comment]
I figured maybe I should import the [Toast.jsx](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Toast.jsx) into the [NewFileForm.jsx](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/NewFileForm.jsx) . But I am unable to figure out how to proceed further. Any pointers?

**Comment by andrewn** [comment]
@catarak I can give advice with the implementation, but I'm just trying to work out what the behaviour should be?

Do we:
1. close the modal, showing the global "toast" banner containing the message?
2. show the message within the modal below the text input, without closing it?

It feels to me, option 1 is more consistent with behaviour elsewhere in the app?

## 1. Showing global toast

The [`createFile` action](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/files.js#L41-L95) should call `setToastText` and `showToast` when a new file has been created. Both the `if` and `else` branches of the function will need these.

Look at the [create collections action](https://github.com/processing/p5.js-web-editor/blob/45b90163857d6e4e07ccb3418c1a6735da3eba18/client/modules/IDE/actions/collections.js#L53-L54) for an example.

## Showing message within modal

Wait for [`handleSubmit`](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/NewFileForm.jsx#L22) to complete successfully and trigger a state change showing the message in the form. Setting a timeout to "reset" the form afterwards and removing the message.

In addition, the `createFile` action [would need to not close the modal](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/files.js#L61).

**Comment by saijatin28** [comment]
> ## 1. Showing global toast
> The [`createFile` action](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/files.js#L41-L95) should call `setToastText` and `showToast` when a new file has been created. Both the `if` and `else` branches of the function will need these.
> 
> Look at the [create collections action](https://github.com/processing/p5.js-web-editor/blob/45b90163857d6e4e07ccb3418c1a6735da3eba18/client/modules/IDE/actions/collections.js#L53-L54) for an example.

Hey! @andrewn I have added the feature using the above approach and made a PR #1426

**Comment by catarak** [comment]
With #1731 being merged, I feel like that handles this issue.
