### ISSUE TITLE
Use of very small font size

### ISSUE THREAD

**Issue by nik72619c** [processing/p5.js-web-editor#1315]
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Google Chrome (Version 74.0.3729.157 (Official Build) (64-bit))
- Operating System: Ubuntu (v18.04)

#### New feature details:
It would be great to use a bit bigger font size for displaying sub texts. Currently the smallest of the text sizes are unable to read:-

![Screenshot from 2020-03-08 19-23-11](https://user-images.githubusercontent.com/30630904/76164315-e9363a80-6173-11ea-91e6-21b226e00bd4.png)

**Comment by nik72619c** [comment]
@catarak please let me know your views on this :)

**Comment by catarak** [comment]
according to the [design system](https://www.figma.com/file/cyHiandYyEAPj0Kj6tJbHc/p5-design-system-2018?node-id=0%3A1) it should be 12px.
