### ISSUE TITLE
Adding preview for image files in editor

### ISSUE THREAD

**Issue by DivyamAhuja** [processing/p5.js-web-editor#1318]
I was trying to preview an image file in p5 web editor but it was just showing blank screen,
so I was thinking there should be a feature to preview images, 3d models, audio etc.

#### Nature of issue?

- New feature request
![Screenshot from 2020-03-09 20-38-14](https://user-images.githubusercontent.com/39771050/76228356-a09b8180-6246-11ea-9a32-9b2138645add.png)

#### New feature details:

Adding preview for media like images, audio, 3d models etc.

**Comment by devashish1099** [comment]
if its required @catarak i would like to work on this issue

**Comment by catarak** [comment]
I think this is a great idea! It is in fact already captured on #57.
