### ISSUE TITLE
Array consoling bug

### ISSUE THREAD

**Issue by Poupas09** [processing/p5.js-web-editor#1319]
**Nature of issue**

- Found a bug

Details about the bug: 
Consoling an array before and after a change gives you the same output
Is there an explanation on why this is happening?

- Web browser and version: Chrome
- Operating System: Windows

https://editor.p5js.org/Poupas/sketches/EdREbC7w

**Comment by Poupas09** [comment]
I also notice that Chrome's console gives me the correct output

**Comment by shakti97** [comment]
Thanks for reporting this issue but someone already raised this issue, you can follow up here #1055
