### ISSUE TITLE
Adding brazilian portuguese developer docs

### ISSUE THREAD

**Issue by Phe0** [processing/p5.js-web-editor#1320]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Add a folder inside the developer_docs folder containing the same developer docs translated to portuguese

**Comment by catarak** [comment]
Awesome! If I make changes to the English docs, would it be possible to get updates to these docs as well?

**Comment by Phe0** [comment]
@catarak sure!!
