### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by JPatagonico** [processing/p5.js-web-editor#1324]
#### Most appropriate sub-area of p5.js?

- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [x] Other (specify if possible)

#### New feature details:
Autocomplete for P5.JS in both the online editor and the Processing editor

**Comment by catarak** [comment]
Duplicate of #99.
