### ISSUE TITLE
not able to load sound from different origin 

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js-web-editor#1325]
#### Nature of issue?
-feature enhacement 

Not able to loadSound from different origin .
### i know this is not a bug ,but a simple user must be able to load a audio from external link, this will increase the use case of web-editor !
i first thought the issue is with p5.sound but it looks like it belongs here !
![corsISSUe](https://user-images.githubusercontent.com/43696525/76809279-4f742a80-6810-11ea-9927-a6b44f961646.png)

-feature enhancement

- Web browser and version: 

chrome

- Operating System

windows

**Comment by catarak** [comment]
In your example here you've put in a youtube url, which returns an entire web page. You need to put in a url to a specific sound file, something like `http://example.com/data/loop.mp3`.
