### ISSUE TITLE
Log styling in console

### ISSUE THREAD

**Issue by zhuoxi** [processing/p5.js-web-editor#133]
Currently, if there are only 2 logs in the console, each of them will occupy half of the height of the console panel.

![image](https://cloud.githubusercontent.com/assets/8460819/19181910/183fb6c6-8c3e-11e6-9f16-358bad8c8691.png)

Would it look better if each of them only takes one line, even if there are only 2 logs?

![image](https://cloud.githubusercontent.com/assets/8460819/19181943/37fd3cae-8c3e-11e6-9de9-da335882dfeb.png)

**Comment by catarak** [comment]
You are definitely correct! I've noticed this but I haven't gotten a chance to fix it as it is minor.
