### ISSUE TITLE
How to add sound in web-editor

### ISSUE THREAD

**Issue by endurance21** [processing/p5.js-web-editor#1331]
Not able to add and play either my local audio files.
Also no option to upload the files from local computer to web-editors!
if I am missing any documentation regarding this, please help!

**Comment by aldrinjenson** [comment]
Sound is working perfectly fine on the web-editor.
You can add local files by dragging and dropping to the modal which pops up when clicking on the add File button.
Please check out this video for further clarification. 

https://youtu.be/Pn1g1wjxl_0

**Comment by endurance21** [comment]
@AidanNelson thanks that helped !
but I highly recommend having a documentation for this on the website itself!

**Comment by LABCAT** [comment]
For anyone looking looking for the answer to this watch the following video from the 14:30 mark:
https://www.youtube.com/watch?v=x1rJJRVTpAI
