### ISSUE TITLE
Increase Font Size for the Invalid File type message 

### ISSUE THREAD

**Issue by aldrinjenson** [processing/p5.js-web-editor#1336]
#### Nature of issue?
- Existing feature enhancement

![Screenshot_2020-03-21_04-14-07](https://user-images.githubusercontent.com/53407417/77211665-ab012980-6b2a-11ea-8b78-44eb07d0ba7a.png)

#### Details about the Issue: 

Currently, when trying to add a new file from the side-nav, if the file type is not supported, the warning-message shown is of very small font-size and hence it is really difficult to read. Proper readability is possible only if the window is zoomed to about 130%. 
The same problem is also there for the message shown when adding a new folder of some extensions as well.

Maybe this won't affect everyone, but for certain folks the font-size could be a difficulty.

#### New feature details:
Kindly increase the Font-Size of the warning message.

**Comment by shakti97** [comment]
Yes this is an accessibility issue and the team is working on this type of issue , will update you soon. Thanks for reporting

**Comment by catarak** [comment]
Thanks for reporting! You are right, according to the [design system](https://www.figma.com/file/cyHiandYyEAPj0Kj6tJbHc/p5-design-system-2018?node-id=0%3A1) this should be 12px font size.

**Comment by shakti97** [comment]
Can I work on this issue @catarak ?
