### ISSUE TITLE
"Speed reduced by 2.5X" dismiss button

### ISSUE THREAD

**Issue by moacdieh** [processing/p5.js-web-editor#1341]
#### Nature of issue?

Add a dismiss button to the speed reduced toast, because it hides the code (or change it's display)
- New feature request

![image](https://user-images.githubusercontent.com/16903864/77530713-11bb7580-6e92-11ea-8047-38ef7c28a95d.png)

It covers the code.

**Comment by catarak** [comment]
I have no idea what this overlay is? It must be a browser extension/plugin you have installed since this is not part of the web editor.
