### ISSUE TITLE
getting_started.md file missing in the developer_docs directory

### ISSUE THREAD

**Issue by mjaything** [processing/p5.js-web-editor#1343]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome Version 80.0.3987.132
- Operating System:  MacOS Catalina Version 10.15.3
- Steps to reproduce this bug: Click [Getting Started](https://github.com/mjaything/p5.js-web-editor/tree/master/developer_docs) of the README.md in the developer_docs directory

404 This is not the web page you are looking for. [Link](https://github.com/mjaything/p5.js-web-editor/blob/master/developer_docs/getting_started.md)

#### Feature enhancement details:
Either remove 'Getting Started' in the README.md or add getting_started.md file

#### New feature details:

**Comment by andrewn** [comment]
#1335 removes the link to "Getting Started" so I'm going to close this issue.
