### ISSUE TITLE
Title typo of the installation.md in developer_docs directory

### ISSUE THREAD

**Issue by mjaything** [processing/p5.js-web-editor#1344]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Spotted the title typo of the installation.md in developer_docs directory
- Web browser and version:  Version 80.0.3987.132
- Operating System: MacOS Catalina Ver 10.15.3
- Steps to reproduce this bug:
See the first line of the installation.md in developer_docs directory. [Link](https://github.com/processing/p5.js-web-editor/blob/master/developer_docs/installation.md)

#### Feature enhancement details:
Simply remove 'Development' on the first line of the document.
'Development Installation' → 'Installation'

#### New feature details:

**Comment by andrewn** [comment]
Thanks for opening this issue, but I'm not sure this is a typo. Having "Development Installation" in the title makes it clear that the instructions relate to installing a development environment.

I'm going to close, but reopen if you think the title could be better or is unclear.

**Comment by mjaything** [comment]
@andrewn Andrew, thanks for handling it. I thought it was a typo, because there are some inconsistencies. The file name is installation.md, not development_installation.md. If you take a look at all the other files in the [developer_docs directory](https://github.com/processing/p5.js-web-editor/tree/master/developer_docs#list-of-documents), the first line of each file is same as its file name. Your explanation also makes sense, but I found it confusing while translating docs into Korean. I think this might also confuse other translators in the future, but I do not think this is an urgent issue, thus I will leave it there.
