### ISSUE TITLE
No Username in share link in ShareModal Component

### ISSUE THREAD

**Issue by gruselhaus** [processing/p5.js-web-editor#1349]
#### Nature of issue?

- Found a bug

***reproducible with https://editor.p5js.org/danno484/full/s_tE8ND4R***

#### Details about the bug: 

<img width="486" alt="Bildschirmfoto 2020-03-27 um 22 47 48" src="https://user-images.githubusercontent.com/33380107/77803639-e1382f00-707d-11ea-9842-aef39daaed90.png">

https://github.com/processing/p5.js-web-editor/blob/b8d47c60b735a69ab8637e81e74b2903dddc46eb/client/modules/IDE/pages/IDEView.jsx#L418

Probably does this property not exist `this.props.ide.shareModalProjectUsername`.

**Comment by catarak** [comment]
Thanks for reporting! I am able to reproduce. I think the issue is that the ShareModal is connected to the wrong username—it's trying to fill in the current user's username rather than the the username of the user that the sketch belongs to.
