### ISSUE TITLE
Add Korean Translation

### ISSUE THREAD

**Issue by min-kim42** [processing/p5.js-web-editor#1350]
#### Nature of issue?

- New feature request

#### New feature details:
I have translated two documents([README.md](https://github.com/processing/p5.js-web-editor/blob/master/README.md), [installation.md](https://github.com/processing/p5.js-web-editor/blob/master/developer_docs/installation.md)) into Korean. However, I am not sure where to add these translated files. Could anyone let me know the good place to put them? Thanks!

**Comment by catarak** [comment]
Thank you! In your PRs you have put them in the right place ✨

**Comment by mjaything** [comment]
Thanks for confirming @catarak !
