### ISSUE TITLE
file upload graphic issue

### ISSUE THREAD

**Issue by daniel-n-kaye** [processing/p5.js-web-editor#1352]
When I upload multiple files (on chrome OR edge) the loading bars graphics never seem to work right, but the uploading works! see the attached screen shot

- Found a bug

#### Details about the bug: 

- Web browser and version: Microsoft Edge - Version 80.0.361.69 (Official build) (64-bit)
- Operating System: Windows 10 Home - 18362.720
- Steps to reproduce this bug: Upload multiple files (using drag and drop) to p5.js web editor

-my first time reporting a bug/issue, hope I did it right!
![p5js web editor file upload graphic error](https://user-images.githubusercontent.com/62715496/77926726-7270f680-7274-11ea-8a14-d0acd7ab1e00.JPG)

**Comment by catarak** [comment]
Thanks for reporting! I believe this is captured as #389.

**Comment by catarak** [comment]
The "file" icon is attempting to denote that these are "files" (as opposed to a "folder"), but yes, it doesn't match the media type.
