### ISSUE TITLE
Collections adding multiples

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js-web-editor#1353]
When adding sketches to a collection there ends up being multiples added.

To reproduce:
 create a collection
 add a sketch (1 sketch in the collection)
 add sketch (now there are three sketches in the collection, 2 of the first sketch added, plus this)
 add sketch (now there are 5 sketches, 2 of the first and 2 of the second, plus this)

ect ect ...

https://editor.p5js.org/slow_izzm/collections/qK_4WYQiT

Tested on both Chrome and Firefox both with same result.

**Comment by ankiiitraj** [comment]
Looks like this has been fixed. I can't reproduce this on Firefox

**Comment by violetcraze** [comment]
@ankiiitraj Had the same problem a couple minutes ago using firefox.

When the page is refreshed the first sketch is duplicated in the list. You can see in the screen shot that there are 21 sketches but if you go to the page there are now 22. https://editor.p5js.org/codingtrain/collections/xiEko8cTN

![Screenshot at 2020-04-03 10-44-07](https://user-images.githubusercontent.com/43045568/78385660-74e78f00-7599-11ea-9340-b1e2485f9cfe.png)

**Comment by catarak** [comment]
Thanks for reporting! I'm not able to reproduce this right now, so any other steps/context would be helpful.

**Comment by slowizzm** [comment]
[screen-recording.zip](https://github.com/processing/p5.js-web-editor/files/4452046/screen-recording.zip)

**Comment by catarak** [comment]
Thank you! This is really helpful.

**Comment by catarak** [comment]
It seems to only add multiple sketches when the collection has just been created, but if you navigate away and then open the collection again, it doesn't add multiples.

**Comment by slowizzm** [comment]
> 
> 
> It seems to only add multiple sketches when the collection has just been created, but if you navigate away and then open the collection again, it doesn't add multiples.

I just re-opened that collection I used to screen-record and it is still adding multiples. I navigated out and back in (several times), still an issue.

**Comment by catarak** [comment]
Think I figured out the issue and managed to fix it!

**Comment by slowizzm** [comment]
> 
> 
> Think I figured out the issue and managed to fix it!

No longer seems to be an issue on my end. Thank you
