### ISSUE TITLE
Cannot upload font (.ttf) file anymore

### ISSUE THREAD

**Issue by amozeng** [processing/p5.js-web-editor#1354]
Hi, the new version of web editor no long support drag to upload file, and limited the file format to only .js, .css, .json, .txt, .csv, .tsv, .frag, and .vert.
And I no longer can upload my font file anymore, which is a huge loss for me cos I am trying to make some project using different fonts with p5.js and share it to my co-worker by web editor...
Can we bring the function back again?
Thank you so much!

**Comment by NikitaChernenky** [comment]
+1. Can't drag and upload files to the folder

**Comment by catarak** [comment]
Hi @amozeng! You need to select "Upload file" rather than "Create file" in the dropdown.
