### ISSUE TITLE
collection with many items, background color does not extend, layout issue, easy css fix

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js-web-editor#1355]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Firefox 74.0
- Operating System: Mac OS 10.13.6
- Steps to reproduce this bug: add many sketches to a collection

It looks like the CSS is set on the body: height: 100%; is causing issues in FF with long collections for me, un checking height: 100%; solves the problem.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1385996/78031264-ebca2100-7328-11ea-8a16-8b736f3cf187.gif)

**Comment by totalcloud-tc** [comment]
Thanks for reporting this issue @bmoren . Will work on it

**Comment by shakti97** [comment]
Thanks for reporting this issue @bmoren . Will work on it

**Comment by catarak** [comment]
Thanks for reporting!
