### ISSUE TITLE
Can't upload a file to a folder

### ISSUE THREAD

**Issue by NikitaChernenky** [processing/p5.js-web-editor#1361]
Hi there!
I am no longer able to upload an image into a folder. So when I create a new project and add a new folder. If I click on this folder, I am only able to Add File (Create) and not actually Upload File. So I am unable to upload an image into a folder.

Details about the bug:
p5.js version: - 0.10.2
Web browser and version: Version 80.0.3987.163 (Official Build) (64-bit).
Operating System: Windows 10 Home
Steps to reproduce this:
Create a new project -> Add folder -> Click arrow-down menu and you won't see upload file option

**Comment by catarak** [comment]
Thanks for reporting! I'm able to reproduce.

**Comment by knectardev** [comment]
awesome! I noticed it was fixed / working just earlier today.

**Comment by nanselmo** [comment]
Hi, I'm experiencing the same error. I can create a new file, but don't see an option to upload a file. 

Details about the bug:
p5.js version: - the official p5 editor
Web browser and version: Google Chrome
Operating System: Chrome OS
Steps to reproduce this:
Create a new project -> Add folder -> Click arrow-down menu by Sketch Files and you won't see upload file option

**Comment by nanselmo** [comment]
I read https://github.com/processing/p5.js-web-editor/issues/825, and I realize I was not logged in. Apologies.
