### ISSUE TITLE
Can't upload image to a folder

### ISSUE THREAD

**Issue by NikitaChernenky** [processing/p5.js-web-editor#1362]
Hi there!
I am no longer able to upload an image into a folder. So when I create a new project and add a new folder. If I click on this folder, I am only able to Add File (Create) and not actually Upload File. So I am unable to upload an image into a folder.
#### Details about the bug:

- p5.js version: - 0.10.2 
- Web browser and version:  Version 80.0.3987.163 (Official Build) (64-bit). 
- Operating System: Windows 10 Home 
- Steps to reproduce this:
-Create a new project ->  Add folder -> Click arrow-down menu and you won't see upload file option

**Comment by maartenwijntjes** [comment]
I got the same problem, on a Mac+safari/chrome/firefox, I guess it is not related to the browser. Did this maybe happen during the editor redesign?

**Comment by hellonearthis** [comment]
It's a security feature of the browsers to prevent cross origin loading.
https://stackoverflow.com/questions/50445639/fetch-api-cannot-load-file-c-users-woshi-desktop-p5-p5-json-birds-json-url

**Comment by slowizzm** [comment]
Same ... Unable to upload any files into a folder. the only option is to 'Create File'.

Firefox/Chrome/Edge

**Comment by maartenwijntjes** [comment]
> It's a security feature of the browsers to prevent cross origin loading.
> https://stackoverflow.com/questions/50445639/fetch-api-cannot-load-file-c-users-woshi-desktop-p5-p5-json-birds-json-url

no this is not the problem as far as i can tell (i thought that occurs when you use an image from a different server), it is purely a function that is
suddenly gone. My students also experienced it, somebody who is making the editor (which is really cool and new collection feature is great!) should maybe check it out.

**Comment by catarak** [comment]
Fixed as #1361.

**Comment by zapzapparoo** [comment]
Hi. Make sure you are logged in! :)
