### ISSUE TITLE
Why does the error comes even though the function is defined?

### ISSUE THREAD

**Issue by Rohitaicyber** [processing/p5.js-web-editor#1363]
here is the link to my project https://editor.p5js.org/rohitgokul817/sketches/yhOcLU2KX

please help me to figure out the error the function is defined buti am getting the error Uncaught ReferenceError: antsweets is not defined (sketch: line 164)

please help me as soon as possible

**Comment by catarak** [comment]
This is the place to submit bugs and feature ideas for the web editor. To get help with p5.js code, I recommend posting to the [Processing forum](https://discourse.processing.org/) or StackOverflow.
