### ISSUE TITLE
comments in high contrast theme no-longer greyed out

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js-web-editor#1376]
#### Nature of issue?

The comments in the high-contrast theme are no longer grey, they are now the same white as statements. This seems like an error to me and If I recall they were grey in the past?

- Found a bug

#### Details about the bug: 

<img width="580" alt="Screen Shot 2020-04-08 at 3 00 01 PM" src="https://user-images.githubusercontent.com/1385996/78828165-e2d0f380-79a9-11ea-99b4-27098a27ddda.png">

- Web browser and version:  FF 74.0.1 (64-bit)
- Operating System: MACOS 10.13.6 (17G65)

**Comment by catarak** [comment]
thanks for reporting! i believed this is due to #1360 being merged, which i will revert now.
