### ISSUE TITLE
Attempted to save stale version of project

### ISSUE THREAD

**Issue by MiWeiss** [processing/p5.js-web-editor#1383]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: `Chrome Version 80.0.3987.149 (Official Build) (64-bit)`
- Operating System: `Win 10`
- Steps to reproduce this bug:  `Unclear`

When I worked on a previously saved sketch, I noticed it cannot be saved. Neither using [Ctrl + s] nor via the menu. Recording network traffic, I saw that the following request failed:
![image](https://user-images.githubusercontent.com/4815944/78912756-47628000-7a88-11ea-9e11-aa07a8a27519.png)

with message
`"Attempted to save stale version of project."`

Most dangerously, no error is shown. Likely, a user will not notice that the saving failed.

Note: After refreshing the page (and losing any unsaved changes), the sketch can now be saved.

**Comment by catarak** [comment]
Thanks for reporting! I'm sorry this happened. There's some code to protect you if you have multiple different versions of a sketch open, but there's some bugs with it that have been hard to track down.

This has come up in the context of #1337, as to support love collaboration features would involve first upgrading how sketch updates are saved.

**Comment by shakti97** [comment]
I have done some investigation over this and found that we already have the stale project error handling code. But still no message is displaying, checking where we are going wrong. Will update you soon.

**Comment by shakti97** [comment]
Got the point causing this issue, will create the pr.

**Comment by catarak** [comment]
i'm not sure if #1404 fixes this, but it certainly helps!!!
