### ISSUE TITLE
Images in folder on p5 web editor upload but don't load

### ISSUE THREAD

**Issue by Sophi333** [processing/p5.js-web-editor#1385]
Hello,

So I have tried in different sketches, fully logged in and such like to run sketches with images but the interface always has a problem. They are uploaded in the right size/ file type and coded correctly but editor just doesn't like using uploaded images and wants me to use a local host via github- that seems like a bit of a weird limitation since the space is available!? 

I tried doing a search on this but there isn't much about it> que pasa?

Thanks

**Comment by slowizzm** [comment]
I just tested on both Firefox and Chrome. Unable to reproduce, all works fine for me.

**Comment by catarak** [comment]
Can you post a link to your sketches so I can try to reproduce? Thank you!
