### ISSUE TITLE
Keyboard Shortcuts - Organizational Headers

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1386]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

The Keyboard Shortcut overlay is currently just a long list of shortcuts. It should have organizational headers, so it's easier to find the shortcuts you're looking for.

Reference of other sites:
<img width="608" alt="Glitch Keyboard Shortcuts" src="https://user-images.githubusercontent.com/6063380/78938511-5a715200-7a80-11ea-86d7-4803aaabe223.png">
<img width="825" alt="CodePen Keyboard Shortcuts" src="https://user-images.githubusercontent.com/6063380/78938515-5d6c4280-7a80-11ea-9aa4-e281ae409b53.png">

It could also be nice to add to this design a box/border around the keyboard shortcuts, as these examples have done as well.

**Comment by shakti97** [comment]
Would like to work on this feature,

**Comment by slowizzm** [comment]
I have noticed there are some shortcuts not listed ... such as ctrl+shift+up/down to move line(s), ctrl+d to select similar. I wonder if there are others, how can we see a complete list of shortcuts?

Also, is there an issue open to add suggestions such as alt+shift+up/down to duplicate line(s)?

**Comment by catarak** [comment]
@slowizzm Those are Sublime Text editing shortcuts. I think that rather than trying to list them all (because there are a ton!) this overlay should link to a page like https://shortcuts.design/toolspage-sublimetext.html.

**Comment by slowizzm** [comment]
@catarak Ahh ... thanks. I didn’t realize the shortcuts were mirroring Sublime. Is it possible to use vscode shortcuts? Maybe this needs to be a feature request? Guess there could be an option in settings to choose either sublime/vscode shortcuts as well as customize.

**Comment by catarak** [comment]
Unfortunately VSCode bindings don't exist right now for CodeMirror, only [vim, emacs, and Sublime](https://github.com/codemirror/CodeMirror/tree/master/keymap). Someone could be a hero and work on this.

I want to limit the amount of text editor customization here as it can be overwhelming for beginners. I'm open to discussing whether keyboard shortcuts are beginner friendly or not! To me this brings up an important question which is "what's the standard for code editing keyboard shortcuts?" Anyway, feel free to move this discussion into a feature request.

**Comment by shakti97** [comment]
I have started working on implementing this feature, dividing keyboard shortcut between Editor Focus and Editor Command has no meaning because almost all the shortcut will only work when we have focus on the editor

**Comment by shakti97** [comment]
@catarak I was thinking to divide them between Text Editing and Advanced/Helper Heading like this
![IMG_20200419_021756](https://user-images.githubusercontent.com/30585570/79670991-74c7d000-81e4-11ea-8fa2-ae6271e3f448.jpg)

Would like to know your opinion over this @catarak

**Comment by catarak** [comment]
Naming these headers is really hard! Even the heading options on Glitch/CodePen are not amazing...

I think "Text Editing" is pretty good. I'm not sure what the other commands should fall under... "Advanced/Helper" feels vague, "Global" feels vague...
