### ISSUE TITLE
Add visual indication upon save failure

### ISSUE THREAD

**Issue by tirtawr** [processing/p5.js-web-editor#1393]
## Nature of issue?

- New feature request

#### New feature details:

This is touched a little bit at #1383, but I think the feature is important enough to have its own scope.

Whenever there's a failure on saving a file, there is no visual indication to the user that something has gone wrong. Currently, the user will only know if something is wrong if they are meticulous and realizes that there's no popup telling them that the project saved successfully. I think this is too much to ask of them.

It would be great if we can add a popup to let the user know that something is wrong.

**Comment by catarak** [comment]
Thanks for the suggestion! Maybe this could be just as simple as showing the Toast component on an error. Maybe the Toast component could have a visually different error state.

**Comment by elit-altum** [comment]
@catarak Can I work on this?

**Comment by catarak** [comment]
@elit-altum yes!

**Comment by RickBr0wn** [comment]
> @catarak Can I work on this?

Hey @elit-altum, How are you getting on with this. If progress has stalled, no worries, I'd be happy to take it on. Let me know ☺️

**Comment by elit-altum** [comment]
Hey @RickBr0wn You may go ahead with this! Thank you!

**Comment by saijatin28** [comment]
@RickBr0wn Hey! Since it's been a while, no issues if the progress has stalled. I've identified the error and will submit a path soon.
