### ISSUE TITLE
Upgrade default template to p5.js 1.0.0

### ISSUE THREAD

**Issue by jeremydouglass** [processing/p5.js-web-editor#1396]
#### Nature of issue?
- New feature request

#### Feature enhancement details:
Upgrade default template to p5.js 1.0.0 (from 0.10.2)

Currently creating a new sketch points to p5.js 0.10.2.At present, the reference is out of sync with the editor. For example, that Vector.reflect is listed in the reference, but not available through the web editor. For an example support discussion, see:
https://discourse.processing.org/t/uncaught-typeerror-velocity-reflect-is-not-a-function/19402?u=jeremydouglass

**Comment by DivyamAhuja** [comment]
@ I would like to suggest something like Development Mode where user can use the latest build of p5 or can choose from previous stable versions. This makes finding bugs easier.

**Comment by catarak** [comment]
@DivyamAhuja you can technically already do this! If you open the left sidebar and click on `index.html`, you can edit that file. By default, it looks like this:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/addons/p5.sound.min.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css">
    <meta charset="utf-8" />

  </head>
  <body>
    <script src="sketch.js"></script>
  </body>
</html>
```
You could put in a different version number on the lines that load p5.js:
```html
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/addons/p5.sound.min.js">
```
To use a development version, I think you'd have to clone the p5.js repository, build the library, and upload it manually to the web editor using the file uploader.

**Comment by DivyamAhuja** [comment]
@catarak Yes I know about this way of changing version but I was seeing that people are reporting bugs or features that were already fixed in p5.js . So I was thinking if there can be a more intuitive menu in p5 web editor that can let us pick versions and maybe it can load latest unofficial build of p5 once every day. This will be useful especially when working in mobile devices as currently changing index.html or even sketch file in mobile devices is such a hassle.

**Comment by catarak** [comment]
I hear you! I think what you are suggesting is captured as #4 within the context of the web editor. To create a daily build on p5.js, I think there would need to be a CI/CD or GitHub action or something set up for p5.js, and I would suggest opening an issue in the [p5.js repository](https://github.com/processing/p5.js).

**Comment by catarak** [comment]
This will be fixed for the next release 🎉
