### ISSUE TITLE
File uploader bugs

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#14]
In the current editor, I have begun to add media uploads. As this is a fairly complicated task, as it stands right now, it only works for:
- jpg/jpeg, png, gif (single frame), and tif
- If you put it in your JS files. Will not resolve media in HTML and CSS. 
- If you download the project as a zip, it will download the images.

Eventually you will be able to uploads fonts, videos, and so on, and will parse it in all file types, but for now, I think it's good enough for teaching basic p5.js.

**Comment by catarak** [comment]
Next step: uploading text files! I think I'll need to add a file limit size, especially for files types like .json, which can be really big, and those will get uploaded to S3 rather than to the mongo database.

**Comment by REAS** [comment]
I'm making a note that I don't think SVG uploading is working. This isn't mentioned in the first comment, but I'm assuming it hasn't be attempted yet.

**Comment by shiffman** [comment]
To add to the pile of files that students are trying to upload to the editor, I had one working with `loadModel()` this morning that wanted to upload an OBJ file.

**Comment by catarak** [comment]
I can handle this file types no problem! I just need to whitelist them.

**Comment by catarak** [comment]
Just tried adding SVG's but I couldn't get it to work because of [processing/p5.js/#1648](https://github.com/processing/p5.js/issues/1648). Obj files are now working though, still to be deployed.

**Comment by catarak** [comment]
just added support for font files: `.tff` and `.otf`, not yet deployed.

**Comment by REAS** [comment]
The interface makes it feel like more than one file can be uploaded at a time, for example to load three images with one drag into the box, but only one is uploading at a time.

**Comment by catarak** [comment]
i'm going to close this--there's a separate ticket for the UX for the uploader being confusing (#271), and if there are bugs this ticket can be reopened.
