### ISSUE TITLE
Results almost unreadable when using dark or high contrast themes

### ISSUE THREAD

**Issue by SamBozman** [processing/p5.js-web-editor#1400]
I am using Firefox 75.0 (64-bit) in Linux Mint 19.1 Cinnamon.
I have vision problems so in your P5.js editor I chose high contrast for my programming environment. 
However, the text results are in a black font and it is almost invisible on the dark background. I think the font should be switched to white if a user chooses to use either dark or high contrast within this editor.
Thank you for listening.
Sam Bozman

**Comment by elit-altum** [comment]
Hey @SamBozman thank you for notifying! Could you please attach a screenshot of the issue? It would really help us resolve it. 
Sorry for the inconvenience!
Thank you!

**Comment by catarak** [comment]
thanks for reporting! i've been working really hard on adjusting all of the colors in #1406. this issue should hopefully be fixed when that PR is merged, and it would be amazing if you could test after merging as well!

**Comment by SamBozman** [comment]
No problem. Once you have released the new version, I will test this colour problem. Thanks
Sam

**Comment by catarak** [comment]
@SamBozman it has been merged, and your testing would be extremely useful!

**Comment by leemark** [comment]
Hi @catarak I have run into this as well, here is a screenshot of how text looks in the Preview window in Dark mode, but in High Contrast mode it is similar, defaulting to black text on a very dark background:
![image](https://user-images.githubusercontent.com/3521469/111940567-b4520880-8a94-11eb-9d98-d76f53ca52e9.png)
Here's an example of a sketch that displays this issue: https://editor.p5js.org/ml5/sketches/XCFPKqIKrt

**Comment by catarak** [comment]
@leemark turned your comment into a new issue at #1852.
