### ISSUE TITLE
Bug: Navigation/Sketches bug

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js-web-editor#1401]
When viewing another users gallery then selecting 'My Account' > 'My Sketches', the user updates (can also be seen in the url), but the gallery of sketches does not, upon refreshing then the gallery will update to reflect correct user. If you are to click the browsers `Go Back` it has the same issue until refreshing the page. 

- Found a bug

Chrome/Firefox

View a users sketches (not your own)
My Account > My Sketches
Notice the url has updated, but the sketches have not
Refresh the page
Select browsers Go Back
Notice the url has updated, but not the sketches

![Annotation 2020-04-22 153802](https://user-images.githubusercontent.com/14972059/80031572-87c1f500-84af-11ea-8674-505d19cd77eb.png)
![Annotation 2020-04-22 153827](https://user-images.githubusercontent.com/14972059/80031589-8c86a900-84af-11ea-9705-2cfd8f8b41a0.png)
![Annotation 2020-04-22 153843](https://user-images.githubusercontent.com/14972059/80031605-901a3000-84af-11ea-9b6a-1de77dad76c5.png)
![Annotation 2020-04-22 153907](https://user-images.githubusercontent.com/14972059/80031616-91e3f380-84af-11ea-8b03-b2b12a1a419c.png)
![Annotation 2020-04-22 153924](https://user-images.githubusercontent.com/14972059/80031625-93152080-84af-11ea-8e82-de6a6e116cb4.png)

If I now Go Back, the issue happens again.

**Comment by andrewn** [comment]
Thanks so much for the detailed bug report! 

I've pushed an update that should fix this. 🎉
