### ISSUE TITLE
Sign up using socials (ex. Github, Google)

### ISSUE THREAD

**Issue by mattfan00** [processing/p5.js-web-editor#1402]
#### Nature of issue?

- New feature request

#### New feature details: 

When signing up for a new account on the p5.js web editor, right now the only way to sign up is by entering in your email and username manually. This is pictured below: 

![image](https://user-images.githubusercontent.com/30060256/80048110-3fb9c700-84dd-11ea-90f9-cb23bb5f652a.png)

However, when logging in, the log in page contains ways to log in through social accounts like Github and Google. This is pictured below: 

![image](https://user-images.githubusercontent.com/30060256/80048234-96270580-84dd-11ea-90ec-5c5918cb195d.png)

I think, in terms of UX, it would be useful to include the option to sign up through social accounts on the sign up page, instead of it being located just on the log in page. 

Thank you for considering this feature request!

**Comment by catarak** [comment]
Thanks for the feature suggestion! The underlying technology already works, to sign up with GitHub or Google, it's just a matter of putting those buttons on the sign up page 😸

**Comment by hmaddisb** [comment]
Hello!

I am new to contributing to open source projects. As a coincidence when I was looking through the user interface I started thinking of the same idea as presented in this issue.  Therefore, I am interested in working on this issue, is that OK?
