### ISSUE TITLE
Bug: broken scrolling in Add to collection window

### ISSUE THREAD

**Issue by Number16** [processing/p5.js-web-editor#1412]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome and Safari
- Operating System: macOS
- Steps to reproduce this bug: Have many collections (more then 10 for my screen size) -> go to any sketch -> File -> Add to Collection -> Can't scroll to the bottom

I created collections for all my projects and found that the scrolling in Add to Collection menu is broken. Here is the screen shot:

![image](https://user-images.githubusercontent.com/20598349/80859421-a0799a00-8c69-11ea-9b98-137381b5f5cb.png)

**Comment by andrewn** [comment]
Thanks for reporting this. I've just merged a fix.
