### ISSUE TITLE
Use one default template

### ISSUE THREAD

**Issue by andrewn** [processing/p5.js-web-editor#1423]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

The default HTML for a sketch is defined in multiple places:

1. [client/modules/IDE/reducers/files.js](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/reducers/files.js)
2. [server/domain-objects/createDefaultFiles.js](https://github.com/processing/p5.js-web-editor/blob/master/server/domain-objects/createDefaultFiles.js)
3. [server/scripts/examples.js](https://github.com/processing/p5.js-web-editor/blob/master/server/scripts/examples.js)

This makes it a bit tricky to update (see #1396).

We could define the template in one place that the files above use.

Note: When the public API is released, then the examples script (3) won't need to create HTML templates since the API creates default files automatically.

**Comment by catarak** [comment]
This is a great idea. Maybe this could also be handled in tandem with #144?

**Comment by SundeepChand** [comment]
Hello @catarak, I would like to work on this.
