### ISSUE TITLE
Generative title wrongly indexed by Google

### ISSUE THREAD

**Issue by jeremydouglass** [processing/p5.js-web-editor#1425]
#### Nature of issue?

- Found a bug
- Existing feature enhancement

#### Details about the bug: 

Currently the Google search engine indexes the web editor along with its generative title. So, for example, it is currently listed as: "p5.js web editor | Stormy moss"

<img width="766" alt="Screen Shot 2020-05-11 at 4 27 56 PM" src="https://user-images.githubusercontent.com/798570/81622054-dbd04300-93a4-11ea-89e5-0b8b57038386.png">

This makes the entry look like a link to a specific sketch -- or to something specific -- when it is not, it is the editor homepage.

#### Change:

It would be nice to alter the time / conditions under which generated titles are added to the title bar so that robots (such as the Google crawler) do not index them, but instead list only "p5.js web editor"

**Comment by catarak** [comment]
Thanks for reporting! I have noticed this but I'm not sure how to fix it. I really don't know a ton about search engine indexing and SEO. Any suggestions or ideas about how to fix this are very welcome 😄

**Comment by jeremydouglass** [comment]
One suggestion would be: don't write the sketch name into the page title until:

a) the user clicks save, or
b) the user clicks "run" for the first time

Bots never click save or run, so no bot will never index or cache a page with "Sleepy Wheelchair" etc. in the title.

**Comment by catarak** [comment]
> One suggestion would be: don't write the sketch name into the page title until:
> 
> a) the user clicks save, or
> b) the user clicks "run" for the first time
> 
> Bots never click save or run, so no bot will never index or cache a page with "Sleepy Wheelchair" etc. in the title.

Wow thank you! I didn't realize this would be so simple to fix, I'm on it!

**Comment by jeremydouglass** [comment]
Just looping back here to confirm that this fix worked -- the web editor is indexed in all search engines as expected.

<img width="603" alt="Screen Shot 2020-06-16 at 12 09 46 PM" src="https://user-images.githubusercontent.com/798570/84817864-7c300d80-afca-11ea-8e63-3181bb6abb7d.png">
