### ISSUE TITLE
Small bug with CSS editor

### ISSUE THREAD

**Issue by Guillaume57** [processing/p5.js-web-editor#1428]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Hello,

There is a small problem when editing a CSS and using custom variables, for example:
```css
:root
{
  --red: #ff0000;
}
```
It's working, but the editor will show a warning "Expected RBRACE" on the line "--red: #ff0000;"

**Comment by Guillaume57** [comment]
Apparently it's a problem with "csslint" [https://github.com/CSSLint/csslint/issues/603](url) , I think nothing can be done here to fix it

**Comment by catarak** [comment]
Thanks for reporting! It seems like CSSLint is out of date, see #1373. JSFiddle had similar issues with CSSLint but they updated their linter (not sure to which one though!).

**Comment by Guillaume57** [comment]
Maybe this one https://github.com/stylelint/stylelint

**Comment by catarak** [comment]
great suggestion!
