### ISSUE TITLE
Undefined objects error missing from console

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#143]
I have noticed that some errors show up in the browser JavaScript console, but not in our console.  I have yet to do a full accounting of error messages so I'll just open individual issues for now.  Here is one example.

``` javascript
function setup() {
  var p = new Particle();
}
```

We should see the error `Uncaught ReferenceError: Particle is not defined` in the editor console.

**Comment by shiffman** [comment]
Noting here also that if you try to `console.log` an undefined value it does not show up in the web editor console, but does appear in the browser console.  Two examples;

```javascript
function setup() {
  var val = undefined;
  console.log(val);
  var arr = [13, 22, 300];
  console.log(arr[4]);
}
```

**Comment by catarak** [comment]
I just tried the first example here, and it's actually working for me:
<img width="739" alt="screen shot 2016-11-02 at 6 40 35 pm" src="https://cloud.githubusercontent.com/assets/6063380/19950121/efdb201e-a12b-11e6-8346-9e660e1b775d.png">
Could this maybe be due to that console messages don't log if the console is not opened? Is this a confusing behavior?

**Comment by lmccart** [comment]
I think that is possible...I've gotten confused myself by this a few times. I didn't realize it but my common pattern of behavior is to open the console when an error occurs to see if there's more info there. I think this is a useful habit to get students in, so maybe we should be logging even when shut.

The reason we added this was to try to deal with serial issues, but it seemed like it didn't really help in terms of the use cases anyway, so maybe best to revert this behavior?

**Comment by catarak** [comment]
I noticed that I've been doing the same thing. I'm hoping that since we added the console batch messages to deal with #80, reverting this behavior won't slow down the editor.

**Comment by shiffman** [comment]
Yes indeed, this has indeed been the problem all along!   I think this can be closed and we can revisit if there are new issues.
