### ISSUE TITLE
Collections Sorting - # of sketches is incorrect

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1441]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Mac OSX
- Steps to reproduce this bug:
1. Navigate to `/collections`
2. Click "# of sketches" 
3. Scroll through the collections... notice the numbers are not in ascending/descending order.
<img width="1552" alt="Screen Shot 2020-05-28 at 3 16 56 PM" src="https://user-images.githubusercontent.com/6063380/83183779-69769700-a0f6-11ea-8eec-c2420b9e9159.png">

As reported in #1424.

**Comment by SebasMag** [comment]
Hi ! I want to contribute fixing this issue if it is possible.
