### ISSUE TITLE
Full screen preview no longer functioning

### ISSUE THREAD

**Issue by knectardev** [processing/p5.js-web-editor#1445]
#### Full screen preview no longer functioning

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome (latest) 
- Operating System: Win7
- Steps to reproduce this bug: 

Click File > Share > Fullscreen

"Present" mode is working fine, e.g. 
https://editor.p5js.org/knectar/present/jUHIH58ye

But "Fullscreen" just loads an empty page with an auto-generated file name. 

e.g. (same file URI as above): 
https://editor.p5js.org/knectar/full/jUHIH58ye

**Comment by catarak** [comment]
Thanks for reporting! I can reproduce and I suspect this is a bug introduced by resolving #1409.

**Comment by knectardev** [comment]
cool, should it be resolved already (notice you marked it closed). this issue is still occurring for me.

**Comment by maartenwijntjes** [comment]
I guess the p5js editor developer(s?) have others things on their mind right now, but just wanted to say  that it would be great when the fullscreen function would work again. I wanted to publish student's work for a class I taught, and all their links are in /fullscreen/ 😬

**Comment by andrewn** [comment]
@maartenwijntjes Just pushed a fix. Let me know if you still have issues.

**Comment by maartenwijntjes** [comment]
That is a quick response! But it does not seem to work for me, does it for you? For example:

https://editor.p5js.org/JuliaBeckmann/full/1dedT3O_X
Does not work, but

https://editor.p5js.org/JuliaBeckmann/present/1dedT3O_X
Does.

Other example:
https://editor.p5js.org/ahemerik/full/qcGn2VHvT
Is not working, while
https://editor.p5js.org/ahemerik/present/qcGn2VHvT
Works

Here is the page of student work: https://visualcommunicationdesign.github.io/output2020

Tested on safari and chrome

Ah… noticed something else: when you click the <> on the top right, the link seems to miss https://editor.p5js.org/<https://editor.p5js.org/ahemerik/full/qcGn2VHvT>USERNAME/




Op 8 jun. 2020, om 10:52 heeft Andrew Nicolaou <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



@maartenwijntjes<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_maartenwijntjes&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=fQ0XK5AoJ5yykeTTnr8PjdayWWrISW6iZef_0J7eSMc&m=5dS_i9vIhXQN6ZRWJXZ2kpy9jBk0nPXwNwvANMCQgDY&s=48OHvLK0Sfouk9qKyI_TRYaOWx_3T-QsaZSs0xgv9hQ&e=> Just pushed a fix. Let me know if you still have issues.

**Comment by andrewn** [comment]
@maartenwijntjes You need to wait a while for it to deploy. Sorry, I should have mentioned that. Will post again when it's live.

**Comment by maartenwijntjes** [comment]
Haha thanks, sorry.

Op 8 jun. 2020, om 11:00 heeft Andrew Nicolaou <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:



@maartenwijntjes<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_maartenwijntjes&d=DwMCaQ&c=XYzUhXBD2cD-CornpT4QE19xOJBbRy-TBPLK0X9U2o8&r=fQ0XK5AoJ5yykeTTnr8PjdayWWrISW6iZef_0J7eSMc&m=eeAWl0g64TDUP3Gn5jPIMqZBkblZ6fHemiOMn4_PdFE&s=qzUmOCy22MC90Evxk4OhLkkk8F5enMieHWVjbc0KAzk&e=> You need to wait a while for it to deploy. Sorry, I should have mentioned that. Will post again when it's live.

**Comment by andrewn** [comment]
@maartenwijntjes Sorry, I just realised that we're now doing proper releases so it won't automatically deploy.

@catarak will bundle it into a future release of the editor

**Comment by maartenwijntjes** [comment]
Thanks!!!

**Comment by andrewn** [comment]
> I will do a release today! For the future, maybe this is an issue that should have been a hotfix?

Great idea. I also forgot about that process 🤦
