### ISSUE TITLE
Client components testing 

### ISSUE THREAD

**Issue by Phe0** [processing/p5.js-web-editor#1454]
## Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
 - Add a coverage script in package.json scripts
 - Make all js and jsx files collected for coverage
 - Add testing to client components

**Comment by Phe0** [comment]
Started working on client testing in this branch:

https://github.com/Phe0/p5.js-web-editor/tree/testing

**Comment by catarak** [comment]
Thanks for working on this! I just want to point out #1432, that we are interested in transitioning from enzyme to react testing framework (or at least investigating the transition) while there are not a ton of tests in this project.

**Comment by Phe0** [comment]
Is someone assigned to investigate this? I can take a look if needed @catarak

**Comment by andrewn** [comment]
@Phe0 I was aiming to replace the couple of enzyme tests we have with testing-library after #1452 was merged in. I was also going to take the opportunity to create stories for the tested components.

Shall I message you when I create the PR as we can then add more tests?

**Comment by Phe0** [comment]
Sure @andrewn, I'll be taking a closer look at the react testing framework and wait for you response. Thanks.

**Comment by andrewn** [comment]
@Phe0 I've opened  #1477 which replaces Enzyme with React Testing Library. Let me know what you think!
