### ISSUE TITLE
touches does not work with the new index.html

### ISSUE THREAD

**Issue by chung-ken** [processing/p5.js-web-editor#1466]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Sorry, I am a teacher using p5.js.  I am new to GitHub.  I hope that this isn't too much or too little information.  Here's the issue:
The touches array doesn't work with touch screen Apple devices (not even on Chrome) with the newer version of index.html:
   <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/addons/p5.sound.min.js"></script>
I found a working p5 sketch and copied their index.html which made it work. This was the older index.html file:
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.5.11/addons/p5.sound.min.js"></script>
I'm not sure what version stops supporting apple devices, but I actually had this problem last year and only just figured out how to get it working.  At the time, this was the index.html file (that did not support touches on iPhones):
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/p5.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.8.0/addons/p5.sound.min.js"></script>

How can we get the newest p5.js library to support apple touch screen devices again?

- Web browser and version:  Chrome
- Operating System:  MacOSX
- Steps to reproduce this bug:
1) Use an apple touch screen device to see this working code:
https://editor.p5js.org/techlu/sketches/ryX4y5DAW
2) Copy the same sketch.js code into a new sketch.  It won't work on the same apple device. (Android and Windows still work.)

**Comment by andrewn** [comment]
Hi @chung-ken, thanks for opening this issue!

Can I just clarify, is the issue that new sketches in the Web Editor isn't using the latest version of the p5.js library (1.0.0)? 

Or is it that the p5.js library itself doesn't work with the touches array?

**Comment by chung-ken** [comment]
@andrewn, thanks for getting back!

So the touches array always works on android devices and desktop/laptop computers with all versions of the p5.js library.
I couldn't figure out why sketches using touch screen apple devices weren't working.  After some testing, I realized that the newer versions of the p5.js library stopped supporting touches on those devices.

I can only speak to what I see 
Specifically:
../libs/p5.js/0.5.11/  still allows touches to work on iPhone / iPad
while
../libs/p5.js/0.8.0/p5.js   and   ../libs/p5.js/0.10.2/p5.js  (using the same sketch.js) do not support touches on iPhone / iPad.

**Comment by chung-ken** [comment]
@andrewn Is there a 1.0.0 version of p5.js?
Open a new sketch on https://editor.p5js.org/
You'll see that the index.html file has:
../libs/p5.js/0.10.2/p5.js

**Comment by catarak** [comment]
@chung-ken there is a 1.0.0 version of p5.js! There's currently an issue with the p5.js CDN (see https://github.com/processing/p5.js/issues/4485) so the web editor is currently linking to 0.10.2. 

I tried running your sketch outside of the web editor on an iOS device for comparison. Here is what I noticed:
- The sketch works with v0.10.2, standalone
- The sketch works with v0.5.11, standalone
- The sketch works with v.0.5.11, in the web editor
- The sketch **does not work** with v0.10.2, in the web editor
- The sketch **does not work** with v1.0.0, in the web editor
- The sketch works with v1.0.0, standalone

Therefore, it seems like it has something to do with the web editor running the sketch and how touches work. My hunch is that it has to do with the sketch running within an iframe.

**Comment by catarak** [comment]
This seems to be working again with p5.js v1.2.0, so I'm going to close this issue.

**Comment by chung-ken** [comment]
Thanks for the update, Cassie! Just tested it myself. It is working with
v1.2.0. The web editor is still loading v1.1.9 by default, but it's easy
enough to change the source file in index.html.

**Comment by catarak** [comment]
@chung-ken let me open an issue to update p5.js in the editor to the latest version!
