### ISSUE TITLE
GitHub Linked Account Deletion

### ISSUE THREAD

**Issue by kkrithika** [processing/p5.js-web-editor#1468]
### Nature of issue?

- [x] Found a bug

#### Details about the bug: 

I created an account on the web editor through my GitHub account. I'm trying to delete my account but I unfortunately can't find a way to do that. Can you manually delete my account or is there a way to detach it from my GitHub?

**Comment by catarak** [comment]
Hi @kkrithika! Do you want to delete your account entirely, or do you want to simply remove its connection to your GitHub account? Either way, let me know what your username is.

**Comment by kkrithika** [comment]
I would like to delete my account entirely! Thank you!

**Comment by catarak** [comment]
Your account has been deleted!
