### ISSUE TITLE
browser console logging full code

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#147]
@catarak I'm not sure if this is in there for dev purposes, but the browser console logs the full code from time to time which sometimes makes debugging difficult.  It's totally ok if you need it there, but just in case it's there by accident I thought I would report it.

<img width="563" alt="screen shot 2016-10-14 at 4 05 29 pm" src="https://cloud.githubusercontent.com/assets/191758/19401216/13343996-9228-11e6-91a9-c0b64b1d53c7.png">

**Comment by catarak** [comment]
This is my bad, accidentally left in a console.log 😄
