### ISSUE TITLE
Extremely important sketch OVERWRITTEN after pressing FILE/NEW

### ISSUE THREAD

**Issue by Gabriel-Haydar** [processing/p5.js-web-editor#1479]
- Found a bug

#### Details about the bug: 

- Web browser and version: Microsoft Edge -->
- Operating System: Windows 10 1909
- Steps to reproduce this bug:

Sketch OVERWRITTEN after pressing FILE/NEW. Even the name that was "O Mergulho Perigoso" changed to "Wary Cuckoo". I just wanted to check the background() function on a new sketch, so I saved my 1 week very important project, that I am to submit tomorrow, and went to FILE and pressed NEW. It has the same date of creation as my project, and all my assets appear to have lost their names.  I really really need to restore all of my progress today. Please restore to a previous version!

![WHY GOD WHY](https://user-images.githubusercontent.com/58334516/85957985-15163f80-b960-11ea-8b98-0593b64a853a.PNG)
![assets have no name](https://user-images.githubusercontent.com/58334516/85958037-8d7d0080-b960-11ea-99fc-87f2bd8d96d7.PNG)
![Lost a really long week](https://user-images.githubusercontent.com/58334516/85958038-8f46c400-b960-11ea-99cc-2a299ba166f8.PNG)

**Comment by catarak** [comment]
I'm really sorry that happened! I'm unfortunately not going to be able to restore your sketch to its previous work. If possible, would you be able to list in more detail exactly what happened? This will help me fix the bug. For example, did you have your old sketch open and click "new"? Did you have it open in multiple tabs?
