### ISSUE TITLE
Automatically saving updated sketch name

### ISSUE THREAD

**Issue by yining1023** [processing/p5.js-web-editor#148]
When a sketch is saved, then I change the sketch name, it seems like I need to click on the "save" button again to save the new sketch name. Otherwise if I open "My Sketches" list, my sketch has the old name, and if I close the "My Sketches" list, my sketch will go back to its old name. 

Perhaps we could automatically save the sketch after user update the name?

**Comment by catarak** [comment]
This is a great idea!
