### ISSUE TITLE
Editor is down (502 Bad Request)

### ISSUE THREAD

**Issue by hachicom** [processing/p5.js-web-editor#1481]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

When trying to access web Editor, it returns error 502, bad gateway

- Web browser and version: Chrome - 83.0.4103.116 (Versão oficial) 64 bits (cohort: Stable)
- Operating System: Windows 10 Home
- Steps to reproduce this bug: accessing https://editor.p5js.org/

**Comment by catarak** [comment]
It seems to be back up! Sorry about that.
