### ISSUE TITLE
Have to Keep Resetting p5js Password

### ISSUE THREAD

**Issue by L64Dragon** [processing/p5.js-web-editor#1489]
Every Time I try to login to my p5js account I have to reset my password. Also WEBGL won't work; I keep getting an error. 

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by oruburos** [comment]
Does this happened in your local environment or in production?

**Comment by catarak** [comment]
Thanks for reporting! I think it is likely this is realted to #1314, which I unfortunately still haven't figured out a good way to fix.

**Comment by catarak** [comment]
fixed via #1317
