### ISSUE TITLE
"Open" to "Examples" when a user is not logged in

### ISSUE THREAD

**Issue by yining1023** [processing/p5.js-web-editor#149]
When a user is not logged in, "Open" links to the sketches of a user called p5, which would be a few example sketches.
Perhaps we could 
- change "Open" to "Examples". And keep the "Examples" after a user logs in.
- add more examples to this sketch list.

**Comment by lmccart** [comment]
yes, this makes much more sense. with the desktop editor, there was a task that would update the example set by pulling from the website repo on release build, I wonder if there is a way to do something similar with the web editor so we can be sure the examples stay up to date and correct.
https://github.com/processing/p5.js-editor/blob/master/gulpfile.js#L248

**Comment by catarak** [comment]
I don't think it would be too hard to set up a similar task! We could just write a node script, run it with npm, and then set up a cron job that runs this task periodically.
