### ISSUE TITLE
Translation files not served from endpoints other than "/"

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1505]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Mac OSX
- Steps to reproduce this bug: 
1. Navigate to any endpoint that is not `/`, e.g. https://editor.p5js.org/cassie/sketches/Wyu-U_0zn
2. Look at all of the requests that the website makes
3. Notice that the `translation.json` files return 404

cc @oruburos && @andrewn 

Since this is a super quick fix (just changing [i18n.js#L10](https://github.com/processing/p5.js-web-editor/blob/develop/client/i18n.js#L10)) and and is fairly critical, I'm just going to fix this 😄

**Comment by andrewn** [comment]
@catarak Sorry about this, I should have spotted that. Thanks for fixing!
