### ISSUE TITLE
Inclusive Language Spanish Translation 

### ISSUE THREAD

**Issue by oruburos** [processing/p5.js-web-editor#1509]
#### Nature of issue?
- Request For Comments

#### Feature enhancement details:

I have been working in a translation effort for the web editor (for Latin Spanish #595) and I want to ask the community (particularly people from Latin America) for their comments on how to tackle the following text within the web editor.
Basically, translating to a highly gendered language like Spanish comes with a difficulty and there are three labels that I want to translate using an inclusive language approach. 

This was a plain translation.
- "Username": "nombre de usuari**o**",
- "Welcome": "Bienvenid**o**",
- "Warning Unsaved Changes": "¿Está segur**o** de que quieres salir de la página? Tiene cambios sin guardar."

In Spanish  one common way to handle this situation is use the letter ‘X’ .(Like in Latinxs).  
Following that idea as precedent the translations would be:

- "Username": "nombre de usuari**x**",
- "Welcome": "Bienvenid**x**",
- "WarningUnsavedChanges": "¿Está segur**x** de querer salir de la página? Tiene cambios sin guardar."

Another option is using the letter “e”, in which case the three labels would be 

- "Username": "nombre de usuari**e**,
- "Welcome": "Bienvenid**e**",
- "WarningUnsavedChanges": "¿Está segur**e** de querer salir de la página? Tiene cambios sin guardar."

 ### PROS X
-  Common approach with the LatinX  concept
### CONS X
-  I don't know if this will have problems with tablet screen readers 
-  Pronunciation introduces problems, 
-   (Maybe it is difficult for people with dyslexia)

### PROS E
 - Is more related to Spanish, and the adoption is more frequent in certain countries.

Another approach that it is used is write the text in feminine gender as default, but I'd rather go with the non-gendered version

**Comment by andrewn** [comment]
This is a really important issue to think about, so thanks for raising it.

I can't speak about the Spanish language, but from a technical point of view:

>  I don't know if this will have problems with tablet screen readers 

- Is this an issue with "tablets" only or all screen readers?
- Can you try some of your language suggestions in different screen readers. [VoiceOver](https://support.apple.com/en-gb/guide/voiceover-guide/welcome/web) is built into macOs/iOS so that's a good start

**Comment by catarak** [comment]
@lm-n may have some insight with respect to Spanish and screen readers!

I also would like to invite @montoyamoraga to comment since they've done a lot of the p5.js Spanish translations so far.

**Comment by montoyamoraga** [comment]
hi @oruburos thank you for your thoughtful comments!

i agree with not using the usual "o" male version

the approach of using X (and @), as in, amigxs, amig@s
work in writing but not in pronunciation,

i would go with adopting the "E" approach,
i see a big adoption of it in my Spanish speaking friends and collaborators

and i am happy to do a read through / revision of anything you translate,
or to brainstorm more this, i also would love the opinion of @lm-n :)
(thank you @catarak for tagging me!)

**Comment by lm-n** [comment]
Hi @oruburos! Thanks for considering these important issues that come up with translations! 

For screen-readers it is better to use standard LatAm Spanish language as much as possible. Some screen-readers will read Latinx as "Lati ene equis" which, as you can imagine, may sound confusing. BTW the same happens with Latinx in English language. 

My approach would be to try to avoid the situations that you describe as much as possible. For example "Warning Unsaved Changes": "¿Está seguro de que quieres salir de la página? Tienes cambios sin guardar." could be translated to  "Warning Unsaved Changes": "¿Quieres salir de la página? Tienes cambios sin guardar."  For "Username": "nombre de usuario" you could say "Username": "Identificación".  For "Welcome": "Bienvenido" you could say "Welcome": "¡Hola!".

If there is no way of saying what you want without a gendered noun/adjective/adverb, I would go with an -e approach but I would to avoid using -e as much as possible.

Hope this helps! I'm sure if you post a list of gendered phrases, together with @montoyamoraga, we can come up with alternatives that are not gendered.

@catarak thanks for tagging me! @montoyamoraga hi!

**Comment by oruburos** [comment]
Thank you all for your comments, the feedback is great.

In my tests (using ChromeVox Classic Extension and Voice Over) I also ran in the problematic regarding X vs E. 
So, I will update the labels trying to avoid this problematic, and if in any moment it is present, I'll follow the -e approach.


Regarding the labels, some of them are in :  https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/es-419/translations.json .

 Have in mind that this is not the definitive structure and that doesn't include the ARIA labels yet.(Which will be the next PR)


{
    "Contribute": "Contribuir",
    "NewP5": "¿Empezando con p5.js?",
    "Report": "Reporta un error",
    "Learn": "Aprende",
    "About": "Acerca de",
    "Resources": "Recursos",
    "Libraries": "Bibliotecas",
    "Forum": "Foro",
    "File": "Archivo",
    "New": "Nuevo",
    "Save": "Guardar",
    "Share": "Compartir",
    "Duplicate": "Duplicar",
    "Examples": "Ejemplos",
    "Edit": "Editar",
    "TidyCode": "Ordenar código",
    "Find": "Buscar",
    "AddToCollection": "Agregar a colección",
    "FindNext": "Buscar siguiente",
    "FindPrevious": "Buscar anterior",
    "Sketch": "Bosquejo",
    "AddFile": "Agregar archivo",
    "AddFolder": "Agregar directorio",
    "Run": "Ejecutar",
    "Stop": "Detener",
    "Help": "Ayuda",
    "KeyboardShortcuts": "Atajos",
    "Reference": "Referencia",
    "Tidy": "Ordenar",
    "Lang": "Lenguaje",
    "FindNextMatch": "Encontrar siguiente ocurrencia",
    "FindPrevMatch": "Encontrar ocurrencia previa",
    "IndentCodeLeft": "Indentar código a la izquierda",
    "IndentCodeRight": "Indentar código a la derecha",
    "CommentLine": "Comentar línea de código",
    "StartSketch": "Iniciar bosquejo",
    "StopSketch": "Detener bosquejo",
    "TurnOnAccessibleOutput": "Activar salida accesible",
    "TurnOffAccessibleOutput": "Desactivar salida accesible",
    "ToogleSidebar": "Alternar barra de deslizamiento",
    "ToogleConsole": "Alternar consola",
    "Preview": "Vista previa",
    "Auto-refresh": "Auto-refrescar",
    "Console": "Consola",
    "Settings": "Configuración",
    "GeneralSettings": "Configuración general",
    "Theme": "Modo de visualización",
    "Light": "Claro",
    "Dark": "Oscuro",
    "HighContrast": "Alto contraste",
    "TextSize": "Tamaño del texto",
    "Decrease": "Disminuir",
    "Increase": "Aumentar",
    "IndentationAmount": "Cantidad de indentación",
    "Autosave": "Grabar automáticamente",
    "On": "Activar",
    "Off": "Desactivar",
    "SketchSettings": "Configuración del bosquejo",
    "SecurityProtocol": "Protocolo de seguridad",
    "ServeOverHTTPS": "Usar HTTPS",
    "Accessibility": "Accesibilidad",
    "LintWarningSound": "Sonido de alarma Lint",
    "PreviewSound": "Probar sonido",
    "AccessibleTextBasedCanvas": "Lienzo accesible por texto",
    "UsedScreenReader": "Uso con screen reader",
    "PlainText": "Texto sin formato",
    "TableText": "Tablero de texto",
    "Sound": "Sonido",
    "WordWrap": "Ajuste automático de línea",
    "LineNumbers": "Número de línea",
    "LangChange": "Lenguaje cambiado",
    "Welcome": "Bienvenida",
    "Login": "Ingresa",
    "LoginOr": "o",
    "SignUp": "registráte",
    "email": "correo electrónico",
    "username": "nombre de usuario",
    "LoginGithub": "Ingresa con Github",
    "LoginGoogle": "Ingresa con Google",
    "DontHaveAccount": "No tienes cuenta?",
    "ForgotPassword": "¿Olvidaste tu contraseña?",
    "ResetPassword": "Regenera tu contraseña",
    "BackEditor": "Regresa al editor",
    "UsernameSplit": "Nombre de usuario",
    "Password": "Contraseña",
    "ConfirmPassword": "Confirma la contraseña",
    "OpenedNewSketch": "Creaste nuevo bosquejo.",
    "Hello": "Hola",
    "MyAccount": "Mi Cuenta",
    "My": "Mi",
    "MySketches": "Mis bosquejos",
    "MyCollections":"Mis colecciones",
    "Asset": "Asset",
    "MyAssets": "Mis assets",
    "TitleAbout": "Editor Web p5.js  | Acerca de",
    "CodeEditing": "Editando Código",
    "Error": "Error",
    "In order to save": "Para guardar",
    "you must be logged in": "debes ingresar a tu cuenta",
    "Please": "Por favor",
    "Find in files": "Encontrar en archivos",
    "Create": "Create",
    "Folder": "Directorio",
    "FindText": "Encontrar texto",
    "FindNextTextMatch": "Encontrar la siguiente ocurrencia de texto",
    "FindPreviousTextMatch": "Encontrar la ocurrencia previa de texto",
    "Code editing keyboard shortcuts follow": "Los atajos para edición son como",
    "Sublime Text shortcuts": "los atajos de Sublime Text ",
    "WarningUnsavedChanges": "¿Estás seguro de que quieres salir de la página? Tienes cambios sin guardar."
  }

**Comment by montoyamoraga** [comment]
thank you @oruburos sounds great!

i read through the labels, and i would change the wording of the last one to avoid the "estás seguro" part, and also to make it shorter, what about

"¿Confirmas que quieres salir de la página? Tienes cambios sin guardar."
or
¿Realmente quieres salir de la página? Tienes cambios sin guardar."

:)

**Comment by oruburos** [comment]
Cool, you're right, shorter is better. It will be included in my next PR. Thanks for the comment.

**Comment by oruburos** [comment]
@montoyamoraga  , @lm-n 

Hi again,  How do you usually translate Modals in Spanish ?
option 1: Diálogo
option 2: Modal
option 3: ???

**Comment by montoyamoraga** [comment]
hi @oruburos i don't understand the context of "modal", can i see the original? or a screenshot? thanks!

**Comment by oruburos** [comment]
Hi, @montoyamoraga sorry for the lack of context. By "Modal" I mean the small dialogs that appear in some actions, for instance in this screen capture they are shown when you try to create a file or folder under Sketch menu.

![modal](https://user-images.githubusercontent.com/718254/89645617-123d3180-d8b2-11ea-8f10-9cc6971063f8.gif)

**Comment by montoyamoraga** [comment]
hi @oruburos, thank you for the explanation and gif! :)

i have seen them in Spanish as "diálogo" or the longer"ventana de diálogo", from "dialog window"

on Wikipedia i found "Modal window" in English, with no corresponding translated article to Spanish,
i had no idea they were called "Modal", at all :)
maybe it makes sense to also use Modal in Spanish, i prefer translations that are really close sounding to the original one,
maybe it's too technical?

From that article, there is a link to "Dialog box", and the corresponding Spanish article is called "Cuadro de diálogo",
which is a synonim (i think) for the "ventana de diálogo" version i knew of.
Any "diálogo" variant might be more well-known, but also it means dialog, and if you look it up on the internet,
you wouldn't find unrelated articles about dialogue,

i am still inclined towards Modal,  because i looked up "Modal + Accesibility" and "Modal + Accesibilidad"
and i get results that explain what it is, 

i didn't know about ARIA, i read a bit about it, thank you so much for doing this very important work,
hope this helped a bit  :)

**Comment by oruburos** [comment]
@montoyamoraga @lm-n And what do you think about the use of 'Assets' in Spanish? (term that ATM is being used in the Spanish translation)

**Comment by lm-n** [comment]
@oruburos hummm... I would probably think of using something like 'recursos' instead of 'assets.' I know they don't mean exactly the same but I would be careful of using a word in English that might limit access.

**Comment by montoyamoraga** [comment]
hi @oruburos! i agree with @lm-n, let's change "assets" to "recursos" :)

**Comment by oruburos** [comment]
Ok, so I'll create a PR for this issue then. Thanks for the feedback
