### ISSUE TITLE
The search list of sketches & collections do not reset back to original state (does not show all the sketches & collections) after search field becomes empty after a search.

### ISSUE THREAD

**Issue by SundeepChand** [processing/p5.js-web-editor#1512]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: On Chrome 84.0.4147.89 (Official Build) (64-bit)
- Operating System: Windows 10 OS Version 1909 (Build 18363.959)
- The search list of sketches & collections do not reset back to original state (does not show all the sketches & collections) after the search field becomes empty after a search. They reset to original state only upon clicking the clear button. To reproduce this bug see the GIF below:

![bug](https://user-images.githubusercontent.com/34120932/88392812-43116700-cdda-11ea-8186-3f2539bb4b83.gif)

I would like to fix this, if this indeed is a bug.

**Comment by catarak** [comment]
Thanks for reporting! This is indeed a bug. Go ahead and work on it!
