### ISSUE TITLE
Fix PropTypes linting errors

### ISSUE THREAD

**Issue by ghalestrilo** [processing/p5.js-web-editor#1514]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

Some invalid PropType declarations (`array.isRequired` and `object.isRequired`) somehow ended up on develop. In order not to block development because of this, I disabled these lines with `// eslint-disable-line`, but it's still tech debt to be addressed. Below are the files we should check:
- *IDEView.jsx*
- *MobileIDEView.jsx*
- *AccountForm.jsx*
- *LoginForm.jsx*
- *NewPasswordForm.jsx*
- *SignupForm.jsx*
- *ResetPasswordForm.jsx*
- *LoginForm.jsx*
- *APIKeyForm.jsx*

**Comment by catarak** [comment]
Great idea 😄

**Comment by KKVANONYMOUS** [comment]
@catarak 
I want to work on this issue. Can you please guide me through

**Comment by catarak** [comment]
Yes! I believe in order to get these errors to appear, you'll need to update React. You don't need to upgrade to React 17, just the latest minor/patch in v16.

**Comment by KKVANONYMOUS** [comment]
Hi, @catarak I have checked all the above specified files and found that only **ResetPasswordForm.jsx** shows the error related to `array.isRequired` and `object.isRequired`.
So should I make a PR disabling these lines using `// eslint-disable-line` ?

**Comment by catarak** [comment]
> So should I make a PR disabling these lines using `// eslint-disable-line` ?

You could do that, but I think a better fix would be to update React and then to actually fix the PropType errors rather than hiding them with `// eslint-disable-line`.

**Comment by KKVANONYMOUS** [comment]
Hi @catarak I have fixed all the PropType errors in the above files by replacing `PropTypes.object.isRequired` with `PropTypes.objectOf(PropTypes.shape())`
If you find it correct I will create a PR for the same.

**Comment by catarak** [comment]
That works!
