### ISSUE TITLE
Feature Enhancement - Add Find and replace command

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#1519]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Hi there! I'd like to propose that a find and replace feature could be added to the editor. Currently we have a find function, as well as find next and find previous, but I think it'd be super handy to also be able to find and replace either single or all instances of a search query. This might also mean some UI changes on the find pop-up bar. 

I'm hoping that since the find functionality is already built out that this wouldn't be too big a lift. Sorry if this has already been proposed, I looked around in the issues but didn't see anything. Thoughts?

**Comment by catarak** [comment]
Thanks for the suggestion 😸 This is built into CodeMirror ([demo](https://codemirror.net/demo/search.html)) so I don't think this would be too hard to implement! In fact, if you look at the code for the [Search popup](https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/codemirror-search.js), some code that handles replace is commented out. The hardest part would be adding in the UI and hooking up the keyboard shortcuts.

**Comment by RadheTians** [comment]
Hello @aferriss and @catarak!!
Can I please follow up on this issue?

**Comment by catarak** [comment]
@RadheTians absolutely! Feel free to work on it.

**Comment by RadheTians** [comment]
Thanks for confirmation @catarak.

**Comment by SundeepChand** [comment]
Hello @RadheTians! Just wanted to ask are you working on this? If not then, I would like to do it.

**Comment by RadheTians** [comment]
Hi @SundeepChand !!
I appreciate your interest but currently I am working on it and looking for the way by which I can add code in UI. It would be great if you share your idea so that we can come up with potential pull request.

**Comment by SundeepChand** [comment]
Sure @RadheTians, continue working on this. For the UI part, from what I've done so far, changes have to be made in Nav.jsx & Editor.jsx as well as the translations have to be defined in translations.json (under translations directory). Its extremely helpful to use "Find" as a reference.

**Comment by RadheTians** [comment]
Since my placement section is going on, therefore, I'm not able to spend time on this issue so, it's handover to you @SundeepChand.

All the very best!!

**Comment by SundeepChand** [comment]
Okay @RadheTians
