### ISSUE TITLE
Uploads of some .js files fail

### ISSUE THREAD

**Issue by vanevery** [processing/p5.js-web-editor#152]
Attempting to add a p5.js library for using the Kinect.  It requires this js file: https://raw.githubusercontent.com/vanevery/kinectron/master/client/bin/kinectron.bundle.js but the upload fails with this in the JS console:

bundle.js:176 text/javascript
s3-us-west-2.amazonaws.com/p5.js-webeditor/:1 POST https://s3-us-west-2.amazonaws.com/p5.js-webeditor/ 400 (Bad Request)
bundle.js:175 File {upload: Object, status: "error", previewElement: div.dz-preview.dz-file-preview.dz-processing, previewTemplate: div.dz-preview.dz-file-preview.dz-processing, content: "/******/ (function(modules) { // webpackBootstrap↵…;↵↵	module.exports = util;↵↵↵/***/ }↵/******/ ]);"…}

bundle.js:175 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Bucket POST must contain a field named 'key'.  If it is specified, please check the order of the fields.</Message><ArgumentName>key</ArgumentName><ArgumentValue></ArgumentValue><RequestId>507B9CC1B61334F5</RequestId><HostId>nZhf7lE/LrBZRjqv/3t7VXNj8DSbnOP+au0zWXNpiEcAD8ENhIYeoaSEN2nZXoNSDEfQhHWKdEI=</HostId></Error>

bundle.js:173 POST http://alpha.editor.p5js.org/api/projects/SyI39Yz1e/files 413 (Payload Too Large)

**Comment by catarak** [comment]
I guess this file is hitting the limits of an HTTP POST, and I'll have to change how it's getting sent to the server.

**Comment by vanevery** [comment]
Something strange is going on.  I just did some tests:

I am able to upload both that js file and jquery's js file (much larger) on a brand new sketch (that hasn't been saved) without issue via the drag and drop.

When I go back to this sketch: http://alpha.editor.p5js.org/projects/SyI39Yz1e  I am unable to upload either.

Also, if I create a new sketch and save I can no longer upload the js files again.

So..  It seems to only be an issue after a sketch is saved.  Previous to saving it works fine.

**Comment by catarak** [comment]
Love weird bugs like this! Thanks for the details, I will do some investigation.
