### ISSUE TITLE
Use latest p5.js version when creating a new project

### ISSUE THREAD

**Issue by TheWizardBear** [processing/p5.js-web-editor#1523]
At the moment the latest version of p5.js is `1.1.9`, yet the editor still uses `0.10.2`. 
It would be useful if the website used the latest version by default, as otherwise the version number has to  be manually changed it if the most recent version of p5.js is wanted.

**Comment by catarak** [comment]
Thanks for the suggestion! There was an issue with the p5.js CDN for 1.0, but I think with the 1.1 release that is resolved, see #1397.

**Comment by rtoal** [comment]
Good news. It looks like the version change has been merged but not deployed due to a Travis PR build error. Hopefully we'll see it live soon!

**Comment by catarak** [comment]
It'll be pushed to production with the next release (sometime this week)!
