### ISSUE TITLE
NOT DUPLICATING 

### ISSUE THREAD

**Issue by Trisston-Coder** [processing/p5.js-web-editor#1534]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment]
Hi @Trisston-Coder! Can you please add the specific sketch that you can't duplicate? I'm not able to figure out what the bug is unless you add steps to reproduce. I just tried duplicating a sketch and it's working for me.

**Comment by Trisston-Coder** [comment]
OK i will send the link
:- https://editor.p5js.org/rupin/sketches/cfYLG68g

**Comment by catarak** [comment]
I'm not even able to load this sketch right now—maybe it's corrupted in the database or something? I will investigate.

**Comment by catarak** [comment]
It seems like you deleted this sketch, so I'm going to close this issue.

**Comment by Trisston-Coder** [comment]
But the problem has not been solved

**Comment by catarak** [comment]
@Trisston-Coder i hear you! unfortunately since the sketch has been deleted i have no way to figure out what the issue is. feel free to reopen this issue if it comes up again!
