### ISSUE TITLE
Showing a toast saying "Project saved" every time when a user clicks on save button

### ISSUE THREAD

**Issue by yining1023** [processing/p5.js-web-editor#154]
When a user clicks on the "save" button, maybe we could show a toast saying "Project saved" too? 
For now, the interface doesn't give any feedback after I click on "save". As a user, I feel that seeing a toast that tells me my sketch is saved would be nice.

**Comment by catarak** [comment]
I thought that I had implemented this but I guess there is a bug... I'm on it!
