### ISSUE TITLE
Console doesn't scroll to bottom to reveal new messages

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1541]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Mac OSX
- Steps to reproduce this bug:
1. Create a sketch that prints lots of messages to the console (i.e. `print()` in the `draw()` loop)
2. Open the console
3. Notice that the console doesn't scroll to the bottom, so it's hard to see new messages.

I believe this was introduced when refactoring the `<Console />` to use `connect()` (see #1502 and #1507). Not sure why it's not working, as I doubled checked and the code that scrolled the console to the bottom is still in there.

**Comment by tatecarson** [comment]
I see that this fix was merged and I am still getting the problem described above. It makes using the console in the draw loop almost impossible.

**Comment by catarak** [comment]
@tatecarson it was merged but it hasn't been deployed yet!
