### ISSUE TITLE
"Add Sketch to Collection" Popup styling bug on Dark and High Contrast themes

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1542]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Mac OSX
- Steps to reproduce this bug:
1. Change the web editor to the "high contrast" or "dark" theme from the preferences
2. Open "My Collections"
3. Click on the arrow next to a collection, then click "Add Sketch"
4. The table is missing the alternating stripes design. 

<img width="1440" alt="Screen Shot 2020-08-11 at 2 47 10 PM" src="https://user-images.githubusercontent.com/6063380/89936592-e4bdf400-dbe1-11ea-9a64-61bbc8c92311.png">

**Comment by SundeepChand** [comment]
Hello @catarak! Can I work on this?

**Comment by SundeepChand** [comment]
I looked into the issuse & found that it is caused because, the modal background color matches the stripe color. So I think we should change the stripes to a darker shade.

**Comment by catarak** [comment]
> Hello @catarak! Can I work on this?

Absolutely!

**Comment by SundeepChand** [comment]
Thanks for confirmation!
