### ISSUE TITLE
Web Editor can't capture and display errors for p5.js >= 1.0.0

### ISSUE THREAD

**Issue by akshay-99** [processing/p5.js-web-editor#1546]
#### Nature of issue?

- [x] Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 83.0.4103.116 
- Operating System: Ubuntu 18.04
- Steps to reproduce this bug:

For sketches running on p5 versions 0.10.2 and older , the editor is able to capture an error, highlight the line and display the error in the editor console perfectly.
![image](https://user-images.githubusercontent.com/38867671/90055514-14145400-dcfb-11ea-8fe2-66cd918adbe1.png)
It cannot do the same for sketches running on newer versions of p5 ( >= 1.0.0 ) as seen here:
https://editor.p5js.org/akshay.padte/sketches/2yX5Q5CeV

This is likely because the initialization code for p5 was [changed a bit](https://github.com/processing/p5.js/pull/4233/commits/dd9d2c85e82a938c77778750cc385cb246d8a942) in processing/p5.js#4233 ( just before 1.0.0 ) and it now runs inside a promise. Which also means that errors now happen inside a promise and would now be caught by `unhandledrejection` listener instead of `onerror`.

Also, since p5 0.6.0, several components of the FES report the line number of the error in the message. However since the editor concatenates the user-code into `srcdoc`, the line number reported by the FES is something like `about:srcdoc:56:3`
![image](https://user-images.githubusercontent.com/38867671/90058055-d74a5c00-dcfe-11ea-8191-41a2a2554e56.png)

I was wondering if it's possible to fix this somehow. Maybe this belongs in an issue of its own.

**Comment by catarak** [comment]
Thanks for reporting! It seems like the code meant to catch JS errors isn't intercepting unhandled promise rejections. This code is located in [consoleUtils.js](https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/consoleUtils.js#L3). Apparently `window.onerror` doesn't catch unhandled promise rejections, and a solution is [proposed here](https://stackoverflow.com/a/55178672).

**Comment by ridait** [comment]
Hello, 
I can take a look at this one unless someone is already on it.

**Comment by ridait** [comment]
@catarak I am sorry for the inconvenience, a new PR is created based on `develop` branch.
