### ISSUE TITLE
Internationalize mobile text

### ISSUE THREAD

**Issue by ghalestrilo** [processing/p5.js-web-editor#1559]
Currently, all texts on mobile views are hard-coded.
Use `i18n` to move these values to the translations file.
Bonus: Provide missing translations

**Comment by catarak** [comment]
btw, you can access the translations on desktop by adding the env variable `TRANSLATIONS_ENABLED=true` to your `.env` file.

**Comment by catarak** [comment]
I did some thinking about the design for switching the language, and this is what I have so far:
<img width="376" alt="Screen Shot 2020-08-19 at 2 51 12 PM" src="https://user-images.githubusercontent.com/6063380/90677863-f62f7d80-e22b-11ea-9644-527caeb8db3d.png">

I was thinking it could be in the dropdown menu, which would then open a popup that is similar to this:
![1_msQUOeOtNhqKYi5tvSbZ2w](https://user-images.githubusercontent.com/6063380/90677957-12331f00-e22c-11ea-833f-f6b47a2ac019.png)

I'm not totally happy with this but I wanted a jumping off point. I was also messing around with the Desktop design to see if that would help generate ideas, which I've settled upon this right now (I'm gonna open a PR and ask Andrew and Omar for feedback):
<img width="1552" alt="Screen Shot 2020-08-19 at 2 58 17 PM" src="https://user-images.githubusercontent.com/6063380/90678253-72c25c00-e22c-11ea-968d-4210fd0f0509.png">
<img width="1552" alt="Screen Shot 2020-08-19 at 2 58 12 PM" src="https://user-images.githubusercontent.com/6063380/90678276-7a820080-e22c-11ea-857a-71e3aa7349e1.png">

In the mobile design, if possible, I would like to (1) have it be clear which language is selected, and (2) not have to open an additional popup.

**Comment by ghalestrilo** [comment]
I think adding a [translation icon](https://material.io/resources/icons/?search=language&icon=translate&style=baseline) is very helpful

**Comment by catarak** [comment]
> I think adding a [translation icon](https://material.io/resources/icons/?search=language&icon=translate&style=baseline) is very helpful

Okay! How would the icon fit into the design?

**Comment by ghalestrilo** [comment]
I think to the left of the language name / dropdown title is a good idea!
On mobile, it can go to the left of the `Language` dropdown item
