### ISSUE TITLE
Create floating canvas for `MobileIDEView`

### ISSUE THREAD

**Issue by ghalestrilo** [processing/p5.js-web-editor#1560]
Currently, the user must navigate outside of the `MobileIDEView` in order to render the sketch and get visual feedback from his code. This is not ideal for UX.
Create a small floating component that renders the code (probably a wrapper around `SketchPreview`) and place it on 

Careful with how it interacts with the console: maybe switching between them is a good idea

Idea: Press+Hold `Play` button to trigger autorun + floating preview. Press again to hide.

**Comment by ghalestrilo** [comment]
The [react-draggable](https://www.npmjs.com/package/react-draggable) should come in handy

**Comment by dewanshDT** [comment]
@raclim @kjhollen @ghalestrilo I want know about the implementation of the moblie view why the PR was closed. And I'm really intrested to work on the responsive design and mobile view. I've seen the design Implementations [here at zeplin](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3) as well as read the [Shuju's blog on the topic](https://www.shujuuu.com/p5js-mobile-editor), can you guys help me getting started with it please?
