### ISSUE TITLE
Add/remove collection buttons not translated

### ISSUE THREAD

**Issue by andrewn** [processing/p5.js-web-editor#1570]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 
- Operating System: All
- Steps to reproduce this bug:

1. Open a saved sketch
2. Switch to Spanish language
2. Select Archivo -> Agregar a colección

The add/remove buttons should have translated ARIA labels, but they don't (see screenshot below).

<img width="1279" alt="Screenshot 2020-08-25 at 08 48 19" src="https://user-images.githubusercontent.com/1762/91147233-45583100-e6b8-11ea-969c-dafcdfc22713.png">

**Comment by andrewn** [comment]
This is tested with PR #1569 too.

**Comment by oruburos** [comment]
Hi, I've submitted a patch for this issue, now these are values when I inspect them

English

![addEN](https://user-images.githubusercontent.com/718254/91169533-6ed08700-e6cf-11ea-92a5-0734059c01d1.png)


Spanish

![addES](https://user-images.githubusercontent.com/718254/91169542-709a4a80-e6cf-11ea-9989-1af3eb044351.png)
