### ISSUE TITLE
Fix visual details on Mobile

### ISSUE THREAD

**Issue by ghalestrilo** [processing/p5.js-web-editor#1573]
Some visual details need an update on the mobile UI. This requires trying things out - If in doubt, use the [figma project](https://www.figma.com/file/4SoaiwasoL3fDlyzfS2JIQ/Second-Iteration?node-id=0%3A1) as reference.

 - [ ] Add p5 logo to the left of the header (mind the different header heights)
 - [ ] Fix some icons
   - `Exit` and `Play` Icons look huge. The svg border is very large - a possible solution is to use there the same color as the background
 - Correct svg padding on `<Header />` and `<Footer />` (ie. three-dots icon looks tiny, footer looks too tall, etc.)
 - [ ] opt. change header color on `<MobileDashboardView />`
 - [ ] opt. Try different font sizes on the header.

Note: The mobile version strays a bit from the visual identity

**Comment by raclim** [comment]
There's a new GSoC project related to the Mobile experience this year so some of the updates here might be outdated—I'm going to close this for now!
