### ISSUE TITLE
Adding a circle icon near the filename when the file is unsaved

### ISSUE THREAD

**Issue by yining1023** [processing/p5.js-web-editor#158]
If the sketch has never been saved, and a user has edited a sketch, generate a toast saying that the project has not yet been saved.

**Comment by catarak** [comment]
Regarding the discussion in #146, I think it's better to not show a toast for this and rely on other visual cues instead. I do still think we need #159, and to leave the Save toasts that exist now.

**Comment by catarak** [comment]
The functionality has been added here, we just need to replace the asterisk with a circle icon:
<img width="1277" alt="aebdb85e-96bc-11e6-81e1-441c0cf48348" src="https://cloud.githubusercontent.com/assets/6063380/20199314/a06ddb3c-a777-11e6-843a-945d10261ecc.png">
