### ISSUE TITLE
Adding Images to Project

### ISSUE THREAD

**Issue by mrgerla** [processing/p5.js-web-editor#1585]
My students and I can no longer add images to our projects in P5JS. When I click on the add file in the Sketch drop down menu, it no longer gives the option to drag and drop or browse a location on the computer. I have tried Firefox and Chrome, and neither seem to be working anymore. 

I couldn't find any recent information on this, as it seems as though it was a problem in the past.

Thank-you for your help.

**Comment by catarak** [comment]
Thanks for reporting! The location for uploading files has moved—you should now see a dropdown option called "Upload File" that is separate from "Create File". This is available when you have a folder selected or the "Sketch Files":
<img width="312" alt="Screen Shot 2020-09-02 at 1 01 13 PM" src="https://user-images.githubusercontent.com/6063380/92013951-7bcb2700-ed1c-11ea-96ef-53e9ab07bf74.png">
<img width="364" alt="Screen Shot 2020-09-02 at 1 01 30 PM" src="https://user-images.githubusercontent.com/6063380/92013958-7d94ea80-ed1c-11ea-934f-fa034998bce5.png">

**Comment by SihanZhang98** [comment]
<img width="277" alt="1" src="https://user-images.githubusercontent.com/70332584/92986010-3a8c0180-f4ea-11ea-9cba-99f519e9b72b.png">

There isn't the "Upload file" option when I click "Sketch Files". Does anyone know why?

> Thanks for reporting! The location for uploading files has moved—you should now see a dropdown option called "Upload File" that is separate from "Create File". This is available when you have a folder selected or the "Sketch Files":
> <img alt="Screen Shot 2020-09-02 at 1 01 13 PM" width="312" src="https://user-images.githubusercontent.com/6063380/92013951-7bcb2700-ed1c-11ea-96ef-53e9ab07bf74.png">
> <img alt="Screen Shot 2020-09-02 at 1 01 30 PM" width="364" src="https://user-images.githubusercontent.com/6063380/92013958-7d94ea80-ed1c-11ea-934f-fa034998bce5.png">

**Comment by catarak** [comment]
@SihanZhang98 are you logged in? You must be logged in in order to upload files.
