### ISSUE TITLE
Translation for Code Mirror Search

### ISSUE THREAD

**Issue by oruburos** [processing/p5.js-web-editor#1588]
- New feature request

At this point, there are no translations for the Find functionality because it is a particular component in the sense that usual approaches used through the translation effort don't work. 
https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/codemirror-search.js
I don't know how to expose it as a React Component, or if that is even required, and could be translated using i18n t functions only.

**Comment by catarak** [comment]
I'm not a huge fan of how this component is rendered since it's different from the rest of the application, and it would be rad to figure out how to render it as a React component!

**Comment by SundeepChand** [comment]
@catarak I would like to work on this.
