### ISSUE TITLE
Connect the <PreviewFrame /> Component

### ISSUE THREAD

**Issue by ghalestrilo** [processing/p5.js-web-editor#1590]
#### Nature of issue?

- Refactor / Code quality

#### Details

The `<PreviewFrame />` component needs a lot of props, some of which are very specific, which are passed by the `<IDEView />`. Since the component is also used in the `<MobileIDEView />` (and futurely in other components, maybe), it's a good idea to make it into a React Container. This has been done to the `<Editor />` component, and it helps dry up the code for the `Views`.
There are two ways to go about this:

1. `connect` it using `mapStateToProps` and `mapDispatchToProps`
2. Use the `useSelector` and `useDispatch` react-redux hooks.

**Comment by ZenVega** [comment]
Hi, I would like to give it a shot. would u assign this to me?
