### ISSUE TITLE
Weather example is using depricated api endpoints

### ISSUE THREAD

**Issue by corvanessen** [processing/p5.js-web-editor#1592]
#### Nature of issue?

- Found a minor bug

#### Details about the bug: 

-When running the Weather example it returned an error.
Putting the url directly in the search bar showed the following message:
IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT  
                                                                                                                                        
 This API endpoint is deprecated and has now been shut down. To keep using the apixu API, please update your integration       
  to use the new weatherstack API endpoint, designed as a simple drop-in replacement.                                          
 You will be required to create an account at https://weatherstack.com and obtain an API access key.                          
                                                                                                                                
  For more information on how to upgrade please visit our Github Tutorial at: https://github.com/apilayer/weatherstack#readme

**Comment by catarak** [comment]
Thanks for reporting! The example has been updated on the p5.js website so the script that re-uploads all of the examples just needs to be rerun. I can do that right now!

**Comment by catarak** [comment]
This has been fixed 😄
