### ISSUE TITLE
Expanding and Collapsing the Sidebar is not working

### ISSUE THREAD

**Issue by oruburos** [processing/p5.js-web-editor#1593]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 

Google Chrome | 84.0.4147.135 (Official Build) (64-bit) (cohort: Stable)
-- | --
Revision | c42bd09b3f24da1698d71d3b4f57402137163566-refs/branch-heads/4147@{#1102}

- Operating System: OS | Windows 10 OS Version 1909 (Build 18363.1016)

- Steps to reproduce this bug:
Trying to expand the sidebar doesn't work

![sidebarbug](https://user-images.githubusercontent.com/718254/92026124-712e8300-ed58-11ea-9c1a-56564507b790.gif)

**Comment by catarak** [comment]
Thank you! This was introduced in https://github.com/processing/p5.js-web-editor/pull/1544 when the `Editor` was refactored to use `react-redux`.
