### ISSUE TITLE
Table summaries are not translated

### ISSUE THREAD

**Issue by andrewn** [processing/p5.js-web-editor#1599]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

The `summary` attribute of the tables need to be translated:

- [Collection.jsx](https://github.com/processing/p5.js-web-editor/blob/5af98ca7658e9275f06bd5800e27ba7f272dd00e/client/modules/User/components/Collection.jsx#L374)
- [SketchList.jsx](https://github.com/processing/p5.js-web-editor/blob/5af98ca7658e9275f06bd5800e27ba7f272dd00e/client/modules/IDE/components/SketchList.jsx#L438)

**Comment by oruburos** [comment]
Ok, I'm on it. CollectionList has the same issue.
