### ISSUE TITLE
Editor on iPad

### ISSUE THREAD

**Issue by liuboto** [processing/p5.js-web-editor#1607]
Would it be possible to add 

html, body {position:fixed} 

To the editor css to make it more usable on iPads. The default behavior of touching and dragging on the canvas moves/bounces the page inside the browser and makes it very difficult to draw or do any kind of useful touch-drag interaction

**Comment by catarak** [comment]
Hi @liuboto! You can actually edit the CSS yourself by opening the file sidebar:
<img width="434" alt="Screen Shot 2020-09-11 at 2 17 43 PM" src="https://user-images.githubusercontent.com/6063380/92959357-aa8e7f00-f439-11ea-8b94-fab3f1e111b6.png">
<img width="628" alt="Screen Shot 2020-09-11 at 2 17 57 PM" src="https://user-images.githubusercontent.com/6063380/92959376-b0846000-f439-11ea-8462-52ebd6bbffbb.png">

I don't think it makes sense to add your suggested CSS by default though!
