### ISSUE TITLE
Console statments scroll out of view 

### ISSUE THREAD

**Issue by tatecarson** [processing/p5.js-web-editor#1608]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Firefox 80, 
- Operating System: macOS 10.15.6
- Steps to reproduce this bug:

Try to log anything in the draw loop. The most recent statements are pushed down to the bottom out of view, making the console almost useless for anything in the draw loop. 

[example](https://editor.p5js.org/tcarso2/sketches/SbAtBLFbI3)

This was mentioned in closed issue (#1541) and merged (#1553) but I am still having the issue. This is making it very hard to teach.

**Comment by catarak** [comment]
Thanks for reporting and I hear you! Fix to be deployed soon.
