### ISSUE TITLE
Working with local data files (json, csv, txt)

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#161]
I can create a `.js` file with "Add File" no problem, but I am not able to add a `.json` file.  I am, however, able to upload a JSON file.

**Comment by shiffman** [comment]
I am updating this issue after some more thought and discussion.  In ICM's data week I demonstrated working with `json`, `txt`, and `csv` formatted data.  A demonstration I would like to be able to do is create a `json` or `txt` file in the editor, type into it, and load that data using `loadJSON()`, `loadStrings()`.  

In addition, I would also like to upload data files and use them the same way with examples.

Currently, the uploading does work, but there is some strange behavior.  For example, in [this testing sketch(http://alpha.editor.p5js.org/projects/H1FYZGukl), the `json` files behaves as expected, but I am not able to access the data of the `txt` file.

I know there are questions and issue around whether these files should live on S3 or in the DB.  @catarak we should discuss this on our next check-in.

The good news, all is well with working with data and APIs via URLs!

**Comment by shiffman** [comment]
Just adding also that I'm seeing the contents of my uploaded JSON and TXT files as blank in the editor.  See: http://alpha.editor.p5js.org/projects/H1FYZGukl

**Comment by catarak** [comment]
This has been merged with master, but not yet deployed.
