### ISSUE TITLE
p5.js, ml5.js, and generative design examples - GitHub API deprecation

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1613]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Authenticating with the GitHub API via query parameters is now deprecated, and needs to be updated to authenticate with the request headers. See [Deprecating API authentication through query parameters](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) for more info. 

The following files will need to be updated:
- [examples.js](https://github.com/processing/p5.js-web-editor/blob/develop/server/scripts/examples.js) for the p5.js examples
- [examples-gg-latest.js](https://github.com/processing/p5.js-web-editor/blob/develop/server/scripts/examples-gg-latest.js) for the generative design examples
- [examples-ml5.js](https://github.com/processing/p5.js-web-editor/blob/develop/server/scripts/examples-ml5.js)

**Comment by Swapnil-2001** [comment]
Hi @catarak , I would love to work on this issue. It would be really helpful if you could suggest some sources from where I can gather information on how to make the changes.

**Comment by catarak** [comment]
> Hi @catarak , I would love to work on this issue. It would be really helpful if you could suggest some sources from where I can gather information on how to make the changes.

It seems like from your PR that you figured it out :) Let me know if there's stuff you're still confused about!

**Comment by Swapnil-2001** [comment]
Thank you, @catarak , I will :)
