### ISSUE TITLE
Content of Sign Up page overlaps with navbar on relatively small mobile screens

### ISSUE THREAD

**Issue by Swapnil-2001** [processing/p5.js-web-editor#1621]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Steps to reproduce this bug:

When the Sign Up page is viewed on relatively small mobile screens, the heading and the navbar overlap. The Login page, however, looks perfectly alright. I believe that the problem could be fixed simply by pushing down the content of the Sign Up page a little.
![Screenshot_2020-09-25-02-11-54-836_com android chrome](https://user-images.githubusercontent.com/53232360/94234933-4cc56100-ff28-11ea-93e2-4b2e9890d62e.jpg)

I would be glad to work on it if a change is deemed necessary.

**Comment by catarak** [comment]
Thanks for reporting! The mobile version of the editor is in progress but not yet enabled in production. This was fixed by #1543.
