### ISSUE TITLE
Missing project

### ISSUE THREAD

**Issue by Nisseboy** [processing/p5.js-web-editor#1629]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome | 85.0.4183.121 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 10 x64
- Steps to reproduce this bug:

I made a project, but got another idea so i saved the project and created a new project, however when i went to go to the first project it was gone. I am sure i saved it as i opened it on my laptop midcoding. I have tried refreshing and waiting but it's still gone on my primary computer aswell as my laptop

**Comment by catarak** [comment]
Thanks for reporting! That's super frustrating and I'm sorry that happened. What's your editor username?

**Comment by Nisseboy** [comment]
> Thanks for reporting! That's super frustrating and I'm sorry that happened. What's your editor username?

Thank you for responding, it's LegoExperten, and the name of the project was Territories @catarak

**Comment by catarak** [comment]
I'm not able to find the sketch! I think somehow it didn't get saved. I know that's super frustrating, and I hope that this can be prevented in the future. 

For future improvements, there's some references in #1337, like adding CRDT and saving to local storage, that could help prevent saving issues! It's a work in progress though.

**Comment by Nisseboy** [comment]
@catarak then how was i able to open it on my laptop while working on it?

**Comment by catarak** [comment]
I think what happened is that you were working on the sketch in the browser, but it somehow never got saved to the database even though you had saved it.

**Comment by Nisseboy** [comment]
@catarak that's wierd. Well, thanks anyways
