### ISSUE TITLE
tool-tips

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#163]
I've noticed the editor has default "tool-tip" names that appear when hovering over interface elements.  For example: "project-menu" for the navigation, and "code-editor" for the code editor.   The "code-editor" one often gets in the way.  I would suggest removing these for now.  There may, however, be some instances where they can be useful in terms of providing additional information for interface elements.

**Comment by catarak** [comment]
The tool tips are actually there for accessibility reasons, so unfortunately I can't remove them.
