### ISSUE TITLE
P5 editor malfunctioning

### ISSUE THREAD

**Issue by tinivasanth** [processing/p5.js-web-editor#1631]
Hi, i am facing an issue with the P5 editor whenever I open the editor and click inside the workspace my code gets jumbled. attaching a copy of the same herewith. anyone could help me out with this...
![P5 editor error](https://user-images.githubusercontent.com/23624178/95749964-0d359d80-0cba-11eb-846b-414418875a4a.PNG)

#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment]
Hey @tinivasanth! I'm not able to reproduce. What browser/OS are you using? Do you have any special keyboard shortcuts setup? Could you possibly post a video of this happening?

**Comment by tinivasanth** [comment]
Hello,
I am using Chrome browser and my OS windows 7 professional.No keyboard
shortcuts.
With Regards,
Tini vasanth

**Comment by catarak** [comment]
I just tried testing this on Windows 7 with Chrome and I wasn't able to reproduce, so I'm thinking it's some way that your computer is configured. Are you using a touchscreen? Can you think of any configurations you have added?

**Comment by tinivasanth** [comment]
hello,
No I have not added any special configurations,recently I reinstalled my OS
as P5 editor was not working but after that too the same issue persists.
With Regards,
Tini vasanth

**Comment by catarak** [comment]
I just noticed that the lines are in alphabetical order. Do you have a browser extension that tidies text in that way? Can you think of any reason why that would be important?
