### ISSUE TITLE
Korean Translation of Web Editor

### ISSUE THREAD

**Issue by yinhwa** [processing/p5.js-web-editor#1632]
**Currently in progress with @kangashley & @yinhwa** 

- - - - - - - - - - 

Hi @catarak, @ghalestrilo ! I'm trying to add Korean translation to the web editor to increase the editor's lingual accessibility to Korean speakers. My particular concern is on some dozens of older adults in Korea that I'll be having p5.js workshop with on November, but it certainly will be helpful for the language group in general both in and out the country.

I have checked in with @ghalestrilo if there'd be any conflicts on the mobile UI if I add new translation, and Thales's told me it will work automatically :)  I've also noticed that [Spanish translation] was successfully added a couple months ago!🎉

And yet, I would like to ask if it will be alright for me to start working on it by now; and if adding translation was part of the maintenance plan. If everything's fine, I'm planning to have it done before the Week 2 of November, since I'm having the workshop on Week 3-4 and afterwards.

Please let me know your opinion!
Thank you :)

#### Nature of issue?
- Existing feature enhancement
- New feature request

#### Feature enhancement details:
- Add Korean translation of log in/sign up; menus; (+examples if possible) 

#### New feature details:
- Add "Korean" button on the top right corner

**Comment by catarak** [comment]
Hey @yinhwa! I'm super excited you want to work on this. Now that @oruburos did the first translation, the new ones should be simpler. He made a [translation guide](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/translations.md) which should help you. Let me know if you have any questions! Also, feel free to open multiple pull requests to complete this, as now that there are releases (like v1.1.1, etc), things that are merged into develop are not immediately merged to production.

**Comment by yinhwa** [comment]
@catarak thank you Cassie!!! :) wish my best luck with the new releases🎇🎉 p5 web editor rox yay!

**Comment by oruburos** [comment]
Hey @yinhwa and @catarak , good to see people working on this. Also, please check #1638 . Good luck.

**Comment by yinhwa** [comment]
Thanks @oruburos for letting me know and your guides on Koji's Issue 😁 Also excited for @koji 's Japanese translation!

**Comment by koji** [comment]
@yinhwa 
Actually, your issue helped me to start working on my issue!
Thank you for opening this!

**Comment by yinhwa** [comment]
@kangashley is joining this translation 🥰 yay
