### ISSUE TITLE
Cannot open p5 online editor on Mac

### ISSUE THREAD

**Issue by Toodle-ux** [processing/p5.js-web-editor#1634]
I cannot open p5 online editor on Mac, using Chrome or Safari. But I can open the editor on Windows using the same Internet connection...

**Comment by catarak** [comment]
Thanks @montoyamoraga! Just transferred :)

**Comment by catarak** [comment]
And @montoyamoraga I also just updated your permissions so you could transfer issues in the future!

**Comment by deepakbabu-vine** [comment]
I am using Mac catalina,I am able to open it,but it loads for sometime
