### ISSUE TITLE
Uploading video files

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#164]
I'm not able to get uploading of a video file to work.  I've tried a few different files -- `mov` and `mp4`.  The upload silently fails but I do see an error in the console.

<img width="585" alt="screen shot 2016-10-22 at 1 22 07 pm" src="https://cloud.githubusercontent.com/assets/191758/19621199/992c51ae-985a-11e6-9653-19e1f1bdb0d3.png">

**Comment by shiffman** [comment]
Connecting this to #14

**Comment by catarak** [comment]
This has been pushed to master, to be deployed.
