### ISSUE TITLE
Bug in High Contrast and Dark Mode

### ISSUE THREAD

**Issue by samyakbambole** [processing/p5.js-web-editor#1642]
Whenever I visit to someone else's code in full-screen mode, the `</>` icon on the top-right isn't visible properly.

**Comment by SundeepChand** [comment]
Hello @samyakbambole! Can you please elaborate the issue. Maybe adding a screenshot would help us better understand the problem.

**Comment by samyakbambole** [comment]
@SundeepChand Ok!

**Comment by samyakbambole** [comment]
![image](https://user-images.githubusercontent.com/64409597/96448621-48434e00-1231-11eb-9116-da3c7c548859.png)
As You can see, The `</>` icon on the top-right isn't visible in full-screen-mode

**Comment by SundeepChand** [comment]
@samyakbambole Thanks for reporting this!

**Comment by samyakbambole** [comment]
> @samyakbambole Thanks for reporting this!

The GitHub Community is really Great! Thanks a Lot!

**Comment by samyakbambole** [comment]
This issue was actually reported in a @CodingTrain stream. I just created an Issue! 

Link for CodingTrain Organization - https://github.com/CodingTrain

**Comment by samyakbambole** [comment]
Link for @CodingTrain YouTube Channel - https://www.youtube.com/user/shiffman
