### ISSUE TITLE
Sketch works on OpenProcessing but not on the P5.js Web Editor.

### ISSUE THREAD

**Issue by EmmanuelPil** [processing/p5.js-web-editor#1643]
Hi.
I'm using a Windows 7 Ultimate 64bit PC with the latest Chrome version.
[This sketch](https://www.openprocessing.org/sketch/984401) works well on OpenProcessing but not on the P5.js Web Editor, and I can"t find the reason.

**Comment by EmmanuelPil** [comment]
After switching off the accessibility features on in settings, the sketch works but does not display the arrow points.
https://editor.p5js.org/noelpil/sketches/cYbw4fW9h

Edit:  But this only happens because I need to set my video (scale) setting to 125% on my  1920 * 1080 monitor,
otherwise, the font and other items are far too small. So I have to adjust the zoom level to 80% to view the sketch.
At a normal 100% browser zoom and a 125% windows scale setting, the arrow points are not drawn.

**Comment by catarak** [comment]
Thanks for reporting! I'm a little confused about all of these zoom settings and what the expected behavior is. I noticed that when I follow the instructions in the OpenProcessing sketch (set the browser scale to 49%), it renders the same way as in the p5.js Editor.

**Comment by EmmanuelPil** [comment]
>" I'm a little confused about all of these zoom settings"

It's quite common to use at least a 125 % 'scale' screen setting for medium to larger screen resolutions.
And they can be changed rapidly to test. But if you leave the normal 'browser' zoom at 100%, the arrows points are not drawn. Only lines. Also note that the grid points in OpenProcessing are transparent, while the same code in the Web Editor gives no transparency.
Another proof that there is something wrong with JS when a larger scale is used, is the following sketch. It doesn't play well with the wrong settings.  https://www.openprocessing.org/sketch/878781

**Comment by catarak** [comment]
Thanks for the update. I'm still having a hard time figuring out if you're reporting an issue with the p5.js library or with the p5.js Editor or both. What is working on OpenProcessing as expected and what is not working on the p5.js Editor as expected? Are there things that are not working as expected in either that are perhaps issues with p5.js itself? I'm just trying to figure out how to support you ✨

**Comment by EmmanuelPil** [comment]
The transparency problem seems to be a p5.js Editor problem since it works well on OpenProcessing.
The scale problem I have to issue on the P5.js GitHub I guess.
I only mentioned it here because I started with the error given when accessibility features are enabled, which maybe should have a notification that this can happen in the setting window itself.
Thank you for looking into this.
