### ISSUE TITLE
referencing uploaded files in index.html

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#165]
Noting here that if you upload an image, it works with both `loadImage()` and `createImg()`, but adding a reference to the image to `index.html` fails:

``` html
<img src="file.jpg">
```

This is, of course, due to the fact that the image actually lives in S3.  I'm not sure if this is actually something we can ultimately support, but if not, documenting or providing some sort of error might be good.

**Comment by catarak** [comment]
This is actually not too difficult to implement--as of right now I'm only parsing JS files for links to S3 files, since I figured at the beginning of the semester students wouldn't even be opening the CSS or JS files.

**Comment by catarak** [comment]
This is basically done in 81475c0e166b531147765e653bd51cfe982527af, though it would be nice to clean up this code a bit and share stuff between the client and server.
