### ISSUE TITLE
CORS issue with loadImage

### ISSUE THREAD

**Issue by vanevery** [processing/p5.js-web-editor#1650]
#### CORS issue between editor.p5.org and assets.editor.p5.org

- Found a bug

#### Details about the bug: 

- Web browser and version: 
- Operating System: MacOS X: Chrome Version 86.0.4240.80 (Official Build) (x86_64)
- Upload an image to the editor and attempt to load it with loadImage
- Get the following error in the JS Console

Access to fetch at 'https://assets.editor.p5js.org/5f6c09af5590b30020c08dee/113d0306-8bf6-4825-b13e-6952fff9acc6.jpg' from origin 'https://editor.p5js.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Here is the sketch that has this issue:
https://editor.p5js.org/vx0000/sketches/qpboKkN7B

**Comment by catarak** [comment]
Thanks for reporting! I was able to reproduce, and then I dug into the S3 bucket and now it's working for me? Super strange bug.

**Comment by quinn** [comment]
i'm having this issue in the p5.js editor, with a file uploaded into the editor. here's a demo:

https://editor.p5js.org/qshan/sketches/Lc10s6m60
