### ISSUE TITLE
sketch entries  in a collection don't sort

### ISSUE THREAD

**Issue by jht1493-gmail** [processing/p5.js-web-editor#1652]
- Found a bug viewing a Collection

When viewing sketches  in a collection can't sort by name or date.

- Web browser and version:  Chrome and Safari 

- Operating System:  MacOS 10.15.7 

- Steps to reproduce this bug:

Open a collection eg: https://editor.p5js.org/jht1493/collections/Gr9aCJs6t
Try clicking on Name or Date header.

Expected: sketches in collection to be sorted

Result: No sorting

**Comment by catarak** [comment]
Thank you for reporting! It would be great to make this table sortable. Since there are a few across the app, I think it makes sense to make a reusable, sortable, filterable table component!

**Comment by plxity** [comment]
@catarak I would like to work this.

**Comment by catarak** [comment]
@plxity go ahead! I would suggest working on the reusable table component rather than just fixing this one component.

**Comment by catarak** [comment]
I'm going to roll this issue into #1442. Really want to prioritize this!
