### ISSUE TITLE
Progress bar not functioning correctly

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#1653]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: macOS
- Steps to reproduce this bug:
1) Go to My assets section.
2) Check the progress bar.

<img width="1081" alt="Screenshot 2020-10-27 at 3 24 11 PM" src="https://user-images.githubusercontent.com/28510494/97285785-a642e780-1868-11eb-8c5e-ab06f664f9d9.png">

**Comment by KKVANONYMOUS** [comment]
I would like to work on this issue

**Comment by catarak** [comment]
Thanks for reporting! I can reproduce.

**Comment by plxity** [comment]
@catarak Can I work on this?

**Comment by catarak** [comment]
@plxity absolutely!
