### ISSUE TITLE
Can I get older version of my file??

### ISSUE THREAD

**Issue by Aditya2111-PRO** [processing/p5.js-web-editor#1661]
I was just working on my project and then suddenly it restarted I lost my older version....Can I get back my older version??
***I need my older version***

Thanks...

**Comment by catarak** [comment]
Unfortunately there isn't a way to get back an older version. Sorry about this!

**Comment by endurance21** [comment]
@catarak the auto save feature must be a good feature addtion ?

**Comment by endurance21** [comment]
if not on server , we can save those last changes to localStorage and if user revisit or refresh the page , the code would still be there being fetched from localStorage?

Extraa efforts can be made to store those changes on server too !

**Comment by catarak** [comment]
I'm going to roll this issue into #103.
