### ISSUE TITLE
Text in Sign Up page fades into background in dark mode

### ISSUE THREAD

**Issue by Swapnil-2001** [processing/p5.js-web-editor#1662]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome (86.0.4240.111)
- Operating System: Windows 10
- Steps to reproduce this bug:

While in dark mode, the "Already have an account?.." portion at the bottom fades into the background.

![p5 js Web Editor _ Signup - Google Chrome 01-11-2020 01_25_07](https://user-images.githubusercontent.com/53232360/97788956-d5e44d80-1be2-11eb-9d8a-729f75525d2b.png)

It should ideally look something like this:

![p5 js Web Editor _ Signup - Google Chrome 01-11-2020 01_25_44](https://user-images.githubusercontent.com/53232360/97788996-1d6ad980-1be3-11eb-99fd-809118a82537.png)

@catarak I'd be glad to change this if it would be handy.

**Comment by catarak** [comment]
@Swapnil-2001 thanks for reporting and go ahead and work on this!
