### ISSUE TITLE
Code folding no longer works in editor

### ISSUE THREAD

**Issue by aceslowman** [processing/p5.js-web-editor#1663]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome 83.0.4103.61 (Official Build) (64-bit)
- Operating System: Linux ( Ubuntu 18.04.4 LTS )

Code folding no longer works in the editor. The arrows in the gutter that are usually used to toggle folding don't respond to clicks.

**Comment by catarak** [comment]
Thanks for reporting! I'm sort of able to reproduce. I found that you have to be somewhat precise where you click on it, like sometimes it works and sometimes it doesn't. I'm assuming there's some hidden element that's blocking it or something. Could you try clicking in a few different spots and let me know if that works for you?

**Comment by aceslowman** [comment]
You're right! It looks like it responds to clicks to the left of the arrow, but not on the arrow itself. Probably wouldn't be as much of an issue if the cursor displayed as a pointer along the whole width of the gutter.

**Comment by catarak** [comment]
@aceslowman agreed! It seems like the solution to this is some investigation as to what's blocking the arrow, and then changing the CSS so when the mouse is over the arrow, it is `cursor: pointer`.

**Comment by aceslowman** [comment]
Just got things running locally and it actually seems to work just fine on the `develop` branch! It looks like there was a PR for a CodeMirror update, maybe the fix was in there.

**Comment by Swapnil-2001** [comment]
Hi @aceslowman @catarak.


> You're right! It looks like it responds to clicks to the left of the arrow, but not on the arrow itself. Probably wouldn't be as much of an issue if the cursor displayed as a pointer along the whole width of the gutter.

Yes, the code folding works all along the width of the gutter, however the `cursor: pointer` mode kicks in only when we hover directly over the arrow. Would changing it to `cursor: pointer` along the whole width of the gutter solve this? If so, I'd be happy to work on it.

**Comment by catarak** [comment]
> Yes, the code folding works all along the width of the gutter, however the `cursor: pointer` mode kicks in only when we hover directly over the arrow. Would changing it to `cursor: pointer` along the whole width of the gutter solve this? If so, I'd be happy to work on it.

I think it's okay to leave it as is. I'm going to mark this as fixed.

Fixed by #1660.
