### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by JD-RD** [processing/p5.js-web-editor#1666]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Following #595 I'd like to contribute to this awesome project by translating the app to french. However I have only a little experience about GitHub and React. Still, I already started the process...
 
I followed the [Translation Guidelines](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/translations.md) and 

- Created a new "translations.json" file inside a new folder named "fr-CA" and translated all strings from the english version
- Edited client/i18n.js
- Edited client/components/Nav.jsx

Please let me know if this enhancement is welcome!

Thanks :)

**Comment by oruburos** [comment]
Great @JD-RD, thanks. I really think that @catarak  would love to see more translations. What is the status of your branch? Are the translations working? is the dropdown showing? I think that the next step would be to create a PR and that someone can have a look at it.

**Comment by catarak** [comment]
@oruburos the translations are live! Right now only Spanish is enabled, but with #1664 open, the Japanese translation will be enabled soon! The French translation is definitely welcome—I recommend looking at the [Translation Guide](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/translations.md)! I also recommend looking at #1664 to figure out what you need to change to make it all work 😄

**Comment by JD-RD** [comment]
> Great @JD-RD, thanks. I really think that @catarak would love to see more translations. What is the status of your branch? Are the translations working? is the dropdown showing? I think that the next step would be to create a PR and that someone can have a look at it.

Yes, everything seems to work properly. I will look into how to do a proper PR asap :-)



> @oruburos the translations are live! Right now only Spanish is enabled, but with #1664 open, the Japanese translation will be enabled soon! The French translation is definitely welcome—

Great!

**Comment by catarak** [comment]
Let me know if you need any help or support!
