### ISSUE TITLE
Add option to Import Code from a Github Repo and Export code to a GitHub Repo of a user. 

### ISSUE THREAD

**Issue by samyakbambole** [processing/p5.js-web-editor#1667]
# New Feature Request. 

There must be an option in the Web editor to Import p5.js code from a GitHub Repository and Export the saved code to a new GitHub Repository of the user. This could be done using the GitHub API.

**Comment by catarak** [comment]
Thanks for the suggestion! I think this is a great idea. I think this is already captured at #753, so I'm going to close this as a duplicate.
