### ISSUE TITLE
Adding more info to Technical Part is useful?

### ISSUE THREAD

**Issue by koji** [processing/p5.js-web-editor#1675]
#### Nature of issue?

- Edit the document

#### Details about the bug: 

I just finished the Japanese translation. I thought maybe adding more details could be helpful for contributors to focus on translation itself.
What do you think? 

If you think this can be useful for contributors, I'm happy to open a new PR for this.

The current idea is the following.
### Adding a new item to Nav.jsx
```js
<li className="nav__dropdown-item">
              <button
                onFocus={this.handleFocusForLang}
                onBlur={this.handleBlur}
                value="ja"
                onClick={e => this.handleLangSelection(e)}
              >
                your language name in your language
              </button>
            </li>
```

### Adding your language info to i18n.js
import your langage from `data-fns/locale`

```js
import { enUS, es, ja, yourLang } from 'date-fns/locale';
``` 

```js
export function languageKeyToDateLocale(lang) {
  const languageMap = {
    'en-US': enUS,
    'es-419': es,
    'ja': ja
    'yourLang': yourLang your imported
  };
  return languageMap[lang];
}
```

**Comment by catarak** [comment]
I think this makes sense to add to `translations.md`! Go ahead and update it and open a PR 😄
