### ISSUE TITLE
Bad Gateway Error 502 on viewing a deleted sketch

### ISSUE THREAD

**Issue by idontknowjs** [processing/p5.js-web-editor#1676]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
When viewing a deleted sketch, instead of showing Page 404 not found
It's redirecting to cloudflare and showing 502 Bad gateway error

![image](https://user-images.githubusercontent.com/53327173/99146387-a121cd00-269d-11eb-901f-c224caf06127.png)

- Web browser and version: Chrome
- Steps to reproduce this bug:
Visit: https://editor.p5js.org/covalentbond/full/CNjP7hLts
This was the link of the deleted sketch

**Comment by catarak** [comment]
Thank you for reporting! The server must be crashing rather than properly handling a deleted sketch.

**Comment by KKVANONYMOUS** [comment]
@catarak I was able to reproduce the issue and would love to work on it.

**Comment by KKVANONYMOUS** [comment]
@catarak I have created a PR addressing this issue. Please review it and suggest any changes for the same, if any.
