### ISSUE TITLE
"Duplicate Sketch" button broken

### ISSUE THREAD

**Issue by bandaloo** [processing/p5.js-web-editor#1677]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Using "duplicate sketch" from the dropdown in "my sketches" doesn't duplicate the sketch; instead an uncaught error in promise appears. (Maybe I'm doing something wrong?)

![Screen Shot 2020-11-14 at 11 55 10 PM](https://user-images.githubusercontent.com/18533407/99170502-5623ac00-26d5-11eb-9536-43c0252018e2.png)

- Web browser and version:  Tested on Chrome 86.0.4240.198 (Official Build) (x86_64) and Firefox 82.0.3 (64-bit)
- Operating System:  macOS Catalina 10.15.7
- Steps to reproduce this bug: go to "my sketches" and try to duplicate a sketch

![Screen Shot 2020-11-14 at 11 56 13 PM](https://user-images.githubusercontent.com/18533407/99171289-c9c5b900-26d5-11eb-997d-32b8ff685c84.png)

Not sure this matters, but this is the sketch I'm trying to duplicate: https://editor.p5js.org/bandaloo/sketches/zXMOZkuYU

**Comment by bandaloo** [comment]
I found a workaround for myself: going to File > Duplicate works from within the editor: 
![Screen Shot 2020-11-15 at 12 11 01 AM](https://user-images.githubusercontent.com/18533407/99171451-2b3a5780-26d7-11eb-8a39-1f83ff86fe07.png)

**Comment by catarak** [comment]
Thanks for reporting! I am able to reproduce. There must be something wrong with the way that duplicate is called from the Sketch List versus from the Navigation.

**Comment by Swapnil-2001** [comment]
Hi @catarak , I would like to work on this, please.

**Comment by catarak** [comment]
@Swapnil-2001 go ahead!

**Comment by Swapnil-2001** [comment]
Thank you! Could you please suggest a suitable place where I could start looking?

**Comment by catarak** [comment]
Yes! I would look at how the `cloneProject` action is being dispatched in [Nav.jsx](https://github.com/processing/p5.js-web-editor/blob/develop/client/components/Nav.jsx#L196) versus in [SketchList.jsx](https://github.com/processing/p5.js-web-editor/blob/develop/client/modules/IDE/components/SketchList.jsx#L140) and figure out how they differ!
