### ISSUE TITLE
Credentials for Github Apps cannot be used to download examples sketch for p5 user in local development

### ISSUE THREAD

**Issue by vulongphan** [processing/p5.js-web-editor#1679]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Operating System: MacOSX 
- Steps to reproduce this bug:
  Create a Github Apps using your Github Account
  Fill in the `.env` file using your Credentials for Github Apps
  Then execute `npm run fetch-examples` to download the examples for a user p5
  There will be an error saying `401 - Bad Credentials`

**Comment by vulongphan** [comment]
Hi @catarak, this is an additional issue I discussed with you in [#1595](https://github.com/processing/p5.js-web-editor/issues/1595) regarding the credentials issue with a Github App. In my PR I updated the installation guide so that other people will not run into the same issue as me.

**Comment by vulongphan** [comment]
Also @catarak  you can tell me if there is any problem with the document update.

**Comment by catarak** [comment]
Thanks for updating the documentation! I'll leave suggestions directly on your PR.
