### ISSUE TITLE
Add limit for total file uploads

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#168]
Each user should have a limit on the total size of the files they've uploaded to S3.

**Comment by uttpal** [comment]
@catarak I would like to fix this issue

**Comment by catarak** [comment]
awesome! it may make sense to work on #167 or #169 first, and #167 has an open PR, #222, with a bug so it hasn't been merged yet.

**Comment by catarak** [comment]
definitely! i think this one will take a little bit of time. let me know if you get stuck!
