### ISSUE TITLE
console not printing anything 

### ISSUE THREAD

**Issue by Ashwin236** [processing/p5.js-web-editor#1685]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by Wildernesss** [comment]
Hi everyone,

Same problem... That is recent. In p5.js online editor, the print() function does not work anymore in the console panel of the editor. The problem happens only into p5.js editor console. Print() still write into browser console.

It would be great if this could be corrected soon :o)

Thanks a lot.

Laurent

**Comment by catarak** [comment]
Thanks for reporting! This should be fixed now. This is due to a feature I have been working on (interactive console!!!) that only breaks on production (locally and on the staging URL it works perfectly 😠 ). Fixed by https://github.com/processing/p5.js-web-editor/pull/1684

**Comment by Wildernesss** [comment]
Thanks so much Cassie for your very quick reaction and fix! And for all your work and thanks also to other peope working on p5.js and this editor. Really great tools!

Laurent
