### ISSUE TITLE
Refactor `fetch-examples` script to only use async/await

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1693]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

The file [`examples.js`](https://github.com/processing/p5.js-web-editor/blob/develop/server/scripts/examples.js) has been edited by many people over the years and could use a refactor. It uses callbacks, Promises, and async/await, and I think that it should be refactored to just use async/await.

**Comment by Swapnil-2001** [comment]
Hi @catarak can I take up this issue please?

**Comment by catarak** [comment]
@Swapnil-2001 absolutely!
