### ISSUE TITLE
Too many warnings while compiling the code on a local machine.

### ISSUE THREAD

**Issue by Kaushal-Dhungel** [processing/p5.js-web-editor#1698]
#### Details about the bug: 

This is not actually a bug but a lot of warnings can be seen while running the code on a local machine. There are a lot of imports that are not used in the code. For example:-

![image](https://user-images.githubusercontent.com/57295839/100753096-5b8c3080-340f-11eb-945e-4fb9dfd25c16.png)

in the given image you can clearly see that there are many unnecessary imports due to which there are a lot of warnings.

**Comment by catarak** [comment]
Thanks for reporting! I agree that these are annoying and it would be great to them.

**Comment by Kaushal-Dhungel** [comment]
I would like to work on it. Can I take this??

**Comment by catarak** [comment]
@Kaushal-Dhungel absolutely!

**Comment by Kaushal-Dhungel** [comment]
While solving this issue, after performing my first commit, I saw another eslint warning "Line X exceeds the maximum line length 120 max-len". 
![image](https://user-images.githubusercontent.com/57295839/101274291-ce582b80-37c2-11eb-9c10-73bbf6bdbb6b.png)
I would like to solve that as well.

**Comment by catarak** [comment]
> I would like to solve that as well.

Go ahead!
