### ISSUE TITLE
Improve keyboard accessibility of the find-replace popup

### ISSUE THREAD

**Issue by SundeepChand** [processing/p5.js-web-editor#1699]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Hello @catarak, sorry for being AFK for quite a while. Since the find & replace feature has been released, I think the order in which the input fields on the popup are accessed on Tab presses can be changed for better UX. I would like to work on this.

**Comment by catarak** [comment]
Yes! Absolutely.
