### ISSUE TITLE
Default sidebar: default visible or hidden?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#17]
When you are a beginner and run the editor for the very first time should you see the sidebar?  I think I vote for no sidebar.

<img width="870" alt="screen shot 2016-07-21 at 2 27 28 pm" src="https://cloud.githubusercontent.com/assets/191758/17034144/5958a2d4-4f4f-11e6-94de-8163713387a7.png">

OR

<img width="860" alt="screen shot 2016-07-21 at 2 28 24 pm" src="https://cloud.githubusercontent.com/assets/191758/17034163/6d33b50a-4f4f-11e6-995c-9ac526830afe.png">

**Comment by lmccart** [comment]
default hidden makes sense to me
