### ISSUE TITLE
Adding Hindi as a part of i18n.

### ISSUE THREAD

**Issue by abhieshekumar** [processing/p5.js-web-editor#1701]
#### Nature of issue?

- Existing feature enhancement

I will like to add Hindi to as a part of i18n.

**Comment by SundeepChand** [comment]
@abhieshekumar That's a great idea.

**Comment by abhieshekumar** [comment]
Yes @SundeepChand. Let's see if the idea gets approved.

**Comment by catarak** [comment]
This is a great idea! There are actually more web editor users in India than in English-speaking countries, so I think this is super important.

**Comment by abhieshekumar** [comment]
Great. I have gone through the steps on adding a new language and will start the process.

Thank you.

**Comment by koji** [comment]
@abhieshekumar 
https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/translations.md#technical-part

Recently, I added Japanese translations and update the translations guide.
I'm happy to support you if you need something from me since my Indian friends have helped people to learn programming via p5js.

**Comment by abhieshekumar** [comment]
There are several instances where instead of using the translated version of a word, the word's pronunciation can be written in Hindi.

For example 'Share' can be written either as -

- 'साझा करें' which is the actual Hindi translated equivalent of Share, or,
- 'शेयर' which is nothing but the pronunciation of the word 'Share' written in Hindi. One will pronounce both Share and शेयर in the same way. This approach is fairly common for a lot of words such as Home, Comment, File, et cetera.

However, which approach should be followed in the project.

@catarak and @SundeepChand what are your thoughts about it? @koji how did you handle it while translation?

**Comment by koji** [comment]
@abhieshekumar 
Actually, I used the words' pronunciation instead of translating because sometimes a translation doesn't really make sense to people.
I recommend you to get feedback from people who know both languages because I did that to make a decision.

**Comment by abhieshekumar** [comment]
Thanks @koji.

It is also pretty common to do the same here. A lot of websites/app use the same approach.

**Comment by SundeepChand** [comment]
> Thanks @koji.
> 
> It is also pretty common to do the same here. A lot of websites/app use the same approach.

Yeah @abhieshekumar, it makes most sense to use words' pronounciation wherever it is appropriate.

**Comment by catarak** [comment]
@abhieshekumar let me know if you need help soliciting feedback on the Hindi translation! I'm happy to post on p5.js/Processing social media, reach out to folks in the Processing India community, etc.

**Comment by rt1301** [comment]
@abhieshekumar  If possible I would also like to work on this. I am also from India and am proficient in the Hindi Language

**Comment by abhieshekumar** [comment]
@rt1301 sure thing. I have already done the ```initial setup``` and am adding translated strings. You may go through the changes that I have made [here.](https://github.com/processing/p5.js-web-editor/compare/develop...abhieshekumar:i18n-hindi) 

The task now is to add the remaining translations. We can split that based on the structure of the ```translations.json``` file. For example you may choose to translate strings under ```KeyboardShortcuts``` key. We can decide on what keys we will be working on to avoid any conflicts later.

**Comment by rt1301** [comment]
@abhieshekumar  That's great! I'll look into the PR that you have made and try to start working on the strings below keyboard shortcuts for now

**Comment by abhieshekumar** [comment]
Ok. @rt1301 I have made a list of keys which still need translation. 

1. DashboardView
2. CollectionCreate
3. AddtoCollectionList
4. Collection
5. CollectionView
6. ShareModal
7. FileUploader
8. UploadFileModal
9. Searchbar
10. Feedback
11. AssetList
12. EmailVerificationView
13. APIKeyList
14. AccountView
15. NewFolderModal
16. NewFileForm
17. NewFileModal
18. IDEView
19. FileNode
20. Sidebar
21. KeyboardShortcuts
22. Console
23. Toolbar
24. SocialAuthButton
25. CodemirrorFindAndReplace 
26. Edit

Would you be comfortable in splitting it in half? I will do the first 13 and you can do the rest. 

Also few words have already been translated for example ```"Username": "यूजरनेम"```or ```"Autosave": "ऑटोसेव"```. So, just make sure to use the same translations throughout.

**Comment by rt1301** [comment]
@abhieshekumar  Ok I'll do the ones from 13-26.

**Comment by abhieshekumar** [comment]
@rt1301 (#1723) and I (#1703) have added the translations. @catarak take a look at it. Some feedback on the translations will definitely help to address any issues. Thank you.

> @abhieshekumar let me know if you need help soliciting feedback on the Hindi translation! I'm happy to post on p5.js/Processing social media, reach out to folks in the Processing India community, etc.

**Comment by catarak** [comment]
@abhieshekumar are the translations ready to be reviewed? If so, let's figure out a way to combine the two PRs—I think it will be easier to review that way!

**Comment by abhieshekumar** [comment]
Yes @catarak, the translations are ready to review.

**Comment by catarak** [comment]
Fixed by #1703.
