### ISSUE TITLE
Lag in bringing the cursor back to it's original postion after tidy operation.

### ISSUE THREAD

**Issue by namanarora00** [processing/p5.js-web-editor#1705]
#### Nature of issue?

Found a bug

#### Details about the bug: 

There is a small lag in moving the cursor to its original position after the tidy operation. This I believe is because we wrap the function in a setTimeout which delays it.

```javascript
setTimeout(() => {
      this._cm.focus();
      this._cm.doc.setCursor({ line: currentPosition.line, ch: currentPosition.ch + INDENTATION_AMOUNT });
}, 0);
```
Why do we need to use setTimeout here as the position to which we're bringing back the cursor is simply the old line number and character number.

- Web browser and version: Chrome Version 87.0.4280.88 
- Operating System:  MacOS Big Sur
- Steps to reproduce this bug: Execute the tidy operation using either the keyboard shortcut or in the menu.

**Comment by catarak** [comment]
Thanks for reporting! Do you want to try to work on this one? You can try removing the `setTimeout` and see what happens—I believe the reason for adding it was that calling `setValue` (in the code above the lines you added) resets the cursor position, which could happen after `setCursor` is called without wrapping it in `setTimeout`.

**Comment by namanarora00** [comment]
Hi @catarak, thank you for your response. I had a [conversation](https://discuss.codemirror.net/t/is-the-order-preserved-in-execution-of-doc-operations/2764) with the maintainer of codemirror and it seems we do not require `setTimeout` in this case. I tried removing `setTimeout` and using tidy and it seems to be working without any lag. Please let me know if it's fine and I can submit a PR.

**Comment by catarak** [comment]
@namanarora00 I'm glad it works! Go ahead and open a PR ✨
