### ISSUE TITLE
WebEditor Hangs with createVector in constructor

### ISSUE THREAD

**Issue by dacaldera** [processing/p5.js-web-editor#1709]
- Found a bug

Chrome: version:  85.0.4183.83
MacOS Mojave 10.14.6

To reproduce the bug: 
The hanging seems to be related to createVector when assigned inside the constructor, and then trying to call a method within the constructor that references the mentioned vector. 

Here is the offending code snippet. 

let pg;

function setup() {
  createCanvas(400, 400);
  pg = new PointsGroup();
}

class PointsGroup {
  constructor() {
    this.bounds = createVector(200, 200);  
    this.points = this.prepare_points();      
  }
  
  prepare_points() {
    var p = [];
    for (var i = 0; i < this.bounds.x; i + 10) {.    
      for (var j = 0; j < this.bounds.y; j + 10) {
        p.push(createVector(i, j));
      }
    }
    return p;
  }
}

And a link to the above editor sketch: 
https://editor.p5js.org/dacaldera/sketches/HMGLWXz-X

**Comment by dacaldera** [comment]
Just found a mistake in the code which I think was causing the issue. Please disregard this  bug report.

**Comment by catarak** [comment]
Glad you figured out the issue you were having!
