### ISSUE TITLE
Adding a tooltip to play and refresh buttons

### ISSUE THREAD

**Issue by m-e-l-u-h-a-n** [processing/p5.js-web-editor#1710]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Although the use of the play and refresh buttons in the top left corners is pretty self explanatory, I think adding a `tooltip` can really help newcomers and new users who are trying to familiarize themselves with the web editor.

**Comment by catarak** [comment]
Thanks for the suggestion! My opinion is that they aren't necessary, as I think play and pause icons are really, really common. Feel free to reopen if you disagree!
