### ISSUE TITLE
Change keyboard shortcut for tidy code

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1711]
@namanarora00: "Instead of deleting the keymap for Shift+tab, could we change the keyboard shortcut for tidy itself since Shift+Tab is a commonly used shortcut for unindenting?"

_Originally posted by @namanarora00 in https://github.com/processing/p5.js-web-editor/issues/1708#issuecomment-745754560_

**Comment by catarak** [comment]
It could be changed. I think I had originally decided to use <kbd>Shift</kbd> + <kbd>Tab</kbd> because that was what CodePen had used in the past, but I just checked and now they changed it to <kbd>Shift</kbd>+<kbd>Command</kbd>+<kbd>F</kbd>. 

I think when I started this project 4.5 years ago, Visual Studio Code wasn't around, and now that it's gotten so popular, some of the common keyboard shortcuts have changed :smile:

**Comment by namanarora00** [comment]
What about customizable keyboard shortcuts? Does it make sense to add this or is it a bit much? Let me know what you think.

Also, just curious, what editor did you use when you started the project? :)

**Comment by catarak** [comment]
I think adding customizable keyboard shortcuts doesn't make sense for this project. It feels to me like an advanced user feature, and the target audience for the web editor is beginner/intermediate folks. Instead I think it makes more sense to just pick a keyboard shortcut that feels conventional/common!

When I started this project, I was using Sublime Text, and switched to VSC a couple of years ago. I still use Sublime Text keyboard shortcuts in VSC just because I know them 😄

**Comment by vulongphan** [comment]
@catarak if you don't mind I will work on changing the current <kbd>Command</kbd> + <kbd>Tab</kbd> to <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>T</kbd> for tidying code

**Comment by catarak** [comment]
You can go ahead and work on this @vulongphan! I would recommend changing the shortcut to <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd>. I would also make sure that you remove the changes from aa2bc5d.

**Comment by vulongphan** [comment]
@catarak could you please check my PR :blush:

Thank you!
