### ISSUE TITLE
Open/Close folders by clicking on folder names

### ISSUE THREAD

**Issue by SundeepChand** [processing/p5.js-web-editor#1712]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Currently the contents of a folder are shown/hidden by clicking on the arrow button provided on the left of the folder name. However, I think it would be more convenient (from user's perspective) to show/hide the folder contents by clicking on the entire div. What are your thoughts about this @catarak? Can I work on this?

**Comment by catarak** [comment]
Thanks for the suggestion! This makes sense to me. Feel free to work on this issue!

**Comment by raclim** [comment]
I think that this might not be a large priority and am going to close this issue for now, but am definitely down to revisit this in the future!
