### ISSUE TITLE
Using React-Joyride to create short tutorial of the website

### ISSUE THREAD

**Issue by kernelpanic77** [processing/p5.js-web-editor#1715]
#### Nature of issue?

- New feature request

#### Feature enhancement details:
Tutorial for editor using react-joyride npm package.

![Screenshot from 2020-12-17 21-42-34](https://user-images.githubusercontent.com/42925218/102513393-29d2c500-40b1-11eb-9ac8-ae15fe5a71f7.png)

#### New feature details:
Using the react-joyride npm package we can create a way to guide new users to features of the website.
https://react-joyride.com/

Pls assign me to this issue. I would like to work on this.
@catarak any suggestions ?

**Comment by SundeepChand** [comment]
@MegaMind77-coder This sounds cool.

**Comment by kernelpanic77** [comment]
Yeah  @SundeepChand 
@catarak  Can I be assigned to this issue ? 
I will post a PR soon.

**Comment by catarak** [comment]
Thanks for the suggestion! I think this is a great idea. I believe there are open issues about this (see #806). That being said, before working on any code for this, I think this would need to be planned and designed. I have questions like:
- What do interactive tutorial experiences look like for other tools?
- How buried/available is the tutorial? Does the tutorial appear for all new users? Can it only be accessed through a help menu?
- What are the core features that should be covered?
- Translations?
- How would you prototype this? Get feedback from users before implementing this?

I appreciate your enthusiasm, I just want to go through the right research/planning/design process before writing a bunch of code!

**Comment by kernelpanic77** [comment]
Yeah, this feature should be well-planned and designed. 

- You should check out [https://circuitverse.org/simulator](url), click on the tutorial guide option from the help dropdown. 
   It would create a similar tour. 
- I think we should add the tutorial option to the help menu as you mentioned.
- The basic features can be mentioned in the tutorial.
  As you mentioned in the comments of #806, We can use this video for reference [https://www.youtube.com/watch?v=x1rJJRVTpAI](https://www.youtube.com/watch?v=x1rJJRVTpAI)
- To be honest, I don't know how we could add translations for the tutorial. But we can discuss it here.

**Comment by catarak** [comment]
closing into #748
