### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. 

### ISSUE THREAD

**Issue by rabbitrg** [processing/p5.js-web-editor#172]
This error presents itself with the majority of API requests.  This particular instance is making a request to a publicly accesssible endpoint that doesn't require any authentication.  The editor is being used with https.

Error:
XMLHttpRequest cannot load https://feeds.citibikenyc.com/stations/stations.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://alpha.editor.p5js.org' is therefore not allowed access.

Sketch below:
function setup(){
  createCanvas(400,400);
  var url = 'https://feeds.citibikenyc.com/stations/stations.json'
  loadJSON(url, 'cititest.json');
}

**Comment by catarak** [comment]
The issue here is not with https or the editor, but with the Citibike API itself. This endpoint has CORS disabled, which means that it loads fine when you navigate to the URL in your browser, but when p5.js makes an AJAX request to the URL, it is blocked.

You can look at this ticket, [processing/p5.js/#1451](https://github.com/processing/p5.js/issues/1451) for more information.

**Comment by VashaTS** [comment]
I get the error:
"Access to XMLHttpRequest at 'https://assets.editor.p5js.org/' from origin 'https://editor.p5js.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource."

When trying to upload a font file to the editor.

Is this the same error? I don;t use any external service

**Comment by catarak** [comment]
@VashaTS can you link to the sketch that has this issue? i think that'll help me figure out what's happening here.

**Comment by VashaTS** [comment]
@catarak https://editor.p5js.org/sajmon313/sketches/NaXcy24Lp

**Comment by catarak** [comment]
@VashaTS thanks! this is actually the correct behavior. the web editor can't load the font files hosted on your server because of CORS!

**Comment by VashaTS** [comment]
@catarak why I can't upload font files to the editor then? The error message I provided in the earlier post was when trying to upload file into the editor.

**Comment by catarak** [comment]
oh i see! i thought that was the error you got when you tried to load your font from your server. 

i just tried making a simple sketch with your font file (https://editor.p5js.org/cassie/sketches/y7kv56ZM6) and it seems like it's not supported by p5.js.

**Comment by VashaTS** [comment]
Hmm ok then, what type of font will work?
 I tried both .ttf and .otf 

Some font has to work sicne there is loadfont() function

**Comment by VashaTS** [comment]
I guess I have to do my own function drawing the font pixel by pixel then :(

**Comment by catarak** [comment]
otf and ttf fonts should work! i think there is something not right with that specific font file. i don't really know anything about font formats, but maybe there's a font file validator or something like that?

**Comment by catarak** [comment]
update: just tried using the mac font validator and it says it's okay. i recommend opening an issue in the p5.js library itself, and attach the font file.

**Comment by catarak** [comment]
i just found a typo in https://editor.p5js.org/cassie/sketches/y7kv56ZM6, and have now fixed that 🤦‍♂️ the good news is, is that you should be able to use the font file! let me know if you are able to use the font file by duplicating that sketch.
