### ISSUE TITLE
[Developer Experience] Use Github Actions to providing linting feedback on PRs

### ISSUE THREAD

**Issue by hydrosquall** [processing/p5.js-web-editor#1720]
#### Nature of issue?

- New feature request (This would likely reuse #861 )

#### New feature details:

- Setting up https://github.com/marketplace/actions/lint-action would give developers feedback immediately if their change introduces a regression in formatting. This would prevent the need for commits like https://github.com/Kaushal-Dhungel/p5.js-web-editor/commit/d444aca7a2627d4f4f741d5478ab416adcfe438a .
- The integration has the ability to auto-fix errors. However, I could see this possibly being confusing to new contributors if they don't know about how to merge those changes back into their local branch. I'd recommend erring on the side of using client-side pre-commit hooks instead if we wanted to make auto-fixes part of the developer experience. https://prettier.io/docs/en/precommit.html

**Comment by hydrosquall** [comment]
Ah I see that https://travis-ci.com/github/processing/p5.js-web-editor/jobs/456150755 exists, perhaps the issue was more about what mismatches constitute "warnings" vs "errors".

With that said, it may be worthwhile to migrate anyways given that the future of open source plans in Travis seems uncertain- I migrated the CI for my own project a few weeks ago for this reason. 

https://github.com/hydrosquall/tiingo-python/pull/546

**Comment by catarak** [comment]
Thanks for opening this issue! `husky` linting hooks got added to this project so that linting errors aren't getting committed to this project anymore. I'm also in the process of adding `prettier` which will also help with linting issues.

I didn't know that Travis had changed their open source pricing—I'm going to reach out to them right now to see if we can get some credits!

**Comment by catarak** [comment]
Fixed via #1735.
