### ISSUE TITLE
Navbar prop 'isUserOwner' is marked as required, but its value is 'undefined' - Jest Error

### ISSUE THREAD

**Issue by rt1301** [processing/p5.js-web-editor#1724]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
While running `npm run test`, the following error is shown :

> Failed prop type: The prop `isUserOwner` is marked as required in `Nav`, but its value is `undefined`.

- Operating System:  Windows 10 (64-bit)
- Steps to reproduce this bug: run the command `npm run test` in the command line

![Navbar-err](https://user-images.githubusercontent.com/63252510/103445469-70701400-4c9a-11eb-8d30-a0fcccb2cb48.png)

**Comment by catarak** [comment]
Thanks for reporting! I am able to reproduce.

**Comment by Swapnil-2001** [comment]
Hi @catarak I would like to work on this please. Could you suggest where I should start looking?

**Comment by SundeepChand** [comment]
Hi @Swapnil-2001 . The test for `client/components/Nav.jsx` is written in `client/components/__test__/Nav.test.jsx`

**Comment by Swapnil-2001** [comment]
Thanks @SundeepChand, I'll start working from there.

**Comment by markogrady1** [comment]
can i fix this, unless its still being worked on?

**Comment by Swapnil-2001** [comment]
Hi @markogrady1, I intended to fix this but got caught up in other work. You can take it up if you wish.

**Comment by markogrady1** [comment]
nice one. I will work on this @Swapnil-2001 if thats ok @catarak
