### ISSUE TITLE
Lost a file

### ISSUE THREAD

**Issue by carterjohnson** [processing/p5.js-web-editor#1725]
Hi. I was working online on a short project yesterday and now it isn't in my sketches.

My username is **_carterjohnson_**, and the sketch name was **_missile_**.

One of the assets of the project is present in my assets, however, but with a different name. Its name in my assets is:
**02241f7f-7413-490b-9f34-c745dee1c345.png**

I'd appreciate some help if possible.
Thank you.

**Comment by catarak** [comment]
I'm really sorry that happened! Unfortunately I'm not sure I'm going to be able to recover your sketch. Can you give me more details about what you were doing and when you noticed it was missing?
