### ISSUE TITLE
The project open in editor does not reset upon logout.

### ISSUE THREAD

**Issue by SundeepChand** [processing/p5.js-web-editor#1726]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome (Version 87.0.4280.88 (Official Build) (64-bit))
- Operating System: Windows 10 (64-bit)
- Steps to reproduce this bug:
    1. Log in to the web editor.
    2. Open any sketch project.
    3. Now logout.
    4. The project remains open (while the expected behaviour is that it would create a new empty project).

@catarak I think fixing this will be a good first step towards implementing #1635. What are your suggestions about this? I would like to work on this.

**Comment by catarak** [comment]
Thanks for reporting! I think it makes sense to make this change.
