### ISSUE TITLE
Script reverts to old version

### ISSUE THREAD

**Issue by braxtondb** [processing/p5.js-web-editor#1728]
Found a bug.

- Web browser and version: Chrome, 87.0.4280.88 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 10
- Here's what _I_ did, but I don't know if it is all required:
1. Go to one of your scripts
2. Make some changes - I coded for a good hour or two
3. Save profusely while editing
4. When finished making changes and you are satisfied, it shows as saved and you should be good to close out of the tab -- I did not. Just switch to another tab for a while
5. After "a while" has passed, perhaps a couple of hours: Sometimes when you come back to your script it will, for some reason, display an older version of the script. In my case, it went back to the version I started with when I started editing that session. This has happened before, and normally you can fix it by refreshing the page **without** making any changes. Making changes and saving, however, will overwrite the entire script with the old version of it. Unfortunately, I had no clue it was reverted in this case, and I just popped in to make some notes only to find out that I now have to reprogram my entire game.

Aside from somehow fixing this issue, I think it would be nice if p5js had some kind of version history implemented, which could also help solve it. Even storing just the last 2-3 versions would be helpful.

**Comment by catarak** [comment]
Hey @Novarender, thanks for reporting and I'm super sorry that happened! That sounds really, really frustrating. I believe the solution here is implementing adding changes to sketches using CRDT's (see recommendation [here](https://github.com/processing/p5.js-web-editor/issues/1337#issuecomment-616817323)), as opposed to simply replacing the entire contents of the JS/CSS/HTML/etc. file. This would also help with potentially saving multiple versions of sketches!

**Comment by catarak** [comment]
Closing into #1635 / #1759
