### ISSUE TITLE
Open file when created

### ISSUE THREAD

**Issue by njberman** [processing/p5.js-web-editor#1731]
#### Open a file when it is created

- New feature request

#### New feature details:
When a file is created:
![image](https://user-images.githubusercontent.com/67945050/103926689-2a3f0880-5111-11eb-8671-ebdb488e11a1.png)
<br>
It doesn't open that new file.
<br>
The request is to make it open the new file when the file is created

**Comment by catarak** [comment]
Thanks for the suggestion! I think this behavior makes sense—this what happens in VSC, Glitch, etc. @rikdewit I see that you're working on this, which you can keep doing 😄

**Comment by rikdewit** [comment]
> Thanks for the suggestion! I think this behavior makes sense—this what happens in VSC, Glitch, etc. @rikdewit I see that you're working on this, which you can keep doing 😄

Thanks for responding! This is my first try on a pull request, so I had some problems rebasing from and into the right branch. I hope this is helpful.
