### ISSUE TITLE
Keyboard input only affect interface elements not canvas.

### ISSUE THREAD

**Issue by pedroAlTo** [processing/p5.js-web-editor#1734]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

In my profile at least, I can't test keyboard inputs as it seems I can't focus on the canvas, no matter what I do.
In the next example there's a exercise I had to do for a project in university (but it happenes with any other project I load):
https://editor.p5js.org/pedro.alm.to/sketches/ENFfF32lo

I take this as an example because it has some keyboard interaction pressing space should make the words move and cusor left/right should cycle between news.

Instead I can only work on the interface or even write in the code window.

To illustrate this I uploaded a screen capture video:

#### New feature details:

**Comment by catarak** [comment]
Thanks for reporting! This is actually an error in your sketch: on line 89, you have `return: false` from the function `mousePressed()`, which prevents the default behavior for pressing the mouse on the canvas, which is to move the focus to the canvas. If you remove this line, then you can focus on the canvas.
