### ISSUE TITLE
Cannot upload or create .xml file into editor.p5js

### ISSUE THREAD

**Issue by Wildernesss** [processing/p5.js-web-editor#1741]
Hi everyone,

Teaching the different data file format, I need to upload a .csv, .json and .xml file into p5.js web editor. Doing this, the editor  gives an error message (after upload trial) : 'You can't upload files of this type'. When trying to create an empty .xml file, the editor says: 'Invalid file type. Valid extensions are .js, .css, .json, .txt, .csv, .tsv, .frag, and .vert.' So it's impossible to work with .xml files...

I don't see any reason to forbid adding .xml file to an online Processing project. Even more when p5.js librariy provides a loadXML() function and resources in order to process .xml data. Is it a bug and could it be corrected?

Thanks a lot for your attention and help!

Laurent
 
- Web browser and version: Google Chrome Version 86.0.4240.75 (Build officiel) (32 bits)
- Operating System: Windows 10 Pro 64 bits version 1909 / 18363.1316

**Comment by catarak** [comment]
Thanks for reporting! You are right, this is a bug. Luckily, it's a simple fix—this file extension just needs to be whitelisted.

**Comment by Wildernesss** [comment]
Thanks a lot for your quick answer Cassie! Glad to know it's just a very small bug and it could be resolved easily without to much effort. 

By the way, I've just observed that it is also not possible to create or rename a file with **.html** extension. It can be usefull to have the possibility to add .html pages to a project, in order to show and let students experiment the opportunity of different graphic user interfaces and different modules into a same project.

Thanks for all your work and this of others on this great tool!

**Comment by SundeepChand** [comment]
Hello @catarak. Can I work on this?

**Comment by catarak** [comment]
@SundeepChand yes! go ahead

**Comment by catarak** [comment]
@Wildernesss I'm going to break out the HTML file issue into a separate issue.
