### ISSUE TITLE
Cannot Load the Web Editor

### ISSUE THREAD

**Issue by WenhaooWuu** [processing/p5.js-web-editor#1746]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by WenhaooWuu** [comment]
I am a student who tried to learn to code with p5js whereas I found out that though having changed multiple browsers as well as computers, the web editer could not even load. Wonder what is the problem.

**Comment by catarak** [comment]
Thanks for reporting! Are you able to open the browser console and see if there are any errors? Also, are you located someone that restricts Internet traffic? Maybe the web editor is using a hosting service that you cannot access.
