### ISSUE TITLE
Cannot create new .html file in editor

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1749]
> By the way, I've just observed that it is also not possible to create or rename a file with **.html** extension. It can be useful to have the possibility to add .html pages to a project, in order to show and let students experiment the opportunity of different graphic user interfaces and different modules into a same project.

> Thanks for all your work and this of others on this great tool!

_Originally posted by @Wildernesss in https://github.com/processing/p5.js-web-editor/issues/1741#issuecomment-770216900_

I've noticed that you can upload an html file and rename them, but you cannot create an html file. I believe this is because it's missing from the variable TEXT_FILE_REGEX.

**Comment by MohdImran001** [comment]
@catarak, I would love to work on it.

**Comment by MohdImran001** [comment]
@catarak , Can I work on it ?

**Comment by frappelatte28** [comment]
@catarak TEXT_FILE_REGEX is working fine i have checked it online with [this](https://www.regextester.com/) online tester. There might be some other issue.

**Comment by frappelatte28** [comment]
@catarak i figured it out , its the problem with `CREATE_FILE_REGEX` assosiated with new-form component !
I have attached a PR to solve the same.
