### ISSUE TITLE
Delete p5.js account!

### ISSUE THREAD

**Issue by Giulia9244** [processing/p5.js-web-editor#1753]
Good Morning,

I'm desperately trying to delete my p5.js account, anybody can help me?
I don't get why on the p5 website there isn't any possibility to delete the account, I'm so angry about that...

Thank you guys!
Giulia

**Comment by Giulia9244** [comment]
> Welcome! 👋 Thanks for opening your first issue here! And to ensure the community is able to respond to your issue, be sure to follow the issue template if you haven't already.

HOW?

**Comment by catarak** [comment]
Hi @Giulia9244! Apologies that there's not currently a way to delete your account through the website; however, I can do it manually. What is your username?

**Comment by Giulia9244** [comment]
Hey Cassie,
Sorry but I think this isn’t the way you do it... I mean, the official website doesn’t offer the possibility (is it even legal???) but an external person can do it?
Thank you! :)

Inviato da iPad

**Comment by catarak** [comment]
@Giulia9244 i'm sorry there is not another way to do it. you can email me at cassie@processing.org if you would like to send me your username there. we have hired lawyers and are working on a privacy policy/terms of service to make sure we are following legal processes, but this is a work in progress.

**Comment by Giulia9244** [comment]
Dear Cassie,

I’m stil (actually WE) thrilled about this procedure… I don’t doubt you are legally working, but it still is pretty absurd…
Never seen another app/ website working so, not presenting a “Delete your account section” and neither a direct contact with the relative department, forcing people to randomly write in a community, plus registering in there!

The account to delete with all its information is linked  to username Giulia9244

All the best,
Giulia

**Comment by catarak** [comment]
Your account has been deleted. I hear that you are frustrated in this process and we can work to improve it. We are doing our best—this is not a commercial product but is supported by grants and donations and a community of volunteers.

**Comment by Giulia9244** [comment]
Thank you really much!

Inviato da iPhone
