### ISSUE TITLE
Error when deleting sketch that contains file url not on s3

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1764]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  N/A
- Operating System:  N/A
- Steps to reproduce this bug:

In testing #1762, I found that the script will fail when deleting the uploaded sketches. I believe it is a bug in [`deleteProject.js`](https://github.com/processing/p5.js-web-editor/blob/1712ffa033c1937e4168b697c155dbd62907950a/server/controllers/project.controller/deleteProject.js#L14), which doesn't check if the url is specifically an AWS S3 url!

**Comment by bomanimc** [comment]
Thanks for catching this!
