### ISSUE TITLE
Update public_api.md in developer_docs to set UI_ACCESS_TOKEN_ENABLED=true

### ISSUE THREAD

**Issue by SundeepChand** [processing/p5.js-web-editor#1769]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Hello @catarak. While working on #975 it took me a few hours to figure out how to enable access token UI in settings page. I think it would be nice if it is mentioned in the docs to set  `UI_ACCESS_TOKEN_ENABLED=true` in the .env file. I would like to work on this.

**Comment by afeefuddin** [comment]
Hey @raclim , I want to work on this issue!! Can you assign me this?

**Comment by jsndz** [comment]
I would also like to work on this issue

**Comment by owais0017** [comment]
i m new to open source kindly let me work on this

**Comment by PiyushThapaa** [comment]
i would like to work on this issue please assign it to me
