### ISSUE TITLE
"Find next" and "Find previous" popups glitches to close

### ISSUE THREAD

**Issue by satyasaibhushan** [processing/p5.js-web-editor#1774]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 88.0.4324.150 (Official Build) (x86_64) (also tried on Safari, the issue remains the same)

- Operating System:macOS Version 11.2.1 
- Steps to reproduce this bug:
     1. While editing a file, click on find next( /prev ) on edit dropdown in the Navigation bar or use keyboard shortcuts  
     2. If you click on the left side of the screen (on the play button or the editor) the popup just disappear which is not the desired behaviour
     3. If you click on the right side of the screen (on the preview section) the popup just freezes and don't close which is a major bug 

###### attaching a video for reference

https://user-images.githubusercontent.com/40578313/108748979-39650300-7565-11eb-99f9-b36d0c9783a6.mov

**Comment by satyasaibhushan** [comment]
Hey @catarak or Anyone ,
I think the ideal functionality will be mimicking the "find" popup functionality.
Presently, the "find next" or "find previous" is working by creating a new popup that's not "find" popup i.e, all three finds have their different popups 
I think the issue will be solved if we somehow managed to use only one popup for all 3 functionalities 
Please share your thoughts!!

**Comment by catarak** [comment]
Hi @satyasaibhushan! In #1243, "Find Next" and "Find Previous" were removed from the dropdown because they don't make sense on their own, they are only used in the context of the "Find" popup. The "Find Next" and "Find Previous" buttons do work on the popup, as to their keyboard shortcuts, so I will be closing this issue.

**Comment by satyasaibhushan** [comment]
Oh no @catarak ,
I was just using the menu to explain the nature of the issue( to show that I was using find next),
The bug still exists even if we use the shortcuts.

**Comment by catarak** [comment]
got it! i'll reopen.

**Comment by satyasaibhushan** [comment]
Hey @catarak, Do you have any ideas to tackle this ?

**Comment by catarak** [comment]
It will definitely involve changing the [`codemirror-search.js`](https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/codemirror-search.js) file, though I'm really not sure what the culprit is...

**Comment by satyasaibhushan** [comment]
Hey @catarak,
never thought the solution would be this simple,
I just changed the shortcuts calling from `findNext`  to  `findPersistantNext` and every thing is working as imagined.
