### ISSUE TITLE
Maximizing console window should get back to its previous height

### ISSUE THREAD

**Issue by Ajaya1000** [processing/p5.js-web-editor#1776]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Currently, if a user maximizes the console window, it maximizes to a fixed height no matter what the previous state was. But I think it will be more convenient to get back to its previous height. @catarak, if it's useful I would like to work on this.

**Comment by catarak** [comment]
Makes sense to me! You can go ahead and work on this.

**Comment by Ajaya1000** [comment]
@catarak  I have raised a pull request for this issue. Please review it and suggest to me if this the right way to do so.
