### ISSUE TITLE
Fix PropTypes linting errors

### ISSUE THREAD

**Issue by satyasaibhushan** [processing/p5.js-web-editor#1781]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 88.0.4324.150 (Official Build) (x86_64)
- Operating System: macOS Version 11.2.1
- Steps to reproduce this bug:

<img width="522" alt="Screenshot 2021-02-26 at 10 48 56 PM" src="https://user-images.githubusercontent.com/40578313/109332948-d33df000-7884-11eb-9167-106a214d5da1.png">

I know this issue is addressed recently in #1514 but the problem exists and is from a single file `IDEView.jsx`
It is a very small fix and I'd like to work on it

**Comment by catarak** [comment]
@satyasaibhushan go ahead and work on this!

**Comment by satyasaibhushan** [comment]
Hey @catarak ,
fixing [this](https://github.com/processing/p5.js-web-editor/blob/be98ad0183137cfb989891ff1a6ad2e44a6b357d/client/modules/IDE/pages/IDEView.jsx#L508) line to `PropTypes.arrayOf(PropTypes.shape())` is  sufficient. But, the either of `editorAccessibility` or `lintMessages` is not used in the code. Do you want me to adjust the line or delete the whole `editorAccessibility` from this file

**Comment by catarak** [comment]
@satyasaibhushan you're right! The component that uses these props, `<EditorAccessibility>`, got moved into `<Editor>`, so these PropTypes can be removed.
