### ISSUE TITLE
German translation of the web-editor 

### ISSUE THREAD

**Issue by tlsaeger** [processing/p5.js-web-editor#1783]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Hi there, 
I could contribute a german translation of the p5-web UI, if you like? 
I was not sure if this is maybe already in the making, so thats why I'm not starting right away. 
Cheers
Tom

**Comment by catarak** [comment]
Hi @tlsaeger! There isn't a German translation and it would be great to have one. Take a look at the [translation documentation](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/translations.md) to get started!

**Comment by tlsaeger** [comment]
Hi @catarak thank you! Unfortunately I cannot get the dropdown to show. I've followed the installation guide as well as the translation documentation. I added `TRANSLATIONS_ENABLED=true` to `.env` but it still does not show up. Everything else is running perfectly. 
Thanks for your help!

**Comment by catarak** [comment]
@tlsaeger that's super strange! Can you open the browser console and see if you notice anything? If the app is working okay, one thing is that it could be a typo in `.env`.

**Comment by tlsaeger** [comment]
@catarak Ran the program to check if something is in the console. Did not change anything, now it works. Thanks for your help!

**Comment by catarak** [comment]
@tlsaeger glad you figured it out! my guess is that you had added the variable to `.env` but you hadn't restarted the server, as of right now the server doesn't get automatically restarted for .env changes (and maybe it should!)

**Comment by tlsaeger** [comment]
@catarak I sent a PR. Thanks again for your support.

**Comment by binomial0** [comment]
I looked over the translation in the PR (@tlsaeger asked for this) and wrote some suggestions. I'll link them here; I hope the format is ok and that this is useful. https://gist.github.com/binomial0/29b78bdaf81ff4399c36edced2ea30ad

**Comment by tlsaeger** [comment]
To add a little context I asked if someone would help me with proof reading here: [Twitter](https://twitter.com/t00may/status/1397104553347190784) and in the [processing](https://discourse.processing.org/t/proof-reading-german-translation-p5-web-editor/30271/2) forum. 
@binomial0 was so kind to offer first suggestions which i will add in the coming days.

**Comment by tlsaeger** [comment]
I incorporated the changes suggested by @binomial0 thanks again for your support. @catarak from my side the PR is ready to be merged.

**Comment by catarak** [comment]
@tlsaeger great, thank you!
