### ISSUE TITLE
Intelligent Code Completion feature

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js-web-editor#1792]
An intelligent code completion or intelliSense feature would benefit student learning success and retention. Although we have the link to documentation, I feel being able to stay in editor to view method parameter documentation would improve the learning workflow and the ability to view object property/method list would improve and reinforce learning concepts.

**Comment by catarak** [comment]
Thanks for the suggestion, I'm very into this idea! This has already been captured in #99.
