### ISSUE TITLE
Extra dot(.) in file names aren't displayed

### ISSUE THREAD

**Issue by jeeyoonhyun** [processing/p5.js-web-editor#1794]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Safari Version 14.0.3, Chrome 88.0.4324.192
- Operating System:  MacOSX
- Steps to reproduce this bug: When you make a new file / rename a file with an extra dot, (e.g. `p5.speech.js`), it automatically shows up in the file list without the extra dot (e.g. `p5speech.js`).

<img width="159" alt="Screen Shot 2021-03-10 at 2 30 56 PM" src="https://user-images.githubusercontent.com/26271473/110693189-297c2e80-81b5-11eb-9d40-767cada31bdd.png">
<img width="159" alt="Screen Shot 2021-03-10 at 2 30 51 PM" src="https://user-images.githubusercontent.com/26271473/110693183-2719d480-81b5-11eb-901f-b61731a8ff5e.png">

**Comment by catarak** [comment]
Thanks for reporting! Turns out this was very simple to fix and i'm working on a PR now 🎉
