### ISSUE TITLE
When will 1.3.0 be standard in editor?

### ISSUE THREAD

**Issue by maartenwijntjes** [processing/p5.js-web-editor#1799]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Found a bug in saveTable() which is luckily resolved in 1.3.0 (https://github.com/processing/p5.js/issues/5080), so was wondering when 1.3.0 will be standard included instead of the now 1.2.0 version.

**Comment by catarak** [comment]
Thanks for opening this issue! It's quick to fix and I'll make a PR for it today. It will be included in the editor in the next release, which I am trying to do more frequently, like once every few weeks or so.

In the meantime, when creating a new sketch, you can edit the sketch's `index.html` file to change the p5.js version to 1.3.0.
