### ISSUE TITLE
Prompt for user to name sketch at "new"

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#18]
Or some sort of randomized / formatted default sketch name?  I'd like to avoid the situation where everyone has a zillion "default sketch name" projects:

<img width="1269" alt="screen shot 2016-07-21 at 2 29 46 pm" src="https://cloud.githubusercontent.com/assets/191758/17034232/ba4df940-4f4f-11e6-9379-5fe0150856c4.png">

**Comment by catarak** [comment]
Just revisiting this and thinking about how to implement this...

Do we still think the user flow is best to force them to name a project when clicking "New"? What about when a user opens the editor for the first time (or the first time in a session)? Do we just need better default names, as #101 suggests?

**Comment by shiffman** [comment]
I prefer the "forced naming" requirement but I know @REAS (and likely others) prefer a generated name.    My issue is that unlike with a desktop application where an entire new window opens it's a bit hard to see what is going on if just the name subtly changes to something automatic.   (Although, unlike with "duplicate", I guess if the code disappears and you see a new blank sketch it's pretty obvious what's happening.)

A third possibility is the "forced naming" with a default name pre-filled in so just a simple "ok" or something can be clicked.   I guess I'm looking for signals to the user as to what is happening and/or a way for "new" to be cancelled if it's clicked accidentally?  

I'm of course amenable to trying anything, I am likely being overly cautious here!

**Comment by REAS** [comment]
Dan, your "third way" seems like a good solution.

**Comment by catarak** [comment]
Regarding this issue, I think we've decided to just have better default names, i.e. #184.
