### ISSUE TITLE
new create collection pop-up opens every time I click back after creating a new collection

### ISSUE THREAD

**Issue by Ajaya1000** [processing/p5.js-web-editor#1804]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome - 88.0.4324.182 (Official Build) (64-bit)
- Operating System: Linux Ubuntu 20.04.2.0 LTS (Focal Fossa)
- Steps to reproduce this bug:
                         -  First Go to `collection` 
                         -  Click `create collection` 
                         - create a new collection
                         -  click `back` from the browser navigation bar without doing anything.

- Expected behavior: Simply get the user back to the collection window
- Current behavior: Every time it opens up another create collection pop-up which is normally an undesired behavior

I would like to work on this issue if it makes sense.

**Comment by Ajaya1000** [comment]
@catarak I have worked on this issue. I'll raise a PR if this issue is unintentional from the beginning. In my new branch after creating a new collection if a user clicks `back` button the browser will get the user back to the collection tab without poping up a new create collection overlay.

**Comment by catarak** [comment]
Thanks for opening this issue! I think this makes sense, though I don't agree with your suggestion about how to fix this. Instead, I think that when the user clicks on "Create Collection", the popup should appear but the URL should not change.

**Comment by Ajaya1000** [comment]
Yes, this makes more sense. Thanks for the suggestion.

**Comment by Ajaya1000** [comment]
@catarak I have raised a PR. Please review if this the way you suggested.
