### ISSUE TITLE
Make the unsaved dot particular to file/ folder changed

### ISSUE THREAD

**Issue by satyasaibhushan** [processing/p5.js-web-editor#1805]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Currently, if we change any file/folder the unsaved dot on top of the file is visible in the editor, next to the file name. Also, the dot is being transferred to every other file even it is not edited
Here's a video to explain:

https://user-images.githubusercontent.com/40578313/111070338-569f4880-84f7-11eb-8fd2-ce2d90a3a6a3.mov

#### New feature details:
I am thinking that it would be nicer if we constrain the dot to the file edited and also the dot to be visible in the files sidebar
Here's a video after change:

https://user-images.githubusercontent.com/40578313/111070542-391eae80-84f8-11eb-96e7-4bee326c4229.mov

**Comment by satyasaibhushan** [comment]
@catarak ,
I've already completed writing the code for this one
If you think this is useful I'll issue a PR

**Comment by catarak** [comment]
Thanks for opening this issue! Rather than making the saved/unsaved files more granular, I think the design should denote simply if the sketch is saved or unsaved.

**Comment by satyasaibhushan** [comment]
Yeah, I agree on retaining the dot on every file when something is changed.
But, don't you think showing which file is changed make sense ?
###### I created this issue as I am used to this feature in VS code
