### ISSUE TITLE
NPM run lint error with pull request

### ISSUE THREAD

**Issue by felipesanchezz** [processing/p5.js-web-editor#1811]
#### Nature of issue?

- Existing feature enhancement

I have recently made a pull request, in which I completely translated the web editor. I followed every step, but I got this error:
![image](https://user-images.githubusercontent.com/75498026/111186725-0de89d80-8592-11eb-942f-3f413ed6c71e.png)

Does anyone know what I should do to fix it? I believe that a Portuguese translation is very important, as there is a rly big commuity, specially in Brazil.

**Comment by Ajaya1000** [comment]
@byfelipesanchez can you share the link to the pull request?

**Comment by Ajaya1000** [comment]
@byfelipesanchez run `npm run lint-fix` locally or follow check i.e replace `e` with `(e)`.

**Comment by felipesanchezz** [comment]
> 
> 
> @byfelipesanchez can you share the link to the pull request?

https://github.com/processing/p5.js-web-editor/pull/1810

> 
> 
> @byfelipesanchez run `npm run lint-fix` locally or follow check i.e replace `e` with `(e)`.

In which file would that be?

**Comment by satyasaibhushan** [comment]
It is given clearly in the error line-9 
File:`client/components/Nav.jsx`
and the line in `Nav.jsx` is `645`, position`26`

**Comment by felipesanchezz** [comment]
> 
> 
> It is given clearly in the error line-9
> File:`client/components/Nav.jsx`
> and the line in `Nav.jsx` is `645`, position`26`

Thanks mate, I just wasn't seeing it, lol. Just fixed it, let's see if it passes the running test!

**Comment by felipesanchezz** [comment]
> 
> 
> > It is given clearly in the error line-9
> > File:`client/components/Nav.jsx`
> > and the line in `Nav.jsx` is `645`, position`26`
> 
> Thanks mate, I just wasn't seeing it, lol. Just fixed it, let's see if it passes the running test!

It worked! 
![image](https://user-images.githubusercontent.com/75498026/111304720-d121b280-8634-11eb-8dee-1589ce7c65fd.png)
Thanks guys!
