### ISSUE TITLE
Direct Integration with GitHub

### ISSUE THREAD

**Issue by felipesanchezz** [processing/p5.js-web-editor#1812]
There should be a way of committing and pushing your files directly from the editor, to GitHub. You would be able to either work with the a cloned repo, or login to your account, and from there access your repositories and stuff. To do so:
- [ ] Integrate "GitHub' area to the layout of the page (HTML and CSS)
- [ ] Work with the GitHub API to actually make the commits and stuff work

The area could be located somewhere over here:

![image](https://user-images.githubusercontent.com/75498026/111053943-04065380-8447-11eb-8f9d-195f7c44cf03.png)

**Comment by Ajaya1000** [comment]
@catarak @byfelipesanchez I went through some of the online IDEs. The most simple and useful one, which is being used by stackblitz, is to have a `commit` button, `fork` button & `branches` window above the file explorer window which also consists of a `pull/refresh` button. But stackblitz being an IDE almost support all kind of folder structure so the cloning of a repo direct to the IDE. But for our editor, we can have a button to add the entry point of the project. This will avoid any kind of unnecessary errors.

**Comment by felipesanchezz** [comment]
> 
> 
> @catarak @byfelipesanchez I went through some of the online IDEs. The most simple and useful one, which is being used by stackblitz, is to have a `commit` button, `fork` button & `branches` window above the file explorer window which also consists of a `pull/refresh` button. But stackblitz being an IDE almost support all kind of folder structure so the cloning of a repo direct to the IDE. But for our editor, we can have a button to add the entry point of the project. This will avoid any kind of unnecessary errors.

Exactly. I mean, a commit button might be possible right? But even if not, a simple indicator about which branch you are in or something like that is already rly good.

**Comment by catarak** [comment]
Thanks for opening this issue! This is actually captured as #753 so I'm going to close this issue as a duplicate. But I agree this would be very useful!!
