### ISSUE TITLE
new sketch option doesn't work from sketch tab

### ISSUE THREAD

**Issue by Ajaya1000** [processing/p5.js-web-editor#1813]
#### Nature of issue?

- Bug

#### Bug details:
If a user clicks `new sketch` from the `sketch tab`, the website simply gets the user back to the editor window without creating a new sketch, just acts as a back button. In my opinion, it should initialize a new sketch instead of staying in the opened sketch. 

To implement the feature we may face some challenges like what if the user hasn't saved his/her previous changes. We may encounter by adding a pop-up a window having two buttons to save the changes there and a link to get back to the editor.
I would love to have a discussion on this.

**Comment by two-ticks** [comment]
Can you share more details or screenshots? I tried the steps in editor but it is creates a new sketch instead of behavior you observed. 

![OIEHQcSb9e](https://user-images.githubusercontent.com/68433541/111737953-84dda900-88a6-11eb-9146-714652f819db.gif)

**Comment by Ajaya1000** [comment]
@two-ticks use the `new sketch` option from the `sketches` tab.
![Screenshot from 2021-03-19 15-10-42](https://user-images.githubusercontent.com/43005088/111761002-620ebd00-88c5-11eb-8a1a-d25b7b25d8a5.png)

Use the `new sketch` button from this window.

**Comment by satyasaibhushan** [comment]
> #### Nature of issue?
> * Existing feature enhancement
> 
> #### Feature enhancement details:
> If a user clicks `new sketch` from the `sketch tab`, the website simply gets the user back to the editor window without creating a new sketch, just acts as a back button. In my opinion, it should initialize a new sketch instead of staying in the opened sketch.
> 
> To implement the feature we may face some challenges like what if the user hasn't saved his/her previous changes. We may encounter by adding a pop-up a window having two buttons to save the changes there and a link to get back to the editor.
> I would love to have a discussion on this.

**Comment by satyasaibhushan** [comment]
> To implement the feature we may face some challenges like what if the user hasn't saved his/her previous changes. We may encounter by adding a pop-up a window having two buttons to save the changes there and a link to get back to the editor.

Yeah @Ajaya1000 , It seems to be a bug. But, I don't think it would be a problem that user hasn't saved the progress because they will already be warned while opening the `sketch-list`.

I think the problem can be solved by correcting either of these cases
1. while opening the `sketch-list` from the sketch tab, 
where the user only being forwarded to `/username/sketches`,but not resetting the editor (i.e, state is not being changed by calling `RESET_PROJECT`)

2. when clicked on the `New sketch` button, where the user is only being forwarded to `/` path, but not resetting the editor

**Comment by Ajaya1000** [comment]
@satyasaibhushan  yes we can mock the existed behavior just like from the file menu. And I'm also updating the comment to the bug.

**Comment by catarak** [comment]
Thanks for reporting! I'm able to reproduce this, when the sketch that had been opened was an unsaved, new sketch.

**Comment by gugray** [comment]
Is there anything I can do to help move this pull request along?
It has a big red X but that's not because the checks failed. The check failed to execute:  failed to receive status: rpc error: code = Unavailable desc = transpor
