### ISSUE TITLE
My programme keeps crashing; I've tried running it on multiple computers, and no errors are displayed, yet my programme keeps freezing. I have found the part which is problematic: function mousePressed(){ for(let q = windowHeight-20; q > windowHeight/2; q = q-3){   for(let w = windowHeight; w > windowHeight/2; w = w-3){     for(let e = windowWidth-20; e > windowWidth/2; e = e-3){       for(let r = windowWidth; r > windowWidth/2; r = r-3){       stroke(225,225,0);       line(q,e,w,r);       }   } } } }. In this programme, when you click your mouse, I want a yellow streak (like a bullet) fire from the centre of the screen to the middle of the screen. Whenever I click my mouse however, the programme crashes.

### ISSUE THREAD

**Issue by LucasWoon** [processing/p5.js-web-editor#1818]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by Ajaya1000** [comment]
Hey @LucasWoon can you please a short title and describe the issue in the comment. It'll be much easier to read. And please follow the template i.e mention your OS and web browser.

**Comment by catarak** [comment]
Hi @LucasWoon! I believe the reason the code is freezing is due to it being very computationally expensive—I see that there are four nested for loops. There is, however, code that should catch this so that the browser window doesn't freeze, and this bug is captured in #698.

**Comment by LucasWoon** [comment]
> Hi @LucasWoon! I believe the reason the code is freezing is due to it being very computationally expensive—I see that there are four nested for loops. There is, however, code that should catch this so that the browser window doesn't freeze, and this bug is captured in #698.

Thank you so much @catarak :)))

**Comment by LucasWoon** [comment]
> Hey @LucasWoon can you please a short title and describe the issue in the comment. It'll be much easier to read. And please follow the template i.e mention your OS and web browser.

Very sorry @Ajaya1000 ! I'm new to GitHub, and didn't know the format. I'll be sure to use it next time, thanks for the help!
