### ISSUE TITLE
trouble with password reset

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js-web-editor#182]
I haven't been able to change my password for either of my two accounts (usernames: kjhollen & kjhollentoo). I tried earlier this morning but the emails haven't arrived (to ucla.edu and gmail.com addresses). Last week, the emails showed up much later in the day and the links were expired when I clicked on them.

**Comment by catarak** [comment]
okay, good to know! I'm not sure why there's such a big delay as to when emails are getting sent, I'll dig into the Mailgun configuration and see what turns up.

**Comment by kjhollen** [comment]
thanks, Cassie!

**Comment by catarak** [comment]
Just made and deployed a small change that _hopefully_ will make a difference, can you try again? The emails are showing up to my email almost immediately, but I think unfortunately it is dependent on your mail provider as well.

**Comment by catarak** [comment]
I took a look at the Mailgun logs, and it seems like for certain mail providers (Gmail) it's working fine, but for other mail providers (UCLA), the emails are bouncing for some reason. I think some of the DNS/Mailgun settings just need to be fiddled around with until this figures itself out.

**Comment by kjhollen** [comment]
Rad, thanks! Yes, as you've determined from the logs, I did try again and I was able to reset my password on the account affiliated with the gmail address. The email to the UCLA account never showed.

**Comment by catarak** [comment]
Just made some changes to the mail configuration, @kjhollen would you mind testing this with your UCLA email?

**Comment by kjhollen** [comment]
@catarak yes! this is now working great with my UCLA email :)
