### ISSUE TITLE
Add tests for filename and extension validation

### ISSUE THREAD

**Issue by vulongphan** [processing/p5.js-web-editor#1821]
I see that there are some unfinished tests in [Project.test.js](https://github.com/processing/p5.js-web-editor/blob/develop/server/domain-objects/__test__/Project.test.js).

![Screen Shot 2021-03-22 at 5 22 02 PM](https://user-images.githubusercontent.com/46087559/112002068-f6cd2100-8b38-11eb-8bbd-6dc5d472460c.png)

@catarak I would like to finish these tests, please let me know!

**Comment by raclim** [comment]
I'm going to close this for now, but please feel free to revisit this or create a new issue in the future, thanks!
