### ISSUE TITLE
I wanted to update website in Hindi language and also wanted to update the design of the website 

### ISSUE THREAD

**Issue by akshaykumar23399** [processing/p5.js-web-editor#1829]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment]
@akshaykumar23399 I believe you're in the wrong repository, I suggest going to the [p5.js website repo](https://github.com/processing/p5.js-website)! I think some work has been done to translate the website to Hindi, see https://github.com/processing/p5.js-website/pull/431, https://github.com/processing/p5.js-website/pull/630
