### ISSUE TITLE
What should open behavior be not logged in?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#183]
(we're having an ICM bug party!)

What should the editor show you when you are not logged in and you click open?  Examples?  Reminder to login?

**Comment by catarak** [comment]
🎉 🎉 🎉 

I _think_ we agreed that `Open` should be changed to `Examples`, see #149.
Also, when a user clicks save, they will be prompted to login/register, and the sketch that had been working on will be saved once they login to their account. Possibly discussed in #146/#52.

**Comment by shiffman** [comment]
Great! Looking at the issues you linked to see I see this is well covered.  Closing!
