### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by LucasWoon** [processing/p5.js-web-editor#1831]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by LucasWoon** [comment]
Hi there, I've been making multiple codes now that import ml5.js into p5.js. I often get this line of feedback everytime I press play: 
Uncaught TypeError: Cannot read property 'split' of undefined (: line 48)
Some of my codes do not even have 48 lines, and my code does not have the word 'split' in it, which leaves me feeling very confused. I make sure to type my code properly with curly brackets and semi colons, but it still appears. Sometimes, I recopy my code to a new document and the error does not appear.
As of yet this error does not seem to be affecting the programme at all, but I am still quite confused
Thank you!
<img width="675" alt="Screenshot 2021-03-31 at 3 45 04 PM" src="https://user-images.githubusercontent.com/76391312/113109019-2adecb00-9238-11eb-846d-952b13e1bdfd.png">

**Comment by catarak** [comment]
Hi @LucasWoon! Thanks for reporting. Would you mind opening up the browser developer tools and and pasting/taking a picture of what you see there?

**Comment by kjhollen** [comment]
Thanks for reporting @LucasWoon. Since there hasn't been any activity on this post, I'm going to close it. If you can provide more details, please re-open!
