### ISSUE TITLE
Creategraphics bug

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#1833]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Hi there! I'm getting this error when trying to call any function on a graphics object. 

`Uncaught TypeError: Cannot read property 'grid' of undefined`

I think this is related to https://github.com/processing/p5.js/issues/5000 

Here's an example sketch showing the issue.

https://editor.p5js.org/aferriss/sketches/63Hly1qCD

I'm wondering if we can update the editor to use a newer p5 release where this issue has been resolved. I believe it was fixed here https://github.com/processing/p5.js/pull/5003

- Web browser and version: Chrome
- Operating System: Mac OSX
- Steps to reproduce this bug: Create a graphics object with createGraphics and call any of it's member functions.

**Comment by catarak** [comment]
Thanks for reporting! Sorry for the delay in getting back to you—I'll update the default to v1.3.1 and do a web editor release.

**Comment by aferriss** [comment]
Thanks @catarak !
