### ISSUE TITLE
how to rename the file 

### ISSUE THREAD

**Issue by Devanshsoni19** [processing/p5.js-web-editor#1838]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by two-ticks** [comment]
If it's a general question please post it on [Processing Discourse](https://discourse.processing.org/). If it's a bug you can follow the  template and give some more details about your issue.

**Comment by ProfLazyTh** [comment]
On the file name, originally sketch.js, there is an arrow to the left of it. Click that arrow and it opens the list of files. Right click sketch.js on the left side and click rename.

**Comment by kjhollen** [comment]
Closing this issue because the question has been answered. In the future, please use the [Processing Discourse ](https://discourse.processing.org/) for questions about how to use the editor. Thanks!
