### ISSUE TITLE
error al escribir

### ISSUE THREAD

**Issue by zaira0108** [processing/p5.js-web-editor#1839]
el programa no me permite modificar o escribir ya que en cuanto le doy clic para poder escribir como que se traba y no puedo modificar el programa

**Comment by Ajaya1000** [comment]
hey @zaira0108 can you please elaborate on the issue? And is this a problem with the online editor?

**Comment by zaira0108** [comment]
Al momento de querer escribir el código no puedo modificarlo no me deja escribir y si llego  a escribir solo se empieza a mover y escribo en cualquier parte del código por lo que tengo que escribir en un bloc de notas y pegarlo para que pueda modificar el código es en linea por whitehat Jr

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Ajaya ***@***.***>
Enviado: lunes, 12 de abril de 2021 02:33 a. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [processing/p5.js-web-editor] error al escribir (#1839)


hey @zaira0108<https://github.com/zaira0108> can you please elaborate on the issue? And is this a problem with the online editor?

**Comment by kjhollen** [comment]
Hi @zaira0108, can you post a link to a specific sketch in your account that you can't edit, so that we can look into this issue? Thanks!

**Comment by raclim** [comment]
Hi @zaira0108! Just wanted to check-in and note that due to inactivity I'll be closing this issue for now. Please feel free to reopen this issue or create a new one if you'd still like converse about it, thanks!
