### ISSUE TITLE
Text box functionality broken in 1.2.0

### ISSUE THREAD

**Issue by rpapson** [processing/p5.js-web-editor#1846]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

 On Chrome
MacOSX
- Steps to reproduce this bug:

Using release 1.2.0 - creating text box using "text(str,x,y,width,height)" in this version breaks words in the middle to fit box.

Moved back to 1.1.9 and the "text(str,x,y,width,height)" and it works perfectly breaking lines only at whole word boundaries.

**Comment by catarak** [comment]
Thanks for reporting! I believe this has been fixed in the 1.4.0 release of p5.js, see https://github.com/processing/p5.js/issues/5081.
