### ISSUE TITLE
Editor Warnings/Errors on working code

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js-web-editor#1847]
Getting warnings/errors in editor on things like template literals and static methods.

Template Literal warning (Yellow): "Expected an assignment or function call and instead saw an expression"
Static Methods warning (Red): "Class properties must be methods. Expected '(' but instead saw '='"

Assuming this is related to #1540. 

Pointing this out bc it confuses my students when they see the warning/errors but the code still works.

**Comment by Spooghetti420** [comment]
Using a static property in a class raises the red squiggle as well, even though it works like you said. I wish I understood how the highlighting works to create a pull request, but I would greatly appreciate any update to the editor! Thank you devs :)

**Comment by raclim** [comment]
Thanks for raising this issue, I'm sorry we couldn't get to this for a while! Since it does seem related to https://github.com/processing/p5.js-web-editor/issues/1540, I'm going to close this for now to consolidate issues, but please feel free to reopen this or create a new one :)
