### ISSUE TITLE
Incorrect filename displayed in side panel

### ISSUE THREAD

**Issue by jesse-harding** [processing/p5.js-web-editor#1848]
#### incorrect filename displayed in side panel

- Found a bug

#### Details about the bug: Uploaded files are shown with whitespace and periods removed. There may be other characters being removed from the string, but those are all I have seen in practice. This has caused difficulties using the editor as a teaching tool for novice coders.

- Web browser and version: Chrome Version 89.0.4389.114 (Official Build) (x86_64)
- Operating System: MacOS v11.2.3
- Steps to reproduce this bug:
1. upload a file that includes a space, multiple period characters, or other whitespace (I assume) in the editor.
2. In the side panel showing file structure, the filename will not include that whitespace or period character (example: p5.serialport.js will show as p5serialport.js)

**Comment by shubhamkapoor01** [comment]
Actually i think this might be intentional so that a naming convention is followed, tho i'm not sure about this, if it's not intentional I would like to work on this issue!

**Comment by catarak** [comment]
Thanks for opening this issue, somehow I missed it? Anyway, it seems to be fixed now so I'm going to close it.
