### ISSUE TITLE
user flow for working in another user's sketch 

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#185]
Here is a scenario I have encountered several times recently.  This is likely part of #146, but since it's a bit specific I thought I would open a new issue.

1) I open up a sketch that is not one of mine and start making changes.
2) I hit CMD-S and am not given any feedback that it's not actually saving.
3) I realize it's not one of my sketches and go to click duplicate and then get the warning: "Are you sure you want to leave this page?"  

I'm not sure what the behavior should be, some general thoughts:

1) Any way to more strongly visually indicate if you are in your own sketch or not?
2) Feedback if you hit cmd-s? "Do you want to duplicate to save?"
3) This warning is unnecessary b/c you do not lose the work, rather your changes make it into the duplicated project.

**Comment by lmccart** [comment]
@lee2sman can you post notes about the issue you noticed in class last week? I believe it is related to this thread. thanks!

**Comment by lee2sman** [comment]
Yes! Had the exact same issue. Some additional feedback. If you click on the title, it will pop up the notification that you autosaved, but then when you login, it won't be saved.

**Comment by catarak** [comment]
@lee2sman regarding your additional feedback, is this if you are editing a new sketch or another user's sketch?

**Comment by lee2sman** [comment]
@catarak this is if you start with another user's sketch and make changes in it.

**Comment by catarak** [comment]
thanks! I think there's a couple things going on here:
1. If a user is looking at another user's sketch, the user shouldn't be able to edit the title (and the pen icon should be gone), and therefore the saving/autosave notification shouldn't appear. I'll make a separate ticket for this.
2. If you are not logged in and you edit another user's sketch, and then login in, it is expected that those changes would remain after logging in, and they do not. It doesn't make sense that those changes would be saved unless the user makes their own copy of the other user's sketch.

**Comment by lee2sman** [comment]
that sounds right to me
