### ISSUE TITLE
I cloned repository and after installing packages I am facing " error  Delete `␍`  prettier/prettier" issue 

### ISSUE THREAD

**Issue by almaskhanwazir** [processing/p5.js-web-editor#1850]
" error  Delete `␍`  prettier/prettier" issue 

- Found a bug

Details about the bug: I just cloned repository, installed all packages, created .env file and when i run application its giving "error  Delete `␍`  prettier/prettier" error
![Annotation 2021-05-01 013351](https://user-images.githubusercontent.com/46604137/116751351-56162f00-aa1d-11eb-8d04-f9e002d3caf3.png)

- Web browser and version:  Chrome version 90.0.4430.93
- Operating System:   Windows 10 64 bit
- Steps to reproduce this bug:
install project by [installation guide](https://github.com/processing/p5.js-web-editor/blob/develop/developer_docs/installation.md)
start project .

**Comment by almaskhanwazir** [comment]
if we add "endOfLine":"auto" to .prettierrc file then issue fixed

**Comment by catarak** [comment]
Thanks for reporting! I think this has to do with the Windows vs Mac/Linux line endings. Want to open a PR with this fix?

**Comment by almaskhanwazir** [comment]
Yeah I will open pull request for this, I already have fixed it locally, thanks for reply

**Comment by almaskhanwazir** [comment]
Please review my PR thanks
https://github.com/processing/p5.js-web-editor/pull/1854
