### ISSUE TITLE
Should be able to drag and drop local files to the files section

### ISSUE THREAD

**Issue by almaskhanwazir** [processing/p5.js-web-editor#1851]
New Feature to drag and drop file into files section

- New feature request

 **Details about the feature:** 
I am not able to drag and drop file from local system into the file section. We should be able to drag files with extensions (js, json, xml, html , css) from local system and drop into files section .

Web browser and version: Chrome version 90.0.4430.93
Operating System: Windows 10 64 bit

**Comment by almaskhanwazir** [comment]
Well sorry it may existed

**Comment by kjhollen** [comment]
Hi @almaskhanwazir, thanks for this great suggestion! This feature is not yet implemented. I think this may be the same feature request as issue #1417, so I'm going to close this so we can keep the discussion in one place. Please comment there if you have any additional thoughts related to this feature.
