### ISSUE TITLE
deleting extra branches

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js-web-editor#1856]
as far as i know, these branches can be deleted with no conflicts:

* bug/extra-dot
* bug/console-production
* revert-667-feature-2/interactive-console
* revert-1624-revert-667-feature-2/interactive-console
* bug/revert-interactive-console
* bug/mongo-sessions
* bug/webpack-docker-compose
* bug-interactive-console

link here :)
https://github.com/processing/p5.js-web-editor/branches

**Comment by catarak** [comment]
Thanks! I just closed a bunch of branches 🎉
