### ISSUE TITLE
In Find, "only whole words" also finds postfixes

### ISSUE THREAD

**Issue by gugray** [processing/p5.js-web-editor#1857]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 88.0.1 (64-bit)
- Operating System: Windows 10

#### Steps:
- Have a sketch open for editing. The sketch should have strings that appear as whole tokens, and as part of other tokens, e.g.: abc, ab, a, ba, bac, Santa
- Press Ctrl+F to bring up the Find window. Make sure all the options are unchecked: not a regex, not case sensitive, not "only whole words".
- Enter a single lower-case 'a' and press Enter to search.
**Result**: All occurences of "a" are highlighted, and pressing Enter or the "next" arrow cycles through them. Great.
- Check "only whole words", return to the text field, and press Enter to search again.
**Actual Result**: Highlighted are all occurrences where "a" is the last character of a token, including but not limited to where "a" is the whole word. Pressing Enter or the "next" arrow cycles through all of these.
**Expected Result**: only those occurrences are found where the input is the whole word, not where its the postfix of a token.

The example uses single-letter "a", but it works with multiple-letter search terms too. The issue doesn't seem to be affected by what you're searching for.

Attaching a screen grab of the issue.

https://user-images.githubusercontent.com/22029901/117532783-9d865780-afe9-11eb-87cc-29b0903905d1.mp4

**Comment by catarak** [comment]
Thanks for reporting! The Find/Replace code is located in the file [`codemirror-search.js`](https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/codemirror-search.js), which is an altered version the default find/replace build into CodeMirror (see [CodeMirror version](https://github.com/codemirror/CodeMirror/blob/master/addon/search/search.js)). That's the place to start to fix this issue!

**Comment by divyanx** [comment]
It seems that the bug is unresolved.
Can I work on this?
It will be my first issue.
