### ISSUE TITLE
unsavedChanges gets reset when switching files

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#186]
Steps to reproduce:
1. Open a new sketch
2. Edit one file, redux will set `unsavedChanges` to `true`
3. Click on another file to edit it, redux will set `unsavedChanges` to `false` even though the project has unsaved changes.

**Comment by yining1023** [comment]
Should unsavedChanges be an array? Each unsavedChange in the array will indicate if this file is changed or not. And there will be a 'unsavedChanges in total' to indicate if there is anything unsaved for the whole project.

**Comment by catarak** [comment]
Yes, I agree with your edit! A part of the Redux methodology is to hold the state as compactly as possible, which I think supports that we should just make it one boolean.
