### ISSUE TITLE
Web Editor thinks optional chaining is an error

### ISSUE THREAD

**Issue by Geodecillium** [processing/p5.js-web-editor#1861]
- Found a bug

- Web browser and version: Chrome 90.0.4430.93
- Operating System: Windows 10 19042.928
- Steps to reproduce this bug:
Using any object/array/function you can add ?. to check if it's nullish before continuing to avoid errors.
official documentation: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining
The code still runs fine, but the editor thinks it wrong.

**Comment by gugray** [comment]
This sounds related to #1540 and #1847

**Comment by catarak** [comment]
This is definitely the same underlying issue as #1540!
