### ISSUE TITLE
Suggestion: Color picker

### ISSUE THREAD

**Issue by everythingability** [processing/p5.js-web-editor#1867]
Hi,

I know this may seem like a minor feature, but when teaching p5js, it's a pain to have to "go elsewhere" to choose a color... It could go in the Help or Sketch menu.
A super simple compromise might be to have a link in the help menu to a resource elsewhere, but ...
It might also link out to a list of HTML color names.

Thank you for all your wonderful work

Tom

**Comment by catarak** [comment]
Thanks for the suggestion! This is actually already an open issue (#90), but I think is worth bringing up again. In my mind I thought this would be a difficult issue but I think there are actually out of the box solutions that would be possible to use, such as [`codemirror-colorpicker`](https://github.com/easylogic/codemirror-colorpicker). I also noticed recently that there's a [custom color picker](https://github.com/patriciogonzalezvivo/glslEditor/blob/gh-pages/src/js/ui/pickers/ColorPicker.js) patricio gonzalez-vivo made for [glslEditor](https://thebookofshaders.com/edit.php) that is worth looking at as well 😄 .

**Comment by ameybh** [comment]
Hey @catarak, I've created a PR for color picker. Do take a look and suggest if any changes. 
I might need help to update the color viewer when the color changes.

**Comment by everythingability** [comment]
Yay! Thanks!

**Comment by anshul2807** [comment]
Is this still an issue??

**Comment by ameybh** [comment]
> Is this still an issue??

Yes since PR #1907 is under review.

**Comment by anshul2807** [comment]
Can I start working on this Issue?

**Comment by ameybh** [comment]
Yes, please go ahead :)
I'm currently not working on this issue.

**Comment by Bhavyajain21** [comment]
Is anyone working on it?
If not, I would like to take up the work.

**Comment by ameybh** [comment]
Yes, please go ahead
