### ISSUE TITLE
TypeError: Class constructor MongoStore cannot be invoked without 'new'

### ISSUE THREAD

**Issue by suiato** [processing/p5.js-web-editor#1871]
#### Nature of issue?

Running `npm start`,  app crashed
> [nodemon] app crashed - waiting for file changes before starting...

because
> /home/suiato/git/p5.js-web-editor/server/server.js:78
> var MongoStore = (0, _connectMongo["default"])(_expressSession["default"]);
>  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^
> TypeError: Class constructor MongoStore cannot be invoked without 'new'
>     at Object.<anonymous> (/home/suiato/git/p5.js-web-editor/server/server.js:36:20)
>     at Module._compile (internal/modules/cjs/loader.js:1158:30)

#### Details about the bug: 
- os: Ubuntu server 20.04.2 LTS on Linode
- git: version 2.25.1
- node: version 12.6.1
- npm: version 7.13.0
- Steps to reproduce this bug: `npm start`

#### Code at server/server.js
<pre>
  1 import Express from 'express';
	:
  6 import session from 'express-session';
  7 import connectMongo from 'connect-mongo';
	:
 35 const app = new Express();
 36 const MongoStore = connectMongo(session);
 37
 38 app.get('/health', (req, res) => res.json({ success: true }));
	:
 73 app.use(
 74   session({
 75     resave: true,
 76     saveUninitialized: false,
 77     secret: process.env.SESSION_SECRET,
 78     proxy: true,
 79     name: 'sessionId',
 80     cookie: {
 81       httpOnly: true,
 82       secure: false
 83     },
 84     store: new MongoStore({
 85       mongooseConnection: mongoose.connection,
 86       autoReconnect: true
 87     })
 88   })
 89 );
 90
</pre>

**Comment by catarak** [comment]
Thanks for reporting! What version of `connect-mongo` is installed? I believe this is an issue with using a later version of this library (see [this thread](https://forum.freecodecamp.org/t/advanced-node-and-express-error/450979)).
