### ISSUE TITLE
Cannot upload or create .stl file into editor.p5js

### ISSUE THREAD

**Issue by sweco-sedahd** [processing/p5.js-web-editor#1874]
Hi everyone,

I thing i have found a similar problem to #1741 .

Function loadModel supports both .obj and .stl files but only .obj files are allowed to be uploaded and created.

Thanks
Daniel

**Comment by catarak** [comment]
Hi @sweco-sedahd! Thanks for reporting. Yes, the issue has the same fix as #1741.

**Comment by shubhamkapoor01** [comment]
Hi, i'm new to open source contributions, i'll give this a try!

**Comment by akshatnema** [comment]
Hey @catarak, I want to work on this issue. I have done the setup of this project on my local system.

**Comment by catarak** [comment]
> Hey @catarak, I want to work on this issue. I have done the setup of this project on my local system.

Yay! I would recommend looking at #1741 for reference on how to fix this issue, and then you can make a PR 😄

**Comment by akshatnema** [comment]
> > Hey @catarak, I want to work on this issue. I have done the setup of this project on my local system.
> 
> Yay! I would recommend looking at #1741 for reference on how to fix this issue, and then you can make a PR 😄

Thanks for the reference. Just a quick question, since .stl files are majorly worked on CAD software for designing, will they work p5 web editor as well, or do I have to make some built-in backend for working on these files?
