### ISSUE TITLE
Syntax Highlighting in Instance Mode

### ISSUE THREAD

**Issue by JetStarBlues** [processing/p5.js-web-editor#1882]
#### Nature of issue?

- New feature request

#### New feature details:

 p5.js keywords are currently not highlighted in instance mode ([live link][0]).

![imsh1](https://user-images.githubusercontent.com/4354703/120733258-0c998380-c4a4-11eb-8bd5-0e9d0f820184.png)

It would be awesome if they were. I noticed in the examples editor, **some** of the keywords are highlighted ([live link][1]).

![imsh2](https://user-images.githubusercontent.com/4354703/120733268-13c09180-c4a4-11eb-9af6-9bc08065f19e.png)

Global mode for comparison ([live link][2]):

![imsh3](https://user-images.githubusercontent.com/4354703/120733702-e3c5be00-c4a4-11eb-91a8-b6a26637f74d.png)

\---

Possible concerns:
- How will the editor know that `p` is an instance of `p5` and not a custom class that the user has defined which happens to have methods with similar names.

[0]: https://editor.p5js.org/acedean/sketches/EhbQAZonN
[1]: https://p5js.org/examples/instance-mode-instantiation.html
[2]: https://editor.p5js.org/acedean/sketches/dYkNDbOuX

**Comment by catarak** [comment]
Thanks for reporting! This would be great though I'm not quite sure how to fix it. I'm not an expert on how CodeMirror syntax highlighting works—basically there's a custom [`p5-javascript`](https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/p5-javascript.js) mode that pulls from a list of [p5.js keywords](https://github.com/processing/p5.js-web-editor/blob/develop/client/utils/p5-keywords.js). Maybe there's a way to highlight these keywords as class methods? Maybe using this [CodeMirror utility](https://github.com/erosman/CodeMirror-plus/tree/main/addon/mode) would help?

**Comment by JetStarBlues** [comment]
I think scope might also play a role.

I've noticed that anything that is not global, does not get highlighted. For example ([live link][0]):

![scopeSyntaxHighlighting](https://user-images.githubusercontent.com/4354703/122478785-40d27100-cf87-11eb-8833-c1320856b9e6.png)


[0]: https://editor.p5js.org/acedean/sketches/SyR8v2grw

**Comment by kunalkumar007** [comment]
**Does this issue is resolved?**
- I am new to open source contribution and would like to try this issue.
- @catarak @jetStarBlues can you please see for it.

**Comment by JetStarBlues** [comment]
Hey @kunalkumar007 
The issue is not resolved. Feel free to take it on!

**Comment by shubhamkapoor01** [comment]
Hey!
i'd like to give this issue a shot tho i'm not yet sure how to fix it.
here are a few observations while i start:
-> in light and dark mode the global variables are highlighted but local variables are not.
-> in high contrast mode both global and local variables are not highlighted.

**Comment by kunalkumar007** [comment]
Hy @shubhamkapoor01 Feel Free to take it on. I am busy with my sem end. So, won't be able to continue on it.

**Comment by calebfoss** [comment]
I gave this a try with PR #1996. The p5-javascript mode appears to style anything that follows a "." as a "property" (with exceptions for the async keyword), and once identified as a property, it ignores any matches with the p5-keywords. I made p5-keywords a priority instead, so if a token matches a p5-priority, it will styled as a p5Function or p5Variable regardless of whether it follows a ".".

Note that this PR does not address local scope variables/functions. For that, it looks like the change would be to the variable-2 class in the scss files for [light theme](https://github.com/processing/p5.js-web-editor/blob/develop/client/styles/components/_p5-light-codemirror-theme.scss), [dark theme](https://github.com/processing/p5.js-web-editor/blob/develop/client/styles/components/_p5-dark-codemirror-theme.scss), and [high contrast](https://github.com/processing/p5.js-web-editor/blob/develop/client/styles/components/_p5-contrast-codemirror-theme.scss). But it looks like those styles were chosen deliberately.
![image](https://user-images.githubusercontent.com/16294664/152248884-a7e932df-6964-486a-a8d1-d9d7381af744.png)
