### ISSUE TITLE
Apple ipad safari apple ipad 14.6.0 work not. 14.0 well good work why?.

### ISSUE THREAD

**Issue by Zwaan69** [processing/p5.js-web-editor#1883]
problem apple ipad 14.6.0 not work
Well 14.0

i will ipad p5.js edior open

#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment]
Thanks for reporting! I'm fairly certain this is related to #1878—there seems to be an issue with a certain version of Safari and `p5.sound.js`.

**Comment by catarak** [comment]
Just published a release to fix this ([v1.4.1](https://github.com/processing/p5.js-web-editor/releases/tag/v1.4.1)), closing!
