### ISSUE TITLE
GLSL Syntax Highlighting

### ISSUE THREAD

**Issue by JetStarBlues** [processing/p5.js-web-editor#1885]
#### Nature of issue?
- New feature request

#### Feature enhancement details:
There is currently no syntax highlighting for shader source code. Files in this category typically have the extensions:
- .glsl
- .vert
- .frag

Here is a [live example][0]. See `shader.vert` and `shader.frag`.

Here is a screenshot:
![glslSyntaxHighlighting](https://user-images.githubusercontent.com/4354703/121988555-c2dc5300-cd57-11eb-9d1a-5bd570f9abdd.png)

[0]: https://editor.p5js.org/acedean/sketches/35P6ahcvE

**Comment by catarak** [comment]
Thanks for reporting! There is technically *some* syntax highlighting for .`vert`/`.frag` files, but it is not very good. Going to look into how to make it better 😄

**Comment by JetStarBlues** [comment]
I see, thank you for taking a look!
