### ISSUE TITLE
text error

### ISSUE THREAD

**Issue by tedsmith2011** [processing/p5.js-web-editor#1889]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

text is not working on one sketch but is working on the other please fix this thanks,Ted

#### New feature details:

**Comment by tedsmith2011** [comment]
by the way, while freezes my hole screen but this is on any sketch

**Comment by catarak** [comment]
Hi @tedsmith2011, thanks for reporting! Would you mind posting a link to the sketches? It's hard for me to figure out what the issue is without more information.

**Comment by tedsmith2011** [comment]
This was an error in my code
