### ISSUE TITLE
Loading local JSON file in the full view

### ISSUE THREAD

**Issue by yining1023** [processing/p5.js-web-editor#189]
I have this test sketch: [http://alpha.editor.p5js.org/projects/Hk5W7ptel](http://alpha.editor.p5js.org/projects/Hk5W7ptel). It can load JSON file in the edit view. 

When I switch to the full view: [http://alpha.editor.p5js.org/full/Hk5W7ptel](http://alpha.editor.p5js.org/full/Hk5W7ptel ), I got 502 (Bad Gateway) error.
<img width="500" alt="screen shot 2016-11-04 at 1 22 01 pm" src="https://cloud.githubusercontent.com/assets/8662372/20015519/2a54bd9c-a292-11e6-8d36-021b2a09cf64.png">

**Comment by catarak** [comment]
Since the full/embed link is being rendered server side, I can't user blob urls to load json/txt/csv files. I think the solution to this is to make new api routes that return these files, something like:
`/api/sketches/<sketch_id>/<path_to_file>`
