### ISSUE TITLE
Sometimes shader files clone their content from other shader files

### ISSUE THREAD

**Issue by applejuiceyy** [processing/p5.js-web-editor#1890]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Firefox Developer (90.0b12 (64-bit))
- Operating System: Windows 10
- Steps to reproduce this bug:

(I don't really know how to describe this hence the weird title)
![bugthing](https://user-images.githubusercontent.com/30875598/123556804-4dc04300-d785-11eb-818b-701b080d73b1.gif)

**Comment by JetStarBlues** [comment]
This might be related to what I encountered #1887
