### ISSUE TITLE
p5.js editor on iPad not working any more

### ISSUE THREAD

**Issue by ghost** [processing/p5.js-web-editor#1891]
#### p5.js editor doesn't work on iPad any more

- Found a bug

#### When running the code in editor (on iPad) the preview only shows "Loading" and nothing else

- Web browser and version:

**Comment by catarak** [comment]
Thank you for reporting! I thought that I had fixed this issue via #1870, but there was an issue with the deployment. With [v1.4.2](https://github.com/processing/p5.js-web-editor/releases/tag/v1.4.2) this has now been resolved 😄
