### ISSUE TITLE
Random is not defined?

### ISSUE THREAD

**Issue by year29thousand** [processing/p5.js-web-editor#1897]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Version 89.0.2 (64 bit)
- Operating System:  
- Steps to reproduce this bug: I don't reallly know how to reproduce the bug, but after a while of using the WEB EDITOR, some random errors appear but it always says, ___ is not defined

Code snippet:
function setup() {
  createCanvas(600, 350);
  
}

//This pong game is 2 player
let AI;

let P1 = [0,0];
let P2 = [0,0]; //but it also can be single player
let BallCoords = [0,0];
let BallVelocityX = random(-5, 5);
let BallVelocityY = random(-5, 5);

let TwoPlayerActive = false;
let GameStage = 0; // Zero means that we're at the starting screen

function draw() {
  if(GameStage == 0) {
     
     Starting();
     
     }
  if(GameStage == 1) {
     
    if(TwoPlayerActive == false) {
      Play();
      
    }else if(TwoPlayerActive == true) {
               PlayTwoPlayer();
             
             }
      
     
     }
}

CONSOLE ERRORS:
ReferenceError: random is not defined
ReferenceError: can't access lexical declaration 'GameStage' before initialization

**Comment by JetStarBlues** [comment]
Hey

The solution can be found further down in the console log of your sketch:

```
Did you just try to use p5.js's random() function? If so, you may want to move it into your sketch's setup() function.

For more details, see: https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup 
```

The sketch is complaining about these lines in particular, where `random()` is used outside of a call from `setup()` or `draw()`. Please see the [linked article][0] for more information.
```js
let BallVelocityX = random(-5, 5);
let BallVelocityY = random(-5, 5);
```

[0]: https://github.com/processing/p5.js/wiki/p5.js-overview#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup

**Comment by catarak** [comment]
@JetStarBlues thank you for offering a suggestion for how to fix @year29thousand's issue!
