### ISSUE TITLE
Sandboxed iframes breaks saveCanvas() function

### ISSUE THREAD

**Issue by emilyweil** [processing/p5.js-web-editor#1899]
I'm seeing the same issue reported here:
https://github.com/processing/p5.js-web-editor/issues/1443#issue-627006482

**Comment by wildparadox** [comment]
Found this through #1443 as well. Despite that issue being closed, [save()](https://p5js.org/reference/#/p5/save) doesn't work in the web editor either for the same reason.

**Comment by catarak** [comment]
Thank you for reporting! I see that I removed `allow-downloads` from the list of [sandbox attributes](https://github.com/processing/p5.js-web-editor/blob/develop/client/modules/IDE/components/PreviewFrame.jsx#L25), but it can be added in again.

**Comment by emilyweil** [comment]
Thanks so much! I'm yearning to saveCanvas().

**Comment by catarak** [comment]
While you're waiting for this fix to be deployed, you can right click on a canvas to save it, though it is obviously not ideal :)

**Comment by emilyweil** [comment]
I'm saving a canvas repeatedly as I draw to it so when saveCanvas() becomes available, I'll be very happy – thanks again!

**Comment by catarak** [comment]
Just did a hotfix release so this should be deployed to production shortly 😄

**Comment by emilyweil** [comment]
That's really great – thank you!

**Comment by emilyweil** [comment]
SaveCanvas() is working beautifully. Thanks again!
