### ISSUE TITLE
Tidy Code produces Linter warning on multiline ternary operator

### ISSUE THREAD

**Issue by loic-brtd** [processing/p5.js-web-editor#1904]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome | 91.0.4472.77 (Official build) (64 bits)
- Operating System:  Manjaro Linux 21.0
- Steps to reproduce this bug:

When using the ternary operator with long expressions, the "Tidy Code" feature breaks lines like this :
```js
const result = "one long expression".includes("one")
  ? "another long expression"
  : "yet another long expression";
```

I like the way it is formatted, but the linter of the editor gives this warning : *"Misleading line break before '?'; readers may interpret this as an expression boundary."*. So the linter gives a warning that is not consistent with the code style of the formatter.

**Comment by catarak** [comment]
Thank you for reporting! I believe this is due to JSHint being outdated and it should be replaced by ESLint, see #1540.

**Comment by raclim** [comment]
Closing this for now since it's been noted in an earlier issue!
