### ISSUE TITLE
keyCode not working

### ISSUE THREAD

**Issue by tedsmith2011** [processing/p5.js-web-editor#1908]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

https://editor.p5js.org/TedS/sketches/9q84RVcd8

#### New feature details:

**Comment by catarak** [comment]
Hi @tedsmith2011! Thank you for reporting. There's actually an error in your sketch. The value of `col` is changed in `keyPressed, but you never call `background()` in `draw()`, so the background color of the canvas is never drawn again. You can fix this by putting in the line `background(col)` into your drawn loop.

**Comment by tedsmith2011** [comment]
Thank you for the help

**Comment by tedsmith2011** [comment]
It still does not work
