### ISSUE TITLE
Status bar for editor

### ISSUE THREAD

**Issue by ameybh** [processing/p5.js-web-editor#1909]
- New feature request

#### New feature details:
* Add status bar and display
  * Current cursor's line and column 
  * Scope of code where the cursor is present at.

**Comment by eltonsampaio12** [comment]
Me and my team would like to take a look at this issue.

**Comment by raclim** [comment]
I feel like there's already some visual indicators for the cursor's positioning within the editor, but can potentially see a benefit to having it indicated somewhere near the top as well. 

I think this request might need some more thought in terms of its usage and design, so I'm going to close this for now, but please feel free to reopen or create a new one pertaining to this in the future! :)
