### ISSUE TITLE
Allow WebUSB in sketch preview

### ISSUE THREAD

**Issue by pelikhan** [processing/p5.js-web-editor#1927]
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome/Edge 90+
- Operating System: Windows/Mac

#### Feature enhancement details:

The p5 web editor allows Web Serial in the preview window. However some devices, like the micro:bit use WebUSB instead. I was wondering if it would be possible to allow web-usb as well.

**Comment by pelikhan** [comment]
Similar fox to https://github.com/processing/p5.js-web-editor/pull/1924 

Add usb

**Comment by catarak** [comment]
Thanks for the suggestion! Is the fix as simple as adding `web-usb` to the allow list?

**Comment by pelikhan** [comment]
Adding ``usb`` should be enough (https://web.dev/usb/#feature-policy). 

You can see a demo of p5js using WebUSB from codesandbox.io at https://codesandbox.io/s/dnyd9?file=/sketch.js . It uses our p5.jacdac library (https://microsoft.github.io/jacdac-docs/clients/p5js/) ... and a micro:bit v2.

**Comment by pelikhan** [comment]
(i am also preparing a submission for this library, working on the image)

**Comment by pelikhan** [comment]
All working now! No drivers needed thanks to WebUSB...
![p5sliders](https://user-images.githubusercontent.com/4175913/136144392-04217a1e-42eb-4a7d-ae7b-b4183140b057.gif)
