### ISSUE TITLE
Loging Bug

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#1928]
Login bug in the code editor

- Found a bug
- details - 
Having intermittent trouble logging in, especially on computers that are not my laptop. Similar issue to #1153 with the red "no" symbol appearing when you hover over the login button. 
Curiously I've found that if I write the password before the username it seems to work. (Replicated this work around a couple of times on the PC). 

Both times it happened in chrome, once on a mac, once on a PC. 
Chrome 92.0.4515.159 
Windows OS 10 v.1903 
(don't have the mac info atm) 

I've never seen the problem on my laptop 
Chrome | 93.0.4577.63
macOS Version 10.14.6

Thanks 
Joe 

#### New feature details:

**Comment by calebfoss** [comment]
My students have been running into the same issue. It's happening when they use lab computers but not their personal computers. I haven't been able to reproduce it. They're using Chrome on Windows 10, but I asked one student to try Firefox and found that the same issue occurred.
Looks like this may possibly be the same issue as #1910.

**Comment by joemckay5** [comment]
Calebfoss, have you tried the "password before the username" trick? Let me know if that works.

**Comment by calebfoss** [comment]
@joemckay5 Unfortunately that trick is not consistently working.

I was able to reproduce the issue by typing in the incorrect password, pressing the "Log In" button OR pressing enter, correcting the password, and then attempting to press "Log In" or enter again.

Looks like this is the relevant error:

`POST https://editor.p5js.org/editor/login 401
(anonymous) @ xhr.js:177
e.exports @ xhr.js:13
e.exports @ dispatchRequest.js:50
Promise.then (async)
u.request @ Axios.js:61
r.forEach.u.<computed> @ Axios.js:87
(anonymous) @ bind.js:9
_D @ actions.js:20
(anonymous) @ actions.js:56
(anonymous) @ actions.js:55
(anonymous) @ index.js:8
onSubmit @ LoginForm.jsx:13
submit @ final-form.es.js:1357
handleSubmit @ react-final-form.es.js:264
m @ react-dom.production.min.js:15
w @ react-dom.production.min.js:15
(anonymous) @ react-dom.production.min.js:16
k @ react-dom.production.min.js:16
_ @ react-dom.production.min.js:17
A @ react-dom.production.min.js:17
O @ react-dom.production.min.js:17
xn @ react-dom.production.min.js:81
le @ react-dom.production.min.js:285
On @ react-dom.production.min.js:83
Pn @ react-dom.production.min.js:84
Fn @ react-dom.production.min.js:84
t.unstable_runWithPriority @ scheduler.production.min.js:18
Yi @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
Tn @ react-dom.production.min.js:82`

**Comment by calebfoss** [comment]
Here are the steps I gave to students as a temporary workaround before this issue is resolved:

1. Try refreshing the page and retyping your credentials
2. If that doesn't work, open the developer tools in your browser. In Chrome, the shortcut for this is control + shift + i
3. Click Console
4. In the console, type the following and then press enter:
document.querySelector(".Button__StyledButton-sc-6bwbx8-0").disabled = false;

**Comment by catarak** [comment]
Thanks for reporting, and apologies for the delay in responding to this! I will take some time today to dig into this and hopefully have a solution sometime this week.

**Comment by catarak** [comment]
I ended up fixing and deploying this today! Let me know if you're still having issues.

**Comment by calebfoss** [comment]
@catarak fabulous! Thank you so much!!!

**Comment by joemckay5** [comment]
Thanks, catarak!  
Joe
