### ISSUE TITLE
when running fullscreen mode the canvas is compressed to a thin squashed band

### ISSUE THREAD

**Issue by lee2sman** [processing/p5.js-web-editor#1938]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Tested on Chrome 94.0.4606.81 and Firefox 92
- Operating System: Ubuntu Linux and Windows 10
- Steps to reproduce this bug:

When you are logged in and Share > Present Mode, the new fullscreen opens up but the canvas is squashed so that it's about 100pixels high and as wide as your window. You can scroll through this squashed canvas. I believe this is new behavior but I don't know definitively. I don't see any errors on the console when this happens. Tested with multiple sketches.

**Comment by prabalp** [comment]
it's Share>Fullscreen, working fine for Share> Present Mode
Present: https://preview.p5js.org/Prabal/present/yh9ovX6dH
FullScreen: https://editor.p5js.org/Prabal/full/yh9ovX6dH

**Comment by catarak** [comment]
Thanks for reporting! I can reproduce. I recently unified some CSS and *thought* I tested it, but clearly I didn't do a good enough job 😄

**Comment by prabalp** [comment]
Yeah I am also trying to fix it ...and will sure upadate.

**Comment by catarak** [comment]
I just did a hotfix release (v2.1.1) as this is an issue that affects all sketches, so this should be fixed once the application is built and deployed (~10 min from now).

**Comment by lee2sman** [comment]
Thank you!
