### ISSUE TITLE
Feature request - easier gallery mode especially on mobile

### ISSUE THREAD

**Issue by vsinha** [processing/p5.js-web-editor#1944]
Apologies if this exists, but I'd really like a gallery view or simpler interface for just showing sketches i've made to friends using my phone or by sending them a link. In this use case, the editor view is not important and just the canvas and play/stop need to be front and center

**Comment by catarak** [comment]
Hello! Yes, you can get to this view by selecting File > Share and then clicking on the Fullscreen or Present view.
