### ISSUE TITLE
My sketch 20211018-MG-Music-Box-02-Galaxie shows a new sketch instead

### ISSUE THREAD

**Issue by MGonGitHub** [processing/p5.js-web-editor#1945]
#### Details about the bug: 

- Web browser and version: Safari Version 14.1.2 (16611.3.10.1.3) 
- Operating System: macOS Big Sur version 11.5.1 (20G80)
- Steps to reproduce this bug:My sketch 20211018-MG-Music-Box-02-Galaxie shows a new sketch instead. I had two safari windows each on a different sketch, was copying some file from one o the other, I got an error that my sketch could not be saved, I checked my internet connection, but all was ok. I could download my problematic sketch(attached its zip), but every time I open it it seems the link to it is broken. the url is : https://editor.p5js.org/MGOBRIAL/sketches/-VPerU0L8,
some other trials another sketch of mine is displayed instead:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/88580946/137791333-4cd9d315-c33f-4300-9665-ccdaa85f58af.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/88580946/137791056-83a9a266-c408-4e0d-abb9-37a7b15194eb.png">

[20211018_MG_Music_Box_02_Galaxie_2021_10_18_18_51_27.zip](https://github.com/processing/p5.js-web-editor/files/7367833/20211018_MG_Music_Box_02_Galaxie_2021_10_18_18_51_27.zip)
s:

**Comment by MGonGitHub** [comment]
Thank you in advance for your help
MGOBRIAL

**Comment by MGonGitHub** [comment]
On Safari : Version 14.1.2 (16611.3.10.1.3)
on macOS : Big Sur version 11.5.1 (20G80)

**Comment by MGonGitHub** [comment]
here is what I get today:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/88580946/137849728-686802d1-4128-49a3-8669-c2770b59551e.png">

**Comment by MGonGitHub** [comment]
today My problème persists:
<img width="831" alt="image" src="https://user-images.githubusercontent.com/88580946/137850135-e8f97874-d5b3-4dad-8aea-47f5f00db66b.png">

**Comment by MGonGitHub** [comment]
and this other sketch (https://editor.p5js.org/MGOBRIAL/sketches/-37wOOywY) appears ( the last one I opened) instead of the galaxy sketch on which I have the problem
<img width="831" alt="image" src="https://user-images.githubusercontent.com/88580946/137850494-bee6760b-7a2f-48c8-b76f-0b6d7a85683a.png">

**Comment by catarak** [comment]
Thanks for reporting! Somehow the sketch itself got corrupted, but I was able to go into the database and fix it. Your sketch should be loading now!

I believe this scenario would be avoided by implementing #1759. As of right now, having the same sketch open in two windows and editing it in both places leads to issues.

**Comment by MGonGitHub** [comment]
Thanks you Cassie Tarakajian for quick reaction.
It was quite lucky thought it was corrupted I still could download to my computer, and recreate it from there
Cheers to all the team
Monique GOBRIAL
