### ISSUE TITLE
Bug of Dark Theme in Collection list view

### ISSUE THREAD

**Issue by gurubi-gina** [processing/p5.js-web-editor#1949]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
- Web browser and version: On Chrome 95.0.4638.54
- Operating System: Windows 10
- Steps to reproduce this bug:

1. Set 'Dark' Theme in your settings.
2. Go to 'My Collections'.
3. Open any of your collections.
4. In this view, the 'Dark' theme is not working properly and that's why you cannot see all the sketches' name, just half of them. (Please find attached a screenshot.) Link to the collection: https://editor.p5js.org/gurubi.gina/collections/BuHvZU7eO
<img width="948" alt="capture1" src="https://user-images.githubusercontent.com/76647859/139248847-a5f76df9-fd97-4030-8077-a23247ac8925.PNG">

Can you please fix it? It worked fine a couple of months ago. Thanks!

**Comment by kjhollen** [comment]
Thanks for reporting this! I've seen this too. Making a note that I think this showed up with a recent push to introduce the privacy policy & terms of service, in case it's helpful.

**Comment by gurubi-gina** [comment]
Hi Kate, Thanks, I hope it can be fixed soon. BTW, I'm teaching some teenage girls for programming with the Editor in Hungary. We are using it quite often and everyone loves it. :)

**Comment by gurubi-gina** [comment]
Thanks a lot for fixing this. :)

**Comment by gurubi-gina** [comment]
Thanks a lot for fixing this.
