### ISSUE TITLE
can't open specific sketch

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js-web-editor#195]
One of the students in our class today reported a problem where she was unable to open a previously saved sketch. It is listed in the set of sketches, but the interface freezes with a blank text editor when the sketch is opened.

Her project had a lot of images in it, which she was planning to move into folders. So she deleted the existing images and planned to re-upload them in folders. Something went wrong in the delete and the sketch stopped responding. She restarted Chrome and opened the sketch again, but the interface freezes without opening the code (other parts of the interface are then non-clickable in this state).

Link to sketch:
http://alpha.editor.p5js.org/projects/rykFUSlWl

Is there any way to tell if the data's still there? The student had another save of the project in a different sketch, but it wasn't as far along as this one.

**Comment by catarak** [comment]
Probably what happened is that the data got corrupted after the file deletion didn't work. I'll see if I'm able to fix this manually so that the student can access their work again.

**Comment by catarak** [comment]
okay, fixed! I think what happened is that the project got into a weird state when the file highlighted in the sidebar got deleted, and then the editor didn't know which file to select. I _thought_ that i had handled this case but I will do some investigation.

**Comment by kjhollen** [comment]
Thank you, Cassie!!!
