### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by code4humanity** [processing/p5.js-web-editor#1951]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
This is an issue to review and discuss improvements in Portuguese translation.

Suggested changes:
- [ ] [Editor de Web p5.js](https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/pt-BR/translations.json#L91) => Editor online do p5.js
- [ ] [Salvar automático ativado.](https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/pt-BR/translations.json#L105) => Salvamento automático ativado.
- [ ] [Prévio](https://github.com/processing/p5.js-web-editor/blob/develop/translations/locales/pt-BR/translations.json#L60) => Anterior

**Comment by parteekcoder** [comment]
hey @raclim is this issue is solved

**Comment by raclim** [comment]
Yes, thank you for catching this!
