### ISSUE TITLE
Can't login with google 

### ISSUE THREAD

**Issue by awade05** [processing/p5.js-web-editor#1957]
#### Nature of issue?

- Found a bug
- Existing feature enhancement

#### Details about the bug: 
![image](https://user-images.githubusercontent.com/51447771/140316642-1d68e0b5-306f-4bb3-b26a-6364ee1324f5.png)

**Comment by catarak** [comment]
This has been fixed, and I'm sorry for not fixing this sooner. We're a really small team (in fact, the editor team is just me, part time), and there are a lot of notifications on discord/discourse/GitHub/Twitter/etc. It's difficult to sift through them and find that things that need to be attended to immediately. In the future, for anything urgent, please email hello@p5js.org. And also, in the future, I'll do a better job of communicating how to reach the team for urgent issues. I really appreciate the patience and support!
