### ISSUE TITLE
Google Sign In NOT WORKING

### ISSUE THREAD

**Issue by Mshuman8** [processing/p5.js-web-editor#1958]
#### Nature of issue?

- Found a bug

#### Details about the bug: We are not able to login using google anymore.

- Web browser and version: 
- Operating System: MacOS Big Sur 11.2.1
- Steps to reproduce this bug: Try logging in using Google -- I can occasionally get it to work on about the 30th attempt. This is not functional for a classroom setting.

<img width="358" alt="Screen Shot 2021-11-04 at 10 42 40 AM" src="https://user-images.githubusercontent.com/37717052/140334687-3932522f-e1ea-452b-ba93-be2bcd410ba3.png">

#### New feature details:

**Comment by catarak** [comment]
This has been fixed, and I'm sorry for not fixing this sooner. We're a really small team (in fact, the editor team is just me, part time), and there are a lot of notifications on discord/discourse/GitHub/Twitter/etc. It's difficult to sift through them and find that things that need to be attended to immediately. In the future, for anything urgent, please email hello@p5js.org. And also, in the future, I'll do a better job of communicating how to reach the team for urgent issues. I really appreciate the patience and support!
