### ISSUE TITLE
Sign in Auth Error

### ISSUE THREAD

**Issue by Cyberdoggo13** [processing/p5.js-web-editor#1960]
There is a current problem with signing in with google, where it brings you to a google page that says authorization error and says Error 400: redirect_uri_mismatch
If you could fix this, that would be great, as the projects I'm working on are stored with a google account

**Comment by catarak** [comment]
This has been fixed, and I'm sorry for not fixing this sooner. We're a really small team (in fact, the editor team is just me, part time), and there are a lot of notifications on discord/discourse/GitHub/Twitter/etc. It's difficult to sift through them and find that things that need to be attended to immediately. In the future, for anything urgent, please email hello@p5js.org. And also, in the future, I'll do a better job of communicating how to reach the team for urgent issues. I really appreciate the patience and support!
