### ISSUE TITLE
Can't duplicate specific sketch

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#1961]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome 95.0.4638.69 (Official Build) (arm64)
- Operating System:  Mac OSX Big Sur 11.4
- Steps to reproduce this bug:
1. Login to p5.js Editor
2. open https://editor.p5js.org/codingtrain/sketches/ULA97pJXR
3. Go to File > Duplicate
4. Editor doesn't not change (is responsive though), then shows the following error in the console
<img width="1303" alt="Screen Shot 2021-11-04 at 5 21 34 PM" src="https://user-images.githubusercontent.com/6063380/140421990-ee801a27-2c50-4d22-969e-96d3e765af34.png">

Possibly related to #719?

**Comment by 3ru** [comment]
I could not duplicate or download [the URL](https://editor.p5js.org/codingtrain/sketches/ULA97pJXR) sketch as well. However, I reproduced [the exact same file structure in my p5 editor](https://editor.p5js.org/Ryuya./sketches/Szv61hVDl) and had no problem.

This is not enough to determine the cause. We may be able to make progress by collecting a few more sketches that cannot be downloaded or duplicated.
