### ISSUE TITLE
Full Screen mode not working

### ISSUE THREAD

**Issue by DenisovichDev** [processing/p5.js-web-editor#1962]
Hello! The fullscreen links don't seem to be working

#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 95.0.4638.69
- Operating System: Windows 10 (64-bit)
- Steps to reproduce this bug: Opening a fullscreen link of a sketch ([this](https://editor.p5js.org/DenisovichDev/full/HheYX4_2P), for instance) seems to open something like this
![image](https://user-images.githubusercontent.com/66998096/140530003-b47a67d9-2bf2-4058-91f2-47a5e74307bb.png)
For some sketches it works on FireFox, but most of the time it doesn't. I don't know if this problem is exclusively for me or not. Feedback is requested.

**Comment by catarak** [comment]
Thank you for reporting! I am able to reproduce. I'll try to find and deploy a fix as soon as possible!

**Comment by catarak** [comment]
One thing I'm noticing is that it *sometimes* it works, sometimes it doesn't... interesting!

**Comment by DenisovichDev** [comment]
Yes I've noticed that too. Some times a certain sketch works on a certain browser and not on another. And I think this bug got introduced very recently too. Thanks for looking into it!
