### ISSUE TITLE
P5.js suddenly isn't showing preview for any of my sketches

### ISSUE THREAD

**Issue by Hel007** [processing/p5.js-web-editor#1969]
For some reason p5.js is not isn't loading the preview for my sketches anymore. I tried logging out and logging back in. I tried closing all my tabs and opening it back up again. I even tried restarting my computer but it still won't show it in the preview. However when I try opening up in a different chrome account it works so I am assuming it is only not showing on this account that I am working on.

**Comment by kjhollen** [comment]
Hi @Hel007, I'm sorry that you're having trouble with the sketch previews. We recently removed the Present mode option (see details in Issue #1965). Can you please clarify if this is the "Present" mode view of your sketch, or the Preview that appears next to your code when editing? Thanks!

**Comment by Hel007** [comment]
Hello, I meant the preview mode that appears next to the coding.

**Comment by kjhollen** [comment]
@Hel007, thanks for answering my question! An update was pushed to the site just a few hours ago, are you still seeing the issue?

**Comment by Hel007** [comment]
Hello, I am not seeing it anymore. The preview is showing up now! Thank you
for letting me know what was going on. I thought there was something wrong
with my laptop. Again thank you!

**Comment by kjhollen** [comment]
awesome, thank you for updating us! I'll close this since it seems to be working now. :)
