### ISSUE TITLE
P5.js is no longer support the option present ?!

### ISSUE THREAD

**Issue by diaaahmedien** [processing/p5.js-web-editor#1970]
#### Nature of issue?

- Found a bug

Dear Sir, the future "Present" in the share menu in the online P5.js editor is no longer valid. my work uses this option is destroyed!

Please, tell me what is happening, shall I transfer to another editor?

**Comment by kjhollen** [comment]
Hello @diaaahmedien, I'm sorry that this has affected your work. We have removed this feature because it is being used for phishing scams and it is difficult for our small team to fix this. For details see discussion in Issue #1965.

If you need a preview without the p5 banner or editor code visible, I suggest switching to another editor or signing up for a service that can host the project. Thanks for your post.

**Comment by diaaahmedien** [comment]
Dear kjhollen, 
Thanks for your prompt response, 

Could you please tell me any alternative if you have it in mind?

Best regards 
Diaa

**Comment by bakercp** [comment]
Didn't see this thread and posted the same question here.

https://discourse.processing.org/t/editor-p5js-org-present-mode-disappeared/33495/2

**Comment by gchinmayvarma** [comment]
Yo so just make a github repo,
Upload all the files, index.html sketch.js and so on

Then go to settings, pages, and host your repo as a github page

Its a lot of work
But this is the best alternative to having the "present" mode from the web editor

I also use the present mode a lot and am very sad its gone now :(

**Comment by kjhollen** [comment]
[glitch.com](https://glitch.com/) is also a great hosting service, with the friendliness of the p5 editor.

**Comment by catarak** [comment]
Hey all,

I just want to say that ideally, I would not like to remove this feature forever. It had been abused and used for phishing scams, which had only been increasing in number, so I had to make a quick decision to prevent this. I am open to any ideas about how to restore this feature and prevent phishing! Thanks for your continued support 💖

**Comment by gchinmayvarma** [comment]
Yes! The present feature is absolutely amazing when it comes to showing others your sketch or seeing it working on mobile, the latter one i find being the best way to make a webpage for mobile.

Hope to see ut back once this problem with phishing sites is dealt with.
