### ISSUE TITLE
Preview won't load

### ISSUE THREAD

**Issue by dayzabeth** [processing/p5.js-web-editor#1973]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by dayzabeth** [comment]
The preview in p5js can't be viewed. It keeps saying "The connection was reset" even though I'm connected to the internet. 
I tried a bunch of different things by restarting my laptop, clearing out cookies, deleting extensions and I even tried working in incognito mode, and nothing has changed. It still keeps showing up as "The connection was reset"

**Comment by kjhollen** [comment]
Hi @dayzabeth, we've been having some problems with sketches created for phishing on the p5 editor, which means some antivirus software is now blocking the previews. If you can add a website to your antivirus software's exception or allow list, please try adding editor.p5js.org and https://preview.p5js.org/*, then see if that clears things up.
