### ISSUE TITLE
attempts to access the editor give a 404 error

### ISSUE THREAD

**Issue by aparrish** [processing/p5.js-web-editor#1974]
Accessing any path at `editor.p5js.org` right now is returning a 404 error (with Google branding). Tested on several computers and browsers!

**Comment by cwhetung** [comment]
Hello,

We are seeing the same issue on Chromebooks and OSX using  Chrome Version 95.0.4638.69.

**Comment by catarak** [comment]
I'm sorry about this! I haven't changed anything recently so I'm not sure what's up. Investigating now and I'll try to get it back up as soon as possible!

**Comment by catarak** [comment]
Seems like it's working again and it was an error with the Google hosting.

**Comment by aparrish** [comment]
Wonderful! Thank you Cassie 🙏

**Comment by catarak** [comment]
Woah! Seems like there was a big outage: https://news.ycombinator.com/item?id=29243617

**Comment by cwhetung** [comment]
Amazing, thank you!

**Comment by kjhollen** [comment]
wow! whew, well, looks like this is resolved. 😅 thanks for reporting so quickly folks, and for finding out what happened @catarak!
