### ISSUE TITLE
Can't Open Specific Sketch

### ISSUE THREAD

**Issue by SanzSeraph** [processing/p5.js-web-editor#1981]
I have a sketch called Random Map Generator Prototype. While I was working on it, I received a message saying that it was saved in another tab, even though I only have it open in one tab.

Now, when I try to load that sketch, it always loads a new sketch with a randomly generated name.

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 96.0.4664.45
- Operating System: Windows 10
- Steps to reproduce this bug:

Not sure how to reproduce it. Seems like a fluke.

**Comment by raclim** [comment]
Hi, I'm sorry we couldn't get to this at the time! Since it's been a while I'm going to close this issue for now, but please feel free to reopen this or create a new one in the future! Thanks for your understanding! :)
