### ISSUE TITLE
getURLParams() not working in fullscreen share mode

### ISSUE THREAD

**Issue by mutterer** [processing/p5.js-web-editor#1991]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 97.0.4692.71 (Official Build) (x86_64)
- Operating System: OSX
- Steps to reproduce this bug:

1. Consider the example at https://p5js.org/reference/#/p5/getURLParams
2. Paste the code below in a new editor window
2. Create the fullscreen share mode using File, Share, Fullscreen option
3. add ?year=2014&month=May&day=15 to the URL
4. From the description, it is expected **not** to work from the editor, but supposed to work using the 'share' URLs

### Snippet:

```js
// Example: http://p5js.org?year=2014&month=May&day=15

function setup() {
  let params = getURLParams();
  text(params.day, 10, 20);
  text(params.month, 10, 40);
  text(params.year, 10, 60);
}
```

**Comment by calebfoss** [comment]
I think this is because the fullscreen and embed links now also display the sketch in an iframe (an iframe within an iframe in the case of embed) in order to prevent phishing, and since the parent and iframe have different subdomains, I don't know if the iframe could get the url of the parent.

**Comment by calebfoss** [comment]
So as long as that's the case, I'm wondering if it makes sense to update the reference page on the website to clarify.

**Comment by rinkydevi** [comment]
hey @calebfoss would u please explain a bit and help to work on it

**Comment by calebfoss** [comment]
@rinkydevi  What would you like further explanation on?

**Comment by raclim** [comment]
I'm going to close this for now, please feel free to reopen this or create a new issue if needed, thanks!
