### ISSUE TITLE
Use p5.js or p5.min.js in index.html

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#20]
I noticed that the minified versions of the library are referenced in `index.html`.   I think we should probably use the full versions for things like the friendly error messages, etc.  (This can eventually be preference with an editable template, etc.)

**Comment by catarak** [comment]
In retrospect this is obvious... but I did not realize the friendly errors aren't in the minified versions. Finally switching this out.

**Comment by catarak** [comment]
also I don't know how to test whether or not this is working... help? @shiffman

**Comment by lmccart** [comment]
I removed the friendly errors from the most recent version of p5.js because they need another pass to make them consistent and work well. So I think it makes sense for us to go with p5.min.js for the time being.
