### ISSUE TITLE
How to config a SSL certificate

### ISSUE THREAD

**Issue by oneandzeros** [processing/p5.js-web-editor#2001]
How do I config a SSL certificate to enable HTTPS request?

I have the domain and the http request is working on port 80.
I also have the ssl certificate already.

You can visit [p5js.net](http://p5js.net)

**Comment by DavidKozdra** [comment]
when I changed the URL to https://p5js.net it redirected to a p5 editor.

Following your domain directly led to a missing page

**Comment by raclim** [comment]
I'm going to close this issue for now, but please feel free to reopen this or create a new one in the future! Thanks! :)
