### ISSUE TITLE
Version inconsistency

### ISSUE THREAD

**Issue by reejuBhattacharya** [processing/p5.js-web-editor#2003]
#### Details about the bug:

- p5.js version: 1.4.0
- Web browser and version: 99.0.4844.82 (Official Build) (64-bit) (cohort: Stable) 
- Operating System: Windows 10
- Steps to reproduce this:

The CDN of p5.js in the `index.html` file of the web-editor refers to version `1.4.0` whereas as the latest released version of p5.js is `1.4.1`. This leads to certain latest features (such as FES features as addressed in this [issue](https://github.com/processing/p5.js/issues/5632) ), not being available in the web-editor.

**Comment by raclim** [comment]
The current p5.js version within the web editor is at 1.5.0, so I'm going to close this issue :) Thank you so much for working on this and catching this at the time!
