### ISSUE TITLE
Site não está funcionando!

### ISSUE THREAD

**Issue by lavi-lucindo** [processing/p5.js-web-editor#2005]
Bom, eu abri o site p5 js web e me inscrevi como o meu curso pedia porém, quando eu cliquei sobre os numeros que estavam no script para mudá-los, o cursor começou a se mover por todos os numeros e palavras do script. Fazendo com que eu nao conseguisse clicar em um numero e excluir ele para colocar outro, ou em qualquer outra coisa que estivesse no script. Eu testei também em outros computadores para me certificar se o problema era com o meu computador mas, no outro computador que testei (totalmente atualizado) deu o mesmo problema. Espero que a equipe do site consiga resolver esse problema para que eu possa dar continuidade ao meu curso e meus estudos.
Grata, Lavigne

**Comment by raclim** [comment]
Hi! :) I'm going to close this issue for now, but please feel free to reopen this or create a new one if this issue still persists for you, thanks for your understanding!
