### ISSUE TITLE
WebGL Primitives with Alpha Affected by Dark/Light Theme

### ISSUE THREAD

**Issue by stungeye** [processing/p5.js-web-editor#2006]
Discovered with my students that the editor's theme (Dark vs Light) will change the colour of 3D primitives when the fill includes an alpha transparency. Is this the expected behaviour?

#### Details about the bug:

- p5.js version: v1.4.0 (via the p5.js Web Editor)
- Web browser and version: Firefox 98.0.2 / Chrome 100.0.4896.60
- Operating System: Windows 10
- Steps to reproduce this: 
  - Open and run [this sketch](https://editor.p5js.org/SauceGames/sketches/pGZwcMIge).
  - Click the editor's settings button (gear).
  - Toggle mode between Light and Dark theme.

Sketch output when using Dark mode:
<img src="https://user-images.githubusercontent.com/124968/161306435-a38b7eb6-e715-4cf8-be0f-d566ab164d05.png" width=200>

Sketch output when using Light mode:
<img src="https://user-images.githubusercontent.com/124968/161306513-2c172bd0-a302-42e8-81a8-b27b2a6cc4fb.png " width=200>

**Comment by mkmori** [comment]
The current approach in 1.4.1 is to default the canvas (and other p5.Graphics) alpha attribute to false, to prevent show-thru. In this case, setAttributes("alpha", false); on the main canvas. (Also, 1.4.0 may be changed to 1.4.1 in the html file.)

Cf.: https://github.com/processing/p5.js/issues/5552

**Comment by stungeye** [comment]
Thanks @mkmori for the clarification. Both of the fixes you mention (setAttributes and p5js v1.4.1) worked for me. Closing this issue now.
