### ISSUE TITLE
🌸✨Leadership Update✨🌸

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#2010]
Hello dear p5.js community!

You've probably noticed that I have been a lot less active on here. When I started this project six years ago, I never could have imagined how big it would become. All of you have written over six million sketches on the p5.js editor! As you can imagine, the responsibility has also grown over the years and there is a lot of pressure to make sure the site is up. 

I have made the difficult decision to step down as the p5.js Editor lead. Keep an eye out soon for an open call to find someone new to lead and steward this project. It has given me so much and I'm excited for this project to grow with new leadership.

To help with the leadership transition process, I am putting the p5.js Editor into maintenance mode. This means that I will only be making sure that the website is online, fixing critical bugs, and updating documentation. This project is not going anywhere—it will still be supported by the Processing Foundation and will not be in maintenance mode forever.

Thanks especially to everyone who has contributed, large and small, to this project over the years. I couldn't have kept this going without you. And thanks for being a supporter of the p5.js Editor!

💖 Cassie

**Comment by calebfoss** [comment]
Thank you for all the work you've done to build and maintain this amazing project! 

As a teacher, it is so amazing to introduce students to a tool that they can get started with so quickly without installing anything, can use to make small or big complex things, and can share their creations with the world so easily. And in creative work, it's such a wonderful tool for sketching. 6 million sketches is absolutely wild, and it's incredible how many folks have benefited from what you've created here. 

Just wanted to say thank you!!! 
👏🏻👏🏻👏🏻👏🏻👏🏻👏🏻
