### ISSUE TITLE
Can't log in like usual

### ISSUE THREAD

**Issue by bricedre** [processing/p5.js-web-editor#2012]
For no apparent reason, I can't get to log in to my account by using the typical login page : https://editor.p5js.org/login

Have my email and password correctly typed, nothing special here.
Cursor changes to red barred circle when I hover over the Log In button.
Clicking doesn't do anything at all.

GitHub & Google buttons works fine though.

**Comment by BillBoese** [comment]
I can't log in either, I had a session open I can still work in it but cannot save. I get the attached error.
![error](https://user-images.githubusercontent.com/72985447/161798436-494fccc6-0981-4e5d-820d-49c0b2aae64e.PNG)

**Comment by catarak** [comment]
Thanks for reporting! I'm aware of the issue and doing my best to track it down. I've isolated the issue to an error with the database and filed a ticket with the database service we're using. I will hopefully hear back soon.

**Comment by catarak** [comment]
I think it is now fixed. Unfortunately an error with the database service itself! I think the planned outage I have scheduled this upcoming weekend will address this issue as well.

**Comment by BillBoese** [comment]
I am able to log in now, all appears to be working normally.  Thank you so much for taking care of this!!!

**Comment by bricedre** [comment]
Wow, that was a quick response :) Thank you so much for all your efforts, this tool is absolutely phenomenal !
