### ISSUE TITLE
Remove React warnings

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#2021]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to the p5.js Editor?

Improves stability of the application.

#### Feature enhancement details:

When running the p5.js Editor locally, React outputs to the console some deprecation warnings, due to updating the React version. I would like to fix these warnings in an attempt to keep React up to date.

**Comment by raclim** [comment]
Closing as addressed, as the warnings are no longer appearing in the console.
