### ISSUE TITLE
Migrate Webpack to use Asset Modules

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#2023]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to the p5.js Editor?

Add stability to the p5.js Editor by keeping packages up to date

#### Feature enhancement details:

I just upgraded to Webpack v5, but I did not upgrade to [Asset Modules](https://webpack.js.org/guides/asset-modules/). `raw-loader`/`url-loader`/`file-loader` are going to be deprecated in the next version, so it would be good to update this.

**Comment by AlexMunoz** [comment]
Hello @catarak, could you please take a look at this PR https://github.com/processing/p5.js-web-editor/pull/2026
