### ISSUE TITLE
Feature Request: Change New Sketch Contents

### ISSUE THREAD

**Issue by ghost** [processing/p5.js-web-editor#2025]
When I make a new sketch, I must change the index.html and other attached files the same way each time: I typically import a specific (domFuncs.js) file with helpful functions that I use frequently, change the spreadsheet to a <style> tag in order to reduce total files and make navigation easier, and remove the p5.js libraries, since I often don't use them in an effort for universality. 
It would be nice if, perhaps in user settings, there was an option to change the default index.html file; and perhaps even to change the files that are created on new sketch.
For my personal example, i'd like to create ONLY an edited index.html file, and a sketch.js file; as well as importing the domFuncs.js(which could be uploaded or typed in editor).
Thank you for considering my request.

**Comment by aarondill** [comment]
This issue was created by me (@aarondill) under a different account which has now been deleted. Please direct any questions or messages to the original reporter to my account. Thank You :smile:

**Comment by raclim** [comment]
I think this could be interesting, but am unsure if this is something we plan to put on our roadmap in the near future! Would definitely be interested in revisiting this down the line if this idea gains more traction!
