### ISSUE TITLE
All sketches have disappeared for user. Recovery possible?

### ISSUE THREAD

**Issue by cmjmousseau** [processing/p5.js-web-editor#2028]
#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

I am a teacher using the p5.js online editor with my students. A student has "lost" his entire semester's sketches in his p5.js editor account. He says that his computer crashed and when he went back to the editor there were no longer any sketches. When I use a link to one his previous sketches I get the  error that it doesn't exist. I can also see that all his sketches are gone when I navigate to see all his sketches.

I'm not sure how this is possible, short of my student individually deleting each sketch. 

I'm curious about this ever happening before and what may have caused it to happen.

Thanks for any help with this issue.

**Comment by calebfoss** [comment]
Something that's happened with my students in the past is that they've changed their username, which results in a change to their sketch links. So that would be something to check!

**Comment by cmjmousseau** [comment]
Thanks for that tip. I will definitely look into that possibility!

**Comment by raclim** [comment]
Hi! Unsure if this issue has exactly been resolved, but I'm planning to close it in a few days. Please let me know if there's anything here that needs further discussion or feel free reopen this issue in the future, thanks! 🙂

**Comment by cmjmousseau** [comment]
I was never able to figure out what happened to that student account. He seemed to be pretty adamant that he didn't change his username as @calebfoss had suggested. In any case, I've retired from teaching and that student has moved on.

Thanks for following up. You may as well close it.

**Comment by raclim** [comment]
😂 Seems to be a mystery. Thanks for getting back to this, I'll close this issue out!
