### ISSUE TITLE
Color picker changing default output 

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#2030]
Hi all, 
The color picker is great!  
I figured out that you can change the default output by clicking the letters, but it is a little unintuitive. 
Could there be an "output pulldown menu?" Or maybe just clicking on any of the letters cycles through all the options? Right now I have to click HEX to get it to output RGB, which feels backward. 
Maybe it should also be under the help menu?

**Comment by heyhimansh** [comment]
Hey @raclim @joemckay5  I really like to address this issue by implementing a color picker with multiple output options, enhancing the user's ability to choose colors according to their preference. Adding such a feature could indeed make the color picker more user-friendly and efficient.

**Comment by raclim** [comment]
Thanks for suggesting this and for your interest in this issue! I don't think this is something we're planning on implementing in the near future so I'm going to close this for now, but I think it can be potentially revisited down the line so I'm going to add it to [this board for closed issues saved for later](https://github.com/processing/p5.js-web-editor/projects/11#card-90887046)!
