### ISSUE TITLE
Change text size based on if computer is desktop or laptop

### ISSUE THREAD

**Issue by potatochipsnotincluded** [processing/p5.js-web-editor#2041]
Hi! I think that it there should be a feature where depending on if you have a laptop or pc change the text size, I've tested this code snippet: `navigator.getBattery().then(function(battery) {
    if (battery.charging && battery.chargingTime === 0) {
        console.log("I'm a desktop")
    } else {
        console.log("I'm not a desktop")
    }
});` and it works! Maybe someone can add this in!

**Comment by 3ru** [comment]
We can already change the font size in the settings, but in what situations do we need this feature?

**Comment by potatochipsnotincluded** [comment]
Well sometimes I need to work on a laptop but I don't want to have to change the font setting because I have to change it back when I'm on desktop, so maybe there could be a setting for default laptop text size and default desktop font size. But I realized if the laptop is charged to 100% the code snippet will say it's a desktop and, I don't know how to fix that, so maybe someone else can fix it?

Oh, I almost forgot, the code snippet I gave you is from StackOverFlow here's the link to it,: https://stackoverflow.com/questions/42596664/detect-whether-client-system-is-laptop-or-desktop-using-javascript
