### ISSUE TITLE
Allow .mjs files in the p5.js editor

### ISSUE THREAD

**Issue by quinton-ashley** [processing/p5.js-web-editor#2047]
I've got some great ideas for how modules can be used in the online editor. It'd be really nice to use top level await!

**Comment by raclim** [comment]
Hi @quinton-ashley, would love to hear more about your ideas for implementing modules! Would you be able to expand a bit more on them? I'd love to get a clearer sense of what you're thinking of! For example, why or in which circumstances would you like to use top level await while working within the editor! Thanks!

**Comment by quinton-ashley** [comment]
old issue sorry, I realized those ideas I had were not so good haha 😂

**Comment by raclim** [comment]
It's all good! I'll close this issue for now, but please feel free to reintroduce this if these ideas come back to you! :)
