### ISSUE TITLE
Find

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#205]
Actually research and implement find.

**Comment by catarak** [comment]
The design for this exists and is on zeplin.

**Comment by andrewn** [comment]
CodeMirror has a `search` addon that manages it's own dialog box and UI. We could use this as-is and use CSS to style the dialog. This is the approach Glitch seem to have taken:

<img width="458" alt="screenshot 2017-04-28 10 14 24" src="https://cloud.githubusercontent.com/assets/1762/25520346/e3a4b642-2bfb-11e7-8858-038a7932858a.png">

It doesn't look like this supports adding to the search dialog such as the Regex and  Case-sensitive search options in the design:

<img width="382" alt="screenshot 2017-04-28 10 17 51" src="https://cloud.githubusercontent.com/assets/1762/25520462/465c5952-2bfc-11e7-8df2-4ccdcfa43594.png">


Alternatively, we could fork the addon and convert it to use React which is more work but would give us more control.

**Comment by catarak** [comment]
In my conversation with the developer at Glitch he advised against making changes to CodeMirror as it can be a big time suck. Though looking at the CodeMirror [documentation](https://codemirror.net/doc/manual.html#addon_dialog), it seems like regex is supported, so maybe  making the UI change wouldn't be so hard.

I say make it work for now without forking the addon, and then once it works, investigate how much time it would take to change the UI.

**Comment by andrewn** [comment]
@catarak This issue can be moved from "In Progress" to "Done"
