### ISSUE TITLE
Increase font size button can concatenate `20` => `202` instead of adding

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2053]
The "Increase" and "Decrease" font size buttons can have strange behavior if they are clicked after typing in the input.

To reproduce, click on the input and type `20`.  Then, _without hitting Enter_, click the "Increase" button.  You should see this:
![image](https://user-images.githubusercontent.com/28965286/183309683-aad1bc88-541c-4605-9177-46966d1bdec1.png)

If the user hits Enter to submit the form then the "Increase" and "Decrease" buttons will work as expected.

**Comment by parteekcoder** [comment]
@raclim this issue is solved you can review my PR #2129

**Comment by parteekcoder** [comment]
@catarak @raclim please review my PR, your suggestions will be appreciated
