### ISSUE TITLE
Improve the console

### ISSUE THREAD

**Issue by quinton-ashley** [processing/p5.js-web-editor#2055]
Make the p5.js console better by implementing a console.log that could log arrays accurately:
https://media.discordapp.net/attachments/837760254229610586/1011294141466038352/unknown.png

**Comment by raclim** [comment]
Hi! As we're currently in the process of organizing issues and discussions, I'm going to close this issue since might not plan to focus on this in the near future. Thanks for your understanding and please feel free to reopen this or create a new one!

**Comment by quinton-ashley** [comment]
this is an easy fix that should be implemented in the near future
