### ISSUE TITLE
When a sketch is downloaded to a zip file bad/invalid CRCs generated for all files in zip

### ISSUE THREAD

**Issue by rruubboott** [processing/p5.js-web-editor#2056]
When a sketch is downloaded as a zip file it sucessfully takes all content (sketch and P5JS supporting libraries) and compresses it into a zip file. However, CRCs are not generated or stored in the zip file. By default the CRC on each file in the zip is 00000000. This prevents extraction of files from the zip archive unless CRC checks are bypassed.

This is happening in multiple web rowsers and operating systems.

**Comment by hspencer** [comment]
Hello. I'm having (I think) the same issue. All uncompressed files are 0 bytes.

**Comment by raclim** [comment]
We just merged and deployed @dwight9339's [pull request](https://github.com/processing/p5.js-web-editor/pull/2048), so hopefully this issue has been resolved. Please reopen this if it appears again, thanks! 🙂
