### ISSUE TITLE
Fail to download big sketch

### ISSUE THREAD

**Issue by cesarholive** [processing/p5.js-web-editor#2057]
#### Details about the bug:

- p5.js version:  p5.js/1.4.1/ 
- Web browser and version: Google Chrome  Versiion  104.0.5112.79 (oficial) 64 bits
- Operating System: 5.15.60-1-MANJARO
- Steps to reproduce this: Click in file and download inside my sketch
  According to the image below, there is a network failure and the download freezes at 10.02mb, I have already tested it on other networks and computers. the problem only occurs with this project https://editor.p5js.org/secesar/sketches/Wk7Oorw40 <a href="https://imgur.com/gpyN2XH"><img src="https://i.imgur.com/gpyN2XH.png" title="source: imgur.com" /></a>

**Comment by 3ru** [comment]
@getsugate
I checked this by going back to the original issue and could download it without any problems.

Is this issue still unresolved?
