### ISSUE TITLE
Cannot save sketch on iOS browser

### ISSUE THREAD

**Issue by LuisBrime** [processing/p5.js-web-editor#2059]
#### Details about the bug:

- p5.js version: 1.4.1
- Web browser and version: 104.0.5112.99 (Official Build) stable (64-bit)
- Operating System: iOS 15.6.1
- Steps to reproduce this:
1. Login with user into the Editor.
2. Open any saved sketch.
3. Make any change and click File > Save
4. This error appears
![image](https://user-images.githubusercontent.com/23020655/188329044-c5d9abcf-befd-4794-a62c-4aebca6c937f.jpeg)

**Comment by raclim** [comment]
Hi @LuisBrime! I tried to recreate the issue (using the versions p5.js 1.5.0 and Safari 16.1) following the outlined steps, and haven't been able to find any issues with saving yet. Has this issue still been persisting for you?

**Comment by raclim** [comment]
Hi! I'm going to close this issue for now, but please reopen this or create a new one if it's still happening for you, thanks! :)
