### ISSUE TITLE
Welcome Rachel @raclim!

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#2061]
Hello p5.js community,

Please join me in welcoming Rachel Lim (she/her) @raclim as the new p5.js Editor project lead! I am so excited that she will be stewarding this project with the support of myself and Processing Foundation, and look forward to everything she brings to this project. I actually taught Rachel p5.js back in 2018 using the p5.js Editor so this feels like it was meant to be 😸 

It will obviously take some time for Rachel to get settled, so please extend to her your patience and support through this transition. Yay Rachel!

💖 Cassie @catarak

**Comment by Qianqianye** [comment]
Welcome, @raclim!
Just updated the web editor maintainer info in the p5.js [contributor_docs](https://github.com/processing/p5.js/blob/main/contributor_docs/README.md#where-our-code-lives)!
