### ISSUE TITLE
Update p5.js version to v1.4.2

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#2062]
### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to the p5.js Editor?

Making the p5.js Editor stable makes the p5.js Editor accessible!

#### Feature enhancement details:

Update the p5.js Editor so that the default version for new sketches, as well as the example sketches, is v1.4.2.

**Comment by Qianqianye** [comment]
We should update the p5.js version on web editor to v1.5.0 🎉

**Comment by SableRaf** [comment]
Working on it! I just need a moment to clean up and test locally.
