### ISSUE TITLE
Downloaded sketches 0 bytes in size..

### ISSUE THREAD

**Issue by rorywalsh** [processing/p5.js-web-editor#2063]
Downloading sketches from the p5js editor no longer seems to work. Each is 0 bytes in size. 

#### Details about the bug:

- p5.js version: The one used by the online editor
- Web browser and version: Chrome
- Operating System: MacOS
- Steps to reproduce this:
   - Login to p5js editor
   - Create a simple sketch
   - Save and hit Download - all the files in the downloaded zip folder are 0

**Comment by kjhollen** [comment]
thanks for this bug report! we're tracking this in issue #2038, so I'm going to close this one to keep the discussion focused there.

**Comment by rorywalsh** [comment]
Thanks @kjhollen I somehow managed to miss the numerous threads on this 🙈
