### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by olivierevrard** [processing/p5.js-web-editor#2064]
The sketch can be downloaded but all the files are empty. Zero octets.

**Comment by yangshuzhan** [comment]
I also have this issue.

**Comment by bluelhf** [comment]
Same issue here — The downloaded ZIP archive has all my files, but their lengths are zero.

EDIT: This issue seems to be a duplicate of #2038.

**Comment by kjhollen** [comment]
Hi folks, thanks for this report. We are tracking this issue in #2038, so I'm going to close this but you can follow updates there.
