### ISSUE TITLE
What happened to presentation mode in p5.js?!

### ISSUE THREAD

**Issue by codeNerdKelly** [processing/p5.js-web-editor#2066]
Is there any way to disable the link in full-screen mode that takes viewers back to the source code?

**Comment by raclim** [comment]
Hi! I don't believe that there's currently a way to disable the links in full-screen mode (but I could be incorrect and am open to any suggestions 🙂). In which scenarios do you feel that disabling the links would be more helpful? I'd love to gain more context!

**Comment by raclim** [comment]
Hi! We're currently in the process of organizing issues to distinguish discussion-related topics from bugs, so I'm going to close this for now :) Please feel free to reopen this or create a new issue in the future, thanks!
