### ISSUE TITLE
Downloaded files are blank (Critical)

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-web-editor#2067]
After logging in, saving a sketch, and then downloading, all files in the zip are blank. 

If verified, this should qualify as a **critical** issue (for example, students cannot hand in assignments in the usual way) 

#### Details about the bug:

- p5.js version: online editor
- Web browser and version: tested in Chrome v105.0.5195.125  and Firefox 105.0.1 
- Operating System: OS X 11.6
- Steps to reproduce this: log in, save sketch, click download, open zip, files are empty

**Comment by dhowe** [comment]
duplicate of https://github.com/processing/p5.js-web-editor/issues/2038

I know everyone is busy but this REALLY needs to be fixed ASAP

**Comment by kjhollen** [comment]
Closing as duplicate.
