### ISSUE TITLE
Download from p5 web editor produces blank text files

### ISSUE THREAD

**Issue by billythemusical** [processing/p5.js-web-editor#2068]
This is an issue with the p5 web editor. When I try the Download option from the p5 web editor, either some or all of the files are empty when unzipped.

Steps to reproduce this:
- Download a project from the p5 web editor.  
- Unzip and open all of the files in a text editor like Atom.  
- See that the files are indeed empty.

### p5.js version
1.4.1
### Web browser and version
Chrome 106.0.5249.119 (Official Build) (x86_64)
### Operating System
MacOS 10.15.7 (19H2026)

**Comment by madshobye** [comment]
I can confirm - I came to report the same problem. Chrome Browser and Mac OSX. The zip file has volume - so it may be a problem with the zip file being encoded wrongly. It is also consistent when downloading old sketches, so my best ques is that the way the cloud ide compresses does not match the way Mac OSX (11.5.2) expects it to parse.

<img width="637" alt="Screenshot 2022-10-18 at 18 12 13" src="https://user-images.githubusercontent.com/497958/196486049-f7c54415-86d9-4147-9097-a0e00b79fc88.png">

**Comment by kjhollen** [comment]
Hi folks, thanks for your bug report. We're already tracking this in #2038, so I'm going to close this as a duplicate. Please see the other thread for possible workarounds, including archiving tools that can still parse the incorrectly zipped file.
