### ISSUE TITLE
Display editor and p5.js version numbers in 'about' menu

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-web-editor#2070]
Would be super useful in tracking issues to easily know what versions one is using...

**Comment by raclim** [comment]
Agreed, I think it'd be a great addition! 🙂

**Comment by idivanshu** [comment]
Hey i am newbie in open source. I want to work on this issue. Can u tell me from where i can fetch the information about editor and p5.js version numbers(like which api) , so that i can display those on about (Menu).
Also can u plz give me link of chat room for this community.

**Comment by dewanshDT** [comment]
hey @raclim please assign this to me

**Comment by dewanshDT** [comment]
@dhowe @raclim I've successfully added this to the about section and created a PR, please check it out.
(this is not hard coded)

![p5about](https://user-images.githubusercontent.com/71703033/219595512-ce6a3f62-6222-47f9-9e02-e8def06bb07f.png)
