### ISSUE TITLE
Binary files in downloaded .zip are corrupted

### ISSUE THREAD

**Issue by pierrep** [processing/p5.js-web-editor#2075]
Any binary files included in the .zip file downloaded by selecting File->Download will be corrupt.
Text files are fine.

#### Details about the bug:

- p5.js version: 1.4.2
- Web browser and version: Firefox 105.0 (64-bit), Chrome 107.0.5304.87 (Official Build) (64-bit)
- Operating System: Linux
- Steps to reproduce this: Download a project with some binary files (sound/images/etc). The zip file downloads, but the extracted files are corrupt and will not open

**Comment by dwight9339** [comment]
That is a problem. @raclim, I'll look into this.

**Comment by Real-John-Cheung** [comment]
Not sure if the fix (#2077) have been live yet or not but seems that now the binary files are still corrupted in the downloaded zip file

**Comment by raclim** [comment]
Hi all! Thanks @dwight9339 for looking into this! The [#2077 ](https://github.com/processing/p5.js-web-editor/pull/2077) fix has just been pushed live. Please feel free to reopen or create a new issue if it persists!
