### ISSUE TITLE
Failing Test in Toolbar.unit.test.jsx

### ISSUE THREAD

**Issue by raclim** [processing/p5.js-web-editor#2084]
#### Details about the bug:

When tests are run using the command "npm run test:ci", regardless of the branch the user is in or the changes that have been made, one test regarding the Toolbar.unit.test.jsx file will fail.

**Comment by KrishangSaharia** [comment]
If this is still open, can I take this issue, also I am new to open source so it would be a good starting point for me also?

**Comment by raclim** [comment]
Hi @KrishangSaharia! Yes, this issue is still open and free to take! Just assigned it to you :)

**Comment by ayushbhaimehta** [comment]
@KrishangSaharia are you still working on this??

**Comment by parteekcoder** [comment]
hey @raclim can you please share the screenshot what is displayed when the test is failing
