### ISSUE TITLE
failing to importing a module from project 

### ISSUE THREAD

**Issue by vlazzarini** [processing/p5.js-web-editor#2091]
#### Details about the bug:

- p5.js version: the latest on p5.js editor
- Web browser and version: Chrome 108.0.5359.98 
- Operating System: MacOS
- Steps to reproduce this:

open the sketch

https://editor.p5js.org/vlazzarini/sketches/DOMRws-Mo

In the sketch.js code, the following commented out line works

```
r = import('./csound.js') // works
```

but this one doesn't

```
r = import('./test.js') // doesn't work
```

with the error

```
TypeError: Failed to resolve module specifier './test.js'
```

both are valid JS modules with exported functions.

I downloaded the sketch and run it locally without any issues.

**Comment by orazdow** [comment]
Same problem here:

    import {solids, polyhedra, models} from './model.js';
    import {loadObj, edgeList} from './loader.js' // << doesnt work 

error: ```TypeError: Error resolving module specifier “./loader.js”. Relative module specifiers must start with “./”, “../” or “/”.```

**Comment by raclim** [comment]
Thank you for bringing this up! I think this is related to an earlier issue, https://github.com/processing/p5.js-web-editor/issues/1933, so I'm going to close this one for now but keep note of this!
