### ISSUE TITLE
Log in via Github account fails repeatedly

### ISSUE THREAD

**Issue by AGardenerCoding** [processing/p5.js-web-editor#2092]
When I select the Log in link of the p5.js.org page, then Log In with GitHub, upon entering my user name and password I get a message something like "Redirecting..." and it returns me to the editor page, but I'm not logged in. Except that apparently I am logged in because I'm able to write this issue, but the editor page won't recognize me as being logged in, even when I try repeatedly.

This has happened some time ago ( haven't tried to log in for a long time ), and it was fixed somehow, but it's happening again.

**Comment by raclim** [comment]
Hi @AGardenerCoding! Thank you so much for reporting this! 

I just tried to recreate this issue, but wasn't able to do so from my end! If this issue is still happening for you, could you possibly add more details or screenshots? Thanks so much!

**Comment by raclim** [comment]
I'm going to close this issue for now, but please feel free to reopen this or create a new one with some additional details of this still persists! Thanks! :)

**Comment by bidgoli** [comment]
Hi there,
I am having the same issue. Getting this error:
```
There was a problem linking your GitHub account to your p5.js Web Editor account. Your GitHub account has already been linked to another p5.js Web Editor account.
```

I have two emails on my Github account (personal and work)
I had all of my sketches stored in the editor when I was logging in with Github.
But then, I used my work email to create a new account in the editor, and now I cannot log in using Github option anymore, and all of my sketches are gone. How can I fix it?
