### ISSUE TITLE
Error to run my project on P5.js

### ISSUE THREAD

**Issue by fsaltiel** [processing/p5.js-web-editor#2093]
Hello!

My name is Fran and I've been coding on p5.js for a while, but today when I entered my project and hit "run" the whole page freeze and eventually it crashed.
I didn't saw anything different from the last day I changed my project and that day it was functional and normal.
Anyway, I need help to get my project back so I can finish it.

Thank you so much! :) and sorry for my bad english :(

P.s.:
I attached a print screen from the console and the network of devtools, and also a video for demonstration, maybe that can be useful.
[p5.js .zip](https://github.com/processing/p5.js-web-editor/files/10320725/p5.js.zip)

**Comment by raclim** [comment]
Hi Fran, thank you so much for bringing this up! I wanted to check-in if you were able to resolve this, or if this issue is still persisting. Based off of what you sent, I was wondering if there was anything that might be resource-intensive within your sketch or device that might be causing this?

**Comment by raclim** [comment]
Hi Fran! I'm going to close this issue for now, but please feel free to reopen this or create a new one if your issue still persists! Thanks for your understanding! :)

**Comment by fsaltiel** [comment]
Hi Raclim! I'm sorry for the late answer, but the problem still persists! I've tried to open P5.js in differents devices, but every time that I run the project, the browser freeze and I have to close the tab. I would really appreciate to be able to finish my project, but even duplicating my project and using the new one, when I hit the button "run" it all freeze and I can't continue to code.

Thanks for your help!
