### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by chaudhary-99** [processing/p5.js-web-editor#2095]
A website without a footer is incomplete. I can add a nice footer that will match the p5-web-editor theme. Please assign this task to me.

**Comment by raclim** [comment]
Hi @chaudhary-99 , thanks for submitting this request! Before getting started with this task, could you describe your plan in more detail or provide some visuals for what you had in mind?

**Comment by raclim** [comment]
I'm going to close this issue for now, but please feel free to reopen this or create a new one with some more details! Thanks! :)
