### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by rajput999** [processing/p5.js-web-editor#2096]
A good looking navbar can make the website attractive. I can make the navbar attractive by adding some css and javascript.
Please assign this task to me.

**Comment by raclim** [comment]
Hi @rajput999, thanks for submitting this request! Before getting started with this task, could you describe your plan in more detail or provide some visuals for what you had in mind?

**Comment by raclim** [comment]
I'm going to close this issue for now, but please feel free to reopen this or create a new one with some more details! Thanks! :)
