### ISSUE TITLE
Can't See the difference in togglers in Light mode

### ISSUE THREAD

**Issue by ayushbhaimehta** [processing/p5.js-web-editor#2099]
#### Feature enhancement details:
One can not find the difference in clicking on or off for Autosave, Auto close and other features. If we give a little bit of shadow to the toggler which is clicked then this confusion can be solved.
![light mode](https://user-images.githubusercontent.com/77238801/212718448-11f76fed-ee14-4a2c-bb56-80ea88cce31c.png)
It can be made in such a way that it is clear for the user to identify whether the toggler is on or off like it is in other modes like dark or high contrast.
![high contrast mode](https://user-images.githubusercontent.com/77238801/212718692-e233de7a-afc6-49b3-9fe7-86b9f2372354.png)

**Comment by mkmori** [comment]
Hi, @ayushbhaimehta !
I also reported this some time ago, and I think a solution and PR may have been created...?
[/p5.js-web-editor/issues/2007](https://github.com/processing/p5.js-web-editor/issues/2007)

**Comment by mkmori** [comment]
Here's the PR--I'm not clear about what should happen next...?

[/p5.js-web-editor/pull/2011](https://github.com/processing/p5.js-web-editor/pull/2011)

**Comment by 3ru** [comment]
I have submitted a PR that addresses this.
I am still determining who is currently maintaining this repository, but I will include the two people(@raclim, @kjhollen) who assigned labels to issue #2007.

**Comment by 3ru** [comment]
@raclim 
I think we can close this issue along with the PR merge of #2011.

**Comment by raclim** [comment]
Sounds good, thanks so much for your work!
