### ISSUE TITLE
what errors / warnings to suppress?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#21]
This came up today, whether we want the editor to highlight errors like missing semi-colons.  For example the following has a 'missing semi-colon' error which is correct in one sense, but not always the convention in p5 examples.

``` javascript
var blah = function() {
  console.log('blah');
}
```

<img width="632" alt="screen shot 2016-07-21 at 2 40 00 pm" src="https://cloud.githubusercontent.com/assets/191758/17034545/1dca8032-4f51-11e6-828c-46fcc3178a5e.png">

**Comment by catarak** [comment]
To do this linting I'm using JSHint/CSSLint/HTMLHint, so we can just add custom configuration to whatever we think is reasonable.

**Comment by catarak** [comment]
Just removed the error for missing semicolons... let me know if there are any other errors that should be removed, or errors that should be added. For reference, here's the [JSHint options](http://jshint.com/docs/options/).

**Comment by lmccart** [comment]
I think it would be useful to suppress the == warning.
<img width="365" alt="screen shot 2016-12-13 at 2 06 41 pm" src="https://cloud.githubusercontent.com/assets/191056/21161427/66b02460-c13d-11e6-81de-dd880ac88a88.png">

**Comment by catarak** [comment]
I like that warning since my personal JS style is to never use `==` and `!=`, but I could be convinced that it's a confusing warning for beginner coders.

**Comment by lmccart** [comment]
Hah I also like the warning for myself! But most of our examples and teaching materials use ==, because teaching the distinction early on feels really confusing. I'm not sure what the answer is.. @shiffman thoughts?

**Comment by shiffman** [comment]
I would err on the side of suppressing the warning for the web editor since I am so lackadaisical abou the distinction, but it wouldn't take much to convince me otherwise.  Are scenarios where code won't work properly and having the warning could help?

**Comment by catarak** [comment]
I think the biggest issue is that it can lead to unexpected behavior when comparing different data types, e.g.
```javascript
console.log(3 == "3"); // true
console.log(3 === "3"); // false.
```
however, I imagine stuff like this isn't in any of the p5 examples or lessons, so I think it's okay to leave this warning off.
