### ISSUE TITLE
Log in problems

### ISSUE THREAD

**Issue by kmason12** [processing/p5.js-web-editor#2102]
I had an account using the email kmason@schools.nyc.gov however I signed in with Google and it gave me a different user name (kmason-diamond) and now I can't access all of the files that I have been saving in my collection over the past 6 years. I would greatly appreciate restoring my original account.

Best,

Karen Mason

**Comment by raclim** [comment]
Hi Karen, I'm sorry to hear that this is happening to you! I have a few questions below to help gain clarity for this issue:

- Did you previously use a different login method besides Google? If so, did you try using that method to sign in again? 
- What was your original username? 

Thank you!

**Comment by kmason12** [comment]
Normally I wouldn't use Google to log in but I did and I created a new
password. I did try again and it automatically signed into the new account.
I would just use my email address ***@***.*** as my username.

Best,

Karen Mason

**Comment by raclim** [comment]
Hi Karen, I'm so sorry for the delay in getting back to this! 

We'll need the email address you use as your username to resolve this. Please feel free to send it to hello@p5js.org, and we can continue our correspondence from there. Thank you again for your patience and understanding!

**Comment by kmason12** [comment]
I just sent the email. I look for assistance in this matter.

Thanks
