### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by itzjustandrei** [processing/p5.js-web-editor#2103]
Hello hello! I recently came back to p5.js and apparently it gives me this error: "TypeError: Cannot read properties of undefined (reading '_report')
    at undefined:2:30224"
I watched several videos and I couldn't solve this problem. Any help will be appreciated!

**Comment by raclim** [comment]
Hi @itzjustandrei! Could you add a link to your project or screenshots to help us gain more insight into what's happening? Thanks! :)

**Comment by itzjustandrei** [comment]
Yeah, sure! I’ll get to my computer as soon as possible. :)


Sent from Yahoo Mail for iPhone


On Monday, January 23, 2023, 8:46 PM, raclim ***@***.***> wrote:




Hi @itzjustandrei! Could you add a link to your project or screenshots to help us gain more insight into what's happening? Thanks! :)

**Comment by itzjustandrei** [comment]
Oops, I accidentally replied on email first. @raclim sure! I’ll try to get to my computer as fast as possible.

**Comment by mkmori** [comment]
Hi, @itzjustandrei , are you still experiencing this issue? And if so, maybe add a little detail to the title, e.g., "TypeError: Cannot read properties of undefined"...?

**Comment by raclim** [comment]
Closing this issue for now—please feel free to reopen this or create a new one if you're still experiencing this, thanks! :)
