### ISSUE TITLE
Cancel Authentication with Github error "Internal Server Error"

### ISSUE THREAD

**Issue by davidbmx** [processing/p5.js-web-editor#2104]
#### Details about the bug:

- Web browser and version: Safari Version 16.2
- Operating System: Mac OS 13.1 
- Steps to reproduce this:
1. Try to sign in with Github
2. In Authorize page click in Cancel button that redirect to https://editor.p5js.org/auth/github/callback?error=access_denied&error_description=The+user+has+denied+your+application+access.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23access-denied
<img width="1069" alt="Screenshot 2023-01-27 at 01 22 13" src="https://user-images.githubusercontent.com/12814631/214987931-eb6df9dd-ea33-4457-b631-836f7401e2a1.png">

**Comment by raclim** [comment]
Thanks for reporting this! I'm going to close this for now, but please feel free to reopen this or report another issue if this persists!
