### ISSUE TITLE
Changes in sketch files sometimes aren't reflected when the sketch is run

### ISSUE THREAD

**Issue by developer9199** [processing/p5.js-web-editor#2105]
As I've worked on larger projects, I've noticed that, sometimes, deleting or uploading files to a sketch doesn't change anything when the code is executed.
For example, if there's a tile texture that I'd like to replace, I would delete the file from the sketch files pane, then upload the new texture under the same name. However, when rerunning the code, the sketch continues to use the old texture until things finally sync up (this usually takes anywhere from a few minutes to hours or days).

![issue](https://user-images.githubusercontent.com/61306129/215283280-33f06d14-15b1-4aae-9e9e-3741da805d99.jpg)

The image above demonstrates the problem in a sketch of mine: the web editor doesn't detect the file's existence despite being listed in the sketch files pane.

**Comment by raclim** [comment]
Thank you for reporting this! I think this issue may be related to https://github.com/processing/p5.js-web-editor/issues/1738. There's been a few earlier issues related to file uploading with supplementary information, so I'll close this for now!
