### ISSUE TITLE
File drawer doesn't show spaces in file names

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js-web-editor#2106]
The editor file drawer removes spaces from files to list them in the UI, but doesn't actually remove them from the file path. A common error I will see with my students is that they encounter an error using loadImage, loadTable, etc. because they use the name displayed in the file drawer, not knowing they need any spaces from the original file name.

#### Details about the bug:

- p5.js version: n/a
- Web browser and version: Firefox 102.7.0esr (64-bit)
- Operating System: macOS 12.4
- Steps to reproduce this: upload a file with a name like "test 2.csv" that has a space in the file name. The file drawer will display the filename as "test2.csv", eliminating the space, but using loadTable("test2.csv", "csv", "header"); will fail with a file not found error.

Example sketch: https://editor.p5js.org/kjhollen/sketches/2tDA5z8ZG

**Comment by dewanshDT** [comment]
hey @raclim @kjhollen I can fix this, can I work on this issue?

**Comment by raclim** [comment]
Hi @dewanshDT, yes feel free to go ahead! :) Just assigned this to you

**Comment by dewanshDT** [comment]
Thanks 😁

**Comment by dewanshDT** [comment]
## This bug is already fixed, I've tried various types of files and they all show space between them in the sidebar
![fixed](https://user-images.githubusercontent.com/71703033/219468490-31889a8f-014e-49db-9b63-0b038bbeff23.png)

### in this example "cas door.png" has gap in between

**Comment by dewanshDT** [comment]
I think we can close this issue

**Comment by dewanshDT** [comment]
I found that this issue only occurs in mac for any browser not for windows devices

**Comment by dewanshDT** [comment]
hey @kjhollen @raclim, I'm really glad to inform you that I've successfully fixed this issue and created a PR please check it out.

![p5fixed](https://user-images.githubusercontent.com/71703033/219490794-cb729707-8545-4c96-9d57-26c921647c2e.png)

I've added all the details related to the changes and how I've fixed the problem in the PR
