### ISSUE TITLE
Difficulty in creating a .env file

### ISSUE THREAD

**Issue by Kirito-Excalibur** [processing/p5.js-web-editor#2107]
#### Difficulty in following things:
* Github access - What is it? Where can i find it? Are you referring to ssh keys?
* AWS Secret key- I only got AWS access key.
* AWS Region- My region is ap south 1. So how i'm supposed to write it?

**Comment by raclim** [comment]
Hi @Kirito-Excalibur! To answer your questions: 

- Yes I believe the Github env variables are referring to your SSH key. 
- I think [this post clarifies where to find your AWS Secret Key](https://www.msp360.com/resources/blog/how-to-find-your-aws-access-key-id-and-secret-access-key/#:~:text=1%20Go%20to%20Amazon%20Web,and%20Secret%20Access%20Key). 
- For your AWS Region, i think it can be written as 'ap-south-1,' which is included in [this list of regions.](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html) 

Hope this helps!

**Comment by raclim** [comment]
Hi, I'm going to close this for now, but please feel free to reopen this or create a new issue!

**Comment by Kirito-Excalibur** [comment]
What is Google id and google secret key?
