### ISSUE TITLE
Time Traveling console.log function

### ISSUE THREAD

**Issue by greenStone83** [processing/p5.js-web-editor#2111]
p5.js version: **1.5.0**

OS: **Windows 10**

Browser: **Firefox, Edge and Chrome, the most recent versions**

Whenever I run this code, I get [3] printed to the console instead of [2]

https://editor.p5js.org/greenStone83/sketches/U8_rP27J_ (include the underscore in the link)

**Comment by quinton-ashley** [comment]
Here's a related issue #1203 from 2019, 3 years ago. I also saw several reports of this issue on the Discord server over the past year. Unfortunately it still hasn't been fixed, even though it seems like a major issue for a dev environment.

**Comment by dewanshDT** [comment]
@greenStone83 @quinton-ashley @raclim I've checked and found that this problem issue is not related to this codebase and is associated with the npm library used `console-feed` here's the link to the repo [console-feed](https://github.com/samdenty/console-feed)

the function or hook they are using lacks asynchronous capabilities, that's the reason causing this problem.
