### ISSUE TITLE
Some functions are not define in the library.

### ISSUE THREAD

**Issue by rewired89** [processing/p5.js-web-editor#2115]
#### Details about the bug:

- p5.js version: 
- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

**Comment by rewired89** [comment]
The console is telling me some functions are not define in the library and I understand that maybe the libraries change but there's not new documentation about it. So what would be the correct-new method for loadAnimation, loadSpriteSheet and drawSprites()? The console show me that drawSprites() is now Spritesdraw() (Spritesdraw for real?), but does not mention the correct method for the other ones. My problem is that my sprite sheet of 15 frames doesn't show up in my canvas.

**Comment by quinton-ashley** [comment]
You need to load the p5.play library in your project. It isn't part of p5.js automatically.

**Comment by rewired89** [comment]
> You need to load the p5.play library in your project. It isn't part of p5.js automatically.

Yes, I did that, I copied and paste your template, thank you for that. Still doesnt work.

**Comment by quinton-ashley** [comment]
I helped rewired89 in the p5.play discord.

This issue can be closed and marked as completed.
