### ISSUE TITLE
Mobile UI (2020 issues?)

### ISSUE THREAD

**Issue by TravelTrader** [processing/p5.js-web-editor#2120]
I would really like a mobile UI of the editor, searched the issues and found a lot entries about a Mobile UI.

Was this cancelled?
Is there a special link for mobile use I couldn’t find yet?

On mobile the code box is too small to read/write anything and the code and preview are not collapsable.

Thank you very much!

**Comment by raclim** [comment]
Hi @TravelTrader, thanks for bringing this up! :) A complete mobile release hasn't finished yet, but we do have some resources for [UX](https://github.com/processing/p5.js-web-editor/wiki/Mobile-Documents) and [project management](https://github.com/processing/p5.js-web-editor/projects/6) done. The Mobile UI is still currently under development, but we're hoping to have a version of it out this year! Please feel free to hop in on the process or provide any particular feedback/features you'd like to see from that experience!

**Comment by ORKO06** [comment]
Hello @raclim, 
I would love to contribute to develop the mobile UI. I am a pre-final year student pursuing BTech in Industrial Design. I am a frontend developer and have knowledge of UI/UX

**Comment by raclim** [comment]
@ORKO06 Awesome! Feel free to refer to the designs and start developing with one of the issues linked above :) You can also add feedback to them or create new Mobile-related issues that you feel haven't been addressed yet.

**Comment by raclim** [comment]
I just realized there was an earlier issue for this https://github.com/processing/p5.js-web-editor/issues/65. To decrease duplicate issues, I'm going to close this for now!
