### ISSUE TITLE
npm i failed

### ISSUE THREAD

**Issue by parteekcoder** [processing/p5.js-web-editor#2121]
Reproduce

1. Clone the repo
2. run command :- npm install

It will give deprecation errors , as the packages used in the project are deprecated

**Comment by raclim** [comment]
Hi @parteekcoder, just to make sure, have you tried running it using the versions node 16.14.2 and npm 8.5.0?

**Comment by parteekcoder** [comment]
> 16.14.2

my node version is 16.16.0 
and npm 8.5.0

**Comment by raclim** [comment]
I'd recommend to try switching to 16.14.2, since that's the one that is most compatible for this project!

**Comment by parteekcoder** [comment]
yeah , that works fine @raclim

**Comment by raclim** [comment]
Awesome! Going to close this for now :)

**Comment by parteekcoder** [comment]
@raclim #387  can you please explain me about that issue , I am not able to find the upload file option
