### ISSUE TITLE
No favicon

### ISSUE THREAD

**Issue by parteekcoder** [processing/p5.js-web-editor#2140]
@raclim 
Reproduce

1. open sketch any other user like https://editor.p5js.org/greenStone83/sketches/IQMmFIkYv
2. you will find there is no favicon

Reason: it is making request to https://editor.p5js.org/greenStone83/sketches/favicon.ico for favicon
instead  should make to https://raw.githubusercontent.com/processing/p5.js-website-OLD/master/favicon.ico

**Comment by parteekcoder** [comment]
![image](https://user-images.githubusercontent.com/100110395/221856254-9987256c-79a4-436f-85f2-9ed6a33eaaca.png)

![image](https://user-images.githubusercontent.com/100110395/221856285-f061b71a-9ed1-4c3e-abd6-bdf7b39452d9.png)

**Comment by Noothan-am** [comment]
hi @parteekcoder ,I would like to fix this issue can you please assign it to me..?

**Comment by parteekcoder** [comment]
thanks @Noothan-am , but I already created a PR for this see #2141

**Comment by Skar3Krow** [comment]
Hey @parteekcoder , I would like to work on this issue if it's still not fixed.
