### ISSUE TITLE
theme setting not stored locally.

### ISSUE THREAD

**Issue by dewanshDT** [processing/p5.js-web-editor#2144]
### Description:
I have noticed that when the user is not logged in and enables the dark theme setting, it is not stored locally and have to enable it every time when visiting the site. It would be a great addition if the dark theme setting could be stored locally for the guest user so that they don't have to enable it every time.

### Expected behavior:
When I enable the dark theme setting, it should be stored locally and should be the default theme the next time they visit.

### Steps to reproduce:
Go to p5 web editor.
Enable the dark theme setting.
Close the browser.
Re-open the browser and go to p5 web editor.
Notice that the dark theme setting is not stored locally and has to be enabled again.

### Suggested solution:
Using local storage to store the theme setting would be a great addition. This way, the setting would persist even after the browser is closed and re-opened or refreshed.

Thanks.

**Comment by dewanshDT** [comment]
I'm on it

**Comment by raclim** [comment]
Thanks for bringing this up! 

After giving this some thought I think for now I'd like to preserve as little information as possible about anonymous users, and feel that although it might be a bit inconvenient to update the theme preference each time, the action itself isn't too time consuming or the user could resolve this by creating an account. However, I also understand if others feel differently or see having these preferences stored as more accessible—this might be something to revisit again in the future!
