### ISSUE TITLE
How to get google id and secret?

### ISSUE THREAD

**Issue by Kirito-Excalibur** [processing/p5.js-web-editor#2146]
Since google+ api is depreciated. What's the alternative? Also mailgun is paid service with no free service, so do i need to buy it to develop p5.js-web-editor, or is there any alternative?

**Comment by raclim** [comment]
The Google Client and Secret ID are OAuth 2.0 credentials, which you can obtain through the Google Developer console. [This article outlines more about this process](https://developers.google.com/identity/protocols/oauth2).  

No, you do not need to purchase Mailgun to get started with developing with the p5 web editor! I believe that you don't need most of the env variables to begin development unless you're working on a specific portion of the editor that requires it.
