### ISSUE TITLE
Development Installation is not documented properly.

### ISSUE THREAD

**Issue by kr-2003** [processing/p5.js-web-editor#2147]
#### Details about the bug:

- [Development Installation](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md) is not documented properly.
- It has some repetitive points and unnecessary texts (like ======, HEAD etc.)
- Steps to reproduce this:
  * Go to [Development Installation](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md) 

https://user-images.githubusercontent.com/96587705/222942743-f414e826-6791-45ee-8fbb-a8cca17ac30c.mp4

**Comment by parteekcoder** [comment]
hey @kr-2003 there is also #2143 PR for this issue
