### ISSUE TITLE
Text Alignment Issue in Hindi Language

### ISSUE THREAD

**Issue by RamGoel** [processing/p5.js-web-editor#2157]
#### Details about the bug:

- Web browser and version: 110.0.5481.178 (Official Build) (64-bit) (cohort: Stable) 
- Operating System: Windows 10 Version 2004 (Build 19041.1415)
- Steps to reproduce this:

1. Go to https://editor.p5js.org/
2. Switch Language to हिंदी
3. Then click on Settings Icon (Top-right corner)
4. You will see that the text alignment appears broken (it means autosave in English)
5. Image for Reference
![image](https://user-images.githubusercontent.com/71088429/223941335-5f5459e1-d9c2-4568-8c96-ca53684399f7.png)

The reason is that the text above this, "decrease font size" which means (कम करें) in hindi, is overflowing to next row.

**Comment by lindapaiste** [comment]
I'm not actually seeing the behavior that you are describing in my browser.  For me it looks like:
![image](https://user-images.githubusercontent.com/28965286/224186101-f1b3abd6-9ada-4d9b-9951-c4a686d4ded1.png)

However I can force it into the "bad" state by changing the `.preference__label` style from `font-size: .75rem` to `font-size: 1.25rem`.
![image](https://user-images.githubusercontent.com/28965286/224186847-3b3a311f-2e3f-4bfa-a670-f5a06a918aca.png)

With this, I can see that the `line-height` is very high!  It has a `line-height: 3.33333rem` inherited from `.contrast .preference__minus-button`.  This is weird to me and is something that might need rethinking, but the current style is built around this line-height, so the easier solution is to keep the text on one line and then the spacing doesn't matter.

Adding `white-space: nowrap;` to the `.preference__label` class will force it to stay on one line.  The default value for `overflow` is `visible` so it will extend outside of the specified width.

Just a note that this opens the possibility of a horizontal collision if the text is excessively long.  What I mean is this:
![image](https://user-images.githubusercontent.com/28965286/224188178-435a42e4-f9b8-41a4-925c-f3b93b9e123b.png)
However it's still a huge improvement over the current behavior, where the words are on separate very-tall lines:
![image](https://user-images.githubusercontent.com/28965286/224188396-2e684ec6-51b6-4ef9-a7d0-65bff658545d.png)

**Comment by KrishavRajSingh** [comment]
is this open?
I am not able to reproduce

**Comment by mallikaakash** [comment]
This issue is  not reproducible, even when checked responsively. The issue has been resolved.
<img width="212" alt="image" src="https://github.com/processing/p5.js-web-editor/assets/121702227/f8d1b315-e6fe-4ad7-b2b3-e3ba2f227227">
