### ISSUE TITLE
404 page crashes in development mode

### ISSUE THREAD

**Issue by dewanshDT** [processing/p5.js-web-editor#2166]
#### Details about the bug:
the 404 page always crashes in development mode making it annoying for the developer to work with the application.

- p5.js version:  any
- Web browser and version: MS Edge 
- Operating System: windows 
- Steps to reproduce this: just refresh in a non-existing route, or it sometimes happens automatically

![image](https://user-images.githubusercontent.com/71703033/225854744-f2a00f0f-3a7a-4b0c-a252-4911d41e2a18.png)

**Comment by lindapaiste** [comment]
I personally have not experienced this.  It may have to do with the server/database not being set up on your end. There are a few issues and PRs regarding whether it's possible to develop the frontend without having to setup mongodb:

- #1348 
- #1999
- #1415 
- #1257

I also think it's weird that the 404 page is rendered on the server and I opened an issue about that:
- #2159 

This is what I see:
![Screenshot 2023-03-17 21 27 51](https://user-images.githubusercontent.com/28965286/226078469-0471e55d-0ec8-4ea4-952a-254b6abb86d1.png)
It doesn't crash, but I also don't get a random sketch displayed like it's supposed to.  Looking at the code, that must mean that I'm in the `else` branch on line 143.  Which I guess means that `User.findOne({ username: 'p5' }` did not find a `user` for me?  Definitely worth digging into more to see what's actually going on.

edit: It seems like in my database I have no `p5` user and in your database you have a `p5` user with 0 sketches.

**Comment by dewanshDT** [comment]
yeah, I don't have anything in my MongoDB database, It's running locally, and connected tho. that's why it's crashing due to 0 sketches. In this PR I just added default values to the arguments which prevented it from crashing even without any sketches. what do you think should I close It? @lindapaiste

**Comment by lindapaiste** [comment]
Not sure.  You've made me realize that I'm missing the p5 examples in my local db so now I'm re-reading the docs on [setting up the development environment](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md).  I think neither of us did step 10 properly.

**Comment by dewanshDT** [comment]
Ohh thanks! I've never thought that before
edit: it still crashes after that though 🤔

**Comment by raclim** [comment]
Hey, thanks for all of your thoughts on this! After thinking about it, I don't think this specific issue is something we'll focus on for now, since as mentioned earlier, I feel that this might be tied to some mishaps in setting up the dev environment. Maybe some updates to the [installation documentation](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md) might need to be made, but I think this might be something to revisit later in the future!
