### ISSUE TITLE
Redundant Scrollbar

### ISSUE THREAD

**Issue by kunxl-gg** [processing/p5.js-web-editor#2171]
Currently when you open the setting tab you see a scrollbar even in the case when there is nothing to scroll to. This isn't a great user experience. The fix should be that the scrollbar should only appear when required.
![image](https://user-images.githubusercontent.com/105335204/226546594-5653cda6-33ec-4813-8314-fee2a348c928.png)

**Comment by lindapaiste** [comment]
Great catch! Let's leave this issue open because there are [a few other uses of `overflow:  scroll`](https://github.com/processing/p5.js-web-editor/search?q=overflow+scroll) which we should examine and possibly change.

**Comment by raclim** [comment]
Thanks for working on this! I agree with looking into other cases of this, but feel like we can possibly open a separate issue for them as well when we pinpoint particular ones we'd like to change!
