### ISSUE TITLE
"Back to Editor" should return to your Sketch with the unique Sketch URL

### ISSUE THREAD

**Issue by dstein-art** [processing/p5.js-web-editor#2175]
I have noticed that if you are currently in a sketch that you are working on, have had it saved, and have the sketches unique URL in the Browsers URL bar... if you go to the "Sketches" or "Collections" menu item and then select "Back To Editor"... it returns you to the editor, it returns you to the source code you were last working on, but the URL is no longer the unique URL, it is https://editor.p5js.org/

Why is this an issue? For people who are using the P5 editor for a class, it is common to share the URL with their classmates. I currently teach Code! 2 at NYU and many of my students have been having trouble getting the unique URL back in the URL bar of the browser.. If a beginner programmer does the steps that I have described above, it is actually tricky to get the Unique URL back, it does not come back by playing or saving... you need to click back on the "Sketches" menu, select your sketch and re-open it, even though it is already opened.

My suggestion is that you should keep track of the URL of the current project, and the "Back To Editor" link should be a URL that brings you back to the project. (I assume the javascript "back" function may be used instead, which is causing the issue)

**Comment by dewanshDT** [comment]
hey @dstein-art thanks for reporting this issue, this has been fixed and will be merged soon 🤞🏻
