### ISSUE TITLE
Improve OG title for linked p5.js sketches

### ISSUE THREAD

**Issue by SableRaf** [processing/p5.js-web-editor#2177]
### **Problem description** 
When sharing a p5.js sketch from the web editor on social media or other websites, the OG title of the resulting webpage only says "p5.js Web Editor". This makes it difficult to distinguish between different linked sketches or know what the sketch is about.

### **Proposed solution** 
Update the OG title to include the title of the sketch and the name of the author, followed by "p5.js Web Editor". For example, the OG title could be "My Sketch by Username - p5.js Web Editor". This would improve the discoverability and sharing of p5.js sketches and help to promote the creators of these sketches.

### How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to the p5.js Editor?

The new feature would help increase access to the p5.js Editor by making it easier for users to share and promote their p5.js sketches on social media and other websites. By improving the discoverability and sharing of p5.js sketches, more people will be exposed to the capabilities of p5.js, and may be inspired to try it out for themselves.

### **Additional information** 
Screenshot from the Processing Foundation forum showing the current behavior is attached below

![image](https://user-images.githubusercontent.com/290261/226952213-391ced7d-5238-4ae5-8fef-162830ff4c4e.png)

**Comment by dewanshDT** [comment]
added this feature ☑️

**Comment by Adityaakr** [comment]
Hey! I would like to work on this issue

**Comment by divyansh2375** [comment]
hey can you assign this issue to me ?

**Comment by arkaslittlemind** [comment]
Hey there! I would like to work on this issue.

**Comment by Nasirahamad88** [comment]
I am already start contribution

**Comment by owais0017** [comment]
assign this to me please.

**Comment by goutamdh** [comment]
Hi folks,

Is this issue still open? I would like to contribute to it.
