### ISSUE TITLE
Turkish Translations

### ISSUE THREAD

**Issue by cemergin** [processing/p5.js-web-editor#2183]
### How would this new feature help increase access to the p5.js Editor?
- Add Turkish translations to the web editor for increased accessibility. 

#### Feature enhancement details:
- Create translation `JSON` into the `locales` folder
- Link to the Turkish translation `JSON` in the `i18n` code. 

[PR Here](https://github.com/processing/p5.js-web-editor/pull/2182)

**Comment by raclim** [comment]
Resolved by https://github.com/processing/p5.js-web-editor/pull/2182 :)
