### ISSUE TITLE
Problems with existing mobile components

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2184]
I'm making this issue to document some of the problems with the existing `MobileIDEView` (and other mobile components) and keep track of them as I fix them.  There are a lot of features that haven't been implemented, but I'm focusing more on bugs and mistakes.

Note that none of the mobile UI is available to end users at the moment due to the `MOBILE_ENABLED` flag, which is `false` in production.

* [x] 1. Theme not applied to Preferences:
Fixed by #2185 

![image](https://user-images.githubusercontent.com/28965286/227730929-54341349-8520-4aa7-a57e-6e486165c2be.png)

* [ ] 2. 404 Not Found error when accessing `/preferences` directly:
These URLs need to be added to the `server` in addition to the `client`.  Which is simple enough, but also annoying and feels fragile.

![image](https://user-images.githubusercontent.com/28965286/227731059-ac5f9862-6cfa-4cc1-81ff-6dccf4e7a384.png)

* [x] 3. App crashes when selecting Theme due to invalid value `"Dark"` instead of `"dark"`.
This gets saved to the user's preferences in the API and cannot be fixed by the user.
Fixed by #2185 

![image](https://user-images.githubusercontent.com/28965286/227731397-2181619e-0fa8-47c2-b673-6476855d74b6.png)

* [x] 4. Prop-types warnings:
Fixed by #2185 

![image](https://user-images.githubusercontent.com/28965286/227730972-f8119430-5095-4137-92bc-8f0c2ed25cc2.png)
![image](https://user-images.githubusercontent.com/28965286/227734094-e39ca09e-9563-495b-8934-712baa126f2d.png)

* [x] 5. Props passed to `PreviewFrame` which don't do anything, because that component only accepts one prop (`fullView`):
Fixed by #2185 

![image](https://user-images.githubusercontent.com/28965286/227734150-920391fe-2e18-4901-994b-b920ce99332f.png)

* [ ] 6. Preview doesn't do anything, due to these `postMessage` errors:
I have not figured out why this works on the desktop version but doesn't work here. 
![image](https://user-images.githubusercontent.com/28965286/227734719-bf6eb921-572c-4944-b67d-36720fbcb4ef.png)

**Comment by dewanshDT** [comment]
hey @lindapaiste I'm already working on these issues on this branch [dewansh-mobile](https://github.com/dewanshDT/p5.js-web-editor/tree/dewansh-mobile), but these issues are not well documented

**Comment by lindapaiste** [comment]
> hey @lindapaiste I'm already working on these issues on this branch [dewansh-mobile](https://github.com/dewanshDT/p5.js-web-editor/tree/dewansh-mobile), but these issues are not well documented

ah cool. I see you found a use for the `FloatingNav`, which I deleted in my PR because it's not used anywhere.  whoops.

I managed to fix most of the issues in my list but not all of them.  I'm mostly trying to get it to a "clean slate" point where you and me and anyone else can work on finishing the mobile UI [redacted] from a better starting point.

**Comment by dewanshDT** [comment]
yeah, that would be great!

**Comment by raclim** [comment]
@lindapaiste Thanks for your work on this so far!

We encourage contributions from all types of learners with varying backgrounds and levels of knowledge, so some of the code in this repository might not reflect as much technical experience as others. I feel that referring to someone else's prior work like that might be discouraging, and kindly suggest aiming towards language that's mindful of everyone's contribution journeys!

**Comment by lindapaiste** [comment]
Closing as stale since we are no longer using these particular components.
