### ISSUE TITLE
Error: p5.js says: p5 had problems creating the global function "createElement" on the default sketch

### ISSUE THREAD

**Issue by codeMGL** [processing/p5.js-web-editor#2189]
#### Details about the bug:

- p5.js version: 1.6.0
- Operating System: Tried on Windows (iPad and PC) and Linux
- Steps to reproduce this:
Only on one of my two p5js accounts, whichever sketch I run (even the default), gives the following error, sometimes along `Script error`:
`🌸 p5.js says: p5 had problems creating the global function "createElement", possibly because your code is already using that name as a variable. You may want to rename your variable to something else. (http://p5js.org/reference/#/p5/createElement) `

I have been searching and this is an error that occured to @Angshu31 on 2020. He opened an issue, now closed, at [link](https://github.com/processing/p5.js/issues/4405)

This is my code (just the default one): https://editor.p5js.org/MarcoGaLo/sketches/CBGQP5A9M
![image](https://user-images.githubusercontent.com/107941587/228460427-18c98d58-edec-4b14-8667-241de9db9f78.png)

**Comment by 3ru** [comment]
@codeMGL 
Is this because the `Accessible text-based canvas' field in the accessibility of the settings is checked?
<img width="370" alt="image" src="https://user-images.githubusercontent.com/69892552/228463287-c99f80b0-960c-40a4-8296-80dda409537e.png">


A similar case has been reported as an existing `p5.accessibility` problem.

**Comment by codeMGL** [comment]
That’s right. I had both checked, but I think I have never toached that options.
If one, or both, are checked, it gives that error, why? What does that make?

**Comment by 3ru** [comment]
@codeMGL 
The only temporary solution is to uncheck both.

This issue is a duplicate of #2188. Please see the referenced issue for more information🙏🏻

**Comment by codeMGL** [comment]
Ok. Thanks for the help
