### ISSUE TITLE
Uncaught ReferenceError: frameCount is not defined in instance mode

### ISSUE THREAD

**Issue by KevinWorkman** [processing/p5.js-web-editor#2193]
I'm trying to use instance mode in the p5 editor: https://editor.p5js.org/KevinWorkman/sketches/51ol4wQej

But I'm getting an error: 

```
Uncaught ReferenceError: frameCount is not defined
    x.name https://cdn.jsdelivr.net/gh/processing/p5.accessibility@0.1.1/dist/p5-accessibility.js:1817
    _setup https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.0/p5.js:51458
    _start https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.0/p5.js:51404
    p5 https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.0/p5.js:51759
    <anonymous> blob:https://preview.p5js.org/8875df3e-44f2-4122-afb6-4252c74a1814:12
```

The same code works outside the the p5 editor: https://replit.com/@KevinWorkman/p5-instance-mode

I get a slightly different error if I include p5.sound in the p5 editor (which is the default), but my guess is it's the same underlying cause.

**Comment by 3ru** [comment]
I assume this is probably a problem with `p5.accessibility`.
If you try and turn off both accessibility settings, I think that error will disappear.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/69892552/228463287-c99f80b0-960c-40a4-8296-80dda409537e.png">

I have not yet been able to investigate this issue, but it is currently being worked on by lindapaiste.
- #2188

**Comment by raclim** [comment]
Thanks for reporting this! I'm closing this for now, but please feel free to reopen this or create a new issue!
