### ISSUE TITLE
Bionic reading support for the editor

### ISSUE THREAD

**Issue by GoldyStuff** [processing/p5.js-web-editor#2203]
### Increasing Access

Bionic reading is a font that just makes everything easier to read, would be cool as something toggle-able.

https://bionic-reading.com/

### Feature request details

A toggle button on the options page

**Comment by raclim** [comment]
I think this would be cool, but unsure if this is something we'd address in the near future! I'm going to close this for now, but will add it to [this project board](https://github.com/processing/p5.js-web-editor/projects/11) to potentially revisit later!
