### ISSUE TITLE
Web editor download link is broken

### ISSUE THREAD

**Issue by blinkandhum** [processing/p5.js-web-editor#2205]
### p5.js version

1.6.0

### What is your operating system?

Mac OS

### Web browser and version

Safari 16.3

### Actual Behavior

Firstly, sorry I could not figure out how to report this as a website issue, the web issues item is a circular link back to reporting any issue... 

When using the p5 editor, if I go to File->Download, it *was* timing out with a Cloudflare error showing the server as down. I say was because while submitting this issue, it seems to have resolved. 

My reason for filing an issue is that I'm thinking about doing an online meetup teaching some basic coding and might use p5/p5 editor in that meetup, so I'm wanting to make sure the editor doesn't have common downtime. Can you let me know if this is a frequent issue? Note that the editor was still working fine, just the download option timed out repeatedly. 

### Expected Behavior

Was expecting to be able to download sketch as files or a zipped folder. 

### Steps to reproduce

The issue has resolved for now, but was happening when selecting File->Download from the editor https://editor.p5js.org

**Comment by raclim** [comment]
Hi @blinkandhum, thanks for reporting this! We've had previous issues with downloading sketches in the past, but there haven't been any known ones mentioned recently. Some factors that have affected this are larger sketch sizes or weaker internet connection, which might be something to note if you choose to use the p5 web editor for your meetup!

**Comment by blinkandhum** [comment]
The returned page was a Cloudflare page saying the server was down, btw.
But I'll keep in mind larger sketch sizes and slower internet connections
might impact the download feature. Good to know. Thx.

**Comment by raclim** [comment]
Thanks again for sharing this, we'll keep an extra eye on Cloudflare as well! I'm going to close this for now, but please feel free to reopen this or create a new issue if this persists!
