### ISSUE TITLE
Cannot login with Github

### ISSUE THREAD

**Issue by schlachtzeuger** [processing/p5.js-web-editor#2208]
### What is your operating system?

Windows

### Web browser and version

112.0.5615.138

### Actual Behavior

When I log in using Github, I still see the links to "Login or Sign Up".

### Expected Behavior

To be greeted with my handle and to be able to access my sketches.

### Steps:
1. In the editor, click on "Log in"
2. Select Login with Github
3. Enter credentials -> you're forwarded to the editor

**Comment by raclim** [comment]
Thanks for reporting this! Just to get better insight into what's happening, do you have 2-factor authentication for your Github account?

**Comment by schlachtzeuger** [comment]
yes, I do have 2FA activated

**Comment by virusinlinux** [comment]
This issue has been resolved!! Please close this Issue

**Comment by hanseo** [comment]
I have exactly the same issue. The only difference is I'm using the Brave browser.
