### ISSUE TITLE
Random characters being deleted when switching between files

### ISSUE THREAD

**Issue by piecesofuk** [processing/p5.js-web-editor#2221]
### p5.js version

1.6.0

### What is your operating system?

Other (specify if possible)

### Web browser and version

Chrome Version 113.0.5672.134 (Official Build) (64-bit)

### Actual Behavior

I'm editing on a Chromebook, os version as above.

I've noticed this has been happening for a while but wasn't sure if it was just random: when I was switching between files it seemed as if characters were being deleted at random.

### Expected Behavior

Characters should not be randomly disappearing

### Steps to reproduce

The following steps appear to reproduce this behaviour:
1. create a new sketch
2. open index.html
3. make an edit that generates an error, for example I've add a < at the start of line 1
![Screenshot 2023-05-28 06 42 03](https://github.com/processing/p5.js-web-editor/assets/578197/077ee732-43f5-489a-a89f-32d9a1dc917d)
4. move to sketch.js
5. place the cursor at the end of the file
6. note the first five characters of line 5 are underlined
![Screenshot 2023-05-27 21 34 06](https://github.com/processing/p5.js-web-editor/assets/578197/8f1003d5-a02b-4b08-af2d-c41515c8a83f)
7. hit return to create a new line
8. those five characters are deleted
![Screenshot 2023-05-27 21 34 38](https://github.com/processing/p5.js-web-editor/assets/578197/3121a9bb-92d2-4a2b-bb15-becbe2c662e6)

**Comment by praveen-rikhari** [comment]
@piecesofuk is this issue still opened?
If Yes, can i work on this.
