### ISSUE TITLE
collection description `EditableInput` text doesn't change color on hover - CSS Specificity

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2223]
### What is your operating system?

None

### Actual Behavior

This is the current behavior of the `EditableInput` when there is an existing description on the collection.

normal:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/b88c36f4-583c-4199-a58b-9d52b97c9643)
hover:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/ebabb584-56c9-4ef1-89a6-ec1e2c4ccf23)

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/e20ecea0-dda0-4774-a0bd-6cba23e156d0)

### Expected Behavior

This is the current behavior when there is no existing description.

hover:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/c351c84c-491c-4404-b2a2-44beaf5a4696)

### Steps:
1. View the collection details page for a collection which you own
2. Give it a description
3. Hover over the description name
4. Notice that the pencil turns pink but the text does not

----

The text of an existing collection description does not change color when hovered.  If there is no existing description, then the words "Add description" will be pink when hovered.

I believe this is a mistake, but perhaps it's the intended behavior.  Can anyone confirm if we do or don't want the text to be pink when hovered?

We have a style targeting the `.editable-input__label` when it is used inside of `.editable-input--has-value` inside of `.collection-metadata__description`
https://github.com/processing/p5.js-web-editor/blob/7212f76f6261ad52a33c9c87e17e5d90be903b3c/client/styles/components/_collection.scss#L77-L81

This selector is very specific, so it takes priority over the `:hover` style of `button.editable-input__label`.
https://github.com/processing/p5.js-web-editor/blob/7212f76f6261ad52a33c9c87e17e5d90be903b3c/client/styles/components/_editable-input.scss#L7C1-L21

The specific selector only applies to non-empty descriptions (due to the `.editable-input--has-value` class) so the hover effect still works if the description is empty.

We can fix this by appending a `:not(:hover)` to the override style in `_collection.scss`.

**Comment by adadgarg** [comment]
@lindapaiste After editing the title, it turns pink while hovering, so I think it's a bug, it should also be the same for the description.
