### ISSUE TITLE
Better SEO title needed on collection details pages

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2251]
### Increasing Access

- Help users find relevant collections via search engines
- Allow users to better identify what pages they have open in their browser when looking at the tab titles

### Feature enhancement details

When looking at the details page for an individual collection, for example https://editor.p5js.org/codingtrain/collections/bD7HTvWYL, the `<title>` meta tag is not very descriptive as it does not contain the name of the collection.

The current title is:
```
<title>p5.js Web Editor | codingtrain's collections</title>
```
A better title would be something along the lines of:
```
<title>p5.js Web Editor | Nature of Code Videos Chapter 3</title>
```
We could include the username, but it verges on too long depending on the collection name (it should be roughly 50-70 characters for SEO purposes but this one is 78 characters) 
```
<title>p5.js Web Editor | Nature of Code Videos Chapter 3 | Collection by codingtrain</title>
```

I personally prefer putting the website at the end of the title rather than at the start, but we put it at the start in all other places.  So that's a separate issue.

**Comment by adadgarg** [comment]
@lindapaiste how about this title:   <title>p5.js Editor | Nature of Code Ch. 3 | codingtrain's Collections</title>

**Comment by tb-rules10** [comment]
Hey @lindapaiste , I'd like to work on this issue. Can you assign me this?
