### ISSUE TITLE
Confusing icons in `QuickAddList`

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2255]
### Increasing Access

It will be easier to make selections if it is obvious which items have already been selected.

### Feature enhancement details

This screenshot shows the UI when I click "Add Sketch" on a collection details page.  The first sketch in the list ("Stormy Sandalwood") is already in  the collection and the other two are not.  But there is no way to know that unless you hover over the ✔️ icon, where you will see either a ❌ to remove the item if it is already added or a ➕ to add the item if not.  This is not great in general but it's totally unusable on touch devices where there is no hover.  A user will not know what clicking the icon is going to do: will it add or remove?

The ✔️ does not mean anything as all items show the ✔️.  In my opinion, we should only show the ✔️ for items which are already in the collection.

As for the items which are not in the collection, we could show the ➕ all the time and not just on hover.  I've also had a look at @shujuuu's [mobile design for this component](https://www.figma.com/file/27wGlxCRns7tyXoEIbcmTA/p5-Mobile---2020?type=design&node-id=199-126&t=VAxy4ru1Z5s71j7n-0).  She is using more of a "radio button" type look, where there is a very clear and obvious ☑️ for items which are added and an empty circle ⚪ for items which can be added by clicking.  If @dewanshDT gets around to creating this radio button element for his GSoC project then we should use that element on the web version as well.  It would definitely be an improvement to usability.

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/c8f1d994-4536-4fa1-b5b7-f018f44451b0)

We show this `QuickAddList` modal:
- With a list of collections, when clicking "add to collection" from the editor.
- With a list of sketches, when clicking "add sketch" on the collection.

**Comment by dewanshDT** [comment]
I think this is a necessary enhancement in terms of user experience

**Comment by Ankush263** [comment]
Hey @lindapaiste, can u assign me to this issue, I can change the UI

**Comment by luckyklyist** [comment]
Hello, @lindapaiste . I've submitted a pull request for this issue. I'm looking forward to your review. Thank you! #2438
