### ISSUE TITLE
Duplicate function in menu does not work.

### ISSUE THREAD

**Issue by shibomb** [processing/p5.js-web-editor#2276]
### p5.js version

Web Editor: v2.6.1  p5.js: v1.6.0

### What is your operating system?

Mac OS

### Web browser and version

Chrome 114.0.5735.133 (Official Build) （arm64） 

### Actual Behavior

Sketch is not duplicated.
The following was displayed in the console log
```sh
Uncaught TypeError: Cannot read properties of undefined (reading 'map')
    at project.js:298:28
    at index.js:8:18
    at n.<computed> (bindActionCreators.js:9:16)
    at Object.m (react-dom.production.min.js:15:205)
    at w (react-dom.production.min.js:15:359)
    at react-dom.production.min.js:16:35
    at k (react-dom.production.min.js:16:236)
    at T (react-dom.production.min.js:17:248)
    at A (react-dom.production.min.js:17:57)
    at _ (react-dom.production.min.js:17:412)
```

### Expected Behavior

The sketch should be duplicated.

### Steps:
1. open your existing sketch in https://editor.p5js.org/
2. select Menu File > Duplicate

**Comment by raclim** [comment]
Thanks for catching this! I'll start working on a fix for this.

**Comment by lindapaiste** [comment]
@raclim It was my fault! 😱

**Comment by raclim** [comment]
@lindapaiste Oh no, not at all 😂 I should've tested it more thoroughly as well!
