### ISSUE TITLE
Keyboard shortcut for "Tidy code" shows "Replace"

### ISSUE THREAD

**Issue by astralBuddy** [processing/p5.js-web-editor#2278]
### p5.js version

/*! p5.js v1.6.0 February 22, 2023 */

### What is your operating system?

Windows

### Web browser and version

114.0.5735.199 (Official Build) (64-bit) (cohort: Stable) 

### Actual Behavior

[ctrl + shift + F] shows the "Replace" box

### Expected Behavior

[ctrl + shift + F] should Tidy Code

### Steps:
1. Open https://editor.p5js.org/
2. Press [ctrl + shift + F]

**Comment by SpicyMelonYT** [comment]
yeah this has ruined my work flow. I am so confused why this would happen

**Comment by astralBuddy** [comment]
Thanks guys! It’s been so cool following your work. You rock.
