### ISSUE TITLE
Vertex not working with rotate() in loop

### ISSUE THREAD

**Issue by lukevanlukevan** [processing/p5.js-web-editor#2279]
### p5.js version

Web Editor

### What is your operating system?

Mac OS

### Web browser and version

Microsoft Edge	114.0.1823.58

### Actual Behavior

Within the for loop after calling rotate(), vertex is not created, unlike point() where the dot does show.

example sketch:
https://editor.p5js.org/lukevrensburg/sketches/G9aTt0en6

### Expected Behavior

For loop will create vertex at position expected after rotate() is called

### Steps to reproduce

```
function setup() {
  createCanvas(400, 400);
  angleMode(DEGREES)
  ellipseMode(CENTER)
  
  background(220);
  translate(width/2, height/2)
  strokeWeight(2)
  fill(255)
    
  beginShape()
  for(let i = 0; i < 50; i++){
    let r = 360/50
    vertex(50,0)
    point(50,0) // where vertex should be
    rotate(r)
    
  }
  endShape(CLOSE)
}
```

**Comment by astralBuddy** [comment]
The [reference](https://p5js.org/reference/#/p5/beginShape) states:
> Transformations such as [translate()](https://p5js.org/reference/#/p5/translate), [rotate()](https://p5js.org/reference/#/p5/rotate), and [scale()](https://p5js.org/reference/#/p5/scale) do not work within [beginShape()](https://p5js.org/reference/#/p5/beginShape).

Oh, and you should call rotate before the thing you want to do it to. I don’t think this is the way to do what you are trying. 
Check out [this video](https://youtu.be/76fiD5DvzeQ) from the coding train at around 8 min.

**Comment by lukevanlukevan** [comment]
Ah I see, that's a lack of reading on my part.

I call rotate after as I wanted my first vertex to be at 0 rotation, so thats why I called it after.
Thanks for the feedback @astralBuddy, I don't imagine this is reasonable to implement or the team would have done so already.
Thanks for the help!
