### ISSUE TITLE
text overflow

### ISSUE THREAD

**Issue by asukaminato0721** [processing/p5.js-web-editor#2280]
### p5.js version

1.6.0

### What is your operating system?

Linux

### Web browser and version

1.52.126 Chromium: 114.0.5735.133

### Actual Behavior

![image](https://github.com/processing/p5.js-web-editor/assets/30024051/0b47fb82-f769-4ee5-bd69-170d06d70c41)

CSS IS AWESOME

### Expected Behavior

text not overflow

### Steps:
1. open the p5.js editor.
2. put the browser at half left/right of the screen.
3. Help > About

### Snippet:
```js

// Paste your code here :)

```

**Comment by swaroopdiwakar007** [comment]
Hey, scroll can be added here to control the overflow if needed.

**Comment by itsajay1029** [comment]
Can you assign this issue to me and explain on what needs to be done ? @swaroopdiwakar007

**Comment by adadgarg** [comment]
@raclim I have opened a pr that can close the issue.

**Comment by raclim** [comment]
Resolved by #2290!
