### ISSUE TITLE
Navigation Bar UX

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#229]
We need to add some hierarchy of information in the navigation bar...

@kshivanku

**Comment by kshivanku** [comment]
Cassie, I was taking this up, just wanted to make sure I have all the items in the nav bar covered. I can see:
1. New
2. Save
3. Open (if user is logged in)
4. Examples
5. Reference
6. About
7. User Settings (Login/Logout)

Did I miss anything? I'll propose something scalable but it would be helpful to know if there are any immediate additions planned for nav bar.

**Comment by kshivanku** [comment]
Hi Cassie,
I did a quick iteration on the nav bar, just wanted to share to get some early feedback. 

**Following were the goals:**
1. Improve hierarchy
2. Make it scalable

**Following were the issues with hierarchy:**
![designissues](https://cloud.githubusercontent.com/assets/12475379/22049209/e4779030-dcff-11e6-9182-a9bd889871e6.jpg)

**Proposed design solution:**
![flat_nav](https://cloud.githubusercontent.com/assets/12475379/22049444/383bbbd2-dd01-11e6-9989-ae2461b7877f.jpg)

**Scalable option**
![nested_nav_1](https://cloud.githubusercontent.com/assets/12475379/22049449/3d191992-dd01-11e6-8772-5c0b4a3c13aa.jpg)
![nested_nav_2](https://cloud.githubusercontent.com/assets/12475379/22049452/413857cc-dd01-11e6-9d51-d6e0400e6152.jpg)

With the navbar items that we currently have, I think we can keep it simple and have two levels. The most used items upfront and rest one level deep inside “more”.

**Comment by catarak** [comment]
this looks great! you missed a couple of navigation items but it should be too hard to integrate them:
- Duplicate
- Download
- Share

I think it's also important to note that as it is now, certain navigation items are or are not shown depending on if a user is logged in or if a sketch has been saved. I think it makes sense to keep this functionality.

**Comment by kshivanku** [comment]
Awesome, thanks @catarak.

I have included the missing functions and made mockups for the following states:
1. Logged out, new sketch
2. Logged out, someone else's sketch
3. Logged in, new sketch, unsaved
4. Logged in, own sketch, saved
5. Logged in, someone else's sketch

Here are the mockups:

**1. Logged out, new sketch**

![5 loggedout](https://cloud.githubusercontent.com/assets/12475379/22078772/3c9711f0-dd87-11e6-98d6-5f5921e13e42.jpg)

**2. Logged out, someone else's sketch**

![6 loggedout_other_user s_sketch](https://cloud.githubusercontent.com/assets/12475379/22078794/51a12f68-dd87-11e6-85fb-3d8aba8cd95d.jpg)

**3. Logged in, new sketch, unsaved**

![1 on_landing](https://cloud.githubusercontent.com/assets/12475379/22078812/620c0e54-dd87-11e6-9dca-b1d6098c5559.jpg)

![2 more_options](https://cloud.githubusercontent.com/assets/12475379/22078821/6c89bbba-dd87-11e6-9049-69b90752a632.jpg)

**4. Logged in, own sketch, saved**

![3 on_save](https://cloud.githubusercontent.com/assets/12475379/22078839/7c95384a-dd87-11e6-987c-0759b7943bd4.jpg)

**5. Logged in, someone else's sketch**

![4 other_user s_sketch](https://cloud.githubusercontent.com/assets/12475379/22078848/88d27898-dd87-11e6-80e1-11a862944f8b.jpg)

**Comment by catarak** [comment]
# Design
<img width="922" alt="screen shot 2017-07-11 at 9 44 25 am" src="https://user-images.githubusercontent.com/6063380/28071396-caa13466-661d-11e7-8402-e325a201d5bd.png">
<img width="922" alt="screen shot 2017-07-11 at 9 43 43 am" src="https://user-images.githubusercontent.com/6063380/28071401-cc495618-661d-11e7-8070-4ab736b7d577.png">
<img width="921" alt="screen shot 2017-07-11 at 9 44 03 am" src="https://user-images.githubusercontent.com/6063380/28071403-cec8bfaa-661d-11e7-84b1-86d2d8a40243.png">

See more details on the [Zeplin project](https://zpl.io/Z2cihf1).

**Comment by shiffman** [comment]
This is so exciting to see pushed live! Great work @catarak and everyone! 👏👏👏
