### ISSUE TITLE
Keyboard shortcut content overflow in small screen

### ISSUE THREAD

**Issue by adadgarg** [processing/p5.js-web-editor#2291]
### What is your operating system?

Windows

### Web browser and version

Chrome version :114.0.5735.198

### Actual Behavior

![Screenshot 2023-07-13 114238](https://github.com/processing/p5.js-web-editor/assets/104292766/9f0cc9e1-3d97-4c62-80af-b1b3ef45ba89)

### Expected Behavior

![2](https://github.com/processing/p5.js-web-editor/assets/104292766/4db1b7c9-d67e-400c-839b-b8db4df17aae)

### Steps to reproduce

1. open the p5.js editor.
2. make the viewport width less than 700px.
3. Go to Help then Keyboard Shortcuts

Similar to issue #2280.

**Comment by adadgarg** [comment]
@raclim PR #2290 can solve the issue. By removing the max width property from the overlay body css

**Comment by raclim** [comment]
Thanks @adityagarg06 for catching this! I just merged #2290 in, so I'm going to close this :)
