### ISSUE TITLE
Project folders / subfolders

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#23]
Some of the teachers mentioned today that they like their students to organize their projects into subfolders.  cloud9 as a model was mentioned.

<img width="194" alt="screen shot 2016-07-21 at 2 45 35 pm" src="https://cloud.githubusercontent.com/assets/191758/17034703/d7a212ae-4f51-11e6-9209-2b4fb34399d6.png">

**Comment by catarak** [comment]
Just for everyone's info, I've been trying to implement this and it's taking a lot of time! Recursive tree structures are hard.

**Comment by catarak** [comment]
woohoo just pushed this to master!

**Comment by catarak** [comment]
just kidding, need to do a database migration before I merge this.
