### ISSUE TITLE
Legacy code for an unreachable collection /create page

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2300]
### Increasing Access

Cleans up the codebase.

### Feature enhancement details

In its current state, the [`CollectionView` component](https://github.com/processing/p5.js-web-editor/blob/4161f98c2127bbead3e317c699694589add135ce/client/modules/User/pages/CollectionView.jsx) doesn't do much of anything.  There are two internal methods which are never called and a boolean check `isCreatePage` which will always be `false`.

The `CollectionView` is the route handler for the path `"/:username/collections/:collection_id"`.  It switches between displaying a single `Collection` and displaying the `CollectionCreate` UI based on whether the `collection_id` portion of the URL is the word `"create"` rather than a valid ID.

**But the `"/:username/collections/create"` URL is impossible to reach**, as [the server only checks for a valid collection ID](https://github.com/processing/p5.js-web-editor/blob/4161f98c2127bbead3e317c699694589add135ce/server/routes/server.routes.js#L124-L128) and will return a 404 page.

My plan is to delete the useless code.  However we could make the `"/:username/collections/create"` URL work if we wanted to.  Right now the UI for creating a collection is a modal that pops up over the `"/:username/collections"` page.  There is no dedicated URL for this.

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/1f6116b8-a2d7-4222-baed-44ed17f303f5)

If the server code is changed, this is what would be displayed:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/7570cd12-c823-49a1-b2a4-33668c46452c)

**Comment by Praveen03AJJARAPU** [comment]
I have an issue while running the project, when I am making changes to the code on the editor it is not showing me the changes on the localhost:8000. I have made many changes to my code but it is not updating, all the setup is done well. To see the changes I have to restart the docker containers and restarting the process takes more than 4 minutes. Can anyone help me out?
