### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by JasonGoemaat** [processing/p5.js-web-editor#2305]
### p5.js version

v1.7.0

### What is your operating system?

Windows

### Web browser and version

Chrome -114.0.5735.199

### Actual Behavior

Fresh clone of `git@github.com:processing/p5.js-web-editor.git` on 2023-07-15.    Using node v16.15.0 on windows.  `npm install` fails, apparently with mis-matched storybook versions somewhere:

```
D:\src\github\processing\p5.js-web-editor>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @storybook/addon-knobs@7.0.2
npm ERR! Found: @storybook/addons@5.3.21
npm ERR! node_modules/@storybook/addons
npm ERR!   dev @storybook/addons@"^5.3.21" from the root project
npm ERR!   @storybook/addons@"5.3.21" from @storybook/addon-links@5.3.21
npm ERR!   node_modules/@storybook/addon-links
npm ERR!     dev @storybook/addon-links@"^5.3.21" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @storybook/addons@"^7.0.0" from @storybook/addon-knobs@7.0.2
npm ERR! node_modules/@storybook/addon-knobs
npm ERR!   dev @storybook/addon-knobs@"^7.0.2" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @storybook/addons@7.0.27
npm ERR! node_modules/@storybook/addons
npm ERR!   peer @storybook/addons@"^7.0.0" from @storybook/addon-knobs@7.0.2
npm ERR!   node_modules/@storybook/addon-knobs
npm ERR!     dev @storybook/addon-knobs@"^7.0.2" from the root project
```

Creating the docker succeeded, so I thought it might be something with Windows.   So I installed nvm and the LTS version of node (18.616.1) and got the same thing.   Then I tried building the Dockerfile and that worked.   Looking at the output I see it was using 16.14.2.   I used nvm to switch to version 16.14.2 in WSL and I was able to install and build.  Changing the node version in the Dockerfile to 16.20.1 produces the same error trying to build with docker.

Also it initially shows vulnerabilities:

```
22 vulnerabilities (1 low, 9 moderate, 9 high, 3 critical)
```

After `npm audit fix`:

```
16 vulnerabilities (7 moderate, 6 high, 3 critical)
```

### Expected Behavior

For the build to succeed with newer versions of node

### Steps:
1. Be using current 16.x or 18.x node version LTS
2. Clone p5.js-web-editor repository
3. Run `npm install`

-or-

1. Change first line in DockerFile to use a more recent version of node:
        FROM node:16.20.1 as base
2. Run `docker build .`

**Comment by wong-justin** [comment]
I experienced the same error too. This was on WSL, using npm version 8.19.4. And a workaround was using `npm install --legacy-peer-deps`.

But that was ignoring when the contributor docs told to use npm version 8.5.0. And package.json says the node version is pinned at 16.4.2 as well. So the install worked after all when using npm 8.5.0.

As for vulnerabilities, I think that's just a given on any project using npm, and the messages kinda get ignored for better or worse.

**Comment by raclim** [comment]
Yes, as @wong-justin mentioned, following the [installation guide](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md) within the contributor docs, the current version of the web editor will only build properly using Node `v16.14.2` and npm `v8.5.0`. Different projects usually use different versions Node, which you can manage using the Node Version Manager. 

The Node version will need to be updated later on, but I don't think this is something we're planning to do in the near future for now!
