### ISSUE TITLE
p5 Editor not allowing duplication or download of one specific sketch

### ISSUE THREAD

**Issue by scottnelson935** [processing/p5.js-web-editor#2314]
### p5.js version

1.6.0

### What is your operating system?

Mac OS

### Web browser and version

Chrome 114.0.5735.198

### Actual Behavior

p5 editor account Evs is able to save/duplicate /download all sketches except one, where duplication/download do not work, but is able to save. The sketch is:

https://editor.p5js.org/Evs/sketches/3IzmbC3MI

When we attempt to download the project, it returns the following error:

{"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:538:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1345:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","config":{"url":"https://assets.editor.p5js.org/64ac52b7d8a9b3001add1e92/852ddc8a-94f9-4fc1-95f0-3faa09af34e3.png","method":"get","headers":{"Accept":"application/json, text/plain, */*","User-Agent":"axios/0.21.4"},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"arraybuffer","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}

### Expected Behavior

the sketch should have no problem duplicating or downloading the sketch when calling those functions.

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)

https://editor.p5js.org/Evs/sketches/3IzmbC3MI

**Comment by lindapaiste** [comment]
This happens when a sketch includes an uploaded asset which has been deleted.  The part of the code which tries to fetch that asset fails with a 404 error.  In this case the problem file is `heart.png` which is in the `assets` folder, though it doesn't seem to be referenced in the code for the sketch.

It definitely needs to be handled better.  Probably just skip over any files which are missing?

**Comment by scottnelson935** [comment]
That makes sense - thanks so much for your help!

-Scott
