### ISSUE TITLE
UI/UX Mobile Responsiveness Issues

### ISSUE THREAD

**Issue by adadgarg** [processing/p5.js-web-editor#2317]
### What is your operating system?

Windows

### Web browser and version

Chrome version :114.0.5735.198

### Actual Behavior

![1](https://github.com/processing/p5.js-web-editor/assets/104292766/a7f71654-0e5d-4202-87c3-f4429eb77544)
![3](https://github.com/processing/p5.js-web-editor/assets/104292766/8d3d9895-dc2e-4e2f-ace2-d05a244a84ae)
![2](https://github.com/processing/p5.js-web-editor/assets/104292766/b376a7d9-1c07-4bf4-a22c-6e04df873267)

 Some pages have responsiveness issues.

### Expected Behavior

The pages should be mobile responsive.

### Steps:
 Go to my collection and add collection and make the viewport width less than 600px;

**Comment by dewanshDT** [comment]
👋 hey @adityagarg06, Thank you for engaging with our project! We appreciate your interest in this issue. Please note that it's already being worked on. Before raising a new issue, kindly check if it's already been reported to avoid duplication. Your contributions are valuable, and we look forward to your continued support. Feel free to share any other questions or suggestions. Thanks again for being part of our community!
