### ISSUE TITLE
Question about translations: should we translate the words "Web Editor"?

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2322]
### Increasing Access

Users in other countries/languages might better understand what they are looking at.

### Feature enhancement details

I'm looking through the translation files and I noticed that we are not consistent about how we translate the phrase "p5.js Web Editor".  Some languages translate "Web Editor" literally, while others keep it as-is in English.  Which is the preferred way?

| language | translation | localized? |
| --- | --- | --- |
| de | p5.js Web Editor | |
| en-US | p5.js Web Editor | ✅  |
| es-419 | Editor Web p5.js | ✅  |
| fr-CA | Editeur web p5.js | ✅  |
| hi | p5.js वेब एडिटर" | ✅  |
| it | p5.js Web Editor | |
| ja | p5.js Web Editor | |
| ko | p5.js 웹에디터 | ✅  |
| pt-BR | Editor de Web p5.js | ✅  |
| sv | p5.js Webb editor | ✅  |
| tr | p5.js Web Editör | ✅  |
| uk-UA | p5.js Web Editor | |
| zh-CN | p5.js 在线编辑器 | ✅  |
| zh-TW | p5.js Web Editor | |

**Comment by adadgarg** [comment]
Should I change the translation.json files with the correct "Web Editor" translation?

**Comment by Akhilbisht798** [comment]
Hey i have actually solved this issue in my pr.
pr -  #2471
As we have discuss about it.
