### ISSUE TITLE
window.p5._report is not defined

### ISSUE THREAD

**Issue by quinton-ashley** [processing/p5.js-web-editor#2327]
### p5.js version

v1.7.0

### What is your operating system?

Mac OS

### Web browser and version

114.0.5735.198 (Official Build) (arm64) 

### Actual Behavior

Only when using the p5.js web editor I get an error saying _report is not defined at undefined.

It's on line 105 of previewEntry.js 
```js
// Monkeypatch p5._friendlyError
const { _report } = window.p5;
```

It seems window.p5 doesn't exist at that point.

### Expected Behavior

No errors.

### Steps to reproduce

Press play to see the error show up in the console:

https://editor.p5js.org/quinton-ashley/sketches/B9bcs2HOK

Working example with no errors:

https://editor.p5js.org/quinton-ashley/sketches/aRSwZGkfg

**Comment by quinton-ashley** [comment]
@davepagurek said that the error was caused by my script tags being at the end of the `body` tag and not inside the `head` tag of my html. The fix was simple, I just moved the tags.

If I'm not mistaken though, it's pretty typical to add script tags at the end of the `body` tag, so this issue should still be fixed imo.

**Comment by lindapaiste** [comment]
Interesting!  That `previewEntry.js` file where the error is gets built into a file `previewScripts.js`. It is definitely injected into the `<head>`.  We could potentially move it to the end of the `<body>` to ensure that the code which loads p5 is always called first.

Here's where we add it to the `<head>`.
https://github.com/processing/p5.js-web-editor/blob/59326e889598b69bb06b591c1606ba0b8aa2a04e/client/modules/Preview/EmbedFrame.jsx#L250-L255

**Comment by Ankush263** [comment]
Hey @lindapaiste, I solved this issue locally. I'm going to open a PR for this 🧑‍💻
