### ISSUE TITLE
What would be a great new feature to add in the web editor? I would love to work on it!

### ISSUE THREAD

**Issue by krshubham** [processing/p5.js-web-editor#233]
I was wondering about a cool feature to add in the web editor that would be challenging and fun to do!
I would love to spend my entire fellowship( if offered) contributing towards the project!

**Comment by catarak** [comment]
Hey Kumar, there's tons of stuff to work on! I think a good place to start is looking through the existing issues. Feel free to suggest something outside of these issues as well. I think a good starting point is the mission statement on the [Processing Foundation website](https://processingfoundation.org/)
