### ISSUE TITLE
Sidebar dropdown stays open after sidebar is closed

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2338]
### What is your operating system?

None

### Actual Behavior

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/68398ea0-7bea-4096-a2ea-484cebb42ad2)

### Expected Behavior

It should be hidden when the sidebar is closed.

### Steps:
1. Click on the ">" button to open the sidebar with the file list
2. Click on the 🔻 icon next to "Sketch Files"
3. Click on the "<" button to close the sidebar

**Comment by mohamedaleya** [comment]
Hi, I'm working on this if you don't mind!

**Comment by mohamedaleya** [comment]
Fixed this, will be making a pull request soon!

![chrome_FgGrV33k5f](https://github.com/processing/p5.js-web-editor/assets/43639707/e611d1d8-c980-4d9f-ac0c-aba93c3568bb)
