### ISSUE TITLE
Adding the filename to the link

### ISSUE THREAD

**Issue by RandomGamingDev** [processing/p5.js-web-editor#2340]
### Increasing Access

Currently, p5.js is decently limited, for example, the fact that to open multiple files at once perhaps to look at one while editing the other, you have to use multiple tabs. While I understand that it's great and advantageous to have people automatically switch to the last file it can be quite annoying when using multiple tabs for code editing. Not to mention the fact that you have to have 2 tabs open at once.
Something that would help to help with alleviating this issue without requiring a more complex IDE is to simply use dynamic URLs that specify the file and to allow middle clicking on the files to open the file in a new tab. It'd be small, but it'd help improve the workflow of developers using the editor.

### Feature request details

Add a URL system that specifies the file.
This wouldn't even have to be implemented on the backend, as a `#` could be used in the URL to specify the file instead, with the file choosing done on the frontend.

**Comment by lindapaiste** [comment]
Interesting idea!  I don’t think that this would be too hard to implement.  I’ll see what I can do.

**Comment by RandomGamingDev** [comment]
I meant frontend lol. Accidentally typed the wrong one.

**Comment by RandomGamingDev** [comment]
Also, nice!

**Comment by navyn13** [comment]
There might be more than one projects with same filename, then how should he get sketch

**Comment by RandomGamingDev** [comment]
Add a hash to the end of it

**Comment by RandomGamingDev** [comment]
Or just an index

**Comment by RandomGamingDev** [comment]
The hash would be nicer tho since you'd have to loop over every other project or create a map of all project names if you did an index, but you can just combine the time of creation and name in a hash for the latter without changing much of the other stuff. I feel like we should prioritize changing less if we can so that there's less stuff that can easily break.

**Comment by navyn13** [comment]
If there is any project with spaces ( " " )in its name we can use "%20" or "+"  in the url. But there can be some projects with names eg: ("adam+eve" and "adam eve") by the same user. Because user can save project name with any special character and space without any boundation it will create problem while getting the the sketch. (Like I am user and saved three projects named: "adam eve" , "adam+eve" and "adam%20eve".

**Comment by RandomGamingDev** [comment]
We could always make it so that % or + is represented by another special symbol that doesn't use itself. That way the special stuff like %20 or + could still be used in names and could just be replaced with another symbol, with only special symbols using either.

**Comment by lindapaiste** [comment]
I think y'all are not understanding this feature request.  The **project name** does not matter, or come into play at all.  We are talking about adding the **file name** (actually, the file path) of the file which is currently open in the editor.  Other web IDEs like CodeSandbox do this.  For example, the URL https://codesandbox.io/s/circle-to-square-czffk2?file=/src/style.css will go directly to the file `/src/style.css` while https://codesandbox.io/s/circle-to-square-czffk2?file=/src/index.ts will go directly to the `/src/index.ts` file.

I would recommend [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) and [`decodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent) for handling special characters.  This creates an unambiguous 1-to-1 mapping.
