### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by RandomGamingDev** [processing/p5.js-web-editor#2354]
### Increasing Access

When using the p5.js editor it can oftentimes be irritating when the types are different (which is just a normal javascript problem). Typescript would help make developing a lot easier and teach a lot of good coding practices. Not only that, but it'd allow for better hints from the IDE to help boost the developer even more.

### Feature request details

Add typescript support ig lol.

**Comment by lindapaiste** [comment]
I would love this but I'm not sure how difficult it would be to add.  Getting support for TypeScript in the editor is the easy part.  The hard part is executing the TypeScript code to preview your sketch.  We would need to transpile the TS code to JS in order for a browser to execute it.  We currently run some other transformations on the project files (like replacing asset URLs) so it would be something that we handle [at the same place in the code](https://github.com/processing/p5.js-web-editor/blob/develop/client/modules/Preview/EmbedFrame.jsx).

Might be some good info here: https://stackoverflow.com/a/59874612/10431574

**Comment by pujari-shivaraj** [comment]
how can i start to contribute and im new to open source

**Comment by Akhilbisht798** [comment]
@lindapaiste, Hey that stackoverflow might be a great way of doing this. We need to check this out.

**Comment by Vivek7038** [comment]
i really want to work on this . can you assign me this . Just need some clarity do you want me to convert every component to typescript or just need to have types defined somewhere in a new file , Or only required the types defined for some specific components

**Comment by abhi267266** [comment]
Hello @lindapaiste,

I understand that we want to enhance our web code editor by adding TypeScript functionality alongside JavaScript. TypeScript cannot be directly run in the browser, so here's a proposed solution on how we can achieve this:
  
To enable TypeScript support, we'll need to integrate the TypeScript Compiler (tsc) into our project. You can include it in your HTML file using a CDN like this:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/typescript/4.5.2/typescript.min.js"></script>
```
We should provide users with a way to switch between JavaScript and TypeScript modes in our code editor. This could be done using a dropdown menu or a button to select the language mode

When a user selects TypeScript mode or attempts to run TypeScript code, we need to compile their TypeScript code into JavaScript programmatically using the TypeScript compiler (tsc). 
example:
```
function compileTypeScript(typeScriptCode) {
  const compilerOptions = { /* configure TypeScript options here */ };
  const { outputText, diagnostics } = ts.transpileModule(typeScriptCode, compilerOptions);

  if (diagnostics && diagnostics.length > 0) {
    // Handle compilation errors
    console.error(diagnostics);
    return null;
  }

  return outputText;
}
```
After compilation, we can execute the resulting JavaScript code in the browser, just like we do with pure JavaScript code.

if you think this can work you can assing me this issue

**Comment by Vivek7038** [comment]
Looks good,  can you share some online resource to do this

**Comment by Vivek7038** [comment]
I really wanted to learn this

**Comment by lindapaiste** [comment]
> We should provide users with a way to switch between JavaScript and TypeScript modes in our code editor. This could be done using a dropdown menu or a button to select the language mode

It could be as simple as looking at the file extension, and loading Typescript if it's a `.ts`.  We have to make sure that we add `.ts` to our regex for validating file names.

Having the user click a button that adds the typescript `<script>` tag to their `index.html` seems like it could be part of a larger "library management" feature which has been proposed from the very start of this repo but has never been implemented.  See issue #4.

> if you think this can work you can assing me this issue

Done.  It sounds like you have a pretty good grasp on it.

**Comment by mrkirthi-24** [comment]
Hey @raclim is the assignee actively working on this issue?

**Comment by RandomGamingDev** [comment]
@mrkirthi-24 No, I'm not currently working on the issue

**Comment by mrkirthi-24** [comment]
@RandomGamingDev i think @abhi267266 is assigned for the issue. So lets hear from him

**Comment by RandomGamingDev** [comment]
ah alr

**Comment by mrkirthi-24** [comment]
@raclim ?? @abhi267266 ??

**Comment by abhi267266** [comment]
still working on it, any help would be great

**Comment by malay44** [comment]
I would love to help you out. 

Email :- malay.p1@ahduni.edu.in

**Comment by raunak42** [comment]
Hey @abhi267266, any updates?

**Comment by abhi267266** [comment]
@raunak42 almost done

**Comment by akshatarora130** [comment]
@abhi267266 Is the feature completed ?

**Comment by abhi267266** [comment]
https://github.com/abhi267266/p5.js-web-editor/commit/bdeda52f6c698c35e1aeb8c90d4ea12b1fd819be

hi, i need help with the syntax highlight for ts, i have tried using the javascript configuration it is working but showing error for some ts related syntax. i dont know how it works if someone can just give me a explanation on it how to configuration for codemirror for or can just give me some resources on it

**Comment by mrkirthi-24** [comment]
@RandomGamingDev Please reaaign this task to someone else.

**Comment by lindapaiste** [comment]
> still working on it, any help would be great

You should create a draft PR with your current progress.  Explain which parts do and don’t work and what you need help with.  That way we can see where you’re at and make suggestions.

**Comment by RandomGamingDev** [comment]
> @RandomGamingDev Please reaaign this task to someone else.

@mrkirthi-24 I'm not a steward for this repo so I don't have the permissions needed to do that. Nor do I know who I'd assign this to.



> > still working on it, any help would be great
> 
> You should create a draft PR with your current progress. Explain which parts do and don’t work and what you need help with. That way we can see where you’re at and make suggestions.

@abhi267266 I agree that this is what you should do so that we can get this out as soon as possible and so that multiple people don't end up working on it at once.

**Comment by abhi267266** [comment]
@RandomGamingDev Ok , I will do that

**Comment by abhi267266** [comment]
I have added a "Enable TypeScript" button and implemented functionality to enable TypeScript files in the application. However, I am currently facing challenges with the compilation process and syntax highlighting in the editor.
