### ISSUE TITLE
Discussion: do users understand the symbols in keyboard shortcuts?

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2355]
### Increasing Access

It would make it more obvious to the user how they can use keyboard shortcuts in the editor.

### Feature enhancement details

We use symbols to represent keys when displaying the keyboard commands.  I'm concerned that these symbols might be a bit obscure.  `⌘` for the "Command" key on Mac is well-understood, but `⌃` for the "Ctrl" key on PC is not.  It's [a valid syntax](https://en.wikipedia.org/wiki/Control_key#Notation), but it's not what is currently used by most applications.  
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/310d2321-090e-4e7e-8bf3-f6299e758e53)
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/1ce93522-afee-4cdd-9262-af8e4a729f21)

The current standard on Windows is to type out both the `Ctrl` and `Shift` keys by name.  Here are some examples:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/8ecd5ce5-3d91-4d57-b443-f5de13e5f4e6)
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/c9284344-6d0d-4273-bf88-d4b39eabcccf)
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/44b9f898-60ed-4860-a790-0048279257bb)
(Edge, Chrome, Github)

**Comment by sdivyanshu90** [comment]
I think we should change it to Ctrl and Shift. This change will enhance the consistency of our shortcuts across platforms and align with established conventions. By using 'Ctrl + Shift,' we can provide a more universally recognizable combination, ensuring a seamless experience for users regardless of their operating system. This change simplifies the shortcut, making it more intuitive and accessible. If everyone agrees, I'm happy to create a pull request to implement this modification.

**Comment by dibyam-jalan27** [comment]
Can i work on this @lindapaiste?

**Comment by Sheikh-JamirAlam** [comment]
I think its a valid point, most of the Windows users are familiar with "Ctrl + Shift" format and its more widely used as well. Will definately increase accessibility. I would like to work on this issue if possible.
