### ISSUE TITLE
Convert legacy React class components to function components

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2358]
### Increasing Access

It keeps the codebase up to date and makes it easier for new contributors.

### Feature enhancement details

[`React.Component` is considered a legacy API and is not recommended.](https://react.dev/reference/react/Component)  We should convert all class components to function components which use React hooks.

---

This is mainly a "Progress Report" for myself because with so many unmerged PRs sometimes I forget what I've already worked on!

Here are the class components which remain the codebase, and the PRs to convert them:
- [ ] EmailVerificationView
- [x] App #2308 
- [x] Overlay #2309 
- [x] AddToCollectionList #2353
- [x] AddToCollectionSketchList #2364
- [ ] ConsoleInput
- [x] CopyableInput #2360
- [ ] Editor -- this one is too annoying/difficult due to the potential for stale closures.  It will likely wait until upgrading to codemirror v6, when the component needs a lot of changes anyways.
- [ ] FileNode
- [x] Toolbar #2352
- [x] Preferences #2335 
- [ ] Searchbar
- [x] IDEView done by @dewanshDT, not submitted yet
- [x] APIKeyForm #2307 
- [x] Collection #2366
- [x] CollectionView #2302 
- [ ] DashboardView
- [ ] Tables -- should be addressed together (see #1442)
  - [ ] SketchListRowBase
  - [x] SketchList #2376
  - [ ] AssetListRowBase
  - [x] AssetList #2376
  - [ ] CollectionListRowBase
  - [x] CollectionList #2376

**Comment by vijayabhaskar-ev** [comment]
Convert EmailVerificationView to function component #2401

**Comment by KSSaiTeja** [comment]
i want to work to work to convert the collectionListRowbase component and make a PR. can i do it?

**Comment by shauryag2002** [comment]
Hi @lindapaiste , It seems like you are working on this issue quite long time,
if not able to do it !
Can @lindapaiste assign it to me?

**Comment by lindapaiste** [comment]
Thank you everyone for all of your work on this!  It looks like all components have been covered in pending PRs.

We do not need any more new PRs for this issue.

**Comment by KSSaiTeja** [comment]
@lindapaiste could you please take my PR into consideration and review it

**Comment by up1512001** [comment]
Can I work on DashboardView if anyone didn't?

**Comment by thakkarnetram** [comment]
Ref #2447 .
I have updated the Assets List to a functional component

**Comment by lindapaiste** [comment]
Normally I would not close an issue until all of the PRs are merged.  But I'm going to close this so y'all will stop submitting unnecessary PRs.

**Comment by KSSaiTeja** [comment]
@lindapaiste what about my PR. will it be considered or closed? as a beginner i didn't understand your point.. please tell me

**Comment by thakkarnetram** [comment]
> @lindapaiste what about my PR. will it be considered or closed? as a beginner i didn't understand your point.. please tell me

 I didn't understand either

**Comment by umangutkarsh** [comment]
Hi @lindapaiste  , I'd like to contribute to this issue, if this issue is still open.
