### ISSUE TITLE
move auto-refresh to preferences panel?

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#236]
I apologize if I missed the discussion of this somewhere. Can we move the auto-refresh option to the preferences panel? As it is, it seems to confuse the information hierarchy in the area where the title is. If this seems ok, I'll go ahead and make the change.

**Comment by catarak** [comment]
I agree that the hierarchy of information is confusing, but I also like that the auto-refresh option is out of the preferences pane. I think it's the kind of option that's nice to turn on and off quickly while coding or teaching, and nice to have visible so it's clear to users what's happening if the preview is automatically refreshing. I also think it makes most sense grouped with the play and pause button. However, perhaps the same argument could be make for a lot of other preferences, and opening the preferences pane isn't hard either.  

Another option besides moving the autorefresh button into the preference pane would be to move the project title/author onto a new line/new section underneath the play/pause buttons. Thoughts?

**Comment by catarak** [comment]
It may also make sense to change the location of the sketch title, as it's a little awkwardly placed. Maybe it would make sense to be where the file name is, though then I'm not sure where the file name would go. Overall, this area could use a little UI/UX glance over.

**Comment by catarak** [comment]
With the new design, autorefresh has been left in the nav.
<img width="768" alt="screen shot 2017-07-11 at 10 20 28 am" src="https://user-images.githubusercontent.com/6063380/28073040-9c9b47e6-6622-11e7-9818-c62404614423.png">
