### ISSUE TITLE
"Add To Collection" doesn't work when viewing another user's sketch list

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2363]
### What is your operating system?

None

### Actual Behavior

When I click the "Add to Collection" button from another user's sketches page, I see a list of **_their_** collections.  Clicking on a collection to add or remove a sketch will give a 403 API error because I do not have permission to modify their collections (good).

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/051440bd-bce8-40df-90ca-35f2829d7f28)

These are codingtrain's collections, not mine:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/506dd4f2-9937-467b-9d67-6de46af2ce64)

The p5 user has no collections:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/cf51eb6f-145e-4d0c-9ae4-b4ac0b5c7450)

### Expected Behavior

I should see a list of **_my_** collections, and be able to add their sketch to my collection.

### Steps:
1. Go to https://editor.p5js.org/p5/sketches
2. Click on the 🔻 next to a sketch
3. Click "Add to collection"

**Comment by divyansh-prks** [comment]
i would like to work on this issue
