### ISSUE TITLE
Password reset email never arrives

### ISSUE THREAD

**Issue by massimopaiser** [processing/p5.js-web-editor#2371]
### What is your operating system?

Windows

### Actual Behavior

Doesn't recognise password and reset email never arrives

### Expected Behavior

Expecting a password reset email to arrive in order to log in

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)

```

**Comment by lindapaiste** [comment]
I suspect that this is the same issue as #2303 (observed on the resend confirmation email) and would be fixed by #2306.

@raclim this should be a priority.

**Comment by raclim** [comment]
Yes, I'm going to close this one for now to consolidate this emailing issue in #2303. 

In the meanwhile, please email hello@p5js.org with your account's username and we can help you manually reset your password from there.
