### ISSUE TITLE
Connection Reset Error in p5.js Web Editor on a Specific Wi-Fi Network

### ISSUE THREAD

**Issue by PeterSterner** [processing/p5.js-web-editor#2378]
### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### p5.js version

Current webeditor version

### Web browser and version

Any browser

### Operating System

Windows and Linux

### Steps to reproduce this

I'm encountering an issue when trying to use the p5.js web editor on a specific Wi-Fi network. Upon attempting to open the web editor, I receive an error message stating that the connection has been reset. This problem occurs exclusively on this particular Wi-Fi network, as I have tested the web editor on several other Wi-Fi networks without any issues.

Steps to Reproduce:

    Connect to the specific Wi-Fi network in question.
    Open a browser and navigate to the p5.js web editor (insert link here).
    Note the error message indicating that the connection has been reset.

Expected Behavior:
I expect to be able to open the p5.js web editor smoothly, regardless of the Wi-Fi network I am connected to. This issue appears to be isolated to this specific Wi-Fi network.

Additional Information:
I have tested this problem on multiple devices, and it only occurs on this particular Wi-Fi network. I do not experience any difficulties using the p5.js web editor on other networks. I have also attempted to clear the cache and cookies in my browser, but the issue persists.

**Comment by PeterSterner** [comment]
I get these error messages in console:

`
Could not parse URL ReferenceError: RPMGetInnerMostURI is not defined
    getHostName chrome://global/content/aboutNetError.mjs:19
    <anonymous> chrome://global/content/aboutNetError.mjs:15
aboutNetError.mjs:21:13
    getHostName chrome://global/content/aboutNetError.mjs:21
    <anonym> chrome://global/content/aboutNetError.mjs:15
`

and this:

`
Uncaught ReferenceError: RPMGetFormatURLPref is not defined
    initPage chrome://global/content/aboutNetError.mjs:302
    <anonymous> chrome://global/content/aboutNetError.mjs:1553
aboutNetError.mjs:302:17
`

**Comment by lindapaiste** [comment]
Very very weird.  These error messages that you saw in the console are coming from the browser itself.  Why would those variables not be defined?  It seems like there must be some sort of plugin or addon on your end that's interfering?

The second one, the browser is trying to show a "not connected to the internet" error page but then it crashes due to a function/variable which is not defined.

> `Uncaught ReferenceError: RPMGetFormatURLPref is not defined initPage chrome://global/content/aboutNetError.mjs:302 <anonymous> chrome://global/content/aboutNetError.mjs:1553 aboutNetError.mjs:302:17`

```
function initPage() {
  // We show an offline support page in case of a system-wide error,
  // when a user cannot connect to the internet and access the SUMO website.
  // For example, clock error, which causes certerrors across the web or
  // a security software conflict where the user is unable to connect
  // to the internet.
  // The URL that prompts us to show an offline support page should have the following
  // format: "https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/supportPageSlug",
  // so we can extract the support page slug.
  let baseURL = RPMGetFormatURLPref("app.support.baseURL");
  let location = document.location.href;
```
[source](https://git.progress-linux.org/packages/fuchur-backports/firefox/tree/browser/base/content/certerror/aboutNetError.js?h=upstream/91.0.1&id=c7e4f46519e75628bfe70500213adcf18bdbb5bf#n242)

The first one, there is another core browser function/variable `RPMGetInnerMostURI` which is not defined.  And I really don't see how anything in the p5.js Web Editor could be causing that?
> `Could not parse URL ReferenceError: RPMGetInnerMostURI is not defined getHostName chrome://global/content/aboutNetError.mjs:19 <anonymous> chrome://global/content/aboutNetError.mjs:15 aboutNetError.mjs:21:13 getHostName chrome://global/content/aboutNetError.mjs:21 <anonym> chrome://global/content/aboutNetError.mjs:15`

```
const HOST_NAME = getHostName();

function getHostName() {
  try {
    return new URL(RPMGetInnerMostURI(document.location.href)).hostname;
  } catch (error) {
    console.error("Could not parse URL", error);
  }
  return "";
}
```
[source](https://hg.mozilla.org/mozilla-central/file/tip/toolkit/content/aboutNetError.mjs#l15)

**Comment by Souf149** [comment]
I have the same issue. Everyone on our WIFI-network can not connect to the editor anymore.
This has only recently started to appear.

![image](https://github.com/processing/p5.js-web-editor/assets/34127049/6c9089c7-f60f-4458-88e4-7094d7b99dec)
![image](https://github.com/processing/p5.js-web-editor/assets/34127049/56f9eb83-4ae0-4595-8d3c-3d21b01d860d)
