### ISSUE TITLE
Deprecated package `node-sass`

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2392]
We are compiling `.scss` files to `.css` using the `node-sass` package which is [deprecated](https://www.npmjs.com/package/node-sass).

We should switch over to `sass` (Dart Sass).

* https://sass-lang.com/dart-sass/
* https://www.npmjs.com/package/sass

This will involve installing the correct packages but will also likely involve changes to our Webpack config files.

_Originally posted by @lindapaiste in https://github.com/processing/p5.js-web-editor/pull/2388#pullrequestreview-1585040708_

**Comment by nsundriyal62** [comment]
i can make these changes 
i already worked on scss and css both
should i directly solve and genrate a PR
OR YOU CAN ASSIGN IT TO ME?

**Comment by lindapaiste** [comment]
@nsundriyal62 You can just create a PR and mention this issue.  I did assign it to you though!

**Comment by nsundriyal62** [comment]
i am working on it buddy
 Thanks for assigning

**Comment by nsundriyal62** [comment]
sorry to bother you again and again
but idk why 

i am unable to setup the envirement for this codebase...........?

i am new to open source and stucked a lot

i also read all your documentation to setup this repo but can not succeed

can you please help me out to solve this problem

i use chatgpt, asking to my friends and so on........

is there any other way to solve bug better than cloning it on your own system and then setting up the envirement

**Comment by C0dewithLokesh** [comment]
@nsundriyal62 dm me i will help

**Comment by luckyklyist** [comment]
I've just submitted a pull request to address this issue. @lindapaiste your feedback and review would be greatly appreciated.

**Comment by lindapaiste** [comment]
Fixed by #2429.  Thank you @luckyklyist!
