### ISSUE TITLE
P5 is not working again

### ISSUE THREAD

**Issue by ThatkidTerrell** [processing/p5.js-web-editor#242]
Please fix this problem of other people being able to sign into others profiles. This issue is still occurring even after you have made the changes that should fix it but you clearly haven't. I don't know why this hasn't been fixed but this is a major fact of why you have so many problems please fix this.

**Comment by lmccart** [comment]
Hi @ThatkidTerrell, I'm sorry for your trouble. We have an open issue for this [here](https://github.com/processing/p5.js-web-editor/issues/113) and we are currently trying to debug.

However, I do request that you please be respectful in your positing and considerate of the fact that this is a volunteer based project and we are all working as hard as we can on this issue and the many others posted. I would like to refer you to the [contributing guidelines](https://github.com/processing/p5.js-web-editor/blob/master/contributing.md) and [p5.js community statement](http://p5js.org/community/). We take respect and collaboration really seriously, and these values form the the basis for our projects -- I hope you'll be open to this.

Additionally, this project is still in the early stages development and has not been released or recommended for public use (as noted in the readme). I'm not sure how you found out about it, but I would suggest you don't use it until we've got it to a point where we feel it is stable and bug free enough to release. We will announce the tool at that time, and officially link to it from the p5js.org website. In the meantime, you might try out existing editors such as [Brackets](http://brackets.io), [Atom](https://atom.io/), [Sublime Text](https://www.sublimetext.com/3), or [OpenProcessing](https://www.openprocessing.org/). Thanks.
