### ISSUE TITLE
When the username is too big, the screen pixels are scattered on small screen

### ISSUE THREAD

**Issue by shauryag2002** [processing/p5.js-web-editor#2427]
### What is your operating system?

None

### Web browser and version

1.57.62 Chromium: 116.0.5845.180 (Official Build) (64-bit) 

### Actual Behavior

When the username is too big, the screen pixels are overflow on small screen
![processing](https://github.com/processing/p5.js-web-editor/assets/77102885/59607d47-8f59-45c7-8d8e-446481690fb1)
![processing-large](https://github.com/processing/p5.js-web-editor/assets/77102885/6b9a2d91-3767-4f18-bd9e-0786164ad5d7)

### Expected Behavior

On small screen,
Username should convert into less characters.
example:
**Hello, guptashaurya2002 !**
will convert to 
**Hello, guptash... !**

You can just better alternative of that problem

### Steps to reproduce

1. login with large username
2. make the screen small(mobile view)
3. see the username overflowing

**Comment by lindapaiste** [comment]
@dewanshDT has been working hard on a new mobile-friendly UI which will fix this problem!  I'm going to close this issue as the code has already been merged into the repo, though it hasn't been released yet.

Fixed by #2361
