### ISSUE TITLE
[cloud]:How to set up Mongodb through cloud if mongodb is not installed

### ISSUE THREAD

**Issue by karshdev** [processing/p5.js-web-editor#2430]
### Increasing Access

Some of my friends are not able to setup this project locally because they don't have mongodb installed

### Feature enhancement details

So how to setup mongodb through cloud

**Comment by luckyklyist** [comment]
You can set it up via Docker. Docker will create a separate environment for it.

**Comment by karshdev** [comment]
![Screenshot 2023-09-13 at 3 30 16 PM](https://github.com/processing/p5.js-web-editor/assets/121494581/f4a8b106-c165-419a-8a88-7d8b27cccab7)
 See this is what happened after....

**Comment by KSSaiTeja** [comment]
@karshdev you've use node 16.14.2 for this project..
for that, install nvm and set the node version to 16.14.2 after that try running docker.. it should work then.

Here is the detailed [guide](https://4geeks.com/how-to/nvm-install-windows). Go through it, and all the best for your contribution

**Comment by luckyklyist** [comment]
> ### Increasing Access
> Some of my friends are not able to setup this project locally because they don't have mongodb installed
> 
> ### Feature enhancement details
> So how to setup mongodb through cloud



> ![Screenshot 2023-09-13 at 3 30 16 PM](https://user-images.githubusercontent.com/121494581/267614768-f4a8b106-c165-419a-8a88-7d8b27cccab7.png) See this is what happened after....

Please go through the documentation. This is not an issue to raise. This will only load up the maintainers' work.

https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md

**Comment by lindapaiste** [comment]
I do think that setting up mongodb is an obnoxious barrier to entry.  We have an issue #1348 regarding running the web app without mongodb and there has been some progress there.

**Comment by karshdev** [comment]
Finally its done
thanks @lindapaiste
