### ISSUE TITLE
Help me 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2432]
### What is your operating system?

None

### Actual Behavior

sidebar is showing on the right side.

### Expected Behavior

I do not know what this sidebar is! I think this sidebar should not be displayed here.

### Steps to reproduce

I set up this project by following the documentation.

**Comment by Ankush263** [comment]
Try clicking `ctrl + h`

**Comment by BamaCharanChhandogi** [comment]
oho! done. Thanks
can you send some resources or a discord link?

**Comment by Ankush263** [comment]
Read the docs. everything is mentioned there

**Comment by BamaCharanChhandogi** [comment]
Ok thanks
