### ISSUE TITLE
Feat: Request to Implement Tailwind CSS for Improved Styling

### ISSUE THREAD

**Issue by KSSaiTeja** [processing/p5.js-web-editor#2435]
### Increasing Access

Dear Repository Maintainers,

I hope this message finds you well. I wanted to discuss the possibility of increasing accessibility and making our project more user-friendly by switching from SCSS to Tailwind CSS for styling purposes.

**Why Tailwind CSS?**

Tailwind CSS is an excellent utility-first CSS framework that simplifies the styling process, making it easier for developers to maintain and extend the codebase. It offers a wide range of pre-designed components and classes, which can significantly reduce the development time and potential errors associated with hand-written SCSS code.

**Accessibility Benefits:**

_Faster Development:_ Tailwind CSS provides a streamlined way to style components, allowing for quicker development and easier maintenance.

_Consistency_: It ensures consistent styling across the project, reducing the risk of style-related bugs and inconsistencies.

_Easy Customization:_ Tailwind CSS allows us to customize styles while maintaining a clear and concise configuration file.

_Responsive Design:_ It comes with built-in responsive design utilities, making it simpler to create mobile-friendly interfaces.

### Feature request details

By incorporating Tailwind CSS into our project, we can enjoy the following advantages:

_Efficiency_: Tailwind CSS simplifies the styling process, reducing the time and effort required to create and maintain stylesheets. This efficiency can lead to faster development cycles.

_Consistency_: With Tailwind CSS, we can ensure consistent styling throughout our project, reducing the risk of style-related bugs and improving the overall user experience.

_Customization_: Tailwind CSS provides a straightforward way to customize styles while maintaining a clean configuration file. This allows us to tailor the design to our project's unique needs.

_Responsive Design_: Tailwind CSS offers built-in utilities for creating responsive designs, making it easier to build interfaces that adapt seamlessly to different screen sizes and devices.

**Implementation Plan:**

To implement this feature, we would need to:

Add Tailwind CSS as a project dependency.
Refactor existing SCSS styles to use Tailwind CSS classes.
Update documentation to reflect the use of Tailwind CSS for styling.

**Conclusion:**

I kindly request that the development team consider this feature request as it aligns with the goal of improving the project's efficiency, maintainability, and overall user experience. If you have any questions or need further information, please do not hesitate to reach out.

Thank you for your time and consideration.

Sincerely,
K S Sai Teja.

**Comment by perminder-17** [comment]
I am going to work on this issue...

**Comment by lindapaiste** [comment]
> I am going to work on this issue...

That would be premature.  Before making a major change like this we need to discuss it and come to a consensus on whether we want to implement it.

[Last time this was discussed](https://github.com/processing/p5.js-web-editor/issues/1215) the team decided on `styled-components`.  But that was 4 years ago and Tailwind was not one of the options that was considered.

I personally like Tailwind so I am open to this.  The biggest downside is that it has a learning curve and it's not readable to those who don't understand it.

**Comment by perminder-17** [comment]
> > I am going to work on this issue...
> 
> That would be premature. Before making a major change like this we need to discuss it and come to a consensus on whether we want to implement it.
> 
> [Last time this was discussed](https://github.com/processing/p5.js-web-editor/issues/1215) the team decided on `styled-components`. But that was 4 years ago and Tailwind was not one of the options that was considered.
> 
> I personally like Tailwind so I am open to this. The biggest downside is that it has a learning curve and it's not readable to those who don't understand it.

Ok sir, can you please provide me the community link so that i can discuss.

**Comment by KSSaiTeja** [comment]
i suggest to change the styling by component wise like legacy components code

**Comment by Akhilbisht798** [comment]
I agree with @KSSaiTeja here. We can change each component like we did from class to functional.
And I think tailwind will be great to consider.

**Comment by KSSaiTeja** [comment]
shall we start the work @lindapaiste could you please share ideas to start work

**Comment by Akshay02022** [comment]
@KSSaiTeja Is this primarily about transitioning from SCSS to Tailwind CSS, or will there also be some UI improvements involved?

**Comment by KSSaiTeja** [comment]
Actually i thought that, first change the styling to tailwind later focus on the UI improvements

**Comment by jeffscottward** [comment]
I don't understand how learning a domain specific language (Tailwind syntax) makes getting into the code base easier. It would make it harder for me and I'm actually very senior and am deep in the ThemeUI/Stitches/Radix ecosystem (for the sake of scalable codebases and ease of themeing).

If the new hot thing comes along and changes to a new implementation that doesn't liter classes, are we gonna do this all over again?

At the least, styled components uses native CSS or DOM object syntax.

Also, CSS now has native nesting like SCSS. 

Tailwind requires knowing CSS and then a whole abstraction on top.

I say stick with less abstractions, or at least an abstraction that still mimics native authoring.

**Comment by KSSaiTeja** [comment]
ok agree with your point.. But i am saying that tailwind css make easier to customise the styling..☺️

**Comment by jeffscottward** [comment]
If you mean higher level with a JSON config file generally then yes. This is where ThemeUI and Tailwind do crossover.

https://tailwindcss.com/docs/configuration

https://theme-ui.com/theme-spec

And with systemization you get amazing things like this that conform to a spec and can be dropped in on the fly.

https://components.ai/theme

But again. AUTHORING in Tailwind syntax make it so that less people can contribute. You need to know the abstraction right up front, so it makes it more exclusionary. It's only easier to people who know that abstraction.

I will author in any which way that mimics either native web syntax (font-family (CSS) or fontFamily (DOM)), but I won't do abstraction by syntax modification. Also Tailwind is bad practice with class littering but that's a different topic.

Per p5's mission statement, this would be decreasing accessibility, not enabling it.

**Comment by jeffscottward** [comment]
By adhering to the css spec you can apply those skills universally.

Here is a tool someone built on top of systemUI that enables you to compile to web, iOS, and Android, in the universal CSS syntax (with some caveats for responsive design arrays per the tool, but the css props are spec).

Because of this tool, I can now deploy everywhere with one codebase.

https://www.dripsy.xyz/#style-once-run-anywhere

**Comment by up1512001** [comment]
Does anyone has started working on this?

**Comment by jeffscottward** [comment]
This should not be a thing and should be closed.

**Comment by KSSaiTeja** [comment]
ok then, if the maintainers say to close this issue.. i will close the issue.. As this is opensource, i shared my thoughts on styling

**Comment by gAurav-0x07** [comment]
Hi, I'm new here and I yesterday made a pull request for #2458. Like it's easier to add Tailwind as a dependency but changing the whole SCSS code into Tailwind is a tedious task. Rather what if we divide this into groups and assign it? let's say we divided all the SCSS code into 5 parts. start assigning each to the one interested, and give them a deadline, if they aren't able to give an update till the deadline assign it to someone else. This way changing the whole SCSS code into Tailwind can be possible. Please share your thoughts on this. Thank you.

**Comment by jeffscottward** [comment]
> Hi, I'm new here and I yesterday made a pull request for #2458. Like it's easier to add Tailwind as a dependency but changing the whole SCSS code into Tailwind is a tedious task. Rather what if we divide this into groups and assign it? let's say we divided all the SCSS code into 5 parts. start assigning each to the one interested, and give them a deadline, if they aren't able to give an update till the deadline assign it to someone else. This way changing the whole SCSS code into Tailwind can be possible. Please share your thoughts on this. Thank you. 

If anything it should be changed to native CSS which now supports most of the things scss has like nesting and variables but there's little value add given it's authored the same way. 

In fact this very point is reason enough and proof that what exists is better than doing a whole tailwind conversion. The web platform settled on a syntax that was invented by a superset, not an entire new DSL. 

It's unnecessary, and limits that amount of people who can contribute. Do not give in to the next new thing. Tailwind will fall out of favor for the next pattern and we will be back here again.

Stick with the native syntax! "Use the platform". Whether it's scss, theme-ui, raw CSS, no new DSLs!

**Comment by gAurav-0x07** [comment]
Alright @jeffscottward, got it, Thank you.

**Comment by raclim** [comment]
I agree with some of the reasons outlined by @jeffscottward about Tailwind CSS adding complication and inaccessibility to the contributor experience, and as pointed out by @DrizzyOVO, it would also be a major change and I'm unsure if that's something we'd want to implement at the moment, so I'm going to close this for now. If needed, we could also revisit the component styling discussion as well!
