### ISSUE TITLE
console confused me at first

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#244]
Maybe I'm an idiot, but I though the console label WAS the console at first. Couldn't figure out why values were not printing.  Anyone else have that problem? Maybe the console could be open one or two lines by default?  Or maybe the >_ icon is too literal?

**Comment by catarak** [comment]
I agree with you, I think the >_ icon makes it confusing. I think the icon should be removed and used as a prompt when the console is made to be interactive.

**Comment by lmccart** [comment]
I am wondering if the console should be open by default? Or is that too much?

**Comment by joemckay5** [comment]
Processing's is open by default, so it will be familiar to students migrating from there.  
As it stands, if you make a mistake there's no red text indicating something is wrong until you open the console. So you might not realize you code's not working the way you intended. 
I'd vote to have it always open, but you could  also keep it closed but open it if there are error messages, or if someone prints.

**Comment by catarak** [comment]
i like the idea of #253 in which there is some design element that shows there are messages in the console, but users have the option to tuck the console away they don't want to look at it/if it is distracting.

**Comment by lmccart** [comment]
@joemckay5 good point. I think from a teaching perspective it makes sense to have it open by default and users can close it if they want to. I'm not sure if the indication that there are messages in the console when closes then is as necessary? I realize we could design this in a way where everything is really explicit, but I'd like to find a balance where we can simplify and skip the things that aren't essential.
