### ISSUE TITLE
Feat: Request to add CSS on Signup form

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2440]
### Increasing Access

**p5.js version**
v1.4.1

**What is your operating system?**
Windows OS

**_Default Behavior:_**

![image](https://github.com/processing/p5.js-web-editor/assets/69814563/46a68cd1-4585-4911-92e4-6356e9654615)

**_After adding CSS:_**

<img width="461" alt="image" src="https://github.com/processing/p5.js-web-editor/assets/69814563/67b46fff-4414-418f-a8f2-cf5c1bef7d2a">

### **Changes:** 

- Add margin from the bottom for good styling.
- add bold on the link

**Comment by BamaCharanChhandogi** [comment]
#2441

**Comment by perminder-17** [comment]
I made the required change. Here what it looks like now. 
![Screenshot 2023-09-15 025149](https://github.com/processing/p5.js-web-editor/assets/127239756/95e69eff-6a29-4e0e-a1a3-786608c1e79d). I have done the pull request also.
