### ISSUE TITLE
Add a shared Link to all the sketches  

### ISSUE THREAD

**Issue by heyhimansh** [processing/p5.js-web-editor#2454]
### Increasing Access
**Easy Sharing:** With shared links, users can quickly and easily share their p5.js sketches with others. This simplicity encourages more sharing of creative work and educational content, which can attract a broader audience.

**Accessibility:** By removing barriers to access (e.g., requiring a login or complex sharing setup), shared links make it easier for people who may be new to p5.js to explore and appreciate the platform's capabilities.

**Community Engagement:** Shared links can be posted on social media, forums, or other online communities. This can attract new users to the p5.js Web Editor, as they can easily see and interact with the shared sketches, potentially leading to increased engagement with the platform.

**Collaboration:** Shared links make it effortless for individuals and teams to collaborate on p5.js projects. Collaborators can access the sketches without requiring them to log in or navigate through complex sharing settings.

### Feature request details
**1. Generate Shareable Links:**
 This link should uniquely identify the sketch and provide read-only access. I can use a unique identifier or a URL parameter to achieve this.

**2. Store and Manage Sketch Data:**
To ensure i have the necessary data to generate the link, I need a way to manage sketch information within your React app. This could involve using React state or a state management library like Redux to store sketch details.

**3. Create a Link URL:**
Use the sketch data to create a URL that includes the unique identifier or parameter for the specific sketch. This URL should lead to a view that displays the sketch in read-only mode.

**Comment by SableRaf** [comment]
Hello @heyhimansh, Thanks for your suggestion! The good news is, the p5.js Web Editor already offers a sharing feature. Just head to `File > Share` to see the available options, including sharing the code and viewing in fullscreen. Appreciate your input and commitment to improving the platform!

**Comment by lindapaiste** [comment]
This is a well-written feature request, but I'm going to close this issue as we do have this feature already.  Perhaps it needs to be more obvious?  If you didn't know it was there then you're probably not the only one.
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/d0ed05fa-7ddf-4a15-b30c-15f06aea1b37)
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/1fafac86-a6df-4db8-8e65-ebac8db15d00)

**Comment by heyhimansh** [comment]
@lindapaiste Thank you for your prompt response and for clarifying that the feature is already available.
