### ISSUE TITLE
Migrating to CSS-Modules

### ISSUE THREAD

**Issue by rajatmohan22** [processing/p5.js-web-editor#2455]
### Increasing Access

Unsure. But I am sure that it would REALLY help maintain the code clean and have separation of concerns

### Feature request details

Recently, while addressing issue #2228  , I noticed that several commonly used components, such as the button, are currently implemented using styled-components. I found this to be quite challenging due to the complexity of the code.

I believe that splitting the code into separate .jsx and .module.css files using CSS modules would greatly enhance code readability and ease of navigation within the codebase.

I am interested in taking the initiative to make these changes. Could someone please provide their approval for this proposal?

**Comment by rajatmohan22** [comment]
Hello @lindapaiste, could you please take a look at this? I could rewire the `Button.jsx` and submit a pull request. Perhaps it would be easier for you to make a decision after that. Please let me know your thoughts, and I'd be happy to proceed with the PR. Thank you!

**Comment by lindapaiste** [comment]
@rajatmohan22 We're actually moving in the opposite direction and trying to migrate from `.scss` files to `styled-components`. See #1760.

**Comment by rajatmohan22** [comment]
> @rajatmohan22 We're actually moving in the opposite direction and trying to migrate from `.scss` files to `styled-components`. See #1760.

Got it, Thanks for the reply!
