### ISSUE TITLE
add CSS for vertical alignment of checkbox labels

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2458]
### Increasing Access

**p5.js version**
v1.4.1

**What is your operating system?**
Windows OS

**### Problem:** 
The checkbox and Text are not Linear.
**_Default Behavior:_**

![image](https://github.com/processing/p5.js-web-editor/assets/69814563/da749ff7-77f0-4453-b375-50d1d748c17f)

**_After adding CSS:_**

<img width="324" alt="image" src="https://github.com/processing/p5.js-web-editor/assets/69814563/4ee877ee-ffcb-4be8-88f0-922a0b86bf0e">

### **Changes:** 

- Add margin for good styling.

**Comment by leftover19** [comment]
Please provide steps to reproduce.

**Comment by BamaCharanChhandogi** [comment]
@all-contributors please add @BamaCharanChhandogi  for infrastructure, tests and code

**Comment by gAurav-0x07** [comment]
Hi guys I'm new here, can ya'll check my code. Thank you.

**Comment by Ganaik2004** [comment]
@BamaCharanChhandogi  want to work on this issue .Please assign it to me.

**Comment by aspired2001** [comment]
I would like to work on this issue please assign this issue to me

**Comment by Varun-45** [comment]
I would like to work on this issue. Please assign this issue to me!

**Comment by Noorain464** [comment]
I would like to work on this issue.
