### ISSUE TITLE
Eye Icon for Revealing and Hiding Passwords

### ISSUE THREAD

**Issue by perminder-17** [processing/p5.js-web-editor#2466]
### Increasing Access

The proposed feature entails the addition of a small eye icon next to password input fields within the application's user interface. Users would have the option to click on this icon, toggling between two states:
1. Password hidden
2. Password revealed

### Feature enhancement details

1.Improved User Experience: This feature would enhance the overall user experience by providing an option to easily view the entered password, reducing frustration associated with mistyped or forgotten passwords during the login or registration process.

2.Enhanced Security: Despite the password being temporarily visible, this feature does not compromise security since it is under the user's control. Passwords would still be securely stored and transmitted as usual.

3.Accessibility: The eye icon would be particularly helpful for users with visual impairments who rely on screen readers. They can easily verify their entered password before submission.
![image](https://github.com/processing/p5.js-web-editor/assets/127239756/59d19c64-27f5-4fbd-99b8-18f9ec929002)

**Comment by perminder-17** [comment]
@lindapaiste Can we work on this issue.??

**Comment by lindapaiste** [comment]
> @lindapaiste Can we work on this issue.??

Sure!  FYI based on my quick googling it seems like the way to unobscure the text is by changing the `<input>` from `type="password"` to `type="text"` and back.

**Comment by perminder-17** [comment]
Ok working on it..

**Comment by perminder-17** [comment]
@lindapaiste can u review?

**Comment by Ganaik2004** [comment]
@lindapaiste  i want to work on these issue . Please assign it to me.

**Comment by sudhanshuku01** [comment]
I'm done can I make pull request for this one

**Comment by Shashank0229** [comment]
Yes , Thats true , we can have or simply we must have an eye icon for password and I think the better solution I have as I can do this in just a 2-3 lines of code , Assign me

**Comment by Shashank0229** [comment]
Hello Sir

It's great to hear from you, I can contribute or can fix your bug , please
allow me to contribute on it

Thank you

**Comment by Varun-45** [comment]
@perminder-17 I want to work on this issue can you please assign it to me

**Comment by madtitan02** [comment]
is this issue still unresolved?? can i work on it

**Comment by lindapaiste** [comment]
Just a note that we need to test this feature in Microsoft Edge and make sure that it works alongside the built-in behavior. We may need to hide the default eye with
```
::-ms-reveal {
    display: none;
}
```
It's probably more complicated to hide our eye and use the default one when in Edge. 

See: https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal

**Comment by perminder-17** [comment]
Ok @lindapaiste  going to do that asap

**Comment by abhinav700** [comment]
@lindapaiste is this issue stil open ? I would Like to work on it.
