### ISSUE TITLE
Bug: Error on Mobile Device

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2470]
### What is your operating system?

Android

### Actual Behavior

https://github.com/processing/p5.js-web-editor/assets/69814563/e1830d44-4eca-4f10-9056-f17d1e6bc94e

### Expected Behavior

The dark theme is working on laptop-sized screens, but on mobile-sized screens, there are errors being displayed.

### Steps:

1. Set up the project locally.
2. Go to "Inspect" in your browser and click mobile size screens.
3. Click the dark button.

**Comment by heyhimansh** [comment]
Hey @lindapaiste, I would like to work on this issue. Could you please assign this issue to me?

**Comment by lindapaiste** [comment]
We are aware of this issue. (See #2184)

What you are looking at is the "old" mobile layout which is only viewable in development mode with the `MOBILE_ENABLED=true` env var.  This version has a lot of bugs.  @dewanshDT just recently created a better responsive design which does not have these issues.

The fix here is that we need to remove the old code.  We need to remove all of the `mobileFirst` switching in the `routes.jsx` file. A lot of old components like `MobileIDEView`, `MobileDashboardView` are no longer used at all and can be deleted entirely -- @raclim should we delete them?  Dewansh and I discussed this and we felt a bit uneasy about throwing out someone else's work but it's probably the best thing to do.

In the meantime, you should use `MOBILE_ENABLED=false` in your development environment.
