### ISSUE TITLE
Fet: Enhancement login page

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2474]
### Increasing Access

The login form is an essential part of this site, and I have recently updated its design for a better appearance.

**Problem:** Many users cannot see the login button displayed below due to the design.

**Solution:** I have made changes to the layout using flex, ensuring that all users can view the content without the need to scroll

![image](https://github.com/processing/p5.js-web-editor/assets/69814563/b1e94c01-2e25-4973-8b4e-44fc42111443)

### Feature enhancement details

I have updated CSS.

**Comment by BamaCharanChhandogi** [comment]
@lindapaiste could we work on this?

**Comment by rajatmohan22** [comment]
I actually prefer the original version; it is simple and elegant. I don't see how aligning it to the side could increase accessibility. Currently, it works perfect. No scrolling is needed to access the GitHub and Gmail logins either

**Comment by lindapaiste** [comment]
I prefer the current version as well.

@BamaCharanChhandogi if you are looking for something to style, we have [some designs](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3) which were created by a designer a few years ago.  Some may be outdated.  Maybe you could work on the file drawer?  Some of that UI requires backend and API work, like showing thumbnails and file sizes.  But some is just CSS.
