### ISSUE TITLE
Bug: why link is not bold on main site

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2475]
### What is your operating system?

Windows

### Actual Behavior

<img width="218" alt="image" src="https://github.com/processing/p5.js-web-editor/assets/69814563/38d30c0e-f287-48ac-b69f-d4b398c7e62f">

<img width="402" alt="image" src="https://github.com/processing/p5.js-web-editor/assets/69814563/bb9bf188-acd4-499d-ae33-c5d153029757">

### Expected Behavior

the link should be bold.

### Steps:
go to the main site and click on the signup or login page

**Comment by lindapaiste** [comment]
@BamaCharanChhandogi Your PR #2441 was merged, but we have not pushed to production since then.  The last production release was on August 16th.  Any changes since then will not be visible on editor.p5js.org until the next release.

https://github.com/processing/p5.js-web-editor/releases
