### ISSUE TITLE
Add User Settings View

### ISSUE THREAD

**Issue by thepackrat** [processing/p5.js-web-editor#248]
Permit logged-in user to see/change associated email address

There's currently no obvious way for a logged-in user to see or change the email address associated with their account. It should probably live in the right-hand user menu.

**Comment by catarak** [comment]
Definitely need this! This hints at a bigger issue which is that this app needs a user settings page, so a user can see and change account settings. I'm going to change the title of this issue to reflect that.

**Comment by yining1023** [comment]
This would be a very helpful feature! I'd love to work on this if it's alright.

For starters, I'm thinking

- [ ] adding `My account` to the upper-right user menu
- [ ] rediecting user to a https `My account` page with `username`, `email` and `change password` like the image below from codepen.

What do you think? @catarak @lmccart 

<img width="198" alt="screen shot 2017-01-05 at 11 05 16 pm" src="https://cloud.githubusercontent.com/assets/8662372/21707260/0237600e-d39c-11e6-9437-7030d7b48bbd.png">

<img width="500" alt="screen shot 2017-01-05 at 11 02 46 pm" src="https://cloud.githubusercontent.com/assets/8662372/21707190/3d487b84-d39b-11e6-819e-5d1ec202f86b.png">

**Comment by catarak** [comment]
@yining1023 yes, perfect! you can go ahead and start on this 😄

**Comment by lmccart** [comment]
looks great to me!

**Comment by thepackrat** [comment]
Will there be an option to change the email, possibly with a confirmation email to avoid typos?

**Comment by catarak** [comment]
@thepackrat yes! some of the code for that is being worked on in #230.
