### ISSUE TITLE
Save user preferences even without login

### ISSUE THREAD

**Issue by devsargam** [processing/p5.js-web-editor#2485]
### Increasing Access

Some people who tend to use the editor aren't logged in due to various reasons.
So, it is tedious to change the preferences accordingly every time you use the editor.
I believe this change will be more useful for those who haven't logged in.
Hence, it will increase access to the p5.js editor.

### Feature request details

All the user preferences that they choose when using the editor should be saved in the browser's local storage. 
The next time they use the editor, the same preferences must be loaded.

**Comment by thinley4** [comment]
This feature will surely enhance the users participation in p5.js Web Editor @devsargam
In my opinion, I think with that we can also add another feature like pop up for reminding users to login or sign up so that they can stay connected.

**Comment by aspired2001** [comment]
Sir , I would like work on this issue please assign this to me

**Comment by devsargam** [comment]
@aspired2001 if possible I wanted to implement these myself since I was a long fan of @CodingTrain and I always wanted to contribute in someway possible.

**Comment by raclim** [comment]
Thanks for raising this! 

We're aiming to preserve as little information as possible about our users to address their privacy concerns and needs, which might be more stringent depending on the context the editor is used in. I would personally like to avoid storing any information unless deeply necessary and feel that this might not be an issue to immediately address in the upcoming months, so I'm going to close this for now. 

However, this could be something to revisit later in the future, so I will add it to this project board (https://github.com/processing/p5.js-web-editor/projects/11)!
