### ISSUE TITLE
p5 logo showing a border when zoomed out

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#2488]
### What is your operating system?

Windows

### Web browser and version

Brave

### Actual Behavior

When we normally open the p5.js Web Editor website the p5 logo is showing a weird border.
![Screenshot 2023-10-03 163743](https://github.com/processing/p5.js-web-editor/assets/80570105/5e30d897-bd55-453f-8c7c-a6956388a23b)

### Expected Behavior

But if we zoom in on the logo the border disappears.
![Screenshot 2023-10-03 164007](https://github.com/processing/p5.js-web-editor/assets/80570105/8120c984-210a-4017-937c-054653ade03a)

### Steps:
1. Zoom in to make the border disappear.
2. Zoom out to make the border appear.

**Comment by DhairyaMajmudar** [comment]
@lindapaiste can you pls. assign this issue to me. I went through the codebase and also finding out the approach to solve this issue. It would be so nice of you if this issue is assigned to me.
