### ISSUE TITLE
Incorrect Cursor Display on Non-draggable Button

### ISSUE THREAD

**Issue by skbhagat0502** [processing/p5.js-web-editor#2489]
### What is your operating system?

Windows

### Web browser and version

Chrome

### Actual Behavior

I've come across a bug in your software that I believe needs attention. When hovering over a button that is not intended to be draggable, the cursor incorrectly displays as a draggable cursor, causing confusion among users.

https://github.com/processing/p5.js-web-editor/assets/109683163/18011852-61fb-41b3-861f-738af603a93c

### Expected Behavior

The cursor should exhibit the standard pointer icon when placed over the button, indicating that it is clickable but not draggable.

### Steps:
1. Navigate to the left arrow button.
2. Hover over the button.

**Comment by skbhagat0502** [comment]
I am working on it.

**Comment by raclim** [comment]
Thanks for raising this! 

The reason why the cursor for this button appears this way was to [make the "Open/Close" of the sidebar more noticeable](https://github.com/processing/p5.js-web-editor/issues/1255). It seemed like a lot of users had difficulty with the sidebar button's visibility, so I'm personally less inclined to change this for now. 

However, I do see the confusion in using a cursor that symbolizes a different action from what's actually happening (which in this case the current cursor's properties `e-resize` and `w-resize` indicate [resizing and scrolling](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)). I don't think we're going to address this yet in favor of other larger changes first, so I'm going to close this for now and add this to [a list of closed issues to revisit later](https://github.com/processing/p5.js-web-editor/projects/11) to re-discuss in the near future!
