### ISSUE TITLE
Feature Request: Logout Confirmation Modal

### ISSUE THREAD

**Issue by skbhagat0502** [processing/p5.js-web-editor#2492]
### Increasing Access

**Benefits:**

1. User-Friendly: Reduces the likelihood of accidental logouts.
2. Enhanced Security: Provides an additional layer of confirmation for sensitive actions.
3. Consistency: Aligns with modern web practices for user interactions.

### Feature request details

**Description:**
Currently, the website includes a **logout** button to allow users to **sign out**. To enhance the user experience and prevent accidental logouts, I propose the implementation of a logout confirmation modal.

**Details:**
Upon clicking the logout button, a modal should appear, asking the user to confirm their intention to log out. The modal should include a clear message such as "Are you sure you want to log out?" along with buttons for "Confirm" and "Cancel."

**Comment by skbhagat0502** [comment]
@lindapaiste Can I work on this?

**Comment by perminder-17** [comment]
Good feature request @skbhagat0502

**Comment by aspired2001** [comment]
I would like to work on this please assign me this project

**Comment by lindapaiste** [comment]
> @lindapaiste Can I work on this?

I am not the one in charge so idk if @raclim has any thoughts about this.  But it sounds fine to me if you want to put in a PR @skbhagat0502.

**Comment by skbhagat0502** [comment]
@lindapaiste @raclim  I am working on this.

**Comment by skbhagat0502** [comment]
@raclim @lindapaiste please review this.

**Comment by abhinav700** [comment]
@raclim  @skbhagat0502 I would like to work on this issue. Is it still open?

**Comment by PiyushThapaa** [comment]
@raclim @lindapaiste Instead of making logout confirmation modal we can simply use confirm function for confirmation as it reduces code size. Also the confirmation of deletion of a sketch of user uses confirm function so we should go with it. If this is a good idea can I start working on this issue...?

**Comment by raclim** [comment]
Thanks for raising this request! After giving this some thought, I don't think adding a confirmation modal on logout is necessary as it isn't a common design pattern. I'm going to close this issue and its associated PRs, but please feel free to check out other issues!
