### ISSUE TITLE
I cant see the changes on my local machine

### ISSUE THREAD

**Issue by Praveen03AJJARAPU** [processing/p5.js-web-editor#2493]
### What is your operating system?

Windows

### Web browser and version

117.0.5938.149

### Actual Behavior

I can't see the changes made in my editor, if I want to see a change I have to stop the docker containers and restart the containers and it takes 3-5 minutes to restart. Please look into the issue. 

npm -v
8.5.0

node -v
v16.14.2

### Expected Behavior

See the changes that I have made in the code editor.

### Steps to reproduce

[+] Stopping 2/2
 ✔ Container p5js-web-editor-app-1    Stopped            2.1s 
 ✔ Container p5js-web-editor-mongo-1  Stopped            0.6s 
canceled
PS C:\Users\Praveen\open-source\p5.js-web-editor> docker-compose -f docker-compose-development.yml up
[+] Running 2/0
 ✔ Container p5js-web-editor-mongo-1  Created            0.0s 
 ✔ Container p5js-web-editor-app-1    Created            0.0s 
Attaching to p5js-web-editor-app-1, p5js-web-editor-mongo-1
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.662+00:00"},"s":"I",  "c":"CONTROL",  "id":23285,   "ctx":"main","msg":"Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'"}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.695+00:00"},"s":"I",  "c":"NETWORK",  "id":4648601, "ctx":"main","msg":"Implicit TCP FastOpen unavailable. If TCP FastOpen is required, set tcpFastOpenServer, tcpFastOpenClient, and tcpFastOpenQueueSize."}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.701+00:00"},"s":"I",  "c":"STORAGE",  "id":4615611, "ctx":"initandlisten","msg":"MongoDB starting","attr":{"pid":1,"port":27017,"dbPath":"/data/db","architecture":"64-bit","host":"389cbe8a1db2"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.701+00:00"},"s":"I",  "c":"CONTROL",  "id":23403,   "ctx":"initandlisten","msg":"Build Info","attr":{"buildInfo":{"version":"4.4.24","gitVersion":"0b86b9b7b42ad9970c5f818c527dd86c0634243a","openSSLVersion":"OpenSSL 1.1.1f  31 Mar 2020","modules":[],"allocator":"tcmalloc","environment":{"distmod":"ubuntu2004","distarch":"x86_64","target_arch":"x86_64"}}}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.701+00:00"},"s":"I",  "c":"CONTROL",  "id":51765,   "ctx":"initandlisten","msg":"Operating System","attr":{"os":{"name":"Ubuntu","version":"20.04"}}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.701+00:00"},"s":"I",  "c":"CONTROL",  "id":21951,   "ctx":"initandlisten","msg":"Options set by command line","attr":{"options":{"net":{"bindIp":"*"}}}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.705+00:00"},"s":"I",  "c":"STORAGE",  "id":22270,   "ctx":"initandlisten","msg":"Storage engine to use detected by data files","attr":{"dbpath":"/data/db","storageEngine":"wiredTiger"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.705+00:00"},"s":"I",  "c":"STORAGE",  "id":22297,   "ctx":"initandlisten","msg":"Using the XFS filesystem is strongly recommended with the WiredTiger storage engine. See http://dochub.mongodb.org/core/prodnotes-filesystem","tags":["startupWarnings"]}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:56.705+00:00"},"s":"I",  "c":"STORAGE",  "id":22315,   "ctx":"initandlisten","msg":"Opening WiredTiger","attr":{"config":"create,cache_size=1359M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress,compact_progress],"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:57.758+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692597:758203][1:0x7f14c8b3acc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 10 through 11"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:58.246+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692598:246282][1:0x7f14c8b3acc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 11 through 11"}}
p5js-web-editor-app-1    | 
p5js-web-editor-app-1    | > p5.js-web-editor@2.7.3 start
p5js-web-editor-app-1    | > cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js
p5js-web-editor-app-1    |
p5js-web-editor-app-1    | [nodemon] 2.0.22
p5js-web-editor-app-1    | [nodemon] reading config ./nodemon.json
p5js-web-editor-app-1    | [nodemon] to restart at any time, enter `rs`
p5js-web-editor-app-1    | [nodemon] or send SIGHUP to 25 to restart
p5js-web-editor-app-1    | [nodemon] ignoring: ./.git/**/* node_modules/**/node_modules       
p5js-web-editor-app-1    | [nodemon] watching path(s): server/**/*
p5js-web-editor-app-1    | [nodemon] watching extensions: js,json
p5js-web-editor-app-1    | [nodemon] starting `node index.js`
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:58.850+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692598:850009][1:0x7f14c8b3acc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Main recovery loop: starting at 10/29568 to 11/256"}}
p5js-web-editor-app-1    | [nodemon] forking
p5js-web-editor-app-1    | [nodemon] child pid: 38
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.027+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692599:27353][1:0x7f14c8b3acc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 10 through 11"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.197+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692599:197652][1:0x7f14c8b3acc0], txn-recover: [WT_VERB_RECOVERY_PROGRESS] Recovering log 11 through 11"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.283+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692599:283319][1:0x7f14c8b3acc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global recovery timestamp: (0, 0)"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.283+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692599:283494][1:0x7f14c8b3acc0], txn-recover: [WT_VERB_RECOVERY | WT_VERB_RECOVERY_PROGRESS] Set global oldest timestamp: (0, 0)"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.331+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"initandlisten","msg":"WiredTiger message","attr":{"message":"[1696692599:331004][1:0x7f14c8b3acc0], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 1, snapshot max: 1 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.366+00:00"},"s":"I",  "c":"STORAGE",  "id":4795906, "ctx":"initandlisten","msg":"WiredTiger opened","attr":{"durationMillis":2661}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.367+00:00"},"s":"I",  "c":"RECOVERY", "id":23987,   "ctx":"initandlisten","msg":"WiredTiger recoveryTimestamp","attr":{"recoveryTimestamp":{"$timestamp":{"t":0,"i":0}}}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.422+00:00"},"s":"I",  "c":"STORAGE",  "id":22262,   "ctx":"initandlisten","msg":"Timestamp monitor starting"}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.437+00:00"},"s":"W",  "c":"CONTROL",  "id":22120,   "ctx":"initandlisten","msg":"Access control is not enabled for the database. Read and write access to data and configuration is unrestricted","tags":["startupWarnings"]}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.440+00:00"},"s":"W",  "c":"CONTROL",  "id":22178,   "ctx":"initandlisten","msg":"/sys/kernel/mm/transparent_hugepage/enabled is 'always'. We suggest setting it to 'never'","tags":["startupWarnings"]}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.517+00:00"},"s":"I",  "c":"STORAGE",  "id":20536,   "ctx":"initandlisten","msg":"Flow Control is enabled on this deployment"} 
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.533+00:00"},"s":"I",  "c":"FTDC",     "id":20625,   "ctx":"initandlisten","msg":"Initializing full-time diagnostic data capture","attr":{"dataDirectory":"/data/db/diagnostic.data"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.535+00:00"},"s":"I",  "c":"REPL",     "id":6015317, "ctx":"initandlisten","msg":"Setting new configuration state","attr":{"newState":"ConfigReplicationDisabled","oldState":"ConfigPreStart"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.545+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"/tmp/mongodb-27017.sock"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.546+00:00"},"s":"I",  "c":"NETWORK",  "id":23015,   "ctx":"listener","msg":"Listening on","attr":{"address":"0.0.0.0"}}       
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:29:59.546+00:00"},"s":"I",  "c":"NETWORK",  "id":23016,   "ctx":"listener","msg":"Waiting for connections","attr":{"port":27017,"ssl":"off"}}
p5js-web-editor-app-1    | [nodemon] watching 81 files
p5js-web-editor-app-1    | p5.js Web Editor is running on port: 8000!
p5js-web-editor-app-1    | p5.js Preview Server is running on port: 8002
p5js-web-editor-app-1    | (node:38) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
p5js-web-editor-app-1    |
p5js-web-editor-app-1    | Please migrate your code to use AWS SDK for JavaScript (v3).       
p5js-web-editor-app-1    | For more information, check the migration guide at https://a.co/7PzMCcy
p5js-web-editor-app-1    | (Use `node --trace-warnings ...` to show where the warning was created)
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:15.481+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:42006","connectionId":1,"connectionCount":1}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:15.505+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn1","msg":"client metadata","attr":{"remote":"172.18.0.3:42006","client":"conn1","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"'Node.js v16.14.2, LE (unified)","version":"3.7.4|5.13.20"}}}
p5js-web-editor-app-1    | (node:38) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:15.545+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:42008","connectionId":2,"connectionCount":2}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:15.547+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:42014","connectionId":3,"connectionCount":3}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:15.551+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn2","msg":"client metadata","attr":{"remote":"172.18.0.3:42008","client":"conn2","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"'Node.js v16.14.2, LE (unified)","version":"3.7.4|5.13.20"}}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:15.553+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn3","msg":"client metadata","attr":{"remote":"172.18.0.3:42014","client":"conn3","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"'Node.js v16.14.2, LE (unified)","version":"3.7.4|5.13.20"}}}
p5js-web-editor-app-1    | <i> [webpack-dev-middleware] wait until bundle finished: /
p5js-web-editor-app-1    | <i> [webpack-dev-middleware] wait until bundle finished: /
p5js-web-editor-app-1    | <i> [webpack-dev-middleware] wait until bundle finished: /
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:26.332+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:53644","connectionId":4,"connectionCount":4}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:26.334+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn4","msg":"client metadata","attr":{"remote":"172.18.0.3:53644","client":"conn4","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"'Node.js v16.14.2, LE (unified)","version":"3.7.4|5.13.20"}}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:30:59.435+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1696692659:435459][1:0x7f14c1b2b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 3, snapshot max: 3 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:31:59.452+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1696692719:452860][1:0x7f14c1b2b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 6, snapshot max: 6 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:32:59.469+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1696692779:469164][1:0x7f14c1b2b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 8, snapshot max: 8 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:33:59.528+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1696692839:528966][1:0x7f14c1b2b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot miax: 10 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:34:00.752+00:00"},"s":"I",  "c":"-",        "id":20883,   "ctx":"conn1","msg":"Interrupted operation as its client disconnected","attr":{"opId":3013}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:34:00.753+00:00"},"s":"I",  "c":"NETWORK",  "id":22989,   "ctx":"conn1","msg":"Error sending response to client. Ending connection from remote","attr":{"error":{"code":6,"codeName":"HostUnreachable","errmsg":"Connection reset by peer"},"remote":"172.18.0.3:42006","connectionId":1}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:34:00.754+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn1","msg":"Connection ended","attr":{"remote":"172.18.0.3:42006","connectionId":1,"connectionCount":3}}    
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:34:59.547+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1696692899:547934][1:0x7f14c1b2b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 12, snapshot max: 12 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:35:57.638+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.18.0.3:37250","connectionId":5,"connectionCount":4}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:35:57.642+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn5","msg":"client metadata","attr":{"remote":"172.18.0.3:37250","client":"conn5","doc":{"driver":{"name":"nodejs|Mongoose","version":"3.7.4"},"os":{"type":"Linux","name":"linux","architecture":"x64","version":"5.15.90.1-microsoft-standard-WSL2"},"platform":"'Node.js v16.14.2, LE (unified)","version":"3.7.4|5.13.20"}}}
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:35:59.572+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1696692959:572665][1:0x7f14c1b2b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 16, snapshot max: 16 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}
p5js-web-editor-app-1    | assets by chunk 63.2 KiB (auxiliary name: app)
p5js-web-editor-app-1    |   assets by path *.svg 28.4 KiB 21 assets
p5js-web-editor-app-1    |   asset 2e95a3ff3baf95b44e86dbcaef8fe10a.mp3 21.4 KiB [emitted] [immutable] [from: client/sounds/audioAlert.mp3] (auxiliary name: app)
p5js-web-editor-app-1    |   asset images/p5js-square-logo.png 13.4 KiB [emitted] [from: client/images/p5js-square-logo.png] (auxiliary name: app)        
p5js-web-editor-app-1    | assets by path locales/ 341 KiB
p5js-web-editor-app-1    |   asset locales/hi/translations.json 34.4 KiB [emitted] [from: translations/locales/hi/translations.json] [copied]
p5js-web-editor-app-1    |   asset locales/uk-UA/translations.json 29.3 KiB [emitted] [from: translations/locales/uk-UA/translations.json] [copied]       
p5js-web-editor-app-1    |   asset locales/ja/translations.json 28.5 KiB [emitted] [from: translations/locales/ja/translations.json] [copied]
p5js-web-editor-app-1    |   asset locales/fr-CA/translations.json 25.3 KiB [emitted] [from: translations/locales/fr-CA/translations.json] [copied]       
p5js-web-editor-app-1    |   + 10 assets
p5js-web-editor-app-1    | assets by path *.js 37.9 MiB
p5js-web-editor-app-1    |   asset app.js 26.8 MiB [emitted] (name: app)     
p5js-web-editor-app-1    |   asset previewApp.js 8.28 MiB [emitted] (name: previewApp)
p5js-web-editor-app-1    |   asset previewScripts.js 2.84 MiB [emitted] (name: previewScripts)
p5js-web-editor-app-1    | orphan modules 779 KiB [orphan] 387 modules       
p5js-web-editor-app-1    | runtime modules 87.1 KiB 45 modules
p5js-web-editor-app-1    | modules by path ./node_modules/ 8.43 MiB
p5js-web-editor-app-1    |   javascript modules 8.39 MiB 1207 modules        
p5js-web-editor-app-1    |   json modules 46.9 KiB
p5js-web-editor-app-1    |     ./node_modules/friendly-words/generated/words.json 44.5 KiB [built] [code generated]
p5js-web-editor-app-1    |     ./node_modules/property-information/hast-to-react.json 475 bytes [built] [code generated]
p5js-web-editor-app-1    |     ./node_modules/axios/package.json 1.92 KiB [built] [code generated]
p5js-web-editor-app-1    | modules by path ./client/ 1.85 MiB 255 modules    
p5js-web-editor-app-1    | modules by path ./server/ 6.43 KiB
p5js-web-editor-app-1    |   ./server/domain-objects/createDefaultFiles.js 1.86 KiB [built] [code generated]
p5js-web-editor-app-1    |   ./server/utils/fileUtils.js 2.56 KiB [built] [code generated]
p5js-web-editor-app-1    |   ./server/utils/filePath.js 2.01 KiB [built] [code generated]
p5js-web-editor-app-1    | ./package.json 7.73 KiB [built] [code generated]  
p5js-web-editor-app-1    | webpack 5.76.0 compiled successfully in 344863 ms 
p5js-web-editor-app-1    | assets by chunk 63.2 KiB (auxiliary name: app)
p5js-web-editor-app-1    |   assets by path *.svg 28.4 KiB 21 assets
p5js-web-editor-app-1    |   asset 2e95a3ff3baf95b44e86dbcaef8fe10a.mp3 21.4 KiB [emitted] [immutable] [from: client/sounds/audioAlert.mp3] (auxiliary name: app)
p5js-web-editor-app-1    |   asset images/p5js-square-logo.png 13.4 KiB [emitted] [from: client/images/p5js-square-logo.png] (auxiliary name: app)        
p5js-web-editor-app-1    | assets by path locales/ 341 KiB
p5js-web-editor-app-1    |   asset locales/hi/translations.json 34.4 KiB [emitted] [from: translations/locales/hi/translations.json] [copied]
p5js-web-editor-app-1    |   asset locales/uk-UA/translations.json 29.3 KiB [emitted] [from: translations/locales/uk-UA/translations.json] [copied]       
p5js-web-editor-app-1    |   asset locales/ja/translations.json 28.5 KiB [emitted] [from: translations/locales/ja/translations.json] [copied]
p5js-web-editor-app-1    |   asset locales/fr-CA/translations.json 25.3 KiB [emitted] [from: translations/locales/fr-CA/translations.json] [copied]       
p5js-web-editor-app-1    |   + 10 assets
p5js-web-editor-app-1    | assets by path *.js 37.9 MiB
p5js-web-editor-app-1    |   asset app.js 26.8 MiB [emitted] (name: app)     
p5js-web-editor-app-1    |   asset previewApp.js 8.28 MiB [emitted] (name: previewApp)
p5js-web-editor-app-1    |   asset previewScripts.js 2.84 MiB [emitted] (name: previewScripts)
p5js-web-editor-app-1    | orphan modules 779 KiB [orphan] 387 modules       
p5js-web-editor-app-1    | runtime modules 87.1 KiB 45 modules
p5js-web-editor-app-1    | modules by path ./node_modules/ 8.43 MiB
p5js-web-editor-app-1    |   javascript modules 8.39 MiB 1207 modules        
p5js-web-editor-app-1    |   json modules 46.9 KiB
p5js-web-editor-app-1    |     ./node_modules/friendly-words/generated/words.json 44.5 KiB [built] [code generated]
p5js-web-editor-app-1    |     ./node_modules/property-information/hast-to-react.json 475 bytes [built] [code generated]
p5js-web-editor-app-1    |     ./node_modules/axios/package.json 1.92 KiB [built] [code generated]
p5js-web-editor-app-1    | modules by path ./client/ 1.85 MiB 255 modules    
p5js-web-editor-app-1    | modules by path ./server/ 6.43 KiB
p5js-web-editor-app-1    |   ./server/domain-objects/createDefaultFiles.js 1.86 KiB [built] [code generated]
p5js-web-editor-app-1    |   ./server/utils/fileUtils.js 2.56 KiB [built] [code generated]
p5js-web-editor-app-1    |   ./server/utils/filePath.js 2.01 KiB [built] [code generated]
p5js-web-editor-app-1    | ./package.json 7.73 KiB [built] [code generated]  
p5js-web-editor-app-1    | webpack 5.76.0 compiled successfully in 346286 ms 
p5js-web-editor-mongo-1  | {"t":{"$date":"2023-10-07T15:36:59.601+00:00"},"s":"I",  "c":"STORAGE",  "id":22430,   "ctx":"WTCheckpointThread","msg":"WiredTiger message","attr":{"message":"[1696693019:601147][1:0x7f14c1b2b700], WT_SESSION.checkpoint: [WT_VERB_CHECKPOINT_PROGRESS] saving checkpoint snapshot min: 19, snapshot max: 19 snapshot count: 0, oldest timestamp: (0, 0) , meta checkpoint timestamp: (0, 0) base write gen: 1542"}}

**Comment by gAurav-0x07** [comment]
Hi @Praveen03AJJARAPU, this was the same issue I faced, I rather did "manual installation" as provided in the guide. Also set your node and nvm to the required version, and run "mongod" in other terminal to start MongoDB.

**Comment by Praveen03AJJARAPU** [comment]
Thank you @DrizzyOVO your solution worked, and I have successfully implemented it. I am closing the issue.
