### ISSUE TITLE
Clicking ctrl + b should open and close the sidebar(file display menu)

### ISSUE THREAD

**Issue by shauryag2002** [processing/p5.js-web-editor#2495]
### Increasing Access

Clicking on ctrl+b , It should open and close the Sidebar like in VS code.

### Feature enhancement details

it will enhance the developers time from clicking the button to just typing ctrl + b .

**Comment by Praveen03AJJARAPU** [comment]
It was already in the editor, check it out.

**Comment by raclim** [comment]
Yes, it's currently implemented in the editor so I'm going to close this for now! If you're having difficulty accessing this feature please feel free to re-open this or note it as a bug.
