### ISSUE TITLE
Translation Typos in Sign Up Form Text

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2499]
### p5.js version

2.7.3

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

Validation typo in sign up page `email`
<img width="396" alt="Screenshot 2023-10-13 at 12 08 07 PM" src="https://github.com/processing/p5.js-web-editor/assets/47579287/0f902eb3-c8ec-4e02-916e-dba1b2b98a73">

### Expected Behavior

This should state `Please enter an email` instead of `Please enter a email`
<img width="383" alt="Screenshot 2023-10-13 at 12 11 50 PM" src="https://github.com/processing/p5.js-web-editor/assets/47579287/051129df-a743-4ec0-8321-6bae77da2efb">

### Steps:
1. Open p5.js web editor
2. Click on sign up 
3. Click on email input
4. Notice the typo in email's validation

--------------------------------------------------------

To Note: Also similar to https://github.com/processing/p5.js-web-editor/issues/2560, raised by @apsinghdev. Referenced here to help organize issues.

**Comment by Ashish020202** [comment]
@PiyushChandra17 please assign this issue to me

**Comment by lindapaiste** [comment]
Good catch.  It's very weird that we don't have any translations for this text.  This might be something where we want to move the text to a translation file and handle it there.  The "a" vs. "an" issue is specific to English, and other languages may have their own quirks.  So we could potentially need a different translation key for each form field.

**Comment by apsinghdev** [comment]
hey @PiyushChandra17 i am not getting such issue 

OS - Windows 11 , Browser - Chrome ( Version 118.0.5993.118 )

![p5i](https://github.com/processing/p5.js-web-editor/assets/109718740/a97508eb-5f76-4101-b5b7-d6d3193ccc4f)

**Comment by lindapaiste** [comment]
> Good catch. It's very weird that we don't have any translations for this text. This might be something where we want to move the text to a translation file and handle it there. The "a" vs. "an" issue is specific to English, and other languages may have their own quirks. So we could potentially need a different translation key for each form field.

It seems like we already have the translation texts!  We just aren't using them in this component.  So this will be easier than I thought.

https://github.com/processing/p5.js-web-editor/blob/a1a5efd44f64f4a449f07379098dcdfe049558eb/translations/locales/en-US/translations.json#L276-L287
