### ISSUE TITLE
Modal box is not responsive

### ISSUE THREAD

**Issue by Praveen03AJJARAPU** [processing/p5.js-web-editor#2501]
### What is your operating system?

Windows

### Web browser and version

Chrome 117.0.5938.149

### Actual Behavior

The modal for adding the file and folder has a fixed width which is incompatible with mobile devices. We have to add the media query to adjust it.

### Expected Behavior

So, I added the media query for the existing modal-content for the device width 500px.

### Steps to reproduce

Actual code:
.modal-content {
  @extend %modal;
  min-height: #{150 / $base-font-size}rem;
  width: #{500 / $base-font-size}rem;
  padding: #{20 / $base-font-size}rem;
  .modal--reduced & {
    //min-height: #{150 / $base-font-size}rem;
  }
}

Changes made:
.modal-content {
  @extend %modal;
  min-height: #{150 / $base-font-size}rem;
  width: #{500 / $base-font-size}rem;
  padding: #{20 / $base-font-size}rem;
  @media screen and (max-width: 500px) {
    width: #{300 / $base-font-size}rem;
  }
  .modal--reduced & {
    //min-height: #{150 / $base-font-size}rem;
  }
}
Please tell me if this is not the method to resolve the issue.

After fix:
![Screenshot 2023-10-13 161806](https://github.com/processing/p5.js-web-editor/assets/97183004/7cedeafe-5905-4303-8e19-7bfa5445d14d)

Before fix:
![Screenshot 2023-10-13 161845](https://github.com/processing/p5.js-web-editor/assets/97183004/e907011d-47e5-4693-8694-c10c6bcc8759)

**Comment by Praveen03AJJARAPU** [comment]
Please assign the issue to me.

**Comment by SableRaf** [comment]
Hey @Praveen03AJJARAPU, thanks for opening the issue and taking the time to describe it in detail. It's awesome that you've even suggested a solution!

However, @dewanshDT already addressed mobile responsiveness for the p5.js Web Editor as part of their GSoC 2023 project. You can check out the details [here](https://github.com/processing/p5.js/blob/main/contributor_docs/project_wrapups/dewansDT_gsoc_2023.md).

So for now, it seems that the specific issue you're pointing out has likely been covered. If you find that this isn't the case, please do let us know and we can revisit it.

**Comment by Praveen03AJJARAPU** [comment]
![Screenshot 2023-10-13 203841](https://github.com/processing/p5.js-web-editor/assets/97183004/04712b44-72f8-4fa1-91db-a3ef7d17c394)

The above screenshot is taken from the original editor, and the issue is still on. Can you please check that, or the editor for the mobile different from the desktop

**Comment by raclim** [comment]
Sorry it took a while, but we just pushed out a new release to the website yesterday, which should be updated with the new Mobile implementation! These components should be responsive now.

**Comment by raclim** [comment]
I'm going to close this for now, but please feel free to reopen this or report other issues, thanks!
