### ISSUE TITLE
Clicking on p5 logo does not refresh the web editor

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2508]
### Increasing Access

Unsure

### Feature enhancement details

Clicking on p5 logo does not refresh the web editor
<img width="52" alt="p5 logo" src="https://github.com/processing/p5.js-web-editor/assets/47579287/5a2e506c-5de2-4ae9-89ec-d457f9ffd3b4">

**Comment by madtitan02** [comment]
i can make theis work  should i directly solve and genrate a PR or do have to get assigned?

**Comment by lindapaiste** [comment]
Related to #2333, where it was suggested that clicking on the logo should take the user to the p5 website.

I am unsure what behavior we want here in the long term.  In the short term, we are unlikely to implement any behavior on the logo.

**Comment by CubeOfCheese** [comment]
I have noticed many of my students click on the logo when I ask them to go to the p5 homepage so that they can look at the reference. This indicates they expect clicking on the logo to link to the p5 homepage. I think opening it in a new tab would be a good way to accommadate this expectation

**Comment by KrishavRajSingh** [comment]
is this open?

**Comment by raclim** [comment]
We closed the other referenced issue to be [potentially planned for later in this board](https://github.com/processing/p5.js-web-editor/projects/11). Since they're similar and we're hoping to discuss it down the line, I'm going to close this one for now.
