### ISSUE TITLE
Aid debugging by highlighting runtime errors console on in code editor

### ISSUE THREAD

**Issue by thepackrat** [processing/p5.js-web-editor#251]
It would be a useful aid to debugging programs if runtime errors printed to the console that had line numbers were also presented to the user as a third highlight colour (blue? green?) with mouse over to the errors being the js console error generated.

**Comment by catarak** [comment]
Just to make sure I'm understanding what you mean, you're thinking of presenting runtime errors in a similar way to the linting errors? This is a cool idea. Do you think it would be difficult to distinguish between linting and runtime errors? is color enough?

**Comment by thepackrat** [comment]
The traditional way to do this in an IDE would be a little alert symbol (triangle sign with ! in it) printed against the line where the error was identified. I think that would work pretty well.

**Comment by zrispo** [comment]
I'm working on this!
