### ISSUE TITLE
Auto-Refresh Button Doesn't Trigger Immediate Refresh

### ISSUE THREAD

**Issue by perminder-17** [processing/p5.js-web-editor#2511]
### What is your operating system?

None

### Actual Behavior

Our current auto-refresh feature doesn't immediately refresh code output when the "auto-refresh" button is clicked. Auto-refresh, which should provide a means for developers to see the output corresponding to the code they've written, currently falls short, potentially leading to inconsistencies between the code and its output.

[issuep5.webm](https://github.com/processing/p5.js-web-editor/assets/127239756/a9fed1e9-c9bf-4e14-a657-6fefd8d08122)

### Expected Behavior

Upon clicking the "auto-refresh" button, the code output should refresh immediately, allowing users to see the impact of their code changes without requiring additional edits.

### Steps:
1. Go to home page
2.Click on auto-refresh.

**Comment by perminder-17** [comment]
@lindapaiste Can i work on this?

**Comment by perminder-17** [comment]
@raclim

**Comment by raclim** [comment]
Thanks for catching this! Yes, please feel free to go ahead and work on it!

**Comment by perminder-17** [comment]
> Thanks for catching this! Yes, please feel free to go ahead and work on it!

Thanks @raclim
