### ISSUE TITLE
 Feature Request - Code Formatting on Save

### ISSUE THREAD

**Issue by skbhagat0502** [processing/p5.js-web-editor#2512]
### Increasing Access

**Feature**
I would like to propose the addition of a new feature to the p5.js web editor - the ability to automatically format code on save.

**Description:**
Currently, users have to manually format their code to ensure consistency and readability. Implementing an option to automatically format the code upon saving a file would greatly enhance the user experience and encourage best coding practices.

**Benefits:**
- Consistency: Ensures a consistent coding style across projects.
- Readability: Improves code readability by enforcing a standardized format.
- Time-Saving: Saves time for users who currently format their code manually.

### Feature request details

Description:
Currently, users have to manually format their code to ensure consistency and readability. Implementing an option to automatically format the code upon saving a file would greatly enhance the user experience and encourage best coding practices.

**Comment by skbhagat0502** [comment]
@lindapaiste @raclim I would like to know your views on this. Should I work on this issue. I am thinking to use prettier for this, the most popular code formatting library. If yes then please assign me this task.

**Comment by rajatmohan22** [comment]
This might just be me; but I feel newcomers might struggle to adapt to an automatic formatting system as they need to understand and adjust to the tool's conventions and settings.

**Comment by raclim** [comment]
Agree with @rajatmohan22 there as well. Some of the pros/cons here feel identical to the currently implemented Autocomplete feature—while some love it, other users have noted it to be confusing, overwhelming, or overstimulating. There's actually a [study on Web Editor Features in the Classroom](https://arxiv.org/pdf/2301.13302.pdf) that delves into more about this that is an interesting read!

**Comment by Akhilbisht798** [comment]
Auto formatting on auto save sounds good, but I would personally not like it due to sudden change of code when I'm trying to concentrate on a line, and it suddenly moves or changes.

**Comment by apsinghdev** [comment]
> Agree with @rajatmohan22 there as well. Some of the pros/cons here feel identical to the currently implemented Autocomplete feature—while some love it, other users have noted it to be confusing, overwhelming, or overstimulating. There's actually a [study on Web Editor Features in the Classroom](https://arxiv.org/pdf/2301.13302.pdf) that delves into more about this that is an interesting read!

Instead of Auto Formatting feature, it would be okay if we add a separate button for it that would format the document when clicked. 

that button can be added below 'Save'

![p5-issue](https://github.com/processing/p5.js-web-editor/assets/109718740/5264aa9e-7349-4c62-8ae0-77f3e29e1afb)


can I work on it?

**Comment by raclim** [comment]
We do currently have a "Tidy Code" button under "Edit" at the moment, which I think accomplishes this! 

After reflecting on this for a bit I'm not sure if we'd be ready to implement something like this at the moment. I'm going to close this for now, but would be open to revisiting this in the future!
