### ISSUE TITLE
Dark theme toggle button on Main page

### ISSUE THREAD

**Issue by madtitan02** [processing/p5.js-web-editor#2513]
### Increasing Access

I suggest that it would be better to add a dark theme toggle button or theme drop-down menu on the main page/every page so that It will be easier for the user to switch themes, Instead of going through settings.

drop-down

### Feature enhancement details

Adding a toggle button / dropdown menu here at highlighted area would provide more accessibility to the userbutton/dropdown
![Screenshot 2023-10-19 013600](https://github.com/processing/p5.js-web-editor/assets/96717231/2f3d2b07-e407-4a08-b96b-60044ece287c)

**Comment by madtitan02** [comment]
@lindapaiste  if the community agrees can i start working on it I can submit a test pr if you want

**Comment by lindapaiste** [comment]
We don’t want to overwhelm the user with too many buttons so we should only put the ones which are most important.  In my opinion I don’t think theme switching is important enough to give it that much screen real estate.  Most users are likely to set the theme once to the one that they prefer and then never change it.  I doubt that many people are switching back and forth regularly.

**Comment by aspired2001** [comment]
Hi please assign me to this issue

**Comment by madtitan02** [comment]
> We don’t want to overwhelm the user with too many buttons so we should only put the ones which are most important. In my opinion I don’t think theme switching is important enough to give it that much screen real estate. Most users are likely to set the theme once to the one that they prefer and then never change it. I doubt that many people are switching back and forth regularly.

But those user who have not logged in find it difficult to turn it on or off as many cant find if the dark theme is even present or not ,And i don't think so it will take too much space and turning it on off will  be easier for them also clicking on setting opens setting dialogue box ,Which further freezes the background so i think providing a small button should be convenient for the user,As many code editor websites do provide and i personally as a user find them very convenient to use.I

**Comment by Abhi1992002** [comment]
i think we should make dark theme as default (becuase it provides good user experience) and if user want to shift to light theme , he can do it using a toggle button.

**Comment by prajwalbandak** [comment]
hey @lindapaiste , If the community agreed for toggle button.Can you assign to me, will start working on it. please confirm.

**Comment by madtitan02** [comment]
> > We don’t want to overwhelm the user with too many buttons so we should only put the ones which are most important. In my opinion I don’t think theme switching is important enough to give it that much screen real estate. Most users are likely to set the theme once to the one that they prefer and then never change it. I doubt that many people are switching back and forth regularly.
> 
> But those user who have not logged in find it difficult to turn it on or off as many cant find if the dark theme is even present or not ,And i don't think so it will take too much space and turning it on off will be easier for them also clicking on setting opens setting dialogue box ,Which further freezes the background so i think providing a small button should be convenient for the user,As many code editor websites do provide and i personally as a user find them very convenient to use.I

@lindapaiste what are your views on this , if you wish to proceed and other members agree do assign me I will make a review pr soon.

**Comment by raclim** [comment]
Thanks for all of your input on this! I don't think this is something we're planning to prioritize in the near future, and might want to get some further design consultation down the line on before jumping into incorporating elements like this so I'm going to close this for now. I'm also going to place this issue into [this board](https://github.com/processing/p5.js-web-editor/projects/11) for now to revisit later on if when we do revisit the design!
