### ISSUE TITLE
Create new folder not working

### ISSUE THREAD

**Issue by madtitan02** [processing/p5.js-web-editor#2516]
### p5.js version

v2.8.0

### What is your operating system?

Windows

### Web browser and version

118.0.2088.46

### Actual Behavior

When clicking on Create a new folder, it should create a new one, but it does not create any one. It displays the following error in the console.
![Screenshot 2023-10-19 020228](https://github.com/processing/p5.js-web-editor/assets/96717231/8564d808-910e-4a7f-be9c-9cac1265db7e)

### Expected Behavior

It should create a new folder, which was filled in create folder dialogue box.

### Steps:
1.click on the sketch drop-down menu
 2.click on add folder
 3.create a new folder
### Snippet:
```js

// Paste your code here :)

```

**Comment by madtitan02** [comment]
@lindapaiste if the community agrees can i start working on it I can submit a test pr if you want

**Comment by lindapaiste** [comment]
Hmmm 🤔 we just rolled out a new version to production today but I’m not sure which change would have led to a 403 forbidden from the API.  Maybe something with `passport`?  You can definitely work on this since it’s a bug.

**Comment by madtitan02** [comment]
Do i have to get assigned to work on it or directly can I start? And I am looking into the documentation first and will let you know the updates on it.

**Comment by madtitan02** [comment]
@lindapaiste, it is working now I have crosschecked it once again I don't know why it happened last time.

**Comment by lindapaiste** [comment]
I’m glad it was nothing! Since we just pushed a new version it might be that you needed to log out and log in again to apply the changes, or something along those lines.
