### ISSUE TITLE
Autocomplete Should Be Set to "Off" in Preferences

### ISSUE THREAD

**Issue by raclim** [processing/p5.js-web-editor#2520]
### p5.js version

1.7.0

### What is your operating system?

Mac OS

### Web browser and version

118.0.5993.70 (Official Build) (arm64) 

### Actual Behavior

While many have enjoyed this feature so far, some educators have reported that students who are new to programming have had difficulty adjusting to using Autocomplete in their courses, and would prefer the default preference for this feature to be "Off". 

I initially changed a few files in [this commit](https://github.com/processing/p5.js-web-editor/commit/836ecac8f3161e9fde45ffd46baed4f0bc970c46) to address this, but missed line 77 of `server/models/user.js`, which I think is causing this to persist. 

### Expected Behavior

For the Default Preference for the Autocomplete Hinter to be set to "Off"!

**Comment by lsdebianchi** [comment]
Hello,

This is very interesting. I had that suspicion when I discovered that p5.js had in fact an autocomplete feature but that it was hidden by default.

Do you have more information regarding the decision? Or more extensive feedback from the educators?
Is not to argue against the change. I fully understand it. But it would be important to me to gain a better understanding on the matter.

Autocomplete is my best friend when programming, as it help my faulty human memory, my bad typing and sometimes is invaluable as an in-code documentation for APIs which I am to lazy to discover by browsing documentation websites. So part of me feels that it has a special value. It's similar to how in Scratch you can see the building blocks on the left. It removes some paralysis and guesswork.

The fact that this may not translate to a beginner is an important consideration. Why not?
I can imagine that it is overwhelming when you type your first letters to be hit by a wall of alien looking options. But is it just that? I would love to hear more about the topic.
