### ISSUE TITLE
Issue with Replace Behavior in p5.js Web Editor

### ISSUE THREAD

**Issue by perminder-17** [processing/p5.js-web-editor#2523]
### What is your operating system?

None

### Actual Behavior

Currently, when the arrow keys are pressed without entering text for replacement, it opens the find elements box.

https://github.com/processing/p5.js-web-editor/assets/127239756/0bed3aac-e0c8-4faa-ab12-87b7361da9d1

### Expected Behavior

When the "Replace" box is open, pressing the arrow keys should navigate to and focus on the find elements in the "Replace" block itself as soon as text is entered for replacement.

### Steps:
1.Open the p5.js web editor.
2. Use the "Replace" functionality (Ctrl+F) without entering any text for replacement.
3. .Press the arrow keys (^ and V) for previous and next, respectively.

**Comment by perminder-17** [comment]
[screen-recording.webm](https://github.com/processing/p5.js-web-editor/assets/127239756/dc172567-c190-471b-b626-27e140503944)

also from this issue i want to correct this one. Preview is coming inside the block of replace.

can i work on this @raclim and @lindapaiste ?

**Comment by perminder-17** [comment]
And one more thing @raclim, I've noticed some important priority bugs related to mobile responsiveness. I'm wondering if I should start working on them or the work still going on? @lindapaiste

**Comment by lindapaiste** [comment]
Ooof.  The behavior that you are seeing in your video is definitely a bug!  Feel free to work on it.

@dewanshDT’s GSoC project is done so I don’t think he’s actively working on anything at the moment.  We finally rolled out his UI and it a huge improvement but we are aware that it’s not perfect.  So if there are specific mobile/responsive issues that you want to fix then feel free to work on them.

**Comment by perminder-17** [comment]
Ok, @lindapaiste Going to fix this asap

**Comment by perminder-17** [comment]
Sorry @raclim for being inactive for this issue. I was a little busy with working on filter() function in p5.js. I will fix this very soon.

**Comment by kirtanchandak** [comment]
Hey, @perminder-17 are you still working on this or should I pick this one?

**Comment by perminder-17** [comment]
> Hey, @perminder-17 are you still working on this or should I pick this one?

Actually I am working on it. If i am unable to do it, i will text you, then you may pick this one.
