### ISSUE TITLE
Replace random sketch name generator with a more predictable naming pattern

### ISSUE THREAD

**Issue by mkmori** [processing/p5.js-web-editor#2528]
### Proposal
I propose the random sketch name generator be replaced by a more predictable and informative, default sketch name, such as "sketch [user name or id] [yyyy-mmdd-hhmm-ss]", similar to that used in the Processing.org Java IDE as of v4.3 ("sketch [yymmdd][alpha character]").

An example for consideration:
**sketch username 2023-0121-1105-00**

I think "sketch" may be omitted, or part of the UI. Note "sketch" is already the default js file name ("sketch.js"):
**username 2023-0121-1105-01**

The sketch ID itself might be an option, (as it appears in the sketch URL)--it might be an esp. good option if it is already assigned (and could be sorted) sequentially. (At a glance, I'm unsure.)

### Rationale (Increasing Access)
As amusing, even inspiring as it may be at times, I believe the random sketch name generator also poses avoidable functional, ethical, and practical issues. Meanwhile, a more straightforward, informative naming scheme could provide additional, practical benefits to a greater number of users, (esp. newcomers to coding and p5.js).

Briefly:
1. Randomly generated sketch names are not consistently, universally beneficial to users, esp. in learning to code with p5.js.
2. Both the humor and the offense-avoidance strategies are culturally specific and potentially alienating, esp. for coding students of differing English language proficiency or idiom.
3. Random culturally or personally appropriate names are difficult or impossible to ensure, esp. as the user community grows in diversity.
4. Unintentional and inappropriate names unnecessarily burden both developers and users.

Respectfully submitted to the p5.js community for further consideration!

### Feature enhancement details

My own arguments are recorded in detail here, where I also hope to solicit thoughts and opinions from the broader community to help inform design decisions regarding the sketch name generator:
(https://discourse.processing.org/t/proposal-for-web-editor-replace-random-sketch-name-generator/43023)

The random sketch name feature is the subject of past and current issues:
(https://github.com/processing/p5.js-web-editor/issues/2247) ("friendly-words" issue)
(https://github.com/processing/p5.js-web-editor/pull/2258) ("friendly-words" issue resolution)
(https://github.com/processing/p5.js-web-editor/issues/1589) (translation issue)
(https://github.com/processing/p5.js-web-editor/issues/2526) (saved sketch display name issue)
~~(https://github.com/processing/p5.js-web-editor/issues/2256) (improper loading--apparently unrelated)~~

**Comment by skbhagat0502** [comment]
@mkmori I want to work on this issue.

**Comment by lindapaiste** [comment]
Just a quick note that #2256 is not related.  That issue has to do with transforming relative file paths to absolute paths.

**Comment by mkmori** [comment]
The issue has not engendered much discussion...but @skbhagat0502, if you're up for it, I think the proposal would certainly benefit from some functional code!

In terms of approving the change--the governance of this project is a bit opaque to me--but to help inform the decision, perhaps a poll would be less taxing than discourse for a greater part of the community...?

**Comment by raclim** [comment]
Thanks for raising this issue and laying out your thoughts on it! 

I feel that there has been a lot of positive past feedback to the random sketch name generator because of the playfulness it lends to an activity/environment that might be intimidating for users who are using these types of tools for the first time! 

I do also feel that the points you've raised are extremely valid and there could be more thought on avoiding harmful names being generated more proactively vs reactively. Since there hasn't been much traction on this issue so far I think for now this isn't something we're planning to tackle in the near future, but would definitely be open to revisiting this if other folks raise this again!
