### ISSUE TITLE
Add visual indication for console messages when console is minimised

### ISSUE THREAD

**Issue by thepackrat** [processing/p5.js-web-editor#253]
Could the minimised console bar have a visual indication that it contains messages, manual or auto-generator errors. This would help for folks who don't reflexively have a JS console open when they are writing js code.

**Comment by catarak** [comment]
you're not the first person to report some confusion with the console messages. anyone have thoughts for a design for this?

**Comment by thepackrat** [comment]
I suggest that a flashing arrow pointing to the console opening control would probably be a reasonable alert. Cleared when the console was opened until a new message was 

This might need a slight change when runtime error messages are displayed like linting errors.

**Comment by catarak** [comment]
For now I've made the console open by default, closing for now. If further discussion needs to be had we can reopen this or make a new ticket.
