### ISSUE TITLE
Show password eye button disappears after clicking on other section of screen

### ISSUE THREAD

**Issue by madtitan02** [processing/p5.js-web-editor#2533]
### p5.js version

v2.8.0

### What is your operating system?

Windows

### Web browser and version

118.0.2088.46 

### Actual Behavior

When using the sign up feature, The create password input box contains an eye button to show or hide the password,It should display the password when clicked,But the eye button disappears after I click on other input box and come back to the password input box.

### Expected Behavior

The actual behaviour should be the eye button should remain even after switching the input box.Below is the screen recording of the issue

https://github.com/processing/p5.js-web-editor/assets/96717231/6dff00eb-78b3-48d0-a57c-d2165a44e029

### Steps:
1.Click on Signup button
 2.create password
 3.Click on any other input box
4.Switch back to the create password input box

**Comment by madtitan02** [comment]
@lindapaiste @raclim do assign me this issue so that I can start working on it

**Comment by leftover19** [comment]
![image](https://github.com/processing/p5.js-web-editor/assets/113136731/5e9e8e9c-23d3-4082-8e22-6d5e3e8e9221)

As of now, there's no eye button for password input, not for login also.

**Comment by madtitan02** [comment]
> ![image](https://user-images.githubusercontent.com/113136731/277664727-5e9e8e9c-23d3-4082-8e22-6d5e3e8e9221.png)
> 
> As of now, there's no eye button for password input, not for login also.

is it mobile version? Because 
![Screenshot 2023-10-24 183213](https://github.com/processing/p5.js-web-editor/assets/96717231/7aba6a27-81e3-4b33-abd4-d3b65bce2423)
it is there on the website

**Comment by leftover19** [comment]
I'm not using mobile version. It's not there on web. 
ps : I double checked the url, tried on incognito ,  pull latest changes, running on localhost, still no eye button.

**Comment by madtitan02** [comment]
Is there any builtin feature in Microsoft edge to show passwords or something cause in Microsoft edge it is displaying this issue even in incognito mode ,But when I did checked it on firefox eye button is not there as you mentioned.

**Comment by leftover19** [comment]
I don't know for sure, but there could be. I remember #2466 was created to add this functionality and is open as of now.

**Comment by lindapaiste** [comment]
I'm going to close this issue because this particular eye icon is coming from your browser.  Turns out that it is a [built-in feature of Microsoft Edge](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal), which I didn't know! What you are seeing is [expected](https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal#visibility-of-the-control).

> If focus moves away from the password field, the browser removes the password reveal button.

When we add our own eye icon we will need to make sure that it works properly in Edge and that we don't end up with two eyes (built-in and custom).
