### ISSUE TITLE
Code folder ( or collapser ) for .html files

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#2537]
### Increasing Access

The proposed feature enhancement would enable users to fold the tags for the HTML files. This would enhance accessibility by providing a more organized and user-friendly interface for users who work with HTML files in the editor.

### Feature enhancement details

This feature enhancement aims to bring the convenience of code collapsers, which are already available for CSS and JS files, to HTML files in the p5.js Web Editor. Code collapsers allow users to collapse and expand sections of code for improved organization and a better user experience.

Example : 
![Screenshot 2023-10-27 003231](https://github.com/processing/p5.js-web-editor/assets/80570105/a045b029-da92-43ca-98a1-f4c89ab923d6)

Can I work on this @raclim and @lindapaiste ?

**Comment by AbhishekCS3459** [comment]
@Ri-Sharma I want to work for this issue

**Comment by raclim** [comment]
I think this would be a great addition! Here's the issue https://github.com/processing/p5.js-web-editor/issues/382 and pull request https://github.com/processing/p5.js-web-editor/pull/407 that initially implemented the code collapsing (or cold folding) for reference.

**Comment by mhsh312** [comment]
Hi @Ri-Sharma are you still working on this? If so, do you need help with something?

**Comment by Ri-Sharma** [comment]
Hey @mhsh312 yes, I'm currently working on it, and at the moment, I don't need any help. I'll definitely reach out if I need assistance in the future. I appreciate your willingness to help.

**Comment by apsinghdev** [comment]
hey @Ri-Sharma can you please assign me this? if you are not working on it.

**Comment by Ri-Sharma** [comment]
> hey @Ri-Sharma can you please assign me this? if you are not working on it.

@apsinghdev Yeah, I am currently working on this.

**Comment by mhsh312** [comment]
Crazy how it only took one import statement. Good catch.

**Comment by Ri-Sharma** [comment]
> Crazy how it only took one import statement. Good catch.

Yeah, but it took me embarrassingly long.😅
