### ISSUE TITLE
editor about section responsiveness 

### ISSUE THREAD

**Issue by achyutvardhan** [processing/p5.js-web-editor#2538]
### What is your operating system?

Windows

### Actual Behavior

![image](https://github.com/processing/p5.js-web-editor/assets/91366441/25325077-6947-4a4b-a39c-9073a1bf99c0)

### Expected Behavior

It must display full **ABOUT** list 

![image](https://github.com/processing/p5.js-web-editor/assets/91366441/0386eb07-dfbd-4362-b630-fb298051fcc0)

### Steps to reproduce
1. Go to inspect 
2. change the window width to 690 or less.

@dewanshDT  can guide through this

**Comment by achyutvardhan** [comment]
@dewanshDT  I have addressed this issue can you help me to correct this

**Comment by shubhexists** [comment]
Hey @achyutvardhan !
I guess the about section changes after 770 px width. I have tested it on Firefox and Chromium.

**Comment by achyutvardhan** [comment]
> Hey @achyutvardhan ! I guess the about section changes after 770 px width. I have tested it on Firefox and Chromium.
No its 649px . i have tested in chrome . issue is from 650px to 770px

![image](https://github.com/processing/p5.js-web-editor/assets/91366441/3bbbe3fb-e10a-401b-aab1-c3ef435a26fa)

**Comment by lindapaiste** [comment]
>  issue is from 650px to 770px

Thanks for the clarification.  With some playing around I can see the problem.  I happens when the width is small **AND the height is too small** to fit the content below it.  We would want a vertical scrollbar inside the modal in that situation.

**Comment by shubhexists** [comment]
Got it! It was the height! Would try to work on it.

**Comment by yashpandey06** [comment]
I wonder if anyone working on this issue, please let me know if no one is working i can go on to resolve this issue

**Comment by Kiran1504** [comment]
I have created pr please review it and merge it. Thank you.
