### ISSUE TITLE
p5 js Server Not updating on Saving in VS

### ISSUE THREAD

**Issue by Typicalcodes** [processing/p5.js-web-editor#2539]
### What is your operating system?

Windows

### Web browser and version

1.59.117 Chromium: 118.0.5993.70 (Official Build) (64-bit)

### Actual Behavior

Sorry for this weird request but I am having a problem that when I am saving the files in vs code it doesn't update the server on changing. That's why I am unable to get the result fast. So i have to re run all the process from docker to vs code server for getting the updated changes which almost takes 7-8 minutes.. And I don't have a potato PC too,

### Expected Behavior

I want to update the server on updating the files as fast as possible.

### Steps:
1. Go through Docker installation 2. run the server  3.save the files after some change
### Snippet:
```js

// Paste your code here :)

```

**Comment by Karanpal97** [comment]
yes i was also getting this issue so yesterday i switched to ubuntu from the windows and things are working fine

**Comment by Typicalcodes** [comment]
is there any way to run it on windows properly.

**Comment by mhsh312** [comment]
Same issue for me. I did manual installation instead and that fixed it. Docker on windows is just not a good experience.

**Comment by Typicalcodes** [comment]
I made mistake by not properly following the guides. I should have used nvm to install the node version 16.14.1 that's why i got into problem. Previously I was working on latest node version.

**Comment by Typicalcodes** [comment]
I made mistake by not properly following the guides. I should have used nvm to install the node version 16.14.1 that's why i got into problem. Previously I was working on latest node version. I have done this in local environment. Running in docker is still a mess.
