### ISSUE TITLE
Disable older auto-save (with notification message) if sketch is opened twice

### ISSUE THREAD

**Issue by thepackrat** [processing/p5.js-web-editor#254]
I can't get to the other computer to confirm, but the most consistent explanation is that an open copy of the sketch I was trying to work on was still open in a browser window on another computer and was auto-saving back over the top of the copy I was working on.

The symptom was the sketch reverting to an earlier version on page reload or reopen, despite the current changes being recorded as saved in this session. I fixed it by making a copy and happily editing that one.

A notification that this is happening would be nice, but this case, there was no way to get to the rogue session that was autosaving the older version of the sketch.

**Comment by catarak** [comment]
This is an interesting bug... maybe autosave should be disabled if a user isn't actively working on a page, or the sketch on that page hasn't been edited in a while? I think the optimal situation would be to have everything connected with websockets, so all changes are propagated to all open sketches.

**Comment by thepackrat** [comment]
That would be ideal, but perhaps this would work as a way of preventing interim surprise while the more complex architecture comes together. 

Having autosave disabled automatically by a pause could yield considerable user surprise if, e.g. a small child went out to play and then came back to fiddle with a sketch without realising they needed to hit save again.

**Comment by thepackrat** [comment]
Similarly, if an edit would re-activate it, a user coming back to the abandoned computer who touched the still active sketch would have the ability to overwrite all new changes to the sketch. That seems too much like a rake in the grass.

**Comment by catarak** [comment]
You're right, figuring out a system for disabling/enabling auto save based on a sketch being idle has a lot of edge cases. Are you saying that you think using web sockets is the best option right now or do you have another idea?

**Comment by thepackrat** [comment]
If the goal is to have multiple copies updating simultaneously, web sockets seem like a reasonable way of getting there, but that comes with a bunch more difficult corner cases, not least trying to to real-time change deconfliction.

For a more straightforward thing, does every version of a particular file have a unique and increasing version number? Every buffer could keep track the version it was trying to save from and have the auto-save call report that. If the version had changed from that expected, the (auto) save should fail, paint a big colourful message at the top about the buffer being changed from another computer, and stop autosaving.

The options should be "reload" at that point, with an open issue to get some sort of simple diff/merge in place. An option to save your unrealised changes just as a new sketch seems a pretty good recovery without lots of extra development, but it would be really helpful if there was some way to see what had changed.

**Comment by catarak** [comment]
As of right now, the projects do not have a version number, however they do have a last saved time, which could be used in basically the same way.

**Comment by catarak** [comment]
Another thought is that I'm using `setInterval` to do the autosaving--if I use `requestAnimationFrame`, then autosave wouldn't run unless the window/tab was selected.

**Comment by thepackrat** [comment]
In the particular case, the window was selected on the unused computer, with a screensaver active. Not sure what that would do. 

I worry that the animationframe solution would let you wipe your changes by unburying a tab containing an older version you'd forgotten you had open.

**Comment by catarak** [comment]
Sorry, wasn't clear--I meant to say I think the solution is to use both requestAnimationFrame and timestamps :smile:

**Comment by catarak** [comment]
This should be fixed now. I basically changed two things:
- The conditional logic for when to autosave has changed. Instead of saving every 30 seconds, it saves after 30 seconds only if there have been changes to a project. It will also only begin autosaving if a user has manually saved the project once. 
- If a user attempts to save a project and the last updated time on the server is greater than the last updated time on the client (i.e. the project has been updated from another browser window or tab), the editor will display an error.

**Comment by shiffman** [comment]
@catarak is this the error message?  I'm seeing it erroneously a bunch (I think).  I will track down to try to reproduce and file a new issue.

<img width="548" alt="screen shot 2017-01-25 at 1 27 00 pm" src="https://cloud.githubusercontent.com/assets/191758/22303602/fe5b3ef4-e301-11e6-8cd5-c9b65383c07e.png">

**Comment by catarak** [comment]
yeah, I can turn it off for now and test more locally.
