### ISSUE TITLE
Feature Request: Improve Project Management with Folder and File Icons

### ISSUE THREAD

**Issue by sanjay-sol** [processing/p5.js-web-editor#2540]
### Increasing Access

The motivation behind this feature request is to make project management more intuitive and efficient. By incorporating these icons and functions, users will have immediate access to common project management tasks, similar to the experience provided by popular code editors such as Visual Studio Code. This feature promotes streamlined project organization, saving time and effort in everyday project management tasks.

### Feature request details

Feature Details:
I propose the addition of icons and functionality to the project management interface to enhance folder and file management within the project. This feature is designed to provide users with convenient tools for organizing their project's directory structure and improving overall usability.

-- Folder and File Icons:

- Create Folder Icon:   A new icon, represented by a folder emoji (📁), will be added next to the project name. When users click this icon, it will trigger the creation of a new folder within the project's directory structure. This action aims to streamline the process of creating project folders and organising project content.

 - Create File Icon:   An additional icon, depicted as a document emoji (📄), will also be positioned alongside the project name. Clicking this icon will open a dialog or form that allows users to create new files within the project directory. This functionality simplifies the task of adding and managing project files.

- Collapse Files Icon:  Collapse All Files Icon: A third icon (⇩) will be introduced to provide users with the ability to collapse or fold all opened project files. This action will enhance project navigation and user experience by allowing users to declutter the interface and focus on specific files when necessary.

You can find sample screenshots resembling the desired functionality from VS Code 

<img width="380" alt="p5-fr-1" src="https://github.com/processing/p5.js-web-editor/assets/114111046/243f764f-2d75-4c29-b56c-6b8c08f33aa4">

in the following location:  

<img width="380" alt="p5-frs-1" src="https://github.com/processing/p5.js-web-editor/assets/114111046/27f2aafb-c672-4792-9110-44f44badb6b8">

 I aim to implement similar features within the p5.js-web-editor, enhancing user experience and project management

**Comment by sanjay-sol** [comment]
Hello @lindapaiste  and @raclim ,

If the community is in agreement, I'd be happy to contribute by submitting a pull request for a review or a rewrite .

**Comment by mhsh312** [comment]
I think this should be divided into two tasks: folder task and icon task. 
I would be down to contribute to either. Please assign it to me.

**Comment by mhsh312** [comment]
I'd be happy to work on this as well.

**Comment by yashpandey06** [comment]
@sanjay-sol have you implemented that ??

**Comment by sanjay-sol** [comment]
@yashpandey06 , Yeah almost completed but I should wait until they assign me ..!

**Comment by sanjay-sol** [comment]
Hello @lindapaiste and @raclim,
I'm in the process of working on the feature request issue, and I wanted to inquire about your availability to discuss it. I've made significant progress and I am currently halfway through the task. If you are in agreement with the proposed feature, I can finalise the implementation and submit a Pull Request. I'm truly enthusiastic about contributing to this foundation and look forward to your feedback.

**Comment by KrishavRajSingh** [comment]
Hey @sanjay-sol  
It's been a month, if you are not working on it, please let me know.

**Comment by KrishavRajSingh** [comment]
I am thinking to leave collapse file Icon as it is not that necessary plus it will take more space.
If we try to fit four icons, the font size will become excessively small.
![image](https://github.com/processing/p5.js-web-editor/assets/99531396/373524ba-5717-4733-86fa-b04ede817702)

what are your views about it??
