### ISSUE TITLE
p5.new shourcut url

### ISSUE THREAD

**Issue by eyaler** [processing/p5.js-web-editor#2541]
### Increasing Access

Yes! I want this for my students to jump into a new editor session.

### Most appropriate sub-area of p5.js?

- [ ] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [ ] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [X] Other (specify if possible)

### Feature enhancement details

Do you know about [whats.new](https://whats.new), [get.new](https://get.new)? Would be wonderful to have our own [p5.new](https://editor.p5js.org/) to open a fresh https://editor.p5js.org/

**Comment by limzykenneth** [comment]
`.new` domains are pretty expensive at $400+/yr depending on registrar so I can't say I recommend it necessarily. Also with the default editor link of `editor.p5js.org` you are already taken to a new editor session so I'm not sure what this will bring though.

**Comment by raclim** [comment]
I have noticed an issue in the editor recently where sometimes I have to click File > New twice in order to trigger the action. I wondering if others have also been experiencing this, and if what @eyaler is trying to suggest could be related to that?

**Comment by lindapaiste** [comment]
> I have noticed an issue in the editor recently where sometimes I have to click File > New twice in order to trigger the action. I wondering if others have also been experiencing this, and if what @eyaler is trying to suggest could be related to that?

I hadn't noticed that before but now I see it 😱.  I'm thinking we should close this and create a new issue for that bug?
