### ISSUE TITLE
Adding unique file type icons for different file types

### ISSUE THREAD

**Issue by mhsh312** [processing/p5.js-web-editor#2542]
### Increasing Access

Adding file type icons makes it quicker to spot files of a certain type. It would makes the UI more aesthetically pleasing.

### Feature request details

Right now, the p5 web editor shows a generic file icon for all types of files.
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/8394fa7a-86e3-4063-a6d5-6b383796e71a)

I am proposing that we add different icons for different file types supported by the editor. 

Example:
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/b5df6eea-ffa5-48ca-8bf4-daad4bb9ee93)

**Comment by mhsh312** [comment]
A good way to do this would be to create a React component and pass the file type as a prop to said component. That way it can work with future supported file types like typescript as well. 
I would be down to work on this feature.

**Comment by lindapaiste** [comment]
I'm glad that you've opened this for discussion because this is definitely something that I would like to implement!  We need to decide what type of icons we would like to use.  You can check out a lot of options on the [React Icons website](https://react-icons.github.io/react-icons/search?q=html).

Something like this [BsFileType](https://react-icons.github.io/react-icons/search?q=bsfiletype) set is much more subtle than your example (from vscode?).  Is that a good thing? Or do we prefer something that's very obvious?
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/3c893487-9fd5-400e-9e25-e4df7ce56d60)

**Comment by mhsh312** [comment]
You're right. The VS Code icon pack was just for an example. I don't think it would suit the minimal UI of p5 editor. 

And yes React Icons would be good but I think the BSfiletype icons are a little too subtle to the point here they are hard to distinguish. I think the [Aioutline](https://react-icons.github.io/react-icons/search?q=aioutline) icons would look better.
You think I should make a PR draft?

**Comment by lindapaiste** [comment]
> You're right. The VS Code icon pack was just for an example. I don't think it would suit the minimal UI of p5 editor.
> 
> And yes React Icons would be good but I think the BSfiletype icons are a little too subtle to the point here they are hard to distinguish. I think the [Aioutline](https://react-icons.github.io/react-icons/search?q=aioutline) icons would look better. You think I should make a PR draft?

If you want to start working on the code that would be fine.  We're probably going to spend some time debating icons, but that will have little impact on code itself.  You can look at #2232 as an example of something similar.

**Comment by lindapaiste** [comment]
Here's another source for ideas (not sure of the license on these) https://jetbrains.design/intellij/resources/icons_list/

**Comment by mhsh312** [comment]
On it.

**Comment by yashpandey06** [comment]
@mhsh312  Are you working on this issue ??

**Comment by mhsh312** [comment]
> @mhsh312 Are you working on this issue ??

Already posted a [PR](https://github.com/processing/p5.js-web-editor/pull/2550) that closes this issue. Just need further discussion with the maintainers about the icon types.

**Comment by yashpandey06** [comment]
@mhsh312  have you posted the pr for this particular issue... i can't see one

**Comment by mhsh312** [comment]
> @mhsh312 have you posted the pr for this particular issue... i can't see one

https://github.com/processing/p5.js-web-editor/pull/2550

**Comment by mhsh312** [comment]
> @mhsh312 have you posted the pr for this particular issue... i can't see one

![image](https://github.com/processing/p5.js-web-editor/assets/135870090/85896abf-aa5b-4ac1-adfc-6e3a3e6f3ada)

Click on the blue text.

**Comment by yashpandey06** [comment]
@mhsh312 got it ..
