### ISSUE TITLE
Reveal of Drop Down list on Hover

### ISSUE THREAD

**Issue by apsinghdev** [processing/p5.js-web-editor#2544]
### Increasing Access

This proposed feature idea enables users to access the drop-down list by hovering over it. This would enhance accessibility by saving time (preventing the need to click the elements), minimizing effort, and providing a smoother user experience.

### Feature enhancement details

This feature enhancement aims to allow a user to reveal the drop-down list of the following elements in the header by hovering over them. This would make the use of the Header easy and smooth.

![p5-headr](https://github.com/processing/p5.js-web-editor/assets/109718740/6c52ee62-0db1-49ac-a474-36506d166255)

Something like this 

![p5-enh](https://github.com/processing/p5.js-web-editor/assets/109718740/61b0b0a6-6926-440f-beca-3aafe256402e)

Can I work on this @raclim and @lindapaiste ?

**Comment by lindapaiste** [comment]
The behavior we have now is that the user has to click on one of the menu items to enable interaction, and then hovering is enabled until the menu is closed. This is a conscious decision as we didn't want menus flying out everywhere if the mouse happens to go over the header. That would make it harder to interact with the toolbar buttons (like play and stop) which are below the header.

See #443
> This may just be me and my own incompetence (as well as the smaller resolution I'm using with a classroom projector), but I am finding while teaching that I'm activating the top menus by accident often. For example, I end up clicking File --> New when meaning to just click run.
> 
> Should they require a click rather than a rollover?

**Comment by im-alok** [comment]
I can fix the issue,Kindly allow me to work on this project

**Comment by yashpandey06** [comment]
@lindapaiste  agree with you it would increase the complexity of the user who is new to p5-web-editor website

**Comment by rajatmohan22** [comment]
> @lindapaiste agree with you it would increase the complexity of the user who is new to p5-web-editor website

lol I don't think this is specific to the p5 editor. In general, having dropdown menus fly all across the screen when the mouse hovers over them seems like poor UI design.

**Comment by apsinghdev** [comment]
> The behavior we have now is that the user has to click on one of the menu items to enable interaction, and then hovering is enabled until the menu is closed. This is a conscious decision as we didn't want menus flying out everywhere if the mouse happens to go over the header. That would make it harder to interact with the toolbar buttons (like play and stop) which are below the header.
> 
> See #443
> 
> > This may just be me and my own incompetence (as well as the smaller resolution I'm using with a classroom projector), but I am finding while teaching that I'm activating the top menus by accident often. For example, I end up clicking File --> New when meaning to just click run.
> > Should they require a click rather than a rollover?

recently I was using a very popular video editor davinci resolve and when I observe it's functionality, I got to know that p5 editor's current drop down list functionality is very much logical comparing to what is proposed. so i totally agree with you guys. Thank you so much for feedbacks
