### ISSUE TITLE
Hovering the cursor over `Auto-refresh` does not change the background text color to `ED225D`

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2545]
### p5.js version

2.9.0

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

Hovering the cursor over `Auto-refresh` does not change the background to `ED225D`
<img width="128" alt="Auto-refresh" src="https://github.com/processing/p5.js-web-editor/assets/47579287/608225a4-f61a-4edd-88b0-9a9f886cbdf2">

### Expected Behavior

Hovering the cursor over `Auto-refresh` should change the background to `ED225D`

### Steps:
1. Open the web editor app
2. Hover cursor over auto-refresh
3. Notice the background text color does not change

**Comment by lindapaiste** [comment]
Good suggestion.  Clicking on the text changes the checkbox so it should look clickable.  I also notice that the `cursor: pointer` is only on the checkbox itself and not the text "Auto-refresh".

**Comment by Ananadharajan** [comment]
I'd like to work on it. Could you please assign me to the task?

**Comment by Neeraj-gagat** [comment]
I'd like to work on this issue. can you please assign it to me ?

**Comment by PiyushThapaa** [comment]
I can fix it can you assign it to me?

**Comment by PiyushChandra17** [comment]
@lindapaiste Can you please review this [PR](https://github.com/processing/p5.js-web-editor/pull/2552)? Thanks!

**Comment by toshiksharma271** [comment]
I would love to work on this.

**Comment by owais0017** [comment]
i would like to work on this issue. kindly assign it to me so that i can get going
