### ISSUE TITLE
Console.log outside draw and setup functions

### ISSUE THREAD

**Issue by Mshuman8** [processing/p5.js-web-editor#2546]
### What is your operating system?

Mac OS

### Web browser and version

Chrome://118.0.5993.88

### Actual Behavior

My console.log statements outside of the draw and setup functions are not running. 

https://editor.p5js.org/mshuman/sketches/F1S7QdaPS

### Expected Behavior

I was expecting it to say "hello" in the console.

### Steps to reproduce

In the sketch.js delete everything except: 

console.log("hello")

**Comment by raclim** [comment]
Thank you for reporting this! I think this is tied to https://github.com/processing/p5.js-web-editor/issues/2518 which also references this issue. We just pushed a fix, so hopefully this should now be resolved! Otherwise, please let us know if this issue still persists.
