### ISSUE TITLE
Adding new files from project menu

### ISSUE THREAD

**Issue by tribalthomas** [processing/p5.js-web-editor#255]
I think that the add files button is no in a user friendly place. With all the arrows used for drop downs it blends in with them. Maybe having another button on the project menu at the top of the screen would be a better place to add it.

**Comment by catarak** [comment]
One option would be to change the design to be like https://gomix.com. There's only one "+" button to add a file or folder, and to put a file in a folder, you specify that file's path, e.g. "lib/new_file.js". My concern is that maybe file paths are confusing to beginners if you've never seen or used one before.

**Comment by lmccart** [comment]
my preference would be to keep the visual design as is for now until we do wider testing, but maybe to add the ability to right click to access the dropdown options, similar to interaction models of sublime or brackets.

**Comment by catarak** [comment]
i agree, I think it's best to leave it for now and evaluate with wider testing. i will add the right click to access the dropdown though.
