### ISSUE TITLE
Tooltip not diplayed when the user hovers over an element in settings.

### ISSUE THREAD

**Issue by Aseem22** [processing/p5.js-web-editor#2551]
### p5.js version

v1.8.0

### What is your operating system?

Windows

### Web browser and version

chrome://118.0.5993.118   (Official Build) (64-bit)

### Actual Behavior

Tooltip is displayed for when user hover pointer over an element in settings.
When hover over radio button "on" of autosave, no tooltip appears.
![ps5js_before](https://github.com/processing/p5.js-web-editor/assets/89309144/cd2b3ad6-bca2-4fa7-87e3-f90983ee5203)

### Expected Behavior

A tooltip using arial-label should appear. Fixing this increases accessibility.
![ps5js_expected](https://github.com/processing/p5.js-web-editor/assets/89309144/34244b3c-f98b-4aeb-99e6-39038545c1b8)

### Steps to reproduce

Steps:
1.Open settings in ps5.js web editor.
 2. Click on settings.
 3. Hover over radio button below Autosave( or any preferences after it).

**Comment by Aseem22** [comment]
I would like to work on this issue. Can you assign me this @lindapaiste and @raclim.

**Comment by im-alok** [comment]
Okay, This the one of basic problem .I would love to work on it...

**Comment by lindapaiste** [comment]
We generally have all of the right aria-label attributes, but those don’t create tooltips automatically. The aria-labels are mainly used by screen readers for visually-impaired users.

My opinion is that the tooltips are distracting and don’t help with accessibility, as they don’t provide any additional information.  But I’m not an accessibility expert.  Are there any guidelines that suggest we should do this?

**Comment by haarsh157** [comment]
Can we consider enhancing user experience by converting the current buttons to toggle buttons, as this modification is anticipated to contribute to improved user-friendliness within the interface.

**Comment by raclim** [comment]
> My opinion is that the tooltips are distracting and don’t help with accessibility, as they don’t provide any additional information. But I’m not an accessibility expert. Are there any guidelines that suggest we should do this?

I don't know the exact guidelines either, but I personally feel that if we have the aria-labels for screen readers in place thenI also agree that having these additional tooltips might be distracting and visually overwhelming. I think adding tooltips could be useful in other contexts (i.e. like explaining how 'Autosave' works). 

I don't think we'll be working on this in the near future, but would be down to revisit down the line if more folks see a need more it!
