### ISSUE TITLE
No preview in local (manual) installation : Localhost refused to connect

### ISSUE THREAD

**Issue by mhsh312** [processing/p5.js-web-editor#2553]
### What is your operating system?

Windows

### Web browser and version

Microsoft Edge: 118.0.2088.76 (Official build)

### Actual Behavior

I did manual installation as guided in the docs. I have the same node version as indicated. Yet the preview section of my installation is showing localhost refused to connect. Port 8002 also returns pitch black screen. 

localhost:8000
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/025455f9-5da7-4d92-8156-59f7c4fe4078)

localhost:8002
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/b66ff386-1390-4891-87d6-a7a277bfb323)

Everything else works fine. 

### Expected Behavior

It is supposed to show the preview of the code.

### Steps:
1. Do the manual installation.
2. npm start
3. localhost:8000
4. Observe the preview

**Comment by raclim** [comment]
Going to close this one since it's similar to the most recent one you posted!
