### ISSUE TITLE
Reversing the Arrow direction while clicking on the navbar items 

### ISSUE THREAD

**Issue by yashpandey06** [processing/p5.js-web-editor#2554]
### Increasing Access

This proposed feature idea aims to enhance the **_interactive_** and **_smoother_** user experience when clicking on elements, making it more appealing to the user.

### Feature enhancement details

The smooth 180 degree  rotation of the cursor makes it more user-interactive when clicking the element on the navbar it will enhance the user experience.

Currently, the arrow isn't rotating on clicking the element

![279152463-6c52ee62-0db1-49ac-a474-36506d166255](https://github.com/processing/p5.js-web-editor/assets/97700473/4eb77ec9-cf03-484a-b486-8022d70ad068)

**Comment by yashpandey06** [comment]
Can i work on this @lindapaiste and @raclim

**Comment by lindapaiste** [comment]
I don’t have strong feelings about this one way or the other, but I have a slight preference towards the way that it is now.

**Comment by yashpandey06** [comment]
Okay @lindapaiste  I understand your point .
So it will be a  good thing to remove unnecessary codes which aren't in use to make codebase look more organised and useful .

**Comment by SableRaf** [comment]
Arrows pointing in the direction the action will occur seems to be a commonly accepted UX good practice. Additionally, the sidebar expand/collapse button already follows that convention. I can see how consistency in design cues like arrow directions can subtly improve the user experience. I wouldn't say it's high priority but I'd be in favor of the change.

Relevant Links:
* https://ux.stackexchange.com/questions/87350/which-way-should-arrows-point-for-a-dropdown-button
* https://setproduct.com/blog/dropdown-ui-design

**Comment by rajatmohan22** [comment]
@SableRaf, I agree as well. It gives the user a sense of responsiveness and control.

**Comment by yashpandey06** [comment]
@SableRaf yeah therefore I proposed this

**Comment by rajatmohan22** [comment]
@SableRaf This could be tagged with "discussion" right, it'd be more interesting to invite a wider range of perspectives.

**Comment by apsinghdev** [comment]
Hey, @yashpandey06 I am in support of this. Also, I have a suggestion. Instead of reversing the arrow, can we smoothly pull it down a bit on hover, and when hovering over another button, the previous one should automatically return to its previous position. You can see this suggestion on this website

https://clipchamp.com/en/video-editor/  

To achieve smoothness, it would be better to do this because if we reverse it to 180 degrees, it will cause the arrow to move rapidly.

as you can see here 

https://online-video-cutter.com/video-editor

**Comment by yashpandey06** [comment]
@apsinghdev yeah !!!!!... I need @lindapaiste 's approval to work on it as the majority wants  it to be done ,
I would love to know @lindapaiste  views on it again .

**Comment by raclim** [comment]
Thanks for all of your input on this! 

I personally feel that while "interactive" or "animated" elements can feel more visually appealing and that implementing something like this seems like a smaller beneficial enhancement, I feel that these types of moving components could be distracting or overstimulating for others, especially for younger students or folks who might be trying to learn how use these types of interfaces for their first time. 

I think that these types of design changes might need consultation first and might not be a high priority for us at the moment, but would definitely be open to revisiting this again! I'm going to close this and add it to [this board ](https://github.com/processing/p5.js-web-editor/projects/11)for now.
