### ISSUE TITLE
Cleaning of codebase by removing unused  components in client folder .

### ISSUE THREAD

**Issue by yashpandey06** [processing/p5.js-web-editor#2555]
### Increasing Access

Proposing this idea would help the new contributors better understand the code as the official React  Documentation promotes hooks and functional components.

### Feature enhancement details

Update the code in this file to use functional components, aligning it with the latest React version. This change will make it more accessible for new contributors to understand, modify, and improve the codebase.

can I work on this @lindapaiste  and @raclim

**Comment by lindapaiste** [comment]
Hey, I think the `NavBasic` was not mentioned in #2358 because it is not actually used anywhere?  If so, we should delete it rather than converting it.

**Comment by yashpandey06** [comment]
Okay @lindapaiste I understand your point .
So it will be a good thing to remove unnecessary codes which aren't in use to make codebase look more organised and useful .
