### ISSUE TITLE
`Login with github` showing Page not found on web (chrome/safari) but it is working on mWeb(chrome) and mWeb(safari)

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2556]
### p5.js version

2.9.0

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

`Login with github` showing Page not found on web (chrome/safari)
<img width="1426" alt="github" src="https://github.com/processing/p5.js-web-editor/assets/47579287/f3859ba1-5311-493d-a058-d48ca7777b7c">

### Expected Behavior

Login with Github should redirect us to github sigin page

### Steps:
1. Open the editor on web app
2. Click on login
3. Click on login with github
4. It redirects us to Page not found instead of github sign in page

**Comment by rajatmohan22** [comment]
@PiyushChandra17 It works fine for me in the web editor. Are you referring to localhost specifically?

**Comment by apsinghdev** [comment]
@PiyushChandra17 its working in my browser.

![git-err](https://github.com/processing/p5.js-web-editor/assets/109718740/42432d04-0544-40f5-9520-29db7d60ed6c)

can you please explain where it's occurring?

**Comment by lindapaiste** [comment]
You will definitely get a 404 page from GitHub if you haven't [set up your development environment](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md#github-api-configuration) with GitHub API credentials.  This is fine to do and everything will work except for the login with GitHub feature.

If your `.env` file looks like the example:
```
GITHUB_ID=<your-github-client-id>
```

Then trying to sign in with GitHub will redirect you to this URL, which is a 404:

https://github.com/login/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Fauth%2Fgithub%2Fcallback&scope=user%3Aemail&client_id=%3Cyour-github-client-id%3E

Notice the `<your-github-client-id>` in the URL -- that's the problem.

**Comment by PiyushChandra17** [comment]
@rajatmohan22 @apsinghdev Yes it's working fine for me aswell, but i was specifically referring to `localhost`. Seems like i have to set up my development env with github api credentials. My bad :)

**Comment by PiyushChandra17** [comment]
@lindapaiste  Sure, will do that.
