### ISSUE TITLE
`Duplicate` and `Add to collection` dropdown options is missing on mWeb(safari) while it's present on mWeb(chrome), only `Download` option is showing

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2558]
### p5.js version

2.9.0

### What is your operating system?

None

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

`Duplicate` and `Add to collection` dropdown options is missing on mWeb(safari) while it's present on mWeb(chrome), only `Download` option is showing
![ellipsis_1](https://github.com/processing/p5.js-web-editor/assets/47579287/cd691a0e-e9fc-4e1a-9a06-854cd67d6149)
![ellipsis_2](https://github.com/processing/p5.js-web-editor/assets/47579287/565917a3-681a-4ec8-bf84-fa7e1bd4de99)

### Expected Behavior

`Download`, `duplicate`, and `Add to collection` all three dropdown options should be visible on mWeb(safari)

### Steps:
1. Open the editor app on mWeb(safari)
2. Press on three dot 
3. Press on Examples
4. Press on ellipsis (three dot)
5. Notice only download option is showing

**Comment by lindapaiste** [comment]
If you see this on `localhost` only then it is due to the same problem as #2557 and we can close this issue.

If the problem occurs in production on mobile safari then we definitely need to take a look.

**Comment by PiyushChandra17** [comment]
@lindapaiste Okay, sure!
