### ISSUE TITLE
Development of p5.js Web Editor

### ISSUE THREAD

**Issue by aradhyamakkar97** [processing/p5.js-web-editor#256]
I don't know whether this is the right place to post this here but I posted this on the processing foundation forums ( https://forum.processing.org/two/discussion/20114/development-of-p5-js-web-editor ) and didn't get reply, so I'll just paste it from there :- 

First I would like to introduce myself a little  I am a second year engineering student from BITS Pilani, India. I was introduced to the world of creative coding from Dan Shiffman's youtube channel and I have fallen in love with p5.js ever since. I would like to improve my skills and also give back to the awesome community by contributing to the development of p5.js web editor since the desktop version of the editor is now depreciated and it looks like p5.js web editor is currently the most active and most required project of the processing foundation related to p5.js (correct me if I'm wrong). I read the contribution guide at https://github.com/processing/p5.js-web-editor but it seems like it's for experienced contributors. Can anyone who is already contributing to the development of the p5.js web editor guide me as to how should I start? Thanks a lot.

**Comment by GABBAR1947** [comment]
Its good that you are interested but this area is specifically for the issues originating in the dev process. irc is the best place for such discussions, so i suggest you to visit the irc  .. Cheers !

**Comment by catarak** [comment]
Hey Aradhya,

I'm glad you're interested in contributing! Any open issue that hasn't been assigned/someone hasn't commented on saying that they are working on it is up for grabs. A good place to start is the most recently updates issues. Feel free to email me if you need more direction, as I think that's a better place to have this kind of discussion 😄
