### ISSUE TITLE
cleanup `lodash` imports ( not consistent throughout the web app)

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2566]
### Increasing Access

This will make the code more clean,concise and readable and maintain consistency throughout the app.

### Feature enhancement details

We need to import `lodash` like this throughout the app,
 * `import {pick, orderby, mapKeys, omitBy, isUndefined } from 'lodash'`
 
instead like this,
https://github.com/processing/p5.js-web-editor/blob/e33f2de4b7ede189155537eaba606730bae2851d/server/controllers/collection.controller/updateCollection.js#L1-L2

 * as we have done here,
https://github.com/processing/p5.js-web-editor/blob/e33f2de4b7ede189155537eaba606730bae2851d/server/migrations/db_reformat.js#L4

or we can simply:
`import _ from 'lodash'`

and we can use lodash functions like _.pick, _.mapKeys, _.omitBy, and many others directly without specifying the full namespace every time.

**Comment by Abjcodes** [comment]
Hey @PiyushChandra17, which is the preferred import statement, `import _ from lodash` or `import {pick, orderby, mapKeys, omitBy, isUndefined } from lodash` ?

**Comment by PiyushChandra17** [comment]
@Abjcodes Both are correct way but we need to stick with one throughout the app, i think the latter one makes more sense and easy to read.

**Comment by lindapaiste** [comment]
At some point in the past it was better to use `import omitBy from 'lodash/omitBy';` to reduce the size of the editor code, as using any `from 'lodash'` imports would include the entire lodash source code in our web app bundle.

We don't need to do that anymore thanks to improvements in Webpack's tree-shaking.  So we can clean up the imports 👍

My personal preference is to import the named functions. `import { uniqWith, isEqual } from 'lodash';`.

**Comment by PiyushChandra17** [comment]
@lindapaiste Sure, Can you please review this [PR](https://github.com/processing/p5.js-web-editor/pull/2567) and if everything seems fine, we can merge this. Thanks!
