### ISSUE TITLE
In Accessible text-based canvas, position of `Plain-text` and `Table-text` is incorrectly aligned with checkbox 

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2573]
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

In Accessible text-based canvas, position of `Plain-text` and `Table-text` is incorrectly aligned with checkbox 
<img width="250" alt="accessibility" src="https://github.com/processing/p5.js-web-editor/assets/47579287/6718d6d7-47b5-49f2-a1cc-f0a9c1d728a4">

### Expected Behavior

In Accessible text-based canvas, position of `Plain-text` and `Table-text` should be aligned with checkbox 

### Steps:
1. Open the editor web app
2. Click on settings icon
3. Click on Accessibility
4. Notice in the Accessible text-based canvas
5. Position of `Plain-Text` and `Table-Text` is incorrectly aligned with `checkbox`

**Comment by Dhruval7878** [comment]
Can someone assign me this issue please ?
Thanks

**Comment by raclim** [comment]
Thanks for raising this! I think this might not be a fix that's needed for now, so I'm going to close this! Definitely down to revisit this in the future though if more interest for this pops up!
