### ISSUE TITLE
In `Safari` browser, sketches table `download` dropdown option is not getting closed when clicking another dropdown `or` clicking outside the table

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2578]
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Safari and Version 16.6

### Actual Behavior

In `Safari` browser, sketches table `download` dropdown option is not getting closed when clicking another dropdown `or` clicking outside the table.

https://github.com/processing/p5.js-web-editor/assets/47579287/4a66755c-0638-4048-b8fd-d8897f8fbca8

### Expected Behavior

In `Safari` browser, sketches table `download` dropdown option should get closed when clicking another dropdown `or` clicking outside the table as it is working in `Chrome`.

### Steps:
1. Open the editor app in `Safari` web browser
2. Click on file dropdown
3. Click on Examples
4. Click on the several dropdown `download` option back to back and also click outside
5. Notice the `download` option is not getting closed

**Comment by lindapaiste** [comment]
Good catch!  I must admit that I usually only check the code in Chrome.

This is definitely a mistake that we should fix.  Feel free to work on it if you want to.

**Comment by PiyushChandra17** [comment]
@lindapaiste I think everyone usually checks the code in Chrome , checked in firefox aswell (working fine). Yes will work on this.

**Comment by raclim** [comment]
I think this was fixed after merging #2379 so I'm going to close this and the affiliated PRs!
