### ISSUE TITLE
`404 page not found` when clicking on my assets file upload preview

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2583]
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

`404 page not found` when clicking on my assets file upload preview

https://github.com/processing/p5.js-web-editor/assets/47579287/d210bdaa-5241-443b-839b-7b0b3b08fa4a

### Expected Behavior

Preview file page should open 

### Steps:
1. Open the editor web app
2. Click on Hello! user-name dropdown
3. Click on My Assets
4. Click on dropdown option
5. Click on open in new tab
6. 404 page not found page opens

**Comment by lindapaiste** [comment]
😱 Definitely a malformed URL.  It should be an absolute URL but it's relative instead, leading to a URL like https://editor.p5js.org/lindapaiste2/https://assets.editor.p5js.org/6457f440a66277001a43e859/3d406e6e-12f3-4fc1-8187-e797e151cfcc.png

This should be easy to fix so let's get this fixed ASAP and include it in the next release.

**Comment by lindapaiste** [comment]
We need to change this from a `react-router-dom` link (which is for internal links) to an HTML `<a>` tag.

https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/components/AssetList.jsx#L5
https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/components/AssetList.jsx#L110-L118

The most recent change to that file was when we upgraded `react-router` versions.  I'm assuming that the previous version knew to ignore the external link?  And the current version doesn't?
