### ISSUE TITLE
"File > New" needs to be clicked twice to create a new sketch

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2584]
> I have noticed an issue in the editor recently where sometimes I have to click File > New twice in order to trigger the action. I wondering if others have also been experiencing this, and if what @eyaler is trying to suggest could be related to that?

_Originally posted by @raclim in https://github.com/processing/p5.js-web-editor/issues/2541#issuecomment-1792653967_

**Comment by lindapaiste** [comment]
After the first click on "File > New" I see the "Opened New Sketch" toast and the URL changes, but the sketch files and the text in the editor are still showing the previous sketch.  Clicking "File > New" a second time works.

My guess would be a problem in the Redux code, or possibly a missing `useEffect` dependency somewhere.

**Comment by lindapaiste** [comment]
Relevant code:

https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/hooks/useSketchActions.js#L24-L32

https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/actions/project.js#L272-L277

https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/actions/project.js#L266-L270

https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/reducers/project.js#L38-L39

After looking at this, it seems like the URL change to `/` is interfering with the intended change in the Redux state.  Either by preventing the intended action (less likely), or by overwriting it with some actions triggered by the new page (more likely).

**Comment by kirtanchandak** [comment]
can I try this one out?

**Comment by lindapaiste** [comment]
> can I try this one out?

@kirtanchandak i assigned this one to myself because I think it’s a bit complex and probably not a beginner-friendly issue.  And also because I’ve previously worked on this part of the code and I might be responsible for it not working right now 😳. But if you want to try it then feel free to do so!  It will give you an opportunity to understand some parts of the codebase, whether or not you are able to solve it.  Look into the hook in the IDEView where we initiate the getProject fetch.

**Comment by lindapaiste** [comment]
@kirtanchandak I’m thinking about this more and I think I know what I did that broke it.  I will explain more later but you should try removing the `setTimeout` in the redux action and see if that fixes it.

**Comment by lindapaiste** [comment]
Here's a lengthy explanation of what happened and how the `setTimeout` is involved.

This issue is my fault, and happened when converting the `IDEView` from a class component to a function component.  We have a code in the `IDEView` which fetches the project from the API based on the id in the URL.

Here's that code before:
https://github.com/processing/p5.js-web-editor/blob/314e4d08b1ef43e40edfc5109689322510d8872e/client/modules/IDE/pages/IDEView.jsx#L112-L118

And after:
https://github.com/processing/p5.js-web-editor/blob/f99eda05a8128adc311c48530e989a6f19edc411/client/modules/IDE/pages/IDEView.jsx#L98-L103

You can see that there are some conditions which got removed.  I recall discussing this with @dewanshDT and saying that some of those conditions didn't make sense.  Now I understand that they were there for this specific scenario of navigating from a saved project to the root URL.

The current (bad) logic is "fetch the project if there is an id in the URL, and the id in the URL it doesn't match the id of the current project".

The previous logic was "fetch the project if there is an id in the URL, **_and there was not an id in the URL on the previous render_**, and the id in the URL doesn't match the id of the current project".  Which is kind of weird logic, right?

We are definitely setting a new project but then overwriting it back it the previous project.  And that's happening because the URL change is in a `setTimeout`.  Which means that there is a single render where the project in the Redux state is the new project but the id in the URL is for the old project.  That will trigger the `useEffect` to fetch the old project.
https://github.com/processing/p5.js-web-editor/blob/031c3d01cde6d6ac59c39ce34bc8ab669b3e2a8f/client/modules/IDE/actions/project.js#L272-L277

If we want the new logic to work, then all we need to do it delete the `setTimeout` and make it so that the URL change and the Redux state change happen on the same render.

**Comment by mhsh312** [comment]
This is why switching from legacy components is scary tbh

**Comment by raclim** [comment]
@mhsh312 it could be daunting but it's definitely a necessary change 😂

@lindapaiste Thanks so much for confirming and tracing back this issue!
