### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8002') does not match the recipient window's origin ('null')

### ISSUE THREAD

**Issue by mhsh312** [processing/p5.js-web-editor#2589]
### What is your operating system?

None

### Web browser and version

Microsoft Edge: 118.0.2088.76 (Official build)

### Actual Behavior

referencing to issue #2553 , when I set up the project locally and run it, everything runs fine except for the output window which says "localhost refused to connect".

![image](https://github.com/processing/p5.js-web-editor/assets/135870090/b33d47c9-9fa5-4b6f-8bbe-302d8e104053)

on further investigation I found out that in my console there the following error when I press the "Play Sketch" button:

![image](https://github.com/processing/p5.js-web-editor/assets/135870090/3df3b88a-ac69-4d92-a644-5ea3bc666021)

Can someone please explain to me what the issue is? I have already set up the project manually thrice. 

### Expected Behavior

It should show the preview just fine without this error.

### Steps to reproduce

1. `npm start` the local project
2. notice the 'localhost refused to connect' message on preview panel 
3. run a code sample.
4. check the console.

**Comment by raclim** [comment]
I remember facing this issue before, though I'm not sure if the context surrounding mine is the same as yours. I think the issue that was happening for me was that the data stored in my cache wasn't up to date with the latest app changes. I was able to resolve it by [clearing all the cookies/cached content](https://help.webex.com/en-us/article/WBX9000035442/Clear-Cache-and-Cookies-in-Microsoft-Edge) associated with the editor. Maybe doing that might help?

**Comment by mhsh312** [comment]
That worked! Clearing all the cache fixed the issue. Thanks!
