### ISSUE TITLE
`Console` and `Clear` does not translate in `hindi` language as compared to other languages

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2591]
### p5.js version

2.9.2

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

`Console` and `Clear` does not translate in `hindi` language as compared to other languages such as Espanol, Francais etc

https://github.com/processing/p5.js-web-editor/assets/47579287/8721b550-400d-41c6-944c-13ab81c26a5d

### Expected Behavior

`Console` and `Clear` should get translate in `hindi` language as compared to other languages

### Steps:
1. Open the editor web app
2. Click on language preferences
3. Try changing the different languages and observe `Console` and `Clear`
4. Verify it does not get translated in `Hindi`

**Comment by avengsum** [comment]
"Console": {
      "Title": "Console",
      "Clear": "Clear",
      "ClearARIA": "Clear console",
      "Close": "Close",
      "CloseARIA": "Close console",
      "Open": "Open",
      "OpenARIA": "Open console"
    },


this is what I got in their JSON response for Hindi so I think we need to modify their backend database. if then how to solve this issue, Piyush 


we can Translate console into adesh pankti which means command line

**Comment by Leokhaidem** [comment]
Hello can i work on this, this will be my first open-source contribution

**Comment by mhsh312** [comment]
This can be fixed by making changes in the translations\locales\hi\translations.json file. I can work on this. I know the hindi language as well.

**Comment by mhsh312** [comment]
> we can Translate console into adesh pankti which means command line

i think it would be better if it was just कंसोल which is just "console" written in devanagari (hindi) script.

**Comment by lindapaiste** [comment]
As @mhsh312 said, the translations are in a .json file in this repo, and you can submit a pull request to make changes. https://github.com/processing/p5.js-web-editor/blob/a1a5efd44f64f4a449f07379098dcdfe049558eb/translations/locales/hi/translations.json#L120-L128

Here are all of the phrases in Hindi which are either missing or copied from the English.  Feel free to translate any of these, but no pressure.  Just fixing the console section would be an improvement.

I'm working on some tools to help us identify missing translations: https://w268rm.csb.app/

```
Nav.Sketch.Title
Nav.Auth.Asset
SocialAuthButton.LogoARIA
About.Forum
About.PrivacyPolicy
About.TermsOfUse
About.CodeOfConduct
Preferences.FontSize
Preferences.SetFontSize
Preferences.AutocompleteHinter
Preferences.AutocompleteHinterOnARIA
Preferences.AutocompleteHinterOffARIA
KeyboardShortcuts.CodeEditing.ColorPicker
Common.p5logoARIA
NewFileForm.Placeholder
NewFolderForm.Placeholder
ResetPasswordForm.EmailARIA
AccountForm.EmailARIA
AccountView.SocialLogin
AccountView.AccountTab
APIKeyList.Name
APIKeyList.Actions
SignupForm.EmailARIA
AssetList.HeaderName
AssetList.HeaderSketch
Feedback.Title
Collection.HeaderName
CollectionCreate.FormLabelARIA
DashboardTabSwitcher.Assets
CollectionList.HeaderName
SketchList.HeaderName
Cookies.Header
Cookies.Body
Cookies.AllowAll
Cookies.AllowEssential
Legal.PrivacyPolicy
Legal.TermsOfUse
Legal.CodeOfConduct
```

**Comment by Brahvim** [comment]
> > we can Translate console into adesh pankti which means command line
> 
> i think it would be better if it was just कंसोल which is just "console" written in devanagari (hindi) script.

Hi there! Are we going for 'pure' transliterations? I feel like "कौन्सोल"/"कॉन्सोल" could work as a better transliteration of the word "console".
...Unless more Hindi-like ones are what you prefer, that is!
