### ISSUE TITLE
Refactor to Functional Components and Integrate Tailwind CSS

### ISSUE THREAD

**Issue by avengsum** [processing/p5.js-web-editor#2599]
### Increasing Access

so here are some points -
->Functional components are concise and enhance code readability.
->Simplifies the code structure, making it easier to maintain and debug.
->Facilitates the use of React Hooks for managing state and lifecycle events.
->Promotes a clean separation between stateful and stateless components.

this will help the new developer to understand our code more easily because nowadays functional components are used and it has became a modern-day practice for react developers so I think we should also move to functional components it will help new developers to understand our codebase easily 

### Feature enhancement details

this will make our code more readable and by adding a tailwind to our code base it will make developers understand and work more easily with the UI part and it will make our code base more modern

**Comment by avengsum** [comment]
so what do you think @lindapaiste  should I start working on this?

and I know that we have already discussed tailwind but I can't stop myself

**Comment by Akhilbisht798** [comment]
Hey I think we have a similar discussion about tailwind CSS on this project and I don't think people were favor on it. So maybe we need to discuss this.
But for function component I agree with you there are many advantages of functional component, and it is more new way writing react. There are many components in this project that are needed to be changed to function components. So it will be a long process.

**Comment by avengsum** [comment]
@Akhilbisht798  but we have to start at some point. should I  start working on functional components @lindapaiste

**Comment by lindapaiste** [comment]
Re: Tailwind - we decided against it
#2435 

Re: function components - we have a lot of pending PRs covering this.  We need to review and merge all of those PRs, which is a pain because it’s easy to create bugs when migrating code so we need to review everything very carefully.  But the code is written so we do not need any additional PRs. 
#2358
