### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by Spencer-OBrien** [processing/p5.js-web-editor#2608]
### Increasing Access

unsure

### Feature request details

I want to delete my account but it is not possible currently.
You are probably storing a lot of account credentials for people who would like to delete their accounts

**Comment by mhsh312** [comment]
Interesting. I didn't know that p5 didn't have a delete account button. 
Currently, we create a user by ultimately calling the `createUser` controller from the `/server / controllers / user.controller.js` file:

https://github.com/processing/p5.js-web-editor/blob/115a7b202af34e1f6061a00caf967cb3816c46f3/server/controllers/user.controller.js#L38-L96

This creates a DB interaction which stores a user object in the Database. Deleting a user should mean deleting this object. 

I am down to work on this.

**Comment by raclim** [comment]
Hi @Spencer-OBrien, if you'd like to delete your account you can reach out to privacy@p5js.org and we can work on deleting it from there. 

I think we might want to approach how we'd implement this more cautiously and further discuss what the interface would look like first!

**Comment by mhsh312** [comment]
I believe we should include the option to delete account in the `account settings` page. 
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/ce3d629d-ae72-4a47-b9ec-da2e0e88d0e1)
![image](https://github.com/processing/p5.js-web-editor/assets/135870090/50161c1c-918c-4541-8f05-3f14c1e37664)
Right beneath the Social Auth Buttons.

**Comment by avengsum** [comment]
@mhsh312 yes it is a good idea

**Comment by avengsum** [comment]
@raclim  I think we have already discussed this Here #1840

**Comment by raclim** [comment]
Thanks for finding it, I think it did get a little lost! I'm going to add a few labels there and close this for now then to consolidate issues.
