### ISSUE TITLE
Song Example crashes when playing song

### ISSUE THREAD

**Issue by nathanernest** [processing/p5.js-web-editor#262]
Steps to replicate
1. Open p5.js Web Editor (https://alpha.editor.p5js.org)
2. Click **Examples**
3. Click **Hello P5 : song**
4. Click Play
5. In the generated sketch, click **play song automatically**

**Comment by yining1023** [comment]
I think this is related to #145: dom createA('#', 'link') function doesn't work as expected

**Comment by catarak** [comment]
Yes @yining1023, this is the same issue as #145. When you look at the src of the iframe after clicking on the button, it is `https://alpha.editor.p5js.org/p5/sketches/SkHDjvqw_Xl/#`, therefore clicking on the button has appended a # to the url and caused the iframe to reload. The solution to this is a combination of #166 and #212.

**Comment by catarak** [comment]
closing as this is the same issue as #145.
