### ISSUE TITLE
Discussion: `react-tabs` vs. `react-router` links

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2621]
### Increasing Access

Using standard HTML `<a>` tags for links is more semantically correct and allows for standard right-click behavior.

### Feature enhancement details

There are multiple places in the app where we use tabs to switch between content.  Some of these are coded using the `react-tabs` package, while others use `<Link>` elements from `react-router-dom`.

It is my opinion that we should use the `react-router-dom` approach in situations where the tabs have different URLs but I want to open this up for discussion.

### Advantages of `react-router-dom`
* We can use the router to control the content on the page, instead of manually switching based on `pathname`
https://github.com/processing/p5.js-web-editor/blob/185a0b1ed3cef02957bd9bc04d25b33c33eee11d/client/modules/Legal/pages/Legal.jsx#L37-L45
* We don't need any callback function when changing tabs.
https://github.com/processing/p5.js-web-editor/blob/185a0b1ed3cef02957bd9bc04d25b33c33eee11d/client/modules/Legal/pages/Legal.jsx#L47-L59
* We can automatically highlight the current tab using the `NavLink` component (instead of `Link`) https://reactrouter.com/en/main/components/nav-link
* Links render as HTML `<a>` elements which is more semantically correct and allows for standard right-click behavior.
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/c70e8166-f1df-4cc0-8ef0-a71dee15183a)
* Screen readers understand links, and they can be focused using Tab navigation.

### Current Usage
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/b64693b3-05a1-4ab7-aa30-bc05ab316901)
Legal page - uses `react-tabs`
https://github.com/processing/p5.js-web-editor/blob/185a0b1ed3cef02957bd9bc04d25b33c33eee11d/client/modules/Legal/pages/Legal.jsx

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/18a068e6-f4a0-4e60-8cdc-b6d0c10c84dc)
Dashboard page - uses `react-router-dom` (with manual routing and highlighting that I would like to clean up)
https://github.com/processing/p5.js-web-editor/blob/185a0b1ed3cef02957bd9bc04d25b33c33eee11d/client/modules/User/components/DashboardTabSwitcher.jsx

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/5a8e6cad-6ccc-4059-839a-64608e26d7b6)
Preferences modal - uses `react-tabs`
This would stay as-is because there is no URL change involved
https://github.com/processing/p5.js-web-editor/blob/185a0b1ed3cef02957bd9bc04d25b33c33eee11d/client/modules/IDE/components/Preferences/index.jsx

**Comment by udittripathi** [comment]
I can host the application locally using docker but when I make changes in the code it is not getting refreshed in the browser. So I have to build a new image every time or there is something I am doing wrong? Kindly help me with this.

**Comment by avengsum** [comment]
@lindapaiste is this issue is solved or anything left that I can work on?
