### ISSUE TITLE
mWeb(safari): First letter gets automatically capitalized in username or email input

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2623]
### p5.js version

2.9.3

### What is your operating system?

Mac OS

### Actual Behavior

First letter gets automatically capitalized in username or email input in login page without pressing shift button on `iOS - mWeb(safari)`

![first letter](https://github.com/processing/p5.js-web-editor/assets/47579287/9724ef8d-a5b3-4594-9e31-4fba715d7192)

### Expected Behavior

First letter should not get capitalized automatically in username or email input 

### Steps:
1. Open the editor web app in iOS - mWeb(safari)
2. Go to the login page
3. Tap on username or email
4. Verify that the first character gets capitalized automatically without pressing `shift`

**Comment by KrishavRajSingh** [comment]
I am working on this.

**Comment by ShashwatPS** [comment]
Can I work on this issue if its still open ?
