### ISSUE TITLE
Add Placeholder for Clearer User Guidance in Console Input Component

### ISSUE THREAD

**Issue by gauravsingh94** [processing/p5.js-web-editor#2644]
### Increasing Access

Incorporating a placeholder within the console input component would significantly enhance the user interface, particularly for new users. This addition serves as a guiding element, clearly indicating where console inputs should be entered. 

### Feature enhancement details

Without the addition of a placeholder, the interface will appear unclear, which is not ideal for new users as they may find it challenging to navigate.

![Screenshot from 2023-11-28 00-07-54](https://github.com/processing/p5.js-web-editor/assets/99260988/afef975f-a638-4c6e-90ba-919261768a80)

**Comment by gauravsingh94** [comment]
After adding placeholder it will like this

[Screencast from 2023-11-28 00-14-57.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/61b58b63-49b1-456d-aab7-5677d6430173)

**Comment by raclim** [comment]
Thanks for raising this! I think this might not be a feature that we're planning to implement in the near future, so I'm going to close this for now. Please feel free to create a new issue or work on other ones within this repository!
