### ISSUE TITLE
No `Validation Error` for username in login when char exceeds the max limit

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2646]
### p5.js version

2.9.3

### What is your operating system?

Mac OS

### Actual Behavior

Currently, We have validation error for username in sign up page when char exceeds the max limit (must be less than 20 char), on the other hand same validation is missing in username input.

### Expected Behavior

Must be validated on username input on login page

### Steps:
1. Open the editor web app
2. Go to login page
3. Notice there is no validation error on username input
4. If we type more than 20 char

**Comment by haarsh157** [comment]
Highlighting a usability concern, the current login functionality provides two options—username and email. Notably, the email option allows for entries exceeding 20 characters, warranting consideration for a more seamless user experience. Proposing an evaluation of the login mechanism to ensure optimal user interaction and accommodate extended email entries.

**Comment by lindapaiste** [comment]
I think it's normal that those sorts of validation errors appear only when you are creating the username and not when you are logging on.

> Highlighting a usability concern, the current login functionality provides two options—username and email. Notably, the email option allows for entries exceeding 20 characters.

This is a really important point.
