### ISSUE TITLE
Expired verification-link result in infinity verification request-loop and (at the end) browser (or part of it) crash

### ISSUE THREAD

**Issue by exetico** [processing/p5.js-web-editor#2652]
### Most appropriate sections of the p5.js website?

User Verification process (Verify Email)

### What is your operating system?

Mac OS

### Web browser and version

Mozilla Firefox Developer Edition 121.0b2

### Actual Behavior

I clicked the "Verify Email", and the page just mass looping through the verification process.

![billede](https://github.com/processing/p5.js-website/assets/3549445/24ea5f84-5a1d-4277-b5d5-6413178ae333)

![billede](https://github.com/processing/p5.js-website/assets/3549445/3f1c70e8-a8c8-491e-bb92-5541c3ee6c49)

![billede](https://github.com/processing/p5.js-website/assets/3549445/332d9071-ea4e-4e85-9cf7-756bded3b244)

![billede](https://github.com/processing/p5.js-website/assets/3549445/29c9a76e-bbf6-4ae4-b339-bd72c4f7e310)

![billede](https://github.com/processing/p5.js-website/assets/3549445/29c9a76e-bbf6-4ae4-b339-bd72c4f7e310)

### Expected Behavior

I expect the page to use the verification token once, and not spamming the p5.js backend.

If the token are invalid (or already used), tell me that it's invalid.

### Steps to reproduce

Open a link with a invalid token like  [https://editor.p5js.org/verify?t=letthefunbegin](https://editor.p5js.org/verify?t=letthefunbegin) (or a expired one)

![billede](https://github.com/processing/p5.js-website/assets/3549445/97b6de50-6f1b-4736-b5d1-5f706773a2c7)

And let the fun begin ;-) ....

I have Consent-O-meter + uBlock Origin installed in my browser.

I ended up in the situation, as I accidentally closed the verification tab just after I clicked the "Verify Email" button in the email. So I reopened the tab, and let me just say that I should be verificed a MASSIVE amount of times, as this point 😉.

### Would you like to work on the issue?

Sadly, no. I dont have time to do so. But handling "undefined" data, and a expired link case, shouldn't take long 😃.

Also, it doenst really look like that's part of the repo:
![billede](https://github.com/processing/p5.js-website/assets/3549445/239a17c9-9244-41a2-8317-a5f4535ae15b)

**Comment by lindapaiste** [comment]
This should be moved to the [web editor repo](https://github.com/processing/p5.js-web-editor/issues) but I do not have permission to move it.  @Qianqianye @raclim

**Comment by lindapaiste** [comment]
It's possible that this would be fixed by https://github.com/processing/p5.js-web-editor/pull/2610 which addresses bad expectations in `catch` clauses and fixes the  `Uncaught (in promise) TypeError: can't access property "data" of undefined` error.
