### ISSUE TITLE
No `Validation` for sketch file `rename`

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2653]
### Increasing Access

Currently we don't have any limit set for sketch file rename, plus it will also make the sketch table look messed up when user renames the file with lots of characters

<img width="1085" alt="sketch rename" src="https://github.com/processing/p5.js-web-editor/assets/47579287/83b5f055-7fac-4048-af94-93b5787ea91d">

### Feature enhancement details

We should provide max char limit to sketch file rename

**Comment by lindapaiste** [comment]
We should make sure that we are using the same validation on any place where the user renames the sketch, whether it’s here or in the Header of the sketch.  We need to check:

- Are there any hard limits set by the backend database or API?
- Do we have any validation when renaming from the Header?
- Do we check for empty texts?
- Are there any other places where the user can rename a sketch?  I think it’s just these two?  Is the sketches table on the Collection page the same component?

I just looked at what we are doing in the Header and there is a maxLength of 128 with a check for empty strings.

https://github.com/processing/p5.js-web-editor/blob/f725abd1505a1fecd8b58ed2f4a57367a6051d27/client/modules/IDE/components/Header/ProjectName.jsx#L16-L26

128 characters is quite a lot, tbh.  Meaning that the table might still look messed up even with this validation.  So we probably want something in the CSS for the table that sets a max width for the column (either this specific column or all individual columns).  We would want it to wrap the text on multiple lines when overflowing.  For your example to work nicely we would also need to allow break-word in the CSS.

**Comment by raclim** [comment]
Just also want to add this issue here, https://github.com/processing/p5.js-web-editor/issues/568, which might also give some more historical context around this!

**Comment by ShashwatPS** [comment]
Can I work on this issue ?
