### ISSUE TITLE
Not able to change the uploaded image file extension type (jpeg > jpg > png)

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2654]
### p5.js version

2.9.3

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

Not able to change the uploaded image file extension type 

### Expected Behavior

We should able to change the uploaded image file extension type 

### Steps:
1. Open the editor web app
2. Click on upload file
3. Upload any `jpeg` extension type image
4. Notice we are not able to change jpeg to `jpg` or `png`

**Comment by lindapaiste** [comment]
We don’t allow the user to change the file extension at all, and this is something that I’ve noticed before and wondered if the pros outweigh the cons.  We should try to find any discussions from when this logic was initially implemented (issues and PRs) to understand why we decided not to allow this.  I’m definitely on board for rethinking it.

**Comment by soniyadotp** [comment]
@lindapaiste What do you think, should I dedicate effort to addressing this issue?

**Comment by Anayverma** [comment]
Hey @lindapaiste I would love to contribute to this issue. Please assign it to me.
