### ISSUE TITLE
Implement new design for Preferences panel

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#266]
![11 web-editor-light-settings-1024 1x](https://cloud.githubusercontent.com/assets/6063380/21942283/66e83920-d99a-11e6-9ba8-3ac2548e6c4b.png)

**Comment by joemckay5** [comment]
I noticed that if the sketch widow is pulled over to the right the preferences pane goes behind the console. 
<img width="332" alt="screen shot 2017-01-28 at 5 32 01 pm" src="https://cloud.githubusercontent.com/assets/6563969/22402058/579cb92c-e5b7-11e6-8c58-f776e196d390.png">

**Comment by catarak** [comment]
Oooo thank you, there's definitely some z-index CSS that needs some TLC.

Linting is a term that refers to the process of checking code for errors before compilation or runtime. It's especially important for JavaScript IMO since there is no compilation time. However, you are right that it is a technical word that many people do not know, especially beginner coders. Since this preference is targeted at vision-impaired users, I'd want to get @CleezyITP and @MathuraMG to weigh in.

**Comment by lmccart** [comment]
I wonder if switching to the design at top will make it more clear? Right now there's no distinction between general settings / accessibility settings so you wonder as a programmer if you need to know what lint sound is. But if it's in the accessibility tab, maybe you will look it up if you don't know, but you won't worry you're missing something if you don't?

**Comment by MathuraMG** [comment]
Completely agree with the language. We were thinking of alternatives - "Audio Error Message" or something along those lines. What do you think?

**Comment by MathuraMG** [comment]
Another verification - where would 'Themes' go ? Under the 'General Settings' tab or 'Accessibility' ?

**Comment by lmccart** [comment]
hmm interesting. it seems like it should be in general, but I also see how high contrast would be expected in accessibility... would it make sense to put in both? or for the screen reader view to actually not have a separation between general and accessibility settings?

**Comment by catarak** [comment]
I like "Audio Error Message". I'm not sure about where themes would go, but maybe it would just go in general settings, since general settings are also relevant to vision-impaired users?

**Comment by catarak** [comment]
See the new design on (Zeplin)[https://app.zeplin.io/project/55f746c54a02e1e50e0632c3/dashboard?tag=2017&tag=settings].

**Comment by CleezyITP** [comment]
need an invite to view!

**Comment by machinic** [comment]
Added @CleezyITP

**Comment by catarak** [comment]
- [ ] move preference from floating window to modal overlay
- [ ] create tabs
- [ ] move preferences into different tabs

don't worry about adding external libraries. that's a separate issue, #4.

**Comment by dhruvdutt** [comment]
@machinic Can you please add me to Zeplin?
username: dhruvdutt 
email: dhruvdutt.jadhav@gmail.com

**Comment by catarak** [comment]
i'm gonna close this because this is actually already done. I guess the PR didn't get attached to the issue correctly 😄

**Comment by dhruvdutt** [comment]
@catarak Can you please add me to Zeplin? I need to see some dimensions and other specific things in design.
Zeplin details:
username: dhruvdutt 
email: dhruvdutt.jadhav@gmail.com

**Comment by catarak** [comment]
just added you!

**Comment by dhruvdutt** [comment]
@catarak Awesome. Thanks. :blush:
