### ISSUE TITLE
Can't copy paste code

### ISSUE THREAD

**Issue by Craigson** [processing/p5.js-web-editor#267]
Any code that is inserted into the editor using copy+paste doesn't run.

Throws the following error: 
Uncaught SyntaxError: Unexpected end of input (sketch: line 50)

**Comment by catarak** [comment]
what a weird bug, thx for reporting this

**Comment by catarak** [comment]
@Craigson I'm not able to reproduce this, can you link me to to the sketch/code that's causing this?

**Comment by catarak** [comment]
i'm going to close this since I can't reproduce it... feel free to reopen if you figure out what causes this.

**Comment by devnull69** [comment]
I just opened a new sketch in p5.js Web Editor ... and I cannot copy/paste either

**Comment by catarak** [comment]
@devnull69 do you have more specific steps to reproduce? Like the code you're trying to copy and paste, your browser, operating system, etc.

**Comment by devnull69** [comment]
Unfortunately ... or rather fortunately ... it is no longer reproducible today

It happened consistently yesterday for my sketch https://editor.p5js.org/devnull69/sketches/nTGGDviTM ... but it no longer does

**Comment by catarak** [comment]
Oh no that's frustrating! If it happens again, definitely update this issue and hopefully we can figure out the root cause.
