### ISSUE TITLE
❓ How Do I Set Up My Development Environment? ❓

### ISSUE THREAD

**Issue by raclim** [processing/p5.js-web-editor#2672]
## Question About Setting Up Your Environment
I wanted to highlight this here since we've noticed a few folks ask questions regarding this. We hope this issue serves as a space for folks to share their issues, advice, or any other thoughts they had while setting up their own local development environments!

## Relevant Resources
[p5.js Web Editor Contributor Docs](https://github.com/processing/p5.js-web-editor/tree/develop/contributor_docs)
[Installation Docs for Setting Up Your Dev Environment](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md)

**Comment by Shivachauhan17** [comment]
i would setup using suggest docker. follow the steps for the project installation using docker.that's how i did it on my local machine and it worked.

[installation using docker](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md)

and do not forgot to put your github API credentials.
try it on stable and good network

**Comment by PiyushThapaa** [comment]
Go through the development installation guide or simply download docker desktop and run these three command in your local folder:
1)  docker-compose -f docker-compose-development.yml build
2) cp .env.example .env (use "copy" keyword instead "cp" if your operating system is windows)
3)docker-compose -f docker-compose-development.yml up

Wait for every command until it is executed (cause it takes time)

Then then you can navigate to http://localhost:8000/ in your browser

**Comment by ayeshag7** [comment]
Hi, I've been trying to set up my local development environment using docker (I've docker desktop installed) after the recent release for a few days. However, whenever I try to build my docker image using `docker-compose -f docker-compose-development.yml build`, I get this error:

```
failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1
```

A more detailed error log is this:

```
 > [app development 2/9] RUN npm install:
58.33 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
59.13 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
.
.
.
.
122.0 npm notice Run `npm install -g npm@10.2.4` to update!
122.0 npm notice
122.0 npm ERR! code ERR_SOCKET_TIMEOUT
122.0 npm ERR! network Socket timeout
122.0 npm ERR! network This is a problem related to network connectivity.
122.0 npm ERR! network In most cases you are behind a proxy or have bad network settings.
122.0 npm ERR! network
122.0 npm ERR! network If you are behind a proxy, please make sure that the
122.0 npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
122.1
122.1 npm ERR! A complete log of this run can be found in:
122.1 npm ERR!     /root/.npm/_logs/2023-12-03T05_38_47_285Z-debug-0.log
```

I've checked my network connection, it's pretty stable. Moreover, I've not manually set my proxies for docker desktop. I also tried uninstalling and installing docker desktop again. But, nothing worked.


Can someone help me identify the source of this error? I'll really appreciate it, thanks. 

@raclim @PiyushThapaa 

Update:
I was able to solve the error by changing my internet server. It was a network connectivity issue in the end!

**Comment by ShreyaBarsude02** [comment]
@raclim after installing the setup manually i ran "npm install", after doing that i got few vulnerabilities/issues and it advised me to do "npm audit fix", shall i proceed with this "npm audit fix" command?

**Comment by raclim** [comment]
@ayeshag7 Sorry for missing this, glad you were able to figure it out!

@ShreyaBarsude02 No, it'd be best to not run that command! Running [`npm audit fix`](https://docs.npmjs.com/cli/v10/commands/npm-audit) will automatically install any updates needed to "fix" vulnerabilities in this project. Since these fixes haven't been applied to this project's code yet, you'd be working with a different version of it, which wouldn't be ideal.

**Comment by Akhilbisht798** [comment]
To set up development Environment on your local machine these are the step you need to do. you should have docker and docker compose installed in your system.
- `git` clone this repo
- `cd` into this repo
- `cp .env.example .env`
- docker compose -f [docker-compose-development.yml](https://github.com/processing/p5.js-web-editor/blob/develop/docker-compose-development.yml) up

That's it. Now you can start contributing.

**Comment by Arpitkandwal** [comment]
I tried to setup the project on my device locally, but i am encountering this error. Can anyone help me with this? p5.js Web Editor is running on port: 8000!
p5.js Preview Server is running on port: 8002
(node:13284) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13284) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

**Comment by macayu17** [comment]
@ayeshag7 I am also getting the same issue even after I fixed my server. Did you do anything else?

**Comment by macayu17** [comment]
![image](https://github.com/processing/p5.js-web-editor/assets/63203492/c0c05a65-b3bc-476c-ad69-e2200f727713)
As soon as I am trying to start the server, I am getting this error. Kindly help!

@raclim @Shivachauhan17 @Akhilbisht798

**Comment by Sudarshan-21** [comment]
@macayu17 are you following manual installation or docker installation?

**Comment by macayu17** [comment]
@Sudarshan-21 I was doing docker installation.

**Comment by Sudarshan-21** [comment]
@macayu17 restarting your docker might work

**Comment by macayu17** [comment]
@Sudarshan-21 I tried it but the issue persists.

**Comment by Sudarshan-21** [comment]
@macayu17 Do the following checks: installed node, nvm, git and try restarting the project itself by reinstalling everything. also remember running "npm install" in the console. Hope it helps.

**Comment by ayeshag7** [comment]
@macayu17 I apologize for the late reply. I hope that you were able to fix this issue. Were you?

**Comment by macayu17** [comment]
@ayeshag7 Nope it still persists.

**Comment by haarsh157** [comment]
![Screenshot from 2024-01-04 10-46-16](https://github.com/processing/p5.js-web-editor/assets/115213858/f585a3d7-db66-4e6d-82cb-6aef78813e13)
When I recently synced my forked repository and tried to run on my local machine I got this error.
Kindly help...
@raclim @lindapaiste

**Comment by Sudarshan-21** [comment]
I am also facing the same issue after I synced my fork repo 2 days ago.
I guess this issue is arising due to recent merges in past 4-5 days.
@raclim

**Comment by macayu17** [comment]
![image](https://github.com/processing/p5.js-web-editor/assets/63203492/69d81dd8-7016-4246-83c4-9d2cab268f5e)
This is the new error which I am getting now.

**Comment by zukentag** [comment]
I have a isuue regarding , changes i make to the code, I cannot see the changes reflect on the web site untill i restart my docker container/

**Comment by Sarthak102** [comment]
@zukentag I am having the same problem is there any solution. or I am doing something wrong.

**Comment by haarsh157** [comment]
> ![Screenshot from 2024-01-04 10-46-16](https://private-user-images.githubusercontent.com/115213858/294092788-f585a3d7-db66-4e6d-82cb-6aef78813e13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDQ3OTIsIm5iZiI6MTcwNTA0NDQ5MiwicGF0aCI6Ii8xMTUyMTM4NTgvMjk0MDkyNzg4LWY1ODVhM2Q3LWRiNjYtNGU2ZC04MmNiLTZhZWY3ODgxM2UxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzI4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MWM5YmRmNjYyMjBkM2IwYjdmNGI2YmM1OWQxNDYzZjVlNmYyNTk1M2M0MThlMTgyNjdmYzI5YmQyZGEyNjgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6DYkcWXC5BbjEJt7Eg0KzEtguW8NJ6bvsOnCjYRx7uU) When I recently synced my forked repository and tried to run on my local machine I got this error. Kindly help... @raclim @lindapaiste

Any update on this??
@raclim

**Comment by Ayush-Vish** [comment]
@haarsh157  Did your issue gets resolved ?

**Comment by haarsh157** [comment]
@Ayush-Vish Yes! I removed the docker images and then set up the development environment again. It worked.

**Comment by PiyushThapaa** [comment]
@lindapaiste @raclim Every time I make some changes in code I have to restart my server to see the changes. Is there any way to see changes simultaneously while changing in code cause it take minutes to start the server. Btw I am using docker.

**Comment by Akshat76845** [comment]
![Screenshot from 2024-10-06 11-41-38](https://github.com/user-attachments/assets/67dd386b-101b-4f56-a72e-74d37a554636)
How to resolve this issues
