### ISSUE TITLE
The option "Autocomplete Hinter" inside the settings tab is not getting translated when changing the language option.

### ISSUE THREAD

**Issue by SuryaPratap1008** [processing/p5.js-web-editor#2673]
### p5.js version

1.9.0

### What is your operating system?

Windows

### Web browser and version

google chrome -v 119.0.6045.161

### Actual Behavior

When the language is set to any other language other than English , the option in the settings menu which is titled "Autocomplete Hinter" remains unchanged i.e. it doesn't get translated to any other language other than English.
![p5 js bug](https://github.com/processing/p5.js-web-editor/assets/86942329/9aeade00-d2bb-4850-9abe-b13b26168b94)

### Expected Behavior

The Expected behavior Must be to translate Everything to the User Selected Language.

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)

```

**Comment by swrno** [comment]
> ### p5.js version
> 1.9.0
> 
> ### What is your operating system?
> Windows
> 
> ### Web browser and version
> google chrome -v 119.0.6045.161
> 
> ### Actual Behavior
> When the language is set to any other language other than English , the option in the settings menu which is titled "Autocomplete Hinter" remains unchanged i.e. it doesn't get translated to any other language other than English. ![p5 js bug](https://private-user-images.githubusercontent.com/86942329/287023030-9aeade00-d2bb-4850-9abe-b13b26168b94.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNzMxNTcsIm5iZiI6MTcwMTM3Mjg1NywicGF0aCI6Ii84Njk0MjMyOS8yODcwMjMwMzAtOWFlYWRlMDAtZDJiYi00ODUwLTlhYmUtYjEzYjI2MTY4Yjk0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE5MzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTMwY2UxZjdhZjNlYzQ0MTcwODM0ZjJmM2NmZTkyOWQ5YjYyMDNjZjNjM2Q5NDU2NTExNTA5ZmUxYmZjZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M1Ujmpx6voPEhgVV69ltJZ3COQY5cYZObLpnC7fHGbM)
> 
> ### Expected Behavior
> The Expected behavior Must be to translate Everything to the User Selected Language.
> 
> ### Steps to reproduce
> ### Steps:
> 1. 2.
> 
> ### Snippet:
> ```js
> // Paste your code here :)
> ```

hey @SuryaPratap1008 , this issue have already been solved #2615

**Comment by HimanshuUpreti02** [comment]
@Swarnendu0123 is the solved issue already merged as it is still not showing on the actual website. If there are issues I would like to contribute to this. Please assign the issue to me

**Comment by raclim** [comment]
We just merged in the issue that addressed this today, but it won't be live on the actual website until around December 22nd (the deployment schedule can be found in the[ README](https://github.com/processing/p5.js-web-editor#how-do-i-know-my-issue-or-pull-request-is-getting-reviewed) or [this issue](https://github.com/processing/p5.js-web-editor/issues/2534)). Since it seems to be resolved for now I'm going to close this, but please feel free to engage with the other issues in this repository!
