### ISSUE TITLE
In the Hindi version of the p5.js web editor, there is an English text present.

### ISSUE THREAD

**Issue by soniyadotp** [processing/p5.js-web-editor#2681]
### What is your operating system?

Windows

### Web browser and version

10

### Actual Behavior

![issue](https://github.com/processing/p5.js-web-editor/assets/63783532/693a4a3a-9aca-441c-b0cc-a0de3843e6b9)

### Expected Behavior

The text "Autocomplete Hinter" should be "ऑटोकंप्लीट हिंटर"

### Steps to reproduce

It can simply be changed by changing the language.

**Comment by mhsh312** [comment]
I have already raised an inclusive issue about all the hindi translation issues #2609 you can contribute there in case someone else has not.

**Comment by umangutkarsh** [comment]
Maintainers, @lindapaiste, @soniyaprasad77 . I've opened a pr to fix the translation-error-issue of 'AutocompleteHinter', please review it and provide feedback if anything else is required.
Thanks.

**Comment by raclim** [comment]
Thanks for taking the time to raise this issue! Since this has been pretty well noticed, I'm going to close this one to help organize issues.
