### ISSUE TITLE
SketchFiles toggle menu does't collapse on clicking anywhere on screen

### ISSUE THREAD

**Issue by Keshav-0907** [processing/p5.js-web-editor#2683]
### What is your operating system?

Mac OS

### Web browser and version

119.0.6045.199 

### Actual Behavior

The menu is not collapsing when clicked somewhere else on the sceen

<img width="1430" alt="Screenshot 2023-12-04 at 10 27 13 AM" src="https://github.com/processing/p5.js-web-editor/assets/91189139/023c72c3-5e2c-43e7-93ff-ff4b9d918c33">
doesn't collapse

### Expected Behavior

The menu should collapse on clicking somewhere else on the screen

### Steps:
1. Go to https://editor.p5js.org/
2. Click to Add new Sketch Files, it opens a small menu
3. Now on clicking somewhere else on the screen, the menu

**Comment by PiyushChandra17** [comment]
@Keshav-0907 This issue has been reported earlier

**Comment by Keshav-0907** [comment]
> @Keshav-0907 This issue has been reported earlier

Can You please mention the issue number here

**Comment by Jaimin791** [comment]
Is this issue still open/not assigned to anyone? can I work on it?

**Comment by PiyushThapaa** [comment]
hey, i am really interested to work on this issue, can you assign it to me?

**Comment by umangutkarsh** [comment]
Maintainers, please review this the PR.

**Comment by lindapaiste** [comment]
closing as a duplicate of #2524
