### ISSUE TITLE
Translating the 'About Block' into all possible type of language

### ISSUE THREAD

**Issue by swrno** [processing/p5.js-web-editor#2692]
### Increasing Access

<img width="569" alt="288120737-9ba54ab8-172d-41e9-b75f-b02bd2f77f9f" src="https://github.com/processing/p5.js-web-editor/assets/94161758/03a26247-5a90-4309-b7ce-78802b57bc2e">

If we can change the about block into all the possible language available, it will be very easy for a Native Speaker of respective Languages, to navigate over to social media and other links.

### Feature request details

Change full 'About Block' into all possible Language.

**Comment by swrno** [comment]
> ### Increasing Access
> <img alt="288120737-9ba54ab8-172d-41e9-b75f-b02bd2f77f9f" width="569" src="https://private-user-images.githubusercontent.com/94161758/288142115-03a26247-5a90-4309-b7ce-78802b57bc2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTY4NjUsIm5iZiI6MTcwMTc5NjU2NSwicGF0aCI6Ii85NDE2MTc1OC8yODgxNDIxMTUtMDNhMjYyNDctNWE5MC00MzA5LWI3Y2UtNzg4MDJiNTdiYzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE3MTYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OGJiNDFhOTk0NjE5YjM0MWI2NGM0ZThiNTFhYWYzM2RlMGQ2MzlhYjA1YjE4YTEzM2UyNjllMThkNzQ1MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dYziT3spDnOlsl-GndB9pPU58tf_AnWZhXXtrj9abpg">
> If we can change the about block into all the possible language available, it will be very easy for a Native Speaker of respective Languages, to navigate over to social media and other links.
> 
> ### Feature request details
> Change full 'About Block' into all possible Language.

@lindapaiste @raclim As I am a native speaker of Bengali, can you assign me the issue, I will make a PR by 6 December 11:00 PM

**Comment by ayushanand308** [comment]
@Swarnendu0123 I guess it has already been taken care of!

**Comment by swrno** [comment]
> @Swarnendu0123 I guess it has already been taken care of!
> 

I opened it 20 days ago. Many terms like Twitter, Discord, Home, Instagram were not available in all types of language. In #2699 I have taken care of all the terms of "about" block.
