### ISSUE TITLE
Editor Cursor Jumping on Edge

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#27]
The editor is now working on IE (cc @MathuraMG), but with a really annoying bug on IE and Edge. As soon as you focus and start typing in the editor, the cursor jumps to the top of the editor. I have no idea why this is happening. I looked at the CodeMirror examples on Edge and IE just to make sure it's not a weird IE/Edge and CodeMirror thing.

**Comment by MathuraMG** [comment]
I was just looking at the [link](http://52.41.35.139:8000/) and the editor actually works great on IE for me

**Comment by catarak** [comment]
Cool, I just tested on IE again and you're right, it's fine. I think this is only an issue on Edge.

**Comment by catarak** [comment]
just tested the editor on Edge and this isn't happening anymore ✨
