### ISSUE TITLE
`PlusIcon` Menu isn't closed when clicked outside and not on any MenuItem or on the Icon itself.

### ISSUE THREAD

**Issue by umangutkarsh** [processing/p5.js-web-editor#2703]
### Increasing Access

This would allow users to be able to close the Menu by clicking outside anywhere on the screen also.

### Feature enhancement details

Just like with the other DropDown menu options, this feature should be added in this PlusIcon also.

Steps to reproduce:

1. Go to p5.js-web-Editor
2. Expand the sidebar
3. Click on PlusIcon
4. Click outside -> The menu is not closed.
<img width="959" alt="iii" src="https://github.com/processing/p5.js-web-editor/assets/95426993/4d4ea6b8-c5bd-4f66-9a26-f52bfd64d57e">

**Comment by umangutkarsh** [comment]
I have a solution for this. Working on this.

**Comment by AdityaNik** [comment]
Hey, @umangutkarsh this issue is already mentioned here #2683

**Comment by raclim** [comment]
Yes, this has been cited already in the issue @AdityaNik mentions above! To organize and consolidate issues I'm going to close this one, but please feel free to go ahead and work on it!

**Comment by umangutkarsh** [comment]
Okay, I'll mention the PR in that issue.
Thanks for letting me know about it.
