### ISSUE TITLE
Adding Sketch Files menu doesn't collapse when clicked somewhere else on the page

### ISSUE THREAD

**Issue by Keshav-0907** [processing/p5.js-web-editor#2705]
### Most appropriate sub-area of p5.js?

- [X] Accessibility
- [ ] Color
- [ ] Core/Environment/Rendering
- [ ] Data
- [ ] DOM
- [ ] Events
- [ ] Image
- [ ] IO
- [ ] Math
- [ ] Typography
- [X] Utilities
- [ ] WebGL
- [ ] Build Process
- [ ] Unit Testing
- [ ] Internalization
- [ ] Friendly Errors
- [ ] Other (specify if possible)

### Web browser and version

119.0.6045.199

### Operating System

MacOSX

### Steps:
1. Go to `https://editor.p5js.org/`
2. Click to Add new Sketch Files, it opens a small menu 
3. Now on clicking somewhere else on the screen, the menu doesn't collapse

### Snippet:

<img width="1430" alt="Screenshot 2023-12-04 at 10 27 13 AM" src="https://github.com/processing/p5.js/assets/91189139/814b672e-3f87-4d7e-b6e8-a3b8504f7340">

**Comment by Simun-12** [comment]
Hi @Keshav-0907, you can assign me this issue.

**Comment by ujjwaleee26** [comment]
@Keshav-0907  this seem to be a issue in the code provided in p5.js-web-editor repo cause there is no such file to correct in p5.js repo code

**Comment by ShashwatPS** [comment]
Can I work on this issue ?

**Comment by Keshav-0907** [comment]
#2684

**Comment by Keshav-0907** [comment]
/ #2684

**Comment by gauravsingh94** [comment]
This issue is already open. Please check #2524
