### ISSUE TITLE
Changing class component to Functional Component.

### ISSUE THREAD

**Issue by Typicalcodes** [processing/p5.js-web-editor#2709]
### Increasing Access

It is important to update components according to new Functional components.

### Feature enhancement details

The component uses useRef for setting a reference to the Codemirror instance which can be used in any useEffect and function. I am referencing a pull request for these issue. I have done a pr before and changed my commit but it was unable to reach to maintainers.

**Comment by ayushlohmod** [comment]
Is this issue still open? I would like to work on it.
