### ISSUE TITLE
Confusing UX for uploading files

### ISSUE THREAD

**Issue by tegacodes** [processing/p5.js-web-editor#271]
The add file dialogue says:
 File must be of type JavaScript, CSS, JSON, TXT, or CSV.

But is this where images and sound files are to be added too? If so, might need to change this text so it includes these file types. Also there is there a way to move existing uploaded files into a newly created folder. ie. rearrange files?

**Comment by catarak** [comment]
This is just a confusing UX. The top half of that window is for adding text files, the bottom half is for adding any type of file, from images to sounds to fonts. 

You can't rearrange files, but feel free to add that as a ticket.

**Comment by catarak** [comment]
The new file screens can be found on the [Zeplin project](https://app.zeplin.io/project/55f746c54a02e1e50e0632c3/dashboard?tag=2017&tag=projectFiles). A few screens for reference:
<img width="768" alt="screen shot 2017-07-11 at 10 29 15 am" src="https://user-images.githubusercontent.com/6063380/28073595-3583854e-6624-11e7-9d2b-3d6b4012421d.png">
<img width="765" alt="screen shot 2017-07-11 at 10 29 40 am" src="https://user-images.githubusercontent.com/6063380/28073596-370beb5e-6624-11e7-8a2a-5d0645e0b61d.png">
<img width="512" alt="screen shot 2017-07-11 at 10 30 08 am" src="https://user-images.githubusercontent.com/6063380/28073599-38b5fc38-6624-11e7-9084-ce0410175fb2.png">
<img width="511" alt="screen shot 2017-07-11 at 10 30 25 am" src="https://user-images.githubusercontent.com/6063380/28073602-3a0b1582-6624-11e7-9ecc-3a93b61a1067.png">

**Comment by catarak** [comment]
Issues #388, #387, and #375 have been created to fix this, closing this issue.
