### ISSUE TITLE
mWeb (Safari) && mWeb(Chrome) - Tapping on sketch name by `username` redirects to nothing

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2717]
### p5.js version

2.10.0

### What is your operating system?

None

### Actual Behavior

mWeb (Safari) && mWeb(Chrome) - Tapping on sketch name by `username` redirects to nothing

https://github.com/processing/p5.js-web-editor/assets/47579287/92b4f248-3e33-4cec-a74e-edc520420a15

### Expected Behavior

mWeb (Safari) && mWeb(Chrome) - Tapping on sketch name by `username` should redirect to their respective username's saved sketches table page

### Steps:
1. Open the editor web app either in chrome or safari
2. Click on saved sketch name by `username`
3. Notice it does not redirects to anywhere

**Comment by aryanas159** [comment]
Can you elaborate on the issue here, I think the redirect to the particular sketch is working fine.

**Comment by lindapaiste** [comment]
It looks like the "by username" is not a link in the mobile header nav.  This is probably an oversight, but maybe we did it on purpose to prevent accidental clicks if the user wants to edit the title?  I don't recall.  Pinging @dewanshDT @shujuuu @raclim.

**Comment by PiyushChandra17** [comment]
@aryanas159 Sure, tapping on `username` does not redirect to anywhere on mWeb

**Comment by PiyushThapaa** [comment]
![Screenshot 2023-12-14 140145](https://github.com/processing/p5.js-web-editor/assets/112943430/97e67258-9472-4be6-ab7d-0db87477366f)

I am unable to find the react code of this block could anyone help me ??

**Comment by Suraj-Dhankad2025** [comment]
@PiyushChandra17 I have tried on both mobile and laptop using chrome there is no such issue.

**Comment by raclim** [comment]
> It looks like the "by username" is not a link in the mobile header nav. This is probably an oversight, but maybe we did it on purpose to prevent accidental clicks if the user wants to edit the title? I don't recall.

I don't think I was involved in this process at the time, but that makes sense to me! If it wasn't intended, I'm not sure if having the username linked would be something we might even want on mobile, but I could see folks getting confused if they're expecting this element.

**Comment by PiyushChandra17** [comment]
@raclim @lindapaiste Yes i do get the point that if the user wants to edit the title, it might lead to accidental clicks. But If we do it carefully then we might avoid this kinda situation. But If folks are getting confused then i think we should probably fix this issue.
