### ISSUE TITLE
Bug: Shortcuts Ctrl + Shift + 1 and Ctrl + Shift + 2 aren't working.

### ISSUE THREAD

**Issue by aryanas159** [processing/p5.js-web-editor#2719]
### p5.js version

v1.9.0

### What is your operating system?

Windows

### Web browser and version

120.0.6099.109 (Official Build) (64-bit) (cohort: M120 Rollout) 

### Actual Behavior

Shortcuts Ctrl + Shift + 1 and Ctrl + Shift + 2 should enable and disable the accessible output options, but they aren't doing anything.

### Expected Behavior

Shortcuts Ctrl + Shift + 1 and Ctrl + Shift + 2 should enable and disable the accessible output options.

### Steps:
1. Go to the web editor. 
2. Try the commands Ctrl + Shift + 1 to enable the accessible output options or disable them with Ctrl + Shift + 2 if they are already enabled.
3. Go to Accessibility in the settings and see that the accessibility options aren't changed
### Snippet:
```js

// Paste your code here :)

```

**Comment by aryanas159** [comment]
The issue is caused because of the shift key, the '1' is being registered as '!' and 2 is being registered as '@'.
![image](https://github.com/processing/p5.js-web-editor/assets/114330931/18689848-655b-4531-a3da-bf50ffb5d47f)

**Comment by mohitejaikumar** [comment]
is this issue still open
