### ISSUE TITLE
Consoleinput arrow is not Adjusting to changed theme.

### ISSUE THREAD

**Issue by Typicalcodes** [processing/p5.js-web-editor#2721]
### What is your operating system?

Windows

### Actual Behavior

Arrow in consoleinput is not adjusted to Themes.
![looking](https://github.com/processing/p5.js-web-editor/assets/100959820/0ae4f847-b969-40c9-9d18-84de728ca3b4)

### Expected Behavior

It should change colour according to theme.
![shoullook](https://github.com/processing/p5.js-web-editor/assets/100959820/5627f99a-0c8d-4da1-8782-ee550d9965a4)

### Steps:
1.  Start the editor 
2. Change the theme

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?
