### ISSUE TITLE
In settings, the color on hover in "General settings" and "Accessibility" is same as on selected

### ISSUE THREAD

**Issue by PiyushThapaa** [processing/p5.js-web-editor#2722]
### Increasing Access

It looks more good if the color on hover is lighter than the color on selected

### Feature enhancement details

https://github.com/processing/p5.js-web-editor/assets/112943430/2065b9fc-549b-4807-82e4-cad2554024ff

The color on hover should lighter than the color on selected..

**Steps to reproduce**

1. Go to the p5 web editor website
2. Go to settings

**Comment by KARAN-CODE50** [comment]
Hey there is this issue still open ? I wanted to contribute to it

**Comment by lindapaiste** [comment]
Personally I don't think this is a problem, as we have the pink underline to indicate the hover state.  But I'll leave it open for discussion.
