### ISSUE TITLE
mWeb - Safari: Clicking on user-menu && ellipsis options flickers for a while

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2724]
### p5.js version

2.10.0

### What is your operating system?

None

### Actual Behavior

mWeb - Safari: Clicking on user-menu && ellipsis options flickers for a while

https://github.com/processing/p5.js-web-editor/assets/47579287/f79e6a81-4f40-4108-b8ee-d0831add0456

### Expected Behavior

mWeb - Safari: Clicking on user-menu && ellipsis options should not flicker 

### Steps:
1. Open the editor web app in mWeb - safari
2. Click on user-menu options ie. My Stuff , Settings
3. Or Click on three dots ie. New, Save , Examples
4. Notice the option flickers while selecting

**Comment by lindapaiste** [comment]
It looks like there is some sort of "button pressed" style applied by the browser (useragent stylesheet).
![Screenshot 2023-12-15 11 42 04](https://github.com/processing/p5.js-web-editor/assets/28965286/cb84a5ec-b67f-4199-814f-ee2eff1d97eb)

**Comment by mrkirthi-24** [comment]
Hey @lindapaiste Can i work on this issue??

**Comment by krishanu7** [comment]
@lindapaiste can i work on this issue ? please describe shortly what i have to do.

**Comment by mrkirthi-24** [comment]
@krishanu7 please go ahead with this issue

**Comment by krishanu7** [comment]
@mrkirthi-24 Should i remove the flicker ?

**Comment by mrkirthi-24** [comment]
Yes please... I am actually busy in some other work... So you can go ahead
