### ISSUE TITLE
Ellipsis modal is not responsive on mWeb 

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2730]
### p5.js version

2.10.1

### What is your operating system?

Mac OS

### Actual Behavior

Ellipsis modal is not responsive on mWeb 

![ios-td](https://github.com/processing/p5.js-web-editor/assets/47579287/7aa64134-2290-413e-8c23-e739cc0210f7)

### Expected Behavior

Ellipsis modal should be responsive on mWeb 

### Steps:
1. Open the editor app on mweb
2. Tap on three dots
3. Notice the modal is not responsive

**Comment by PiyushChandra17** [comment]
@lindapaiste I think the recent fundraiser PR merged is causing this issue, need to investigate on this one.

**Comment by aryanas159** [comment]
@PiyushChandra17 You're right, the recently added 'fundraiser' item was causing the issue, adding a max-width fixed it, also the modal was overflowing and hiding the content in smaller screens, being able to scroll the menu will fix this issue.

**Comment by raclim** [comment]
Thanks for catching this! This is definitely on me—I should've handled the mobile nav changes more carefully, especially when I wasn't completely sure about it! 

I'm deploying the fix @aryanas159 created as an immediate remedy for now, since this issue greatly impacts the mobile experience.
