### ISSUE TITLE
Enhancement in prompt of You need to login or signup to save the project

### ISSUE THREAD

**Issue by aditya123473892** [processing/p5.js-web-editor#2734]
### Increasing Access

steps to reproduce 
 1) when you save the  project without login there appears a prompt that says In order to save sketches, you must be logged in. 
     Please [Login]  
 2) The buttons of login and signup are not properly visible it looks like normal text 

here is the image
![Screenshot 2023-12-17 012451](https://github.com/processing/p5.js-web-editor/assets/117269123/05ea5250-052d-44f6-9ca7-aaf5e5995465)

### Feature enhancement details

we can apply  background color of  the buttons to make it more user friendly

**Comment by aditya123473892** [comment]
can i work on it

**Comment by haarsh157** [comment]
I want to work on this issue kindly assign me this issue

**Comment by Sachin737** [comment]
I would like to work on it.

**Comment by Ranjeet0062** [comment]
"I am fixing this issue. Please consider my contribution, and if it is correct, then please merge it. I am providing a screenshot of the fixed issue."
![p5 errormodal](https://github.com/processing/p5.js-web-editor/assets/105407521/0d10bb3d-896c-4f39-8e3f-1e4ec5a9a3bd)

**Comment by lindapaiste** [comment]
I'm going to tag this with "needs design" because it's kind of subjective what it *should* look like.  I agree that those links should be more obvious but I'm unsure of the exact design that we would want.  I'd love to get some input from contributors with a design background!

**Comment by codebysid** [comment]
@lindapaiste this prompt has two buttons and styling both as filled button will indicate both as action buttons, instead styling them as Link Buttons ( with an underline ) would be better. Whats your thoughts on this ?

**Comment by haarsh157** [comment]
Hey @lindapaiste 
Can you consider this design which looks user friendly as well as the styling suits the design of the web editor

Also, I would like to suggest that should we have transitions when the user hovers over any of the button in the web editor to make it more user friendly?
![Screenshot from 2023-12-21 12-45-20](https://github.com/processing/p5.js-web-editor/assets/115213858/d13be0f2-af64-40ce-bb5d-d18d950a45bf)

**Comment by lindapaiste** [comment]
IMO this is a good opportunity for us to refine and/or expand our set of core UI components.  Whatever we come up with here can likely be used in other places.  I don't think we should be adding a bunch of CSS that is just for this one modal.

If we decide that we want a link-styled look then we should create a `TextLink` component and use it here.   We would use `styled-components` to create a wrapper around the `Link` (probably using the existing `ButtonOrLink` component).  The text would be the same color as the logo (pink).  Possibly bold?  Possibly underlined?  Maybe only underlined on hover?

If we want a button-styled look then we already have a `Button` component.  I realized that there are some problems in that component so I opened issue #2821 and PR #2822 to address that.

Our existing button styles would look like this:
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/9a526aa3-0ccf-4416-af65-cb22c316eec0)


> Hey @lindapaiste Can you consider this design which looks user friendly as well as the styling suits the design of the web editor
> 
> Also, I would like to suggest that should we have transitions when the user hovers over any of the button in the web editor to make it more user friendly? ![Screenshot from 2023-12-21 12-45-20](https://private-user-images.githubusercontent.com/115213858/292124688-d13be0f2-af64-40ce-bb5d-d18d950a45bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNDAxNzQsIm5iZiI6MTcwNDEzOTg3NCwicGF0aCI6Ii8xMTUyMTM4NTgvMjkyMTI0Njg4LWQxM2JlMGYyLWFmNjQtNDBjZS1iYjVkLWQxOGQ5NTBhNDViZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMVQyMDExMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTQ5ZDA0ODg0ODUxZGM4NThhYzE2N2I4MGFjMzBhMjI4MGI4MWJjNGY3ZThiMWVlY2E2OWU5YWQ1YzA3YTNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UrfhPLfjeK4YjklgriMOCSlfBjMo4mIfL41u5Aeu4-8)

This looks really nice.  IMO it looks better than our standard buttons, but for the sake of consistency we probably want to use the same standard buttons.  I'm not opposed to changing the standard gray button everywhere to look more like this, but that's a larger change that requires more discussion and consensus.

Let's open a new discussion or issue to talk about transitions.  The way that we invert from dark-on-light to light-on-dark makes it hard to transition nicely.

I noticed that we don't have any hover effect on the solid pink button style and that's an easier fix.  I'm going to make an issue and assign it to you.

**Comment by aditya123473892** [comment]
@lindapaiste we might need to have different colour composition for different contrast themes. In dark mode the button looks easily visible but in contrast and light mode its  kind off less visible and seems like simple text more

**Comment by lindapaiste** [comment]
Here's two possible link-styled looks.
![Screenshot 2024-01-03 12 40 30](https://github.com/processing/p5.js-web-editor/assets/28965286/a572c764-f096-4167-a5e8-df7d555c5d8d)
![Screenshot 2024-01-03 12 40 38](https://github.com/processing/p5.js-web-editor/assets/28965286/a0171d33-71a6-43bb-b339-a0d2c33e7539)

**Comment by aditya123473892** [comment]
i already made the pull request for above one but it looks same  in contrast or dark mode  #2755

**Comment by raclim** [comment]
I agree with @lindapaiste that we'll want something that is consistent and reusable throughout the editor rather than making several css changes. I feel like we can wait to address this until we reach a consensus on a longterm solution for implementing these types of links. I'm going to close the pull requests that have been created for this issue so far for now since I feel that they're currently implementing css changes that might not work/be consistent with other links in the editor!
