### ISSUE TITLE
Consoleinput is not a functional Component

### ISSUE THREAD

**Issue by Typicalcodes** [processing/p5.js-web-editor#2737]
### Increasing Access

We should use react hooks and new functional components.

### Feature enhancement details

Converting consoleinput class component to a functional component.

**Comment by raclim** [comment]
Thanks for raising this! This has already been addressed in an earlier PR and issue (https://github.com/processing/p5.js-web-editor/pull/2360), so I'm going to close this for now, but please feel free to check out and work on our other issues!
