### ISSUE TITLE
Google Apps Login / SSO

### ISSUE THREAD

**Issue by agersoncgps** [processing/p5.js-web-editor#275]
Eventually a "Login with Google" would be amazing. Just one less account for the kids to have to create.

**Comment by catarak** [comment]
there's currently an open PR (#224) about this, but #248 needs to happen first 😄

**Comment by catarak** [comment]
Another question/open discussion I have about this is should accounts be automatically linked? i.e. if you register with your email and then try to login with Github or Google or whatever, should it automatically link to your email? I think this should happen _only_ if your email is verified, which is a work in progress. And on a user's account settings page, they should be able to link accounts from there/change the Github/Google/Whatever profile that is linked to the account.

**Comment by agersoncgps** [comment]
Yes, I think only one unique email addressed should be allowed across accounts, regardless if its created with Google Apps APIs or local accounts. So, yes, I think they should be linked. I would think the act of authenticating with Google would serve the same purpose as verifying the email.

**Comment by catarak** [comment]
I _think_ the only issue with automatically linking accounts without an email verification is the following circumstance:
1. A user creates an account with an email address they don't have access to.
2. Another user creates an account with Github, connected with the email the first user had. 
3. The second user now has access to the account of the first user.

**Comment by agersoncgps** [comment]
In this case was the first user was fraudulently identifying themselves with the email belonging to the second user? If so wouldn't blocking access to the main functionality of the site until the email was verified handle this? And if an unverified, un-populated with content account gets handed over to its rightful owner, isn't that ok?

**Comment by catarak** [comment]
hmmm I think you are right. thanks for talking this out with me!
