### ISSUE TITLE
We should raise different toast message when clicking on `Save All Settings`

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2757]
### Increasing Access

Unsure

### Feature enhancement details

Currently, on account settings page - Even if we do not edit any details, we get the toast message **Settings saved.** 
Instead toast message should be `Please update your account detail`.

**Comment by gauravsingh94** [comment]
@PiyushChandra17  @lindapaiste Please give you thoughts on this 

Final Output

[Screencast from 2023-12-24 03-11-28.webm](https://github.com/processing/p5.js-web-editor/assets/99260988/be289c2d-a357-4394-b6f9-647f03376df8)

**Comment by PiyushChandra17** [comment]
@lindapaiste I think we should probably update the toast message, It would enhance the user experience i reckon.Thanks!

**Comment by lindapaiste** [comment]
I'm not sure about this.  I think that the current message is fine 🤷.  The settings that are saved do in fact match the current settings, so it's not inherently incorrect or misleading.

**Comment by raclim** [comment]
Agree that I'm not sure about this one either. I don't think this is something that we might be implementing in the near future, so I'm going to close this for now!
