### ISSUE TITLE
NavBasic component is a class component

### ISSUE THREAD

**Issue by haarsh157** [processing/p5.js-web-editor#2759]
### Increasing Access

This particular component that is being used in the share modal is implemented using legacy react class component.

### Feature enhancement details

This component can be converted to a functional component.

**Comment by sarthkjoshi** [comment]
I'm solving this issue.

**Comment by lindapaiste** [comment]
This component is not used and there is an open PR to delete it.  See #2555

**Comment by sarthkjoshi** [comment]
> This component is not used and there is an open PR to delete it. See #2555

Okay
