### ISSUE TITLE
"p5.AudioIn is not a constructor"

### ISSUE THREAD

**Issue by ariciano** [processing/p5.js-web-editor#276]
Using the code in the example hasn't been working to get audio input from computer's microphone.

"var mic;
function setup(){
  mic = new p5.AudioIn()
  mic.start();
}"

**Comment by catarak** [comment]
In order to use live video/audio, you have to use https! Try navigating to the same URL you were using, except replace the beginning `http://` with `https://`. There is an open issue about this to add a button/explanation about this, #170. 

If this still doesn't work, let me know!

**Comment by ariciano** [comment]
thank you - I have been and it still doesnt work

**Comment by catarak** [comment]
okay, I'll investigate further

**Comment by ariciano** [comment]
<img width="696" alt="screen shot 2017-01-20 at 2 49 50 pm" src="https://cloud.githubusercontent.com/assets/22209957/22163183/c11d5e68-df1f-11e6-9acc-62c95f402d7f.png">

**Comment by ariciano** [comment]
thank you!

**Comment by catarak** [comment]
unfortunately this sketch is working totally fine for me... again, maybe you accidentally deleted p5.sound from your html?

**Comment by chad187** [comment]
I am getting that same error with https. I am running it with node 11.6 and express 4.16.4
here is my code
![f2](https://user-images.githubusercontent.com/8450028/51051291-3dea1f80-1588-11e9-9707-c6924b85b823.GIF)
![f3](https://user-images.githubusercontent.com/8450028/51051292-3dea1f80-1588-11e9-8dda-0d6ed7b6521b.GIF)
![f1](https://user-images.githubusercontent.com/8450028/51051294-3dea1f80-1588-11e9-86d3-dfeb740e1a9b.GIF)
![f4](https://user-images.githubusercontent.com/8450028/51051293-3dea1f80-1588-11e9-8ba6-5e944f90d074.GIF)

**Comment by catarak** [comment]
@chad187 i think this is because you're not including the p5.sound library in your index.html. also, the issue you posted isn't related to the web editor, so i recommend posting it to https://github.com/processing/p5.js if you think there is an issue with p5, or to the [processing forum](https://discourse.processing.org) if you're having an issue with using the library.

**Comment by bendeg** [comment]
Like chad, I had the same issue and it worked right way after adding p5.sound.js (p5.min.js already added)

**Comment by carlesgutierrez** [comment]
I have this error with Firefox and using the online Sound min library with the webeditor
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.10.2/addons/p5.sound.min.js"></script>`
```
Is my firefox wrong? I'm the only one this error? 

Test code https://editor.p5js.org/shiffman/sketches/S1ZGs5WZG
error:

>  TypeError: p5.AudioIn is not a constructor (sketch: line 18)

**Comment by catarak** [comment]
@carlesgutierrez can you post a link to your sketch? I'm not able to reproduce.

**Comment by tensionhead** [comment]
Seems like for sound processing you have to add
```html
<script src="https://cdn.jsdelivr.net/npm/p5@1.3.1/lib/addons/p5.sound.js"></script>
```
to your html. Before doing this I got the same error as @ariciano I am a total beginner with P5.js, but maybe it' really not entirely clear from the [**Get Started**](https://p5js.org/get-started/) section?!
