### ISSUE TITLE
mWeb - `Support p5.js and the Processing Foundation` modal is not responsive 

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#2760]
### p5.js version

2.10.2

### What is your operating system?

Mac OS

### Actual Behavior

mWeb - `Support p5.js and the Processing Foundation` modal is not responsive 

https://github.com/processing/p5.js-web-editor/assets/47579287/3862a029-374f-4fb5-a69c-8ec206249cd2

### Expected Behavior

mWeb - `Support p5.js and the Processing Foundation` modal should be responsive 

### Steps:
1. Open the editor web app in mobile web
2. Tap on three dots
3. Tap on Support p5.js and the processing foundation
4.  Notice the modal is not responsive

**Comment by PiyushChandra17** [comment]
@lindapaiste What are your thoughts on this one? If we are not planning to keep this modal in the long term, then probably it's not big of a deal. Please let me know if i should proceed with this issue and raise a PR. Thanks!

**Comment by raclim** [comment]
Thanks for reporting this. Merging this in would be ideal, but I don't think we're going to do it by the time we we're planning to take down this modal, which is on January 15th. I'm going to close this for now, but we can keep this in mind to implement a better mobile experience for the next fundraiser.
