### ISSUE TITLE
Error not handled correctly in server/controllers/user.controller.js

### ISSUE THREAD

**Issue by BrawlerXull** [processing/p5.js-web-editor#2762]
### What is your operating system?

None

### Actual Behavior

Error is not handles correctly

### Expected Behavior

Should be handles correctly

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)
// This is what i propose 
// Please let me know if here is a better way to solve this
export function findUserByUsername(username, cb) {
  User.findByUsername(username, (err, user) => {
    if (err) {
      console.error("Error finding user:", err);
      cb(null); 
    } else {
      cb(user); 
    }
  });
}

**Comment by BrawlerXull** [comment]
<img width="1440" alt="Screenshot 2023-12-23 at 8 40 38 PM" src="https://github.com/processing/p5.js-web-editor/assets/111864031/193952ca-8d38-44cb-8c27-5488c838e4fc">

**Comment by BrawlerXull** [comment]
Or we can return a promise?

**Comment by lindapaiste** [comment]
TBH I wonder if we even need this findUserByUsername function?  We could update the one place it’s used, in the aws.controller, to call User.findByUsername directly.

**Comment by BrawlerXull** [comment]
@lindapaiste i opened the issue but someone else have sent pr I want to solve this

**Comment by BrawlerXull** [comment]
@lindapaiste also please let me know if there is any slack channel to connect with the org members

**Comment by BrawlerXull** [comment]
> TBH I wonder if we even need this findUserByUsername function? We could update the one place it’s used, in the aws.controller, to call User.findByUsername directly.

I'll look into it
