### ISSUE TITLE
loadSound does not work

### ISSUE THREAD

**Issue by ariciano** [processing/p5.js-web-editor#277]
<img width="895" alt="screen shot 2017-01-20 at 2 54 57 pm" src="https://cloud.githubusercontent.com/assets/22209957/22163355/773a5db8-df20-11e6-9cea-f0c2e07f5713.png">

**Comment by catarak** [comment]
i'm not able to reproduce this, as [this sketch](https://alpha.editor.p5js.org/cassie/sketches/rJPTZ-HDx) is working totally fine for me. I tried on both http and https. Maybe you accidentally removed the link to p5.sound from your `index.html`?
