### ISSUE TITLE
The sidebar project options disappear only when clicked on the toggle button.

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#2770]
### Actual Behavior

The sidebar project options disappear only when clicked on the toggle button. 

https://github.com/processing/p5.js-web-editor/assets/80570105/cf426cbe-c934-4c72-9593-e639d28cc636

### Expected Behavior

The expected behavior should be that the sidebar project options should disappear whenever clicked anywhere outside.

@lindapaiste @raclim can you assign this issue to me?

**Comment by gauravsingh94** [comment]
Please refer this #2524  
It is already open.
