### ISSUE TITLE
Consistent Hover Styling for Login and Signup Links in Error Component.

### ISSUE THREAD

**Issue by gauravsingh94** [processing/p5.js-web-editor#2773]
### Increasing Access

In other sections of the website, hovering over a component changes it to the primary color. Applying the same effect here will create a uniform website design.

### Feature enhancement details

Applying the same effect here will create a uniform website design.

![image](https://github.com/processing/p5.js-web-editor/assets/99260988/de55537a-072c-4103-9908-39a978dc3d46)

**Comment by gauravsingh94** [comment]
In other section on hover 
![image](https://github.com/processing/p5.js-web-editor/assets/99260988/cc1bf6c7-72c2-4190-a178-ab9210611a25)



In the Error Section


![image](https://github.com/processing/p5.js-web-editor/assets/99260988/e7dcff4d-5e6c-4500-99ae-e2d7df438214)

**Comment by lindapaiste** [comment]
Related to #2734

**Comment by aditya123473892** [comment]
1. this enhancement  is already under discussion

**Comment by raclim** [comment]
Thanks for your input on this! Since this is already open, to consolidate issues I'm going to close this for now.
