### ISSUE TITLE
Adding an iconpack for files

### ISSUE THREAD

**Issue by rahulkhattri0** [processing/p5.js-web-editor#2775]
### Increasing Access

This will enhance UX a little bit.

### Feature request details

![image](https://github.com/processing/p5.js-web-editor/assets/72620481/3f9ecdb7-09a5-42ae-9d8f-db9e1e8f299b)
Here we can add icon images according to the file type.

**Comment by rahulkhattri0** [comment]
If this seems like a good idea,please assign this issue this to me.

**Comment by gauravsingh94** [comment]
> If this seems like a good idea,please assign this issue this to me.

Please proceed with the task without seeking assignment confirmation. Your pull request will be reviewed by Lindapaiste  and subsequently merged by Raclim. 
Keep it simple.

**Comment by Sahil-Shadwal** [comment]
> If this seems like a good idea,please assign this issue this to me.

Are you working on this ? If not , then i would like to work on this issue

**Comment by rahulkhattri0** [comment]
> > If this seems like a good idea,please assign this issue this to me.
> 
> Are you working on this ? If not , then i would like to work on this issue

yes

**Comment by salmanansari14** [comment]
hello, I want to working on it ?

**Comment by lindapaiste** [comment]
Hey I just wanted to say that we already have an issue for this #2542.  We have the code but we're still kinda unsure on which exact icon pack to use.  Feel free to chime in on that thread.
