### ISSUE TITLE
Issues with Saving Project When Refreshing Page? 

### ISSUE THREAD

**Issue by gauravsingh94** [processing/p5.js-web-editor#2788]
### Increasing Access

**Existing Problem**

1. When we are refreshing the accedently remove the ide content.

2 Storing what they have written to the local store would be benifical they will not lost their work if they accidently refresh their page.

### Feature enhancement details

3. i will implement a buttom same as auto refresh named "auto save" it will the project automatically.

Please give me your views on this so that i can start working on it if it feels legit to you.

**Comment by gauravsingh94** [comment]
@lindapaiste 
Please give me your views on this so that i can start working on it if it feels legit to you.

**Comment by SasiDharan731** [comment]
This seems like a good idea and I think this issue should be moved into the newly introduced discussion tab. @raclim

**Comment by raclim** [comment]
We do already have 'Autosave' in the Settings modal and I think we should already be informing users if they're closing out a page with unsaved changes, but I could be wrong on that one. I agree and think we could see if others also face these types of saving issues and how they currently handle it, or what some other workarounds could be!
