### ISSUE TITLE
Check Out Our Discussions!

### ISSUE THREAD

**Issue by raclim** [processing/p5.js-web-editor#2792]
We recently opened up Discussions (which is next to the Pull requests tab in the navigation menu) to create more open forums for communal discourse and to help organize and distinguish issues that might need further input. 

We are going to start migrating some issues that we feel are good discussion topics there, so please direct any future feature requests, ideas, or any other topics that might need community insight within the Discussions tab. If you're interested in assisting with moderating Discussions in accordance with [our community guidelines](https://p5js.org/community/), give a shout out below and we can get back to you by around January 18th!

**Comment by aryanas159** [comment]
Hey, @raclim, I would love to help with moderating discussions.

**Comment by vivekbopaliya** [comment]
i am up!

**Comment by aditya123473892** [comment]
i would like being part of it

**Comment by PiyushThapaa** [comment]
I would love to be a part of it

**Comment by 0Kaju12** [comment]
i would like to be a part of it

**Comment by arpitghura** [comment]
I would love to be a part of it.

**Comment by gauravsingh94** [comment]
I will happy to be the part of it.

**Comment by chandrudu461** [comment]
I will happy to be the part of it.
