### ISSUE TITLE
font not loading

### ISSUE THREAD

**Issue by peterthompsonnz** [processing/p5.js-web-editor#280]
When using the `textFont` function to set a font the following error occurs:
```
var f;

function preload() { 
  f = loadFont("SourceCodePro-Regular.ttf");
}

function setup() {
  createCanvas(480, 440);
  imageMode(CENTER);
  textFont(f);
}
```
"Uncaught TypeError: Cannot read property 'appendChild' of undefined (sketch: line 202)"

This also occurs when `ellipseMode` is set to `RADIUS` in `setup`.

Browser: Chromium, Version 52.0.2743.116 Built on Ubuntu , running on elementary OS 0.3.2 (64-bit)

**Comment by peterthompsonnz** [comment]
Extensions disabled, browser restarted, shutdown and extensions enabled: issue fixed.

**Comment by catarak** [comment]
glad you were able to figure this out!
