### ISSUE TITLE
Turning the environment variables more modular and easy to use with a Config Object export.

### ISSUE THREAD

**Issue by Zack-Dx** [processing/p5.js-web-editor#2806]
### Increasing Access

This would help to make the code modular and increase its readability.

### Feature enhancement details

Adding this file would help to organise them in a much better way, and we can simply use them just by their name instead of adding a suffix as a process.env everywhere so that we can just destructure the Config object on top and access them.

**Comment by pankaj-2503** [comment]
I would like to contribute to this issue as it seems i can work on this by including .env file and writing variables into that so that we can use them for better code modularity and reusability

**Comment by Zack-Dx** [comment]
Assign me this.
