### ISSUE TITLE
Error message not indicating the right line

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#283]
In my tests, the message was always 4 lines higher than the actual broken line. The red highlight is correct. 
<img width="664" alt="screen shot 2017-01-28 at 4 23 07 pm" src="https://cloud.githubusercontent.com/assets/6563969/22402084/73896512-e5b8-11e6-8b4a-04e72cb6f407.png">

**Comment by catarak** [comment]
can add a link to this sketch specifically? I'm not able to reproduce.

**Comment by joemckay5** [comment]
It happens if the error comes after a for loop. Here's an example. 
http://alpha.editor.p5js.org/Joemckay/sketches/BJnVmhiwg

**Comment by catarak** [comment]
I think this may also have to do with the infinite loop protection code. I'll look into it.

**Comment by catarak** [comment]
I was able to fix this by updating my loop protect code at https://github.com/catarak/loop-protect. Deploying to production shortly.
