### ISSUE TITLE
Adding drag and drop feature in code navigation 

### ISSUE THREAD

**Issue by aditya123473892** [processing/p5.js-web-editor#2831]
### Increasing Access

This would help the users to drag and drop the files from one folder to another in their projects. It might be timesaving 

### Feature request details

![Screenshot 2024-01-03 155705](https://github.com/processing/p5.js-web-editor/assets/117269123/9de9a6a4-8265-4499-ac2e-aa5ca9225a9b)

**Comment by aditya123473892** [comment]
can i be assigned with this feature if it is worth adding

**Comment by ayushlohmod** [comment]
Hi @aditya123473892, if you need any help with this project, I'm happy to pitch in.

**Comment by krishanu7** [comment]
will you use React DND or hard code it  ? if you need any help please connect with me.

**Comment by aditya123473892** [comment]
@ayushlohmod  i would very much  require help for the project for proceeding further just  basic idea how to proceed

**Comment by Ayush-Vish** [comment]
@ayushlohmod  I would like  to wor kon this issue. 
I have hands on experience in Drag and drop using Reat DND .

**Comment by aditya123473892** [comment]
@lindapaiste can u please give a feedback on this feature

**Comment by raclim** [comment]
Thanks for raising this! This was already proposed earlier in https://github.com/processing/p5.js-web-editor/issues/1417, so I'm going to close this to organize and consolidate issues. Please feel free to go ahead with working on this feature based on the discussion in that thread.
