### ISSUE TITLE
Refactoring Searchbar from class component to functional component. Enhancement

### ISSUE THREAD

**Issue by Shyam-Raghuwanshi** [processing/p5.js-web-editor#2832]
### Increasing Access

Unsure

### Feature enhancement details

Feature enhancement details
The Searchbar component still uses class based component structure. Changing it to functional based component would simplify the state management and maintainability of code along with being consistent with modern react

**Comment by lindapaiste** [comment]
Hey we have like 7 different PRs for converting the component.   The complex part is properly memoizing the `throttle` and a lot of the PRs didn't do that part properly.  I need to review them all and find one which handles it best.

**Comment by lindapaiste** [comment]
In the meantime I'm going to close this because we don't need any additional PRs.
