### ISSUE TITLE
Find and Replace dialog has design inconsistencies

### ISSUE THREAD

**Issue by mrkirthi-24** [processing/p5.js-web-editor#2834]
### p5.js version

v1.9.0

### What is your operating system?

Mac OS

### Web browser and version

Google Chrome 120.0.6099.129

### Actual Behavior

![Screenshot 2024-01-05 at 1 04 28 AM](https://github.com/processing/p5.js-web-editor/assets/53830546/3d6b6841-c97f-46c3-9647-2b9ea6152b75)

I feel the dialog box has some inconsistencies.

### Expected Behavior

Input fields need to fill the gap and the buttons need to aligned properly.

### Steps:
1. Go to p5.js web editor
2. In the Edit menu, click Replace option
3. Find and Replace dialog box will appear

**Comment by mrkirthi-24** [comment]
@lindapaiste I would like to work on the issue if validated.

**Comment by lindapaiste** [comment]
> @lindapaiste I would like to work on the issue if validated.

Yes it's definitely a mistake.  I think we messed it up when we rolled out the responsive design.  It might help to look through the git history for that file and see what changed.  I think we probably changed some CSS to make the "find" modal responsive and didn't think about what would happen to the "find and replace" one.

**Comment by Pankaj3112** [comment]
@lindapaiste can i work on this?

**Comment by lindapaiste** [comment]
Fixed by #3037
