### ISSUE TITLE
Adding Hovering to travel in navbar rather than clicking.

### ISSUE THREAD

**Issue by shubham-200315** [processing/p5.js-web-editor#2838]
### Increasing Access

Unsure

### Feature enhancement details

**_Current Condition_** :   As of now we have to click on one of the option in navbar(file/edit/sketch/help) to open its sub-options and only then it allow us to hover iterate over other option's sub option.

**_What I'm Proposing_**:   We can add a feature to let our user open the option's suboption on just hovering over it rather that clicking on it and opening anyone one of it to enable hovering for rest of the options.  

https://github.com/processing/p5.js-web-editor/assets/105916104/e3b451f8-1d4c-4edf-852b-2f24c8a25751

Hey @raclim  @lindapaiste , Can we proceed with this ? I have a plan of how to approach this just needed your conformation.
Thank you for your consideration.

**To everyone : If anyone has better  idea on how to approach this I am open to suggestion.**

**Comment by lindapaiste** [comment]
This has been proposed before but we're happy with the way that it is now.  See #2544 and #443 for discussion.

**Comment by shubham-200315** [comment]
Ya I think you are right..It'll be a Chaos for user if not hovered deliberately.
Thank you for your suggestion and closing the issue.
