### ISSUE TITLE
Date Range Picker (File->Examples/Open)

### ISSUE THREAD

**Issue by shubham-200315** [processing/p5.js-web-editor#2840]
### Increasing Access

Unsure

## Where to Find the Issue:

1. Visit [p5.js Web Editor](https://editor.p5js.org/).
2. Navigate to the "File" option.
3. Select either the 'Open' or 'Examples' suboption.
4. Within the chosen option, locate the table with filtering options for 'Date Created' and 'Date Updated'.

## Current Condition:

As of the present moment, users can only sort their sketches based on the latest or oldest order.

![Current Screenshot](https://github.com/processing/p5.js-web-editor/assets/105916104/78b8d8ad-1406-42b3-ba01-9e027ce2ba43)

## Proposed Enhancement:

I propose the addition of a date range picker (utilizing any external React component) to facilitate the selection of a date range from dd:mm:yyyy to dd:mm:yyyy. This feature aims to assist users in easily locating projects created within a specific timeframe.

![Proposed Screenshot](https://github.com/processing/p5.js-web-editor/assets/105916104/9a1ebf32-4b21-491b-826f-a22540c36099)

## Action Items:

Hey @raclim, @lindapaiste, please take a look (PTAL) and provide feedback on whether we can proceed with this enhancement. I have a detailed plan on how to implement it and would appreciate your approval.

## Community Engagement:

To the entire community: If anyone has a better idea or suggestions, please feel free to share and collaborate on this improvement.

**Comment by skushagra9** [comment]
I would like to work on this

**Comment by shubham-200315** [comment]
Sure you can buddy, but let maintainers approve it first.

**Comment by lindapaiste** [comment]
I'll defer to @raclim on this because I don't have a strong opinion.  I think it might be excessive and I don't want to clutter the UI with features that aren't used very often but I'm not totally opposed.

**Comment by pankaj-2503** [comment]
> I'll defer to @raclim on this because I don't have a strong opinion. I think it might be excessive and I don't want to clutter the UI with features that aren't used very often but I'm not totally opposed.

Yeah, I also think this might be excessive and would create lot of clutter to UI . It should have to be minimalistic and simple to use.

**Comment by shubham-200315** [comment]
Yeah @lindapaiste you are right , like i was just keeping in mind about the scenario when there will be like 100s of sketches and user may want to see only this month sketches or something then she/he can. If you feel like you can close this issue. We can work on something more important.
Thank you for responding.

**Comment by Vishal2002** [comment]
@shubham-200315  @lindapaiste  @pankaj-2503   Instead of a date picker we should only have the dropdown menu to choose a month and for that respective month we would have the sketches. Isn't it a good idea

**Comment by shubham-200315** [comment]
@Vishal2002 , Ya might be but I am sure if maintainer are picking up this issue at first place.

**Comment by raclim** [comment]
I think this could be helpful, especially for folks who have a lot of sketches, but I guess I'm not envisioning all the use cases for it yet and feel that this might not be a priority feature to implement.

Maybe a feature that might achieve something similar to this in terms of pinpointing/organizing sketches, but is more complicated, would be adding tags (https://github.com/processing/p5.js-web-editor/issues/557)? 

 I think I might close this for now, but would be open to reopening it if there's ideas on specific scenarios where having a date range picker would be particularly helpful vs other organizational features!
