### ISSUE TITLE
The t&c portion of the SingUp page is not translated

### ISSUE THREAD

**Issue by harmanbatheja15** [processing/p5.js-web-editor#2846]
### What is your operating system?

Mac OS

### Actual Behavior

The T&C is not being translated

<img width="748" alt="Screenshot 2024-01-06 at 6 44 30 AM" src="https://github.com/processing/p5.js-web-editor/assets/66913564/f00223d5-429a-48bc-bf56-5cc3b93ff481">

### Expected Behavior

The T&C should be translated.

<img width="610" alt="Screenshot 2024-01-06 at 6 45 04 AM" src="https://github.com/processing/p5.js-web-editor/assets/66913564/927dc550-0d5c-483b-b6d1-e10c7c615ecd">

### Steps:
1. Add ```"Warning": "By signing up, you agree to the p5.js Editor's <0>Terms of Use</0> and <1>Privacy Policy.</1>"``` in [_translations/locales/en-US/translations.json_](/processing/p5.js-web-editor/blob/develop/translations/locales/en-US/translations.json) file, inside the _SignupView_ section.
2. Update the import statement in the [_SignupView.jsx_](/processing/p5.js-web-editor/blob/develop/client/modules/User/pages/SignupView.jsx) file.
3. Add the updated Translation code in the [_SignupView.jsx_](/processing/p5.js-web-editor/blob/develop/client/modules/User/pages/SignupView.jsx) file.

### Snippet:

```js

"SignupView": {
    "Title": "p5.js Web Editor | Signup",
    "Description": "Sign Up",
    "Or": "Or",
    "AlreadyHave": "Already have an account?",
    "Login": "Log In",
    "Warning": "By signing up, you agree to the p5.js Editor's <0>Terms of Use</0> and <1>Privacy Policy.</1>"
  },

```

```js

import { useTranslation, Trans } from 'react-i18next';

```

```js

<Trans
    i18nKey="SignupView.Warning"
    components={[
        <Link to="/terms-of-use">Terms of use</Link>,
        <Link to="/privacy-policy">Privacy Policy</Link>
    ]}
/>

```

**Comment by lindapaiste** [comment]
fixed by #2847
