### ISSUE TITLE
Changing a duplicate changes the original

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#285]
Perhaps this is on purpose? In most programs "duplicate" means make a copy, but changes to the new copy do not affect the original - this is what I was expecting. If there's a solid reason for changes to the duplicate to also change the original then it needs to be more explicit just what "duplicate" means.

**Comment by catarak** [comment]
Woah, no, this is definitely a bug. Changing the copy should not affect the original.

**Comment by joemckay5** [comment]
I didn't think so, but I didn't know what "linting" meant either, so I was hedging my bets :)

**Comment by catarak** [comment]
😂

**Comment by catarak** [comment]
fixed and deployed!
