### ISSUE TITLE
Improper button layout on find and replace dialog box in mobile view

### ISSUE THREAD

**Issue by mrkirthi-24** [processing/p5.js-web-editor#2857]
### p5.js version

v1.9.0

### What is your operating system?

Mac OS

### Web browser and version

Google Chrome 120.0.6099.129

### Actual Behavior

Buttons are not properly aligned on Find and Replace dialog box on mobile view

![Screenshot 2024-01-07 at 12 36 01 PM](https://github.com/processing/p5.js-web-editor/assets/53830546/9aefc2a3-dc0b-4204-bed3-c0a795dfcbe6)

### Expected Behavior

Proper padding needs to be added on small screens

### Steps:
1. Open p5.js Web Editor in mobile screen
2. In the Edit menu, click Replace option
3. Find and Replace dialog box will appear

**Comment by lindapaiste** [comment]
fixed by #3037
