### ISSUE TITLE
Issue with Language Change and Invalid Username/Password Error on p5.js Web Editor

### ISSUE THREAD

**Issue by Vishal2002** [processing/p5.js-web-editor#2860]
### p5.js version

v1.9.0

### What is your operating system?

Windows

### Web browser and version

120.0.6099.199

### Actual Behavior

**When we sign in and give the wrong credentials then the error message from server is always appear in english even though we have changed the preferred language.**

<img width="960" alt="Screenshot 2024-01-07 134808" src="https://github.com/processing/p5.js-web-editor/assets/35897449/1a5ccd7c-f5b4-4abc-bf5d-d881ad226df4">

### Expected Behavior

**The Error message should also be in the preferred language.**

### Steps:
1. Go to the sign in page in the p5.js web editor.
2. Try to sign in with wrong credential 
3. You will see some errors but when you change the preferred language from the top then also you will find the same error.

**Comment by aryanas159** [comment]
Hey, @Vishal2002 are you working on this issue?

**Comment by Vishal2002** [comment]
> Hey, @Vishal2002 are you working on this issue?

I have raised the issue and looking for the maintainers to look into it.

**Comment by aryanas159** [comment]
This issue is caused because we are directly displaying the error message coming from the API request, I don't think we currently have translations to handle the ```submitError``` in the LoginForm. We are probably gonna need to add new translations for every language.
I can work on this.
@lindapaiste how do you suggest we proceed?

**Comment by Vishal2002** [comment]
@aryanas159 Buddy that I know

**Comment by Keshav-0907** [comment]
Actually their are translations already present for the errors  : `ReduxFormUtils`

```json
"ReduxFormUtils":  
{
    "errorInvalidEmail": "Please enter a valid email address",
    "errorEmptyEmail": "Please enter an email",
    "errorPasswordMismatch": "Passwords must match",
    "errorEmptyPassword": "Please enter a password",
    "errorShortPassword": "Password must be at least 6 characters",
    "errorConfirmPassword": "Please confirm your password",
    "errorNewPassword": "Please enter a new password or leave the current password empty.",
    "errorEmptyUsername": "Please enter a username.",
    "errorLongUsername": "Username must be less than 20 characters.",
    "errorValidUsername": "Username must only consist of numbers, letters, periods, dashes, and underscores."
}

**Comment by aryanas159** [comment]
@Keshav-0907 These are error messages for form validations, not for submissions.

**Comment by Vishal2002** [comment]
@lindapaiste I think we have to integrate i18n library in backend which will first get the preferred language and upto to that we will send the response in the preferred language only.
