### ISSUE TITLE
the translation feature for the string which is top in nav bar is not working

### ISSUE THREAD

**Issue by shivapranav07** [processing/p5.js-web-editor#2865]
### What is your operating system?

Windows

### Actual Behavior

the text which is on the nav bar is not changing when we change the language 
<img width="1078" alt="issue3" src="https://github.com/processing/p5.js-web-editor/assets/152789149/e33ed8f8-35b6-423d-9414-e1f8b1d1afde">

### Expected Behavior

the language must be changed to the selected language

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)

```

**Comment by KartikChawla09** [comment]
I would like to work on the issue! Please assign it to me!

**Comment by shivapranav07** [comment]
actually i am working on this issue !

**Comment by KartikChawla09** [comment]
> actually i am working on this issue !

Oh, I have already executed the modification and was in the process of preparing a pull request. Nevertheless, please feel free to proceed with your work on the given issue.

**Comment by shivapranav07** [comment]
Actually it is my fst tym doing open source i have sorted the issue if it
doesnt work feel free to override my pull req

**Comment by shivapranav07** [comment]
@lindapaiste can you please review my pull req

**Comment by harmanbatheja15** [comment]
I think there is no issue there. The translation for that text is not added in the particular languages. @lindapaiste Can you confirm I am right or not?

**Comment by shivapranav07** [comment]
Yes, they have used the keyword "Fundraiser," but it appears that the translation for that term has not been added in any language. Am I correct @harmanbatheja15 ?

**Comment by harmanbatheja15** [comment]
> Yes, they have used the keyword "Fundraiser," but it appears that the translation for that term has not been added in any language. Am I correct @harmanbatheja15 ?

Yes

**Comment by shivapranav07** [comment]
I have added the translation of that term to every language present in the p5.js Web Editor and created a pull request for it. @harmanbatheja15 @lindapaiste

**Comment by harmanbatheja15** [comment]
>  
> I have added the translation of that term to every language present in the p5.js Web Editor and created a pull request for it. @harmanbatheja15 @lindapaiste 

I think you should not add the translations using Google Translator. As we can't check if the translations are correct or not.

**Comment by shivapranav07** [comment]
Is there an alternative method to Google Translate that you could suggest? Your guidance would be beneficial to me.

> > I have added the translation of that term to every language present in the p5.js Web Editor and created a pull request for it. @harmanbatheja15 @lindapaiste
> 
> I think you should not add the translations using Google Translator. As we can't check if the translations are correct or not.

**Comment by raclim** [comment]
Thanks for raising this issue! 

We're planning to take down this text since it was meant to be a temporary promotion for the 2023 fundraiser until January 15th. Since I just reverted the fundraiser PR and the next release is going to be on January 16th, we're not going to merge in further changes to the fundraiser modal for now.

The past few PRs definitely did raise some issues with the 2023 implementation (such as mobile responsiveness and adding translations)—hopefully many of these can be addressed for 2024!
