### ISSUE TITLE
'===' vs '==' warning messages

### ISSUE THREAD

**Issue by REAS** [processing/p5.js-web-editor#287]
@lmccart mentioned a preference to not have a warning in the editor to suggest to replace "==" with "===". The current warning is "Use '===' to compare with true'

**Comment by lmccart** [comment]
this change was actually just made :) https://github.com/processing/p5.js-web-editor/issues/282

**Comment by lmccart** [comment]
ah but not deployed yet I guess, it will be in the next update!

**Comment by catarak** [comment]
I noticed that this warning is still coming up for nested objects, e.g.
```javascript
if (a.b === 5) {

}
```
shows the error, but
```javascript
if (b === 5) {

}
```
does not
