### ISSUE TITLE
mWeb: Support P5.js and Processing Foundation Content Overflow in Mobile View

### ISSUE THREAD

**Issue by krishanu7** [processing/p5.js-web-editor#2870]
### p5.js version

1.9.0

### What is your operating system?

Android

### Web browser and version

120.0.6099.144

### Actual Behavior

![BugP5](https://github.com/processing/p5.js-web-editor/assets/93394632/7f2b594a-f249-4315-9d72-34fff869c93f)
The content in the Support P5.js and Processing Foundation is going beyond the parent container.

### Expected Behavior

N/A

### Steps:
1. Open in Mobile View
2. Click on three dot Menu
3.  Click on  Support P5.js and Processing Foundation!

**Comment by krishanu7** [comment]
I would like to contribute to this. Can you please assign this to me?

**Comment by arpitghura** [comment]
Look at this comment: 
https://github.com/processing/p5.js-web-editor/pull/2761#issuecomment-1870395461

**Comment by raclim** [comment]
Going to close this since we just reverted the PR that added the banner. These changes should be up by early next week!
