### ISSUE TITLE
The t&c portion of the signup page isn't translated correctly

### ISSUE THREAD

**Issue by sourav-sm** [processing/p5.js-web-editor#2871]
### What is your operating system?

None

### Actual Behavior

It isn't being translated to bengali
![image](https://github.com/processing/p5.js-web-editor/assets/116539402/3cc2471e-6e81-4434-8180-449a8d333daf)

### Expected Behavior

It should be translated to bengali

### Steps:
1.open  [ p5.js web editor](https://editor.p5js.org/)
2.Click of "sign up" button
3.Select any language other than "English",for example  "Bengali"
4.Observe the error that mention above

**Comment by Huzaifa785** [comment]
Hey!

I solved the issue, if any updates need to be done in the PR, let me know and I'll update it ASAP.

**Comment by swrno** [comment]
Well I feel, this will cause an issue, when we will change the language, the grammar of that specific line can be wrong.
I have added the whole Bengali Translation 2 months ago by #2618, if it is an issue for all the native speakers, I would love to work on this.
@lindapaiste @raclim what do you suggest?

**Comment by sourav-sm** [comment]
Hello,
    I think the issue is the same for all native languages. If you allow me
I can work on this.
Here I have added some examples--
[image: Screenshot 2024-01-09 113800.png][image: Screenshot 2024-01-09
113821.png][image: Screenshot 2024-01-09 113841.png]
