### ISSUE TITLE
The terms and condition of the signup page isn't translated correctly

### ISSUE THREAD

**Issue by riteshwadhwani** [processing/p5.js-web-editor#2879]
### What is your operating system?

None

### Actual Behavior

It is not being translated to the Turkish
![Screenshot 2024-01-11 195807](https://github.com/processing/p5.js-web-editor/assets/119737525/1e011303-fad5-4e0f-8ef7-1e8091f78903)

### Expected Behavior

It should be like this
![Screenshot 2024-01-11 200406](https://github.com/processing/p5.js-web-editor/assets/119737525/98fd8b62-d177-4482-9173-4df8ed0fe3cb)

### Steps:
1. open ### **_p5.js web editor_**
 2.Click on **signup** button
 3.on bottom the T&C need to be change in Turkish

**Comment by chilllsaksham** [comment]
can anyone tell me how to go about the issue?

**Comment by riteshwadhwani** [comment]
If
