### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by abedin-ashraf** [processing/p5.js-web-editor#2884]
### What is your operating system?

Linux
=
### Actual Behavior

![Screenshot from 2024-01-05 19-01-34](https://github.com/processing/p5.js-website/assets/107454977/bbe39535-6da4-4601-b6fc-63e7e2315ab8)
Bengali isn't translated

### Expected Behavior

It should show বাংলা in the dropdown button as well as we select Bengali as your chosen language

### Steps to reproduce

1. Go to tanslations file
2. go locales
3. go be
4. then open translations.json file
5.  inside that file Add this {"Bengali": "বাংলা"}

**Comment by AdityaNik** [comment]
is this issue still open?

**Comment by lindapaiste** [comment]
Fixed by #2849
