### ISSUE TITLE
duplicate broken

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#289]
Just discovered in class, when I duplicate a sketch, it no longer works. Perhaps related to recent #285 fix?

Working sketch: http://alpha.editor.p5js.org/natureofcode/sketches/SkHfb91dl
Broken duplicate: http://alpha.editor.p5js.org/natureofcode/sketches/rkKmb51dg

<img width="869" alt="screen shot 2017-02-01 at 11 47 56 am" src="https://cloud.githubusercontent.com/assets/191758/22516617/517b7708-e874-11e6-9696-cc969266580e.png">

**Comment by catarak** [comment]
okay, I rolled back to 09a4829bef9bba6788c8fabd34cd76804b54bcb5 for now, until I figure out what's happening.

**Comment by kjhollen** [comment]
Thanks for posting this! I saw this yesterday in my office hours but wasn't sure what had caused it. Here's another sketch with the same issue: http://alpha.editor.p5js.org/deenie/sketches/Hki-1KAPl, in case it's helpful.

**Comment by catarak** [comment]
by the way, this has been reverted but the sketches duplicated with the first change I made are corrupted and should be deleted. sorry about the headache!

**Comment by catarak** [comment]
duplicate should be working now, let me know if there are any issues.
