### ISSUE TITLE
Upgrade storybook version to latest

### ISSUE THREAD

**Issue by mohitbalwani** [processing/p5.js-web-editor#2899]
### Increasing Access

Unsure

### Feature enhancement details

While using storybook, I came across a popup which said version 7.6.8 is available. The current version of storybook that we are using is 7.0.27. It would be good to upgrade it if that doesn't breaks anything.

**Comment by mohitbalwani** [comment]
I would like to work on this issue if project maintainers can give confirmation whether we should do it!

**Comment by lindapaiste** [comment]
> I would like to work on this issue if project maintainers can give confirmation whether we should do it!
Sure!
