### ISSUE TITLE
All sketches intermittently non-functional

### ISSUE THREAD

**Issue by gdamron** [processing/p5.js-web-editor#290]
This error started appearing in the console this morning almost every time I try to run a sketch:

![p5js error](https://cloud.githubusercontent.com/assets/715727/22521958/9c9221fc-e86e-11e6-83b9-27c7a5948449.jpg)

It affects all sketches, and prevents them from running, include one as simple as:

```js
function setup() {
  background(0);
}
```

The code I am trying to run is this:
https://gist.github.com/gdamron/3998aed348ed37beeafc0bdff42c8b53

I've noticed that if I comment out everything except for, say, setting the background color, the error will eventually clear after several tries.  But once I re-introduce more complex code, it returns.

**Comment by catarak** [comment]
hmmmm i'm not sure where that is coming from, i'll investigate. i'll try running this sketch locally and see if I can reproduce.

**Comment by gdamron** [comment]
I won't *quite* work for you without an api key or project id, but you should at least see an orange canvas and text input.

**Comment by gdamron** [comment]
It looks like creating an arbitrary JS object is what triggers it. I am able to reproduce 100% of the time with this sketch:
```javascript
function setup() { 
  var obj = {
    param: 'blahblahblah'
  };
  createCanvas(400, 400);
}

function draw() { 
  background(220);
}
```

If I run the default sketch, everything is fine. Once I've added an object, the error appears and remains even after deleting the object.

**Comment by gdamron** [comment]
Looks like this is the issue:

https://github.com/catarak/loop-protect/commit/c8bbdd3601aa871dc17adf495dfa0fa7294f63cb#diff-5790ae54650a526454580f24a5da65bfR116

trying to get the substring of an array

**Comment by catarak** [comment]
oooo awesome that you tracked it down! the infinite loop protection code was adding a bunch of lines of code and caused #283. i can revert that change and test more thoroughly.

**Comment by catarak** [comment]
okay, reverted. let me know if you are still having this issue.

**Comment by gdamron** [comment]
Success!
