### ISSUE TITLE
FEAT : Adding a Auto Save Feature just like Leetcode 

### ISSUE THREAD

**Issue by Ayush-Vish** [processing/p5.js-web-editor#2907]
### Increasing Access

![image](https://github.com/processing/p5.js-web-editor/assets/127919475/a6a7ad81-e9d9-4b1d-8d0c-b237dd7e2ff8)

It will be feature that will be either on or off.
Some User don't have the habit of saving file again n again. So this feature will be useful for those user.

### Feature request details

- I will add a flag whether it is on or off. 
- We will store the code in the local storage and When the user will run the code then only we will upload the code to the mongodb .
- If the user quits the session then also we will upload the code to mongo DB.
If you likes this Feature Please assign it to me.

**Comment by Ayush-Vish** [comment]
@lindapaiste  If you like this feature. Please assign this feature to me.

**Comment by lindapaiste** [comment]
We do have auto-save!  Check the "Settings" dialog (⚙️button).

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/c558b902-e003-4f94-978d-0da79b1ceb2b)
