### ISSUE TITLE
Implementing the feature for resending Password Reset Emails.

### ISSUE THREAD

**Issue by Keshav-0907** [processing/p5.js-web-editor#2908]
### Increasing Access

The addition of a feature to resend password reset emails in the p5.js Web Editor would contribute to increased access in the following ways: 

- Improved User Experience 
- Will reduce support requests ( Users can tackle account access issues independently )
- Increased User retention on the platform

### Feature request details

To have a `resend password reset email` features for users when they are reseting their password. We can also implement a timer, so that the request for another password reset email can be raised after a particular time after the first request is made. ( 30 sec, 60 sec )

Because their can be couple of reasons that the user may not receive the password reset email.  

<img width="1433" alt="Screenshot 2024-01-16 at 9 54 00 PM" src="https://github.com/processing/p5.js-web-editor/assets/91189139/62de97b0-c5d5-4ea9-82e9-a80dfcd0cd12">

**Comment by lindapaiste** [comment]
Sounds like your suggestion is that below the "check your spam folder" message we might add another line like "Can't find the email? Send it again." Where "send it again" is a link which would re-send a new email with the same reset password code.

> To have a `resend password reset email` features for users when they are reseting their password. We can also implement a timer, so that the request for another password reset email can be raised after a particular time after the first request is made. ( 30 sec, 60 sec )

I wonder what sort of limitations we have on this currently, if any.  Feel free to look around in the source code.
https://github.com/processing/p5.js-web-editor/blob/b28f347a61de10cd932da75fcc86887dc04f2c86/server/controllers/user.controller.js

**Comment by Keshav-0907** [comment]
We can make a new Api Endpoint `resendResetPassword`, that allows a user to request the resend of a reset password email. It checks if the user exists, has an active reset password token, and if the token is still valid.

It would require us to add 2 new properties in the userSchema : `resetPasswordToken` (for temporarily storing the Token ) & `resetPasswordExpires` ( Time after which it expires )
And If conditions are met, it will resend the reset password email to the user.

If you find it workable and in line with the project's goals, could you please consider assigning it to me? I'm open to further discussion and collaboration to implement this.

**Comment by shekharkalshetti** [comment]
can i work on this issue?

**Comment by Keshav-0907** [comment]
@lindapaiste should i start working on this issue with this approach ? 

> We can make a new Api Endpoint `resendResetPassword`, that allows a user to request the resend of a reset password email. It checks if the user exists, has an active reset password token, and if the token is still valid.
> 
> It would require us to add 2 new properties in the userSchema : `resetPasswordToken` (for temporarily storing the Token ) & `resetPasswordExpires` ( Time after which it expires ) And If conditions are met, it will resend the reset password email to the user.
> 
> If you find it workable and in line with the project's goals, could you please consider assigning it to me? I'm open to further discussion and collaboration to implement this.
