### ISSUE TITLE
Adding rounded edges to Contract/Expand Sidebar button & aligning sidebar header with editor header.

### ISSUE THREAD

**Issue by Ri-Sharma** [processing/p5.js-web-editor#2909]
### Increasing Access

This enhancement will enhance the user interface.

### Feature enhancement details

Before :- 
![image](https://github.com/processing/p5.js-web-editor/assets/80570105/3d9511e3-2076-4ffc-a68b-f8eba510d21f)

After :- 
![image](https://github.com/processing/p5.js-web-editor/assets/80570105/3931d5a7-0234-4027-9d2e-ba3cfb912980)

@lindapaiste, If this enhancement is approved, I am eager to contribute to its implementation.

**Comment by raclim** [comment]
Thanks for suggesting this! I think that to keep all the button elements throughout the whole editor consistent, it might be better to have the `border-radius` of the Sketch Files icon to match the `border-radius` of the other elements. Maybe like this? 
<br />
<img width="201" alt="Screenshot with border radius added to Sketch Files icon" src="https://github.com/processing/p5.js-web-editor/assets/43053081/7531dc7a-d0d1-4fca-9fb7-cbfc0b886fe4">
<br />
A part of myself is also wondering if it might be okay to drop the `background-color` altogether (pictured below), but this also might not be consistent with the other button elements. I think this was a part of the mobile implementation, so I'm not as familiar with its design. @lindapaiste @dewanshDT do either of you have any thoughts on this? 
<br />
<img width="205" alt="Screenshot of Sketch Files icon without grey background" src="https://github.com/processing/p5.js-web-editor/assets/43053081/41342f5d-42ae-41c4-97b8-9b210814d67c">

**Comment by raclim** [comment]
Thanks again for suggesting this! 

After thinking about it, I feel a little hesitant to introduce to many new changes to the UI and think it would be best to approach these intentionally to ensure that we have other factors buttressing these changes in hand with aesthetic. I think there's a few other issues that reference the Sidebar as well, so I'm thinking it might be better to revisit this with maybe a larger redesign or encompassing issue for it (like the About). Until then, I'm going to close this and its affiliated PR for now!
