### ISSUE TITLE
UX Detail: Title Cell should be the target for opening a Sketch.

### ISSUE THREAD

**Issue by machinic** [processing/p5.js-web-editor#292]
When going to Open a Sketch the entire cell containing the title should be the target — users shouldn't have to narrow in on just the title text itself to open the Sketch.

Design updates to this list and modal could obviate this issue.

**Comment by catarak** [comment]
This has been added and deployed, but I'm wondering if you think the rows need a hover state.

**Comment by machinic** [comment]
Absolutely we will. I'm going to bundle that up with the other design changes for this list view. Having the cell be the target felt more like a quick UX fix that would likely remain true. I imagine that implementation effort will be under a new issue number.
