### ISSUE TITLE
Password inputs should have a toggle password visibility icon

### ISSUE THREAD

**Issue by PiyushThapaa** [processing/p5.js-web-editor#2922]
### Increasing Access

It helps users to see if they entering the right password or not

### Feature enhancement details

![Screenshot 2024-01-19 094954](https://github.com/processing/p5.js-web-editor/assets/112943430/64681e31-fd51-4fa4-af6c-a88fceee8741)

In signup, login or account setting page, there are password inputs without any toggle visibility icon 
By adding it users can see if they are entering the right password or not 

@lindapaiste If you think this is a useful feature please assign this one to me...

**Comment by raclim** [comment]
Thanks for suggesting this! I think this was already raised in an earlier issue, https://github.com/processing/p5.js-web-editor/issues/2466. To help organize and consolidate issues, I'm going to close this for now. 

There's also a PR that exists for this at the moment. You can continue to work on this, but I think the existing PR is pretty far along so there might be a greater chance of that one going in. Please also feel free to check out some of the other issues in the repo!
