### ISSUE TITLE
Enhancement Request: New File Shortcut Key

### ISSUE THREAD

**Issue by Himanshi2012** [processing/p5.js-web-editor#2926]
### Increasing Access

This new feature would enhance accessibility by providing a more efficient way for users to create new files. 

### Feature enhancement details

Objective:
Introduce a keyboard shortcut (^ + N) Ctrl + N  for creating new files in the p5.js Web Editor.

Current Workflow:
Users currently rely on mouse interactions to create new files, which can be less efficient for keyboard-centric users.

Proposed Solution:
Implement a globally recognized shortcut key to initiate the creation of a new file.

Benefits:

    Efficiency: Users can quickly create new files without interrupting their workflow.
    Accessibility: Provides an alternative method for users who prefer keyboard navigation.
    User Experience: Enhances the overall user experience by streamlining the file creation process.

**Comment by raclim** [comment]
Thanks for bringing this up! This has been brought up in an earlier issue, https://github.com/processing/p5.js-web-editor/issues/1292, which has a pull request that we'll probably merge for it. I'm going to close this one for now to organize and consolidate issues.
