### ISSUE TITLE
Addition of "Copy" button to Link to collection present in my collection section

### ISSUE THREAD

**Issue by anshikkay** [processing/p5.js-web-editor#2927]
### Increasing Access

1.Enhanced Usability: The "Copy" button would simplify the task of copying link, reducing the need to manually select and copy link, which can be error-prone and time-consuming.
2.Improved Productivity: Users can save time and effort when sharing link .

### Feature request details

I propose the addition of a "Copy" button to my collection 
when share button clicked. This button will allow the users to easily copy the collection link.
steps to reach the new feature addition point
my collection->create collection->share button->Link to collection
![Screenshot 2024-01-17 000511](https://github.com/processing/p5.js-web-editor/assets/129502224/2d88daa6-5628-457e-ad26-be58df12aeb4)

**Comment by anshikkay** [comment]
hello! @lindapaiste ,I would like to work on this issue, please assign to me

**Comment by lindapaiste** [comment]
We do have it set up so that it copies to the the clipboard when you click anywhere in the text box.  You don't need to manually select the text.

I'm not opposed to having some sort of copy button or icon there, but that would need more thought in terms of how we want it to look.

**Comment by gawandeabhishek** [comment]
Hi, @lindapaiste ! I would like to work on implementing the 'Copy to Clipboard' feature for this. Could you please advise whether I should include a tooltip? The tooltip would be visible after copying, and it would display a message such as 'Copied,' similar to the way GitHub shows a message when copying a link for cloning a project.

**Comment by anshikkay** [comment]
hi, @lindapaiste, I am currently contemplating the placement of the copy button in relation to the link. I am considering either situating the copy button above the link or placing it beside the link. I would appreciate your input on this matter.
 If you have any suggestions or insights, I would be grateful for your input.


![Screenshot 2024-01-21 004045](https://github.com/processing/p5.js-web-editor/assets/129502224/a47d205b-fdb8-4e04-af56-9bd580e4761d)

**Comment by YashGupta2111** [comment]
@anshikkay is this still active?? 
can i work on this?

**Comment by rahulrana701** [comment]
@lindapaiste @raclim  do you have any plans for this issue or can you suggest what sort of changes you want or you think it is not required so please share your views on this so that I could start working on it.
