### ISSUE TITLE
Enhancement Request: Centralized Alignment of text and buttons on Account Settings

### ISSUE THREAD

**Issue by Himanshi2012** [processing/p5.js-web-editor#2929]
### Increasing Access

1.The alignment of buttons on the Account Settings page can be improved to match the centralized layout observed on other pages.
2.Ensures a cohesive and user-friendly design

### Feature enhancement details

Objective:
Achieve centralized alignment for buttons on the Account Settings page to align with the standardized layout on other pages.

Current Design:
The buttons on the Account Settings page are not centrally aligned, creating a visual inconsistency compared to other pages.

Proposed Solution:
Adjust the layout of buttons on the Account Settings page to centralize their alignment, matching the design observed on other pages.
![Screenshot from 2024-01-20 02-22-50](https://github.com/processing/p5.js-web-editor/assets/147904539/0bfc2a65-158c-430e-aaf2-1727064e7bc5)
![2](https://github.com/processing/p5.js-web-editor/assets/147904539/1b542e3b-fca3-4176-9957-039614af8946)

**Comment by Himanshi2012** [comment]
Hello @lindapaiste 
This is my first time contributing here, and I'm excited to get started. I came across this issue and would like to work on it. Could you please assign it to me? I'm looking forward to contributing to it.

**Comment by gAurav-0x07** [comment]
Hi @lindapaiste, I've made a pull request for this issue, hope you review it. Thank you.

**Comment by raclim** [comment]
Thanks for raising this issue! I think this might not be something we're looking to implement, so I'm going to close this for now. Please feel free to work on the other issues within this repository!
