### ISSUE TITLE
UI Detail: Share sketch modal border is default focus

### ISSUE THREAD

**Issue by machinic** [processing/p5.js-web-editor#293]
We may want to have a re-think about increasing the focus indication overall in the design system but other modals, palettes, etc currently have the lightly focus-styled border whereas this modal is applying the default browser focus style. 

Modal background screen also rightly contributes to focus. 

<img width="546" alt="share-sketch-modal" src="https://cloud.githubusercontent.com/assets/3985997/22649055/5f0f84aa-ec47-11e6-915b-b41d33badeea.png">

Compare with Preferences for example. 

<img width="327" alt="preferences" src="https://cloud.githubusercontent.com/assets/3985997/22649025/3a7aeae4-ec47-11e6-8e2f-bc8134edfe03.png">

**Comment by catarak** [comment]
It would definitely be good to get @MathuraMG and @cleezyitp in this conversation, as the modal focus got added for accessibility reasons. Many of the modals have a `tabindex` so that they can have focus (and therefore have a border). We added this so that if a user is only using a keyboard, and they click on one of the navigation items, then their focus goes straight to the modal, rather than having to tab through a bunch of other things first.

**Comment by machinic** [comment]
Cool. I welcome their input! I'm very much in favor of `tabindex`and showing focus. My primary aim is to have the focus indicated consistently across the experience.  

To recap, the current state things is two types of focus: the browser default focus and, for lack of a better term, the p5-style focus. Is it felt that the p5-style is insufficient as a marker of focus (it's in the preferences example posted above)? My first impulse is for me to investigate bringing the p5 focus style up in intensity, though not as much as the default focus. I think we may find a broad application of the browser default focus to be too heavy-handed if we go all-in on that. 

I know we can target the browser default focus to tone it down some. Is that an area we might consider. Essentially meeting half way? Dial up p5 and dial back the default?

Let me know what you all think. I appreciate the guidance on what the possible parameters for finding a solution are.

**Comment by MathuraMG** [comment]
I like the idea of modifying the default view to make it look more aligned with the p5 styles. I think that as long as we can surround the modal by a contrasting border, we should be fine. @cleezyitp - what do you think ?

**Comment by CleezyITP** [comment]
It took me a bit to try and understand what you are talking about. Just to be sure- are you referring to the inconsistency of p5's _visual_ styling when a modal is in focus?

I can see there is a difference between the Share Sketch and Preferences modals in terms of the visual styling while in focus- Glad to have some consistency there, as long  the accessibility isn't compromised. 

Did I get that right @machinic?

**Comment by machinic** [comment]
My apologies for any ambiguity. Indeed, I am talking about the different ways we can achieve a  consistent visual representation of the `focus` state within the overall experience because currently we are being inconsistent.

**Comment by CleezyITP** [comment]
Hey, 

Wanted to follow up on this-- I am in a wcag design talk and we are learning about color contrast accessibility. Apparently, when a page has multiple tab interfaces with inactive tabs dimmed to a level that the dimmed colors do not meet acceptable contrast ratios (4.5:1)-- the page is less accessible (fails wcag 2.0). So...if we are looking to rework the design language of the interactions on p5 and bring more consistency to it, let's consider the contrast of dimmed elements!

Happy to help when the design is worked on-- just let me know.

**Comment by catarak** [comment]
This was fixed when I did a big accessibility overhaul about a year ago ✨ I learned that for non-interactive elements, like an overlay, they shouldn't have a visible focus border like this.
