### ISSUE TITLE
About section of this repo says "p5.js Web Editor, officially launched!". Update to something more descriptive.

### ISSUE THREAD

**Issue by SableRaf** [processing/p5.js-web-editor#2938]
### Increasing Access

A more descriptive "About" section would better guide and inform users, especially those new to the project, reducing the risk of confusion.

### Feature enhancement details

I suggest updating the text to something like this from the readme:

> The p5.js Editor is a website for creating p5.js sketches, with a focus on making coding accessible and inclusive for artists, designers, educators, beginners, and anyone else! You can create, share, or remix p5.js sketches without needing to download or configure anything.

**Comment by lindapaiste** [comment]
I’m totally on board with this. Not sure about the specifics of the text, but definitely what you are suggesting is better than what we have currently.

**Comment by raclim** [comment]
Just reviewed and implemented this with @SableRaf, so I'm going to close this as completed!
