### ISSUE TITLE
The color of sketch link in sketches table should be changed to theme color when hovered

### ISSUE THREAD

**Issue by PiyushThapaa** [processing/p5.js-web-editor#2943]
### Increasing Access

Color of sketch name (link) will change to theme color on hover so that users can see that its a link...

### Feature request details

![Screenshot 2024-01-23 140650](https://github.com/processing/p5.js-web-editor/assets/112943430/1eab202e-2044-48d9-98f7-84b1d4afb4d9)
Currently there is no change in color in sketch name when hovering on it, only a pointer cursor is appearing
I will add theme color on it (when hover)
It will appear in all kinds of sketch tables 
I know how to do it please assign this one to me @lindapaiste @raclim

**Comment by Noorain464** [comment]
I would like to work on this issue
