### ISSUE TITLE
Add reset font size button

### ISSUE THREAD

**Issue by AnshuPathak-88825** [processing/p5.js-web-editor#2945]
### Increasing Access

it will reduce time to reset font to it's original size

### Feature enhancement details

Code editors often come with default font sizes, but users may have varied preferences for readability and visual comfort.
Users might manually adjust the font size to suit their needs, but finding the optimal size or reverting to the default can be cumbersome.

**Comment by lindapaiste** [comment]
I'm not sure about this because we want to avoid "button overload".  It would need to be something really discreet, if we were to do it at all.

**Comment by vaishnavi192** [comment]
@lindapaiste so what do you think which changes should we make? I would like to work on it

**Comment by raclim** [comment]
Thanks for raising this! 

I'm not really sure about this as well. I think if there were an implementation of this, it could possibly be a general reset button for all settings. Overall though, I think I'm personally leaning towards not implementing this for now.

**Comment by katiejliu** [comment]
<img width="677" alt="Screenshot 2024-04-12 at 12 47 18 PM" src="https://github.com/processing/p5.js-web-editor/assets/78124298/6f5f277e-27e3-4d5b-8dbb-789db28f4227">
Perhaps a solve is an informational text saying default text size is 18. This would avoid the button overload as well. Not sure about this placement but
