### ISSUE TITLE
Add a arrow key to toggle Sketch Files Section

### ISSUE THREAD

**Issue by rahulrana701** [processing/p5.js-web-editor#2953]
### Increasing Access

For mobile users , by applying the arrow key in sketch files section near add sign , will make much more clear to the users like this button is used to toggle this particular section , and user would be able to see the code files fully.

<img width="173" alt="Screenshot 2024-01-25 153248" src="https://github.com/processing/p5.js-web-editor/assets/123585591/3d7ff5c0-3d84-42a7-9a0c-a343cd7c6f12">

### Feature enhancement details

I will add this particular icon which will toggle this section , @lindapaiste so I would like to work on this issue , please assign it to me

**Comment by rahulrana701** [comment]
@lindapaiste done

**Comment by katiejliu** [comment]
This issue seems similarly related to this issue https://github.com/processing/p5.js-web-editor/issues/2888

In which the discussion is of improving the overall UI of this area on mobile and web @raclim

**Comment by raclim** [comment]
Thanks for pointing this out @katiejliu! I'm going to close this as a duplicate.
