### ISSUE TITLE
UI Detail: icon squish code editor

### ISSUE THREAD

**Issue by machinic** [processing/p5.js-web-editor#296]
We will detail responsive web adjustments after we address some larger design goals, but this issue could be tackled now. The shapes containing the icon do not maintain when the window is resized. They ought to continue to be circular.

E.G.
![squish-detail](https://cloud.githubusercontent.com/assets/3985997/22649388/accd7354-ec48-11e6-9fbd-8348a86cb3ea.png)

**Comment by dhruvdutt** [comment]
I'm on it. :hand:
