### ISSUE TITLE
Add transitions when user open files

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [processing/p5.js-web-editor#2963]
### Increasing Access

for mobile and Windows both users can get a smooth experience when user click the `files` button

<img width="183" alt="Screenshot 2024-01-27 115628" src="https://github.com/processing/p5.js-web-editor/assets/69814563/e5440b9f-747b-4c2a-8fe2-87ebba92ef51">

### Feature enhancement details

I want to add a transition effect on sketch files. @lindapaiste I would like to work on this. please assign it to me.

**Comment by lindapaiste** [comment]
I'm fine with this.  I think we always intended to have a slide effect there.  For the mobile we are using a `transform` on the editor div to move it over so we can add a CSS `transition` there.  I put in a really slow one as a test to see what it looks like (`transition: transform 5000ms`).  The sliding works fine for both opening and closing.  However the "sketch files" panel is blank while closing.  Not a huge deal but if we want to make it really smooth then this might be something where we could use `react-transition-group` to unmount the files list only after the slide is complete.

Ideally we would support the [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) preference of the user.  I'm not sure if `react-transition-group` has any built-in support for that?

**Comment by aniketjat03** [comment]
Hi @lindapaiste ,I am new to this Organisation and would like to contribute. Is there any community channel where I can connect to other contributors ? It would really be of great help.

**Comment by rahulrana701** [comment]
@BamaCharanChhandogi are you still working on this issue , or I should go ahead with it @lindapaiste @raclim  could you please confirm
