### ISSUE TITLE
Semantic HTML issues in header section

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2967]
### Increasing Access

Using proper semantic HTML allows screen readers to understand our content.

### Feature enhancement details

I found two issues relating to the header section while running an accessibility check:

1. We have a `<header>` element inside another `<header>` element, and multiple `<header>` elements on mobile.  We need to get this down to one.  We can change incorrect ones to either a React Fragment or a `<div>` or potentially remove them from the tree entirely.
2. We have a `<span>` as a direct child of a `<ul>` in the "login or signup" part of the nav bar.  Probably we change the `<span>or</span>` to `<li>or</li>`.  It would also be acceptable to have the entire "login or signup" as one list item, but making the "or" into its own list item is probably easier to implement.

We want to fix these HTML structures without changing the style.

**Comment by VrajRP2004** [comment]
hi sir I am hear to participate my first open source contribution so please assign me this issue.

**Comment by vaishnavi192** [comment]
@lindapaiste for issues which have PR linked with them are considered as closed right?

**Comment by asimdelvi** [comment]
Can you assign me this issue?

**Comment by Simran-Sunil** [comment]
Can I work on this issue?

**Comment by Bhavyabhardwaj** [comment]
anyone working on this issue ? if not can i work on this....?
