### ISSUE TITLE
No password confirmation when resetting a password

### ISSUE THREAD

**Issue by Keshav-0907** [processing/p5.js-web-editor#2975]
### Increasing Access

Adding a Confirm Password field when resetting password in the p5.js Web Editor will : 

- Enhances security,
- Reduces the risk of user errors,
- Decreases support requests

### Feature request details

When reseting password through User Settings, their should be a `confirm new password field` which will help in confirming the new password. 

This will ensure enhanced security and user experience by minimizing the likelihood of any mistypes in the new password by the user.

<img width="1440" alt="Screenshot 2024-01-29 at 4 02 25 AM" src="https://github.com/processing/p5.js-web-editor/assets/91189139/1a173cf8-04de-42b6-aea0-f7b9e1fc1919">

**Comment by aniketjat03** [comment]
@lindapaiste  Can you please assign this issue to me. I am thinking to solve this issue by adding a new input field for Confirm new password [here](https://github.com/processing/p5.js-web-editor/blob/develop/client/modules/User/components/AccountForm.jsx#L157-L164), and add validation in the respected backend controller to check both input passwords are same. 
thanks!

**Comment by raclim** [comment]
Hmm, I'm personally not sure if this might be needed here but I might be biased towards having less page elements in general! I'm okay with adding this if having this is a recommended best practice.  I'm wondering if adding an eye icon (https://github.com/processing/p5.js-web-editor/issues/2466) could be an alternative for addressing this as well?

**Comment by Keshav-0907** [comment]
I could not find any article/report regarding the best practice for this case, but now i also think adding a eye icon should be preferred because having a `Confirm Password Field` is also hiding the "Social Login" section on majority of the devices. 

<img width="1440" alt="Screenshot 2024-02-02 at 3 06 03 AM" src="https://github.com/processing/p5.js-web-editor/assets/91189139/b0987453-0976-4949-bf78-24ce39382bd4">

**Comment by raclim** [comment]
Closing due to reasons laid out in associated PRs!
