### ISSUE TITLE
About Page not aligned properly for mobile users.

### ISSUE THREAD

**Issue by rahulrana701** [processing/p5.js-web-editor#2976]
### p5.js version

1.9.0

### What is your operating system?

Windows

### Web browser and version

chrome://121.0.6167.85

### Actual Behavior

The about page is not aligned properly below 641px width , the spacing between them is very less which is not user friendly like this 
<img width="170" alt="Screenshot 2024-01-29 193048" src="https://github.com/processing/p5.js-web-editor/assets/123585591/575ff748-8511-4346-928b-8d6e11ac062d">

### Expected Behavior

The about should be aligned properly like this , because this is how about page was getting displayed above 641px width.
<img width="172" alt="Screenshot 2024-01-29 193004" src="https://github.com/processing/p5.js-web-editor/assets/123585591/ff780cbf-7851-4c71-9c0f-c472bcb34d0e">

### Steps:
1. Go to the project on any browser.
2. Then go to about page. 
3. Then check responsiveness of this page and below 641px width you could see the issue.

**Comment by rahulrana701** [comment]
Hi @lindapaiste I want to work on this issue.

**Comment by raclim** [comment]
Thanks for raising this! We do have an open issue regarding the entire About page, which is currently undergoing a redesign. I'm going to close PRs related to the About page for now until the redesign is ready to be implemented.
