### ISSUE TITLE
UI Detail: vertical alignment of Title text

### ISSUE THREAD

**Issue by machinic** [processing/p5.js-web-editor#298]
The baselines of all text in this row should align. Title text is `2px` too high off of it. 

![text-alignment-title-detail](https://cloud.githubusercontent.com/assets/3985997/22649564/7bb320e2-ec49-11e6-9f95-d01251317c1c.png)

**Comment by saumya1906** [comment]
I wish to work on this issue. Any pointers / guidelines?
