### ISSUE TITLE
UI Detail: color of "by" in author/account name

### ISSUE THREAD

**Issue by machinic** [processing/p5.js-web-editor#299]
We may make design updates that change the color of the author and/or the title text but `by` should be the same gray as everything else is currently (connecting words like `by` likely will not change from that gray).

![editor-author-type-detail-color](https://cloud.githubusercontent.com/assets/3985997/22649597/a2c27caa-ec49-11e6-89b6-bb6d5bbe216a.png)

**Comment by Katy310** [comment]
May I work on this issue?
