### ISSUE TITLE
Evaluate redundant redirects between client and server

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#2992]
### Increasing Access

It is confusing to work with code where redirections can be be initiated from multiple places.

### Feature enhancement details

Ref: https://github.com/processing/p5.js-web-editor/pull/2987#issuecomment-1925915203

We should look through the https://github.com/processing/p5.js-web-editor/blob/develop/client/routes.jsx file and see which redirects are not actually needed because they are already handled by the server in https://github.com/processing/p5.js-web-editor/blob/develop/server/routes/server.routes.js.

Specifically, we should check over our usages of `userIsNotAuthenticated`, `userIsAuthenticated`, `userIsAuthorized`, and `createRedirectWithUsername`.  I have a hunch that we can actually delete all four of those functions.  Let's make a list of all routes which use some form of redirection and whether each route's redirect logic duplicates what is already implemented on the server.

**Comment by lindapaiste** [comment]
Logged-out only:
- `"/login"` [client](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/client/routes.jsx#L54) and [server](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/server/routes/server.routes.js#L71-L76)
- `"/signup"` [client](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/client/routes.jsx#L55) and [server](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/server/routes/server.routes.js#L22-L27)
- `"/reset-password"` [client only](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/client/routes.jsx#L60-L63), [not on server](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/server/routes/server.routes.js#L78-L80)

Logged-in only:
- `"/account"` [client](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/client/routes.jsx#L93) and [server](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/server/routes/server.routes.js#L113-L119)

Logged-in only, redirects to URL with username:
- `"/sketches"` [client redirects](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/client/routes.jsx#L85-L88), [server only checks logged-in](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/server/routes/server.routes.js#L90-L96)
- `"/assets"` [client redirects](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/client/routes.jsx#L89-L92), [server only checks logged-in](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/server/routes/server.routes.js#L98-L104)
- (we maybe should have a similar redirect on `"/collections"`?)

Only for current user:
- `"/:username/assets"` [client](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/client/routes.jsx#L69-L72) and [server](https://github.com/processing/p5.js-web-editor/blob/91e5b79069c7d38555082b6f25bd566b8dbf74af/server/routes/server.routes.js#L106-L111) (we return a 404 for another user's assets, which might not be 100% correct)

Viewable to anyone:
- `"/"`
- `"/reset-password/:reset_password_token"` (but maybe should make this logged-out only)
- `"/verify"` (maybe should be logged-in only?)
-  `"/projects/:project_id"`
- `"/:username/full/:project_id"`
- `"/full/:project_id"`
- `"/:username/sketches/:project_id/add-to-collection"` (we only link to this URL if logged in, but there's no verification on the URL itself)
- `"/:username/sketches/:project_id"`
- `"/:username/sketches"`
- `"/:username/collections/:collection_id"`
- `"/:username/collections"`
- `"/about"`
- `"/privacy-policy"`
- `"/terms-of-use"`
- `"/code-of-conduct"`

**Comment by lindapaiste** [comment]
Proposed changes to server:
- [ ] redirect `"/sketches"` and `"/assets"` to the URL with the username
- [ ] redirect `"/reset-password"` and `"/reset-password/:reset_password_token"` to `"/account"` if the user is logged in (since the account page allows changing the password)

Proposed changes to client:
- [ ] remove all auth checks from `routes.jsx`
- [ ] delete `/utils/auth.js` file
- [ ] delete `/components/createRedirectWithUsername.jsx` file

**Comment by adadgarg** [comment]
@lindapaiste can you assign this issue to me

**Comment by Keshav-0907** [comment]
@lindapaiste can i work on this issue

**Comment by PiyushChandra17** [comment]
@raclim I would like to work on this issue. Can you please assign me this issue? Thanks!
