### ISSUE TITLE
live coding

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#3]
Two items came up in meeting with @catarak today.

1. Live coding should be a preference that can be disabled.  (Play, stop, and pause buttons?).  If live coding becomes a hassle to maintain / implement it can be saved as a feature for later.
2. It would be nice to figure out a way to not destroy and recreate the canvas as users type to eliminate the flashing.

**Comment by joancc** [comment]
Hi, I'd like to suggest using [Esprima](http://esprima.org/demo/validate.html) to validate users code syntax before reloading the preview as a way to help minimize the flashing from item 2?@toolness introduced me to this tool a while back for a similar web editor project with codemirror, and I believe he might be using it in his p5 widget too.

**Comment by catarak** [comment]
I 100% support this idea! It is definitely in the pipeline, but thanks for pointing this out.

**Comment by indefinit** [comment]
Is there a way we can let the user know they are in live coding mode when the play button is pressed?  It caught me by surprise while I was testing console output.  This is so cool, by the way!

**Comment by catarak** [comment]
The plan is to make a preference or toggle that will turn the autorun on or off for just this reason.

**Comment by shiffman** [comment]
Also, it's a subtle distinction but we discussed a bit during user testing the other day that technically this is not "live coding" as the sketch is restarting each time a change is made, rather than simply interpreting the new code as it is running.   For now, I might lean towards the "auto-run" being off by default with an option to enable, but perhaps I'm being too conservative.
