### ISSUE TITLE
Migrating the whole codebase from `javascript` to `typescript`

### ISSUE THREAD

**Issue by swrno** [processing/p5.js-web-editor#3007]
### Increasing Access

By migrating the codebase to TypeScript, we aim to increase accessibility to developers who are familiar with statically typed languages and who prefer the robust type checking provided by TypeScript. This change will facilitate a smoother onboarding process for new contributors and help improve collaboration within the open-source community.

### Feature enhancement details

On a very high level we have 3 main folders, which we can convert into typescript:

- [ ] client
- [ ] server
- [ ] webpack

**Comment by pravintargaryen** [comment]
Cool. Right Decision for the long term.

**Comment by Swarnendu0123** [comment]
Hello @raclim! @lindapaisteI think this is a great issue to work on. With the advent of Google Summer of Code (GSoC) approaching, I am reaching out to inquire about Processing Foundation's participation in this year's program. 

Can I do it as my GSoC project?

**Comment by lindapaiste** [comment]
I'm going to close this issue so that we can keep the discussion in one place in #3004
