### ISSUE TITLE
Better handling when renaming files

### ISSUE THREAD

**Issue by Keshav-0907** [processing/p5.js-web-editor#3014]
### p5.js version

 v2.11.0

### What is your operating system?

Mac OS

### Web browser and version

Brave v1.61.109

### Actual Behavior

When renaming a file from the side-bar, the blinking text cursor is placed at the end. But in general cases only the file name is to be changed not the extension ( `.js` , `.html`, `.png`, etc). 

Currently we have to explicitly, move the cursor back from the end. 

https://github.com/processing/p5.js-web-editor/assets/91189139/344d55b4-24f2-4612-89a0-b40876225bf1

### Expected Behavior

To solve this issue, when renaming we can auto-place the blinking text cursor at the end of the filename, excluding the extension

In addition, we can also have a confirmation when the user tries to change the extension for a file

### Steps:
1. Visit https://editor.p5js.org/ 
2. Try Renaming a file form the sidebar

**Comment by lindapaiste** [comment]
> In addition, we can also have a confirmation when the user tries to change the extension for a file

We actually don't allow this it all, but it's not explained to the user.  It will keep the previous file name.  So there is definitely room for improvement there!  I would be fine with allowing them to change the extension with a confirmation.

**Comment by rahulrana701** [comment]
@lindapaiste I would like to work on this issue because I think I can solve it , so could you please assign it to me

**Comment by Keshav-0907** [comment]
@rahulrana701 I am already working on this

**Comment by rahulrana701** [comment]
@Keshav-0907 ok
