### ISSUE TITLE
Unable to load assets/mySong.m4a. The request status was: 404 (Not Found) The error stack trace includes: loadSound at setup (about:srcdoc:103:9)

### ISSUE THREAD

**Issue by corbinyo** [processing/p5.js-web-editor#302]
Can't load audio anymore.

**Comment by catarak** [comment]
maybe this has to do with the .m4a extension? i just tested some .mp3/.wav files and it seems to be working okay.

**Comment by corbinyo** [comment]
I forgot to reply to this with an update! Yes mp3’s are working!

Thank you for response. Should m4a’s work?

Thanks :) 
Corbin

**Comment by catarak** [comment]
it should but it does not 😸

**Comment by catarak** [comment]
woohoo fixed and deployed 😄

**Comment by corbinyo** [comment]
Time to convert my vinyls! 🤠
