### ISSUE TITLE
Missing ending quotation mark to "Added to [collection]" toast

### ISSUE THREAD

**Issue by pie999** [processing/p5.js-web-editor#3021]
### p5.js version

v1.9.0

### What is your operating system?

Windows

### Web browser and version

Firefox 122.0.1

### Actual Behavior

The ending quotation mark is missing from the "Added to [collection]" toast.
https://github.com/processing/p5.js-web-editor/blob/6cac275429c3911d87afdcdbbdbf185092aeac29/client/modules/IDE/actions/collections.js#L83

### Expected Behavior

There should be a quotation mark after `${collectionName}`.

### Steps to reproduce

Add a sketch to a collection.

**Comment by aditya3011ai** [comment]
Hi @pie999 , I would like to work on this Bug could you please assign it to me.

**Comment by lindapaiste** [comment]
This is definitely a mistake.  But also, we really should migrate all three of those texts to our translation system.  They are not getting translated at all right now.

https://github.com/processing/p5.js-web-editor/blob/6cac275429c3911d87afdcdbbdbf185092aeac29/client/modules/IDE/actions/collections.js#L50
https://github.com/processing/p5.js-web-editor/blob/6cac275429c3911d87afdcdbbdbf185092aeac29/client/modules/IDE/actions/collections.js#L83
https://github.com/processing/p5.js-web-editor/blob/6cac275429c3911d87afdcdbbdbf185092aeac29/client/modules/IDE/actions/collections.js#L113
