### ISSUE TITLE
`SearchBox` styling issue

### ISSUE THREAD

**Issue by swrno** [processing/p5.js-web-editor#3030]
### Actual Behavior

![Screenshot (80)](https://github.com/processing/p5.js-web-editor/assets/94161758/3c1cda52-8f38-4857-a4ba-6728b01b02ed)

### Expected Behavior

![Screenshot (79)](https://github.com/processing/p5.js-web-editor/assets/94161758/ac4ab912-f7c9-46f0-9476-5833aa92836f)

### Steps:
1. Go to p5.je-web-editor
2. Press `Ctrl`+`F`
3. A search box will pop up, tap on the arrow on the left

**Comment by lindapaiste** [comment]
I think the expected behavior is that the two boxes fit on the same line.  We messed this up when adding some changes to support the responsive design.  I can look back in the git history and get a snapshot of the earlier version.  Pretty sure there is another open issue about this already.

**Comment by swrno** [comment]
Hmm, I thought the arrow on click pointing towards the bottom, so the replacement input will also appear to the bottom side.
>Pretty sure there is another open issue about this already.

Maybe we can merge them into a single issue.

**Comment by VivekJaiswal18** [comment]
Can I work on this issue?

**Comment by lindapaiste** [comment]
This is what it previously looked like.  The top line stays the same and additional content shows up below.
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/17b5c2ca-0519-43ae-98aa-8317784a179a)
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/60883856-db40-4723-a117-9f4bacafff38)

Also...omg I thought we fixed this but this is the production site 😱 
![image](https://github.com/processing/p5.js-web-editor/assets/28965286/b9fd14f8-882a-43b3-8cdc-30037b7617d5)

**Comment by lindapaiste** [comment]
I have a CSS that fixes it.  Whoever gets to it first can put this in a PR.  It falls apart below around 350px but that's really small so I think we call this good enough for now and revisit the small-screen issues later.

In `.CodeMirror-dialog`
change lines:
```
margin-left: #{math.div(-552 * 0.5, $base-font-size)}rem;
```
```
z-index: 10;
```

Then replace these two blocks:
```
.CodeMirror-find-controls {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: #{math.div(35, $base-font-size)}rem;
}
```
```
.CodeMirror-search-controls {
  width: 60%;
  display: flex;
  flex-wrap: wrap-reverse;
  justify-content: flex-start;
  align-items: flex-end;
}
```

**Comment by PiyushThapaa** [comment]
`margin-left: #{math.div(-552 * 0.5, $base-font-size)}rem;` 
@lindapaiste  This code is giving a sass error
![Screenshot 2024-02-19 171921](https://github.com/processing/p5.js-web-editor/assets/112943430/7e5eb9ec-7a2f-4fbb-97a5-854f54fca789)

**Comment by parikshitgupta3** [comment]
@lindapaiste the code that you provided is working for me
<img width="1710" alt="Screenshot 2024-02-20 at 2 24 08 AM" src="https://github.com/processing/p5.js-web-editor/assets/72187548/5478ab7d-0e19-4bb5-815a-69a83aca2b4c">
I raised the PR also
