### ISSUE TITLE
Adding a search bar in the `File Explorer`

### ISSUE THREAD

**Issue by swrno** [processing/p5.js-web-editor#3031]
### Increasing Access

Adding a `Search Box` in the file explorer can potentially help creators, who are working with big projects, it helps them to locate a file very easily.

### Feature request details

Currently, we don't have any search bar in the `file explorer`, We can add one Search Box which will potentially be very helpful, if anyone is working with a lots of files.

**Comment by Ri-Sharma** [comment]
This will a great addition. If possible I would to work on this @lindapaiste, @raclim.

**Comment by rahulrana701** [comment]
@lindapaiste @Ri-Sharma   It is a duplicate issue , this issue has already been opened by someone.

**Comment by swrno** [comment]
I guess #2496, is the same issue. We can continue our discussions on #2496. Let me just close this issue.
