### ISSUE TITLE
Issue with negative values in SASS with `math.div`

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#3038]
We recently updated our SASS package and migrated the code to use `math.div` instead of the deprecated slash `/` operator for division.  In the process we messed up one line dealing with the position of the search modal.

It previously was this:
```
margin-left: -#{552/2 / $base-font-size}rem;
```
https://github.com/processing/p5.js-web-editor/blob/2a8d3e2d260171ef6515745c1ffee9b522d56865/client/styles/components/_editor.scss#L92

I suggested a fix but it might not be right?  I'm unsure if the minus sign `-` should be inside or outside of the statement.  Also unsure if it's ok to do multiplication like `-552 * 0.5`.  We would love if someone who is good at SASS can fix this!

>              `margin-left: #{math.div(-552 * 0.5, $base-font-size)}rem;` 
> @lindapaiste  This code is giving a sass error
> ![Screenshot 2024-02-19 171921](https://github.com/processing/p5.js-web-editor/assets/112943430/7e5eb9ec-7a2f-4fbb-97a5-854f54fca789)
> 
> _Originally posted by @PiyushThapaa in https://github.com/processing/p5.js-web-editor/issues/3030#issuecomment-1952286140_

**Comment by swrno** [comment]
I am really good at math. Maybe we can play with mathematics, Maybe we can use:

```sass
margin-left: #{math.div(-552 * 0.5, $base-font-size)}rem;
```
 Or 
```sass
margin-left: #{math.div(552 * 0.5, $base-font-size)*(-1)}rem;
```
Or
```sass
margin-left: #{552 * 0.5 * math.div(1, $base-font-size) * (-1)}rem;
```
The sass couldn't recognise `-#` as any operator, so it is throwing errors.

**Comment by lindapaiste** [comment]
@Swarnendu0123 are all of those syntactically correct?  I wonder why @PiyushThapaa was having issues.  I thought it had been working for me 🤷

**Comment by lindapaiste** [comment]
You're also giving me a 💡 moment that since division is the only operation which is a pain, maybe instead of dividing by `$base-font-size` all the time we multiply by its inverse and call it `$px-to-rem`.  Though we can also define an `@function pxToRem($px)` which is probably better.

https://sass-lang.com/documentation/operators/numeric/
https://sass-lang.com/documentation/breaking-changes/slash-div/
https://sass-lang.com/documentation/at-rules/function/

**Comment by swrno** [comment]
> @Swarnendu0123 are all of those syntactically correct?  I wonder why @PiyushThapaa was having issues.  I thought it had been working for me 🤷 

I haven't tested but I am almost sure, all of them should work.

**Comment by swrno** [comment]
> You're also giving me a 💡 moment that since division is the only operation which is a pain, maybe instead of dividing by `$base-font-size` all the time we multiply by its inverse and call it `$px-to-rem`.  Though we can also define an `@function pxToRem($px)` which is probably better.

I was also thinking about it, because dividing by some number is equivalent to multiplying with its reciprocal.

**Comment by swrno** [comment]
Accha, @lindapaiste anyone is raising any PR, can we automate something from the GitHub workflow which will deploy the changes with PR, probably then your task would be very easy for checking any type of PR.
I personally faced this now, when the PR was there, I couldn't see the changes live.

Like this, in my one project, I have automated the vercel bot: https://github.com/Swarnendu0123/http-request-inspector/pull/19#issuecomment-1949751173

**Comment by PiyushThapaa** [comment]
@Swarnendu0123 @lindapaiste Still getting the same issue I don't know what's wrong 

Here's the code that I changed

![Screenshot 2024-02-20 181801](https://github.com/processing/p5.js-web-editor/assets/112943430/516fdbf3-2bfd-48e9-8561-ebac7bbece7d)

![Screenshot 2024-02-20 181836](https://github.com/processing/p5.js-web-editor/assets/112943430/cfa1c4b0-317a-41d6-9505-6a44a068c049)

**Comment by swrno** [comment]
I think, It might be for some setup error, if you are using docker, just rebuild the container, most probably it should fix the error.

**Comment by PiyushThapaa** [comment]
yeah now its working thanks 👍
