### ISSUE TITLE
Logged out error modal pops up when downloading another user's sketch

### ISSUE THREAD

**Issue by lindapaiste** [processing/p5.js-web-editor#3053]
### What is your operating system?

None

### Actual Behavior

![image](https://github.com/processing/p5.js-web-editor/assets/28965286/038596b4-6a64-47e2-9733-b761121eba17)

### Expected Behavior

I should be able to download p5's sketch without any error.

The sketch actually does export successfully, using the saved version of the project.

We are getting this message because we make a PUT request to the API before exporting a sketch.  That API request will fail if the user is not the owner of the sketch.  The easiest solution would be to only make that API call if there is a logged in user and that user is the owner of the sketch.

The relevant code is here:
https://github.com/processing/p5.js-web-editor/blob/64c36cae65541783e848eb5c0e11eb255ec6c940/client/modules/IDE/hooks/useSketchActions.js#L42-L45

There is some nuance here with regards to how we would handle local/unsaved changes.  Right now those changes would not be applied if it is not your sketch.  This is part of a larger discussion happening in #2904.

### Steps:
1. Make sure that you are logged out
2. Go to a sketch which is not your own, such as https://editor.p5js.org/p5/sketches/Data:_True_and_False
3. Click the "File" menu
4. Click "Download"

**Comment by vivekbopaliya** [comment]
I haven't looked into the issue yet but why are we calling `autoSaveProject` before downloading? It doesn't seem necessary to save someone's project before downloading it i think so. Removing that step should fix it.
