### ISSUE TITLE
Can't download the programs

### ISSUE THREAD

**Issue by nrbt9** [processing/p5.js-web-editor#3055]
### p5.js version

Actuell p5js Editor

### What is your operating system?

Mac OS

### Web browser and version

brave, firefox

### Actual Behavior

i can't download the programs. i get the message "the website is not available".
It has also happened that the browser displays an empty JSON file. the two phenomena alternate.

### Expected Behavior

is obvious?

### Steps:
1. File -> Open -> Download

**Comment by rj-Anurag** [comment]
@nrbt9 Its working fine now check it out

**Comment by raclim** [comment]
Thanks, I'm going to close this for now!
