### ISSUE TITLE
Enable `.mtl` File Uploads

### ISSUE THREAD

**Issue by SableRaf** [processing/p5.js-web-editor#3067]
### Increasing Access

Allowing `.mtl` file uploads in the p5.js Web Editor would ensure feature consistency between the editor and p5.js itself, reducing potential confusion for users.

### Feature enhancement details

The p5.js Web Editor currently blocks the upload of `.mtl` files with a "you can't upload files of this type" error, despite `.mtl` file support being available in p5.js since version 1.9.2 (see processing/p5.js#6710). This discrepancy limits users' ability to fully utilize p5.js's 3D capabilities within the Web Editor.

![image](https://github.com/processing/p5.js-web-editor/assets/290261/8678c3ca-948a-4eca-8a81-4bf0c952bb8a)

**Comment by lindapaiste** [comment]
It needs to be added here and I think that's it? https://github.com/processing/p5.js-web-editor/blob/c4de2669ad4df5b0e99927a4dff8c7394d8f0744/server/utils/fileUtils.js
