### ISSUE TITLE
Editor is a focus trap

### ISSUE THREAD

**Issue by sampottinger** [processing/p5.js-web-editor#3085]
### p5.js version

N/A (Online Editor)

### What is your operating system?

Linux

### Web browser and version

Firefox 142

### Actual Behavior

Entering the editor is possible with the keyboard but it isn't possible to leave it using the escape key. This is a "focus trap" which is covered in [WCAG 2.1.2](https://www.w3.org/WAI/WCAG21/Understanding/no-keyboard-trap.html).

### Expected Behavior

This may be a possible hint for fixing in a recent change in ACE editor behavior which is resolved recently in https://github.com/ajaxorg/ace/pull/5114

### Steps:
1. Open the p5.js web editor
2. Give the code editor focus
3. Try to leave the code editor

**Comment by sampottinger** [comment]
See https://codeberg.org/sketchingpy/Sketchingpy/pulls/65/files for example of recent fix we saw on https://sketchingpy.org

**Comment by raclim** [comment]
Thanks for raising this and suggesting a potential fix!
