### ISSUE TITLE
Unexplained TypeError

### ISSUE THREAD

**Issue by FriddoDK** [processing/p5.js-web-editor#309]
While entering this program:

function setup() { 
  createCanvas(800, 400);
	
  
  i = 0;
  while(i <= 11) {
  	triangle(200,300,600,300,i * 40 + 1200/11,100);
    i++;
  }
} 

i get a very strange error:

Uncaught TypeError: Cannot read property 'children' of undefined (sketch: line 47)

It seems quite unrelated to my program, maybe some code analysis problem?

to reproduce, copy the code

thanks

**Comment by catarak** [comment]
weird! will investigate.

**Comment by catarak** [comment]
hmmm, i'm not able to reproduce. can you add a link to your sketch to this ticket?

**Comment by FriddoDK** [comment]
Sure I'll send link soon

**Comment by JimishF** [comment]
Code works fine in editor without errors.
![image](https://cloud.githubusercontent.com/assets/8057628/23991847/c50721fa-0a60-11e7-8083-a1071f7f27f9.png)

**Comment by catarak** [comment]
Since I haven't been able to reproduce this issue I'm going to close it. If it pops up again, feel free to reopen it or open a new issue.
