### ISSUE TITLE
Outages within the p5.js Editor

### ISSUE THREAD

**Issue by raclim** [processing/p5.js-web-editor#3096]
Currently, the p5.js editor is experiencing some outages since earlier this week. We're currently investigating this issue and will provide updates as progress towards a resolution is being made. Incident reports for the editor can also be tracked on the [status page for Processing Foundation software](https://processing.statuspage.io/). 

Thanks so much for your patience and understanding as we work to resolve this issue!

**Comment by SableRaf** [comment]
Hey @raclim, just a heads up, the link for the status page is: https://processing.statuspage.io/

**Comment by raclim** [comment]
Oh no 😅 I didn't realize I put the wrong link! Thanks for catching that @SableRaf!

**Comment by SableRaf** [comment]
No problem! I edited your original comment to update the link.

**Comment by limzykenneth** [comment]
Just in case you haven't catch this, it seems like signing in with username and password is not currently working (server always return 401 incorrect username and password).

**Comment by raclim** [comment]
Oh no thank you so much @limzykenneth for catching and sharing this!! I didn't realize I missed such a big issue in last night's release. I just rolled it back, so I think signing in with username/password should work again!

**Comment by TiborUdvari** [comment]
Hello, I don't know if this is related, but I'm getting 500 errors when trying to delete sketches. I think this showed up a few days ago so I guess it might be related.

**Comment by raclim** [comment]
@TiborUdvari Thank you so much for reporting this! I think this is definitely related and might've been caused by one of my attempts at releasing a solution to some of the issues causing the outages. 

I'm sorry that you've been experiencing this for a few days, it must've been really frustrating 😅 I'll continue to keep this post updated, and hopefully we'll try to have this issue fully resolved by the middle of this week! Thanks so much again!

**Comment by rruubboott** [comment]
HI all
Just to log here - at about 16.45 or so GMT the editor went down again - similar problems to last Tuesday (500 error, can't save, can't run sketches)

**Comment by raclim** [comment]
Thank you @rruubboott!

**Comment by raclim** [comment]
Just to provide an update, we narrowed down the larger cause for this from two issues that occur when a user logins to their account, and when a project is retrieving or deleting assets. Thank you again for your patience and please let us know if you encounter any other issues that might be related to this!

**Comment by TiborUdvari** [comment]
Deletes work fine now! Thank you!

Although I see that public API requests don't seem to work anymore on my side, I don't know if it is related to the fix: https://github.com/processing/p5.js-web-editor/issues/3109
