### ISSUE TITLE
Add git hook for deployment

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#310]
I'd like to change the workflow for this project to be that all pull requests are to the branch `development` rather than `master`, and then when `development` is merged with `master`, there's a git hook to rebuild the application. 

I'd also like to rebuild the application if any of the submodules have new commits to their respective master branches. Currently there is only one submodule.

**Comment by catarak** [comment]
this is almost done. i'll need to take down the editor for a moment to finish setting this up, which I will do at the wee hours of the night 😄

**Comment by shiffman** [comment]
I'm doing some testing related to fixes recently merged. Question related to this issue. . .

If something is committed to master should I assume it is deployed to production or no?

 (@catarak apologies if you've told me this before!)

**Comment by catarak** [comment]
this is a good question! one option would be to have two branches, `master` and `development`, and all pull requests should be made to development, and we have a staging server that automatically builds when something is pushed to `development`, and the production server that automatically builds when something is pushed to `master`. 

i'm thinking that maybe it would make sense to do some Docker/Travis CI/other configuration to make this happen since setting up git hooks can be a little annoying.

**Comment by shiffman** [comment]
Having a continuous integration system would be awesome! I recently did a bunch of stuff with CircleCI (have a connection there) but Travis might be more "free". I'm happy to do any research / work on setting this up if that would be helpful.

**Comment by catarak** [comment]
awesome, will let you know, thanks!

**Comment by dhruvdutt** [comment]
@shiffman @catarak I have some experience working with CIs. Please let me know if there's something I can help with. :hand:
