### ISSUE TITLE
bug: The t&c line of signup page for japanese language is still in english.

### ISSUE THREAD

**Issue by nishikant23** [processing/p5.js-web-editor#3102]
### p5.js version

2.19.9

### What is your operating system?

Windows

### Web browser and version

chrome/brave

### Actual Behavior

It is not translating to japanese.

![p5js_jap_wo_jap_warning](https://github.com/processing/p5.js-web-editor/assets/119045534/bd2db37f-bac9-4f6d-a366-86bea41fc5ce)

### Expected Behavior

It should be translated to japanese.,like below img.

![p5js_jap_warning](https://github.com/processing/p5.js-web-editor/assets/119045534/1693697f-e1c2-42e5-a529-8c4fb6137ed3)

I have translated to cloned repo of this, also get confirmed with my japanese friend the provided japanes-translation is in correct grammar usage.

### Steps to reproduce

**Steps to find error:**

1.open [p5.js web editor](https://editor.p5js.org/)
2.Click of "sign up" button
3.Select any language other than "English",for example "Japanese"
4.Observe the error that mention above

**Comment by raclim** [comment]
Thanks for sharing this! Could you also add a text version of the Japanese translation into your description, so the translation can be read outside of the image as well?

**Comment by nishikant23** [comment]
Sorry, but, text version of translation, I didn't got your point here,
Can you please come explain me detail, I am not getting it

**Comment by nishikant23** [comment]
![image](https://github.com/processing/p5.js-web-editor/assets/119045534/52b41d62-a40d-4ce1-b45c-fce106d27795)

I am getting while pushing to p5js-web-editor cosde base 
Please refer attached image for reference.

Thank you

**Comment by Shrijan125** [comment]
@raclim I would like to work on this issue. Can you assign me?

**Comment by nishikant23** [comment]
@raclim please check my open PR to merge, thanks.
