### ISSUE TITLE
Can't not delete any of my sketches

### ISSUE THREAD

**Issue by pmcallihan** [processing/p5.js-web-editor#3104]
About 3 days go I felt that I had too much junk in my account and tried to pare it back to just the ones I wanted to keep.  The delete on the editor 'open' page ask me if I was sure.  Toggle yes and the delete popup accept my choice.  It did not delete the sketch.  The editor has been sluggish and not working in some instances.  I suspect that I've screwed my account somehow.
I really like using p5js editor to my other choices, "open processing, visual studio, code pen and processing. Please help if you can.  
Thank you PhilC
callihan@yahoo.com

**Comment by raclim** [comment]
Hi @pmcallihan, thank you so much for reporting this issue! 

This seems to be tied to a series of recent issues with outages in the editor, which is detailed in this thread: #3096. There are several issues contributing to these outages, which we're currently trying to resolve at the moment. The particular issue with deleting sketches seems to have been tied to one of the recent fixes we released, which should be resolved within the next day or two. I'm sorry that this is happening at the moment, and thank you so much for your patience and understanding as we work through this! Please feel free to continue reporting any other issues you're experiencing to help us achieve a complete resolution more quickly!

**Comment by Alilymae** [comment]
I've been having the same issue as well, no matter how many times I try my sketches in p5js editor just won't delete. My editors getting crowded as I use it for creating artwork in uni. hope this issue is fixed soon.

**Comment by raclim** [comment]
Thank you for sharing @Alilymae! I'm sorry that you've been experiencing this too—we're working to have a fix up as soon as possible!

**Comment by raclim** [comment]
I think this should now be addressed with the latest release and pull request (https://github.com/processing/p5.js-web-editor/pull/3107)!! I'm going to close this for now, but please let me know if you're still experiencing issues with this! Thank you so much again for your patience with this!!!
