### ISSUE TITLE
UI detail : icon confusion

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#312]
I think the icons to to open a drop-down menu and the icons to open the console and project-folder are too similar. The drop-down icons could be a solid triangle like it is in the Processing UI, and all be the same size.  
Also, the icon for the project folder should stay on the right of the project div, the same way it stays at the top of the console. I'm attaching a jpeg to show the proposed changes. 
![p5ui](https://cloud.githubusercontent.com/assets/6563969/23314995/2a2872ca-fa92-11e6-95f7-f8a413793969.jpg)

**Comment by joemckay5** [comment]
Hmm, maybe those triangles look too much like the mac OS arrows that turn and open folders. Maybe if they weren't solid?

**Comment by joemckay5** [comment]
How about little circles like Blender does it? 
![p5ui2](https://cloud.githubusercontent.com/assets/6563969/23315519/844c3226-fa94-11e6-9641-6ddb51d52550.jpg)
?

**Comment by catarak** [comment]
My design inspo for using the down arrows was https://gomix.com. I think it would make more sense to change the sidebar/console open and close icons rather than the options dropdown icons. Maybe @machinic has an opinion?

**Comment by joemckay5** [comment]
That could work - as long as they are differentiated a bit more. 
I like the gomix interface (and gomix itself looks cool), but until I click on the icon I would assume that the arrow means, "open files within this folder", not "open an options menu". Once you do click on it it's clear, but until then it could be misleading for some.

**Comment by machinic** [comment]
I agree there's some confusion now and I'll be doing some clean up around that area as there's some additional actions that we take on folders (via the dropdown menu) that weren't fully baked in the original design. I agree that perhaps the solution lies in some of the moves made around the UI elsewhere e.g. sidebar and console (as well as the add action, for that I may try to revive the OG design add File UI a more designed version of `[+]` ).
