### ISSUE TITLE
Make the newly header bar hideable

### ISSUE THREAD

**Issue by arthurcloche** [processing/p5.js-web-editor#3126]
### Increasing Access

I would love to be able to close the header bar, as it is a common practice on many websites.
I understand the purpose of it but it's really distracting and creates a focus point on my screen where i would like to be able to focus on my code and visual. 

### Feature enhancement details

Add a closing button on the header bar or add that feature inside of the account settings if we want to enforce registering first to get access that.  

![Screenshot 2024-05-16 at 4 55 44 PM](https://github.com/processing/p5.js-web-editor/assets/38710749/367cabe2-687e-4332-b8ae-9f6f59368f73)

**Comment by raclim** [comment]
Thanks for reporting this! That makes sense, we'll try to see if we can have something up for this within the next week!

**Comment by Aseem22** [comment]
@raclim I would like to work on this issue. Can you assign me?

**Comment by raclim** [comment]
Sure @Aseem22, assigned!

**Comment by raclim** [comment]
This is currently deployed on the editor now. This banner will be taken down altogether by next Friday, so hopefully it won't be too distracting until then. Thanks again @Aseem22 for working on this and @arthurcloche for raising this issue!

**Comment by Aseem22** [comment]
Thanks @raclim !!
