### ISSUE TITLE
assign a custom  icon to a file type 

### ISSUE THREAD

**Issue by RAHULDAS6009** [processing/p5.js-web-editor#3136]
### Assigning custom icons to file types in a p5js web editor enhances the user experience by making it easier to visually distinguish between different types of 
![Screenshot 2024-05-26 210300](https://github.com/processing/p5.js-web-editor/assets/121535378/d94b05fa-4a32-4022-ae88-3e1daf22b39b)
files

### If the extension of file is .js it will be js icon,similarly for .css  css icon and for html it will be html  icon
![Screenshot 2024-05-26 212108](https://github.com/processing/p5.js-web-editor/assets/121535378/35c4941c-bf10-49d9-b339-0a188abfd011)

**Comment by Rayan9064** [comment]
Can you assign this issue to me as I can solve this by identifying the extension of the file and displaying the icon accordingly.

**Comment by RAHULDAS6009** [comment]
Sorry,@Rayan9064  I am working on this

**Comment by raclim** [comment]
Thanks for opening this! We do actually have a [pending issue](https://github.com/processing/p5.js-web-editor/issues/2542) and [PR](https://github.com/processing/p5.js-web-editor/pull/2550) for this that we're planning on merging at the moment, so I'm going to close this issue and associated PR. I'm sorry that we're not able to get this in, but please feel free to check out the other open issues, thanks!
