### ISSUE TITLE
Glitches in `banner` when dragging the `console` 

### ISSUE THREAD

**Issue by PiyushChandra17** [processing/p5.js-web-editor#3137]
### p5.js version

2.12.13

### What is your operating system?

Mac OS

### Web browser and version

Chrome and 117.0.5938.132

### Actual Behavior

Glitches in `banner` when dragging the `console` 

https://github.com/processing/p5.js-web-editor/assets/47579287/0fe36142-aa7e-47f9-aeae-8a391174b420

### Expected Behavior

There shouldn't any Glitches in `banner` when dragging the `console` 

### Steps:
1. Open the editor web app
2. Drag the console upwards or downwards
3. Observe the glitches in banner

**Comment by raclim** [comment]
Thanks for raising this issue! This is a temporary banner that we're planning to remove today, which should resolve this!
