### ISSUE TITLE
Mobile version file name layout is broken

### ISSUE THREAD

**Issue by shujuuu** [processing/p5.js-web-editor#3157]
### What is your operating system?
iOS

### Web browser and version
Chrome 125.0.6422.80 (Official Build) stable (64-bit)

| Actual Behavior | Expected Behavior |
|--------|--------|
| Sketch name and folder should be on the same row. | (See previous screenshot) |
| <img width="361" src="https://github.com/processing/p5.js-web-editor/assets/43021463/a39e251f-c06d-4f91-b0f2-f3dac4f188c3"> | <img width="361" alt="Screenshot 2024-06-13 at 5 01 05 PM" src="https://github.com/processing/p5.js-web-editor/assets/43021463/03d16226-3454-485e-8acf-b942f010e161"> | 

### Steps to reproduce
- Open p5js editor from your phone's browser or..
- Open from desktop browser then resize window to the smallest resolution

**Comment by PiyushChandra17** [comment]
@shujuuu Indeed it's broken, I would like to work on this one since i have pretty decent experience working in `mobile platforms`

**Comment by shujuuu** [comment]
Hey @PiyushChandra17, sorry just saw your comment. I thought it was pretty straightforward so I jumped into fixing it right after opening the issue. I should have probably waited for @raclim or @lindapaiste to assign it to us.

**Comment by raclim** [comment]
@shujuuu Since you first raised the issue, I think it's cool if you create the PR for it as well! We do still have a few other [mobile issues](https://github.com/processing/p5.js-web-editor/issues?q=is%3Aopen+is%3Aissue+label%3A%22Area%3A+Mobile%22) that could be checked out as well!

**Comment by shujuuu** [comment]
Will check them out! Thanks @raclim! 😊
