### ISSUE TITLE
Signup & login pages are cropped on both side

### ISSUE THREAD

**Issue by shujuuu** [processing/p5.js-web-editor#3158]
### What is your operating system?
iOS

### Web browser and version
Chrome 125.0.6422.80

### Actual Behavior

Input fields are being cropped on both sides
| Login page | Signup page |
|--------|--------|
| <img width="320" src="https://github.com/processing/p5.js-web-editor/assets/43021463/90537fab-f4ee-466c-8fb5-a54c5e8b548a"> | <img width="320" src="https://github.com/processing/p5.js-web-editor/assets/43021463/c4291bb0-9385-4ae7-af4d-7736ccedfae7">|

### Expected Behavior
<img width="360" alt="login" src="https://github.com/processing/p5.js-web-editor/assets/43021463/8886ab8e-33a6-4fb6-95f3-ad5d304ef222">

### Steps to reproduce
Go to signup or login page from mobile phone

**Comment by DevItaliya22** [comment]
Working on it

**Comment by mBasak03** [comment]
Can you please assign me the issue or should I start by myself?

**Comment by YashSachdeva** [comment]
Hi @shujuuu , can I know if the issue is solved?

**Comment by shujuuu** [comment]
@mBasak03 @YashSachdeva I tried to fix this, let's see if it gets approved. If not, maybe ask the maintainers to assign one of you.
