### ISSUE TITLE
Add @media print CSS statements to be able to get usefull pdf formatting

### ISSUE THREAD

**Issue by valueerrorx** [processing/p5.js-web-editor#3166]
In order to document the work of my students it sometimes makes sense to use the webbrowsers print to pdf feature

unfortunately the cookie banner is always visible, the code is cut off and the rest doesn't fit either.
adding some css statements would help a lot

@media print {  //this controls how the  view is printed (to pdf)
    #cookiebanner  {
        display: none !important;
    }
}

thank you!

**Comment by Qianqianye** [comment]
Hi @valueerrorx, could you provide more context on the use case you are asking for? Screenshots will be helpful.
Just to confirm, is this issue related a p5.js website (https://p5js.org) or p5.js website editor (https://editor.p5js.org)?

**Comment by valueerrorx** [comment]
![Screenshot_20240611_082455](https://github.com/processing/p5.js-website/assets/7266848/cf03eb50-2dae-4f9d-b055-2eed34e991e8)

talking about the editor.  it would be really nice if the @media print would change the css in a way that the code and the result are shown.

**Comment by Chaitanya1672** [comment]
Hi @Qianqianye @raclim 
Could you please clarify the expectations for this issue? Specifically, when utilizing landscape orientation in a PDF printout, all the code becomes visible.
![image](https://github.com/processing/p5.js-web-editor/assets/100834122/1fca323f-46a9-4cde-a988-4db3020e2656)

**Comment by valueerrorx** [comment]
ok thank you... landscape is a little bit better. but because the code element is integrated in the sourrounding page it will be clipped.

if the editor component is set fit content and the sourrounding divs are set to overflow-y visible the whole code would be printed.  the cookie bannner (and the console) need to be set to display:none



![Screenshot_20240616_122649](https://github.com/processing/p5.js-web-editor/assets/7266848/0754288a-690d-4173-bb6a-4ff16377674f)

**Comment by Chaitanya1672** [comment]
ok @valueerrorx, I also think it is a good idea to include only the code and its solution in the PDF. I will work on this. In the meantime, you can check my PR if you haven't already. I have added preview image.
