### ISSUE TITLE
duplicate bug

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#317]
I'm experiencing the following issue:

1. Open sketch. 
2. Click duplicate.
3. It no longer works to switch which file is being viewed (`index.html` vs. `sketch.js` etc.)
4. Close window and re-open sketch from URL and now it works.

(Will try to pinpoint / reproduce this more later, just noticing it office hours so posting quickly)

**Comment by catarak** [comment]
will investigate!
