### ISSUE TITLE
Sign-Up Page Broken

### ISSUE THREAD

**Issue by JonasGruenwald** [processing/p5.js-web-editor#3172]
### What is your operating system?

Mac OS

### Web browser and version

Firefox@126.0.1, Chrome@125.0.6422.142, Safari@latest

### Actual Behavior

In the web editor https://editor.p5js.org, when I click on "Sign Up", I get taken to https://editor.p5js.org/signup which renders a blank page.
There is a React Error in the console.

On Chrome, the error is:
```
TypeError: Cannot read properties of undefined (reading 'createElement')
    at SignupForm.jsx:156:19
    at react-final-form.es.js:710:12
    at ea (react-dom.production.min.js:153:146)
    at ja (react-dom.production.min.js:173:192)
    at ks (react-dom.production.min.js:265:425)
    at Su (react-dom.production.min.js:246:265)
    at Eu (react-dom.production.min.js:246:194)
    at gu (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
```

### Expected Behavior

Presumably there should be a signup page?
If signup is not currently possible, maybe a message could be there, explaining this.

### Steps:
1.  Ensure you are not logged into the web editor (open an incognito window)
2.  Go to https://editor.p5js.org/signup

### Notes

I was able to sign up through GitHub by using 'Sign In' instead of 'Sign Up'

**Comment by raclim** [comment]
Thank you so much for catching and reporting this! This might be related to some new changes we made to the Login/Signup pages in [this PR](https://github.com/processing/p5.js-web-editor/pull/2467/files#diff-9850faa6349d2bcdf2359d33ed824f241409168f68f6878f13ff887efd4b0295). We'll try to have a resolution for this as soon as possible!

**Comment by raclim** [comment]
@JonasGruenwald Just want to update that I just pushed out a fix for this, so I believe that the signup page should be loading now! Thanks again and please let me know if this issue still persists!

**Comment by JonasGruenwald** [comment]
woah that was quick! yeah page seems to load now :)
