### ISSUE TITLE
Getting npm err by docker compose on npm install

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [processing/p5.js-web-editor#3180]
### p5.js version

web

### What is your operating system?

Windows

### Web browser and version

chrome://latest

### Actual Behavior

Whenever i am trying to set up the project using docker compose it shows me npm err during npm install
![image](https://github.com/processing/p5.js-web-editor/assets/101992909/f1c4f590-c3da-45a3-9b91-ae22c2831ae0)
After that i tried to run manually npm install
It also showing me errors
![image](https://github.com/processing/p5.js-web-editor/assets/101992909/27f60ce7-e397-421e-99d0-ef3a4e52ddc1)

### Expected Behavior

Whenever we try to set up the project then it should be set up without any npm errors
Its should'nt show any conflict between the versions or any other kind of error 

### Steps:
1. Try to fix the npm error so that user dosent get erros during npm install
 
### Snippet:
```js

// Paste your code here :)

```

**Comment by utsavjosh1** [comment]
@Rudra-Sankha-Sinhamahapatra Upgrade you npm version.

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
I have the latest npm version

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@JoshiUtsav

**Comment by utsavjosh1** [comment]
![image](https://github.com/processing/p5.js-web-editor/assets/98454866/929af401-b8fa-4ca8-a2cf-2a7d8bac437a)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
is it working for you?
how can i run it ??
Because i think the project is running on older versions...so if i get back to older npm,node versions it will not be a good idea

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@JoshiUtsav

**Comment by utsavjosh1** [comment]
Yes, it is working on my machine

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
@JoshiUtsav do you have the latest node js,npm version?

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
![image](https://github.com/processing/p5.js-web-editor/assets/101992909/c2248808-27d2-4bd4-a11e-e22e9a6cf969)
using latest versions

**Comment by ghost** [comment]
> is it working for you? how can i run it ?? Because i think the project is running on older versions...so if i get back to older npm,node versions it will not be a good idea

You can use nvm to use a specific node version for a particular project by using `nvm install vX.Y.Z` and you can refer to [https://www.freecodecamp.org/news/node-version-manager-nvm-install-guide/](url)

**Comment by raclim** [comment]
Hi @Rudra-Sankha-Sinhamahapatra, although you have the latest node and npm versions on your machine, they aren't the ones that are compatible with this repository, which runs on node v16.14.2 and npm v8.5.0. 

<img width="262" alt="Screenshot 2024-07-09 at 11 27 38 AM" src="https://github.com/processing/p5.js-web-editor/assets/43053081/93b15e62-dfc2-4570-8145-3972607f13b9">


 You can refer to the [installation docs](https://github.com/processing/p5.js-web-editor/blob/develop/contributor_docs/installation.md) for more context on this as well. We do receive some npm warnings for some incompatible dependencies at the moment, but plan to update our node version soon.

**Comment by raclim** [comment]
Just wanted to update that we just made some adjustments to the Docker configuration, which hopefully also addresses a few other issues with installing it. I'm going to close this issue for now, but please feel free to reopen this or create a new one if this still persists, thanks!

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
okay
