### ISSUE TITLE
Cannot change user email.

### ISSUE THREAD

**Issue by shibomb** [processing/p5.js-web-editor#3193]
### What is your operating system?

None

### Actual Behavior

Users cannot change their email address in https://editor.p5js.org/account 

### Expected Behavior

Users can change their email address.

### Steps:
1. Change email in https://editor.p5js.org/account
2. (you cannot click "Save All Settings"Button)
3. Enter new password. Then the “Save All Settings” button will be enabled.
4. Click "Save All Settings" Button.
5. (You will probably get a “Current password is not provided” error due to a server-side check.)
6. Enter current password and  Click "Save All Settings" Button.
7. (in the server side, The email change process will not be executed because the current password has been entered.)

**Comment by rj-Anurag** [comment]
@shibomb Hey , your issue is not valid at all If you are login with some third party github or google then the email is same for editor as well. There is no point on changing email
