### ISSUE TITLE
User Interaction problem

### ISSUE THREAD

**Issue by BabluKumar17** [processing/p5.js-web-editor#322]
User Interaction problem

![image](https://cloud.githubusercontent.com/assets/14871809/23824591/4465b508-069f-11e7-90ac-bc3ea33fb977.png)

**Comment by catarak** [comment]
yeah, i'm aware of this issue. it has to do with how the preview is being rendered, related to #145 and the other issues labeled server-side preview generation. i'm going to fold this into #145 but consider it a +1.
