### ISSUE TITLE
debouncing while signup by user

### ISSUE THREAD

**Issue by sohelhussain** [processing/p5.js-web-editor#3237]
<img width="1253" alt="Screenshot 2024-09-21 at 10 51 48 PM" src="https://github.com/user-attachments/assets/699f5d3d-691d-4beb-a63f-b27fad38fc0c">

### Actual Behavior

the req function are call again and again when we type a word by word

### Expected Behavior

 when the user are stop the writing, that are function are call after 100ms

**Comment by raclim** [comment]
Thank you so much for opening this! To help consolidate and organize issues, I'm going to close this one as https://github.com/processing/p5.js-web-editor/issues/3235 has been raised!
