### ISSUE TITLE
Collections Not Visible to Non-Owners

### ISSUE THREAD

**Issue by raclim** [processing/p5.js-web-editor#3269]
### What is your operating system?

Mac OS

### Web browser and version

All Browsers

### Actual Behavior

Collections is not visible to users who do not own the collection. 

<img width="1300" alt="Screenshot 2024-11-07 at 2 01 00 PM" src="https://github.com/user-attachments/assets/c744c21e-c510-4811-b6a2-734187e873ed">

### Expected Behavior

Collection to be visible (pictured below). 
<img width="1399" alt="Screenshot 2024-11-07 at 12 35 56 PM" src="https://github.com/user-attachments/assets/9de3b880-3bd4-49ca-a65b-decb98f602f1">

### Steps:
1. Find a URL to a collection that is not created under your own account. i.e `/:username/collections/:collection-id`
2. Afterwards, a blank page should appear.

**Comment by jht9629-nyu** [comment]
I see the same problem attempting to view my collections from other account:
https://editor.p5js.org/jht1493/collections/xgLMHI3T8

**Comment by raclim** [comment]
Just pushed out a fix for this, hopefully it works!
