### ISSUE TITLE
Console history not accessible with up arrow

### ISSUE THREAD

**Issue by bojidar-bg** [processing/p5.js-web-editor#3271]
### p5.js version

1.11.1

### What is your operating system?

Linux

### Web browser and version

Firefox Version: 131.0.3 / 20241014102019

### Actual Behavior

Pressing the up arrow key does not bring old code into the console's input field.

### Expected Behavior

Pressing the up and down arrow keys cycles through history, so that we don't have to retype any of the code we've just entered
This used to be the case until recently; not sure at what point the regression happened, however.

### Steps:
1. Enter some code into the console's input field, e.g. `1`. Press enter to execute it.
2. Press the up arrow key. 
3. Observe that nothing happens.
4. Input some more text, without pressing enter.
5. Press up arrow again.
6. Observe that your just-entered code gets deleted.

### Snippet:
N/A (Default sketch works just fine for reproducing.)

**Comment by bojidar-bg** [comment]
Looking at the component tree with the React devtools addon and comparing with the code in [ConsoleInput.js:12-14](https://github.com/processing/p5.js-web-editor/blob/686f9e55b7aad15fe48d037cc363981bf0e84005/client/modules/IDE/components/ConsoleInput.jsx#L12-L14), I can see that the `commandHistory` state manages to only store one line of code, while `commandCursor` remains at -1 at all times.

![image](https://github.com/user-attachments/assets/9739bd9a-878c-4d1a-9fdf-95af921ca752)

I'm going to guess that the problem comes from the fact that `useEffect` on line 18 and event on line 27 captures the initial value of `commandHistory` which then renders line 48 ineffective: (and probably likewise for `commandCursor`)
https://github.com/processing/p5.js-web-editor/blob/686f9e55b7aad15fe48d037cc363981bf0e84005/client/modules/IDE/components/ConsoleInput.jsx#L48

CC @nahbee10 because it would seem that the previous code, which correctly used state actions for that, was replaced in https://github.com/processing/p5.js-web-editor/commit/a46664009fff0d78a635d20f02615d0181fd8479#diff-5ea6bdfa3c08ded9faeb06a44e8ca992e31c3b5f94c816c390d1cc91266b96ffL45-R48

**Comment by raclim** [comment]
Thanks for raising this @bojidar-bg! I'm currently working on the Console at the moment, and can add this to the next set of changes to it! Hopefully it should be out by sometime next week.

**Comment by ujjwaldubey1** [comment]
@raclim I'll Feel very happy to work on this issue

**Comment by raclim** [comment]
Thanks for the interest @ujjwaldubey1! I did end up finding a solution to it and am currently in the midst of testing and making a few other edits to the Console, so I think we might be covered here. I'll check out the fix you just submitted for the other issue soon though!

**Comment by ujjwaldubey1** [comment]
Okay!!

**Comment by lindapaiste** [comment]
@raclim when I [reworked this component](https://github.com/processing/p5.js-web-editor/blob/750994d5cad00543fdc4addee4feeb501602556f/client/modules/IDE/components/ConsoleInput.jsx) I found that I had to store both the line number and the array of commands in the same `useState` hook.  That way you can access both items in a `prevState` callback, allowing you to change the line without needing to introduce a dependency on any state.

That was for v6 so the actual code will be a little different, but the principle still holds.

https://github.com/processing/p5.js-web-editor/blob/750994d5cad00543fdc4addee4feeb501602556f/client/modules/IDE/components/ConsoleInput.jsx#L76-L79

(I actually feel that it's very bad practice to induce a side effect from within a `setState` so I kinda hate these two)
https://github.com/processing/p5.js-web-editor/blob/750994d5cad00543fdc4addee4feeb501602556f/client/modules/IDE/components/ConsoleInput.jsx#L93-L101

https://github.com/processing/p5.js-web-editor/blob/750994d5cad00543fdc4addee4feeb501602556f/client/modules/IDE/components/ConsoleInput.jsx#L115-L122

**Comment by lindapaiste** [comment]
> Looking at the component tree with the React devtools addon and comparing with the code in [ConsoleInput.js:12-14](https://github.com/processing/p5.js-web-editor/blob/686f9e55b7aad15fe48d037cc363981bf0e84005/client/modules/IDE/components/ConsoleInput.jsx#L12-L14), I can see that the `commandHistory` state manages to only store one line of code, while `commandCursor` remains at -1 at all times.
> 
> ![image](https://private-user-images.githubusercontent.com/5276727/384530598-9739bd9a-878c-4d1a-9fdf-95af921ca752.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MjUxMjksIm5iZiI6MTczMTUyNDgyOSwicGF0aCI6Ii81Mjc2NzI3LzM4NDUzMDU5OC05NzM5YmQ5YS04NzhjLTRkMWEtOWZkZi05NWFmOTIxY2E3NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTNUMTkwNzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQzMGQwZDEyMTQ4Zjg1M2Y0NDUzZmY4ZTY4MTA2N2FmOGZjMmRlYzU0OGRlMjM2MGY4ZmMxYTcyYTJlYjBiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NpuBNkqwWhbgPQjQfxoOhNT9-dHKBfNv-eUnkuZwSyo)
> 
> I'm going to guess that the problem comes from the fact that `useEffect` on line 18 and event on line 27 captures the initial value of `commandHistory` which then renders line 48 ineffective: (and probably likewise for `commandCursor`)
> 
> https://github.com/processing/p5.js-web-editor/blob/686f9e55b7aad15fe48d037cc363981bf0e84005/client/modules/IDE/components/ConsoleInput.jsx#L48
> 
> CC @nahbee10 because it would seem that the previous code, which correctly used state actions for that, was replaced in [a466640#diff-5ea6bdfa3c08ded9faeb06a44e8ca992e31c3b5f94c816c390d1cc91266b96ffL45-R48](https://github.com/processing/p5.js-web-editor/commit/a46664009fff0d78a635d20f02615d0181fd8479#diff-5ea6bdfa3c08ded9faeb06a44e8ca992e31c3b5f94c816c390d1cc91266b96ffL45-R48)

Thanks for identifying the relevant commit.   I can see that we actually were using `prevState` based callbacks in the previous version and then it was changed to use the state variables directly.  But the dependency array for this hook does not contain any of those variables.  This means that the value of the `commandHistory` variable, when accessed inside the `useEffect`, will always be `[]`.  100% of the time.  The body of this function gets the values of all of its variables on the very first render and they are never re-evaluated, due to the empty dependency array.  @nahbee10 this is called a "stale closure" and it's what I was warning you about in the WIP PR
> You have to be very careful that any function which you provide to the CodeMirror editor will be called with the right variables at the time of execution.

Stale closures are a major issue when dealing with these CodeMirror components, and it's why I've rejected so many previous attempts to convert this component.  There is a lot of explanation and suggestions in my review comments on #2409 that you should look at.

**Comment by raclim** [comment]
@lindapaiste I just attached the PR I was working on—in it I continued with some of the newer changes and broke the `useEffect` hook down into separate ones and added in the relevant variables (`commandHistory`, `commandCursor`, `dispatchConsoleEvent`) into their dependency arrays, which I think is handling the stale closures. 

I found it to work, but it's a bit lengthy and I guess I'm not sure if it's the best approach?
