### ISSUE TITLE
Alignment issue  of Eye Section in login & Signup

### ISSUE THREAD

**Issue by Jatin24062005** [processing/p5.js-web-editor#3277]
### Increasing Access

Whenever we select on the eye button in the login and signup page on focus the border are  not aligning  well which create a bad impression to the User
![image](https://github.com/user-attachments/assets/b35a95b1-59b0-468e-a91a-9e159ef8a517)

### Feature enhancement details

Go in the Styling Directory and find for the csss class = form_eye_icon and make changes as per need.

**Comment by raclim** [comment]
Thanks for opening this! 

We do currently have an issue open for this, https://github.com/processing/p5.js-web-editor/issues/3241, with a few PRs and notes on how we might want to handle this—I also provide a bit more details in [my comment for a recent PR on some css suggestions](https://github.com/processing/p5.js-web-editor/pull/3263#issuecomment-2474382914). To help organize and consolidate duplicate issues, I'm going to close this one but please feel free to add any new suggestions to the linked one!
