### ISSUE TITLE
AWS dependency

### ISSUE THREAD

**Issue by grigio** [processing/p5.js-web-editor#33]
I read from the readme

> Or, if you don't want to do that, just ask me to send you mine. Refer to this gist for creating an S3 bucket for testing, or if you don't want to do that, I will send you my AWS credentials.

Is possible to be AWS agnostic? At least for local development?

**Comment by catarak** [comment]
AWS S3 is necessary for media uploads and eventually, publishing. I could add a configuration option for development, so that if you wanted to work on stuff that didn't have to do with media uploads or publishing, you could still do work. Open to other options as well.

**Comment by catarak** [comment]
You can actually just put gibberish for these Amazon variables and everything will be fine; you just won't be able to upload to S3.
