### ISSUE TITLE
BIG BUG!!!

### ISSUE THREAD

**Issue by KianNagpal** [processing/p5.js-web-editor#331]
Dear Humans
I Recently Saw A Cockroach nearby even though I used bug spray beforehand..
I Cannot work out what happened so if you would please so kindly look into it

-HUMAN

**Comment by catarak** [comment]
Hey, I ask that you would read the [contributing guidelines](https://github.com/processing/p5.js-web-editor/blob/master/contributing.md) before submitting issues. This is an open source project and therefore it is frustrating to receive issues that are spam and waste the time of contributors.
