### ISSUE TITLE
Anonymous Saving Disable?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#34]
In the user testing session we are leaning towards disabling anonymous saves to reduce confusion for now and add it back later perhaps as a feature.  At the very least, prompt users to remind them that they aren't logged in and can if they want.

Thoughts @lmccart?

**Comment by lmccart** [comment]
I could imagine it being useful to autosave (even if it's just in local storage) for anonymous users just so that if you close and immediately reopen the tab it still holds your code. That is, it wouldn't show up in any sketchbook anywhere, it's just for restoring state. Similar to power cycling your macbook and seeing the open windows reopen. However, if this adds complication or is difficult to implement, we can definitely forget it.

**Comment by shiffman** [comment]
@lmccart yes, I agree that would be very useful. 

I wrote the above issue quickly today during our meeting, but for more background we discovered that anonymous saving was the source of several bugs / confusion points during the user testing.  And since we are asking students to sign up for an account we thought focusing on making saving to your sketchbook more robust a higher priority.

**Comment by lmccart** [comment]
Ah, got it. I'd say if it's causing bugs and confusion let's scrap it!

**Comment by shiffman** [comment]
Just noting that this came up in class again this week and I can offer more specifics.  With anonymous saving, several students created and saved projects without noticing they were not logged in.  They then submitted the anonymous links as homework. . .  When other students clicked on the links and messed with the code, the original code was lost.   All along they thought someone had messed with the code in their own account.

So for now, yes, let's just remove this feature.  If we add it back in, we'll want to think about whether we need to alert a user that they are not logged in or make anonymous sketches read-only or something .. . ?  Not sure how other editors handle it.

**Comment by zhuoxi** [comment]
CodePen generates unique url when saving if not logged in. Another person with that link will have to "fork" the pen before being able to edit the file.

http://codepen.io/anon/pen/bwZxqK
->
http://codepen.io/anon/pen/ANOTHER_RANDOM_STRING

jsfiddle will allow anonymous users to update the file, but would add version number at end of the url.

https://jsfiddle.net/7r5h34p1/
->
https://jsfiddle.net/7r5h34p1/1

**Comment by catarak** [comment]
With this feature, I've followed the flow of CodePen (except I think there's a bug in which anonymous users can edit any sketch that doesn't belong to a user), but I think the best thing is just to remove this feature as it's too confusing.

**Comment by catarak** [comment]
Closed with commit 0a459246ac62f72b4de61bc2f4db773e43d63478
