### ISSUE TITLE
Textures and other 3D scetches not showing.

### ISSUE THREAD

**Issue by jloooo** [processing/p5.js-web-editor#348]
This may have something to do with the textures.

**Comment by catarak** [comment]
can you link to the sketch you're having issues with?

**Comment by catarak** [comment]
@jloooo fyi this p5 example is working for me: http://alpha.editor.p5js.org/p5/sketches/rkk7uycLSwx

**Comment by catarak** [comment]
i'm not able to reproduce this so i'm going to close this issue. feel free to reopen if you run into this issue again.
