### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by lanstonpeng** [processing/p5.js-web-editor#349]
I checkout the repo and follow the instructions to setup
while I open `localhost:8000`, it did show the p5 editor page, but the terminal always shows this particular error

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property '_id' of null
    at /Users/lanstonpeng/devs/p5.js-web-editor/server/views/404Page.js:9:28
    at Query.<anonymous> (/Users/lanstonpeng/devs/p5.js-web-editor/node_modules/mongoose/lib/model.js:3737:16)
    at /Users/lanstonpeng/devs/p5.js-web-editor/node_modules/kareem/index.js:277:21
    at /Users/lanstonpeng/devs/p5.js-web-editor/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by catarak** [comment]
I'm not sure what's triggering the 404 page to load, but the reason it's crashing is because `npm run fetch-examples` loads p5.js example sketches to the p5 user and that hasn't been run yet. This needs to be added to the README.

**Comment by catarak** [comment]
i fixed the readme but otherwise i am not able to reproduce this. feel free to reopen if you run into this issue again.
