### ISSUE TITLE
"Payload too large" error on adding data files

### ISSUE THREAD

**Issue by mtchl** [processing/p5.js-web-editor#351]
Hi - love your work folks! Ran into this issue with my students this week.
https://alpha.editor.p5js.org/mtchl/sketches/H1xyolxgZ
This sketch includes text files with position data - 1000 coordinate pairs, each file is c 45kb. After uploading a third file of the same size, the sketch refuses to save and any new edits go unsaved.

The JS console shows this error
`PUT https://alpha.editor.p5js.org/api/projects/H1xyolxgZ 413 (Payload Too Large)    vendor.js:174 `

Deleting a file fixes the issue and the sketch is saveable again - but uploading any more text files (txt or json) throws the same error. Uploading image / media files seems to not trigger the error.

I'm on MacOS 10.12.4, browser is Chrome  57.0.2987.133. I get the same error with current Safari.

**Comment by catarak** [comment]
Since the file is so small, it's being uploaded to MongoDB locally rather than to S3. Therefore, this is probably an issue with the Express.js configuration or the ngnix config—will investigate!
