### ISSUE TITLE
Duplicating a sketch causes issues with uploaded files

### ISSUE THREAD

**Issue by yporteous** [processing/p5.js-web-editor#354]
When duplicating a project, uploaded files seem to not carry over properly. While this can be worked around with external hosting for javascript libraries, the same cannot be done for images or other assets that need to be loaded by the javascript.

**Comment by kjhollen** [comment]
Just encountered this one today, too. 

Example broken sketch:
http://alpha.editor.p5js.org/kjhollen/sketches/BkFrYIfxZ

Original sketch:
http://alpha.editor.p5js.org/kjhollen/sketches/H1XSKIfxW

Console error for the duplicate sketch says 403 Forbidden when trying to load the asset from aws.

**Comment by catarak** [comment]
this is one of those very fun bugs in which this works locally but not in production. investigating...

**Comment by catarak** [comment]
i have determined that this has to do with the permissions of the s3 bucket itself. investigating more...
