### ISSUE TITLE
sketch disappeared

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#355]
this is the sketch:
http://alpha.editor.p5js.org/lmccart/sketches/SJYXZuA1e

I'm able to open this sketch via my sketchbook (it's named locate me), but when I do I get a blank sketch with a randomized name.

**Comment by catarak** [comment]
hmmmm it appears this sketch is somehow corrupted, will investigate

**Comment by lmccart** [comment]
i might've broken it myself... i've remade it already so feel free to disregard this issue if it's not useful for you to investigate

**Comment by catarak** [comment]
i looked into this and what i think happened is that there was no selected file, and therefore the editor didn't know which file to display. maybe this shouldn't be stored in the database, and this should be determined on the front end only...

**Comment by catarak** [comment]
Code has been added to prevent sketches from getting corrupted like this!
