### ISSUE TITLE
S3 authentication doesn't work in newer AWS regions

### ISSUE THREAD

**Issue by andrewn** [processing/p5.js-web-editor#358]
I'm running the Editor locally with a test S3 bucket in the `eu-central-1` Frankfurt (EU) region. Trying to upload files gives me this error:

```xml
<Error>
  <Code>InvalidRequest</Code>
  <Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message>
  ...
</Error>
```

[Stackoverflow suggests](https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4) that this is because we're using an older authentication mechanism that isn't supported in the newer zones.

This isn't a big issue since in production we're using a region where it works but I thought it'd be good to capture this somewhere.

**Comment by catarak** [comment]
It would probably be good to upgrade this at some point 😄
