### ISSUE TITLE
error line numbers don't match in console

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#36]
This is due to how the JS code is inserted into iframe HTML file.

<img width="625" alt="screen shot 2016-08-10 at 3 09 39 pm" src="https://cloud.githubusercontent.com/assets/191758/17567241/87ccf738-5f0c-11e6-8f61-c7120125877a.png">

**Comment by catarak** [comment]
One way to fix this would be to load the JS files as a bloburl rather than put them inline.
