### ISSUE TITLE
Could Tidy be either a keyboard shortcut and/or full-width of the dropdown?

### ISSUE THREAD

**Issue by bensk** [processing/p5.js-web-editor#360]
The dropdown is not super discoverable, and then I'm watching people click on the whitespace next to tidy, and get no result.

Thank you!

**Comment by catarak** [comment]
If you click on "Keyboard Shortcuts" under the tidy option, it opens up an overlay with a list of all of the currently supported keyboard shortcuts (though not including the detailed list of Sublime Text shortcuts that the editor supports). Tidy is in there!

It's true that "tidy" is hard to click, so I can make that full width/easier to click.

**Comment by bensk** [comment]
🙏🏾 Thank you! Sorry I missed the shortcut.
