### ISSUE TITLE
Right-clicking on multiple files leaves multiple dropdowns open

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#368]
1. right-click file and choose "rename"
2. type new name and hit enter
3. context menu doesn't disappear

(chrome / osx)

<img width="163" alt="screen shot 2017-06-01 at 3 49 23 pm" src="https://cloud.githubusercontent.com/assets/191056/26704122/00b983c4-46e2-11e7-9797-4f75239ce992.png">

**Comment by catarak** [comment]
i'm not able to reproduce this one... is this still happening?

**Comment by aferriss** [comment]
@catarak Definitely still happening for me in Chrome, Safari, and Firefox on osx. Same steps to reproduce as Lauren. 

Additionally if you right click another file in the project folder while the dropdown is open, a second dropdown will pop up. 

The only way to dismiss the menus is by right clicking them again.

**Comment by catarak** [comment]
Cool, I'll look into this one again, though it may become irrelevant when the new sidebar design is implemented (#389).

**Comment by dhruvdutt** [comment]
Couldn't reproduce the original issue but the issue that @aferriss mentioned still prevails.

> if you right click another file in the project folder while the dropdown is open, a second dropdown will pop up.
The only way to dismiss the menus is by right clicking them again.

@catarak Can I work on fixing this?

**Comment by catarak** [comment]
@dhruvdutt sure!

**Comment by dhruvdutt** [comment]
Why is this closed?

**Comment by catarak** [comment]
because it was fixed as #988
