### ISSUE TITLE
cannot view other sketch files

### ISSUE THREAD

**Issue by quasarbright** [processing/p5.js-web-editor#370]
The file dropdown menu that usually allows you to switch between the sketch files (different scripts and the html and css) is not appearing, making it impossible to view, create, or edit other files in a sketch.
![p5jscapture](https://user-images.githubusercontent.com/24596031/27007106-05c6f45c-4e15-11e7-9086-aa089b6ef7f0.PNG)

**Comment by catarak** [comment]
This appears to only be an issue in the dark theme mode.
