### ISSUE TITLE
UI: Enable dismissing overlays with click or escape keypress

### ISSUE THREAD

**Issue by alignedleft** [processing/p5.js-web-editor#371]
Currently, when the following overlays are open:

- Share Sketch
- Open Sketch
- Examples

…to dismiss an overlay, one has to click the "X" in the top right corner.

I’d suggest adopting the convention where, in addition to "X", either of the following also dismisses an overlay:

- clicking anywhere in the gray background area (`div.overlay`)
- pressing the `escape` key

**Comment by catarak** [comment]
I think this is a great idea!

**Comment by AntonVoltchok** [comment]
I would be interested in helping out, currently my stack is React redux rethink express front / koa node back, so somewhat similar.

**Comment by catarak** [comment]
@AntonVoltchok feel free to work on this and make a PR! just comment on this ticket if you do start working on it so no one else is also working on it 😸

**Comment by Katy310** [comment]
I would like take up this issue, if no one is working on it.

**Comment by catarak** [comment]
@Katy310 go ahead and work on this!
