### ISSUE TITLE
Project stops running occasionally

### ISSUE THREAD

**Issue by Mikeryp** [processing/p5.js-web-editor#381]
The project doesn't run sometimes. I make changes with auto refresh enables, and it doesn't refresh, then i restart the project manually, but the project doesn't load! then after sometime, it starts to function properly again .... please work on this!

:)

All the best for the p5js web editor !!!

**Comment by catarak** [comment]
Hmmm, I'll play around with this and see if I can recreate. Is this happening to you for all sketches or only certain ones?

**Comment by Mikeryp** [comment]
I found the exact source of the problem!!  

When auto refresh is enabled, changing a few values refreshes without any problem. Even calling existing functions doesn't cause the problem. But when you define a new function, the auto refresh stops functioning and so does the play button even after i disable the auto refresh,

This is quite irritating if i just forgot to uncheck the auto refresh just before defining a new function!!

**Comment by catarak** [comment]
Thanks for digging around and figuring out the cause of this 😄

**Comment by catarak** [comment]
@Mikeryp i'm not able to reproduce. could you post the sketch that breaks it or post a video of this happening?

**Comment by Mikeryp** [comment]
@catarak Posting the sketch wont help, because it happens while you are writing a new function. I will see if my computer has enough power to record the screen, because my computer does not have a lot of power.

And the problem does not comes just with 1 function .... sometimes its 1, sometimes its more. Just enable autorefresh, run the code, then while the code is running and autorefresh is enabled, write new functions (which could do anything), and keep on writing new functions and call them in the draw function .... My sketch breaks at 2 new functions (yet). 

Just try this while i am figuring out how to record it!

**Comment by Mikeryp** [comment]
@catarak 
Here is the video about the bug.

[bug.zip](https://github.com/processing/p5.js-web-editor/files/1150391/bug.zip)

I hope you fix it. All the Best!! :)

**Comment by catarak** [comment]
it seems like this bug is fixed? i just tried reproducing this and i couldn't.
