### ISSUE TITLE
code folding

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#382]
Code folding is an addon to CodeMirror, as demonstrated in this [example](https://codemirror.net/demo/folding.html). 

[Zeplin Screen](https://zpl.io/Kr0ir).

**Comment by zrispo** [comment]
I'm working on this!

**Comment by himanshuc3** [comment]
It's already implemented. You may want to close this of.

**Comment by catarak** [comment]
for some reason the PR didn't get connected with this issue. closing!
