### ISSUE TITLE
Update Login and Signup Screens with New Design

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#383]
<img width="510" alt="screen shot 2017-07-11 at 10 36 04 am" src="https://user-images.githubusercontent.com/6063380/28073808-e2303242-6624-11e7-9939-6fd39aec2aa6.png">
<img width="511" alt="screen shot 2017-07-11 at 10 36 17 am" src="https://user-images.githubusercontent.com/6063380/28073810-e3d01ea0-6624-11e7-87ff-e864bd79d840.png">
<img width="512" alt="screen shot 2017-07-11 at 10 36 32 am" src="https://user-images.githubusercontent.com/6063380/28073814-e549d29e-6624-11e7-9125-bbe679e9f2ce.png">
<img width="511" alt="screen shot 2017-07-11 at 10 36 48 am" src="https://user-images.githubusercontent.com/6063380/28073817-e79bf1bc-6624-11e7-9f38-68a613562ce2.png">

Even though there aren't explicit designs for the Password Reset/Set New Password modals, those should also be updated to follow this new design.

More details on the [Zeplin project](https://zpl.io/Z2cihf1).

**Comment by nik72619c** [comment]
I was thinking of some designs like:-
![login](https://user-images.githubusercontent.com/30630904/55027136-8e6f0600-502a-11e9-9a5b-dd36f85aa212.PNG)

**Comment by nik72619c** [comment]
or:-
![login2](https://user-images.githubusercontent.com/30630904/55027213-beb6a480-502a-11e9-984d-8f7a5a0ada64.PNG)

**Comment by nik72619c** [comment]
Shall I work on this and file a PR? @catarak

**Comment by catarak** [comment]
hi! thanks for your design suggestions; however, there are already designs. also, i would hold on this—i'm thinking about switching the login/signup/account settings to overlays rather than full screen views, since there's no longer issues with http/https.

**Comment by nik72619c** [comment]
didnt get the word "overlay " here...Could you please explain?

**Comment by catarak** [comment]
overlay as in the way that the sketch list, sketch preferences, etc. are rendered.

**Comment by nik72619c** [comment]
@catarak could I have some personal chat with you, if you dont mind?

**Comment by nik72619c** [comment]
could you provide your gmail/twitter/telegram account?

**Comment by catarak** [comment]
feel free to reach out via Gitter.

**Comment by catarak** [comment]
fixed by #1340.
