### ISSUE TITLE
Update Find styling to new design

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#385]
<img width="512" alt="screen shot 2017-07-11 at 10 49 54 am" src="https://user-images.githubusercontent.com/6063380/28074507-bf217e80-6626-11e7-9534-02f31b552064.png">

See more details on the [Zeplin project](https://zpl.io/Z2cihf1).

**Comment by dhruvdutt** [comment]
@catarak  This seems to be the current behaviour. What's the change required?
