### ISSUE TITLE
Update dropdown styling throughout app

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#386]
<img width="512" alt="screen shot 2017-07-11 at 10 57 08 am" src="https://user-images.githubusercontent.com/6063380/28074885-cbfd1da2-6627-11e7-8a8a-fe694694d752.png">

See [Zeplin project](https://zpl.io/IWOoy) for more details.

**Comment by dhruvdutt** [comment]
What's the required change here?
