### ISSUE TITLE
Update design for adding a text file

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#388]
<img width="514" alt="screen shot 2017-07-11 at 12 49 42 pm" src="https://user-images.githubusercontent.com/6063380/28079767-9bc420f8-6637-11e7-9cf6-6e27f41176ce.png">
<img width="512" alt="screen shot 2017-07-11 at 12 49 50 pm" src="https://user-images.githubusercontent.com/6063380/28079769-9cbb603e-6637-11e7-94e9-e6b0462c0b42.png">
<img width="512" alt="screen shot 2017-07-11 at 12 50 00 pm" src="https://user-images.githubusercontent.com/6063380/28079770-9d9af1c2-6637-11e7-8f8e-86551fcab0c5.png">
<img width="514" alt="screen shot 2017-07-11 at 12 50 16 pm" src="https://user-images.githubusercontent.com/6063380/28079772-9e927488-6637-11e7-836f-fe6ff94ba208.png">
<img width="515" alt="screen shot 2017-07-11 at 12 50 26 pm" src="https://user-images.githubusercontent.com/6063380/28079775-9f8f1166-6637-11e7-9e1c-283633547092.png">

Get the details on [Zeplin](https://zpl.io/Z2cihf1).

**Comment by dhruvdutt** [comment]
@catarak Can I pick this up? ✋
The current modal for adding new file is slightly different since it also includes some space for uploading files/drag and drop box.

**Comment by catarak** [comment]
@dhruvdutt absolutely work on this!
