### ISSUE TITLE
Update Sketch List styling

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#390]
<img width="515" alt="screen shot 2017-07-11 at 1 40 38 pm" src="https://user-images.githubusercontent.com/6063380/28082051-5078431a-663f-11e7-9db1-d2febe73adda.png">
<img width="514" alt="screen shot 2017-07-11 at 1 45 40 pm" src="https://user-images.githubusercontent.com/6063380/28082053-52531b92-663f-11e7-95a4-d6612e4fd363.png">
<img width="513" alt="screen shot 2017-07-11 at 1 49 49 pm" src="https://user-images.githubusercontent.com/6063380/28082240-ebdfa514-663f-11e7-9e18-aab39c12edcf.png">
<img width="514" alt="screen shot 2017-07-11 at 1 50 04 pm" src="https://user-images.githubusercontent.com/6063380/28082241-ee4c5fe0-663f-11e7-99cd-d40f3c341653.png">
<img width="514" alt="screen shot 2017-07-11 at 1 49 37 pm" src="https://user-images.githubusercontent.com/6063380/28082563-cf464204-6640-11e7-903f-e3dfaeb92b45.png">

Deets on [Zeplin](https://zpl.io/Z2cihf1).

**Comment by LakshSingla** [comment]
@catarak I would like to work on #789 but I am unable to get to the above screens. https://editor.p5js.org/ seems to open a sketch for me automatically. Can you please guide which steps to take to reach to this screen?

**Comment by catarak** [comment]
Here are the rendered screens: https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3

If you need exact measurements and colors, I can add you to the zeplin project!

**Comment by LakshSingla** [comment]
@catarak Would this design be possible ? Considering that "Open" comes from `Overlay.jsx` whereas the `Sketches|Collections|Files` would have to be implemented in the `SketchList.jsx`

**Comment by catarak** [comment]
@LakshSingla sorry for the delay on this—got busy and sick over the holidays. i can add you do the zeplin project. do you have a zeplin username? if not, i can invite you via email—feel free to email me your email address!

**Comment by LakshSingla** [comment]
@catarak Lemme create a layout for the modal, then I will move onto the styling part of it. I am doubtful of this design. (Refer to my comment above, quoted below)

> @catarak Would this design be possible ? Considering that "Open" comes from `Overlay.jsx` whereas the `Sketches|Collections|Files` would have to be implemented in the `SketchList.jsx`

**Comment by catarak** [comment]
@LakshSingla there is already a design, so there is no need to make one.

**Comment by LakshSingla** [comment]
@catarak Sorry for the misunderstanding. By layout I meant basic React layout.

**Comment by catarak** [comment]
@LakshSingla i would just ignore the Sketches | Collections | Files header for now, and make it just "Sketches", since the other features are not yet implemented. 

also, my email address is in my github profile!

**Comment by LakshSingla** [comment]
@catarak I have mailed you my e-mail id ..

**Comment by catarak** [comment]
@LakshSingla just invited you!

**Comment by LakshSingla** [comment]
@catarak Thanks!!
One question though: Which endpoint do I need to query to get the sketch's preview? (First column)

**Comment by catarak** [comment]
@LakshSingla don't worry about the thumbnail! that's not implemented yet.

**Comment by LakshSingla** [comment]
@catarak Sorry for the delayed update. I am still working on the issue

**Comment by siddhant1** [comment]
@catarak @LakshSingla is this still being worked on?

**Comment by LakshSingla** [comment]
@siddhant1 #819

**Comment by catarak** [comment]
fixed by #1340.
