### ISSUE TITLE
Update share sketch styling, add copy to clipboard on click

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#391]
<img width="517" alt="screen shot 2017-07-11 at 1 47 23 pm" src="https://user-images.githubusercontent.com/6063380/28082496-a3cf02b4-6640-11e7-8e44-64d0cb2e13f4.png">
<img width="515" alt="screen shot 2017-07-11 at 1 47 34 pm" src="https://user-images.githubusercontent.com/6063380/28082499-a51d59ae-6640-11e7-9429-3bbf2c2136b4.png">

More details on the [Zeplin project](https://zpl.io/Z2cihf1).

**Comment by dhruvdutt** [comment]
@catarak Is there some work left on this? I can probably pick it up if anything is pending.

**Comment by catarak** [comment]
i think this is done ✨
