### ISSUE TITLE
list of sketches not showing in Safari

### ISSUE THREAD

**Issue by kjhollen** [processing/p5.js-web-editor#402]
A few students in class today reported that their list of saved sketches is not showing up when they are logged in and click Open. They were all using Safari when this happened, and I was able to replicate on my own machine by switching to Safari, too.

Everyone is happy using Chrome as a workaround for now—so this can be a low priority issue. :)

**Comment by enauman** [comment]
List of example sketches does not show up in Safari either, Safari v10.1.1. Just says Open a sketch.
