### ISSUE TITLE
File Upload "EntityTooLarge" error box too small

### ISSUE THREAD

**Issue by enauman** [processing/p5.js-web-editor#403]
When uploading a file to a sketch that exceeds maximum allowed the error msg only shows when you mouse over the loading bar, and msg box is too small to read the error to find out what the maximum allowed is (5MB?). Chrome v59.
<img width="260" alt="screen shot 2017-07-23 at 10 07 56 am" src="https://user-images.githubusercontent.com/8062084/28499984-482dc398-6f8f-11e7-9fb8-bb9b33343c87.png">

**Comment by catarak** [comment]
I agree, this is not ideal 😄 we're working on a new design for the file uploader and may throw out this library.

**Comment by catarak** [comment]
This has been fixed ✨
