### ISSUE TITLE
P5.js Editor did not save my file.

### ISSUE THREAD

**Issue by Superman795** [processing/p5.js-web-editor#404]
I was doing my assignment on the web editor, I saved my work 5 times and it looked alright. One day later I return to resume my work and it wasn't saved at all. All my hard work was gone. This is not fun. Please fix this bug. Its happened to me the second time.

**Comment by catarak** [comment]
I'm sorry that happened! This project is still in active development and all of the bugs are not ironed out yet. 

That being said, I don't know how to reproduce this and therefore fix this, so any insight you have would be great! 

I think it would also be good to have better error reporting if there are errors with saving. I can play around with this.

**Comment by Superman795** [comment]
Hey catarak, I understand that the editor is still in its alpha stage of development. There were no error codes issued plus when I saved the file it said project saved. I agree on the part where it would be hard to reproduce this bug. I think there must be a problem on the server side where it is probably not updating with the new files.
