### ISSUE TITLE
Collection/classroom page design

### ISSUE THREAD

**Issue by zrispo** [processing/p5.js-web-editor#416]
Hi all!

I'm currently working on implementing the design for the classroom list page seen here in the zeplin project:

https://app.zeplin.io/project/55f746c54a02e1e50e0632c3/screen/59413d8a749bc4afbca089c7

That's coming along, but we will also need the page that shows information about the classroom including:
 - Classroom name
 - Usernames of all instructors
 - Usernames of all students
 - Classroom description 
 - Classroom image/thumbnail
 - List of assignments
 - List of sketches submitted to each assignment

Here's a quick mockup of what the page might look like (apologies for annoying glare):

![20840325_1840892645928143_1662331426_n](https://user-images.githubusercontent.com/4970417/29327382-ee21024e-81bc-11e7-9a4c-b97d09eb0870.jpg)

It's still a work in progress so any help/input would be greatly appreciated!

**Comment by nileshgulia1** [comment]
hey @zrispo , can u please elaborate the issue?

**Comment by catarak** [comment]
@zripso had started building out a classrooms system over the summer (which was super ambitious and awesome) but i'm not sure he's actively working on it right now!

**Comment by cshirky** [comment]
We're developing a new p5 class at NYU, and are interested in looking at the mockups. Is the work posted to Zeplin publicly visible anywhere? Or can we get an invite to the Zeplin project listed above?

thanks,

-c

**Comment by catarak** [comment]
Here's a link to the latest designs, which doesn't include the classrooms system, but it's similar to the current mock ups for collections: https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3

I had deployed the classrooms branch publicly for a bit, which I am happy to do again if you'd like to look at it, but it's definitely a WIP.

**Comment by cshirky** [comment]
Cassie, many thanks, this is helpful. And we're ITP: We live WIP. :)

Am talking to Zach and Shiffman in another thread, will get back to you about the classrooms branch.

**Comment by zrispo** [comment]
Hey all!

It's been a while since I started working on the classrooms system, but myself and @luxapodular (who did GSOC in 2015 working on Processing.py) are back on it and will be getting the classrooms system up and running as soon as we can!

We'll be working from the `classrooms` branch

**Comment by catarak** [comment]
@zrispo let me know if i can help in any way!

**Comment by migom6** [comment]
Hi @zrispo @catarak. 
Since I am applying for GSOC 2k18 and according to the ideas lists this is one of the proposed projects. It would be very helpful for me in writing the proposal if I get the status of this (how much of this is done.). I tried following up on all the issues but I was clueless. 
Thank you for your time 😄

**Comment by catarak** [comment]
you can check this out on the `classrooms` branch.

**Comment by migom6** [comment]
Hi! @catarak!
I did and I followed all the commits.
**_Here is my proposal:_** [proposal link](https://docs.google.com/document/d/10oOgDLvs9dlc5W-Q_PxfcnM46C9ubmzcfvatP0kRMY0/edit?usp=sharing)
**_Here is a very rough wireframe that can be integrated with the existing code:_** [wireframe scenes invision](https://invis.io/25GKOD4KTNX#/287902177_Scene1)

Thank you for your time. 😃

**Comment by catarak** [comment]
i'm in the process of doing some project management and organization, and trying to close out stale tickets. after many discussions about using the web editor in classrooms, we're ultimately decided that it doesn't make sense to create a LMS within the web editor. instead, the web editor can supplement existing LMS systems! i appreciate all of the thought, prototypes, and discussions around making a classroom system, as it's helped me make decisions about what the goals for this project are!
