### ISSUE TITLE
friendly error system preferences item

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#417]
@almchung has implemented the "friendly error system" in the p5.js, that is, functionality that will (optionally) check the parameters passed into p5 functions when they're called and send helpful messages to console. we're about to merge it this week. this feature can be toggled on and off by setting a boolean variable (`p5.disableFriendlyErrors = true/false;`) in the sketch. is it possible to add this as a preferences item that can be toggled from there, too? 

if it sounds ok, I can work on implementing this.

**Comment by lmccart** [comment]
I guess one point for debate --
only the p5.js library has this functionality it. p5.min.js doesn't. if the user updated the index.html file to link to p5.min.js, the preferences item would no longer have an effect. would this be ok? or would we need to do some detection and auto-hide the item? or is this a reason it shouldn't be in preferences at all?

**Comment by catarak** [comment]
I think it would make sense to, by default, add the non-minified p5.js to a project and include the friendly errors in preferences. Maybe the preference could be removed or unable to be changed if the non-minified version of p5 isn't included in the project?

**Comment by catarak** [comment]
@lmccart for this to work as expected, do `p5.dom.js` and `p5.sound.js` need to be included as the non-minified versions as well?

**Comment by lmccart** [comment]
no, just p5.js.

**Comment by catarak** [comment]
i'm having trouble disabling the friendly errors using `p5.disableFriendlyErrors = true`. does this need to be called in a specific place?

**Comment by lmccart** [comment]
using version 0.6.0, both of these are working for me:

```javascript
p5.disableFriendlyErrors = true;

function setup() {
  ellipse(3, 3);
}
```

```javascript

function setup() {
  p5.disableFriendlyErrors = true;
  ellipse(3, 3);
}
```

**Comment by himanshuc3** [comment]
Is this feature already implemented in the web editor?

**Comment by dhowe** [comment]
I really can't imagine why we not using the friendly error mechanism by default in the online editor (including p5.js rather than p5.min.js). This seems the place where it would be most useful of all (perhaps with an option to disable for the few advanced users still using the editor who happen to need higher performance)? Multiple times per week I see sketches like below fail silently for new users and it is totally confusing for them:

```
var size = 300;
function setup() {
  createCanvas(400, 400);
  ellipse(200,200,size);
}
```

**Comment by dhowe** [comment]
How about just defaulting to the non-minified p5.js for now? Not sure, but I think it is [this line](https://github.com/processing/p5.js-web-editor/blob/f4ff0b1c34172bec71cc33c093d3620a92815760/client/modules/IDE/reducers/files.js#L16)

**Comment by lmccart** [comment]
@dhowe I think one concern was that this significantly slows things down performance-wise and might give a slow first impression of the library. but I may be misremembering.

**Comment by dhowe** [comment]
when new students don't even get basic error messages on mistakes, it is sort of beside the point whether performance is good or not, as they will quickly give up or move on to another tool

this seems absolutely critical from my (teaching) perspective...

**Comment by catarak** [comment]
i hear you @dhowe. i agree this should be added soon!

**Comment by catarak** [comment]
i'm going through a backlog of pull requests and just reached my initial version to add this as a preference. i'm thinking that it's too confusing to add this as a preference, as it's unclear what it should do. for example, is this a per-sketch preference or per-account? maybe, for all projects, non-minified p5.js should be included by default, and advanced users can change to p5.min.js if they need to. this could also fit into a #4 library management system, in which a user could, with a GUI, switch from the non-minified to the minified for a project.

**Comment by dhowe** [comment]
> maybe, for all projects, non-minified p5.js should be included by default, and advanced users can change to p5.min.js
This is what I was thinking -- ideally one could easily switch to minified via the UI (rather than hand-editing the index.html)

**Comment by catarak** [comment]
agreed! the library management feature has unfortunately been pushed off for a while, but i actually don't think it's a ton of work. would be a great self-contained project within the editor for someone to work on!

**Comment by lmccart** [comment]
@catarak makes sense to me!
