### ISSUE TITLE
Hello P5: song example breaks the preview window

### ISSUE THREAD

**Issue by rasagy** [processing/p5.js-web-editor#418]
### What I tried to do
Opened the first Example in the list — `Hello P5 : song`, and clicked on `play song automatically.` Here’s the project: http://alpha.editor.p5js.org/p5/sketches/r1SLhBE4mZ-

### What happened
The sketch played two notes, and then reloaded the page with editor _inside_ the preview section:

![image](https://user-images.githubusercontent.com/1117531/29661739-9929746a-88e2-11e7-930f-07e001d40843.png)

### Other attempts

I read on https://github.com/processing/p5.js-web-editor/issues/414#issuecomment-321290727 that there are some errors with the Preview section that don’t show up on Full screen, so I went to `Share`, got the link as `http://alpha.editor.p5js.org/full/r1SLhBE4mZ-` and tried this in the full screen link.

- First time, it played a note and appended a `/` to the link: `http://alpha.editor.p5js.org/full/r1SLhBE4mZ-/#`
- After clicking on the `play song automatically` link, it appended another `/` to the link: `http://alpha.editor.p5js.org/full/r1SLhBE4mZ-//#` and gave a 404.

<details><summary>Here’s a gif and screenshot of the console</summary>

GIF: <p>
![p5 editor inception](https://user-images.githubusercontent.com/1117531/29662123-cc0d9a2c-88e3-11e7-861b-9f86f4a94ba7.gif)

Errors in console: <p>

<img width="430" alt="screenshot 2017-08-24 15 30 47" src="https://user-images.githubusercontent.com/1117531/29662057-9a53f918-88e3-11e7-9d20-c48a9f117e3c.png">

Errors in full screen view: <p>

<img width="1278" alt="screenshot 2017-08-24 15 36 57" src="https://user-images.githubusercontent.com/1117531/29662081-b0a66610-88e3-11e7-994a-35b466902969.png">

</details>

----

### Platform details

I’m on Google Chrome Version 60.0.3112.101 (Official Build) (64-bit) / Mac Sierra. 

Let me know in case this is already being discussed in another issue/you need more info to replicate it!

**Comment by catarak** [comment]
Thanks for the detailed breakdown! This is a known issue, discussed in #145. The example actually got fixed, I just need to rerun the task in production. I'll do that right now :smile:

**Comment by catarak** [comment]
This is now fixed in production. Dom links still cause the editor to render in the iframe, so I will leave #145 open.
