### ISSUE TITLE
Running one program actually runs a different program.

### ISSUE THREAD

**Issue by BenLuker** [processing/p5.js-web-editor#419]
I was working on two separate programs for my class. I opened program A and ran it. Then I opened program B and ran it. They were identical. I thought I had duplicated program A as program B, because they were identical, so I deleted program A. Then I ran program B again, and it was completely different! I just lost program A because of this.

**Comment by catarak** [comment]
Oh no, I'm sorry to hear this! I will try to recreate, but can you also add a link to the sketch? Maybe it's a a bug that has to do with the specific sketch.

**Comment by catarak** [comment]
My current steps to reproduce this bug are:

1. Open existing sketch
2. Don't save it
3. hit duplicate
4. Make changes to the duplicate sketch
5. When you save the duplicated sketch, your changes disappear

**Comment by BenLuker** [comment]
You know what? I think I was just stupid and did something wrong. Thanks
for your concern though.

**Comment by catarak** [comment]
No worries! I think that this helped me find a separate bug so 🎉 🎉 🎉

**Comment by kjhollen** [comment]
Oohhhhh I think I saw this over the summer but didn't report it because I couldn't figure out the steps to reproduce it. Glad you could track this down, Cassie, and thanks for filing, Ben!

**Comment by himanshuc3** [comment]
@catarak Repeating the steps you did to reproduce the issue, the page got reloaded but the changes did not get lost when I repeated the process.

**Comment by catarak** [comment]
@shinytang6 does #546 fix this?

**Comment by dhruvdutt** [comment]
@catarak Can this be closed?
