### ISSUE TITLE
Video Not playing in Safari

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#420]
~~Using the createVideo function appends a visible video element to the body of the page. Each time the function is called a new video is appended.~~ 

~~Here's the code in question and a screenshot~~
~~http://alpha.editor.p5js.org/aferriss/sketches/r1NEgAhdb~~

Perhaps this is a separate issue, but I also noticed that videos don't play in the p5 canvas on Safari (though the appended element does play).

![screen shot 2017-08-24 at 6 35 38 pm](https://user-images.githubusercontent.com/3698659/29696036-17403948-88fb-11e7-8091-fb6fb979217b.png)

**Comment by kjhollen** [comment]
Hey @aferriss I think this is the expected behavior—createVideo is part of the DOM library and adds a video element to the page. Maybe there's something in the docs that can be updated to make it more clear?

**Comment by aferriss** [comment]
@kjhollen 🤦‍♂️ ah you're totally right! I need to read the docs more carefully.

**Comment by catarak** [comment]
Just tested this project in Safari outside of the editor to make sure it's not p5.js issue. It works, so I'll need to do some digging to figure out what's causing this.

**Comment by himanshuc3** [comment]
It is playing in Safari v11.0.1 ( Mac - v10.13.1 )

**Comment by catarak** [comment]
I'm still seeing this issue on Safari v9.1.

**Comment by catarak** [comment]
This is working for me on the latest Safari—going to close this issue!

**Comment by philipkrueger** [comment]
For those who are searching: It was not playing from my local python server. As I moved to my ftp everything is working...
