### ISSUE TITLE
Log in screen returns to Sign up screen

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#421]
1. Go to https://alpha.editor.p5js.org/signup
2. Click Log In at the bottom
3. Fill in your info and try to Log in

Afterwards you'll be redirected back to the Sign up screen. Clicking the X in the upper right corner cycles the Log In and Sign up screens back and forth. Going to alpha.editor.p5js.org will bring you to the editor and you'll be signed in.

**Comment by catarak** [comment]
Thanks for submitting this! I can reproduce. After logging in or signing up, the app is supposed to redirect you to the last page you were on before authenticating. There's obviously a bug there 😄
