### ISSUE TITLE
Organize sketches into collections within a user's account

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#43]
Not only should a user be able to organize the files within a sketch into folders, but also a user should be able to organize their projects into folders.

**Comment by mimiyin** [comment]
Being able to share sketch folders would be really useful too!

**Comment by catarak** [comment]
Collections are better than folders because sketches can be in multiple collections 😄

**Comment by catarak** [comment]
# Design
<img width="513" alt="screen shot 2017-07-11 at 10 01 07 am" src="https://user-images.githubusercontent.com/6063380/28072185-42381466-6620-11e7-89f9-0db8e703095f.png">
<img width="510" alt="screen shot 2017-07-11 at 10 03 06 am" src="https://user-images.githubusercontent.com/6063380/28072189-440cccf0-6620-11e7-95e0-b37b3938ba06.png">
<img width="512" alt="screen shot 2017-07-11 at 10 03 27 am" src="https://user-images.githubusercontent.com/6063380/28072192-459ec23a-6620-11e7-8f35-d2ed73854709.png">

See more details on the [Zeplin project](https://zpl.io/Z2cihf1).

**Comment by GiammaCarioca** [comment]
Hi, guys. I'm a beginner. I've been teaching myself JS and ReactJS for a few months now. They say the best way to learn it's to work on a real project. I'm wondering how could I help out with this one feature.

**Comment by catarak** [comment]
Hi @GiammaCarioca! This issue is definitely one that's been coming up in conversation/asked as a feature a lot, but I think it needs to be broken up into smaller issues. Therefore, I don't think it would be a good first issue without a little more planning work. However, there are issues labeled "help wanted" or "good first issue" that would be great to start on!

**Comment by slowizzm** [comment]
As an educator I would love to see this feature added in the near future. It would be nice to have a collection of lessons, student work, instructor examples, inspiration, my personal sketches, ect ...  

By the looks of it, I'm just an echo ... just wanted to back this feature request.

**Comment by catarak** [comment]
@slowizzm it's useful to get feedback on issues that lots of folks want, so thanks!

**Comment by andrewn** [comment]
Closing this as #1115 now has more detail about the collections feature that is being implemented.
