### ISSUE TITLE
class and let warnings

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#430]
As with #21, I'd like to suppress the warnings in the editor for `let` and `class` as we plan to use this syntax for teaching at ITP.  Thoughts?

<img width="301" alt="screen shot 2017-09-01 at 4 15 57 pm" src="https://user-images.githubusercontent.com/191758/29986476-904535a0-8f31-11e7-99f8-70413acb4280.png">

**Comment by catarak** [comment]
agreed! this is a simple change to the JSHint configuration so it can be added quickly 😸
