### ISSUE TITLE
keyIsDown

### ISSUE THREAD

**Issue by garryson361** [processing/p5.js-web-editor#435]
wont let me do
var p1y = 150
var p1x = 0

	rect(p1x,p1y,10,100)
	if(keyIsDown(DOWN_ARROW)){
	p1y = p1y - 3
	}

**Comment by lmccart** [comment]
this works for me:
```javascript
var p1y = 150
var p1x = 0

function setup() { 
  createCanvas(400, 400);

} 

function draw() { 
  background(220);	
	rect(p1x,p1y,10,100)
	if(keyIsDown(DOWN_ARROW)){
	p1y = p1y - 3
	}
}
```
have you included setup and draw in your code?
which version of the p5.js library are you using? which browser are you running it on?

**Comment by garryson361** [comment]
Yeah... Im sorry. I forgot to click on the window where it was running

**Comment by catarak** [comment]
no worries, thanks for reporting!
