### ISSUE TITLE
Remove or change preview warning?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#438]
Filing an issue to follow up on discussion with @catarak @lmccart today. The preview warning is less necessary now and takes up quite a bit of screen real estate especially while teaching on a lower resolution projector. I'm not sure if it's best to remove or have it fade out or just make it smaller, subtler, whatever you think is best Cassie!

> THIS IS A PREVIEW VERSION OF THE EDITOR, THAT HAS NOT YET BEEN OFFICIALLY RELEASED. IT IS IN DEVELOPMENT, YOU CAN REPORT BUGS HERE. PLEASE USE WITH CAUTION.

**Comment by catarak** [comment]
i'm finishing up #229 which removes this!
