### ISSUE TITLE
Invisible Menu Items

### ISSUE THREAD

**Issue by AidanNelson** [processing/p5.js-web-editor#439]
Menu items are invisible (in background color) until I hover my mouse over them.  Then, they switch to white.
<img width="250" alt="screen shot 2017-09-15 at 3 55 22 pm" src="https://user-images.githubusercontent.com/6486359/30501153-430425fe-9a2f-11e7-82a9-afe6bb023c67.png">

**Comment by catarak** [comment]
looks like an issue with the theming 😄 should be a quick fix!
