### ISSUE TITLE
Download Sketch as zip - Save Library Files

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#44]
It may cause issues if the library files are still just linked as CDNs, especially if a user expects to be able to run the project offline.

**Comment by indefinit** [comment]
+1 to this enhancement!

**Comment by catarak** [comment]
should this be the default? should this be an option that a user can turn on?

**Comment by lmccart** [comment]
my intuition says let's just do this by default, and not add more options that could potentially confuse

**Comment by meiamsome** [comment]
@catarak Looks like this issue has been solved by #367 and should be closed?

**Comment by catarak** [comment]
yep!
