### ISSUE TITLE
Canvas preview in editor doesn't show full range of mouse postions

### ISSUE THREAD

**Issue by vanevery** [processing/p5.js-web-editor#441]
function draw() {
print(mouseX);  // Never shows 0 when run in editor, lowest value appears to be 6
}

MacOS Chrome Version 61.0.3163.91 (Official Build) (64-bit)

**Comment by catarak** [comment]
I believe this is due to the HTML element that allows you to reside the code pane/preview pane being on top of the canvas/iframe. If it were behind the iframe then a user wouldn't be able to drag it, so it probably makes sense just to give it some width and not be on top of the code pane or the preview pane.

**Comment by nileshgulia1** [comment]
Hey @catarak @vanevery :) what is the status of the issue ,is anybody working on it?

**Comment by catarak** [comment]
no one is working on this right now! feel free to pick it up if you'd like 😄

**Comment by nileshgulia1** [comment]
@catarak  @vanevery  

> print(mouseX); // Never shows 0 when run in editor 

It shows 0 in the console.what is the bug ?
Tested on:Firefox Quantum 57.0.1 (64 bit)
![screenshot from 2017-12-21 18-39-52](https://user-images.githubusercontent.com/22280901/34257146-9464e80c-e67e-11e7-9b9c-4bcade639eaa.png)

**Comment by vanevery** [comment]
Can you try in Chrome with a smaller window?

**Comment by nileshgulia1** [comment]
@vanevery  sure. 
tested on :ubuntu 64 bit
![screenshot from 2017-12-21 18-56-12](https://user-images.githubusercontent.com/22280901/34257647-bfa77884-e680-11e7-8098-08fb2f137b09.png)
ah ,after it shows:
![screenshot from 2017-12-21 18-58-59](https://user-images.githubusercontent.com/22280901/34257742-181a4c26-e681-11e7-8716-064e161b295a.png)

**Comment by himanshuc3** [comment]
How is it so that when measured in terms of pixels, 
```
function setup() { 
  createCanvas(400, 400);
} 

function draw() { 
  background(220);
	print(mouseX);
}
```
the preview pane is as expected 400x400, while because the leftmost mouseX position is 6 and rightmost mouseX position is 400 the dimensions should be 394x400.
What do you think @catarak @nileshgulia1 @vanevery

**Comment by catarak** [comment]
see my above comment for why this behavior is occurring.

**Comment by himanshuc3** [comment]
does anyone know where is the canvas element located shown in PreviewFrame. I can't find it... :(

**Comment by shinytang6** [comment]
@himanshuc3 maybe adding `z-index: 10` to `_preview-frame.scss` works? l have tried that one before but l forget the specific line l added :)

**Comment by himanshuc3** [comment]
I don't if it works on display:flex items. One more disadvantage would be
that it would reduce the size of hovering for resize bar.

**Comment by shinytang6** [comment]
ok... not very sure about that:)
