### ISSUE TITLE
confusion re: missing options, not your sketch

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#442]
I've noticed in the last couple weeks working with students that there is some confusion over the missing "save" and also the missing "add file", "add folder" options when you are viewing a sketch that is not part of your own account. 

I wonder if instead of removing these options, it might be more clear to have them "greyed out" and perhaps a message "please duplicate into your account before __________" if you try to click on them?

Has anyone else encountered this?

(Loving the new design btw!)

**Comment by catarak** [comment]
i agree—these options should definitely be removed if you do not own the sketch!

**Comment by catarak** [comment]
okay wow i totally misread this, you are saying that it is confusing that these options are missing. from a UX perspective i think it's a little cumbersome to have a popup. one option which CodePen projects use is to make all projects that a user does not own read only, but then you have to duplicate a project in order to change anything.

**Comment by shiffman** [comment]
Yeah, there's no great solution here and I am ok with it as is. I just wanted to note that I got stuck for a while b/c I didn't realize I wasn't in my own project and was wondering if there's a way to visually indicate that? Happy to leave open for discussion for a bit and then close if my momentary lapse doesn't recur with others.

**Comment by machinic** [comment]
I think disabling (graying out) the standard menu options that are not available to you when a sketch is not your own makes sense. It also builds muscle memory for the UI in that pieces are not disappearing or moving around. I'll also think more about additional tweaks that could ameliorate this issue.

**Comment by himanshuc3** [comment]
![screen shot 2018-04-17 at 9 20 36 pm](https://user-images.githubusercontent.com/19166045/38881286-3691e69a-4285-11e8-98e7-0f7f4d300b27.png)
1. I think, for now (Project Name) by (author) is probably the simplest way of indicating. If we could highlight it a bit more in the new UI that is to be implemented, that would help.
2. Also as @machinic said, either greying the whole menu section or not showing it at all and instead showing a duplicate/Fork would be better.

**Comment by ashu8912** [comment]
Hey @catarak  i think this issue is resolved now
