### ISSUE TITLE
Activating Menus --> File/New by accident

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#443]
This may just be me and my own incompetence (as well as the smaller resolution I'm using with a classroom projector), but I am finding while teaching that I'm activating the top menus by accident often. For example, I end up clicking File --> New when meaning to just click run. 

Should they require a click rather than a rollover?

**Comment by machinic** [comment]
I think so given that the UI has been tightened-up in terms of overall space, so this is more likely to occur now than in the previous iteration. Having that degree of intentionality (trigger menus on click)  would help and is not outside of the realm of expectation particularly if we include a hover indication — I suggest something like this (where File is being hovered):

<img width="362" alt="file-on-hover" src="https://user-images.githubusercontent.com/3985997/30813940-c28905e2-a1dc-11e7-96ed-f9925e10e119.png">

**Comment by catarak** [comment]
noted! i can play around with this.
