### ISSUE TITLE
undefined String, missing console error

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#444]
The following code produces an error in the Chrome console `Cannot read property 'toString' of undefined` but no error shows up in the editor console.

```javascript
let txt;

function setup() { 
  createCanvas(400, 400);
  text(txt,100,100);
} 
```

**Comment by catarak** [comment]
i've noticed some console errors only appearing in the Chrome console as well, will investigate!

**Comment by kjhollen** [comment]
I think that maybe all of the syntax error messages are not showing in the p5 console? but print() seems ok. 

also seeing that 'file not found' messages are no longer showing in console, which I think had been added:
http://alpha.editor.p5js.org/kjhollen/sketches/BkTlyaoa-

but error message for using color too early appears to be working:
http://alpha.editor.p5js.org/kjhollen/sketches/ryW0Jaop-

(sharing these examples in case they are helpful)

**Comment by shiffman** [comment]
I've been keeping a list of errors that don't show up in the console that maybe should (a new one I found today, for example, is `NavigatorUserMediaError: Only secure origins are allowed`). @catarak, would you prefer one issue with a long list of errors or separate issues for each or. . .?

**Comment by catarak** [comment]
@shiffman for now let's put all of the errors in one issue, and if it makes sense eventually to break them up into smaller issues we can do that.

**Comment by shiffman** [comment]
Sounds great, I think I'll open a new thread to try to get this organized.
