### ISSUE TITLE
Default background color is too close to IDE background color

### ISSUE THREAD

**Issue by sofian** [processing/p5.js-web-editor#447]
I find that when introducing P5.js to students it is important for them to be able to see that something is going on even when their code is empty. In the current interface, the default color of the background matches the background color of the IDE, which makes it difficult to see.

I would suggest perhaps adding a border around the preview.

![screenshot from 2017-09-28 20-40-07](https://user-images.githubusercontent.com/791244/30996264-98b968b6-a48d-11e7-9188-dc95782589ce.png)

**Comment by catarak** [comment]
this is addressed in the latest design:

https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3/screen/59413d796dcd7f8bbce04ece

**Comment by sofian** [comment]
Good. I'll close this then.
