### ISSUE TITLE
406 Errors on GET Assets for fullscreen link

### ISSUE THREAD

**Issue by devonelliott** [processing/p5.js-web-editor#449]
I've added a couple of files to my sketch, a .csv and .txt, that I'm trying to preload using loadTable (with the 'csv' and 'header' options) and loadStrings.

The files are in the project, but they do not appear under the 'My assets' window, and I can't find any options to add assets to that window. I added these in the project editor sidebar, where I created a folder called 'assets' and then uploaded the files.

On the fullscreen link, I get _406 (Not Acceptable)_ errors at the GET request for those files.

The same sketch operates fine locally on my machine, with no 406 errors. Additionally, the sketch seems to be working in the Preview within the editor. It's only in the fullscreen link where I get those 406 errors.

The errors occur in both Chrome and Safari, but the p5js sketch runs fine locally and in the editor's preview on both of those browsers.

<img width="1071" alt="screen shot 2017-10-04 at 10 33 10 am" src="https://user-images.githubusercontent.com/4967358/31181572-b1ddfbc0-a8ef-11e7-9643-3ee93dc8a24e.png">

**Comment by catarak** [comment]
thanks for reporting this!

**Comment by TheChesireCat** [comment]
Hi all,

Upon investigation of the p5.js httpDo function it seems that the content-type of the request is by default text/plain for non json/xml/text files. This conflicts with the ```requestsOfType``` middleware function 
```javascript
const requestsOfType = type => (req, res, next) => {
  if (req.get('content-type') != null && !req.is(type)) {
    return next({ statusCode: 406 }); // 406 UNACCEPTABLE
  }

  return next();
};
```
I am able to succesfully GET the csv file if I edit the request and remove the content-type header.

**Comment by catarak** [comment]
interesting! i believe this middleware was added for security reasons, so that the API would only accept JSON see https://github.com/pillarjs/understanding-csrf#how-to-mitigate-csrf-attacks. however, maybe csv and txt should be whitelisted?

**Comment by TheChesireCat** [comment]
I believe a possible fix would be adding a requestOfTypePlain as another middleware. Similar to the requestOfTypeJSON.
The site shouldn't be vulnerable to CSRF attacks as long as the client only accepts resources from p5js affiliated urls and of known benign filetypes.

**Comment by catarak** [comment]
makes sense. thanks for the help in figuring this out!
