### ISSUE TITLE
Add file by drag and drop does not allow .js library upload

### ISSUE THREAD

**Issue by sulfobus** [processing/p5.js-web-editor#450]
Images work fine, but when trying to add a new library to a project, it fails:
![image](https://user-images.githubusercontent.com/32538694/31220782-c6e4911e-a9c1-11e7-8ecd-5f3d53cf532a.png)

Only way to add a library AFAIK is to create a new file and copy-paste the library as text into the editor.
Sorry if I'm missing something here, first time poster.

**Comment by catarak** [comment]
that should work, thanks for reporting!

**Comment by catarak** [comment]
just tried to reproduce this but i'm able to upload javascript files. do you have the specific file you're trying to upload?

**Comment by sulfobus** [comment]
Thanks for looking into it. I'm trying to upload the p5.collide2d library downloaded from from https://github.com/bmoren/p5.collide2D. I tried both full and minimized versions. I tried also using my github login, but get same error. If I rename the same file to for example .png if uploads fine. 

Clicking on the drop-file-box brings up the file browser with a filtered list ("Custom files", showing only html-files and images afaik). It is possible to change the filter to "All files" but trying to upload any other file type than the "custom files"-filter gives the error (s.a. pdf, php).

I'm using Windows 10 64bit, Chrome browser. Tested on two computers.

**Comment by catarak** [comment]
i just downloaded and uploaded those files and it's working for me. the response from the uploader is cryptic though, it says 'uploaded plaintext file locally' and looks like it didn't work. is that what you see?

**Comment by sulfobus** [comment]
No, I get the message above: "You can't upload files of this type" and no file is uploaded.

I tested earlier tonight on a Mac running Chrome and there it worked just fine, just like you describe. Tested another Win10 laptop with Firefox, where it gave the error.

**Comment by catarak** [comment]
okay got it. i bet this has to do with the MIME type that Windows assigns to the file, which is different from Mac. thanks for helping me figure this out!
