### ISSUE TITLE
P5.js uncompressed download broken.

### ISSUE THREAD

**Issue by repgainer3** [processing/p5.js-web-editor#451]
On the P5.js/download page, none of the files work, whenever I try to download them it gives me a 404 error.

**Comment by catarak** [comment]
thanks for this! could you be more specific about what's going on? are you referring to the p5 web editor or do you mean on the p5.js website, at https://p5js.org/download/? i just tried to download the latest p5.js on the website and it doesn't seem to be working, so i think that's what you mean.
