### ISSUE TITLE
My editor has not been working for the past few days.

### ISSUE THREAD

**Issue by ngchupkov** [processing/p5.js-web-editor#452]
Hi, my editor has not been working at all. It won't let me save any projects or preview them for the past few days. I tried using my account on a different computer and even tried to make a different account but i could still not get it to work. Hope you can help.

**Comment by catarak** [comment]
thanks for reporting this! i'm sorry this is happening to you, but i'm not able to reproduce this. could you be more specific about what's happening? what is your account? do you have a specific sketch that is not working?
