### ISSUE TITLE
Adds newline when editing on mobile chrome android

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#453]
_From @inodb on October 15, 2017 20:43_

On Android chrome Google pixel when I use the editor it seems to automatically add newlines on every edit.

_Copied from original issue: processing/p5.js#2266_

**Comment by avocadoboi** [comment]
Yep. Same here on LG G3.

**Comment by himanshuc3** [comment]
I am also using android on Gionee f103 ( android v6.0 ).
I apparently did not have any issues with extra lines being generated. 
It would however help me bit more if you could be a little more precise in how to reproduce this issue.

**Comment by avocadoboi** [comment]
This isn't happening to me anymore, so i guess it's fixed.

**Comment by catarak** [comment]
maybe it was an issue with CodeMirror ✨

**Comment by avocadoboi** [comment]
probably :^)

**Comment by inodb** [comment]
yup fixed for me as well

**Comment by catarak** [comment]
great i will close this then! feel free to reopen if it comes up again.
