### ISSUE TITLE
noprotect doesn't work?

### ISSUE THREAD

**Issue by aparrish** [processing/p5.js-web-editor#455]
As illustrated by [this sketch](https://alpha.editor.p5js.org/allison.parrish/sketches/ryVN0lEaW). The error message isn't particular about where `// noprotect` is supposed to go, so I put it everywhere I could think of that seemed even vaguely reasonable. Am I doing it wrong or is something broken? Not being able to turn off infinite loop detection is making it difficult to process large data sets :(

**Comment by catarak** [comment]
thanks for this! the loop protection library is finicky, so i'll (1) make sure it is working properly and (2) figure out how to make it more clear as how to use it.

**Comment by catarak** [comment]
just tested this, this has been fixed. `loop-protect` will be updated by #698 since the current version is causing issues.
