### ISSUE TITLE
Running sketches with syntax errors.

### ISSUE THREAD

**Issue by boazsender** [processing/p5.js-web-editor#457]
First of, way to go on this awesome software! I was able to clone, install and run a local instance to debug really easily.  The setup docs were great, and so was the getting started experience!

I have an architectural suggestion that I wanted to make after working to resolve the "save after syntax error" bug in #428. Over in #456 I made a quick fix to prevent that from happening. I think that fix works as a short term solution, but is a bit brittle and a bit of a high overhead— rerunning syntax checking in the preview frame component when it's already been run in the editor component.

What do you think of a potentially more robust solution where the app shares data between the editor component and the preview frame component, and uses the state of the sketch from the editor to selectively run the preview in certain cases (e.g. when the sketch has no syntax errors)?

In either case, I think that my recommendation would be to not "auto refresh" or "auto run" code with syntax errors in it. Does that sound right? Would this be desirable? I'm not a regular p5 teacher or user, so I don't know if there would be a case where you want syntax errors to be run. What do ya'll think?

**Comment by shiffman** [comment]
Thanks for looking into this @boazsender! I'll let @catarak weigh in on the technical details, but in principle I agree the sketch does not need to "auto refresh" when there is a syntax error.
