### ISSUE TITLE
loop protect & // noprotect

### ISSUE THREAD

**Issue by AidanNelson** [processing/p5.js-web-editor#458]
#### Nature of issue?

- [x] Found a bug

#### Details about the bug: 

- Web browser and version: Version 61.0.3163.100 (Official Build) (64-bit)
- Operating System: Mac OS X 10.11.6
- Steps to reproduce this: 
The following code throws an error: "Exiting potential infinite loop at line 4. To disable loop protection: add "// noprotect" to your code."  No variation in where I put // noprotect makes a difference.

function setup() {
	createCanvas(400, 400);
	// noprotect
	for (let i = 0; i < 500; i++) {
		for (let j = 0; j < 800; j++) {
			console.log("i: " + i + " / j: " + j);
		}
	}
}

**Comment by catarak** [comment]
thanks for submitting this! this was also reported in #455 so i'm going to folk this issue into that one, but good to know that many people are seeing this and therefore should be higher priority.
