### ISSUE TITLE
maximize canvas preview/minimize code editor

### ISSUE THREAD

**Issue by indefinit** [processing/p5.js-web-editor#46]
Would be very nice to have a button to minimize the code editor and maximize the canvas preview if possible.  I'm pretty sure codepen has a way to resize panes, right?

**Comment by catarak** [comment]
I just pushed to production the ability to drag resize the panes (let me know if this is not working) but no way to maximize the editor or the preview. There will also be different views of the sketch, i.e. a presentation view and embed view (see #6).

**Comment by shiffman** [comment]
Resizing panes is working great!

**Comment by catarak** [comment]
This feature will be added in the updated design:
![03 web-editor-light-example-1024 1x](https://cloud.githubusercontent.com/assets/6063380/19288007/206473ea-8fd2-11e6-8cd1-b03f43e375c8.png)
![07 web-editor-full-view-small-canvas-1024 1x](https://cloud.githubusercontent.com/assets/6063380/19288010/261f1290-8fd2-11e6-8d59-cabce8d3575f.png)

**Comment by catarak** [comment]
this is the same as #208
