### ISSUE TITLE
sketches popup for other users can only be accessed by changing the url while it's already open

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#460]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement

#### Feature enhancement details:
Not sure whether to file this as a bug or feature enhancement. I want to be able to type `alpha.editor.p5js.org/username/sketches` in the address bar and view that person's sketches. Right now the only way I can do this is if I 
1. open a new sketch while logged in
2. click 'Open' from the file dropdown (at this point I see all my sketches).
3. change the user name in the url to the one I'd like to see. 

Otherwise if I try to navigate to alpha.editor.p5js.org/aferriss/sketches I just get brough to a new empty sketch.

I'm not sure if the sketches are meant to be private, which is why they're not initially shown —but it 
 would nice to be able to look at other people's sketches without going through the steps I outlined above.

**Comment by catarak** [comment]
i agree that this user experience could be improved! i am open to any and all suggestions about this. i think this could partially be solved by building out the classrooms feature (#426, in early stages), but also some search and/or browse built into the app would be great too.

**Comment by himanshuc3** [comment]
I think this feature would be similar to how different pens are shown by codepen.io. 
Any other views?

**Comment by catarak** [comment]
this issue is specifically for a full screen sketch list view (or perhaps a profile view). if you think other views/designs make sense feel free to open another issue!

**Comment by kjhollen** [comment]
doing a little bit of old issue clean-up. I believe that this now works, so I'm going to close this issue. @aferriss if there's something I'm missing, feel free to re-open!
