### ISSUE TITLE
Broken link (to tutorials) on about page

### ISSUE THREAD

**Issue by andylolz** [processing/p5.js-web-editor#464]
#### Nature of issue?

- [x] Found a bug

#### Details about the bug: 

Link to [Tutorials](https://p5js.org/tutorials/) on [the about page](https://alpha.editor.p5js.org/about) should now link to [Learn](https://p5js.org/learn/).

Refs processing/p5.js-website#132

**Comment by catarak** [comment]
thanks for this! should be a quick fix ✨
