### ISSUE TITLE
exported projects with unicode strings display garbage

### ISSUE THREAD

**Issue by aparrish** [processing/p5.js-web-editor#466]
Projects with Unicode characters inside strings work fine in the web editor, but using these strings in (e.g.) the `text()` function displays garbage. [This project](https://alpha.editor.p5js.org/allison.parrish/sketches/rJMf9yE0-) illustrates the issue. The Chinese character (猫) is displayed fine in the web editor, but when you export the project and open it in the web browser, it shows some mojibake:

![image](https://user-images.githubusercontent.com/125839/32150160-3dff350c-bce5-11e7-95d4-d843e1cd10c8.png)

I can verify that this problem happens with the exported project in Chrome 61.0.3163.100 and Firefox 56.0 on Mac OS 10.11.6, and happens whether I open the file from the filesystem directly (`file:///` url) or using a local web server (Python 3's `http.server`).

It looks like the HTML for the sketch doesn't have a `meta charset` tag. I think that Chrome and Firefox are correctly guessing the encoding for the web editor version because nginx is configured to serve all html content with a `Content-Type: text/html; charset=utf-8` header. When loading from a filesystem or from a web server that doesn't send that header, the browsers seem to be guessing the charset incorrectly. Adding `<meta charset="UTF-8">` to the sketch's `index.html` seems to fix the problem with the exported version while not affecting the functionality of the version hosted through the web editor, so a potential fix would just be to include that line in the template that generates the HTML.

**Comment by catarak** [comment]
thanks for the detailed issue! i think it is very reasonable that the default `index.html` file should have the `<meta charset="UTF-8">` tag so i will add that for all new sketches.
