### ISSUE TITLE
aria-live tags not working

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.js-web-editor#47]
Tested the IDE - [http://52.41.35.139:8000/](http://52.41.35.139:8000/) on IE 11 on Windows 8
- Syntax highlighting not working
  ![capture](https://cloud.githubusercontent.com/assets/5505598/17609785/1ef3278c-6006-11e6-91df-9888177b58ba.PNG)
- aria-live tags are not working - the aria updates are not being read out when the value changes with a screen reader. This however is not a generic IE issue ( aria-live works in [this](http://mathuramg.com/CodeMirrorTest/version4/) example in IE 11/ Windows 8)

**Comment by catarak** [comment]
I think the syntax highlighting is not working because right now it uses [CSS variables](http://caniuse.com/#feat=css-variables), but I'll fix that when I add all of the themes. 

I'm not sure about the aria-live tags though, you'll probably have to help me debug that.

**Comment by MathuraMG** [comment]
Yep, I am looking into the aria-live bug. Will update when I figure the reason!

**Comment by catarak** [comment]
@MathuraMG did you ever figure this one out? I vaguely remember talking about this. I'm going to make a separate ticket for the IE syntax highlighting, as I'm working on that right now.
