### ISSUE TITLE
chrome extension

### ISSUE THREAD

**Issue by jawadcode** [processing/p5.js-web-editor#473]
# Please could you make this editor a chrome extension
I don't know if this is possible and if I'm wasting your time but please could make this into a chrome extension as it would be impractical as a website?

**Comment by catarak** [comment]
thanks for the suggestion! i'm not sure i understand what you mean, as this project *is* currently a website. could you elaborate further, or include some simple wireframes?

**Comment by VictorGaiva** [comment]
My guess is that you are say you'd like to be able to use this in chrome as an offline editor, without having do download a program to your computer. Then an extension would make sense.

**Comment by jawadcode** [comment]
Yes, that is what I meant.

Sent from Mail for Windows 10

**Comment by catarak** [comment]
i agree, that would be awesome! there's a few features i think are higher priority for now, but i've been getting a lot of requests for offline access so we'll see 😄

**Comment by jawadcode** [comment]
Thank You for listening to me.

**Comment by bmoren** [comment]
some more discussion about offline access over on the forum: 

https://discourse.processing.org/t/p5-js-desktop-editor/9728/6

some discussion points that came up:
+ take the code from the current web-editor and compile it as an electron app so it would be a stand alone editor.
+ Another way to do this might be adding support for the Offline Web Applications API directly to the p5 web editor. http://apress.jensimmons.com/v5/pro-html5-programming/ch12.html 
+  a build process to include a copy of the reference that is offline.

**Comment by catarak** [comment]
i think it would be better to support the offline web applications API—as we learned from the desktop editor, supporting different OS's with an electron app is difficult.

**Comment by catarak** [comment]
I'm going through and cleaning up old issues. I believe the way that would make sense to support offline support would be to use a service worker with local storage. (#813 / #103)
