### ISSUE TITLE
Bug: Print() creates Dialogt to PRint File to Printer and Alpha.editor issue

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#474]
_From @Xrispy7 on November 13, 2017 2:4_

I found a bug with Print(); on both Google Chrome Local and Google Chrome > p5.js Alpha Editor
When I try to use Print() in the Alpha Editor i get the following error:

//begin example
var x = 10;
print(x);
//end example
Ignored call to 'print()'. The document is sandboxed, and the 'allow-modals' keyword is not set.

when  I use Print(); Locally Google Chrome opens a Print Dialog window, as if I want to Print my File to a Printer.

Macbook Pro 2011 MACOSX 10.8.5 Laptop, Google Chrome version 49.0.2623.112 (64-bit) 
/*! p5.js v0.5.16 October 11, 2017 */

_Copied from original issue: processing/p5.js#2360_

**Comment by lmccart** [comment]
_From @limzykenneth on November 13, 2017 9:58_

Hi @Xrispy7, we have a dedicated repo for the web editor, can you post this issue [over there](https://github.com/processing/p5.js-web-editor/issues) so the web editor team can have a look at it? Thanks.

**Comment by catarak** [comment]
this is caused by calling `print()`  outside of a p5 function. if you call `print()` inside of `setup()` or `draw()` and so on, it functions as `console.log`. i'm pretty sure this is the intended behavior, @lmccart can you confirm?

**Comment by catarak** [comment]
i will answer this question myself and say yes, this is intended behavior, see https://github.com/processing/p5.js/wiki/Frequently-Asked-Questions#why-cant-i-assign-variables-using-p5-functions-and-variables-before-setup

**Comment by lmccart** [comment]
@catarak yes this is correct! sorry I should've looked closer at the code example before moving, I though this was referring to calling print() inside of setup or draw.

**Comment by Xrispy7** [comment]
@cassie @lmcart Thank you both for clearing this up so quickly! I'll invest
further before posting a bug next time.

Chris P
