### ISSUE TITLE
"Fullscreen" not displaying images that appear in normal mode 

### ISSUE THREAD

**Issue by lberdugo** [processing/p5.js-web-editor#477]
- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: Lots of my students are having an issue where image assets they load show up in the preview window in the alpha editor, but do **not** show up when they use the fullscreen version. I've taken a cursory look and I think this occurs in Chrome, Firefox, and Safari.

- Web browser and version: 62.0.3202.94
- Operating System: MacOSX
- Steps to reproduce this: Here is an example

Editor: http://alpha.editor.p5js.org/marisolreyes97/sketches/SJ9b96dyG 
Fullscreen: http://alpha.editor.p5js.org/full/SJ9b96dyG 
Fullscreen code hosted on a personal server: https://xarts.usfca.edu/~lberdugo/coffee_run_1/

**Comment by catarak** [comment]
it appears this was also fixed with 03eae2f1efdaa43689c5de0465832c6913d784b1 \ :smile: /
