### ISSUE TITLE
Student unable to login without resetting password each time

### ISSUE THREAD

**Issue by cmorgantywls** [processing/p5.js-web-editor#480]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version:  Chrome and most other browsers (all current versions)
- Operating System: 
- Steps to reproduce this: Student account is Luisannyr8121. Whenever she tries to log in, she is told her password is incorrect and needs to reset it each time. I have tried resetting her password myself and logging in and it makes the same error. Additionally, she sometimes does not receive the password reset e-mail (which I've also witnessed trying to get back into her account myself).

#### New feature details:

**Comment by crhallberg** [comment]
The same thing is occurring with one of my students. Username: monterw1. Uses a password manager, so definitely not an mistyping error.

**Comment by catarak** [comment]
thanks! hopefully I can get to the root of this.

**Comment by catarak** [comment]
Some possible stuff to try:
- [ ] update database, and trim all whitespace from usernames and email addresses
- [ ] on sign up, don't allow any whitespace in username, email, or passwords
- [ ] trim whitespace on login, only at the end of username or email, not on passwords

**Comment by catarak** [comment]
I'm 99% sure this was fixed by #1317 🎉
