### ISSUE TITLE
Mailgun key required in .env for developement 

### ISSUE THREAD

**Issue by simonlimon** [processing/p5.js-web-editor#484]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request
- [x] Issue with development setup

#### Details about the issue: 

- Operating System: MacOSX 10.13.1
- Steps to reproduce this: 
    1. Fork the repo and clone it from scratch.
    2. Follow the instructions on the `README` to set up the development environment. 
    3. Try to run `npm start`. It will fail with the following error message:
```
/Users/spf/src/open_source/p5.js-web-editor/node_modules/mailgun-js/lib/mailgun.js:15
    throw new Error('apiKey value must be defined!');
```
After adding `MAILGUN_KEY=<mailgun-api-key>` to the `.env` file everything started working okay, even with an incorrect key. Is this expected behavior for development or am I doing something wrong? If it is expected, maybe the `README` instructions for development should be updated to make this clearer?

**Comment by catarak** [comment]
thanks for submitting this! you don't need the mailgun key unless you are specifically working on the part of the app that sends emails (i.e. password reset and email verification). i agree, this could be clearer in the setup guide, and it would be nice in the app didn't crash if you're missing this key.
