### ISSUE TITLE
http/https in sketch preferences

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#485]
This is re: bdd8df63015e6f61bfe415931ddb55479c224d6a (removing HTTPS in toolbar).

In helping some students this weekend I noticed the preference doesn't work properly if you are viewing a sketch that is not part of your account. Perhaps this is by design, i.e. if the sketch requires HTTPS, the creator of that sketch should have set that properly? But we may need some sort of UI element to indicate this since it fails silently.

**Comment by shiffman** [comment]
Just noticed also in office hours that the "sketch preference" for `https` is not retained if you "duplicate" the sketch.

**Comment by catarak** [comment]
thanks for reporting this! will investigate.

**Comment by catarak** [comment]
not relevant anymore since the whole site is https!
