### ISSUE TITLE
Server logging in production

### ISSUE THREAD

**Issue by francisli** [processing/p5.js-web-editor#489]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

In ```requestsOfType.js``` there are some active console.log statements printing the entire request object, which can leak sensitive info (i.e. you'll see passwords sent during registration, etc). If you're actively debugging something in the production environment, I'd suggest introducing a logging library like Winston (https://github.com/winstonjs/winston) that you can control with a log-level environment variable so it's easy to turn on and off.

**Comment by catarak** [comment]
thanks for this! i meant to only leave in these logging statements temporarily 😸
