### ISSUE TITLE
vendor.js not being assigned a unique hashed filename

### ISSUE THREAD

**Issue by francisli** [processing/p5.js-web-editor#493]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

If you view the source of the main index page served from a production deployment, you'll observe that the vendor.js file did not get assigned a unique hashed filename like app.js and app.css. This can potentially cause issues if a newer index file fetches an older version of vendor.js served up from a cache.

**Comment by catarak** [comment]
thank you ✨

**Comment by dhruvdutt** [comment]
I'll look into it. :hand:

**Comment by catarak** [comment]
amazing! i assume this is a webpack configuration issue and hopefully isn't too hard to fix.
