### ISSUE TITLE
Support US East (N. Virginia) region for S3 buckets, CNAME for buckets

### ISSUE THREAD

**Issue by francisli** [processing/p5.js-web-editor#497]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

I've created my bucket in US East (N. Virginia) so that its in the same region as my server. However, since the code is manually constructing URLs based on the region code, this is failing as the region code is "us-east-1", but being the very first s3 region, the host is simply "s3.amazonaws.com".

This handling of the S3 bucket URLs also prevents using CNAMEs for the bucket urls, which is what I'd really like to do so that the bucket can also be put behind a CDN.

**Comment by catarak** [comment]
thanks for this! i am very clueless about all things AWS so i appreciate knowing about all of the things i have done incorrectly.
