### ISSUE TITLE
My assets modal does not show orphaned assets

### ISSUE THREAD

**Issue by francisli** [processing/p5.js-web-editor#498]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

Actually, not sure if it's a bug or intended behavior- if you start a new sketch, upload a file in the sidebar, but don't save your sketch, the file will still be in the S3 bucket, but will not appear in the "My assets" modal. In ```listObjectsInS3ForUser```, only assets that are found in saved projects are listed.

Shouldn't all assets be returned, maybe with some sort of "orphaned" indicator, so that they can be deleted by the user?

**Comment by catarak** [comment]
i think at first i thought that these shouldn't be returned, but thinking about this again, i agree, i think that these assets should be returned 😄
