### ISSUE TITLE
xsrf protection unnecessary...?

### ISSUE THREAD

**Issue by francisli** [processing/p5.js-web-editor#500]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:

So, I see that XSRF protection is enabled with csurf on the server side, and setting a cookie containing that token for the axios library on the client side to pick up and send on each request back...

So, one issue with this implementation is that it prevents CDN caching of the root (/) homepage, since everyone needs to get a token in order to be able to register/log in. Since the root is going to be the highest trafficked page, this will prevent being able to utilize the CDN to reduce load on the server.

Since the API is a JSON-only API to be invoked using AJAX calls (the requestOfType middleware returning an error otherwise), is this really necessary? Browser forms cannot post JSON (so you can't just put the server url into the action param of a FORM on a malicious site), and AJAX calls will be restricted by CORS (so you can't script it otherwise). So, I'm not sure there's any XSRF vulnerability to be addressed...?

**Comment by catarak** [comment]
Yeah I think you are right, the XSRF protection is unnecessary. There are a few routes that are not JSON but they are just GET requests so there's nothing to worry about there, right?

**Comment by francisli** [comment]
That's right- as long as the GET requests don't have any side-effects (which they shouldn't per the semantic intent of GET) then there shouldn't be anything to worry about with those routes.
