### ISSUE TITLE
Configure unit tests

### ISSUE THREAD

**Issue by nileshgulia1** [processing/p5.js-web-editor#502]
#### Nature of issue?

- [x] New feature request

#### New feature details:
It will be good if unit tests are configured like  p5.js project.
needs some discussion from the members

**Comment by catarak** [comment]
i definitely support this! feel free to work on this 😄

**Comment by nileshgulia1** [comment]
yeah taking this up :+1:  :)

**Comment by nileshgulia1** [comment]
@catarak Is there any active communication channel for the community so that i can ask related queries? :)

**Comment by catarak** [comment]
not sure why you closed this, but the discussion takes place on github issues, and for any specific questions feel free to email me directly 😄

**Comment by nileshgulia1** [comment]
@catarak  I was a bit busy working on anything else,sorry for not informing .

**Comment by shinytang6** [comment]
Would like to look into this issue:) l know something about Mocha and Jest. Which one should be used here?

**Comment by nileshgulia1** [comment]
Hey @shinytang6 , Go for it , the project uses react so it may be better to use jest+enzyme for writing tests . cheers :)

**Comment by catarak** [comment]
i'm not an expert at writing unit tests but i've heard that mocha is the most popular framework. what would be the advantage of using jest instead?

**Comment by nileshgulia1** [comment]
@catarak Jest provides some important features such as [snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html) which makes it different from mocha. Yes mocha is also good and famous , but jest is used especially for react components for smoke testing(testing rendering of components independently)

**Comment by sepans** [comment]
I started working on adding unit tests before seeing this issue so apologies for not communicating it here beforehand.

Would love to know your feedback.
