### ISSUE TITLE
Text area fallback for codemirror

### ISSUE THREAD

**Issue by MathuraMG** [processing/p5.js-web-editor#503]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### New feature details:
With the updates in ios and screen reader softwares, codemirror is becoming less accessible. To deal with this problem, we would like to add a text area fallback to codemirror so that people on screen readers can easily access the code.
@lm-n @cleezyitp

**Comment by siddhant1** [comment]
@MathuraMG are you still working on it? I can pick this one up.

**Comment by catarak** [comment]
@siddhant1 i don't think she is. i think this will have to be added as a setting under the "accessibility" settings/
