### ISSUE TITLE
Add Dark, Light, and High Contrast Color Themes

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#51]

**Comment by CleezyITP** [comment]
Hey @catarak should we be submitting the high contrast version?

**Comment by CleezyITP** [comment]
@MathuraMG

**Comment by catarak** [comment]
I recent finished adding the dark theme, which makes it fairly easy to add the high contrast theme. I will need help figuring out all of the mappings.

You can get a sense of the mapping I need by looking at `client/styles/abstracts/_variables.scss` and looking at the `$themes` variable, for how the colors in the IDE itself are mapped. For the CodeMirror editor, you can look at `client/styles/components/_p5-light-codemirror-theme.scss` and `client/styles/components/_p5-dark-codemirror-theme.scss`.

**Comment by MathuraMG** [comment]
@catarak - had a look at the code base, the mapping makes sense! 
For the high contrast theme - I can open up a PR, or would you prefer I send you the values?

 cc @CleezyITP

**Comment by catarak** [comment]
If you made a PR that would be amazing, let me know if you have any questions!

**Comment by MathuraMG** [comment]
Great I'll do that!
