### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Rosmeee** [processing/p5.js-web-editor#513]
l follow the instructions to setup and everything runs well but when l type `npm start`
shows this error
```
'BABEL_DISABLE_CACHE' is not an internal or external command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! p5.js-web-editor@0.0.1 start: `BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the p5.js-web-editor@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Anyone can help me?

**Comment by catarak** [comment]
thanks for submitting this! not sure how to fix this. i was just thinking this morning that i'd like to remove the babel dependency, since i updated the node version in development and production. the reason babel is necessary right now is for the `import` and `export` statements.

**Comment by Rosmeee** [comment]
so how should l get involved in development now？l want to contribute to this
