### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by dhruvdutt** [processing/p5.js-web-editor#515]
#### Nature of issue?

- [x] Existing feature enhancement

#### Feature enhancement details:
Currently, we're using React 15.1.x which was [released](https://github.com/facebook/react/releases/tag/v15.1.0) more than 20 months ago. We should upgrade to use [latest version 16.2.0](https://github.com/facebook/react/releases) for React and ReactDOM. 

React is something that is core to our application which handles all the rendering and mounting and is a crucial part of how UI performs in real-life. We should definitely see significant performance improvements because of the core rewrite and the [new fiber architecture](https://github.com/acdlite/react-fiber-architecture).

Also, the size of react package has decreased drastically to [5.1kb](https://bundlephobia.com/result?p=react@16.2.0) from [21.2kb](https://bundlephobia.com/result?p=react@15.1.0) which is like 4x reduction.

React's API has been pretty stable and the upgrade should be easy enough. The steps I can think of for the moment are:
- [x] Skim through all the release notes of React, ReactDOM versions from [15.1.0](https://github.com/facebook/react/releases/tag/v15.1.0) till [16.2.0](https://github.com/facebook/react/releases/tag/v16.2.0)
- [x] Make a note of all the breaking changes, depreciations.
- [x] Fix our codebase for the breaking changes.
- [x] Trace dependencies that have peerDepedencies with React < 16 and update them. 
- [x] Build and test the app locally with dev and in production environment.

**Comment by dhruvdutt** [comment]
I've also started working on it. Please assign it to me.

**Comment by catarak** [comment]
go ahead and work on this! if there are any other packages that would make sense to upgrade along with react, go ahead and update those in your PR as well. this upgrade seems very worth it.
