### ISSUE TITLE
save and download?

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#517]
At the moment, if you make a change to your code and then click "download" what downloads is the latest save and not the latest code. I think that download should probably trigger an "auto-save" so that it's really "save and download". . .thoughts?

Also, it might be useful to name the zip file with a timestamp, i.e. `project_yr_mm_dd_time` if a project is downloaded multiple times it allows for some baby steps into version control?

**Comment by catarak** [comment]
both of these are great ideas and not hard to implement!

**Comment by shinytang6** [comment]
l'm on it :)
