### ISSUE TITLE
Dropdown for navbar (e.g. `file`, `edit`, etc) gets stuck in firefox

### ISSUE THREAD

**Issue by joeyklee** [processing/p5.js-web-editor#525]
#### Nature of issue?

- [X] Found a bug

#### Details about the bug: 

- Web browser and version: FireFox
- Operating System: MacOSX 10.12.6  
- Steps to reproduce this:

In firefox, the nav for the  `file`, `edit`, `sketch`, and `help` get stuck. If you click on the name of the nav button or the carrot 🥕, the menu doesn't close. Only if you click out of the menu onto another nav button does the currently selected menu close. 

It currently works in Chrome ✨

<img width="1457" alt="screen shot 2018-02-07 at 15 31 29" src="https://user-images.githubusercontent.com/3622055/35940190-59792366-0c1c-11e8-9671-f10ff8f97d9e.png">

**Comment by himanshuc3** [comment]
Doesn't work in Safari v11.0.1 ( macOs v10.13.1 ) either.
