### ISSUE TITLE
Add Arduino sensor data connection example (completed)

### ISSUE THREAD

**Issue by jywarren** [processing/p5.js-web-editor#529]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:

I wrote an example sketch for connecting to an Arduino (read-only, although two-way is possible) to collect live sensor readings and plot the (crudely) on the canvas. It works through an audio connection using WebRTC, so you can connect an audio cable to pin 3 and ground of an Arduino, load up [this sketch](https://create.arduino.cc/editor/jywarren/023158d8-be51-4c78-99ff-36c63126b554) or something based on it, and start receiving data.

To make testing easier, I've included a link to a YouTube video of recorded sensor data as audio: https://www.youtube.com/watch?v=GtJW1Dlt3cg

The sketch is here and includes some links to the Arduino code, the video, and documentation, but it's pretty simple to start with:

https://alpha.editor.p5js.org/jywarren/sketches/rkztwSt8M

I've heard from @catarak that folks are interested in doing more Arduino work in p5js, and I hope this helps -- we're certainly interested in this over at @publiclab (non-p5js video of an Arduino connected to a browser here: https://www.instagram.com/p/Be6BwwchwRR/)

I'd love to have this featured as an example and am happy to put in extra work if needed! Thanks for p5js and the web editor, both amazing projects!! 🙌

**Comment by catarak** [comment]
this is awesome! i'm not sure what the best place to link to this would be, thoughts @lmccart and/or @shiffman?

**Comment by shiffman** [comment]
This is wonderful! I think if you package it up as a library with documentation for p5.js specifically then it could be considered for listing on [the p5.js add-ons page](https://p5js.org/libraries/). The repo for the site is here: https://github.com/processing/p5.js-website/

**Comment by jywarren** [comment]
@shiffman -- cool! Thanks! I submitted a PR over there, should I close this @catarak? If accepted over there, would the example get included in the web editor too? Just curious!

**Comment by catarak** [comment]
it would get added! there's a script in the web editor repository that scrapes all of the examples from github and uploads them to the editor. and yes, probably makes sense to close this issue 😸

**Comment by lmccart** [comment]
thanks @jywarren this is great!
