### ISSUE TITLE
Support for Rivescript

### ISSUE THREAD

**Issue by pfe1223** [processing/p5.js-web-editor#534]
#### Nature of issue?

- [x] Existing feature enhancement

#### Feature enhancement details:
I work in education, and I can think of several ways to use Rivescript (specifically chatbots from Dan Shiffman's Coding Train YouTube page) in the classroom. However, the P5 web editor tells me that JS, JSON, CSS, TXT, or CSV files are allowed. Could file support be upgraded to allow for files with the .rive extension? Thanks in advance.

**Comment by catarak** [comment]
I don't know anything about Rivescript! How do these files get embedded in a web page? Are they compiled to Javascript? Right now there's not a system in place for compiled files, i.e. Coffeescript, SCSS/Sass, and so on.

**Comment by pfe1223** [comment]
I am not sure if I can answer you question about how the files are embedded. Here is the about page for the project.

https://www.rivescript.com/about

I assume they get compiled. Are compiled files something that will be added, or is it a very low priority? Thanks for your help.

**Comment by shiffman** [comment]
@pfe1223 Does it work if you make a `txt` file and load that with the RiveScript code. The RiveScript files are just plain text so this may be a fine solution?

**Comment by pfe1223** [comment]
@shiffman It works when using the .txt extension. Thanks so much for your help.
