### ISSUE TITLE
Autocomplete brackets

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#55]
I think this is a CodeMirror plugin, so it shouldn't be too hard.

**Comment by shiffman** [comment]
I'm not 100% convinced we should have this as I've seen this feature cause confusion in the context of a zero-experience-first-day workshop.  I'm loathe to have zillions of preferences but I might have this something that a user can enable, but off by default.   

Or maybe it's such a standard now with text/code editors that I'm wrong here.

(For reference, I'll note the p5 desktop editor does include this feature, but the Processing PDE does not.)

**Comment by catarak** [comment]
I know that in Sublime Text it is included by default, but I agree with you, that it can be confusing for beginners. I've gotten some feedback from users (with a programming background) that they would like this feature, but I'll table this for now and see if I get more feedback about it.

**Comment by lmccart** [comment]
I could go either way on this. I like the autoclose brackets but I am not a beginner programmer, I'm fine to leave them out for now and re-evaluate later.
