### ISSUE TITLE
Implement current responsive designs

### ISSUE THREAD

**Issue by himanshuc3** [processing/p5.js-web-editor#550]
- [x] Feature enhancement

Possible reasons:
- [ ] No meta tags added
- [ ] No media queries

I would like to take up this issue.

**Comment by catarak** [comment]
There are some designs for this which are on Zeplin! It appears to be published to the [Scene View](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3) but the responsive image isn't loading for me—is it working for you?

**Comment by himanshuc3** [comment]
If you talking about p5-js-responsive-handling image, it is loading in carousel/gallery view.

**Comment by catarak** [comment]
yes, great!

**Comment by himanshuc3** [comment]
There are no designs for mobile screen sizes on zeplin. Although most of the work would be done on the desktop, mobile screens could be used to most probably view some sketches or do minor editing.

**Comment by catarak** [comment]
We had decided that views for smaller screens, i.e. Chromebooks, were a priority over mobile designs since folks don't code as much on their phones. Maybe there's some low-hanging fruit though that would make it easy to view code/sketches on mobile though?

**Comment by himanshuc3** [comment]
Chromebook resolution is close to the that of MacBook Air, on which the site looks fine. So, Should I close this issue?

**Comment by catarak** [comment]
Let's leave this open, and I'll change the title to "implement current responsive designs."

**Comment by birgere** [comment]
A lot of schools use iPad. We would love responsivnes for this screen size. But I recommend using media queries for width (not for device-width) (https://www.sitepoint.com/media-queries-width-vs-device-width ) and to use em as width unit.

**Comment by catarak** [comment]
definitely agree about using media queries! i've never seen code that uses em for the width unit in media queries—what are the benefits of doing it that way?

**Comment by himanshuc3** [comment]
em as width unit for fonts, div widths?

**Comment by birgere** [comment]
Percentages is a good relative unit för fonts and widths!

**Comment by himanshuc3** [comment]
So what do you exactly mean when you say that "Em units is a good way to go for media queries". How does it really have a benefit vs percentages?

**Comment by birgere** [comment]
For media queries you have to use a unit to define the breakpoint for the query.
Percent is not a valid width for the actual media query. The width of the screen cannot be 50% of itself, It is always 100%.
But percentages is good for for many other purposes, such as width on divs or max-width on img.

**Comment by himanshuc3** [comment]
Isnt the breakpoint usually defined in terms of pixels.

**Comment by birgere** [comment]
As I said, it can be done width px, but there are good reasons to use em instead.
