### ISSUE TITLE
Move examples username and password to .env file

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#555]
#### Nature of issue?

- [X] Found a bug

#### Details about the bug: 

- Web browser and version:  N/A
- Operating System:  N/A
- Steps to reproduce this:

the file `server/examples.js` contains the p5 username and password. this should be moved to environment variables so that any user can't login to this account!

**Comment by himanshuc3** [comment]
There probably are some linting issues with the PR, I could work them out and submit this thing. What do you say @catarak .

**Comment by catarak** [comment]
go ahead! i also just noticed that i had started a code review on that PR and never submitted it—just did though!
