### ISSUE TITLE
Make saving more user-friendly

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js-web-editor#560]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:

1. Saving file through ctrl+s when user is unlogged doesn't popup the ErrorModal.
2. Although Save option is diabled when the user is not the owner of the sketch, l think it  will be better if another ErrorModal pops up when using ctrl+s ?

**Comment by shiffman** [comment]
Agreed, this is a great idea!

**Comment by catarak** [comment]
agreed, sounds great!

**Comment by catarak** [comment]
just looked at what happens on codepen—if you hit command/ctrl + s it automatically forks the sketch. does that make sense?

**Comment by shinytang6** [comment]
also tried that and agree with you now:)
