### ISSUE TITLE
Add character limit to sketch name - Back end validation

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js-web-editor#568]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

name a project with special characters and try to donwload.
some of them will cause problem, e.g. &,|...

**Comment by catarak** [comment]
this is two things, right? 1. sketch names need a length limit (i don't know what an appropriate character limit is) and 2. sketch names need to be... url encoded? escaped somehow? not sure.

**Comment by himanshuc3** [comment]
@shinytang6 Can you provide an example. I tried a couple of them including &, | and when downloading the sketch, & is named and, | - or .

**Comment by shinytang6** [comment]
@himanshuc3 What you listed is the problem:)

**Comment by himanshuc3** [comment]
But what's the problem if the name of the file changes. It downloaded without any errors.

**Comment by shinytang6** [comment]
it doesn't matter with the content, should download the project in what you name.

**Comment by GaurangTandon** [comment]
@catarak Is anyone working on this issue? If not, then I'd like to take it up :) I plan to follow the advice given on [this post](https://superuser.com/questions/358855/what-characters-are-safe-in-cross-platform-file-names-for-linux-windows-and-os) for generating file names.

I plan to either:

1. generate file names based on the platform the user is using when they download the sketch (so same sketch can have different file names when downloaded on Windows/Linux) (also fall back to safer Windows naming when OS is not Windows/Mac/Linux)
2. generate safe cross platform file names (i.e. like Windows) every time for consistency's sake.

Would you suggest anything else? I prefer the second option. I can also display a toast message every time a restricted character is trimmed out from a file name.

**Comment by catarak** [comment]
i suggest the latter. i don't think it makes sense to change the sketch titles as they are in the editor, other than giving them a length limit; rather, i think the sketch titles should be escaped only when they are downloaded and translated to the name of a zip file, as this is the only time the sketch title affects this.

**Comment by catarak** [comment]
The zip file is generated on the fly, so when a browser window requests that url, it generates the zip file. The entry point, server-side, is here: https://github.com/processing/p5.js-web-editor/blob/master/server/controllers/project.controller.js#L332

**Comment by GaurangTandon** [comment]
So, the problem here is that the first part of the file name (before the timestamp) is generated using [`slugify`](https://www.npmjs.com/package/slugify), which is too restrictive in what it allows. I noticed that even Chinese characters, which are perfectly valid in both URLs ([example URL](https://www.key-shortcut.com/en/writing-systems/%E6%96%87%E5%AD%97-chinese-cjk/cjk-characters-1/)) and file names, are completely removed. Try `文字` as the sketch name for example.

I'll send in a PR.

**Comment by catarak** [comment]
there are TWO issues here, not just one:
- [ ] sketch names need a maximum length
- [ ] file names need to work with Mac/WIndows/Linux/etc file systems.

**Comment by catarak** [comment]
1. I looked at some other online code editors for limit lengths:
    - CodePen: no length limit
    - glitch.com: 51 characters
    - jsfiddle: 256 characters
    - Codesandbox: no length limit

256 seems like it's a good starting point? maybe smaller than that makes sense?

2. I think this check should be done both client and server side—on the server this would be done in models/project.js, and client side on the project input form.

**Comment by GaurangTandon** [comment]
On an average use case, I think names would be like `Lab 25th January 2019 - Demonstrating recursive functions with colors` that's about 60-70 characters. Thus, at max, even 128 chars seems more than enough for most cases. However, before setting out to impose a limit, I would first want to make sure what percentage of existing sketches would be impacted by this length limiting, and minimize the damage thereof.

**Comment by catarak** [comment]
let me do a query on the db...

**Comment by GaurangTandon** [comment]
Perfect, I'll try and get the length limit of 256 added into the code!

**Comment by catarak** [comment]
the OS issue was fixed, but adding a project name limit would also be good to add.

**Comment by siddhant1** [comment]
Will send a pr to close this

**Comment by shakeabi** [comment]
@siddhant1 I don't think a front-end check would cut it. You must also include a backend validation.

**Comment by josephmwells** [comment]
I'm going to try and tackle this. 

Quick question, can we just use mongoose validators such as `minlength`  and `maxlength` found [here](https://mongoosejs.com/docs/schematypes.html#string-validators) ? These will throw an error which can be caught and sent back to the client. (I haven't checked to see how validation errors are currently being handled.)

**Comment by catarak** [comment]
@josephmwells using the validators makes sense to me! Also for this issue, it is referring to specifically the sketch title. It would be a separate issue/PR for the sketch files.
