### ISSUE TITLE
Add authorization to specific routes

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#569]
#### Nature of issue?

- [X] Existing feature enhancement

#### Feature enhancement details:
Certain routes should not be accessible by all users! One that comes to mind is a user's settings (`/<username>/settings`) and a user's assets (`/<username/assets`). Maybe these routes should not include the username and just use the user that it stored in the cookie? Or they should redirect to `/` if a user who is not logged in as the `<username>` tries to navigate to one of these routes. The former appears to be what most websites do.

**Comment by himanshuc3** [comment]
If I may ask, is the file structuring done according to mern.io.

**Comment by catarak** [comment]
yes, that is the inspiration!

**Comment by catarak** [comment]
server-side, this project uses a library called `passport` which adds some `node`/`express` middleware magic 🔮and if a user is logged in, the user is stored in `req.user`. so you could compare the `<username>` in the route to `req.user.username`. another option would be to remove the username from the route, and determine the user from the cookie (just check `req.user.id`).

**Comment by migom6** [comment]
@catarak 
what's the progress? should I take this issue?

**Comment by catarak** [comment]
no progress, feel free to take it!

**Comment by migom6** [comment]
@catarak @shiffman 
Does this **_/\<username>\/settings_** exists ? if not should this route be created ?

**Comment by catarak** [comment]
it does exist. i was thinking that this route should be moved to just `/settings` and the assets one should be moved to just `/assets` and then we can avoid this authorization issue all together.
