### ISSUE TITLE
Different view for media files in editor

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#57]
Right now, for S3 hosted files, the editor just silently fails. It would be cool if info could be displayed about the files, but for now, just an error that these files can't be edited.

**Comment by REAS** [comment]
A thought, I wonder if there's something we can learn about the interface for this from Scratch or Director. 

![castwindowgraphical](https://cloud.githubusercontent.com/assets/677774/20539827/5a78983c-b0ab-11e6-83b3-ac6ef5dd0aff.gif)

**Comment by catarak** [comment]
To differentiate this from #196, this ticket addresses, for example, the situation in which a user clicks on an image or a sound file in the sidebar--what should the area of the editor where the text editor is look like? It would be cool if there were a few different designs, based on the MIME type of the file.
