### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by himanshuc3** [processing/p5.js-web-editor#573]
- From the beginner perspective, it could help them start faster.
- It helps organize code, find things faster and therefore makes finding bugs easier.

Starting from the root. This Issue starts by adding some bits of comments in index.html page. More issues will follow regarding documentation from my side. It would be providing me with more depth understanding of code.

**Comment by catarak** [comment]
awesome! i tried to link to a lot of the conventions i'm following in the README but this could be expanded.  could be added to `contributing.md`?

**Comment by himanshuc3** [comment]
Sure. Also, is the convention used here following the boilerplate by MERN.io. If it is:
- Is it strictly followed or some custom rules applied.
