### ISSUE TITLE
Remove startAccessibleSketch() 

### ISSUE THREAD

**Issue by lm-n** [processing/p5.js-web-editor#585]
#### Nature of issue?

- [ ] Found a bug
- [X] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:
Remove `startAccessibleSketch` from reducer. 

@MathuraMG https://github.com/processing/p5.js-web-editor/pull/583

**Comment by parteekcoder** [comment]
hey @raclim why do we want to remove `startAccessibleSketch()`

Please tell me so that I can solve this issue in the best way possible

**Comment by divyansh-prks** [comment]
can you please more elobrate it ?
