### ISSUE TITLE
Cant close saving error dialog

### ISSUE THREAD

**Issue by BlinfoldKing** [processing/p5.js-web-editor#589]
#### Nature of issue?

- [x] Found a bug

#### Details about the bug: 
I cannot close the modal that show up when i'm trying to save while not logged in

- Web browser and version: Chromium (Version 64.0.3282.140), Firefox (58.0.2), Google Chrome (V63)
- Operating System: Ubuntu 17.10, Windows 10
- Steps to reproduce this:
press Ctrl+S while you are not logged in

**Comment by catarak** [comment]
thanks for submitting this!

**Comment by shinytang6** [comment]
it was fixed in #578 :)

**Comment by himanshuc3** [comment]
Yeah. This one is fixed. It should be closed.
