### ISSUE TITLE
Alpha editor in Spanish

### ISSUE THREAD

**Issue by montoyamoraga** [processing/p5.js-web-editor#595]
#### Nature of issue?
-  New feature request

#### New feature details:

I would love to have buttons "EN/ES" for toggling language between English and Spanish

Here is the complete translation, of the menu and every text I could find =)

File
Archivo

New
Nuevo

Save
Grabar

Examples
Ejemplos
(include examples in Spanish)

Edit
Editar

Tidy Code
Ordenar código

Find
Buscar

Find Next
Buscar siguiente

Find previous
Buscar anterior

Sketch
Bosquejo

Run
Ejecutar

Stop
Detener

Start Accesible
Iniciar accesibilidad

Stop Accesible
Detener accesibilidad

Help & Feedback
Ayuda y comentarios

Keyboard Shortcuts
Atajos

Reference
Referencia

About
Acerca de

Welcome
Bienvenida

New to p5.js?
¿Empezando a aprender p5.js?

Examples
Ejemplos

Learn
Aprende

Resources
Recursos

Libraries
Bibliotecas

Reference
Reference

Forum
Foro

Feedback
Comentarios

Submit Feedback
Enviar comentarios

Via GitHub Issues
A través de GitHub Issues

If you're familiar with Github, this is our preferred method for receiving bug reports and feedback.
Si sabes usar GitHub, este es nuestro método favorito para recibir reportes de errores y comentarios.

Go to GitHub
Ir a GitHub

Via Google Form
A través de Google Form

You can also submit this quick form
También puedes llenar este cuestionario corto

Go to form
Ir al cuestionario

Auto-refresh
Auto-refrescar

Preview
Vista previa

Log in or Sign Up
Ingresa o registráte

Console
Consola

Settings
Configuración

General settings
Configuración general

Theme
Modo de visualización 

Light
Claro

Dark
Oscuro

High Contrast
Alto contraste

Text Size
Tamaño del texto

Decrease
Disminuir

Increase
Aumentar

Indentation amount
Cantidad de indentación

Decrease
Disminuir

Increase
Aumentar

Autosave
Grabar automáticamente

On
Activar

Off
Desactivar

Sketch Settings
Configuración del bosquejo

Security Protocol
Protocolo de seguridad

Serve over HTTPS
Usar HTTPS

Accesibility
Accesibilidad

Lint warning sound
Sonido de alarma Lint

On
Activar

Off
Desactivar

Preview sound
Probar sonido

Accessible text-based canvas
Lienzo accesible por texto

Used with screen reader
Uso con screen reader

Plain-text
Texto sin formato

Table-text
Tablero de texto 

Sound
Sonido

**Comment by catarak** [comment]
this is so awesome and thanks for doing this! i think next steps for this issue are
- [ ] include an i18n library
- [ ] move all of the text into a json file that maps ids to text
- [ ] change all of the text to id's and map them to the json file
- [ ] add UI to switch between languages

**Comment by montoyamoraga** [comment]
what about this one?
https://github.com/i18next/react-i18next
or this one?
https://github.com/yahoo/react-intl
i'm down to try anyone of them, i'm not familiar to react but happy to try stuff

**Comment by catarak** [comment]
cool! i can take a look as well.

**Comment by scollovati** [comment]
Yeah, localisation would be a great feature.
When it'll be ready I can localise strings in italian language (it_IT) :)

**Comment by montoyamoraga** [comment]
@lm-n hey! thankns! feel free to do it, they are the first post of this thread.
let me know if you see any mistake

**Comment by lm-n** [comment]
@montoyamoraga Here are some of my comments:

- "Reference: Reference" creo que deberíamos de traducir reference a "referencia o documentación"
- "Log in or Sign Up - Ingresar o registrarse" me parece que estás conjugando todas las otras acciones en la traducción a segunda persona "tú" y no "usted", si es así, entonces por consistencia, debería de decir: "Ingresa o regístrate" 
- "General settings" actualmente no tiene traducción. Sugiero que sea "Configuraciones Generales"

Here I propose other translations that I believe are more accurate to the accessibility features that we have been working on: 
- "Theme: Color" Creo que es importante no traducir "Theme" a "Color" porque "Theme" es más que una cuestión de preferencia estética o de color, especialmente para personas con problemas de vista o discapacidad visual. Por tanto sugiero que se traduzca a "Modo"
- "Lint warning sound: Sonido de alarma Lint" sugiero "Sonido/alarma de errores comunes"
- "Accessible text-based canvas: Lienzo accesible por texto" sugiero "Lienzo de texto accesible"
- "Used with screen reader: Uso con screen reader" sugiero "Para usarse con un lector de pantalla"
- "Plain-text: Texto plano" sugiero "Texto sin formato"
- "Table-text:Texto tabla" sugiero "Tablero de texto"

**Comment by montoyamoraga** [comment]
@lm-n hola!
I added most of your comments to my original post,
I still think that Reference should be Reference
I know that someone knew might not understand it at first, but Reference 
is the standard nomenclature, I rather keep it, what do you think?
The same with Lint, it's a standard and I rather be specific.
And I am still unsure about Theme, what do you think of "Modo de visualización"?

**Comment by lm-n** [comment]
@montoyamoraga sounds good! Sorry for my late answer. I've been working on the accessibility stuff and forgot about this thread. I think it might be a good idea to come up with some community translation guidelines. And yup, totally agree with "Modo de visualización". Also a random thought, have you considered moving all translations to transifex https://www.transifex.com/ ? It works with github and CI and makes translating content super easy, might be useful for the folks working on the Chinese language version of the website and for future edits and languages.

**Comment by catarak** [comment]
just fyi i haven't had a chance to make any progress on this as i am focusing on a permanent/scalable hosting solution.

but transifex looks cool! do they have a lower price/free open source option?

**Comment by lm-n** [comment]
Yup! It’s free for open source projects! 

“We are proud and humbled to be hosting the largest Open Source translation community in the world. We offer Transifex for free to Open Source projects that have no funding, revenue, and/or commercialization model. If you have a question whether your organization qualifies for our Open Source program, please contact us.”

**Comment by catarak** [comment]
this has been merged and deployed 🎉 🎉 🎉

**Comment by montoyamoraga** [comment]
YES @catarak

**Comment by lm-n** [comment]
Thank you 🙏 🙏  @catarak @oruburos

**Comment by oruburos** [comment]
> Thank you 🙏 🙏 @catarak @oruburos

thanks to @andrewn  for his patience.
