### ISSUE TITLE
Navigation dropdown menus are not accessible by keyboard

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#597]
#### Nature of issue?

- [X] Found a bug

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Mac OSX
- Steps to reproduce this:

1. Hit `tab` to focus on one of the navigation menu options (e.g. 'File')
2. Hit `enter` to open the dropdown
3. Hit `tab` again to cycle through the options of the dropdown, except the dropdown closes. 

I'm pretty sure at one point this worked, as I spend a lot of time researching how to make dropdowns keyboard accessible and perfecting it.

**Comment by himanshuc3** [comment]
It's working in my local environment! Reproduced it as per your instructions @catarak.

**Comment by catarak** [comment]
hmm, as in you're able to tab through and select "new", "open", etc.?

**Comment by himanshuc3** [comment]
No, i am able to tab from between menu items but not within sub-menu items.

**Comment by catarak** [comment]
Okay, same for me. The issue is not being able to tab into submenu items.

**Comment by Neilshweky** [comment]
I would like to tackle this issue, or a similar issue that pressing `tab` cycles through all of the different tabs

**Comment by catarak** [comment]
go for it!

**Comment by Neilshweky** [comment]
I submitted a pull request! Let me know what you think!

**Comment by himanshuc3** [comment]
Is this solved @Neilshweky @catarak

**Comment by Neilshweky** [comment]
Hi! I'm sorry I haven't forgotten about this I just have so much work right now (as the semester is nearly over).... I definitely should be able to work on it this week though, I'll keep you posted! Thanks!

**Comment by catarak** [comment]
no worries ✨

**Comment by migom6** [comment]
what's the status?

**Comment by Neilshweky** [comment]
Hey! I'm looking into other ways of fixing this issue!

**Comment by dhruvdutt** [comment]
@catarak This can be closed I guess.
