### ISSUE TITLE
Detailed Git workflow

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js-web-editor#602]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### New feature details:

Should we add a more detailed git workflow in contributing.md like https://github.com/processing/p5.js/wiki/Development do? New contributors are always confused about the git :)

**Comment by shinytang6** [comment]
Although l don't think the wiki is good enough? Do you guys use this method?

**Comment by shinytang6** [comment]
Will do that tomorrow :)

**Comment by lmccart** [comment]
i found this wiki page which might be useful. it could be edited to include any info you feel is missing: https://github.com/processing/p5.js/wiki/Preparing-a-pull-request

**Comment by shiffman** [comment]
I also recently made this video tutorial. I have yet to publish it but in case it is helpful at all. (It's more specific to contributing to p5.js.)

https://www.youtube.com/watch?v=Rr3vLyP1Ods
