### ISSUE TITLE
"My Account" dropdown menu doesn't work

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js-web-editor#604]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

1. Open a new sketch
2. Log in
3. Click "My account" dropdown

**Comment by extrajordanary** [comment]
I'm on Chrome, and the dropdown opens for me, and I can see the url previews for each link (except logout) but when I click any button, nothing happens. I have to manually enter the urls into the browser to get there.

**Comment by catarak** [comment]
I'm also able to reproduce this.
