### ISSUE TITLE
relocation for "Autocomplete for the p5.js web editor" wiki page

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#605]
we're doing some reorganization of the p5.js wiki (essentially removing it and putting all the content in more easily indexed places). I'm wondering about this post on [autocomplete](https://github.com/processing/p5.js/wiki/Autocomplete-for-the-p5.js-web-editor) from @kaganjd's 
gsoc project. it seems most related to this repo and should probably be kept here rather than in the p5.js repo. is this assumption correct? is there a good place I can put it?

**Comment by catarak** [comment]
maybe, for now, we can add this to the web editor wiki, and reevaluate in the near future?

**Comment by lmccart** [comment]
👍 may I go ahead and drop it there?

**Comment by catarak** [comment]
go for it!
