### ISSUE TITLE
Privacy Policy, Terms of Service, Community Guidelines

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#609]
#### Nature of issue?

- [X] New feature request

#### New feature details:

We currently don't have a Privacy Policy or Terms of Service—we probably need need these for the public release, right?

**Comment by shiffman** [comment]
I'm happy to research / help think about this. Any suggestions from anyone as to where to start welcome!

**Comment by catarak** [comment]
References:
- [Glitch](https://glitch.com/legal)
- CodePen
  - [Privacy Policy](https://blog.codepen.io/legal/privacy/)
  - [Terms of Service](https://blog.codepen.io/legal/terms-of-service/)
  - [Code of Conduct](https://blog.codepen.io/legal/code-conduct/)
  - [Licensing](https://blog.codepen.io/legal/licensing/)
- OpenProcessing
  - [Community Guidelines](https://www.openprocessing.org/home/comg)
  - [Terms of Service](https://www.openprocessing.org/home/tos)
  - [Privacy Policy](https://www.openprocessing.org/home/prp)

We could also create an email address for specifically reporting abuse. 

We should also document how to delete accounts/sketches so that someone besides me can do this.

**Comment by catarak** [comment]
I started working on the [Terms of Service on a gist](https://gist.github.com/catarak/bafb46eca3ae128fc1e2298e63be25b), I'm still working through it though!

**Comment by ashu8912** [comment]
Hey @catarak  is this done
