### ISSUE TITLE
onUpdateLinting timeout length

### ISSUE THREAD

**Issue by omnikrll** [processing/p5.js-web-editor#61]
The onUpdateLinting function in the CodeMirror config currently has a timeout of 2000 ms. With the warning sounds on, it's a little confusing for the alert to sound that long after you've moved on, and after the line style with the red highlighting has been applied.

Would it be possible to either call this.beep.play() to the same function that applies the red highlight to the line with the linting error, or to add a UI control to set that timeout length?

**Comment by catarak** [comment]
@MathuraMG I think you told me a reason for the timeout being this long but I can't remember.

**Comment by omnikrll** [comment]
Yeah I figured there was probably a reason for the timeout being that long- maybe to give a screen reader time to catch up?

Personally, with my particular vision disorder (I'm legally blind only in one eye) I don't rely on a screen reader as much as I do inverting the colors of the display. I was playing with it, and setting the timeout to 800ms instead of 2000 felt much more usable for my particular use case.

**Comment by MathuraMG** [comment]
If the timeout was 200ms, the alert beep seemed way to insistent. So we just increased the time so that it seems usable for people who are just learning to code as well.
(cc @ CleezyITP)

**Comment by omnikrll** [comment]
@MathuraMG Yeah 200ms sounds way too quick- like, it wouldn't even give you time to put in a closing bracket for a function.

On the other hand, 2000ms might make more sense both for people who are new to coding, not especially quick typists (maybe suffer from repetitive stress injuries?), or rely more heavily on screen readers than I do.

Would a UI element to set the timeout make sense, since this could vary from user to user?
(cc @catarak @CleezyITP)

**Comment by catarak** [comment]
I'd like to have as few preferences as possible, as I think having lots of configuration options can be overwhelming for beginner coders. I think our options are

1. Put in a UI slider, with some reasonable limits. 
2. Put in a UI slider, do some user testing and see what most people like, then pick a value and hide the slider.
3. Pick a value, do some user testing, and decide whether it's good or needs to change.

**Comment by MathuraMG** [comment]
Option no 3 seems highly practical - I agree with @catarak that too many choices can be overwhelming. Also, we will include this in our test scenarios. (+@cleezyITP)

**Comment by omnikrll** [comment]
Option 3 is probably the quickest for dev time. In the long run, if there's any kind of "advanced" preferences, maybe users could customize it in there?

**Comment by catarak** [comment]
I'm trying to close out stale tickets. There's not really any active work to be done on this one, and it can be reopened if anyone wants to change this feature.
