### ISSUE TITLE
Unable to sign out of editor.

### ISSUE THREAD

**Issue by Laphatize** [processing/p5.js-web-editor#610]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### The Issue itself
The issue is that I'm unable to sign-out of the editor.
I'm currently using the Chrome browser (64bit) on macOS.

I have a video of the issue.
https://youtu.be/BPEqGU92jxk

**Comment by shinytang6** [comment]
It's similar to #604 :)
