### ISSUE TITLE
Print dialog appears when calling print on undefined variables

### ISSUE THREAD

**Issue by aferriss** [processing/p5.js-web-editor#614]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

Calling print(x) with an undefined variable brings up the browser print dialog. I noticed that there was a similar issue over on https://github.com/processing/p5.js-web-editor/issues/474 but that seemed to be more focused on calling print outside of setup or draw. In this case, it just happens if a variable becomes undefined.

One of my students stumbled across this by accidentally providing the dist function without enough parameters `let x = dist(10, 35)`, which ended up returning undefined.

- Web browser and version: Chrome/Firefox/Safari
- Operating System: MacOSX 10.12.6
- Steps to reproduce this: [Alpha editor link](http://alpha.editor.p5js.org/aferriss/sketches/ByM_3PEjf)

**Comment by catarak** [comment]
thanks for submitting this! i want to try this in a different code editor to make sure this is not an issue with p5.js but with the editor.

**Comment by catarak** [comment]
posted in processing/p5.js#2765

**Comment by aferriss** [comment]
Thanks! I should have checked there first >_<

**Comment by catarak** [comment]
no worries! it's not always easy to figure out an issue is with the editor or p5.js itself.
