### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by himanshuc3** [processing/p5.js-web-editor#616]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

I think it could be discussed, if needed or not!
Just to give a bit of importance and well documented history of the project, we could setup Continuous Integration!
Suggestions would be most welcomed.

**Comment by catarak** [comment]
this is technically set up (you'll see the `.travis.yml` file in the repository). however, i don't have the code set up so that when new code is merged to master, it's deployed to the server/servers/etc. this is waiting on figuring out a new hosting situation.

**Comment by himanshuc3** [comment]
Gotcha.

**Comment by shinytang6** [comment]
Since CI only checks lint problem now, l am thinking maybe we can check for lint errors before commiting code :thinking:

**Comment by catarak** [comment]
yeah! it would be cool to have the CI do other stuff but i figured it would be a good starting point. at least now i don't have to manually lint PR's and tell folks to fix the linting errors.

**Comment by catarak** [comment]
i have done this 🌈
