### ISSUE TITLE
print(); can lead to browser printer dialog opening

### ISSUE THREAD

**Issue by mrmaarten** [processing/p5.js-web-editor#618]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version:  chrome with online editor  alpha.editor.p5js.org
- Operating System: windows 10
- Steps to reproduce this:

It happens with the online editor alpha.editor.p5js.org
I cannot reproduce this from scratch but it has happened to me many times. I have also seen it happen with others.

the code is a simple print(10_example); statement leading to the browser printer dialog box to open. If the sketch is on auto-refesh, you cannot escape from it.

#### New feature details:

**Comment by himanshuc3** [comment]
Maybe its because of incompatible version of p5.js.

**Comment by mrmaarten** [comment]
Thanks for the suggestion.

I was using: 

  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/addons/p5.dom.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/addons/p5.sound.min.js"></script>

seems the latest version..

**Comment by catarak** [comment]
if you are using `print()` and the value you are passing to it is `undefined`, then it will open the print dialog. i'm going to close this, and if you have a specific example in which you try to `print()` a string/object/class etc. and it opens the print dialog, feel free to reopen this.

**Comment by fronofro** [comment]
This is still causing me some issues. Using `print()` with undefined values creates an infinite loop of print dialog boxes from the browser that you cannot stop if it is in the draw function. 

If you saved your work prior to running it you can hit back on the browser and then re-open the file and change it before running. I accidentally typed `print()` and it was not an ideal experience. Maybe this should not be the action of the `print()` method without defined values?

**Comment by catarak** [comment]
@fronofro i hear you, that's annoying! your request actually belongs in the p5.js repository itself, not the web editor repository, as `print()` is defined by p5.js.

**Comment by fronofro** [comment]
@catarak ok I will post it there
