### ISSUE TITLE
How to install p5 in Max computer？

### ISSUE THREAD

**Issue by 1014493111** [processing/p5.js-web-editor#626]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### New feature details:

**Comment by shinytang6** [comment]
Do you mean installing p5.js or p5.js web editor>? lf you want to install p5.js web editor locally, just follow the README. For p5.js, [https://p5js.org/](https://p5js.org/) may help

**Comment by catarak** [comment]
this is the place to report bugs or feature ideas with the p5.js web editor. for help with p5.js, see https://p5js.org/get-started/, or https://forum.processing.org/two/categories/p5-js.
