### ISSUE TITLE
(feature discussion): Adding a togglable grid overlay over/inside canvas element to give a sense of coordinates.

### ISSUE THREAD

**Issue by gdad-s-river** [processing/p5.js-web-editor#631]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

### Adding a togglable grid overlay over/inside canvas element to give a sense of coordinates.

While doing [the introduction to visual arts using p5js on kadenze](https://www.kadenze.com/courses/introduction-to-programming-for-the-visual-arts-with-p5-js-vi), my high school cousin asked me if I could request a feature on his behalf to enable a togglable grid overlay on / inside the canvas element to get a better sense of coordinates, especially for people trying out p5js for the first time with no prior programming background.

**Comment by catarak** [comment]
cool idea! could be useful and/or complicated with the p5.js transform functions (e.g. `translate()`, `scale()`). maybe this would make more sense as a p5.js addon library?

**Comment by gdad-s-river** [comment]
It would indeed! I'll give it a shot. Thanks! 💛
