### ISSUE TITLE
Uncaught ReferenceError: loopProtect is not defined

### ISSUE THREAD

**Issue by REAS** [processing/p5.js-web-editor#635]
In the alpha editor, a for loop is generating the error "Uncaught ReferenceError: loopProtect is not defined". We confirmed this behavior on two machines, both OS X. I was able to test multiple examples, and examples with multiple loops were working (see, the "Iteration" on the p5.js site), but when that example was modified to have a single loop, the error returned. Here's an example to test:

```
function setup() {
  createCanvas(720, 360);
}

function draw() {
  for (var i = 0; i < 10; i++) {
    rect(50, i * 10, 475, 10);
  }
}
```

**Comment by catarak** [comment]
this is also being reported in #633. will investigate!

**Comment by REAS** [comment]
Thank you @catarak. I confirm the `for` is working again.
