### ISSUE TITLE
Array issue with loop

### ISSUE THREAD

**Issue by Coach1** [processing/p5.js-web-editor#636]
I've been noticing that the loops I've been creating are no longer working in the p5js editor. I even opened up an old project that I had saved, and it's not working either. If you can please help me, that would be great! Thank you!
-->
![7 1 what is array issue with loop](https://user-images.githubusercontent.com/39306228/40069442-586b9ecc-5839-11e8-8a28-f7e7cf345199.PNG)

**Comment by meiamsome** [comment]
See #635 and #633

**Comment by catarak** [comment]
closing for redundancy of #635. but thanks for reporting this!
