### ISSUE TITLE
username + pwd doesn't work, email + pwd does

### ISSUE THREAD

**Issue by epar** [processing/p5.js-web-editor#637]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
- Web browser and version: Multiple 
- Operating System: macOS 
- Steps to reproduce this: When I try to login using username + pwd, I get "Invalid username or pwd" however, when I use my email address + pwd I do get logged in. I've checked triple checked my username and password when I put it in and tried multiple browsers with the same result. 

Probably be related to: #480 #481 #562 

#### New feature details:

**Comment by catarak** [comment]
thanks for submitting this! i'll do some digging. could have to do with whitespace or something like that.

**Comment by epar** [comment]
@catarak just FYI: there are no white spaces in either my username or password. Also, I haven't encountered this problem with my other account. Lemme know if you need more info!

**Comment by epar** [comment]
the username is _GenerativeDesignS18_ , I can also give you the pwd if that helps (email?)

**Comment by catarak** [comment]
i'm going to close this as a duplicate under #480, but it is definitely a priority to fix this!
