### ISSUE TITLE
Incorrect duplicate console information

### ISSUE THREAD

**Issue by shinytang6** [processing/p5.js-web-editor#644]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

1. Open a sketch
2. Generate errors or write some console commands e.g `console.log("xxx")`
3. Log in to your account again and run the sketch

And after that each time you login in, the console information will double unless you refresh the page.

**Comment by shinytang6** [comment]
l will try to fix it in #639

**Comment by catarak** [comment]
interesting bug, thanks for finding and documenting this!

**Comment by kjhollen** [comment]
I can't reproduce this one, so I'm going to close it! Probably got fixed with other things somewhere along the way. Thanks for reporting!
