### ISSUE TITLE
Broken image in verification email

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js-web-editor#649]
<img width="620" alt="screen shot 2018-06-15 at 19 06 21" src="https://user-images.githubusercontent.com/157106/41494846-464728e8-70cf-11e8-990d-3c065b56b3d5.png">

#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Browser, OS details: Google Chrome | 67.0.3396.87 (Official Build) (64-bit), OS | Mac OS X 10.13.5
- Steps to reproduce this: I signed up for a new account using my Gmail address.

As far as I can tell, the HTML points to https://alpha.editor.p5js.org/images/p5js-square-logo.png which is a broken URL.

**Comment by Vertmo** [comment]
I will try to fix this really quick (by reintroducing the logo at the correct url, which should fix the emails).

**Comment by catarak** [comment]
@vertmo go for it!

**Comment by Vertmo** [comment]
I think you should probably close this ^^

**Comment by catarak** [comment]
@Vertmo thanks for the reminder! i guess the 'fixes #issuenumber' syntax only works if it's a commit message, not if it's in the title of the PR.
