### ISSUE TITLE
Mobile Development

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#65]
Please file this in the much later department.  But since it came up in e-mail I thought I would note it here.  I'm thinking about how the IDE itself could be used for mobile development.  I'm thinking of a scenario like:
1. Type code on your desktop.  
2. Access a "mobile view" to see your sketch running on your mobile.
3. See the debug console of what you are running on mobile on your desktop.  (see https://jsconsole.com/)

**Comment by ghalestrilo** [comment]
@shiffman would love your opinion on the progress being made :)

Previewing the mobile layout:
- Checkout into the `develop` branch
- Run the command: `MOBILE_ENABLED=true npm start`
- Access the `/mobile` endpoint

**Comment by catarak** [comment]
@ghalestrilo let's instead set up the staging server so that we can have folks test mobile!

**Comment by catarak** [comment]
@ghalestrilo i just enabled the `/mobile` route on the staging server
