### ISSUE TITLE
Email verification fails

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js-web-editor#650]
<img width="575" alt="screen shot 2018-06-15 at 19 09 44" src="https://user-images.githubusercontent.com/157106/41494863-ae0b7b96-70cf-11e8-8ea1-16946b3fba0c.png">

#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Browser, OS details: Google Chrome | 67.0.3396.87 (Official Build) (64-bit), OS | Mac OS X 10.13.5
- Steps to reproduce this: I signed up for a new account using my Gmail address.

When I click on the "Verify Email" button or the link below it, it takes me to a page that says "Something went wrong". The link it sent me is https://alpha.editor.p5js.org/verify?t=33081704d89281c329756f9bd0494b649e0e04a6

**Comment by shinytang6** [comment]
And it seems that even though we do not verify the mail, users can also log in through the username

**Comment by catarak** [comment]
thanks for submitting this! i think this got implemented and then never used and then broke 😄i want to fix this for the public release so i'm gonna put it in that milestone.

**Comment by DeltaFlash** [comment]
Check your mail here https://sales.reply.io#1 in the "Email verification" section, frequent and possible reasons, these are minor failures in the mail server, but still check your mail is desirable

**Comment by catarak** [comment]
cool, thanks!

**Comment by dhruvdutt** [comment]
How can I replicate this?

**Comment by catarak** [comment]
@dhruvdutt i don't think i ever figured out the steps to reproduce. figuring that out would be super helpful!

**Comment by catarak** [comment]
i actually figured out what was causing this! the expiration date for the token wasn't getting set properly when re-sending a verification email. this will be fixed on master soon!
