### ISSUE TITLE
Cannot tab into file options menu

### ISSUE THREAD

**Issue by awarua** [processing/p5.js-web-editor#659]
#### Nature of issue?

- [X] Found a bug

#### Details about the bug: 

- Web browser and version: Chrome v67

- Operating System: MacOSX 10.12.6
- Steps to reproduce this:

In the web interface, click the down arrow to open the file options menu

![image](https://user-images.githubusercontent.com/92529/42005965-75ccdb04-7aba-11e8-80fa-8026f2452e87.png)

Click tab to tab to the first menu item 'Rename'. 
You will see the menu item highlight and then the menu closes. 

I believe that this is because in the `FileNode` component, there is an onblur event handler that closes the file options menu [https://github.com/processing/p5.js-web-editor/blob/9a0c0448844743d4d167d77f9763cddc05909b70/client/modules/IDE/components/FileNode.jsx#L124](#L124)

**Comment by catarak** [comment]
thanks for reporting this!

**Comment by AnkurIngale** [comment]
Is it still there?

**Comment by catarak** [comment]
@AnkurIngale yes, this is still a bug

**Comment by AnkurIngale** [comment]
https://github.com/processing/p5.js-web-editor/pull/891#issue-261372952 Please review.
