### ISSUE TITLE
fill( ) method causing script error in Alpha Editor.

### ISSUE THREAD

**Issue by gmaster350** [processing/p5.js-web-editor#660]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

Bug does not occur in locally hosted html pages.
Bug appears to occur only in the alpha editor.

- Web browser and version: Google Chrome 67.0.3396.99
- Operating System: Windows 10 64-bit
- Steps to reproduce this:  Use fill method anywhere.

script:

setup(){
    createCanvas(400, 400);
}

draw(){
    background(220);
    fill("red");
    ellipse(100, 100, 50);
}

console: 
Script error. (: line 0)

**Comment by catarak** [comment]
thanks for submitting this! I'm only seeing this error if I turn on the accessibility features, which means that this is an issue with [processing/p5.accessibility](https://github.com/processing/p5.accessibility). I looked in the issues for that repo and there's already an issue for this, processing/p5.accessibility#71. If you would like to turn this error off, go to Settings -> Accessibility -> Accessible Text-Based Canvas and uncheck all of the boxes.
