### ISSUE TITLE
When Auto-refresh on and start typing a loop sentence Browser crashes and changes are lost

### ISSUE THREAD

**Issue by maximorosales** [processing/p5.js-web-editor#662]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 
Chrome
- Operating System: 
Windows 10
- Steps to reproduce this:

It could hapends with any loop statement.
As Auto-refresh is on it wll try to execute the code while typing.
Writing something like:
for(let i-0; i<10;){}
It makes browser to crash and all changes done are lost.

**Comment by catarak** [comment]
thanks for reporting this! i think this is an issue with the loop-protect code, for some reason it is not catching the infinite loop!

**Comment by catarak** [comment]
hopefully will be fixed by #698

**Comment by catarak** [comment]
I'm going through and closing old issues/deduplicating them. I think this will be fixed by updating the `loop-protect` library (#698).
