### ISSUE TITLE
Feature suggestion: List p5 version in editor UI

### ISSUE THREAD

**Issue by j6k4m8** [processing/p5.js-web-editor#665]
#### Nature of issue?
- [x] New feature request

#### New feature details:
Would be very useful to list the p5 version somewhere (maybe Help→Version) so that it's easy to find and report. This editor's a great bug-reproducibility tool!

As is, I had to crawl through the iframe to find the appropriate p5 network request.

PS: Sorry about filing multiple issues today! I love p5 so so much :)

**Comment by catarak** [comment]
good idea! i think that this may be covered by the library management design (#4). there's actually an easier way to check it: you can look at the `index.html` file, which you can open by opening the file sidebar by clicking the ">" by the sketch title.

**Comment by j6k4m8** [comment]
....I can't believe I didn't think of that.

**Comment by catarak** [comment]
closing this, as i think it will be solved by #4.
