### ISSUE TITLE
Forum button links to old forum

### ISSUE THREAD

**Issue by TheWizardBear** [processing/p5.js-web-editor#671]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

(Though this might count as a bug?)

#### Details:

Clicking on "Forum", after clicking on "about" in the "Help & Feedback" drop-down, still sends you to the [old forum ](https://forum.processing.org/two/) rather than the [new one](https://discourse.processing.org/).

**Comment by catarak** [comment]
ooooh thank you! this is quick fix ✨
