### ISSUE TITLE
"Leave site?" dialog shows even after I save my work

### ISSUE THREAD

**Issue by KevinWorkman** [processing/p5.js-web-editor#675]
When I close the editor, I get a dialog:

Leave site?
Changes you made may not be saved.

This makes sense if I'm closing the tab while I have unsaved changes, but this message also appears if I save my work before closing the tab.

This makes me feel paranoid and like my work hasn't been saved. Maybe we should only show the dialog when there's unsaved work?

- Web browser and version: Chrome 68
- Operating System: Windows 10

**Comment by shiffman** [comment]
I came across this issue as well while live streaming. I think it is saving but just not registering that it is saved.

Here is a link to a spot in the video where it comes up:
https://youtu.be/wTDDsOZwdQY?t=4728

**Comment by catarak** [comment]
I have noticed this—I think it's related to #576 and how the files are compared. Someone started working on this in #658 but never got to finish it!

**Comment by catarak** [comment]
@KevinWorkman i just merged in a PR that will hopefully fix this (still building and deploying, will take ~10 min). let me know if you're still seeing this!

**Comment by kjhollen** [comment]
hey folks, I've been seeing this one in class this week. work is being saved as far as I can tell, but the unsaved indicator doesn't go away.

**Comment by catarak** [comment]
i noticed this in class today too! i had been working on an unsaved sketch for a few minutes, and then saved it, and then it still said unsaved.

**Comment by catarak** [comment]
I just noticed a consistent way to reproduce this!
1. Login to an account or be logged in to an account
2. Open an existing sketch
3. Hit Command + S or Click Save from File -> Save
4. Sketch now appears unsaved

**Comment by catarak** [comment]
I just tried my steps to reproduce and it's working okay for me. Think I may close this for now, and if it comes up again, just reopen.
