### ISSUE TITLE
Email verification seems to be broken

### ISSUE THREAD

**Issue by runemadsen** [processing/p5.js-web-editor#676]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

I have a bunch of students trying to sign up for the editor, and they are all getting "Something went wrong" when they go to the verification link. They can still log in, but the verification step is broken for most `@nyu.edu` addresses.

Screenshot:

<img width="1280" alt="screen shot 2018-09-05 at 2 38 44 pm" src="https://user-images.githubusercontent.com/192021/45075486-da536f80-b119-11e8-8e93-756b697d56a7.png">

**Comment by catarak** [comment]
Thanks for reporting this! I haven't been able to reproduce this yet, but I've been trying with my regular gmail account. I'll try with my NYU email and see if that does it.

**Comment by catarak** [comment]
Also reported in #650.

**Comment by catarak** [comment]
UPDATE (ugh): just tried with my NYU email and it worked. This feels like one of those scenarios in which it's broken for everyone except for me.

**Comment by catarak** [comment]
@runemadsen can you post at least one account that the verification isn't working on?

**Comment by badcat** [comment]
@catarak I can :) the account is /BadCat  
thank you.

**Comment by catarak** [comment]
this has not yet been fixed, but i'm going to mark this as a duplicate under #650.
