### ISSUE TITLE
Loadpixels / updatepixels combo causes drawing to stop

### ISSUE THREAD

**Issue by vixo777** [processing/p5.js-web-editor#678]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- Operating System: Windows 10
- Steps to reproduce this:

I have a sample here (https://editor.p5js.org/vixo777/sketches/H13tfrJOm) to test fading using loadPixels and updatePixels and progressively setting the pixels colors to the background color. The issue is that in the draw loop, only one line is displayed by the "randomLines" function, even when is called multiple lines.
Steps to reproduce (note that changing the pixels to background color is commented out on purpose. Feel free to uncomment to test): 
1. Run the sketch as is, only one line is displayed
2. Comment out the call to "fadeImage()" and run. Multiple lines are displayed
3. Uncomment out the call to fadeImage and comment out the calls to either loadPixels or updatePixels, Multiple lines are displayed. Uncomment the calls to both load and update pixels. Only one line is displayed.

It would seem as if there is something in the combination of loadPixels and updatePixels that causes any additional drawing not to show up.

Hope this helps. Thanks.

**Comment by vixo777** [comment]
Apologies. I believe this belongs in the p5 repo and not the editor.

**Comment by catarak** [comment]
@vixo777 no worries, and thanks for reporting!
