### ISSUE TITLE
File navigation UI bug

### ISSUE THREAD

**Issue by TheWizardBear** [processing/p5.js-web-editor#679]
**I found a bug** to do with the UI of folders and files in the file navigation section of the webpage.

- Select a folder or file (A) other than the folder or file you are about to use (B).

Do not select B (but you can select the large arrow to the left of it).
The smaller arrow to the right of B does not appear as the folder is not selected (A is selected instead).
- Right click B.

The pop-up UI will not go away (even if you click off).
It should automatically disappear if you click on something else.
Of course, you can right click B again to make it go away but I think that this should happen automatically, espicially as you can right click on any of the unselected files or folders (ones that don't have the small arrow to the right) and the pop-up UIs will stack up. Like so:
![image](https://user-images.githubusercontent.com/42446683/45230532-0a894280-b2c1-11e8-84b2-99720af27b8e.png)

Also it means that you can have other overlapping UIs/inputs when you click on multiple buttons from the pop-up things (even from the same one):
![image](https://user-images.githubusercontent.com/42446683/45230667-77044180-b2c1-11e8-8c99-899b530cc31b.png)
Here the "add folder", "create file" and console UIs are all overlapping one another while I am renaming a file!

**Comment by catarak** [comment]
thanks for reporting this! i am able to reproduce. i think the console/add file+folder windows overlapping should be broken out into a separate issue.

**Comment by ankur54** [comment]
Hi. Has anyone taken up this issue? I would very much like to work on it.

**Comment by catarak** [comment]
there's currently an open PR (#876), though it has not been merged yet as i have asked for changes.

**Comment by ankur54** [comment]
Ok. So, someone else is working on this, right?

**Comment by catarak** [comment]
yes! i would wait to see if they don't finish it within the next week or so.

**Comment by catarak** [comment]
fixed by #876!

**Comment by ankur54** [comment]
@catarak was it just a css issue, or was some other technology involved?

**Comment by catarak** [comment]
@ankur54 it turned out to be just a css issue!
