### ISSUE TITLE
When changing a file name, sketch does not mark itself as unsaved

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#681]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version:  Google Chrome | 68.0.3440.106 (Official Build) (64-bit)
- Operating System:  Mac OSX
- Steps to reproduce this:

As discussed in #658,
1. Open an existing sketch, or save a new sketch
2. Open the sidebar
3. Click on the "v" next to a file name, and edit the file name
4. Hit enter or click outside of the text input
5. If you refresh the page, the old file name is still there. And since the sketch is not marked as unsaved, there is no warning that the sketch is unsaved.

Expected Behavior:
1. Open an existing sketch, or save a new sketch
2. Open the sidebar
3. Click on the "v" next to a file name, and edit the file name
4. Sketch is marked as "unsaved"

**Comment by catarak** [comment]
@bhawesh96 i think that i agree—i think the behavior matches how a desktop code editor works, and i like that.

**Comment by Janglee123** [comment]
@catarak  I want to work on this but can not find where to start, can you help me ?

**Comment by catarak** [comment]
Sure! If you look at the [input for a file in the sidebar](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/FileNode.jsx#L138), when a user blurs the input (i.e. clicks out of it or hits enter), it calls a function called [validateFileName()](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/FileNode.jsx#L51), which dispatches an action by calling [updateFileName()](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/FileNode.jsx#L62). `updateFileName()` only updates the file client-side, in the redux store, so this data would have to be propagated to the server. 

There's a few different ways to approach this:
1. Save the sketch after updating the file name. This could be hard, since there's no way to tell when the redux store has finished updating, and I think this is not best redux practices.
2. Create a new API endpoint, for updating just the file name. This would mean making an AJAX request, creating an endpoint in express server-side, and figuring out the MongoDB query to make this work! There's a lot of steps here, but you could look at [saveProject()](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/actions/project.js#L67) for reference.

-

**Comment by EOstling** [comment]
@catarak I would like to help with this issue, what needs to be done?

**Comment by catarak** [comment]
i just thought about this again, and i think that the whole sketch _shouldn't_ be saved when you change a file name. it should, however, mark that there are unsaved changes. so, to address your question @EOstling, what you can do is investigate why the sketch is not being marked as unsaved when a file name is updated.

**Comment by EOstling** [comment]
Sounds good! I am on it!

**Comment by dhruvdutt** [comment]
@EOstling Are you still working on this?

**Comment by simranaggarwal1999** [comment]
@catarak I would like to contribute to this. May I?

**Comment by simranaggarwal1999** [comment]
Hey! I had a look at it. When we are making the changes to the File name and pressing enter the the changes are not getting autosaved. When the Save button is pressed then the file name is getting saved. I guess it is working fine.

**Comment by ghalestrilo** [comment]
Hi everyone, given the recent inactivity on this, I decided to attempt a solution. The PR above fixes this issue, and describes the solutions. Feedback much appreciated ❤️
