### ISSUE TITLE
Student project crashes

### ISSUE THREAD

**Issue by runemadsen** [processing/p5.js-web-editor#687]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

I have a student sketch that crashes the page whenever loaded. I have tried on multiple computers, and it's the same problem everywhere. Not sure exactly what's going on, because it's hard to debug, but the error in Developer Tools is:

```
TypeError: Cannot read property 'content' of undefined
```

**Comment by shinytang6** [comment]
Could you provide a link to the sketch?

**Comment by catarak** [comment]
that sounds annoying! yes, please link to the sketch and i can see if i can narrow down the issue.

**Comment by runemadsen** [comment]
WOOPS, sorry. Here we go:
https://editor.p5js.org/Ich_xiuai/sketches/SJg5toe6wX

**Comment by carlaplotnicoff** [comment]
please I am a sttudent having the same issue! https://editor.p5js.org/carlaplotnicoff/sketches/SycQtp_pm

**Comment by catarak** [comment]
@carlaplotnicoff thanks for the update! i see what the issue is and i think i know how to fix it.

**Comment by catarak** [comment]
i think this has been fixed—let me know!
