### ISSUE TITLE
Lint warnings: long template strings / import lists

### ISSUE THREAD

**Issue by bendman** [processing/p5.js-web-editor#688]
It's not a big deal, but I figured I'd report it. Should the config be changed to ignore strings, or just add line/section exceptions to the areas that throw warnings?

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Operating System: MacOSX 10.13.4
- ESLint: 4.9.0
- Steps to reproduce this: Checkout and install the `master` branch and `npm run lint`

```console
$ npm run lint

> p5.js-web-editor@0.0.1 lint /Users/bendman/Development/p5.js-web-editor
> eslint client server --ext .jsx --ext .js


/Users/bendman/Development/p5.js-web-editor/client/modules/IDE/components/Console.jsx
  6:1  warning  Line 6 exceeds the maximum line length of 120  max-len

/Users/bendman/Development/p5.js-web-editor/server/examples-gg-latest.js
  30:1  warning  Line 30 exceeds the maximum line length of 120  max-len

/Users/bendman/Development/p5.js-web-editor/server/views/404Page.js
  48:1  warning  Line 48 exceeds the maximum line length of 120  max-len

✖ 3 problems (0 errors, 3 warnings)
```

**Comment by catarak** [comment]
i think the warning should stay in place—it is pretty annoying to have super long lines of code and i do prefer them to be broken up. i think these should either be fixed, or, if it seems more annoying/unclear to break them up, then the comment to suppress the warnings should be added.
