### ISSUE TITLE
Negative Font Size

### ISSUE THREAD

**Issue by Janglee123** [processing/p5.js-web-editor#689]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

- Web browser and version: Firefox 62.0 (64-bit)
- Operating System: Linux (Solus)
-  Steps to reproduce this:  Go to [website](https://editor.p5js.org) and decrees font size 

#### Details about the bug:
Recently I found that editor font size can be negative

**Comment by dmfabritius** [comment]
Is anyone working on this? I can make the fix, and also fix the indentation amount from going negative.

**Comment by dmfabritius** [comment]
For reference, here is my latest working version, which modifies Preferences.jsx

for the font size:
`              <button
                className="preference__minus-button"
                onClick={() => { if (this.props.fontSize > 8) this.props.setFontSize(this.props.fontSize - 2); }}
                aria-label="decrease font size"
              >
`
and for the indent:
`              <button
                className="preference__minus-button"
                onClick={() => { if (this.props.indentationAmount > 1) this.props.setIndentation(this.props.indentationAmount - 2); }}
                aria-label="decrease indentation amount"
              >
`

**Comment by bhawesh96** [comment]
This issue can be closed right?

**Comment by Janglee123** [comment]
@bhawesh96 No , I just started working on it but if you want you can work on it

**Comment by bhawesh96** [comment]
@Janglee123 Alright, I'll do it.

**Comment by bhawesh96** [comment]
How should the behaviour be? Should the buttons be disabled upon reaching the extreme limits?
Need to handle the case when one enters a font size less than the minimum limit directly into the `<input>` field.

**Comment by Janglee123** [comment]
Can you make it disappeared at limits ? You can ask it to @catarak

**Comment by catarak** [comment]
@bhawesh96 i agree, i don't think making the buttons disappear is a nice UX! i think what should happen is that once a user has the minimum/maximum size selected, then clicking the -/+ buttons won't do anything. you could disable the buttons (only the - button for minimum value, only the + button for maximum value) too.

i also noticed that you can set the indentation amount to negative values too. maybe it would be good to also give this a smart minimum and maximum value? like 0-6? i think it makes sense to fix this as part of this ticket.

**Comment by bhawesh96** [comment]
Disabling the buttons do not make the button _look_ disabled as `onHover` CSS remains. Hence, as a user, I might just keep clicking the button since I'm not being notified about the minimum / maximum value.

**Comment by catarak** [comment]
we could add a disabled style!

**Comment by bhawesh96** [comment]
@catarak This issue can be closed.

**Comment by catarak** [comment]
@bhawesh96 thanks!
