### ISSUE TITLE
Accessible Preferences

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#69]
Just an idea--maybe we could have section labeled "Accessibility Features" or something similar with a toggle. When it is disabled, all of the accessibility features are off and hidden from the preferences menu, but when on, all of the options are enabled unless a user drills down and turns them off. 

Just trying to think about ways to make these preferences for users without accessibility needs less confusing and easy to find and enable for accessible users. Thoughts?

@CleezyITP @MathuraMG

**Comment by CleezyITP** [comment]
I'm ok with having a section called "Accessibility Features" but as usual, I advocate for them being visible at all times. We have already hidden the "play with text output" button and hiding this set of features feels like we are brushing them under the rug.

**Comment by catarak** [comment]
Okay, makes sense. I'm going to put these preferences under the heading "Accessibility Features", but they will be visible at all times.

**Comment by catarak** [comment]
This is handled as part of the updated design:
![11 web-editor-light-settings-1024 1x](https://cloud.githubusercontent.com/assets/6063380/19287975/fddd81ae-8fd1-11e6-9edd-6d41965ad534.png)

**Comment by MathuraMG** [comment]
Hi @catarak , @CleezyITP  - 

Just wanted to also start up a conversation about having multiple types of accessible canvas outputs.

We are currently looking at having the below 3 types as user preferences -
[Plain Text output](http://mathuramg.com/monkeyPatchTest/)
[Grid Text output](http://mathuramg.com/MonkeyPatchGridTest/)
[Sound output](http://mathuramg.com/monkeyPatchSound/index.html)

On some user testing and feedback - we have been told that it would be could to have keyboard shortcuts as well to switch between them.

Do options like the below seem fair?

Cmd+Option+0 - Turn of accessible output
Cmd+Option+1 - Turn on Plain text
Cmd+Option+2 - Turn on Grid text
Cmd+Option+3 - Turn on Sound

**Comment by MathuraMG** [comment]
Hi @catarak , @CleezyITP  - 

Just wanted to also start up a conversation about having multiple types of accessible canvas outputs.

We are currently looking at having the below 3 types as user preferences -
[Plain Text output](http://mathuramg.com/monkeyPatchTest/)
[Grid Text output](http://mathuramg.com/MonkeyPatchGridTest/)
[Sound output](http://mathuramg.com/monkeyPatchSound/index.html)

On some user testing and feedback - we have been told that it would be could to have keyboard shortcuts as well to switch between them.

Do options like the below seem fair?

Cmd+Option+0 - Turn of accessible output
Cmd+Option+1 - Turn on Plain text
Cmd+Option+2 - Turn on Grid text
Cmd+Option+3 - Turn on Sound

**Comment by catarak** [comment]
This sounds good to me! Would these shortcuts use Control instead of Cmd on Windows?

**Comment by MathuraMG** [comment]
It should be Ctrl +Alt on Windows.. But I will do a bit more research on Windows screen readers before I can confirm this.
Mainly trying to ensure that these shortcuts don't interfere with screen reader shortcuts.

**Comment by MathuraMG** [comment]
Sorry - Just a quick check, is
Cmd/Ctrl + Shift +1/2/3/4 ok?

 I was testing it and Cmd+Option did not seem comfortable at all.
@CleezyITP @catarak

**Comment by catarak** [comment]
On Mac I know that Cmd + Shift + 3/4 are used for taking screenshots, so it would have to override that functionality. I'm not sure about Windows.

**Comment by MathuraMG** [comment]
Oh ok - then what do you think of Cmd + Shift + 0 to turn it off and Cmd + Shift +1 to turn on and circle between the various choices ( since there will be only  3 ) - would that be a good "shortcut interface" ?

**Comment by catarak** [comment]
Would maybe Cmd + Shift + 1 and Cmd + Shift + 2 make more sense since they are next to each other? 

As to whether cycling through the options is okay, it seems okay to me, just as long as users can pick a default choice as to which mode it begins on when a user clicks play. I defer to @CleezyITP though 😄

**Comment by MathuraMG** [comment]
Spoke to @CleezyITP as well - will stick to Cmd+Shift+1 for On/Toggle between options and Cmd+Shift+2 for turning it off !

**Comment by catarak** [comment]
folding this into #266
