### ISSUE TITLE
Lag on the webpage

### ISSUE THREAD

**Issue by MrT3chnik** [processing/p5.js-web-editor#691]
#### Nature of issue?

- [x] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version:  Firefox 62.0
- Operating System:  Windows  10
- Steps to reproduce this: Use the web editor
 The editor freezes every few seconds and has to reload everytime i go into its tab.

#### Feature enhancement details:
Please make it faster, at this speed it is not usable. (I have a pretty decent laptop, it has to be the site)

**Comment by MrT3chnik** [comment]
The issue was mainly present when typing, maybe the syntax checking slowed it down and just from switching tabs it reopened a blank page with a spinner and then reopened my project.On 12 Sep 2018 20:23, Cassie Tarakajian <notifications@github.com> wrote:Thanks for reporting this! Are these the steps to reproduce?
Open the web editor in Firefox, leave it open and running on a tab (is a sketch running or not?)Switch to a new tabCome back to the tab with the editor running, it freezes, and then you have to reload the page.
Can you try doing some stuff like turning off the Firefox add-ons, opening a new sketch, etc.? I haven't seen this behavior before and it would be helpful to isolate the issue. In my experience, once the web editor is loaded in your browser window (which sometimes can take a few seconds), it's pretty fast.

**Comment by catarak** [comment]
Huh, that's super weird! I've never seen that behavior. Is it for all sketches or just a specific one? Could you possibly take a video of it?

**Comment by MrT3chnik** [comment]
I'm currently not at my computer, but I can do that tomorrow, so you can see my problem.On 12 Sep 2018 20:46, Cassie Tarakajian <notifications@github.com> wrote:Huh, that's super weird! I've never seen that behavior. Is it for all sketches or just a specific one? Could you possibly take a video of it?

**Comment by catarak** [comment]
@MrT3chnik any updates on this?

**Comment by catarak** [comment]
no worries, thanks for the update!
