### ISSUE TITLE
Add File Dialog Cannot Be Closed

### ISSUE THREAD

**Issue by tonyweed** [processing/p5.js-web-editor#693]
#### Nature of issue?
There's no way to close the (Add File, Add Folder, Rename, Delete) prompt after creating a new file off of a subfolder.

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request
#### Details about the bug: 

Web browser and version: 
Google Chrome | 68.0.3440.106 (Official Build) (64-bit)
- Operating System: MacOS Latest
- Steps to reproduce this:
Open p5-web
Create a new folder
Right click on that folder and click add file
You cannot close this dialog

**Comment by catarak** [comment]
thanks for reporting! does this seem related to #679? are you not able to close the "new file" window or the dropdown that appears under the folder?

**Comment by catarak** [comment]
closing this as a duplicate

**Comment by GaurangTandon** [comment]
Hi @catarak, did you accidentally forget to close this issue, or is there anything else that needs to be done here?
