### ISSUE TITLE
Issues with connecting email accounts and OAuth accounts

### ISSUE THREAD

**Issue by Richard-Koeln** [processing/p5.js-web-editor#695]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: FireFox Quantum 64bit as well as Chrome 68.0.3440.106 (Offizieller Build) (64-Bit) (cohort: Stable)
- Operating System: Windows 10
- Steps to reproduce this:
Login:
Password:

Whenn I changed the passwort via "forgot password" routine, I can change it and I am logged in automatically.
Afte I logged out, it is not possible to log in anymore.

**Comment by catarak** [comment]
Thanks for reporting! I have noticed some funkiness with the login sometimes, but have yet to determine the exact issue. Will investigate!

**Comment by Richard-Koeln** [comment]
I found out:
I have registered on editor.p5js.org with Email Adress/Passwort combination (nither Google nore Github Account.
By chance I used the same Email which I used for registration my account on Github.
Whenever I logged out from the editor it was not possible to log in again using the registered email / password combination.
So it seams that using an Email of an existing Github account for registering an p5js editor account  won't work properly!
In between I use my Github directly for login: works fine!
I thried setting up account by using email which definitely is not used at Github: works also fine!.
Hope this helps to improve the editor!
Thanks a lot for your great work on it!
kindlyRichard 


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: Cassie Tarakajian <notifications@github.com> 
Datum: 17.09.2018  18:56  (GMT+01:00) 
An: "processing/p5.js-web-editor" <p5.js-web-editor@noreply.github.com> 
Cc: Richard-Koeln <Richard.Jungkunz@th-koeln.de>, Author <author@noreply.github.com> 
Betreff: Re: [processing/p5.js-web-editor] Login not possible (#695) 

Thanks for reporting! I have noticed some funkiness with the login sometimes, but have yet to determine the exact issue. Will investigate!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/processing/p5.js-web-editor","title":"processing/p5.js-web-editor","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/processing/p5.js-web-editor"}},"updates":{"snippets":[{"icon":"PERSON","message":"@catarak in #695: Thanks for reporting! I have noticed some funkiness with the login sometimes, but have yet to determine the exact issue. Will investigate!"}],"action":{"name":"View Issue","url":"https://github.com/processing/p5.js-web-editor/issues/695#issuecomment-422091546"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/processing/p5.js-web-editor/issues/695#issuecomment-422091546",
"url": "https://github.com/processing/p5.js-web-editor/issues/695#issuecomment-422091546",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [processing/p5.js-web-editor] Login not possible (#695)",
"sections": [
{
"text": "",
"activityTitle": "**Cassie Tarakajian**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@catarak",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"processing/p5.js-web-editor\",\n\"issueId\": 695,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"processing/p5.js-web-editor\",\n\"issueId\": 695\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/processing/p5.js-web-editor/issues/695#issuecomment-422091546"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 380636138\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by catarak** [comment]
That is really helpful, thank you!

**Comment by migom6** [comment]
Is anyone currently working on this issue?

**Comment by catarak** [comment]
@migom6 nope! go ahead and work on it if you'd like.

**Comment by siddhant1** [comment]
@migom6 are you still working on it?

**Comment by dhruvdutt** [comment]
@migom6 Any update here? I would like to work on this as well. ✋

**Comment by catarak** [comment]
if an issue hasn't been updated within a month, i think you can safely assume they are not working on it anymore 😄

**Comment by catarak** [comment]
I'm 99% sure this was fixed by #1317 🎉
