### ISSUE TITLE
Settings -> Indentation amount not respected when entering new line 

### ISSUE THREAD

**Issue by config2000** [processing/p5.js-web-editor#700]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Google Chrome v69.0.3497.92
- Operating System: MX Linux 17.1 

- Steps to reproduce this:
Change settings -> indentation amount. Creating a new line in the code (created by pressing ENTER) does not appear to respect to the indentation amount set. Typically it enters 1 tab indentation regardless of the tab setting.

**Comment by catarak** [comment]
Thanks for reporting! I think this is actually pretty simple to fix—just an update to the CodeMirror configuration. Right now, the settings `indentWithTabs` and `tabSize` are set, but `indentUnit` is not set. Should be set like [this](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Editor.jsx#L138) and updated when the prop changes like [this](https://github.com/processing/p5.js-web-editor/blob/master/client/modules/IDE/components/Editor.jsx#L173).
