### ISSUE TITLE
Add QR code to Share Modal, to make it easy to open sketch on mobile

### ISSUE THREAD

**Issue by yonghuming** [processing/p5.js-web-editor#702]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

##### add page title
add page title and some discrib on page 
![image](https://user-images.githubusercontent.com/435079/45928795-e9d91200-bf7b-11e8-8117-d2f273be7478.png)
this is not user friendly
##### add qr code when share sketch on mobile device
add qr code on right bottom when share sketch for easily use in wechat

**Comment by yonghuming** [comment]
![image](https://user-images.githubusercontent.com/435079/45928870-c367a680-bf7c-11e8-94f5-09da0cb610c6.png)
seems need to modify http version of full screen page

**Comment by catarak** [comment]
Thanks for reporting! Is this actually three separate issues?
1. In full screen view, sketch title, favicon, etc. are missing from the website.
2. Add a QR code to "Share" modal for easier sharing.
3. Adding a base URL is causing a bug, though it's not clear to me from your report what the bug is. Can you let me know more?

**Comment by catarak** [comment]
the full screen issues have been fixed by #692. i'm going to turn this into a feature enhancement suggestion to add qr codes!

does anyone have any insight as to how much QR codes are used?

**Comment by slowizzm** [comment]
@catarak Though I rarely use qr codes, I did add one to a flyer for my creative coding class I am teaching next semester that points to a full screen interactive mobile sketch. Beyond this use I don’t see any other reason for a qr code feature, but obviously when I want to generate one it would be nice to have the editor generate one for me.

**Comment by catarak** [comment]
@slowizzm good to know!

**Comment by catarak** [comment]
@LakshSingla i don't have any near-term plans to work on this issue, but feel free to take it up if you feel it is important!

**Comment by LakshSingla** [comment]
In lieu of making the editor more mobile friendly, I believe they should be added (Although may be proposed as a long term goal). I propose adding a small button to the share modal which would open another overlay containing the QR Code. Here's a react library we may use [qrcode.react](https://www.npmjs.com/package/qrcode.react). It should be easy to implement if there are no problems with the positioning of the modal. If you wish, I can take up on this issue, or we can hold back on it for the time being. Your call... @catarak

**Comment by devashish1099** [comment]
@catarak  do you want this feature now, if so i would like to work on it

working plan ->
it just requires 2 npm packages react-native-svg and react-native-qrcode-svg
and some lines of code

**Comment by catarak** [comment]
I think ultimately it doesn't make sense to add this to the web editor. Just searching "generate qr code from url" returns tons of results, and it's is probably way more customizable.
