### ISSUE TITLE
key could not get focus afer click run button

### ISSUE THREAD

**Issue by yonghuming** [processing/p5.js-web-editor#703]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: chrome 68.0.3440.106
- Operating System: 
- Steps to reproduce this:windows 10 64 bit
https://github.com/processing/p5.js-web-editor/issues/701
```
function setup() {
createCanvas(600, 600);
snake = new Snake();
}

function draw() {
background(50);
snake.show();
snake.update();
print(snake.yspeed);
}

function keyPressed() {
if (keyCode === UP_ARROW) {
snake.dir(0, 1);
} else if (keyCode === DOWN_ARROW) {
snake.dir(0, -1);
} else if (keyCode === LEFT_ARROW) {
snake.dir(-1, 0);
} else if (keyCode === RIGHT_ARROW) {
snake.dir(1, 0);
}
}

function Snake() {
this.x = 0;
this.y = 0;
this.xspeed = 1;
this.yspeed = 0;

this.update = function() {
this.x = this.x + this.xspeed;
this.y = this.y + this.yspeed;
}

this.dir = function(_x, _y) {
this.xspeed = _x;
this.yspeed = _y;
}

this.show = function() {
fill(255);
rect(this.x, this.y, 10, 10);
}
}
```
![image](https://user-images.githubusercontent.com/435079/45929166-6cfc6700-bf80-11e8-945f-52a3a7238f9b.png)

#### New feature details:

**Comment by catarak** [comment]
This is suggested as a feature enhancement in #654. Going to close this as it is a duplicate!
