### ISSUE TITLE
Sktech not working on Chrome 69.0.3497.100 (browser-related issue)

### ISSUE THREAD

**Issue by LMSzor** [processing/p5.js-web-editor#707]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Chrome 69.0.3497.100
- Operating System: MacOS X
- Steps to reproduce this:
https://editor.p5js.org/Meares/sketches/Sy3fwtbYQ
The above sketch was working fine when I created it a few days back. Somehow it throws an error now. The console error does not provide any useful information - `Script error. (: line 0)`.
The sketch works fine in *Safari 11.0 (12604.1.38.1.7)* and *Opera 53.0.2907.68*.

EDIT: The sketch was originally created by using Chrome, so there is no way that it didn't work at all. Something has changed either in Chrome (I would say that they implemented another "security" measure to dynamically executed scripts) or in the editor.

**Comment by catarak** [comment]
@LMSzor do you have any of the accessibility features turned on? Click on the cog icon -> Accessibility Tab -> Accessible text-based canvas -> are any of the boxes checked? if so, try turning all of them off and try again. 

This bug will be fixed in the next release of the p5.accessibility library!

**Comment by LMSzor** [comment]
@catarak yeah, I actually had "table-text" checked in. Switching it off solved the problem. Thanks!

PS. With the "sound" option *on*, the script still works. Seems like only "X-text" options are making problems.

**Comment by catarak** [comment]
cool, glad that fixed it. thanks for the info!
