### ISSUE TITLE
Icon/text misaligned in console messages

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#711]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version:  69.0.3497.92 (Official Build) (64-bit)
- Operating System:  Mac OSX 10.13.4
- Steps to reproduce this:

<img width="710" alt="screen shot 2018-10-03 at 2 37 19 pm" src="https://user-images.githubusercontent.com/6063380/46431638-52fa1b80-c71a-11e8-869b-a83a22430cde.png">
<img width="710" alt="screen shot 2018-10-03 at 2 37 25 pm" src="https://user-images.githubusercontent.com/6063380/46431644-55f50c00-c71a-11e8-9b06-d75003ff4a4e.png">
When you print messages to the Web Editor console, the text is not in line with the icon. it actually appears that the icon is centered, but the text is not.

**Comment by Janglee123** [comment]
@pwjablonski as I think change in `padding` or `log_icon_height`
may be not works, but if you got it then kudos to you. Problem seems to be inside `console-feed`. I have opened [issue](https://github.com/samdenty/console-feed/issues/17) in console-feed repo. That will surely be help you.

**Comment by AnkurIngale** [comment]
Can I work on it?

**Comment by catarak** [comment]
@AnkurIngale absoutely! though it might not be possible to fix at the moment, see https://github.com/samdenty/console-feed/issues/17

**Comment by AnkurIngale** [comment]
@catarak please visit this link : https://github.com/samdenty/console-feed/issues/17#issuecomment-473078066

**Comment by pwjablonski** [comment]
@Janglee123 Apologies for the delay here and thanks for the input. @AnkurIngale sounds good to me!  I unfortunately won't have as much time to dig into this as I had thought at the moment and happy to pass it off. 

@catarak would you like me to close down #832 since @AnkurIngale is taking this up?

**Comment by catarak** [comment]
@pwjablonski no worries!

**Comment by catarak** [comment]
fixed by #667
