### ISSUE TITLE
Highlight matching brackets in code editor

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#712]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [X] New feature request

#### New feature details:
In the code editor, it would make it easier to debug code if when you have selected or have the cursor next to a bracket, it would highlight the matching one. 

This is a feature built into CodeMirror. To add this feature, the steps are
1. Include the CodeMirror `edit/matchbrackets.js` file.
2. Add styling for `CodeMirror-matchingbracket`, `CodeMirror-nonmatchingbracket`.

You can read more about these in the [CodeMirror manual](https://codemirror.net/doc/manual.html).

**Comment by Janglee123** [comment]
@catarak I want to work on this

**Comment by bhawesh96** [comment]
https://codemirror.net/doc/manual.html#addon_matchbrackets

This might help.
@Janglee123
