### ISSUE TITLE
"Cannot display JSHint error (invalid line 0)" on modification in editor

### ISSUE THREAD

**Issue by Rom194** [processing/p5.js-web-editor#715]
There is the warning `Cannot display JSHint error (invalid line 0)` when we add or delete a char in the editor.

For more information on this error, there is a screenshot:
![capture d ecran_2018-10-04_18-26-15](https://user-images.githubusercontent.com/25200594/46488599-6a610380-c803-11e8-8751-aebea2301ac0.png)

**Comment by catarak** [comment]
thanks for reporting! i am able to reproduce. this would be related to displaying lint errors. not sure what's going on here!
