### ISSUE TITLE
Remove lint warnings

### ISSUE THREAD

**Issue by bhawesh96** [processing/p5.js-web-editor#717]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Operating System: Linux 16.04
- Steps to reproduce this:
`npm run lint`

#### Work required:
Remove unused imports and variables.

**Comment by catarak** [comment]
thanks for reporting! would be great to do this. i've gotten really good at ignoring them.

**Comment by cdncat** [comment]
I'll do this! :)
