### ISSUE TITLE
request status: 403 error when running old project with media

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-web-editor#719]
A student in class noticed when she tried to run an [older project](https://editor.p5js.org/kay1997/sketches/ryNOISLie) that involved loading media and once ran correctly, this error came up:
```
Unable to load https://s3-us-west-2.amazonaws.com/assets.editor.p5js.org/587418d1950d178e6be11e71/0736c312-787a-485f-882a-71e6367b6a00.wav. The request status was: 403 (Forbidden)
```
Is there any fix for this? Or does she need to just re-upload all the media files?

Thanks!

**Comment by catarak** [comment]
I think this is a lingering error from when I moved all of the files uploaded to S3 to a new bucket, and the access permissions all changed. I will see if I can fix this!

**Comment by lmccart** [comment]
here's one more with the same problem: https://editor.p5js.org/Bella/sketches/BkDE56r7e

**Comment by raclim** [comment]
Closing this for now since it's dated and has been referenced in a subsequent issue!
