### ISSUE TITLE
Uncaught TypeError: this.class is not a function

### ISSUE THREAD

**Issue by Leiyufazhuangjia** [processing/p5.js-web-editor#721]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 69.0.3497.100 
- Operating System: 
- Steps to reproduce this:Windows10
https://editor.p5js.org/leiyufazhuangjia/sketches/ry6z88Vcm
//I'm trying to change the 'class' attribute of some DOM element in sketch.js.
//when i mousePressed any p label i wish the "class" transform from 'world' to 'nature',at the same time
//it can display as a 'nature' class style.However it doesn't work,
//Uncaught TypeError: this.class is not a function <-----this error feedback always happens.
//Some error of the code? feel a little confused.
//https://editor.p5js.org/leiyufazhuangjia/sketches/ry6z88Vcm

function setup() {
  noCanvas(400, 400);
  for (var i = 0; i < 15; i++) {
    p = createP('hello world');
    p.position(random(600), random(600));
    p.class('world');
    p.mousePressed(be_nature);
  }
}
function be_nature(){
  this.class('nature')
}

<!DOCTYPE html>
<html>

<head>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/p5.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.dom.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.2/addons/p5.sound.min.js"></script>
  <script src="sketch.js"></script>
  <link rel="stylesheet" type="text/css" href="style.css">
  <meta charset="utf-8" />

    <style>
    .world {
      background-color: rgb(60, 60, 150);
    }

    .nature {
      font-size: 30pt
      background-color: rgb(60, 60, 40);
    }
  </style>
</head>
<body>
</body>
</html>

#### New feature details:

**Comment by slowizzm** [comment]
https://editor.p5js.org/slow_izzm/sketches/rkkXU4rc7

**Comment by catarak** [comment]
@Leiyufazhuangjia thanks for reporting! this is actually an error with your code. in the function `be_nature`, because it's defined in the global scope, `this` refers to `window`. There are two different ways to fix this:
1. Pass the `p` element to the function `be_nature()` as an argument.
2. When calling be_nature(), bind it to the scope of the `p` element, i.e. change  `p.mousePressed(be_nature);` to `p.mousePressed(be_nature.bind(p));`

In the future, if you're looking for p5.js help, I recommend asking on the [Processing forum](https://discourse.processing.org/)! The GitHub issues for the p5.js Web Editor (where we are now!) are for reporting bugs/requesting features/etc. with the Web Editor itself.

**Comment by shiffman** [comment]
I just looked at this and it's a bug in the p5.dom library! @Leiyufazhuangjia You should go ahead and file an issue here: https://github.com/processing/p5.js/issues

@catarak The dom library is actually supposed to bind the DOM element for you behind the scenes.

@Leiyufazhuangjia Two things that would be helpful for your bug report.

1. Your code actually works as of p5 version 0.6.1. 

2. When posting code it's good to make a very simple example that demonstrates the issue only (without other code.) You can also put your code inside of three "back ticks" and it will be formatted:

```javascript
function setup() {
  noCanvas();
  button = createButton('hello');
  button.mousePressed(test);
}

function test() {
  console.log("test");
  this.html('goodbye');
}
```

Let me know if you need help filing the issue!

**Comment by Leiyufazhuangjia** [comment]
@shiffman  Thanks for reply! i'm totally new learning programming.I'll file the issue,.
Before the bug fixed, i think the bind function is a good alternative way to code in p5 web editor right?

**Comment by catarak** [comment]
i didn't realize that the dom library is supposed to bind behind the scenes for you, and this is a bug in `p5.js`. for now, yes, `bind` is a good alternative, or using an earlier release of p5!
