### ISSUE TITLE
Fr

### ISSUE THREAD

**Issue by edhebert** [processing/p5.js-web-editor#723]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:

Hi! 

I'm assembling a syllabus for Spring semester, for an introductory programming course. I'm hoping to direct students to the P5 editor for most of their work this year. I noticed, however, that the P5 "friendly error system" is disabled by default on the P5 editor. In order to activate it, students would be required to edit the index.html file to change p5.min.js to p5.js. 

For students that are entirely new to programming, this online editor will be invaluable! Likewise, I assume the FES is designed to primarily help those beginners. However, asking a complete noob to begin lesson 1 by asking them to immediately leave sketch.js, reveal index.html, and ask them to make edits there would be a disconnect from the whole "P5 will be fun and friendly!" sales pitch.

I'd love to see the Friendly Error System enabled by default in the P5 web editor, with the option to disable it for performance reasons as students progress. 

Thanks!

Ed

**Comment by catarak** [comment]
thanks for reporting this! this is covered in #417, and i can prioritize working on it.

**Comment by catarak** [comment]
going to close this issue since it's a duplicate!
