### ISSUE TITLE
Granting permissions

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js-web-editor#724]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

I noticed that when you sign up for the editor, it says that you are authorizing @catarak. I know who this is, but I'm not sure everyone does, and I can imagine it raising suspicion for some people. I would feel more comfortable giving permission if there was an official Processing or p5.js GitHub account associated with these permissions.

(It would also help make the editor more maintainable in the future if this is not associated with an individual  developer's account.)

<img width="544" alt="screen shot 2018-10-05 at 22 53 40" src="https://user-images.githubusercontent.com/157106/46641967-5ed64b00-cb29-11e8-8b80-676bf615b252.png">

**Comment by catarak** [comment]
thanks for reporting! this is a good call, and i bet i can move this application to the processing foundation github account..

**Comment by shiffman** [comment]
Happy to help with this on the Processing Foundation side if I can!

**Comment by catarak** [comment]
@shiffman i just sent a request to @processing to transfer the application.

**Comment by shiffman** [comment]
Yay! I think someone approved already before I got to the request. . is it set now?

**Comment by catarak** [comment]
it's no longer in my account so i assume so. i think i have to create a new github account to test this...

**Comment by catarak** [comment]
just tested, it works!
