### ISSUE TITLE
Exponentiation operator shown as error when used.

### ISSUE THREAD

**Issue by TheV360** [processing/p5.js-web-editor#725]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
When I try to use the [exponentiation operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Exponentiation_(**)), it says it's an error.

- Web browser and version: Firefox 62.0.3
- Operating System: Windows 10
- Steps to reproduce this: write any line of code with the exponentiation operator.
````javascript
function setup() {
  createCanvas(2 ** 8, 2 ** 7);
}

function draw() {
  background(220);
}
````

**Comment by catarak** [comment]
Thanks for reporting! This has to do with the JSHint configuration in the Editor component. Basically, JSHint doesn't currently support ES7, which includes the "**" operator, but this will be included in the [next release](https://github.com/jshint/jshint/pull/3060). I've been trying to find a way that it would show the error, but I can't figure that out.

**Comment by LakshSingla** [comment]
This seems to be working now, although the CodeMirror shows a linting error. Should a separate issue be created for it ?

**Comment by catarak** [comment]
a new version of JSHint has been released, see https://github.com/jshint/jshint/releases. this issue should be pretty easy to fix now—just updating JSHint in the web editor!
