### ISSUE TITLE
New Folder can be created without name

### ISSUE THREAD

**Issue by Janglee123** [processing/p5.js-web-editor#726]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Firefox 62.0.3 (64-bit) 
- Operating System: Solus 3.9
- Steps to reproduce this:
1.Right-click on project folder
2.Select add folder
3.Click on Add Folder without typing name

**Comment by catarak** [comment]
Thanks for reporting! This should be as simple as adding some form validation.

**Comment by ns23** [comment]
Hello, can i work on this issue ?

**Comment by catarak** [comment]
@ns23 yes!

**Comment by ns23** [comment]
Thank you. I will fork the repo and set up local environment first.

**Comment by catarak** [comment]
@ns23 I recently updated the developer documentation and changed the instructions for setting up your local environment, so if you run into any issues or have any feedback, feel free to open an issue!

**Comment by ns23** [comment]
Sure
