### ISSUE TITLE
Images load in Editor window but not in fullscreen view

### ISSUE THREAD

**Issue by vanevery** [processing/p5.js-web-editor#727]
#### Nature of issue?

- [x ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
When loading images added to the editor, they function in normal editor view but aren't loaded by Chrome in full screen view.  Things seem to work fine with one image but as soon as they are loaded in a loop, there is an issue.

Chrome gives this error:
Redirect from 'http://editor.p5js.org/full/H1RAuYHq7/images/3.jpg' to 'https://editor.p5js.org/full/H1RAuYHq7/images/3.jpg' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://editor.p5js.org' is therefore not allowed access.

- Web browser and version: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Operating System: MacOS
- Steps to reproduce this:
https://editor.p5js.org/shawn/sketches/S178ugnqX
Try in full screen

**Comment by catarak** [comment]
thanks for reporting! will look into this...

**Comment by molleindustria** [comment]
Great job with the web editor.

Unfortunately I have to report the same issue. Some sketches can't load external assets on fullscreen. I have issues reproducing it but it also seems like the links to some resources are being rewritten without the s in https

VM49:1 Mixed Content: The page at 'https://editor.p5js.org/full/BJkTOFMoQ' was loaded over HTTPS, but requested an insecure resource 'http://editor.p5js.org/sketches/BJkTOFMoQ/assets/compliments.txt'. This request has been blocked; the content must be served over HTTPS.

**Comment by catarak** [comment]
just tested both of these sketches and it seems to be fixed. let me know otherwise!
