### ISSUE TITLE
npm start gave fail to compile error.

### ISSUE THREAD

**Issue by ns23** [processing/p5.js-web-editor#729]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: Ubuntu 18.04
- Steps to reproduce this:

After cloning the repo and making changes to the .env file, When I ran `npm start` code failed to compile and I got following error
![error](https://user-images.githubusercontent.com/10084011/46905786-10a0bd80-cf16-11e8-82a1-529844ca4c39.png)

**Comment by ns23** [comment]
I will check my  `.eslintric` file and will give an update

**Comment by catarak** [comment]
closing since i can't recreate this!
