### ISSUE TITLE
Updating assets

### ISSUE THREAD

**Issue by slowizzm** [processing/p5.js-web-editor#734]
- [x ] Existing feature enhancement

Instead of adding a `-#` to the end of a file that is being re-uploaded (or more specifically a file that has the same name as an existing file in the project), it would be nice if it would just overwrite that existing file.

**Comment by catarak** [comment]
thanks for reporting! i think it would be confusing if it just overwrote the old asset. however, maybe this can function like in an operating system—the editor could show an alert, asking if the user wants to overwrite the file or keep both.

**Comment by slowizzm** [comment]
Yes, I agree. An alert would be best to prevent user error.

**Comment by LakshSingla** [comment]
@catarak @slowizzm What are the different ways in which one can add files ? Are there any other ways than clicking on the project name to reveal the add file/folder dropdown ?

**Comment by LakshSingla** [comment]
@catarak I would like to work on this issue. Can you please help me with which functions needs refactoring. Also, the only method I know to add a file in the ide is to click on the new file or new folder dragdown, in the sidepane. Are there any other methods to achieve it?

**Comment by slowizzm** [comment]
Yes, that is the only method I know of to upload files. I have also noticed that you can only upload 6 files at a time.

**Comment by LakshSingla** [comment]
@catarak @slowizzm I found the redux action responsible for producing the unique filename. Is there any pre existing modal I can reuse for issuing the warning?

**Comment by catarak** [comment]
yeah! i would use the component `client/modules/App/components/Overlay.jsx`. Maybe it would make sense for the overlay to have a few buttons which say "Keep Both", "Replace", "Cancel", and then the "X" would also cancel.

**Comment by catarak** [comment]
in my opinion, the amount of effort it would take to work on this issue exceeds its benefit, and therefore i think it makes sense to close this issue. feel free to reopen if you think otherwise!!

**Comment by slowizzm** [comment]
@catarak That makes sense. I would like to say that I have students every semester frustrated with this because they often need to re-edit their assets and when some of those assets are image sequences this can be a tedious process. One solution for this is for me to just have them work in vs code, but then that takes them out of the p5 environment and I love using this editor as a teaching tool for art and media students new to code. 

I will let you be the judge to re-open, as I am sure there are higher-priorities needing attention.

**Comment by catarak** [comment]
got it! maybe the solution here is not being able to edit assets, but for the flow for uploading/renaming/deleting assets to be easier.

**Comment by slowizzm** [comment]
@catarak Yes, that sounds like a plausible solution. Sounds like this may be relative to being the able to the re-order files issue, not sure what issue that is but I have seen it.
