### ISSUE TITLE
Mistake with #713

### ISSUE THREAD

**Issue by Vertmo** [processing/p5.js-web-editor#735]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
Hi ! It's me again. I unfortunately made a small CSS mistake during my work on #713, which causes a useless scroll bar to appear on the `/full/` page. I'll be correcting that quickly.

**Comment by catarak** [comment]
thanks for finding this (and fixing this very soon)!
