### ISSUE TITLE
Sign up form doesn't validate username uniqueness

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#742]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

I noticed that in the web editor logs, the node application has been crashing because of an attempt to create a new user with an existing username. In the sign up form, there should be validation to prevent this, but it appears to not be working. Would be nice to fix this soon as it's causing crashes in the application!

**Comment by anaplian** [comment]
I'd like to take a look at this :slightly_smiling_face:
