### ISSUE TITLE
Lost insertion point when clicking on curly brackets. 

### ISSUE THREAD

**Issue by joemckay5** [processing/p5.js-web-editor#751]
This is a trivial issue, but it's probably an easy fix too. When I click on a curly bracket the formatting shows the partner to that curly, which is awesome, but the insertion point goes away, so I lose where I "am".  That sounds a lot more existential than it really is, but it's still worth fixing I think.

**Comment by catarak** [comment]
thanks for reporting! i have noticed this as well. i spent some time trying to figure out how to fix this, by bringing the cursor to the front of the outline, but i couldn't figure it out. i think the solution here is just to change the styling, where the matching brackets get just an underline rather than a whole outline.

**Comment by joemckay5** [comment]
Processing solves the problem by only putting a box around the curly bracket that the cursor is not next to (if that makes sense). So there is only one box. It seems to be fairly intuitive, but maybe that's just because I'm so used to the processing interface. Could that be possible in p5?

**Comment by catarak** [comment]
the codemirror editor adds the same css class to the matching brackets, so i don't think there's a way to highlight only one of them.

**Comment by LakshSingla** [comment]
I would like to work on it, but I am unable to understand the issue at hand. What I inferred was that if you click on a curly bracket, the cursor moves to that curly instead of staying at its position which we need to fix. Am I correct ?

**Comment by LakshSingla** [comment]
I would like to claim this issue. What I inferred was that sometimes, on clicking the curly bracket, hides the text insertion cursor (which needs a fix).

**Comment by catarak** [comment]
@LakshSingla i don't think there's a way. i think for now a good approach would be to change the design!
