### ISSUE TITLE
Multiple "Add File" creates multiple names for single file

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js-web-editor#752]
Found a bug, Chrome70.0.3538.77 on macOS

1. Go to [editor.p5js.org](editor.p5js.org)
2. Open the side bar
3. In the dropdown click "add file"
4. In the "Name" field type "file1.txt" and click "Add file" button
5. In the "Name" field type "file2.txt" and click "Add file" button
6. Close the "Add file" dialog
7. Click "file1.txt"
8. Type "hello, world" and save the file.
9. Click on "file2.txt"

Expected behavior: file2.txt is empty.

Actual behavior: file2.txt shows "hello, world".

**Comment by catarak** [comment]
thanks for reporting! i just tried doing this a few times and i wasn't able to reproduce. trying to think of what else could be at play here...
- is this a brand new sketch?
- are you logged in?

**Comment by kylemcdonald** [comment]
* it was a new sketch (the first thing that appears when i go to https://editor.p5js.org/
* i was logged in

i just tried to reproduce it and it isn't happening now. i made sure to do it a few times before writing the steps above (closing and reopening the site each time), so i know it was wrong before... but glad to see it's not happening now :)
