### ISSUE TITLE
QR code for p5js

### ISSUE THREAD

**Issue by Rozanova** [processing/p5.js-web-editor#754]
#### New feature details: 
I'd like to suggest a QR code for p5js so that we can easily test sketches on our phones that have accelerometers in them. Right now if i want to text a sketch I have to use TinyURL. It's not terrible but would be nice if a QR code was available

**Comment by catarak** [comment]
thanks for the suggestion! this has already been captured in #702, so i'm going to close this ticket, and change the priority on that ticket.
