### ISSUE TITLE
Feature request: Add file or folder from menu

### ISSUE THREAD

**Issue by dhowe** [processing/p5.js-web-editor#758]
Not sure if this is addressed elsewhere, but I couldn't find it so here goes... 

In my experience students have a very hard time finding the current add-file/add-folder interface which now requires 3 clicks, two of which are on unlabelled '>' arrows. I know a drag/drop UI is in the works, but is there a reason not to also add this as a menu option, either under File or Sketch?

**Comment by catarak** [comment]
I like that idea!

**Comment by LakshSingla** [comment]
@catarak I have added the New File and New Folder option in the Navbar. Please review the changes
