### ISSUE TITLE
console.log p5.Table p5.TableRow

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#761]
Also found at Creative Coding fest! 

- Existing feature enhancement
- tested on chrome Version 67.0.3396.87 (Official Build) (64-bit), mac os X 

See: https://editor.p5js.org/icm/sketches/HyK88pH6Q

```javascript
let data;
function preload() {
  data = loadTable('test.csv');
}
function setup() {
  console.log(data.getRow(0));
}
```

The p5 web editor console prints a `p5.Table` and `p5.TableRow` object as follows:

![screen shot 2018-11-11 at 10 13 50 am](https://user-images.githubusercontent.com/191758/48314664-83936780-e59a-11e8-8bb5-248be87eb138.png)

Looking in the chrome console I see:

![screen shot 2018-11-11 at 10 14 29 am](https://user-images.githubusercontent.com/191758/48314669-9c038200-e59a-11e8-87a2-861f1b37bede.png)

I'm not sure what the p5 web editor console can easily show, but having it render the data in the object would be helpful!

**Comment by catarak** [comment]
i think this has to do with how the `console-feed` library serializes console messages. even though this library works really well, it's not well documented and @shinytang6 and i have definitely missed some obvious stuff like this. i actually think this is pretty easy to fix! will investigate...

**Comment by catarak** [comment]
unfortunately my fixes cause the console to stop working in prod, even though it was working locally 😠

**Comment by catarak** [comment]
turns out it was working but it was a caching error. woohoo!
