### ISSUE TITLE
Investigate accessible features accidentally being turned on

### ISSUE THREAD

**Issue by kaidrumm** [processing/p5.js-web-editor#768]
#### Nature of issue?

- [ x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Reproducible on Chrome and Firefox, I think it was happening on Safari as well.
- Operating System: MacOSX
- Steps to reproduce this: 
One of my students is not able to use the p5js editor anymore, it seems to freeze every time he logs in. One of the first symptoms was that SVG color names stopped working- background(255,0,0) works but background('red') does not. The editor works fine on his computer when he is logged out, and it freezes when he logs in on his friend's computer. It seems to me that this happened for this student and not others because he types code with nonsense syntax all the time and left auto-refresh checked, so the editor is trying to resolve syntax errors constantly.

**Comment by catarak** [comment]
Can you check if the accessibility features are turned on for that account? You can click on the Settings cog icon in the upper right, click on the "Accessibility" tab, and make sure that all of the checkboxes under "Accessible Text-Based Canvas" are all unchecked.

**Comment by siddhant1** [comment]
@catarak I was going through the issues and this is happening very regularly that developers are turning on accessing features by accident , I think we should make a toast or something after accessibility is turned on . What do you say

**Comment by catarak** [comment]
i think users are hitting some keyboard shortcut or something and turning on the accessible features. maybe it would be helpful to note that the accessibility features are in "alpha", and also something in the toolbar that appears when they are on.

**Comment by kaidrumm** [comment]
Ah you guys bumped the thread :) Yes, it was an issue with accessibility features. 

Another issue that has persisted after we turned those off is that he cannot press tab without freezing the editor. So the shift+tab autoformatting option doesn't work.

**Comment by catarak** [comment]
oh no! that sounds annoying. did it just start happening? a [PR was just merged](https://github.com/processing/p5.js-web-editor/pull/966) the overrides the tab key within the context of the code editor, so maybe it's related to that.

**Comment by kaidrumm** [comment]
No, good idea but it has been happening for at least a month.

**Comment by catarak** [comment]
okay, thanks. it must be something else then! a couple of other questions:
- does this happen if the student is logged in on any computer?
- does this happen if another account is logged in on the computer the student had been using?

**Comment by catarak** [comment]
i did some investigation of this. if a user clicks on "start accessible output" in the nav, it actually turns on all of the accessibility features and saves that to their account. i think, for now, the best solution is to remove these options from the nav. i'm going to leave the keyboard shortcuts enabled, for now, and see if this causes issues.

**Comment by kaidrumm** [comment]
Thank you so much for looking into it :)
The class is over now so I don't have a way to check in on the student again.
For what it's worth, based on what you said I wouldn't be surprised if he mashed keys and turned on the accessible output by accident via the keyboard shortcut.

I'm not sure about the "tab not working" part of the issue, but we can close it unless someone else comes up with a similar problem.
