### ISSUE TITLE
Broken error messages

### ISSUE THREAD

**Issue by Vertmo** [processing/p5.js-web-editor#769]
#### Nature of issue?

- [X] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Firefox 64.0
- Operating System: Manjaro Linux
- Steps to reproduce this:
It seems a recent commit has broken the error messages. When making an error in the sketch (for instance using an undeclared variable) no error message is shown in the editor's console, although one is present in the browser's web console.
Moreover, if I use `console.error("Something something")` the editor simply crash (with a React log).
I think the bug was introduced in a recent commit, because one of my local branches pointing at 61dd0bb4d0b220f57667e8e60fce187dd6964d67 is working flawlessly. I'm going to investigate further to find the exact commit causing the bug.

**EDIT**: Weirdly enough, the editor doesn't crash when testing it locally with the latest version of the master branch, but it does still show errors related to `consoleEvent.arguments` in the browser's console. I'm guessing these problems are related to the changes related to #761 and the following multiple corrections.

**Comment by catarak** [comment]
The problem here is browser caching. I cleared the Cloudflare CDN caching, but this could be fixed in the long run by adding a chunkhash to the previewScripts.js output target in the webpack config.

**Comment by Vertmo** [comment]
Are you sure about the caching thing ? Cause I just tested it with a browser I never even used the web editor with, and it's giving me the same error.

**Comment by catarak** [comment]
Looking at #770, i think the caching could be related, but also what you changed as part of that PR is also contributing.

**Comment by catarak** [comment]
yeah, makes sense! i made a massive change to the console since there was a bug in how the messages were getting serialized/deserialized, and tried to test it best i could.
