### ISSUE TITLE
external libraries?

### ISSUE THREAD

**Issue by awaywiththespoons** [processing/p5.js-web-editor#772]
#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [x] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### New feature details:
i am wondering about external libraries - it looks like this was once possible from this image: 
https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3/screen/59413d8c2b29205ef75cbe48 
but I can't now seem to find the feature.
would be really useful (got a workshop in a school soon and they only have chrome so need to use the web editor)

**Comment by catarak** [comment]
i wish this had already been implemented! it's a future feature, currently under #4.
