### ISSUE TITLE
Bug with template string code formatting

### ISSUE THREAD

**Issue by kleinesfilmroellchen** [processing/p5.js-web-editor#773]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 
After trying the text editor with a larger project I have written, I discovered the following: when using a template string of the form

```text(`Lives ${playerLives}\nStreak ${round(streak*10)/10}`, 0, 0); ```

(used to display game information in `draw()`) the code after it is regarded as part of the template string, or in other terms:

![image](https://user-images.githubusercontent.com/28656157/49172734-1e819500-f342-11e8-952f-b23d20915e9e.png)

Everything after this line turns turqoise.

Now, to be clear, this is fully functional code without any errors whatsoever, it is just a flaw in the editor's formatting system

- Web browser and version: Chrome 70.0.3538.110
- Operating System: Windows 10
- Steps to reproduce this: Open [this](https://editor.p5js.org/kleinesfilmroellchen/sketches/BkE1_Lh0X) Editor page and file sketch.js or create similar code to what is shown above.

**Comment by catarak** [comment]
thanks for reporting! it seems like this is something that codemirror supports, so maybe the version of codemirror needs to be updated. hopefully it's that and not something else.

**Comment by catarak** [comment]
i made a custom syntax highlighting file for p5 (like, maybe two years ago), so maybe that needs to be merged with the newest javascript syntax highlighting file in codemirror

**Comment by GaurangTandon** [comment]
Hey @catarak, could you please tell which files need to be changed to fix this issue?  I'd love to help fix this issue. I looked all over the `client` directory and could not find the custom syntax highlighting file that you mention.

**Comment by catarak** [comment]
it's in `client/utils/p5-javascript.js`, which was forked from https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js, however that version is much newer. i would look at the last time `client/utils/p5-javascript.js` was updated, compare that to https://github.com/codemirror/CodeMirror/blob/master/mode/javascript/javascript.js as it was at that time, figure out what i changed to make the p5 syntax highlighting work, and then add it to the newer version.

**Comment by LakshSingla** [comment]
@catarak It is not an issue of the version. I migrated it to the latest version in the CodeMirror repository. They also have many issues with template string formatting (judging from their Issues tracker). But that is not the problem here because their code does not reflect this issue.
The main issue with this code is usage of `p5function` . I am attaching a screenshot of the cases in which it posts a problem and which it does not. 
![Uploading Screenshot from 2019-01-15 22-13-29.png…]()

**Comment by catarak** [comment]
@LakshSingla thanks for digging into all of this!
