### ISSUE TITLE
loadImage() Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by koji** [processing/p5.js-web-editor#775]
The first one got `Access-Control-Allow-Origin`, but the second one works.

```js
function preload() {
  imgBtn[0] = createImg("assets/photo1.jpg");
  imgBtn[1] = createImg("assets/photo2.jpg");
  imgBtn[2] = createImg("assets/photo3.jpg");
  imgBtn[3] = createImg("assets/photo4jpg");
  imgBtn[4] = createImg("assets/photo5.jpg");
}
loadImage(imgBtn[a].elt.src, function (img) {
  image(img, 0, 0);
});
```

```js
function preload() {
  for(let i=0; i<photoNum; i++) {
    imgBtn[i] = createImg(`assets/photo${i+1}.jpg`);
  }

loadImage(imgBtn[a].elt.src, function (img) {
  image(img, 0, 0);
});
```

#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: Chrome(the latest version)
- Operating System: MacOSX
- Steps to reproduce this:

#### New feature details:

**Comment by catarak** [comment]
thanks for reporting this! the weird thing is that this only seems to happen the first time you run the sketch. when you re-run it, it works!
