### ISSUE TITLE
My sketch works except when offline using p5 library.

### ISSUE THREAD

**Issue by sarbu9** [processing/p5.js-web-editor#776]
In this sketch I am using the camera on my computer. It worked properly in the web editor. I copied the code into a sketch file offline and I got an error.

Here is the code from my index file:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="./library/p5.js"></script>
    <script src="./library/addons/p5.dom.js"></script>
    <title>Camera Filter Sketch</title>
  </head>
  <body>
    <script src="./sketch.js"></script>
  </body>
</html>

#### Nature of issue?

- [ ] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this:

#### New feature details:

**Comment by catarak** [comment]
hi @sarbu9! do you mean using the web editor, not connected to the internet, or are you working on a sketch locally on your computer, using another text editor, e.g. sublime text or visual studio code?

**Comment by catarak** [comment]
@sarbu9 the github issues for the p5.js web editor are for reporting bugs and suggesting features for the editor itself. this sounds like an issue with your code, and the best place to get help with that is the [processing forum](https://discourse.processing.org/). feel free to reopen this ticket if you think there's an issue with the web editor!
