### ISSUE TITLE
Make console windows resize grab area larger.

### ISSUE THREAD

**Issue by prcoy** [processing/p5.js-web-editor#777]
#### Nature of issue?

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

#### Feature enhancement details:

Please make the grab area on top of the console window larger. It takes me two or three tries to get it and drag it upward. It seems to be only 1/2 pixel high. Two or three pixels would be great. Also, make it a contrasting color that would be more obvious.

**Comment by catarak** [comment]
yes! i agree that this could be fixed.

**Comment by GaurangTandon** [comment]
I've worked on this and now the resize handle area looks like this:

![image](https://user-images.githubusercontent.com/6308683/49885816-36870780-fe5e-11e8-8cae-6abb596ae5d6.png)

As you can see there is a subtle additional grey shade over the existing grey console header, hovering over which reveals that it's meant to resize the panel (via cursor pointer).
By adding visible color and increasing the visible area by 5px, I hope to have adequately addressed the issue.

**Comment by GaurangTandon** [comment]
Hey @catarak, I was wondering about this issue last night, and what do you think this fix instead? https://youtu.be/3YY85TImE-A

I still feel that the resizer could use some sort of visual indication as to what exactly its boundaries are, which would help the user in performing the resize. I myself spent first few seconds confused at where to exactly place the mouse. A black boundary, that reveals its boundaries on hover (as shown above), would be much clearer. (It would also signal to unknowing users that the console is draggable :P) 

Also if you move your mouse over it at a normal-fast speed, the black boundary doesn't show up. It only shows up when you knowingly move your mouse in that region slowly.

**Comment by catarak** [comment]
i like the experience, but i don't think the ui design fits with the overall design, because this same resize pattern would need to be added to all other resizable panes (the sidebar, the divider between the code and the preview). open to suggestion, but i'd like to see it thought out what it would look like in all of the resizers, and in all of the color themes.
