### ISSUE TITLE
Accessability

### ISSUE THREAD

**Issue by affie888** [processing/p5.js-web-editor#780]
#### Accessability for the Web Editor

- [ ] Found a bug
- [x] Existing feature enhancement
- [ ] New feature request

- Web browser and version: Chrome 71.0.3578.80
- Operating System: MacOS Mojave version 10.14.1

**Comment by catarak** [comment]
I'm going to close this issue, as I think it belongs in the p5.accessibility repository, which is actively working on adding support to make canvas elements more accessible for folks who use screen readers.
