### ISSUE TITLE
npm audit finds 1084 vulnerabilities as many package.json dependencies are outdated

### ISSUE THREAD

**Issue by GaurangTandon** [processing/p5.js-web-editor#785]
#### Nature of issue?

- [x] Found a bug
- [ ] Existing feature enhancement
- [ ] New feature request

Running `npm start` gave 1084 vulnerabilities. So I ran `npm audit`, which gave a full report. The gist goes as:

    found 1084 vulnerabilities (839 low, 167 moderate, 74 high, 4 critical) in 26554 scanned packages

Now, I did fix some of them by running `npm audit fix`, however, I would like it if the dependency versions were updated in the current `package.json`. For example, here is one output table that was present in the thousands of tables `npm audit` gave me:

![image](https://user-images.githubusercontent.com/6308683/50039012-be346800-0050-11e9-9094-a92bf904df41.png)

As I can see in the current `package.json`, the version is outdated:

https://github.com/processing/p5.js-web-editor/blob/244af16b64cfa37f1fac0f54750e9a7c314269a3/package.json#L51

Now, running `npm audit fix` gave this final output, after fetching binaries for `node-sass@4.11.0` and `nodemon@1.18.9`:

```
npm WARN babel-plugin-webpack-loaders@0.9.0 requires a peer of webpack@>=1.12.9 <3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ htmlhint@0.10.1
+ babel-register@6.26.0
+ node-sass@4.11.0
+ express-session@1.15.6
+ lodash@4.17.11
+ body-parser@1.18.3
+ nodemon@1.18.9
+ express@4.16.4
+ jshint@2.9.7
+ nodemailer-mailgun-transport@1.4.0
+ babel-core@6.26.3
+ console-feed@2.8.5
+ request@2.88.0
+ redux-devtools@3.4.2
+ babel-preset-env@1.7.0
added 267 packages from 219 contributors, removed 1280 packages, updated 100 packages and moved 69 packages in 301.168s
fixed 734 of 1084 vulnerabilities in 26554 scanned packages
  2 vulnerabilities required manual review and could not be updated
  5 package updates for 348 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)
``` 

I will make a PR updating all these non-breaking version changes in the `package.json`.

Also, could you please review the remaining vulns? They seem to be quite critical. I would request you to update the dependency versions.

To reproduce these messages, simply a fresh clone of this repo and running `npm install` should suffice. (running node v8.14.0 on npm 6.4.1)

**Comment by everygamer** [comment]
Just curious, but is this type of security vulnerability checking being done on a regular basis? I work in the IT department at a college that is thinking of using this with a CS program, but need to determine if it should be running on our infrastructure and/or cloud host it so that it is not mixed in with our other school systems.

**Comment by catarak** [comment]
It is being checked on a regular basis!
