### ISSUE TITLE
Unable to move scroll bar with the mouse

### ISSUE THREAD

**Issue by chrisorban** [processing/p5.js-web-editor#795]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Firefox (Quantum 64.0) and Chrome (62.0)
- Operating System: Ubuntu Linux 16.04
- Steps to reproduce this bug: 

With any sketch try to click and drag the scroll bar with the mouse. Here is a video demonstrating it with firefox:

https://drive.google.com/file/d/1stXsZCo4FmCeW-rLaerawsmBS87WhK1a/view?usp=sharing

As you can see in the above video it is not possible to move the scroll bar down with the mouse cursor in firefox. Moving it left or right works fine, but dragging it down or up does not work at all.

The behavior with chrome is similar:

https://drive.google.com/file/d/1nMXL6B_lC1CIDqCysSs3w-hA9727K6uV/view?usp=sharing

As you can see the behavior in chrome is slightly better than firefox in the sense that if you put the cursor in exactly the right spot you can drag the scroll bar downwards, but a little to the left or right of that you won't be able to drag the scroll bar downards or upwards, similar to the behavior in firefox.

It seems as if the area that you can click and drag the scroll bar is too small. In chrome it is very small and in firefox it is so small that you can never get the mouse in the right spot to click and drag to move the scroll bar.

This seems to be a bug and not a new feature request or an enhancement.

**Comment by catarak** [comment]
thanks for reporting! the videos are really helpful. i do know what is causing this—i had messed with the UX for the pane resize dragger a couple of weeks ago, and didn't notice this bug as i always use two finger drag to scroll.

**Comment by siddharthshah3030** [comment]
#818 
tried to fix this by changing display properties of resizer
if you want further enhancement or other modification to this issue then tell me

**Comment by siddharthshah3030** [comment]
#818

**Comment by chrisorban** [comment]
Is this now migrated to http://editor.p5js.org ? The behavior still seems the same to me on firefox. I still can't drag the scroll bar with the mouse. Issue is less bad with chrome.

**Comment by catarak** [comment]
@chrisorban not yet! some changes still need to be added to PR #818
