### ISSUE TITLE
Share>Fullscreen>Open vs fullscreen link, NO SOUND

### ISSUE THREAD

**Issue by lishap** [processing/p5.js-web-editor#798]
#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 71.0.3578.98 
- Operating System: Mac OSX High Sierra 10.13.6 (17G65)
- Steps to reproduce this bug: Try to play in fullscreen.

My sketch will not play sound when I use the link to copy and paste into the browser address bar. However, if I click open from the share fullscreen menu or play the sketch in the editing window, it does play.

https://editor.p5js.org/lishap/sketches/ryAJineZE
https://editor.p5js.org/lishap/full/ryAJineZE

**Comment by TireOnFire** [comment]
i got the same problems dude!!
