### ISSUE TITLE
Custom CSS Scrollbars to make the UI more seamless

### ISSUE THREAD

**Issue by anuraghazra** [processing/p5.js-web-editor#799]
- Existing feature enhancement
## New Scrollbars
![p5web](https://user-images.githubusercontent.com/35374649/50739221-18b18600-1203-11e9-97ef-8315e72fd309.png)

#### Feature enhancement details:
If those ugly scrollbars can be replaced with more Sleek looking (small) scrollbars then it will improve the UX and also those default scrollbars are HUGE in width which makes less room for other stuff.

it will make the UI consistent.

**Comment by GaurangTandon** [comment]
I can work on this issue. As far as I understand, resizing scrollbars or changing their colors is [supported](https://caniuse.com/#search=scrollbar) on all major desktop browsers (Firefox out of the box, all others with prefix `-webkit-`) except Edge.

Can a maintainer please describe exactly what color changes they would like, or should I submit an initial draft first?

**Comment by anuraghazra** [comment]
@catarak I'm currently using latest chrome in windows.

**Comment by catarak** [comment]
thanks @anuraghazra! i think this issue is way more relevant on windows/linux as on mac os the scrollbars are fairly minimal.

**Comment by GaurangTandon** [comment]
@catarak can this issue please be assigned to me? Also, do you have an initial idea in my mind, or should I submit an initial design first?

**Comment by catarak** [comment]
@GaurangTandon go ahead and work on this! i don't have an initial design, but yes, i think it would be helpful to have a design in mind. feel free to post references or wireframes!

**Comment by raclim** [comment]
We've had a few scrollbar-related PRs merged and in queue that I feel resolve this issue (ex. https://github.com/processing/p5.js-web-editor/pull/2161), so I'm going to close this for now!
