### ISSUE TITLE
Integrating prettier for uniform code formatting.

### ISSUE THREAD

**Issue by himanshuc3** [processing/p5.js-web-editor#800]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- [x] New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment]
this is already integrated in the editor, though perhaps a bit hidden! if you go to help -> keyboard shortcuts you'll see that the shortcut is shift + tab.
