### ISSUE TITLE
Add link to embed view (fullscreen, without header) to share modal

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#802]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Currently, the Share Modal links to an edit view, fullscreen view, and an embed iframe element. This should also include a embed view, without a header, which is what the embed iframe renders.

**Comment by LakshSingla** [comment]
I am unable to understand 'embed view, without a header'. Should one include `iframe` to display the content ? If so, what does 'without a header' imply.
