### ISSUE TITLE
Web Editor welcome experience

### ISSUE THREAD

**Issue by daaain** [processing/p5.js-web-editor#806]
#### Nature of issue?

- New feature request

#### Feature enhancement details:

I found P5.js via a Mozilla blog post: https://blog.mozilla.org/blog/2019/01/03/moss-2018-year-in-review/

In which it's described as:

> The Processing Foundation maintains p5.js, an open-source JavaScript framework that makes creating visual media with code on the web accessible to anyone, especially those without traditional computer science backgrounds. p5.js enables users to quickly prototype interactive applications, data visualizations, and narrative experiences, and share them easily on the web.

So I opened https://p5js.org/ and after reading the intro clicked on the link on the bottom to try the Web Editor.

What I was expecting is maybe some tutorial but definitely something a visual way of working, but what it ended up seeing is a minimal example and not much idea what to do:

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/69962/51213680-7fc1ef80-1913-11e9-9fb4-f3785da7f9db.png">

So what I'm proposing is creating some sort of welcome / beginner experience, be it a modal window with a short video embedded, an interactive tutorial, or a (moving) visual library of examples, but please make it not be just a blank grey background 🙏

**Comment by catarak** [comment]
@daaain i think this is a great idea! the web editor has mostly been used in conjunction with curricula/workshops/classes/etc. which has served this purpose. i made a [video](https://www.youtube.com/watch?v=x1rJJRVTpAI) that walks through the basic features, and i know @shiffman has made a few one-off shorter videos that show off features of the editor as well. 

if you have ideas/reference please add them here!

**Comment by LakshSingla** [comment]
I totally second this part. I also completely missed that arrow. 
> I totally missed the power behind the > left of sketch.js above the line numbers.
> I thought i was just some kind of graphical highlighter that had no function.
> Maybe it should be a different colour and have better tip text.
> ![screenshot_7](https://user-images.githubusercontent.com/121805/51218809-e1756e80-1992-11e9-8422-8203f602e992.jpg)

**Comment by shiffman** [comment]
I agree with all of the thoughts above! A model for this might be the Processing "Getting Started" tool created by @jaewhyun as part of last year's Google Summer of Code. For more, you can read her medium post [Making the Processing Development Environment Better for Beginners](https://medium.com/processing-foundation/making-the-processing-development-environment-better-for-beginners-a43302952f18). 

I think a web editor "welcome experience" would be an excellent project for a future GSoC, fellowship, etc. and would love to help however I can!

**Comment by catarak** [comment]
i think the focus would be the online editor, though it would be impossible to leave the basics of p5.js out. the current landing page for explaining the basic concepts of p5.js is hello.p5js.org

**Comment by hellonearthis** [comment]
I like the "Making the Processing Development Environment Better for Beginners" article.  
The welcome to processing model would make a very good interactive guide.
_I also think the reference tool is also very nicely formatted._

The hello.p5 would  be cool as a p5 editor interactive video.  
It would take less work to build than having something integrated into the p5 editor. 

Having better tooltips would be the easiest thing to do in the short term, I going to try and have a go at that.  But still learning GIThub and working out the process of working on an existing repo.

**Comment by catarak** [comment]
@hellonearthis let me know if you run into issues, and it's okay if the PR(s) are small! one fixed tooltip is better than no fixed tooltips 😸

**Comment by shakeabi** [comment]
I would like to have a go at this if no one is working on it. My suggestion would be to try something like this. 
[link](https://react-joyride.com/). This would be a great intro to the editor. Also we can set a flag in localstorage so that this tutorial happens only the first time a user opens the editor. What do you guys think?

**Comment by catarak** [comment]
@shakeabi i appreciate your enthusiasm for working on this, but i think before thinking about technically how to implement something like this, we need to think about this from a design perspective. 

also, i made a video that introduces the basic concepts of the editor—as a bare minimum, we could link to that.

**Comment by shakeabi** [comment]
@catarak are there any existing designs for this? Can I propose some?

**Comment by catarak** [comment]
there are not yet any designs for this—feel free to add ideas!

**Comment by catarak** [comment]
I'm going to roll this issue into #748. Still very much would like to brainstorm ideas for a p5.js Editor walkthrough of all of the features, ranging from recording a new walkthrough video to creating gifs to adding a JS library.
