### ISSUE TITLE
Accessibility - contrast

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js-web-editor#807]
#### Nature of issue?
The gray on gray doesn't have enough contrast.
![screenshot_8](https://user-images.githubusercontent.com/121805/51219109-3796e180-1994-11e9-97c1-7397cd3894fa.jpg)

#### Feature enhancement details:
Let users define their own colour palettes for the editor

**Comment by devashish1099** [comment]
i am looking forward to solve this issue
but i want to know how is that u propose that user define their own palettes

**Comment by catarak** [comment]
Thanks for the idea! I unfortunately don't think that giving users the ability to define their own themes makes sense for this project.
