### ISSUE TITLE
Cannot read property _id of null

### ISSUE THREAD

**Issue by LakshSingla** [processing/p5.js-web-editor#808]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Saving the client side code causes `nodemon` to restart, but crashes due to a MongoDB error, which can be rectified. I have seen an open PR about this issue. It causes slow development cycles (especially in case of client side code where frequent iterations are required, and undermines the whole point of using `nodemon`. It would be helpful if addressed immediately.

![screenshot from 2019-01-16 19-32-29](https://user-images.githubusercontent.com/30999375/51253873-99237400-19c5-11e9-920b-c155488086c3.png)

- Operating System: Ubuntu 18.04.1 LTS x86_64, Kernel: 4.15.0-43-generic
- Steps to reproduce this bug: Run `npm start`, and make a few changes on the client side and save the project

**Comment by catarak** [comment]
it's crashing because you didn't run the script that fetches the p5 examples—please run `npm run fetch-examples` and see if that fixes it.
