### ISSUE TITLE
Feature request: Auto-format

### ISSUE THREAD

**Issue by tigoe** [processing/p5.js-web-editor#81]
Processing's Auto-format is a godsend for teaching. Can we have it in the P5 editor too?

**Comment by catarak** [comment]
There's been a little bit of discussion around this in #16. This is a configuration option to CodeMirror so I think it shouldn't be too difficult to implement. Not sure what the design for this should be though, should it be just a keyboard shortcut, or also a button in the toolbar? My instinct is that it should be both.

**Comment by tigoe** [comment]
I agree with your instinct. Command-T is a reflex for me now.

Tom Igoe
--
sent on the go. please forgive any terseness or typos

**Comment by catarak** [comment]
The problem with using Command + T in the browser is that I think for many people it's the shortcut for creating a new tab. Codepen uses Shift + Tab, which could be a good option.

**Comment by catarak** [comment]
This has been added and deployed!
