### ISSUE TITLE
Docker image little problem.

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js-web-editor#811]
#### I am using the docker development environment.  Which is really nice apart from nodemon not working and having to restart after changes, but that's ok really as I have a problem with loading svg and sound in the popup windows like preferences (no + - or sound) and add files/folders having no exit as the X didn't load.

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Win 10 and Docker Engine - Community  Version: 18.09.1
- Steps to reproduce this bug:  docker-compose -f docker-compose-development.yml up
Where the image is supposed to be is `<span class="isvg failed"></span>`
![screenshot_3](https://user-images.githubusercontent.com/121805/51447449-229ac380-1d83-11e9-8963-130ca95f2081.jpg)

**Comment by catarak** [comment]
thanks for reporting! i don't have any experience developing on windows so i could use your help and patience. i'm wondering if this has to do with file system differences on mac/linux and windows...

**Comment by catarak** [comment]
i'm not sure about the SVGs not loading, but i think this is the issue for windows: https://stackoverflow.com/questions/39239686/nodemon-doesnt-restart-in-windows-docker-environment

can you try changing the `start` script in the `package.json` to add `-L` after `nodemon`, i.e. `cross-env BABEL_DISABLE_CACHE=1 NODE_ENV=development nodemon -L index.js`

**Comment by hellonearthis** [comment]
Will try that out,  I am guessing the when using the docker image on a Mac there are no graphic issues.
Been kind of busy to test this and to learn the finer details of docker, so won't get to try this out until next week.

**Comment by catarak** [comment]
no worries! getting development environments set up can be tricky.

did you run the command `docker-compose -f docker-compose-development.yml run --rm app npm run fetch-examples`?
