### ISSUE TITLE
Hello P5: Song example playing song with Right Button

### ISSUE THREAD

**Issue by nucliweb** [processing/p5.js-web-editor#816]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: 
-- Chrome 71.0.3578.98
-- Firefox 64.0
-- Safari 12.0.2
- Operating System:  MacOSX Mojave 10.14.2
- Steps to reproduce this bug:
-- Open example **Hello P5: song**
-- Click with the right button
-- You can hear the sound and see the context menu
-- If you click out of context menu, the menu disappears but the sound continuous playing

#### Video
📺 [Hello-P5-Song.mp4.zip](https://github.com/processing/p5.js-web-editor/files/2796932/Hello-P5-Song.mp4.zip)

#### Feature enhancement details:

To fix this bug, you need change this code.
```
// When we click
function mousePressed() {
  // Map mouse to the key index
  var key = floor(map(mouseX, 0, width, 0, notes.length));
  playNote(notes[key]);
}
```

To this other code.
```
// When we click
function mousePressed(event) {
  if(event.button == 0 && event.clientX < width && event.clientY < height) {
    // Map mouse to the key index
    var key = floor(map(mouseX, 0, width, 0, notes.length));
    playNote(notes[key]);
  }
}
```

> I would send a PR, but I don't know where are the examples files  😅

**Comment by catarak** [comment]
hi! thanks for reporting. the p5 examples are in [p5 website](https://github.com/processing/p5.js-website) repository. i'll move this ticket over there 🌈

**Comment by catarak** [comment]
copied as https://github.com/processing/p5.js-website/issues/380
