### ISSUE TITLE
P5 example "Typography: word" not working 

### ISSUE THREAD

**Issue by maartenwijntjes** [processing/p5.js-web-editor#820]
The example https://editor.p5js.org/p5/sketches/rJZlz4ly7_m gives this error message:

> Font could not be loaded:  https://rawgit.com/processing/p5.js-website/master/dist/assets/examples/assets/SourceSansPro-Regular.otf

Seems weird because
1) The link works
2) The actual link in the code is to the asset folder, which also contains a font

**Comment by limzykenneth** [comment]
From what I can tell it seems there's something wrong with the font, can you try another one see if that works?

**Comment by catarak** [comment]
the issue here is that rawgit has been sunset—the examples need to be updated to use a service besides rawgit!

**Comment by limzykenneth** [comment]
I forgot about this but yes I found this across a lot of the sketches under the p5 account, lots of the assets are all trying to pull from rawgit.
