### ISSUE TITLE
recover a possible lost file?

### ISSUE THREAD

**Issue by andytilia** [processing/p5.js-web-editor#821]
I'm a teacher with students using the p5.js web editor. She lost a file from "My Sketches". We've done standard troubleshooting to get it back, with no luck.  I won't dismiss that it could be due to user error, so I don't want to send anyone on a wild goose chase -- just want to see if is this an issue already reported or any known recovery steps? Thanks in advance - Andy

**Comment by jaytay579** [comment]
I also have just encountered this error twice in a row. I saved a sketch and suddenly the code reverted to a previous version. I then added a lot more code to the sketch and things worked fine, but as soon as I introduced an error into the program, the code again reverted -- this time to the previous version of the code that had been lost in the prior reversion! So, there definitely seems to be a high-priority bug to be written up here...

**Comment by shiffman** [comment]
I think this may be related to #790? Thanks for your patience, I can imagine how frustrating this could be and hopefully we'll be able to sort out the bug, it may be a little while though... feel free to reach out anytime if I can help in any way.

**Comment by catarak** [comment]
this is definitely related to #790! i'm going to prioritize working on fixing this issue—i've been traveling but now am back and can work on this.

**Comment by andytilia** [comment]
Great - thanks! The scenario in #790 happened to me yesterday as well.

Meanwhile my student has recreated her lost file, so no need to hunt for that specific case.

**Comment by MIR-SJ** [comment]
@catarak  Hello, I'm not sure if this is still open, but I deleted my file accidentally.
It was my first ever proper project which I shared, hosted on P5js itself. It would mean a lot if it could be recovered.
Please get in touch so I'll be able to share the information for that. I'll really appreciate the help if recovery is possible. Thank you
