### ISSUE TITLE
"Add file" and "Add folder" don't work in side menu

### ISSUE THREAD

**Issue by lobertrand** [processing/p5.js-web-editor#825]
The "Add file" and "Add folder" options aren't working for me from the side menu.

#### Nature of issue?
- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome | 71.0.3578.98 (Build officiel) (64 bits) (cohort: Stable)
- Operating System: Windows 10
- Steps to reproduce this bug:
  - Click on the ">" right arrow to open the side menu
  - Click on the "v" down arrow and click on "Add file" or "Add folder"

**Comment by farhan787** [comment]
Both "Add file" and "Add folder" are working fine from the side menu. I think you may have some other issues like internet connection or it may be a browser issue.

**Comment by lee2sman** [comment]
Hi, I have been able to reproduce this in Firefox and Chrome. Appears to be a new bug? It happens when I am not logged in.

Choosing Add File and Add folder produce the "enter filename" dialogue but don't appear to work.

**Comment by catarak** [comment]
thanks for reporting! i tried the add file and add folder options while not logged in, and it's still working for me. can you add more details about how to reproduce? for example, does this happen if it's a new sketch, if you're logged in, if the sketch already exists. etc.

**Comment by meiamsome** [comment]
Oh, come to think of this, perhaps this is a side-effect of #837 ?

**Comment by catarak** [comment]
@meiamsome could be! though i think if a user is not logged in, then that code wouldn't be called.

**Comment by meiamsome** [comment]
@catarak Yeah, in that case it wouldn't be called, @lobertrand didn't specify if they were logged in with this problem or not, though, so maybe they were. That said, I don't think we should assume they are related, so I'd suggest leaving this open in case anyone can reproduce the issue for the time being?

**Comment by catarak** [comment]
@meiamsome i agree!

**Comment by lee2sman** [comment]
Here's some more info. If I open a new private window and open the editor page but don't login (I'm testing with Chrome and Firefox)  and I choose add file or add folder, I am able to get that to work without having logged in. I don't have an option to upload an image (Maybe that's an intentional choice? if so, might want to have the dialogue box say 'Log in to be able to upload media files'). I'm not sure if this matches original poster's issue exactly.

![screen shot 7](https://user-images.githubusercontent.com/7377908/53130484-60346d00-3538-11e9-9941-ad16aa841f11.png)

**Comment by lobertrand** [comment]
The problem occurred whether I was connected or not, my internet connection was fine and it happened for several days in Chrome, Edge and Firefox. But now it seems to work again ^^

**Comment by catarak** [comment]
thanks for the details! it seems like this bug is not currently reproducible, so i'm going to close this ticket for now. if it happens again, please reopen this issue!
