### ISSUE TITLE
p5 version not updated

### ISSUE THREAD

**Issue by sanketsingh24** [processing/p5.js-web-editor#826]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Probably the version on web editor is somehow still v0.7.2, while the current p5 version is v0.7.3.

- Web browser and version: chromium 71.0.3578.98  
- Operating System: Arch Linux (64-bit)
- Steps to reproduce this bug:
use `circle()` or `square()` (For some reason i was not able to log in)

**Comment by icq4ever** [comment]
open closed issue here. (check below link)
https://github.com/processing/p5.js/issues/3512

**Comment by hellonearthis** [comment]
This can be updated by the user via the index.html
<img width="1386" alt="screenshot_19" src="https://user-images.githubusercontent.com/121805/52635669-5e165100-2f2f-11e9-8a67-4b50c96846cb.png">

**Comment by icq4ever** [comment]
@hellonearthis good to know that :)

**Comment by sanketsingh24** [comment]
@hellonearthis I think that way is not beginner friendly, and we should be responsible for the version update stuff

**Comment by rozim** [comment]
Ditto, reproduced, a simple sketch that calls circle(10, 10, 10) fails with
"Uncaught ReferenceError: circle is not defined...".

**Comment by catarak** [comment]
thanks for reporting! i agree with @sanketsingh24, that changing the version in the index.html is not beginner friendly. it would be great if this version updated automatically (see #144, in which it took me forever to figure out a real solution, which has not yet been implemented). for now, i will update this manually 😄 

also, i think this points to more support of #4—it would be great if you could see all of your "installed" js libraries easily for a sketch!

**Comment by davidluckyvr** [comment]
Circle is still not defined in the web editor. Giving a reference error.

**Comment by catarak** [comment]
@davidluckyvr have you tried updating the p5.js version of the specific sketch you're working on? the p5.js version will only be updated for new sketches.
