### ISSUE TITLE
customize the editors cursor

### ISSUE THREAD

**Issue by hellonearthis** [processing/p5.js-web-editor#829]
The ability to customize the cursor would help with accessibility.
Like VS Code being able to select **block, block-outline, line, line-thin, underline, or underline-thin**

Also selecting the colour of the cursor would be help too as it's got zero contrast to much of the sketches text.

**Comment by catarak** [comment]
For me, one of the driving principles of the web editor is not adding a ton of configuration options. Would it instead make sense to change the cursor by default in the high contrast theme? Do you have an idea as to what a good default style for the cursor would be?

**Comment by hellonearthis** [comment]
Making it 2px wide and 'red' would be a good start if it was part of the high contrast theme.

<img width="106" alt="screenshot_35" src="https://user-images.githubusercontent.com/121805/53131843-c968be80-35d2-11e9-851b-56eb4e467c23.png">

**Comment by catarak** [comment]
You can change the style of the cursor using CodeMirror: https://codemirror.net/doc/manual.html#styling, and then scroll to 'CodeMirror-cursor'

**Comment by catarak** [comment]
I believe this was addressed in the big accessibility overhaul i did ~1yr ago. Please reopen or open a new issue to request more changes!
