### ISSUE TITLE
File missing in amplitude analysis sound example

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js-web-editor#830]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

File missing in amplitude analysis sound example:
https://editor.p5js.org/p5/sketches/S1EgmNgJXuQ

the file assets/lucky_dragons_-_power_melody.mp3 does not exist and causes the editor to crash when the sketch is run.

- Web browser and version: 

Firefox 64.0.2 
Google Chrome | 72.0.3626.96 (Official Build) (64-bit)

- Operating System: 
os X 10.13.4

- Steps to reproduce this bug:

try to run the amplitude analysis sound example

**Comment by catarak** [comment]
thanks for reporting! i'm pretty sure this is due to the sunsetting of rawgit. also reported in #820.
