### ISSUE TITLE
Page Crashes Under certain console.error situations

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js-web-editor#833]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
- Steps to reproduce this bug:

Any call to `console.error` where the first argument is not a string will cause a crash.
This includes all of the following:
`console.error()`
`console.error({})` // any object that doesn't support `indexOf`
`console.error({}, 'A string here')`

In particular, some parts of p5 will call `console.error` with an Error object (or sometimes generic other objects) as the first argument.

This is a more generic version of one of the problems in #831

**Comment by Janglee123** [comment]
just for sake of information, passing number inside `console.error()` is one more reason for crashing editor.
