### ISSUE TITLE
additional tabs

### ISSUE THREAD

**Issue by Judithricketts** [processing/p5.js-web-editor#835]
#### Nature of issue?

- Found a bug
- Existing feature enhancement
- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### New feature details:

**Comment by catarak** [comment]
hi @Judithricketts! can you go into more detail about what you are requesting? there isn't enough here for me to figure out what you are suggesting. thanks!

**Comment by Judithricketts** [comment]
Apologies, this was a mistake - regards Judith
