### ISSUE TITLE
p5.js Web Editor crashing

### ISSUE THREAD

**Issue by CTeam30** [processing/p5.js-web-editor#840]
- Found a bug

#### Details about the bug: 

when adding ';' to the line    'for (game.level; game.level = game.level + 50____)'    in the space marked with ___  and run the code. The page will crash and has to be restarted.

- Web browser and version: Chrome 72.0.3626.109 (Official Build) (64-bit) (cohort: Stable)
- Operating System: Windows 10 Home, Version 1803
- Steps to reproduce this bug:
add ';' to the line 'for (game.level; game.level = game.level + 50____)' in the space marked with ___ and run the code. The page will crash and has to be restarted.

No crash:
for (game.level; game.level = game.level + 50)

Crash:
for (game.level; game.level = game.level + 50;)

also crashes with:
for (var x =game.level; x =game.level;) {

}

**Comment by Sunomikey** [comment]
What's your expected outcome here? 

The reason your page is crashing is most likely due to an Infinite loop. The for loop is expecting 

```
for (init; test; update) {

}
```

The most basic for loop will need:
```
for(var x = 0; x < 10; x= x+1){
}
```

There are some more advanced versions of this but I don't think that's what you're going for here.

**Comment by CTeam30** [comment]
ohh ok thank you.

I was attempting to draw a rectangle every time the level went up but I can see why what I wrote created an infinite loop.
