### ISSUE TITLE
Multiple Files of the Same Name in folders

### ISSUE THREAD

**Issue by meiamsome** [processing/p5.js-web-editor#842]
#### Nature of issue?
- Found a bug

#### Details about the bug: 
When there are two files with the same name but in different folders, the frontend UI can get confused and overwrite the wrong file contents.

- Steps to reproduce this bug:

1. Create a new project
2. Add a folder
3. Create file 'style.css' inside the folder, and add some contents and save
4. The contets of 'style.css' in the root folder are the same as those you just created in the subfolder

**Comment by catarak** [comment]
thanks for reporting! i would assume there's some code that checks which file to update by name and not by the full path and/or id.

**Comment by meiamsome** [comment]
@catarak yep, that is the case - is it safe to assume a file in redux will always have an attached unique `id`? I have a PR to change this to be id-based but I don't know if there will be such cases where there is no id?

**Comment by catarak** [comment]
@meiamsome yes, the id's should be unique! it uses the mongodb objectid's, which are generated client side
