### ISSUE TITLE
npm run clean and npm run start fails (cross env is not recognised as a command)

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#852]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
npm run clean and npm run start fails in powershell (Windows)
- Operating System: 
Steps to reproduce
1. Run npm run fetch-examples on a new fork

![image](https://user-images.githubusercontent.com/30566406/53620252-4c63c780-3c18-11e9-8c2e-9eb35fa356f6.png)

**Comment by siddhant1** [comment]
Looks like we have to hit npm install first 
I think we should mention it somewhere in readme.md. This should be in readme instead of https://github.com/processing/p5.js-web-editor/blob/master/developer_docs/installation.md

**Comment by catarak** [comment]
The installation guide is mentioned in the README, though it's indirect. There's a link to the developer docs, which is the README in `developer_docs`, which links to the installation guide. Maybe the copy in the root README can be more clear—something like, "contributors, start here!".

**Comment by siddhant1** [comment]
Yeah sure that'll good , I think we should also add a list of starting steps in the readme to make it beginner friendly
Something like this
# Setting up the project
This project requires Node.js version >= 8.10 and yarn

Install dependencies
`yarn`
Run development
`yarn start`
Deployment
`yarn build`

**Comment by catarak** [comment]
i don't think it should be added to the root README! i had the installation instructions in there for a while, but it got way too long. in my opinion, the point of the root README is to be a landing page for the project, and adding the installation instructions are too detailed.

**Comment by siddhant1** [comment]
So should we make a link saying "contributers here" and link them to the installation instructions.

**Comment by catarak** [comment]
i just added another link to CONTRIBUTING.md and the root README. if think it should be clearer, feel free to make a PR, but it's under the section "Get Involved", so i'm not sure how to make it more clear than that.
