### ISSUE TITLE
Add husky to prevent committing poorly formatted code

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#854]
I think we should add a pre-commit hook to lint-staged files to prevent committing poorly formatted code

**Comment by catarak** [comment]
there's already linting checks integrated into travis ci, which get run every time a commit is pushed to github. what's the benefit of using husky too?

**Comment by siddhant1** [comment]
Husky runs every time when user commits , Travis ci runs when he makes a pull request.

Adding husky will let the user know about the mistakes on committing.
Also we can use `prettier --write` to autoformat the code on committing according to .prettierrc

**Comment by catarak** [comment]
i can see the benefit of this, but for this project, i don't think it makes sense. p5.js and the p5.js web editor attract a lot of folks with a variety of programming experience, and a lot of times new contributors will make [wip] pull requests, which i think is totally cool if there are linting errors. to me, this is not a big issue that this project is having, and i think the costs outweigh the benefits.

**Comment by siddhant1** [comment]
I think this makes sense , thank you for reviewing
