### ISSUE TITLE
Give signin with google and signin with github options on the signup page

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#855]
We should give sign in with google and sign in with github options on signup page because the user first creates an account and then he will sign in.
If there are no options present in the signup page , he will create a normal ID

**Comment by catarak** [comment]
agree! i don't think it's totally clear you can sign up with google/github. i think there's a few things that could be cleaned up with the authentication flow in general 🌈

**Comment by siddhant1** [comment]
Can you tell me what should I do to clean up the flow?

**Comment by catarak** [comment]
there's a few other open tickets:
- #760
- #695 - possibly related to some weirdness with connecting email/pw accounts with oauth accounts

**Comment by siddhant1** [comment]
Both of the tickets seem inactive , should I refactor it and send another pr?

**Comment by siddhant1** [comment]
Also I think we shoudl include checking of the previous session on refresh , once you login and refresh it logs you out .

**Comment by catarak** [comment]
This has been fixed!
