### ISSUE TITLE
Enhancement :- Move from momentjs to date-fns to improve performance

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#858]
This is a very small enhancement in the editor but I we should use date-fns over momentjs because it is super small and imporves performance.

Links :- https://twitter.com/addyosmani/status/1037587112730611714?lang=en

**Comment by catarak** [comment]
for how little this project uses momentjs, i agree, i think this is a great idea. hopefully would even be too hard!

**Comment by siddhant1** [comment]
Working on this and sending a PR!

**Comment by siddhant1** [comment]
Closing ! Fixed
