### ISSUE TITLE
Bug : Login with github and login with google fails

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#863]
Screenshots attached:
![screenshot from 2019-03-03 12-49-57](https://user-images.githubusercontent.com/30566406/53692324-9339f480-3db3-11e9-8ab0-5cbddc427fac.png)
![screenshot from 2019-03-03 12-50-17](https://user-images.githubusercontent.com/30566406/53692325-9503b800-3db3-11e9-804c-e37b3c3666ce.png)

**Comment by LakshSingla** [comment]
Is this on your localhost ?

**Comment by siddhant1** [comment]
Whoops ! Looks like it was the problem ! Thanks for claryifying

**Comment by dhruvdutt** [comment]
@siddhant1 I'm also facing some similar issue. What's `GITHUB_ID` and `GITHUB_SECRET`? Do we need to create a personal access token or an OAuth app from GitHub?

**Comment by catarak** [comment]
@dhruvdutt you need to create an OAuth app on Github. That will give you a `GITHUB_ID` and `GITHUB_SECRET`, and you'll need to fill in a callback url (http://localhost:8000/auth/github/callback).
