### ISSUE TITLE
Option to tag the sketches

### ISSUE THREAD

**Issue by LakshSingla** [processing/p5.js-web-editor#864]
#### Nature of issue?
- New feature request

#### New feature details:
Option to create tags (custom defined) and tag the sketches (#231), so as to categorize them and increase the ease of use for users with a large amount of sketches. (Credit @slowizzm). Goes hand in hand with the search feature.
I believe that there is an existing issue (#557), but it does not quite talk about tags being a separate entity from the sketch name itself. @catarak If you like, I could work on a preliminary layout after while. It would require some design expertise (how to display tags for the current sketch, how to add and remove tags to current sketch, and maybe how to display tags in the `SketchList`)
On the other side, we can include tags in the name of the sketch itself, whichever seems to be more convenient feature.

**Comment by catarak** [comment]
i'd be curious to discuss whether it makes sense to add tags, or implement #43, or both. for me, one principle of the web editor is less is more, so i think it's worth thinking about how these features are related. #43 is a high priority issue to be worked on in the near future, so it's important to have this discussion now.

**Comment by shiffman** [comment]
I am not sure whether "tags" or "folders" or "collections" or all of the above is the right terminology or implementation either! For me, the two main things I see a need for are:

1. A way for me to organize a group of sketches in my own account into a "collection" or "folder" that can be viewable from a single link. An example of this is "Nature of Code book examples" or "All Coding Train coding challenges". Subdirectories / subscollections could also be nice, but maybe that's too much for a first implementation.
2. A way to organize a group of sketches from across different accounts. For example, I would love to be able to collect all student sketchees for a given homework assignment and see them at a single link.

(1) above is probably highest priority for me but maybe for others (2) is more important. Is there a single implementation that could cover both?

The tricky thing re: (2) is if we share sketches in a "collection" across multiple accounts -- who owns/curates the collection and how are permissions to add sketches allowed? Maybe you can create collections in your own account and if you want to add a sketch from someone else's account to the collection they have to approve?

Tags would be a simple low-fi way of doing this: "Hey! tag all your sketches _Shiffman_week1_homework_2019_" or something like that?

**Comment by catarak** [comment]
@shiffman thanks for breaking this down! sometimes it's hard to separate "user stories" from "implementation", and focusing on collections/tags feels like focusing on implementation. i think it would be helpful to think about incrementally implementing these features rather than focusing on implementation details, which will then help figure how what is necessary here.

**Comment by catarak** [comment]
I'm going to fold this into an issue opened earlier.
