### ISSUE TITLE
resizing console only comes into effect after re-engaging with the code editor window

### ISSUE THREAD

**Issue by bmoren** [processing/p5.js-web-editor#865]
#### Nature of issue?

The console must be tied into the update of the codemirror editor. when resizing the console, it will only accept the resize when re-engaging with the editor. 

- Found a bug

#### Details about the bug: 

- Web browser and version:  FF 65.0.1 (64-bit)
- Operating System:  MAC OS 10.13.4
- Steps to reproduce this bug: 
1. drag up the console to a new size
1. it will snap back to its original position
1. make a line return in the code editor
1. the console will snap to the position you chose previously.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1385996/53742568-8de5b400-3e5e-11e9-8c5a-65f958981a4e.gif)

**Comment by catarak** [comment]
i've noticed this, but haven't figured out steps to reproduce, so thanks for this!

**Comment by siddhant1** [comment]
Will investigate and fix !
