### ISSUE TITLE
Logging in with github account logs you in as aparrish

### ISSUE THREAD

**Issue by mimiyin** [processing/p5.js-web-editor#87]

**Comment by catarak** [comment]
Wow, that's really strange. I'm not able to reproduce this, can you tell me

- did you have an account previously, before you tried to log in with github?
- the email/username of the github account you tried to login with
- were you using your own computer or a shared computer?

**Comment by mimiyin** [comment]
I was able to repro with my github account.
I had an account already under mimi.yin@nyu.edu
But several students in my class reported it and they didn't already have accounts.

**Comment by shiffman** [comment]
I can confirm that this just happened to me, tried with two github accounts.

**Comment by catarak** [comment]
Okay, it seems like it's an issue when a user doesn't have an account yet and tries to login with Github. For now, I'll just remove logging in with Github, figure out why this is happening, and readd it.

**Comment by aparrish** [comment]
hahahahaha

**Comment by Akarshit** [comment]
I tried this in production, but am unable to reproduce this. I confirmed that the user doesn't have a account while doing sign-in.

**Comment by catarak** [comment]
I think the issue is if a user doesn't have a public email--the github oauth needs to be configured to get the user's email even if they have not made it public.

**Comment by shiffman** [comment]
end of an era
