### ISSUE TITLE
Menu hiding Main Navigation Tabs

### ISSUE THREAD

**Issue by nimishagarwal76** [processing/p5.js-web-editor#871]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 70.0.3538.77 (Official Build) (64-bit)
- Operating System: Ubuntu 18.04.1 LTS

#### Bug details:
![screenshot from 2019-03-06 22-00-23](https://user-images.githubusercontent.com/37630020/53899201-ae309100-405f-11e9-8154-f9ef3bedc3d2.png)

I am not sure if this was intended this way, but would definitely be better if the main-navigation dropdown opened a little below so that it does not hide other tabs.

**Comment by catarak** [comment]
thanks for reporting! i agree that this UX could be improved.

**Comment by siddhant1** [comment]
@catarak Since I picking up on this one , what kind of design change you'd expect

**Comment by nimishagarwal76** [comment]
@siddhant1 apart from design changes I think some functionality changes would also be required. Even if you margin the menu down you would be required to click on a menu twice to open it. Once for closing the already opened menu and other for opening the required menu.

**Comment by siddhant1** [comment]
I think we can just space out stuff when the drop-down is on

**Comment by catarak** [comment]
i don't like the idea of spacing the nav items when the dropdown is open. i think they should be that spaced out to begin with, or the dropdown should open below the item, or the dropdown should be reshaped so it doesn't hide the other items. i'm not a ui/ux designer so i'm open to input on which of these is best.

**Comment by nimishagarwal76** [comment]
I feel that putting dropdown below the item is generally followed and a better idea. Google Docs follow the same.

**Comment by catarak** [comment]
i like the google docs dropdown design. i like that when you open one of the dropdowns, and then hover to another top level item (e.g. from "File" to "Edit"), the dropdown under the next menu item will open.
