### ISSUE TITLE
Center sketch in "Present" mode

### ISSUE THREAD

**Issue by Whitevinyl** [processing/p5.js-web-editor#872]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

I think it would be nice if the canvas was centered in the browser when using the Present mode (file > share). It's visually more pleasing and makes a bit more sense if demoing a sketch on large screen/projector.

The following kind of styling should center small canvases, while still allowing much larger canvases to be scrolled:

A container styled with:
    display: flex;
    min-width: 100vw;
    min-height: 100vh;

And the canvas styled with:
    margin: auto;

**Comment by catarak** [comment]
thanks for the suggestion! this has come up before, and my opinion is that this can be more harm than help, as i'm sure there are plenty of times that folks _wouldn't_ want the sketch to be centered. my suggestion for this is to edit the sketch's CSS so that the canvas is centered on the page.

**Comment by Whitevinyl** [comment]
Ah cool - I've since discovered the lefthand folder view (had no idea that was there!) with the css & html, and it makes much more sense to me now why it is how it is. Thanks!
