### ISSUE TITLE
Unnecessary Scroll Bar

### ISSUE THREAD

**Issue by nimishagarwal76** [processing/p5.js-web-editor#885]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome 70.0.3538.77 (Official Build) (64-bit)
- Operating System: Ubuntu 18.04.1 LTS
- Steps to reproduce this bug:

There always exist an unnecessary scroll bar in the file-navigation which is only needed when files exceed the div. We can just change the  ```overflow:scroll``` to ```overflow:auto``` to resolve. @catarak what are your views regarding it.

If it is to be changed I will send a PR then.

![Screenshot](https://user-images.githubusercontent.com/37630020/54298886-adf44080-45df-11e9-96b6-02d080cedd87.png)

**Comment by catarak** [comment]
thanks for reporting! i'm also seeing this scrollbar appear on Windows. feel free to fix this issue.
