### ISSUE TITLE
Hover effect on sidebar elements

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#886]
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System:  Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
add hover effect on side bar elements
![Capture](https://user-images.githubusercontent.com/28510494/54337007-9e164400-4653-11e9-8428-30dc5c442e74.PNG)

Earlier there was no hover effect on sidebar elements like "remane" or "delete"

**Comment by catarak** [comment]
thanks for reporting! yes, this is in the design and hasn't been implemented yet.

**Comment by plxity** [comment]
I have added a Pull request for the same. Please review it @catarak.

**Comment by catarak** [comment]
@plxity currently working on a review!
