### ISSUE TITLE
Add eye button to see password in login form

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#888]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
Add eye button to see the password in the password field like usual login / signup form
![Capture](https://user-images.githubusercontent.com/28510494/54338053-d3706100-4656-11e9-85ca-401c3766db8f.PNG)

#### New feature details:

**Comment by catarak** [comment]
thanks for reporting! this feels useful, but also not high priority or urgent.

**Comment by plxity** [comment]
@catarak Yes Okay. I'll all the Pull request for the same.

**Comment by AnkurIngale** [comment]
@plxity Can i do it?

**Comment by plxity** [comment]
@AnkurIngale Actually, I have already started working on this.

**Comment by catarak** [comment]
@plxity this project is using an icon set called Modern Pictograms, make sure you use the eye icon from that! it's not free, so i can send you the icon if you need it.

**Comment by plxity** [comment]
@catarak Okay I will use that. Please send me the icon.

**Comment by catarak** [comment]
here it is! https://www.dropbox.com/sh/i3sq7y4jy16znur/AABqsv2KaSgRoQ95yDwGG6-Ua?dl=0

**Comment by plxity** [comment]
@catarak I need two different types of eye SVGs. One you send can be used when the password is visible. I need one more when the password is not visible. Please send that too.

**Comment by catarak** [comment]
hmmm, that's not part of the modern pictograms icon set. i did a little UX research about this, and i think it would be better to (1) change the button to say "Show" or "Hide" or (2) have a checkbox that says "Show password" under the form.

**Comment by plxity** [comment]
@catarak Okay sure, I will figure that out. :)

**Comment by EkaanshArora** [comment]
Hey @plxity, it's been a while, you still working on this?

**Comment by plxity** [comment]
@EkaanshArora Actually, I was working on other issues. Yes, I am working on it. WIll send a PR by Tomorrow.

**Comment by shakti97** [comment]
is it still open? If no, I would like to work on it
