### ISSUE TITLE
Add minimum length of at least 6 characters for password

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#889]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
As of now, the user can signup with 1 character length also, at least a minimum of 6 character length should be there for making application more strong

**Comment by catarak** [comment]
thanks for reporting! i agree that this is a good idea and important.

**Comment by plxity** [comment]
@catarak I will add the Pull request for the same.
