### ISSUE TITLE
can't click away from dropdown menus with project-folder sidebar 

### ISSUE THREAD

**Issue by justinpeake** [processing/p5.js-web-editor#89]
didn't want to select either and tried to click out of it by accessing the chevron but was hidden.

![screen shot 2016-09-07 at 1 39 22 pm](https://cloud.githubusercontent.com/assets/8682347/18322119/12ce3f24-74ff-11e6-8ba6-06cf69f90aeb.png)

**Comment by catarak** [comment]
This is an issue on both Safari and Firefox, but not Chrome, from the blur event not firing. I think this can be fixed by adding a tab index to the dropdown buttons.
