### ISSUE TITLE
Integrate surge links within the project

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#894]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version:  Chrome
- Operating System:  Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
Adding surge will provide a smooth option for the other contributors and mentors/reviewer to check the changes made by the person. Adding this will be beneficial for the long run.

#### New feature details:

**Comment by plxity** [comment]
@catarak What do you think about this feature?

**Comment by catarak** [comment]
what is surge?

**Comment by plxity** [comment]
@catarak  Check this surge implementation by Fosassia 👍 https://github.com/fossasia/accounts.susi.ai/pull/724 (It is implemented in every fossasia project)

If you submit a PR, Just mention your PR number in the link and it will create the website with the changes you have made in a PR. Mentors can easily check what changes are made by the contributor.

**Comment by catarak** [comment]
ah cool! as a place to stage changes. that would be super cool!

**Comment by plxity** [comment]
@catarak Can I work on this?

**Comment by catarak** [comment]
sure! i think the first step is making a plan, since the staging will need to integrate with a lot of different services.

**Comment by plxity** [comment]
@catarak Yes, I agree.  So how to proceed with that?

**Comment by plxity** [comment]
https://blog.fossasia.org/auto-deployment-of-pull-requests-on-susper-using-surge-technology/
@catarak  Please read this once.

**Comment by catarak** [comment]
you tell me! this project already integrates with travis and builds a docker image.

**Comment by siddhant1** [comment]
I had an opinion on this , personally I feel we should surely add a service to deploy on every pr and I have tried netlify , it's continuously integration is super good and deploys within seconds and super easy to setup

**Comment by plxity** [comment]
@siddhant1 We can use netlify(Both are same), but I have experience with surge and find its implementation easy.
