### ISSUE TITLE
Repetition in Console after changing "Accessible text-based canvas" options.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#896]
#### Nature of issue?
Repetition in Console after changing "Accessible text-based canvas" options.

<img width="1140" alt="Screenshot 2019-03-15 at 8 29 08 PM" src="https://user-images.githubusercontent.com/33569473/54440590-0737ad80-4761-11e9-95ed-1bf8ccd7e94f.png">

- Found a bug

#### Details about the bug: 

- Web browser and version: On Chrome
- Operating System: MacOSX
- Steps to reproduce this bug:

Clear the console after every change.

@catarak please express your views on it.

**Comment by catarak** [comment]
thanks for reporting! this is definitely a bug.

**Comment by shakeabi** [comment]
I would like to take a swing at this if no one's working on it.

**Comment by AnkurIngale** [comment]
@shakeabi Sorry but I am working on it.

**Comment by shakeabi** [comment]
No problem. General Doubt: @catarak should we push package-lock.json while giving a pr?

**Comment by catarak** [comment]
@shakeabi if you change or add an npm library, then you should change `package-lock.json`. to prevent your `package-lock.json` from changing for other reasons, make sure you're using the node/npm versions specified in `package.json` (under "engines").
