### ISSUE TITLE
Fetching file contents from JavaScript does not return correct content

### ISSUE THREAD

**Issue by yanickrochon** [processing/p5.js-web-editor#897]
#### Nature of issue?

- Found a bug

- Steps to reproduce this bug:
1. Create a new project, 
2. Add a new file (ex: `async-file.js`)
3. Edit that file with anything
4. Go to the file URL (using another tab), for example : `https://editor.p5js.org/<user_name>/sketches/<sketch_id>/async-file.js`
5. Go back to the editor and modify `async-file.js`
6. Save the whole project
7. Go back to the other tab displaying the content of `async-file.js` and refresh (F5)
8. The content has not changed.

This issue still occurs if all browser cache is disabled, or cleared, etc. The file content does not reflect the content in the editor.

**Comment by catarak** [comment]
thanks for reporting! i am seeing this issue. i wonder what's going on here...

**Comment by yanickrochon** [comment]
I added an URL GET parameter, and it seems to fix the problem. It is perhaps server caching?

**Comment by catarak** [comment]
i think it must be a serving caching issue.

**Comment by yanickrochon** [comment]
As far as I can tell, it seems like the files are stored on AWS, and directly accessing a project file through GET URLs make an internal redirect to AWS. Is it possible that the content of the file is not correctly updated on the remote server? Or perhaps AWS performs caching on it's own there.

See [`project.controller.js`](https://github.com/processing/p5.js-web-editor/blob/f8ee62a1b5e3c4e9b2e1dc5446a7250c5fd10d34/server/controllers/project.controller.js#L172)

**Comment by catarak** [comment]
small, plaintext files are not stored on AWS but are instead stored in mongodb

**Comment by siddhant1** [comment]
I will take this @catarak , will try to investigate and fix

**Comment by GaurangTandon** [comment]
@siddhant1 	If you're not working on this issue, may I take it up?

**Comment by siddhant1** [comment]
Still working on this :)

**Comment by catarak** [comment]
Fixed by #1234.
