### ISSUE TITLE
Passwords do not match error in signup page is not intuitive

### ISSUE THREAD

**Issue by shakeabi** [processing/p5.js-web-editor#906]
#### Nature of issue?

- Found a bug

The passwords do not match error in signup page is not intuitive.

All other error messages popup only after the respective fields are filled in.
However, 'passwords do not match' error pops up immediately after the focus of the password field is blurred. This is slightly non-intuitive and irritating. I think this error should come up only after,
1. the user has entered the confirm password field and
2. removed the focus of the same field.

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Ubuntu 18.04

@catarak what are views on this?
PS: Would like to work on this...

**Comment by catarak** [comment]
thanks for reporting!

**Comment by GaurangTandon** [comment]
@catarak I already sent out a PR, please check it out :)

**Comment by shakeabi** [comment]
@GaurangTandon Please check for claims before giving a PR

**Comment by shakeabi** [comment]
@GaurangTandon Also I believe its better to check for the existence of confirmPassword before the equality check and keeping the error in error.password makes it dynamic.

**Comment by GaurangTandon** [comment]
> Please check for claims before giving a PR

Sorry, I do check if someone has written they'd like to work on an issue, but I missed this one from you. Saw just now.

**Comment by shakeabi** [comment]
@catarak I still think it the error should be given with the password input for the reasons stated in #960.
This way we can dynamically indicate the user whether his password matches or not.
