### ISSUE TITLE
Mixed Content/CORS errors are not displayed

### ISSUE THREAD

**Issue by mrseoliveira** [processing/p5.js-web-editor#912]
Hi,

No error message in this code below, but not working. The problem is http API, instead of https.

```
let flightAPI = "http://aviation-edge.com/v2/public/flights?key=d0d178-7e0a13&depIata=OPO";
let geoAPIurl1 = "https://geocode.xyz/"
let geoAPIurl2 = "?json=1&auth=15227473486649212337x1987"
let lat;
let lon;
let geoAPI;

function setup(){
    noCanvas();
    loadJSON(flightAPI, gotData)   
 
}

function gotData(data){
     lat = data[0].geography.latitude;
     lon = data[0].geography.longitude;
     geoAPI = geoAPIurl1+lat +','+lon+geoAPIurl2;
     loadJSON(geoAPI, gotDataGeo)
 }

function gotDataGeo(data){
	console.log('a')
    console.log(data.city);
}
```

**Comment by shakeabi** [comment]
@mrseoliveira I don't think its recommended to use API calls over http as they're generally not secure. 
However many API servers are http based and thus we can have an option to enable http based API calls.
And http API's can be fetched using a **meta tag**. 
LINK: [Why one shouldn't use http based API on HTTPS](https://stackoverflow.com/a/33507729)
LINK: [Optional Solution](https://stackoverflow.com/a/48700852)

**Comment by catarak** [comment]
thanks for reporting! one solution is to use https://cors-anywhere.herokuapp.com/.

but also, yes, there should be a clear error here and there's not. #868 is possibly related.

**Comment by catarak** [comment]
The code in the iframe that is supposed to catch these error ([previewEntry](https://github.com/processing/p5.js-web-editor/blob/master/client/utils/previewEntry.js)) is not catching these errors and writing them to the Web Editor console.
