### ISSUE TITLE
Align in one line

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#914]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
![Capture](https://user-images.githubusercontent.com/28510494/54481065-22381980-4856-11e9-97fd-a99682258f48.PNG)

- Web browser and version:  Edge 
- Operating System: Windows
- Steps to reproduce this bug:

Both the fields should be in one line.

**Comment by AnkurIngale** [comment]
You doing it or can I?

**Comment by plxity** [comment]
![2019-03-18](https://user-images.githubusercontent.com/28510494/54520285-64fd0d00-498e-11e9-8cd5-7a343bf1316c.png)
Check the left corner where the file name is written.
And I am taking this up. :)

**Comment by AnkurIngale** [comment]
<img width="763" alt="Screenshot 2019-03-18 at 5 45 01 PM" src="https://user-images.githubusercontent.com/33569473/54529832-114aed80-49a7-11e9-9196-7aec584a74cb.png">
Totally fine with me.

**Comment by GaurangTandon** [comment]
@plxity facing the same issue. @AnkurIngale what's your screen resolution? And are you at 100% zoom?

**Comment by plxity** [comment]
@AnkurIngale which browser are you using?

**Comment by nik72619c** [comment]
The PR has not solved the issue for Ubuntu. I provided a fix for it here:- 
issue #1273
