### ISSUE TITLE
Link OAuth accounts from user settings page

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#915]
#### Nature of issue?

- Existing feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Chrome
- Steps to reproduce this bug:

#### Feature enhancement details:
As the user is already logged in, It makes no sense to display "Login with github" on the page.

**Comment by plxity** [comment]
@catarak What do you think about this?

**Comment by catarak** [comment]
Rather than "Login with Github" this button should display whether or not a user has linked their Github/Google account to their account.

**Comment by plxity** [comment]
@catarak Okay, I will add the Pull Request for the same. :)

**Comment by plxity** [comment]
@catarak I just wanted to ask, what is the point of displaying that? :)

**Comment by catarak** [comment]
> @catarak I just wanted to ask, what is the point of displaying that? :)

i'm not sure what you're referring to!

**Comment by plxity** [comment]
@catarak I meant, is it necessary to display if they have linked their account to Github/google on settings page?

**Comment by catarak** [comment]
yeah! i think it would be good to give users the ability to link or unlink these accounts.

**Comment by plxity** [comment]
@catarak Okay, I will try to figure out the best approach to implement this. :)
