### ISSUE TITLE
Change color of logo when theme is changed.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#916]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
When the theme is changed to high contrast the logo on extreme top left should also be changed to yellow in color.

**Comment by plxity** [comment]
@catarak What do you think about this?

**Comment by siddhant1** [comment]
I don't think it's that big of a deal

**Comment by plxity** [comment]
@siddhant1 yeah I know, but these are the basic UI changes which builds your app.

**Comment by catarak** [comment]
yes, it should be changed!

**Comment by plxity** [comment]
@catarak Can you please send me the yellow logo? :)

**Comment by catarak** [comment]
it's an SVG so you can use CSS to change the color.

**Comment by plxity** [comment]
@catarak I tried changing color, But it's not happening. Can you help me with this?

**Comment by catarak** [comment]
changing the colors for SVGs is different than colors—you will have to target the svg element (it's `<g>` or `<svg>`), and you will have to use `fill` rather than `color`.

**Comment by plxity** [comment]
@catarak  Yeah, I figured that out. I checked the SVG in illustrator. The layers are not structured properly. Can you just check once?
