### ISSUE TITLE
Navbar not responsive on mobile devices

### ISSUE THREAD

**Issue by Shubhanshu88** [processing/p5.js-web-editor#917]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
On mobile devices , some navbar elements tend to overlap due to which the ui is not displayed as predicted

- Steps to reproduce this bug: Either use mobile view in chrome devtools or open the editor on a mobile device

![IMG_20190317_132647](https://user-images.githubusercontent.com/42772987/54487760-8f33c980-48bf-11e9-824d-367693ca957d.jpg)

**Comment by GaurangTandon** [comment]
Hey, I tried fixing this but soon enough realized that this cannot be fixed reasonably well enough unless we use a collapsing/hamburger navbar at lower widths. 

One simple fix I tried was to remove all padding between the list items, even then the navbar breaks at near ~400px viewport width. Reducing the font size beyond the current set would make the navbar almost invisible though, so there does not seem to be any other option other using a hamburger menu.

Thoughts?

**Comment by siddhant1** [comment]
I think that the whole ui is still not mobile responsive and needs to be done , maybe @catarak can shed some light on this.

**Comment by Shubhanshu88** [comment]
There might be 2 ways to fix this :
1. The current base-font-size maybe decreased accordingly with screen size

2. A certain constant width of Navbar (and hence the whole Editor) has to be fixed below which horizontal overflow is possible and the user can scroll horizontally   (this width might be around 363px for current base font size)

OR Possibly a combination of both OR other ideas can be implemented

**Comment by GaurangTandon** [comment]
Hey @Shubhanshu88, I have questions regarding your fixes:

1. We cannot decrease the font-size beyond a certain limit of readability, so the display will still not be proper on smaller phones (5.5" and below I believe)

2. I am sorry but I have never seen horizontally scrolling navbars in popular websites, and thus they might be very counter-intuitive to new users. Are they common? Can you link to a nice popular implementation on a production website?

Thanks!

**Comment by Shubhanshu88** [comment]
I agree that the font size can be decreased only to certain extent, yet unlike other sites a dropdown for nav items would not be user-friendly.

A Better implementation could be:  
To keep the p5 logo and Log in nav-item on one nav and just below that the other nav-items(file, edit .. ) on another nav. 
This would be much like what Github itself implements for mobile devices.This might work out.

Till then it would be better to wait for further instructions

**Comment by catarak** [comment]
on [Zeplin](https://zpl.io/scene/agQmKD2) there are mobile designs not yet implemented! i'd start from those.

**Comment by Shubhanshu88** [comment]
The above pr makes the nav responsive till almost 380px after which nav width cannot be decreased.

Below 380px, the navbar may be made horizontally scrollable with a fixed width(just like github) or seperate navbars may be made for logo,login and one for other nav items or some other fix, 
@catarak  what would you suggest?

**Comment by catarak** [comment]
i'm honestly not sure at the moment, as i'm not a UI/UX designer. i think the approach is going to be something like
- a few things in the nav menus that are most commonly used will need to be top-level visible
- everything else will be hidden by a hamburger menu on the left, and account stuff on the right of the nav

**Comment by Shubhanshu88** [comment]
@catarak I have added some designs for the navbar and toolbar, would you please review and give your suggestions?
[Link](https://xd.adobe.com/view/233c8b0a-d72f-46f1-62ef-b8593a39016d-550d)

**Comment by catarak** [comment]
@Shubhanshu88 thanks for making those! i will be able to review them in a few days.

**Comment by catarak** [comment]
Fixed, not yet deployed to production.
