### ISSUE TITLE
drag-and-drop uploads

### ISSUE THREAD

**Issue by aparrish** [processing/p5.js-web-editor#92]
My first instinct when uploading files was to just drag them to the sidebar. I don't think I'm alone on this? (Or maybe this functionality exists and it just doesn't work in my browser) It might be nice to support this?

**Comment by catarak** [comment]
This came up again recently, especially in the context of middle and high school students who may not be familiar with file systems--maybe it would make sense to drag files onto the text editor and have them automatically upload to the root directory of the project. 

But also sidebar drag and drop makes sense. The file upload UX is definitely wonky right now (see #271) so I'm open to input.

**Comment by machinic** [comment]
@catarak I'm currently weighing options myself between: 

1: anywhere within the viewport initiates some file detection and handling for appropriate upload and add to the project which I think is the most direct and discoverable experience. 

2: targeted upload zones: sidebar initiates the above whereas drag and drop to the editor would also load the file in a tab (if it were of an acceptable filetype to do that). I like this in that it gives me as the user a bit more control and feels like a pro move, I also have some concerns that it might feel overdone or require more dexterity than necessary (i.e. I can see some asking why do I have to target my drop?). 

This is what I'm thinking about now, I definitely encourage other opinions.

**Comment by lmccart** [comment]
I'm leaning toward option 1... also because by default the sidebar is hidden. So option 1 would enable beginners to be able to drag+drop a file into the project without ever having to open the sidebar if they didn't want to.

**Comment by catarak** [comment]
closing this as it's covered in #375.
