### ISSUE TITLE
Enhancement : Automatically format code when indentation amount is changed.

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#921]
When the indentation is changes , the previous code remains as it is until the user presses shift+tab.
An easy fix would be to call codemirrors tidy function ad componentWillUnmount .

**Comment by siddhant1** [comment]
Hm , sometimes it happens and sometimes it does'nt.

**Comment by catarak** [comment]
yeah, i've noticed some funkiness with this. it's worth investigating the codemirror configuration and seeing if anything needs to change?

**Comment by catarak** [comment]
i just had a thought, with respect to #836 and #941. are those more important than text indentation? i think font size is important, and i use it all of the time, but i have never changed the indentation, nor have i seen anyone do it. or changed it from spaces or tabs. is this something that beginner coders even care about?

**Comment by bmoren** [comment]
@catarak I'd second removing indentation amount from the settings and hard fixing it, it seems like a much lower level feature to font size / softwrap / bracket&quote autocomplete.  I also have never changed indentation. I use font size almost every time I open the editor, especially in a teaching context.

**Comment by catarak** [comment]
i think indentation got included because it was in the original mockups, and is in the p5 desktop editor, so i never questioned it.

**Comment by catarak** [comment]
okay, i made an issue to remove it (#965). i moved #836 up to being a tagged ticket. i'm still on the fence about #941.

**Comment by anku255** [comment]
@catarak Hey! If I am not mistaken then this issue can be closed now. #966 has removed the indentation configuration option.

**Comment by catarak** [comment]
yep!
