### ISSUE TITLE
There is no way of knowing that these switches are on

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#922]
![Screenshot from 2019-03-17 17-59-48](https://user-images.githubusercontent.com/30566406/54490733-7be42680-48de-11e9-94ad-18f95317a281.png)

**Comment by AnkurIngale** [comment]
Which switches are you talking about? The three options below? They turn to yellow on selecting them. Correct me if I am wrong.

**Comment by siddhant1** [comment]
Ah , the css is so weak I can't see it , but it is happening , thanks for responding .

**Comment by GaurangTandon** [comment]
@AnkurIngale hey, where did you find the rules for yellow text color? All I find is  a `#333` grey text color on `[aria-checked="true"]`. I agree with @siddhant1 that it is impossible to know whether the switches are on unless you look into the html markup.

**Comment by AnkurIngale** [comment]
@GaurangTandon he himself said that it's happening. Please look carefully.

**Comment by siddhant1** [comment]
Ikr , it's happening but the contrast is very low and I am waiting for @catarak views on this :)

**Comment by catarak** [comment]
i agree, the difference between on and off here is small. 

maybe, given [this design](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3/screen/59413d86749bc4afbca08994), it should be blue when selected?

**Comment by siddhant1** [comment]
Yes , I will send the fix

**Comment by catarak** [comment]
hmmm, the arrows shouldn't be blue though. they should be the same color as other icons in the theme.

**Comment by shakti97** [comment]
@catarak can you please share the link of the design so that i send a fix for it

**Comment by siddhant1** [comment]
https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3/screen/59413d86749bc4afbca08994

**Comment by catarak** [comment]
Fixed by #1406.
