### ISSUE TITLE
Enhancement :- Give control of ctrl + +/- to the editor and change the font 

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#923]
I think we should give access to ctrl + +/- to the editor.
I can work on it and send a pr :)

**Comment by AnkurIngale** [comment]
That would be much needed. But on chrome, if you do the ctrl + +, it zooms up everything, which is also not too bad 😅

**Comment by catarak** [comment]
what do you think ctrl & +/- should do?

**Comment by siddhant1** [comment]
Increase the font size when the editor is focused

**Comment by catarak** [comment]
i think for accessibility reasons this is not a good idea. sometimes users want to use the +/- keys to increase the font size of the whole web page, that is the expected behavior, and i think it's a bad idea to change this.

**Comment by siddhant1** [comment]
I was thinking of doing this when the editor is focused.

**Comment by catarak** [comment]
@siddhant1 even if the editor is focused, i still don't think it's a good idea.
