### ISSUE TITLE
Unable to type indentation amount and text size.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#924]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
When tried to manually enter Text size, it lands up on 8, 16 or 36. Also, the indentation amount can only be changed by selecting the entire number and typing a new one. Hitting backspace to the existing value automatically sets it to 2 and on typing directly, it sets up to 6.
- Web browser and version: On Chrome
- Operating System: MacOSX
- Steps to reproduce this bug:
For both, just type in the textbox selecting and without selecting.

@catarak @siddhant1   What do you think?

**Comment by AnkurIngale** [comment]
@GaurangTandon I was working on this issue. You should have at least asked before.

**Comment by AnkurIngale** [comment]
And I am working on it :)

**Comment by siddhant1** [comment]
Hey Gaurang , please comment on issues you are working on to maintain the dignity of oss .
Thanks

**Comment by AnkurIngale** [comment]
Yeah, it's totally fine. BUt @GaurangTandon Please comment on the issue you want to solve as someone else might already working on it.

**Comment by GaurangTandon** [comment]
@AnkurIngale @siddhant1 yeah, alright!
