### ISSUE TITLE
Very low contrast ratio for several heading texts in light theme

### ISSUE THREAD

**Issue by GaurangTandon** [processing/p5.js-web-editor#925]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome latest
- Operating System: Ubuntu 18.04
- Steps to reproduce this bug: visit editor.p5js.org

![image](https://user-images.githubusercontent.com/6308683/54494171-85c95200-48fd-11e9-9a9a-bcb555b4b17a.png)

Notice the contrast ratio value. It is much below the acceptable 4.5 AA benchmark set by the WCAG. I personally also found it difficult to view the navbar items easily. The same goes for labels on the signup page, and several other sub-header texts. They could probably use a slightly darker shade of grey color.

**Comment by GaurangTandon** [comment]
PR: #926

**Comment by catarak** [comment]
This is addressed in some design changes on Zeplin that have no yet been integrated. Can you use the colors from there?

**Comment by catarak** [comment]
Fixed by #1406.
