### ISSUE TITLE
Modal/ snackbar should be displayed when settings are saved.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#932]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
Whenever Settings are saved on https://editor.p5js.org/account page, a modal or snack bar should be displayed confirming settings are saved

**Comment by plxity** [comment]
And I am working on it. :)

**Comment by catarak** [comment]
agreed, there should be feedback here!

**Comment by plxity** [comment]
@catarak Should I simply display a  `alert` or Snakbar? I guess alert will do, What do you think?

**Comment by catarak** [comment]
no, don't use an alert! there's a `Toast` component which should be used.
