### ISSUE TITLE
Responsive IDE: Rearranging IDE Panes for Mobile devices

### ISSUE THREAD

**Issue by Shubhanshu88** [processing/p5.js-web-editor#933]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
Some panes of IDE maybe arranged column-wise instead of row-wise specifically for mobile devices for enhancing UI

In future, this feature could also provide a reponsive UI for PWA

**Comment by Shubhanshu88** [comment]
The layout could be similar to that of codepen or w3 schools editor

**Comment by catarak** [comment]
it would be great to start working on this! there's been tons of requests to get this to work on mobile. feel free to add wireframes and/or reference designs.

**Comment by DexterShepherd** [comment]
I'm interested in helping out with this if no one is already working on it.

**Comment by catarak** [comment]
@DexterShepherd go ahead! this is a big issue so feel free to make small, incremental changes.

**Comment by DexterShepherd** [comment]
@catarak Awesome! I saw you mention zeppelin comps in another issue relating to mobile. Are there already mock ups for this somewhere?

**Comment by catarak** [comment]
There are a few, though it's not totally complete. See https://zpl.io/scene/agQmKD2

**Comment by catarak** [comment]
Fixed on develop, not yet deployed to production.
