### ISSUE TITLE
Merge together the exact same console events

### ISSUE THREAD

**Issue by GaurangTandon** [processing/p5.js-web-editor#934]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

Consider the following code:

```
function draw() {
	print("hello");
}
```

Run it and you will get an output similar to this:

```
(12) hello
(5) hello
(6) hello
...
```

Basically, the number of times parameter keeps changing, and a new console event keeps getting logged, even though the console event is literally the same. Therefore, I feel this can be considered as a feature enhancement, to merge together exactly same console events if they are consecutive.

Proposed solution: check if the `messageEvent` in the `handleConsoleEvent` in `PreviewFrame.jsx` is the same as the last one in `this.props.consoleEvents`. If so, simply increment the `times` property of the last event. I will attempt to submit a related PR right now.

**Comment by AnkurIngale** [comment]
I feel the console has divided count on purpose. Correct me if I am wrong.

**Comment by GaurangTandon** [comment]
@AnkurIngale I am not sure why that should be on purpose. Even in the Chrome developer console, subsequent identical logs are clubbed. (try running `setInterval(() => console.log(1), 1000);` with varying time intervals)

**Comment by siddhant1** [comment]
I feel it's done on purpose , not sure why though

**Comment by catarak** [comment]
it's not on purpose!

**Comment by catarak** [comment]
go ahead and work on this!

**Comment by brijsiyag** [comment]
Is this issue still exists?
I am new to open source and contributing first time so is this right issue for me to solve?

**Comment by shubhamkapoor01** [comment]
Hi i'm new to open source contributions, I've given this a shot and added code to check previous console event if it's exactly same as the current one then we don't rewrite it hope it's what you're looking for!
