### ISSUE TITLE
Show the count of search elements found

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#936]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:
![2019-03-18 (1)](https://user-images.githubusercontent.com/28510494/54521558-2c126780-4991-11e9-8a6d-a00b62cb2582.png)
 When seacrhed for some word, count of the results found should be displayed like most of the applications.

#### New feature details:

**Comment by plxity** [comment]
and I am working on this. :)

**Comment by GaurangTandon** [comment]
I went through the [codemirror manual](https://codemirror.net/doc/manual.html). It'd be interesting to see if this feature is already available in Codemirror @plxity . See if you can find something :)

**Comment by plxity** [comment]
@GaurangTandon Okay sure, I'll look into it once. Thanks for the help:)

**Comment by davidbmx** [comment]
Hi, I new contributor and I'd like to help, i see the data search matches for all page in object cm.state.search.annotate.matches.length;

**Comment by catarak** [comment]
go ahead and work on this!

**Comment by davidbmx** [comment]
Hi @catarak, i send pull request for this, #1151
