### ISSUE TITLE
Is Autosave working?

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#937]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
I made a new project. Wrote a line of code. Saved it. Then wrote another line of code. It doesn't save. My question is what is Autosave doing?
- Web browser and version:  On Chrome
- Operating System: MacOSX/Linux along with version -->
- Steps to reproduce this bug:
Do the same as above.

I'll be working on it.

**Comment by catarak** [comment]
hmm, i'm not able to reproduce. i tried from a new sketch and an existing sketch.

**Comment by catarak** [comment]
was your internet connected maybe interrupted?

**Comment by AnkurIngale** [comment]
@catarak   try writing in one sketch. Without saving, open another sketch. Comeback. I did the above steps and no changes were saved. If needed, I'll attach a gif.

**Comment by catarak** [comment]
did you save the first sketch at least once? autosave doesn't get turned on unless you save the sketch at least once after opening it.

**Comment by AnkurIngale** [comment]
I wrote a line of code, saved it, wrote another line of code, left the current project and came back. The latter line is not saved. Is it working for you @catarak ?

**Comment by catarak** [comment]
hmmm, i just tried that and it is working for me. do you have javascript disabled if a tab doesn't have focus?
