### ISSUE TITLE
Icons and labels in find not visible.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#940]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
The next and previous icons (the up and down arrows) are barely visible in contrast mode. In fact, I didn't know there was such a feature.
- Web browser and version:  On Chrome
- Operating System: MacOSX
- Steps to reproduce this bug:

Ill do it.

**Comment by plxity** [comment]
@AnkurIngale Can you a SS of the issue? Thanks.

**Comment by GaurangTandon** [comment]
Something like this @plxity:

![image](https://user-images.githubusercontent.com/6308683/54532914-01370c00-49af-11e9-883d-2c1e9b0867dd.png)

**Comment by siddhant1** [comment]
I think once @catarak shares her views we can work on this together with #922

**Comment by siddhant1** [comment]
@AnkurIngale I will merge this with #922 so you can close this one, many issues make it difficult to reply to everyone .
