### ISSUE TITLE
Autocomplete bracket and quotation mark pairs

### ISSUE THREAD

**Issue by GaurangTandon** [processing/p5.js-web-editor#941]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

I know this has been brought up first in #55. The case was made that beginners might find it confusing. I agree with that. The first impression can certainly be confusing. However, within two-three days of programming, I believe they will realise how nice it would be to have brackets autocomplete themselves :) Not only just brackets, but also double and single quotes.

I believe this can be a useful toggle switch to have in the settings. @catarak thoughts? if you're ok with it, I would wish to work on it!

**Comment by siddhant1** [comment]
I was also thinking of opening an issue for this

**Comment by catarak** [comment]
if this were added as a setting, it would definitely be off by default. i could be convinced that this should be added, but for now, it's not high priority. i'd want some input from beginner coders about their experience.

**Comment by ashu8912** [comment]
Hey @catarak any updates on this one i have local changes that adds this autoComplete bracket and string will push them if required.

**Comment by sagar-joshi** [comment]
I am working on this
