### ISSUE TITLE
Ctrl-G opens "find" dialog instead of "goto line" dialog

### ISSUE THREAD

**Issue by GaurangTandon** [processing/p5.js-web-editor#942]
#### Nature of issue?

- Found a bug

- Web browser and version: Chrome latest
- Operating System: Ubuntu 18.04
- Steps to reproduce this bug:

1. Open editor.p5js.org and press Ctrl-G while inside the code editor.

Expected behavior: goto line dialog box should open. This is the standard implementation across all possible code editors. 
Actual: Find dialog box opens.

I'll start working on this issue. Will see if possibly a code-mirror addon can be integrated, and why Ctrl-G is remapped to Ctrl-F in the first place.

**Comment by siddhant1** [comment]
According to https://codemirror.net/demo/search.html , ctrl+g is mapped for this purpose

**Comment by siddhant1** [comment]
Also chrome follows the same behaviour which makes this issue redudant , Also I feel rather than making issues and making prs , let @catarak present her views.

**Comment by GaurangTandon** [comment]
> According to codemirror.net/demo/search.html , ctrl+g is mapped for this purpose

Hmm, thanks for pointing it out @siddhant1 ! Isn't it very counter-intuitive though? I am coming from a VS Code background, and I believe users of this website's editor will eventually migrate to similar code editors, where behaviour of Ctrl-G is standard.

> Also chrome follows the same behaviour which makes this issue redudant

Sorry but Chrome is not a code editor.

> let @catarak present her views.

Indeed. Initially, I did not know this is by default in Codemirror. I traced the origins of that feature ([relevant issue](https://github.com/codemirror/CodeMirror/issues/3030)) and it doesn't seem like they debated about using Ctrl-G at all, simply ignored the possibility. Would definitely wait for @catarak 's views on this one.

**Comment by AnkurIngale** [comment]
<img width="357" alt="Screenshot 2019-03-18 at 8 20 59 PM" src="https://user-images.githubusercontent.com/33569473/54539015-5ed15580-49bb-11e9-819d-7d6378eb20c8.png">
This is currently what ctrl G does.

**Comment by AnkurIngale** [comment]
Rather I'll say we should have a keyboard shortcut like ctrl L or something for goto line. If needed, I can work this up.

**Comment by catarak** [comment]
the UX here is... odd. it works when i open the find dialog with metaKey + G but doesn't work with metaKey + F? maybe codemirror isn't being configured right?

**Comment by adrijshikhar** [comment]
@catarak is this issue still available?
i would like to take this up
