### ISSUE TITLE
UX issues with the rename/delete dropdown in the file explorer

### ISSUE THREAD

**Issue by GaurangTandon** [processing/p5.js-web-editor#943]
1. The rename/delete buttons are not clickable unless you hover right over them. Common UX interpretation would suggest being able to click in the whitespace on the right side should also work.

![image](https://user-images.githubusercontent.com/6308683/54534753-0dbd6380-49b3-11e9-9830-cb6fd95a543f.png)

2. Being able to press Escape inside an input to abandon all changes and quit is a common UX practice. However, this has not been implemented in the rename file input box.

I will attempt to submit a PR to address these.

**Comment by catarak** [comment]
thanks for reporting, and I agree, this is annoying!

**Comment by progfay** [comment]
I found the difference of pulldown menus design between `.nav__dropdown` and `.sidebar__file-item-options`

### `.nav__dropdown`

[![Image from Gyazo](https://i.gyazo.com/3df882e6133a02e67afd79c324c26dc1.png)](https://gyazo.com/3df882e6133a02e67afd79c324c26dc1)


### `.sidebar__file-item-options`

[![Screenshot from Gyazo](https://gyazo.com/9d23319df2ece56e26f6e85f6c55e261/raw)](https://gyazo.com/9d23319df2ece56e26f6e85f6c55e261)

I think `.sidebar__file-item-options` dropdown is difficult to operation.
I wanna change `.sidebar__file-item-options` design like `.nav__dropdown` .

**Comment by progfay** [comment]
Wow, I found #886 and it will be solved by #887 .
