### ISSUE TITLE
"Add folder" button creates a folder which opens to the side in the code editor

### ISSUE THREAD

**Issue by GaurangTandon** [processing/p5.js-web-editor#945]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome latest
- Operating System: Ubuntu 18.04
- Steps to reproduce this bug:

1. Open a new sketch and click the dropdown for "project-folder"
2. Click Add folder and add a new folder.
3. Click on the newly folder in the explorer.

Result: folder is editable in the code editor!

![image](https://user-images.githubusercontent.com/6308683/54535125-dc916300-49b3-11e9-8366-3d5bf5bf1c33.png)

This behaviour is definitely confusing me. What should be the result of editing a folder in this manner be? 

Is this is a bug?  I think it is, but I'll wait for @catarak to confirm.
And if it is a bug, I'd like to work on it. Thanks!

PS: A relatively minor related issue is that a newly added folder has - as its icon - a solid down arrow instead of the folder icon it is supposed to have.

**Comment by AnkurIngale** [comment]
It might be a bug but it's a good way to document things up in that folder 😅

**Comment by catarak** [comment]
this is related to #645. for folders, long files, and assets, the code editor should be replaced with something else 😄

**Comment by dinolinjob** [comment]
I'm Dinolin yp job, I would like to work on this issue.

**Comment by GaurangTandon** [comment]
@catarak What do you think should it display? Would a simple "Sorry, the file type is unsupported in our editor." suffice? I can work to incorporate it.

**Comment by AnkurIngale** [comment]
Yeah it's a bug. But honestly speaking, it's good. I mean I can document things of that folder there. No need to create text files. Maybe it's just me being lazy 😅

**Comment by catarak** [comment]
it shouldn't be an error. one solution would be that folders can't be selected, and when you click on them, it simply opens/closes the folder.
