### ISSUE TITLE
No condition for checking if only username or password is provided or if neither is provided

### ISSUE THREAD

**Issue by abhinavsagar** [processing/p5.js-web-editor#951]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome
- Operating System: Windows 10
- Steps to reproduce this bug: Inappropriate action when user just types username and forgets to type password or vice versa or neither of the two.

If a user forgets to type in any of the two ie username or password then no action is happening. Rather user should be made aware of the fact that he has missed to type username or password or both.

**Comment by catarak** [comment]
thanks for reporting! i unfortunately don't understand what the issue is you are trying to report. can you list steps to reproduce, or explain it another way?
