### ISSUE TITLE
Preview iframe boundaries not visible: add border to iframe only when play starts 

### ISSUE THREAD

**Issue by Shubhanshu88** [processing/p5.js-web-editor#953]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
When developing certain sketches, the user may not find a clear distinction between the iframe section and rest of the editor background.This can cause problems in case of interaction sketches if boundaries are not visible.
 
The proposed solution is to display a border similar to code editor pane when play starts.
On stopping, the iframe is configured to stop displaying the border.

**Comment by Shubhanshu88** [comment]
This issue is visible in flocking example sketch in dark theme, the background and iframe cannot be distinguished easily

**Comment by catarak** [comment]
thanks for suggesting! i think this would cause more harm than good. i think this is an issue with the specific sketches, rather than the web editor. a user can simply update the CSS if they would like the canvas to have a border.
