### ISSUE TITLE
Enhancement: Unresponsive UI of the editor

### ISSUE THREAD

**Issue by nik72619c** [processing/p5.js-web-editor#955]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
The Code Editor is un-responsive for mobile views.

**Comment by nik72619c** [comment]
![Capture](https://user-images.githubusercontent.com/30630904/54630467-ec867100-4a9f-11e9-8252-845df41bbce1.PNG)

**Comment by nik72619c** [comment]
please tell if I can make a PR on this one

**Comment by catarak** [comment]
what change are you suggesting?

**Comment by nik72619c** [comment]
The particular aspect I am pointing out to is the arrangement of UI according to the viewport but since you mentioned that work is going on for mobile-friendly views, I can help write media queries for the same :)

**Comment by catarak** [comment]
okay! can you update this issue title/description with the specific thing you are proposing to change?
