### ISSUE TITLE
Unsaved file circle disappears on opening assets but file remains unsaved and changes still present.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#956]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
The circle which displays if the file is unsaved disappears on opening My assets( or anything which prompts that you have unsaved files). According to me, the unsaved changes should either disappear or the circle should still be present because it's still not saved. Look into gif for better understanding.
![ezgif-3-41c5130a6add](https://user-images.githubusercontent.com/33569473/54636531-abe12480-4aac-11e9-978c-1f5c1a14c4f7.gif)

- Web browser and version:  On Chrome
- Operating System: MacOSX
- Steps to reproduce this bug:

If this is an issue, I'll resolve it.
Views @siddhant1 @catarak @GaurangTandon @plxity ?

**Comment by siddhant1** [comment]
Hm, The dialog box says that you have unsaved changes and if you click yes the changes will be lost , so that's expected that changes will not be saved . Am i missing something?

**Comment by AnkurIngale** [comment]
I agree with you @siddhant1 . But the changes aren't lost, they are still present, just not saved. My belief is we can either continue to display the unsave circle or remove the changes made.

**Comment by siddhant1** [comment]
Yes they are not saved and they won't be reflected in the shareable url (if you open in another browser) the changes are lost

**Comment by catarak** [comment]
yeah, this is a strange edge case. i think the issue is that the dialog shouldn't appear if you've opened one of the overlays, it should only open if you close the page or open a new sketch.

**Comment by catarak** [comment]
Testing this again, it seems like it's been fixed.
