### ISSUE TITLE
Need to double-click data folder to add files

### ISSUE THREAD

**Issue by awarua** [processing/p5.js-web-editor#963]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Chrome

- Operating System: Windows

- Steps to reproduce this bug:
* Add a 'data' folder to the project folder
* Click on the down-arrow next to the folder to 'add file'
* Choose the file (e.g. an image) to upload.
* It will upload, but will not be inside the folder.

You need to double-click the folder in order to upload it.

**Comment by catarak** [comment]
thanks for reporting! i can reproduce.

**Comment by siddhant1** [comment]
I will fix this soon
