### ISSUE TITLE
Remove indentation options from user preferences

### ISSUE THREAD

**Issue by catarak** [processing/p5.js-web-editor#965]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:

4.3% of registered users have changed the indentation amount. 3% have changed space indentation to tab indentation. This seems pretty small. Since one goal of this project is to keep configuration options down, let's get rid of this and use a smart default. Since the airbnb eslint configuration uses "two spaces", I say we stick with that.

**Comment by qualitymanifest** [comment]
I'll take a crack at this, it looks like it mainly just involves reverting most of the changes from this PR https://github.com/processing/p5.js-web-editor/pull/9/files
