### ISSUE TITLE
update "preview sound" button to match design

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#969]
#### Nature of issue?

- Feature enhancement

#### Details about the bug: 

- Web browser and version: Chrome
- Operating System: Windows
- Steps to reproduce this bug:

#### Feature enhancement details:

![Capture](https://user-images.githubusercontent.com/28510494/54810395-05fc0880-4cac-11e9-9419-bb104fd78e2a.PNG)
 ' Preview sound ' is actually a button and proper border  should be present to make its UI better & to make it look like a button.
#### New feature details:

**Comment by catarak** [comment]
i don't think it needs a border. in the [design](https://scene.zeplin.io/project/55f746c54a02e1e50e0632c3/screen/595987f3dfe43c83d043bcf7) it is simply a different color and i think that is enough.

**Comment by plxity** [comment]
@catarak Okay, I will add a PR for the same.
