### ISSUE TITLE
Responsiveness for Log in screen: Currently, elements not working as intended

### ISSUE THREAD

**Issue by Shubhanshu88** [processing/p5.js-web-editor#972]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Steps to reproduce this bug:
    - Open Log in screen on any mobile device (either portrait or landscape view or both)

         - The buttons do not behave as intended (decreased height, even shorter than logo),
         - Also below certain width the "Log In" form heading is not properly aligned vertically (in few cases, not even visible on screen)
         - In portrait view, the username and password input boxes have 100% width, leaving no padding

![issue_login_p5](https://user-images.githubusercontent.com/42772987/54829323-2a6fd900-4cdc-11e9-8c51-512670a19da8.png)

**Comment by Shubhanshu88** [comment]
The solution may be to fix the form width so that the form heading does not shift beyond screen height

**Comment by catarak** [comment]
yep, go ahead and work on this!

**Comment by tanhengyeow** [comment]
Hi @catarak !

It seems like this issue hasn't been worked on for some time. Can I work on it? 😄

**Comment by catarak** [comment]
@tanhengyeow absolutely!
