### ISSUE TITLE
Direct navigation to Log In screen does not render elements properly

### ISSUE THREAD

**Issue by Shubhanshu88** [processing/p5.js-web-editor#974]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

When user navigates directly to Log in screen without initially going to the editor screen, the github and google buttons are not displayed as intended

- Steps to reproduce this bug:
    - Navigate directly to https://editor.p5js.org/login without opening https://editor.p5js.org

**Comment by Shubhanshu88** [comment]
In this case, the buttons do not contain theme classes and placeholders are not imported.

A possible solution may be to hard code css properties.

**Comment by catarak** [comment]
thanks for reporting! i think a better solution would be to figure out how to import the theme classes properly.

**Comment by progfay** [comment]
I found same bug on https://editor.p5js.org/account (navigate directly)

[![Screenshot from Gyazo](https://gyazo.com/6c095d38db02730e3861bef9ac4d6562/raw)](https://gyazo.com/6c095d38db02730e3861bef9ac4d6562)

**Comment by progfay** [comment]
In my research, no `<style>` difference between `/` and `/login` .
I suggest there is not provide Theme className for `/login` .
And, `.light .github-button` style does not appied for '.github-button' in '/login' .

**Comment by catarak** [comment]
@progfay thanks for investigating!
