### ISSUE TITLE
Refactor all HTTP requests to use axios

### ISSUE THREAD

**Issue by siddhant1** [processing/p5.js-web-editor#975]
As I was working on #521 , we use a package named 'request' which only supports callbacks.
I think we should switch to request-promise alternative.
LInks :- https://github.com/petkaantonov/bluebird
https://github.com/request/request-promise-native

@meiamsome @catarak Should I switch it up?

**Comment by catarak** [comment]
`request-promise` is already a dependency, so feel free to refactor accordingly.

**Comment by siddhant1** [comment]
Cool , I will have a look

**Comment by catarak** [comment]
There are a bunch of different request libraries used in this project (`request`, `request-promise`, `axios`). Since `axios` works both client-side and server-side, this project should just use it.

**Comment by SundeepChand** [comment]
Hello @catarak, can I work on this?

**Comment by catarak** [comment]
@SundeepChand absolutely! I also think this is a good fit for you since it touches a few files and you're familiar with the codebase.

**Comment by SundeepChand** [comment]
@catarak, where can I find the `Personal Access Token` to make requests to the public API? And how can I get `EDITOR_API_ACCESS_TOKEN` to run  `fetch-examples-ml5.js`

**Comment by catarak** [comment]
> @catarak, where can I find the `Personal Access Token` to make requests to the public API? And how can I get `EDITOR_API_ACCESS_TOKEN` to run `fetch-examples-ml5.js`

@SundeepChand ahh sorry that is confusing! the idea is that eventually, users (such as ml5) will be able to generate their own access tokens to upload sketches programatically. the way you would generate this token is to create an `ml5` account on your local database, login as that user, then go to settings > access tokens, and then generate a token.

**Comment by SundeepChand** [comment]
Thanks @catarak! I was able to create a token and was able to run `fetch-examples-ml5.js`, but its giving some errors that has to be fixed. PS: Finally I've figured out cause of the error, will be updating the PR soon.
