### ISSUE TITLE
Missing p5.js keyword/function highlights

### ISSUE THREAD

**Issue by Janglee123** [processing/p5.js-web-editor#978]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

After marking that the new `circle` and `square`  are not highlighting like other p5 functions. I have generated a list of functions that not highlighted by the editor.

Here you go:
https://editor.p5js.org/Janglee123/sketches/z5DUgwwjy

**Comment by siddhant1** [comment]
Can you attach a ss , for me they are working completely fine.

**Comment by Janglee123** [comment]
NO, they don't, just checkout  #983

**Comment by AnkurIngale** [comment]
Yeah I have noticed it in #983 and will be working on it.

**Comment by catarak** [comment]
i can reproduce! this project forks the CodeMirror JS syntax highlighting file, which needs to be updated to include the new p5.js keywords.

**Comment by catarak** [comment]
The file that needs to be updated is https://github.com/processing/p5.js-web-editor/blob/master/client/utils/p5-javascript.js

**Comment by Spongman** [comment]
i know this would be a huge change, but i wonder if switching to the [Monaco editor](https://microsoft.github.io/monaco-editor/index.html) and using the [p5.d.ts](https://github.com/p5-types/p5.ts) wouldn't give a significantly better editing & completion experience?

similar to this:

![image](https://user-images.githubusercontent.com/1088194/55506193-abe33780-5609-11e9-8444-f7b20c6030b0.png)

**Comment by catarak** [comment]
unfortunately the Monaco editor doesn't have mobile support! and i also don't know how accessible it is. i imagine the typings could be used for autocomplete in the codemirror editor, however.

**Comment by Spongman** [comment]
here's the [Monaco Editor Accessibility Guide](https://github.com/Microsoft/monaco-editor/wiki/Monaco-Editor-Accessibility-Guide).

not sure about mobile support, it works fine on my android tablet and iPhone.
