### ISSUE TITLE
"duplicate" confusion

### ISSUE THREAD

**Issue by shiffman** [processing/p5.js-web-editor#98]
A lot of this may be resolved with the upcoming design review, but I'm making a note here that the term "duplicate" caused some confusion.   What it is meant to do / does was not completely clear to students.   I'm not sure if "Save As" would resolve all the questions, but it's something we could consider.

**Comment by zhuoxi** [comment]
Though "duplicate" mimics the Mac right-click menu, "Save as new" or even geekier, "fork" (as used by codepen.io) might sound clearer?

**Comment by lmccart** [comment]
copy?

**Comment by shiffman** [comment]
I think whatever we choose, we'll probably want to prompt the user to rename the sketch, just as happens with usual "save as" behavior.   This is a cue to the user as to what is happening. . otherwise it's not obvious that the project ID in the URL address bar is changing.
