### ISSUE TITLE
Drop-down arrow pertaining to 'My Account' should be clickable

### ISSUE THREAD

**Issue by pranavtharoor** [processing/p5.js-web-editor#981]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome | 73.0.3683.75 (Official Build) (64-bit)
- Operating System: Ubuntu 16.04.1 LTS
- Steps to reproduce this bug: Click the arrow on the drop-down pertaining to 'My Account'

![p5js-cropped](https://user-images.githubusercontent.com/22600061/54875484-454e6480-4e26-11e9-9814-eb1f9ea7a006.png)

The triangle icon should be a part of the 'My Account' button. Currently, on clicking the icon area nothing happens (only for the 'My Account' drop-down). Intuitively, the drop down should open when the icon is clicked.

**Comment by pranavtharoor** [comment]
I would like to submit a PR for this

**Comment by siddhant1** [comment]
Will be solved by #900

**Comment by catarak** [comment]
i just tested this, and it is not fixed by #900 at the moment.

**Comment by catarak** [comment]
fixed by #982
