### ISSUE TITLE
Cannot exit log in and sign up pages on opening sign up page from log in page.

### ISSUE THREAD

**Issue by AnkurIngale** [processing/p5.js-web-editor#985]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
Opened log in page, from there I opened sign up page. Now when I click on 'X' (exit), it brings me back to log in. Again clicking on exit brings me back to Sign up. And this continues.
- Web browser and version:  On Chrome
- Operating System: MacOSX
- Steps to reproduce this bug:
Do as above.

@catarak views? Obviously, I won't be playing around here. Normally, I should fill up and submit one of the two. But this is annoying.

**Comment by siddhant1** [comment]
Hm , looks like some kind of bug , will try to reproduce

**Comment by catarak** [comment]
thanks for reporting! this is a bug and i can reproduce.

**Comment by Marton6** [comment]
I would like to fix this.

**Comment by AnkurIngale** [comment]
@Marton6 Make sure you get the permission before doing it. Thanks btw.

**Comment by Marton6** [comment]
@AnkurIngale I'm sorry, will pay attention to this in the future. Thanks for pointing it out!

**Comment by catarak** [comment]
@Marton6 / @AnkurIngale unless an issue has been claimed, you can assume it's open and available to work on! no need to as permission.

**Comment by catarak** [comment]
Fixed by the merge of #1340
