### ISSUE TITLE
Feature: Clicking on username appearing in navigation bar should direct the user to Settings page.

### ISSUE THREAD

**Issue by plxity** [processing/p5.js-web-editor#986]
#### Nature of issue?

- New feature request

#### Details about the bug: 

- Web browser and version: 
- Operating System: 
- Steps to reproduce this bug:

#### Feature enhancement details:

Clicking on the username in the navbar should redirect the user to account settings page.
In most of the web apps, there is a feature like this. So, I think implementing this would be a great option.  @catarak What do you suggest? :)

#### New feature details:

**Comment by catarak** [comment]
i think it makes sense to leave it as it is now. in the future, it would be nice to have individual profile pages for users, so if anything, i think the username should link to that.

**Comment by plxity** [comment]
@catarak Okay no issues:)
