### ISSUE TITLE
Multiple File Options

### ISSUE THREAD

**Issue by nimishagarwal76** [processing/p5.js-web-editor#987]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

Latest Merge ```Fixed Issue #659 (#964)``` causes multiple menus to remain open.
![Screenshot (1)](https://user-images.githubusercontent.com/37630020/54921104-ef171980-4f2a-11e9-8650-6df203cfad4f.png)

#876 removed the issue but it comes again now.

**Comment by Marton6** [comment]
Hello! I would like to work on this issue.
