### ISSUE TITLE
Folder can be renamed to "" empty string

### ISSUE THREAD

**Issue by Marton6** [processing/p5.js-web-editor#989]
#### Nature of issue?

- Found a bug

#### Details about the bug: 
It is possible to clear the name of a folder by renaming it to "" and files can be renamed to only contain a valid extension (".js", ".css" etc.).
Moreover two or more folders with an empty name ("") can be contained in the same folder which will probably cause issues.

- Web browser and version: Chrome 71.0.3578.98
- Operating System: Windows and Linux
- Steps to reproduce this bug: 
    1. Create a folder with a proper name.
    2. Click rename in the file navigator.
    3. Clear the name of the folder and click outside of it. 

![Screenshot_20190325_220842](https://user-images.githubusercontent.com/13394704/54954293-9788a600-4f4a-11e9-984b-b190b035e34b.png)

**Comment by siddhant1** [comment]
Looks like a bug to me , will fix this soon!

**Comment by catarak** [comment]
thanks for reporting! this is a bug and i can reproduce.

**Comment by siddhant1** [comment]
@catarak I think just adding a length cap might work?

**Comment by siddhant1** [comment]
I think as discussed on https://github.com/processing/p5.js-web-editor/pull/962#issuecomment-475330642 we should also add some validations at the backend and s3

**Comment by catarak** [comment]
i think there should be frontend and backend validations.

**Comment by olalekanteeblaze** [comment]
I'm a first time contributor, is this still open for me to work on?

**Comment by siddhant1** [comment]
Hey sure , go for it ! What you need to do an to counter this one.
1. Add backend model level validations for folder name
2. Add a front end validation or some sort of min length validation
3.  I think we have some prs already doing the 1 , you can pick up (2).
 
If you have any doubt , most people here will be happy to help(or just tag me).
Congratulations of your first oss project.
Cheers!
