### ISSUE TITLE
Inconsistency between the results and the code

### ISSUE THREAD

**Issue by ZiyaoWei** [processing/p5.js-web-editor#990]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Web browser and version: Google Chrome 72.0.3626.121 (Official Build) (64-bit)
- Operating System: Mac OS X 10.13
- Steps to reproduce this bug:

1) Copy the following into the editor:
```
function setup() {
}
 
function draw() {
	console.log(1);
}
```
2) Run the code, verify logging works;
3) Do this as fast as possible: comment the line `console.log(1);` and run the code again;
BUG: 1s still get logged!
4) wait 1 second;
5) Do this as fast as possible: uncomment the same line and run the code again;
BUG: 1s no longer get logged although `console.log(1);` is uncommented!

My guess is that somehow the code editing/interpretation happens asynchronously and won't take effect until after a split second, thus when events happen at roughly the same time the orders got reversed.

Not sure if this is considered a bug but if so, I would be happy to help put up a fix, although cannot promise when that would happen.

**Comment by catarak** [comment]
thanks for reporting! i can reproduce. i recently added a [commit](https://github.com/processing/p5.js-web-editor/commit/2cc0d578fbc24ca7ce9e12f7bd26d28fb4ad28ce) that helps with fixing this issue.

**Comment by ZiyaoWei** [comment]
Cool, thanks! Just to clarify - since 2cc0d578fbc is already merged into master, this still needs a fix?

**Comment by catarak** [comment]
yeah, it still needs to be fixed! i changed it so that when you save a sketch, it pulls from the CodeMirror context, rather than the redux store, and i think the same thing could be done when running a sketch.
