### ISSUE TITLE
Migrate to server-side rendering

### ISSUE THREAD

**Issue by nik72619c** [processing/p5.js-web-editor#994]
#### Nature of issue?

- Existing feature enhancement

#### Feature enhancement details:
The current version of the editor is client side rendered. Server side rendering of the application not only boosts performance and startup time for the app but also provides search engine optimisation.

**Comment by nik72619c** [comment]
@catarak please give your thoughts on this

**Comment by catarak** [comment]
yeah, this would be nice! i've never done server-side rendering before so i don't know where to start with this.

**Comment by nik72619c** [comment]
Not an issue, will make a pr on this

**Comment by ashu8912** [comment]
@catarak any progresses on this one?

**Comment by catarak** [comment]
I'm sure it's a lot of work to move to `Next.js` but I imagine it would really help with load time.
